// Lecturas · Texto científico (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["cientifico"] = [
  {
    id: "cientifico-01-ciclo-agua",
    titulo: "El viaje sin fin del agua",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["USGS (Servicio Geológico de Estados Unidos), Water Science School: «Where is Earth's Water?» y «How Much Water is There on Earth?»"],
    antes: "¿Crees que el agua que bebes hoy pudo ser antes nieve, nube o mar? ¿Por qué?",
    texto: [
      { h: "Siempre la misma agua" },
      { p: "El agua de la Tierra no se gasta ni se fabrica de nuevo: se mueve sin parar de un lugar a otro y cambia de estado. Los científicos llaman a este recorrido ciclo del agua o ciclo hidrológico. Gracias a él, el agua que hoy sale de tu grifo pudo formar parte, hace miles de años, de un glaciar, de una nube o de un océano." },
      { h: "Las etapas del ciclo" },
      { p: "Todo empieza con la energía del Sol. Cuando calienta los mares, los ríos y los lagos, una parte del agua líquida se convierte en vapor y sube a la atmósfera. Este proceso se llama evaporación. Las plantas también expulsan vapor de agua por sus hojas: es la transpiración." },
      { p: "A medida que asciende, el vapor se enfría y se transforma en gotitas diminutas que forman las nubes. Es la condensación. Cuando las gotas se unen y pesan demasiado, caen en forma de lluvia, nieve o granizo: es la precipitación." },
      { p: "El agua que llega al suelo puede seguir dos caminos. Una parte corre por la superficie hacia arroyos y ríos, y acaba en el mar; esto se conoce como escorrentía. Otra parte se filtra en la tierra, lo que se llama infiltración, y forma depósitos de agua subterránea: los acuíferos. Tarde o temprano, el Sol vuelve a evaporarla y el ciclo comienza otra vez." },
      { h: "¿Cuánta agua dulce hay?" },
      { p: "Aunque nuestro planeta se ve azul desde el espacio, casi toda su agua es salada. Según el Servicio Geológico de Estados Unidos (USGS), más del 96 % del agua de la Tierra está en los océanos. Solo alrededor de un 3 % es agua dulce, y la mayor parte de ella está congelada en glaciares y casquetes polares o escondida bajo tierra. El agua de ríos y lagos que usamos cada día es una parte muy pequeña del total." },
      { h: "Conclusión" },
      { p: "El ciclo del agua reparte y renueva el agua del planeta de forma natural. Sin embargo, el agua dulce disponible es escasa, sobre todo en regiones con pocas lluvias, como gran parte de Andalucía. Por eso es tan importante no contaminarla y no malgastarla." },
      { dato: "¿Sabías que la nieve de las montañas funciona como una despensa de agua? Al derretirse en primavera, alimenta los ríos y los embalses." },
    ],
    vocabulario: [
      { p: "atmósfera", d: "Capa de gases que rodea la Tierra." },
      { p: "glaciar", d: "Gran masa de hielo que se forma en las montañas altas o en las zonas polares." },
      { p: "acuífero", d: "Depósito de agua que se acumula bajo tierra, entre las rocas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué fuente de energía pone en marcha el ciclo del agua?", r: "El Sol, que calienta el agua de mares, ríos y lagos y la evapora.", lineas: 1 },
      { tipo: "comprension", q: "¿Cómo se llama el paso del vapor de agua a las gotitas que forman las nubes? Elige:", opciones: ["Evaporación", "Condensación", "Infiltración"], r: "Condensación" },
      { tipo: "comprension", q: "Explica con tus palabras la diferencia entre escorrentía e infiltración.", r: "En la escorrentía el agua corre por la superficie hacia arroyos, ríos y el mar; en la infiltración se filtra en el suelo y forma acuíferos.", lineas: 2 },
      { tipo: "comprension", q: "Si en la Tierra hay tanta agua, ¿por qué dice el texto que el agua dulce es escasa?", r: "Porque casi toda es salada (más del 96 %), y de la poca agua dulce que hay, la mayor parte está helada o bajo tierra. La que podemos usar con facilidad es muy poca.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el autor menciona Andalucía en la conclusión?", r: "Porque es una región con pocas lluvias donde el agua dulce escasea; así el lector entiende que el problema le afecta de cerca.", lineas: 2 },
      { tipo: "texto", q: "Los textos científicos usan tecnicismos. Copia tres palabras técnicas del texto. ¿En qué parte (introducción, desarrollo o conclusión) aparece el dato del USGS?", r: "Por ejemplo: ciclo hidrológico, evaporación, transpiración, condensación, precipitación, escorrentía, infiltración, acuífero. El dato del USGS aparece en el desarrollo.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué dos cosas podrías hacer en casa o en el colegio para no malgastar agua? ¿Por qué son útiles?", r: "Respuesta libre. Valorar que propongan acciones concretas (cerrar el grifo, duchas cortas, reutilizar agua…) y expliquen su efecto.", lineas: 3 },
      { tipo: "opinion", q: "¿Te resulta más fácil aprender el ciclo del agua con un texto como este o con un dibujo? Explica por qué.", r: "Respuesta libre. Valorar que argumenten su preferencia.", lineas: 2 },
      { tipo: "reflexion", q: "En algunos lugares del mundo conseguir agua potable cuesta horas de camino cada día. ¿Cómo cambiaría tu vida si te pasara a ti?", r: "Respuesta libre. Valorar la empatía y la relación con el valor del agua.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-02-abejas",
    titulo: "Las abejas, pequeñas jardineras del planeta",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["FAO (Organización de las Naciones Unidas para la Alimentación y la Agricultura): Día Mundial de las Abejas y datos sobre polinizadores"],
    antes: "¿Qué sabes de las abejas, además de que fabrican miel? ¿Crees que son importantes para nosotros?",
    texto: [
      { p: "Cuando pensamos en abejas, solemos acordarnos de la miel o de sus picaduras. Sin embargo, su trabajo más importante es otro: la polinización. Sin ella, muchas de las frutas y verduras que comemos no existirían." },
      { h: "¿Qué es la polinización?" },
      { p: "Las flores producen un polvo muy fino llamado polen. Para que una planta forme frutos y semillas, el polen tiene que viajar desde la parte masculina de una flor, los estambres, hasta la parte femenina, el pistilo, de la misma flor o de otra de su especie. Como las plantas no pueden moverse, necesitan ayuda: el viento, el agua o los animales polinizadores." },
      { p: "Las abejas visitan las flores para alimentarse de néctar, un líquido azucarado, y para recoger polen para sus crías. Mientras lo hacen, los granos de polen se pegan a los pelillos de su cuerpo y pasan de una flor a otra. Así, sin saberlo, hacen posible la fecundación de las plantas." },
      { h: "Muchas más abejas de las que imaginamos" },
      { p: "La abeja de la miel vive en colmenas muy organizadas, con una reina, obreras y zánganos, pero no es la única. Según la FAO, la organización de las Naciones Unidas para la alimentación, en el mundo hay unas 20.000 especies de abejas. Muchas son solitarias y viven en pequeños agujeros en la tierra o en la madera." },
      { p: "La FAO calcula que tres de cada cuatro cultivos que producen frutos o semillas para la alimentación humana dependen, al menos en parte, de los polinizadores. Entre ellos están los almendros, los manzanos, los melones o las fresas." },
      { h: "Un trabajo en peligro" },
      { p: "En las últimas décadas, las poblaciones de abejas y de otros polinizadores han disminuido en muchos lugares. Entre las causas, los expertos señalan el uso de plaguicidas, la pérdida de flores silvestres, las especies invasoras y los cambios en el clima." },
      { h: "Conclusión" },
      { p: "Las abejas son esenciales para la naturaleza y para nuestra alimentación. Por eso la ONU declaró el 20 de mayo Día Mundial de las Abejas. Plantar flores, respetar a los insectos y no usar venenos en jardines y huertos son pequeñas acciones que ayudan a protegerlas." },
      { dato: "¿Sabías que las abejas de la miel se comunican con una especie de baile? Con sus movimientos indican a sus compañeras dónde hay flores." },
    ],
    vocabulario: [
      { p: "polinizador", d: "Animal que transporta el polen de una flor a otra." },
      { p: "zángano", d: "Macho de la abeja de la miel." },
      { p: "plaguicida", d: "Producto químico que se usa para eliminar insectos u otras plagas." },
      { p: "cultivo", d: "Planta que se siembra y se cuida para obtener alimentos u otros productos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Según el texto, ¿cuál es el trabajo más importante de las abejas?", r: "La polinización.", lineas: 1 },
      { tipo: "comprension", q: "¿Para qué visitan las abejas las flores? Elige:", opciones: ["Para ayudar a las plantas a tener frutos", "Para alimentarse de néctar y recoger polen", "Para construir sus colmenas"], r: "Para alimentarse de néctar y recoger polen" },
      { tipo: "comprension", q: "Explica cómo pasa el polen de una flor a otra gracias a las abejas.", r: "Cuando la abeja busca néctar, el polen se pega a los pelillos de su cuerpo y lo deja en la siguiente flor que visita.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el texto con la expresión «sin saberlo»?", r: "Que las abejas no polinizan a propósito para ayudar a la planta: solo buscan comida, y la polinización es una consecuencia de ello.", lineas: 2 },
      { tipo: "comprension", q: "Si desaparecieran muchas abejas, ¿qué pasaría en una frutería? Razónalo con un dato del texto.", r: "Habría menos fruta y probablemente más cara, porque tres de cada cuatro cultivos que dan frutos o semillas dependen en parte de los polinizadores.", lineas: 2 },
      { tipo: "texto", q: "Un texto científico es objetivo: no da opiniones personales y apoya lo que dice en datos. Copia un dato numérico y di de qué fuente procede. ¿Por qué es importante citar la fuente?", r: "Por ejemplo: unas 20.000 especies de abejas, o tres de cada cuatro cultivos; procede de la FAO. Citar la fuente permite comprobar que el dato es fiable.", lineas: 3 },
      { tipo: "opinion", q: "¿Te importaría que hubiera colmenas cerca de tu colegio? Da un argumento a favor y otro en contra.", r: "Respuesta libre. Valorar que den argumentos de ambos lados.", lineas: 3 },
      { tipo: "opinion", q: "¿Cuál de las acciones de la conclusión podrías hacer tú? ¿Por qué la eliges?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Muchos seres pequeños, como las abejas o las lombrices, hacen trabajos enormes que no vemos. ¿Pasa lo mismo con algunas personas de tu entorno? Pon un ejemplo.", r: "Respuesta libre. Valorar que reconozcan trabajos poco visibles (limpieza, cuidados, mantenimiento…).", lineas: 3 },
    ],
  },
  {
    id: "cientifico-03-corazon",
    titulo: "El corazón, un motor que no descansa",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["National Heart, Lung, and Blood Institute (NHLBI, Institutos Nacionales de Salud de EE. UU.): «How the Heart Works»"],
    antes: "Pon la mano en el pecho. ¿Qué notas? ¿Sabes para qué sirve ese movimiento?",
    texto: [
      { p: "Pon la mano en el lado izquierdo de tu pecho y quédate quieto unos segundos. Ese golpeteo rítmico es tu corazón, un órgano que trabaja día y noche desde antes de que nacieras." },
      { h: "¿Cómo es?" },
      { p: "El corazón es un músculo hueco, más o menos del tamaño de un puño, situado en el centro del pecho, entre los dos pulmones y un poco inclinado hacia la izquierda. Por dentro está dividido en cuatro cavidades: dos superiores, llamadas aurículas, y dos inferiores, llamadas ventrículos. Unas válvulas, que funcionan como puertas que solo se abren en un sentido, impiden que la sangre retroceda." },
      { h: "¿Cómo funciona?" },
      { p: "El corazón actúa como una bomba doble. La parte derecha recibe la sangre que vuelve del cuerpo cargada de dióxido de carbono y la envía a los pulmones. Allí la sangre suelta ese gas y se carga de oxígeno. Después regresa a la parte izquierda del corazón, que la impulsa con fuerza hacia todo el organismo a través de las arterias. Las venas se encargan de devolverla al corazón. Este recorrido completo se llama circulación sanguínea." },
      { p: "Cada latido tiene dos fases: la sístole, cuando el músculo se contrae y expulsa la sangre, y la diástole, cuando se relaja y se vuelve a llenar. Según el Instituto Nacional del Corazón, los Pulmones y la Sangre de Estados Unidos (NHLBI), el corazón late unas 100.000 veces al día." },
      { h: "Cómo cuidarlo" },
      { p: "El corazón es un músculo y, como todos, se fortalece con el ejercicio. Correr, nadar, montar en bici o jugar al aire libre lo ayudan a trabajar mejor. También le sientan bien una alimentación variada, con frutas y verduras, y dormir lo suficiente." },
      { h: "Conclusión" },
      { p: "El corazón es el motor del aparato circulatorio: reparte oxígeno y nutrientes a todas las células del cuerpo. Conocer cómo funciona nos ayuda a entender por qué merece la pena cuidarlo." },
      { dato: "¿Sabías que el corazón late más deprisa cuando haces ejercicio? Tus músculos necesitan más oxígeno, y el corazón bombea más rápido para dárselo." },
    ],
    vocabulario: [
      { p: "cavidad", d: "Espacio hueco dentro de algo." },
      { p: "válvula", d: "Pieza que deja pasar un líquido en un sentido y le impide volver atrás." },
      { p: "nutriente", d: "Sustancia de los alimentos que el cuerpo necesita para vivir y crecer." },
      { p: "organismo", d: "Conjunto de órganos que forman un ser vivo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántas cavidades tiene el corazón y cómo se llaman?", r: "Cuatro: dos aurículas (arriba) y dos ventrículos (abajo).", lineas: 2 },
      { tipo: "comprension", q: "¿Qué ocurre durante la sístole? Elige:", opciones: ["El corazón se relaja y se llena de sangre", "El músculo se contrae y expulsa la sangre", "La sangre se carga de oxígeno"], r: "El músculo se contrae y expulsa la sangre" },
      { tipo: "comprension", q: "¿Para qué envía la parte derecha del corazón la sangre a los pulmones?", r: "Para que la sangre suelte el dióxido de carbono y se cargue de oxígeno.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué crees que pasaría si las válvulas no cerraran bien?", r: "La sangre podría retroceder y el corazón bombearía con menos eficacia.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el texto empieza pidiéndote que pongas la mano en el pecho?", r: "Para captar la atención del lector y relacionar el tema con su propio cuerpo antes de explicarlo.", lineas: 2 },
      { tipo: "texto", q: "Indica qué parte del texto es la introducción, cuál el desarrollo y cuál la conclusión. Escribe dos tecnicismos del desarrollo.", r: "Introducción: el primer párrafo (la mano en el pecho). Desarrollo: «¿Cómo es?», «¿Cómo funciona?» y «Cómo cuidarlo». Conclusión: el último párrafo. Tecnicismos: aurícula, ventrículo, válvula, arteria, sístole, diástole, circulación sanguínea.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué actividad física te gusta más? ¿Crees que la practicas lo suficiente? Explica por qué.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece buena idea medir el pulso antes y después de Educación Física? ¿Por qué?", r: "Respuesta libre. Valorar que relacionen ejercicio y ritmo cardiaco.", lineas: 2 },
      { tipo: "reflexion", q: "El corazón trabaja sin que lo notemos. ¿Qué otras cosas importantes de tu vida funcionan sin que las veas gracias al trabajo de otros?", r: "Respuesta libre. Valorar ejemplos concretos (agua corriente, luz, limpieza, cuidados…).", lineas: 3 },
    ],
  },
  {
    id: "cientifico-04-luna",
    titulo: "La Luna, nuestra vecina",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["NASA Science: «Moon Facts»", "Natural History Museum de Londres: «The Moon» (ficha divulgativa)"],
    antes: "¿Has observado que la Luna cambia de forma? ¿Por qué crees que ocurre?",
    texto: [
      { p: "La Luna es el único satélite natural de la Tierra y el astro más cercano a nosotros. Aunque de noche parece brillar con luz propia, en realidad no la tiene: refleja la luz del Sol." },
      { lista: ["Distancia media a la Tierra: unos 384.400 kilómetros.", "Diámetro: unos 3.475 kilómetros, más o menos la cuarta parte que el de la Tierra.", "Gravedad: la sexta parte de la terrestre.", "Tiempo que tarda en repetir sus fases: unos 29 días y medio."], titulo: "Ficha de la Luna" },
      { p: "Como su gravedad es mucho menor, una mochila que en la Tierra cuesta levantar parecería seis veces más ligera en la Luna." },
      { h: "¿Por qué cambia de forma?" },
      { p: "La Luna gira alrededor de la Tierra y, a la vez, sobre sí misma. Tarda lo mismo en dar una vuelta completa alrededor de nuestro planeta que en girar sobre su eje; por eso siempre nos muestra la misma cara. La mitad de la Luna está siempre iluminada por el Sol, pero desde la Tierra vemos una parte distinta de esa mitad según su posición. Así se producen las fases: luna nueva, cuarto creciente, luna llena y cuarto menguante." },
      { h: "Una superficie llena de cicatrices" },
      { p: "La Luna casi no tiene atmósfera que la proteja. Por eso su superficie está cubierta de cráteres, huecos producidos por el choque de meteoritos durante miles de millones de años. Las manchas oscuras que vemos a simple vista son llanuras de lava solidificada. Los primeros astrónomos las confundieron con mares, y todavía hoy se llaman así." },
      { h: "La influencia de la Luna" },
      { p: "La gravedad de la Luna atrae el agua de los océanos y es la causa principal de las mareas, la subida y bajada del nivel del mar que se observa cada día en las playas de Cádiz o de Huelva. Entre 1969 y 1972, doce astronautas de las misiones Apolo caminaron sobre su superficie, y hoy varias agencias espaciales preparan el regreso de los seres humanos." },
      { h: "Conclusión" },
      { p: "La Luna no es solo un adorno del cielo nocturno: influye en los mares, nos ha ayudado a medir el tiempo y fue el primer paso de la humanidad fuera de la Tierra." },
    ],
    vocabulario: [
      { p: "satélite", d: "Astro que gira alrededor de un planeta." },
      { p: "eje", d: "Línea imaginaria alrededor de la cual gira un cuerpo." },
      { p: "meteorito", d: "Trozo de roca del espacio que choca contra un planeta o un satélite." },
      { p: "marea", d: "Subida y bajada del nivel del mar que se produce cada día." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué brilla la Luna si no tiene luz propia?", r: "Porque refleja la luz del Sol.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué son los «mares» de la Luna? Elige:", opciones: ["Lagos de agua helada", "Llanuras de lava solidificada", "Cráteres muy profundos"], r: "Llanuras de lava solidificada" },
      { tipo: "comprension", q: "¿Por qué desde la Tierra vemos siempre la misma cara de la Luna?", r: "Porque tarda lo mismo en dar una vuelta alrededor de la Tierra que en girar sobre sí misma.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que en la Luna se conservan tantos cráteres?", r: "Porque casi no tiene atmósfera que frene los meteoritos, ni viento ni lluvia que borren las marcas con el tiempo.", lineas: 2 },
      { tipo: "comprension", q: "Un astronauta salta en la Luna. ¿Llegaría más alto o más bajo que en la Tierra? Justifícalo con un dato del texto.", r: "Más alto, porque la gravedad de la Luna es la sexta parte de la de la Tierra.", lineas: 2 },
      { tipo: "texto", q: "En este texto hay una lista con datos. ¿Por qué crees que el autor organiza así esa información? ¿Qué rasgo del texto científico demuestra?", r: "Para que los datos se localicen y comparen con facilidad. Demuestra la precisión y el uso de datos comprobables propios del texto científico.", lineas: 2 },
      { tipo: "opinion", q: "Si pudieras viajar a la Luna, ¿irías? ¿Qué es lo que más y lo que menos te gustaría del viaje?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que merece la pena invertir dinero en volver a la Luna? Da al menos una razón.", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "reflexion", q: "Durante siglos se pensó que las manchas de la Luna eran mares. ¿Qué nos enseña esto sobre cómo avanza la ciencia?", r: "Respuesta libre. Valorar la idea de que la ciencia corrige sus errores con nuevas observaciones.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-05-donana",
    titulo: "Doñana, un aeropuerto para las aves",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["UNESCO, Centro del Patrimonio Mundial: ficha del Parque Nacional de Doñana (n.º 685)", "Red de Parques Nacionales (CNIG): ficha de Doñana"],
    antes: "¿Por qué crees que algunas aves viajan miles de kilómetros cada año?",
    texto: [
      { p: "Cada otoño, miles de aves cruzan el cielo de Europa rumbo al sur. Muchas hacen una parada, o se quedan todo el invierno, en un lugar muy especial del suroeste de Andalucía: Doñana. Por eso se dice que este espacio natural funciona como un gran aeropuerto para las aves." },
      { h: "Un mosaico de paisajes" },
      { p: "Doñana se extiende por las provincias de Huelva, Sevilla y Cádiz, junto a la desembocadura del río Guadalquivir. Fue declarado parque nacional en 1969 y Patrimonio de la Humanidad por la UNESCO en 1994. Reúne ecosistemas muy distintos: la marisma, una enorme llanura que se inunda en otoño e invierno y se seca en verano; las dunas móviles, montañas de arena que el viento empuja lentamente tierra adentro; y los cotos, zonas de monte mediterráneo con alcornoques, pinos y matorral." },
      { h: "¿Por qué migran las aves?" },
      { p: "La migración es un viaje de ida y vuelta que muchas aves realizan cada año. En primavera y verano, numerosas especies crían en el norte de Europa, donde hay comida abundante y días largos. Cuando llega el frío, escasean los insectos, las semillas y el agua sin helar, y viajan hacia zonas más templadas. Doñana está en un lugar estratégico: cerca del estrecho de Gibraltar, el paso más corto entre Europa y África." },
      { h: "Cifras de récord" },
      { p: "Según la UNESCO, Doñana sirve de refugio invernal a más de medio millón de aves acuáticas cada año. Entre ellas destacan los ánsares, unos gansos que llegan del norte de Europa, además de patos, flamencos, espátulas y garzas. En el parque se han observado cientos de especies de aves, algunas tan amenazadas como el águila imperial ibérica." },
      { h: "Conclusión" },
      { p: "Doñana es uno de los humedales más importantes de Europa, y su vida depende del agua. Si la marisma y los acuíferos se secan, las aves pierden su lugar de descanso. Cuidar Doñana es cuidar un tesoro que pertenece a todo el planeta." },
    ],
    vocabulario: [
      { p: "humedal", d: "Terreno cubierto de agua de forma temporal o permanente." },
      { p: "desembocadura", d: "Lugar donde un río llega al mar." },
      { p: "ecosistema", d: "Conjunto de seres vivos y del lugar en el que viven." },
      { p: "templado", d: "Ni muy frío ni muy caluroso." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿En qué provincias se encuentra Doñana?", r: "En Huelva, Sevilla y Cádiz.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué son las dunas móviles? Elige:", opciones: ["Zonas que se inundan en invierno", "Montañas de arena que el viento desplaza", "Bosques de alcornoques y pinos"], r: "Montañas de arena que el viento desplaza" },
      { tipo: "comprension", q: "¿Por qué muchas aves abandonan el norte de Europa cuando llega el frío?", r: "Porque escasean los insectos, las semillas y el agua sin helar.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el autor compara Doñana con un aeropuerto?", r: "Porque, como en un aeropuerto, allí llegan, paran y salen viajeros: las aves descansan o pasan el invierno durante su migración.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué relación hay entre la cercanía del estrecho de Gibraltar y la abundancia de aves en Doñana?", r: "El estrecho es el paso más corto entre Europa y África; como Doñana está cerca, queda en la ruta de muchas aves migratorias.", lineas: 2 },
      { tipo: "texto", q: "Escribe dos datos del texto que se puedan comprobar (fechas, cifras…). ¿Por qué el autor escribe «según la UNESCO»?", r: "Parque nacional en 1969; Patrimonio de la Humanidad en 1994; más de medio millón de aves acuáticas en invierno. Escribe «según la UNESCO» para indicar la fuente del dato y dar objetividad al texto.", lineas: 3 },
      { tipo: "opinion", q: "¿Te gustaría visitar Doñana? ¿Qué te gustaría observar y cómo te comportarías para no molestar a los animales?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "El texto dice que Doñana es un tesoro que pertenece a todo el planeta. ¿Estás de acuerdo? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "reflexion", q: "Las aves migratorias no entienden de fronteras. ¿Por qué crees que proteger la naturaleza necesita que distintos países colaboren?", r: "Respuesta libre. Valorar la idea de que las aves dependen de lugares de varios países a lo largo de su viaje.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-06-lince",
    titulo: "El lince ibérico, la vuelta de un superviviente",
    subtipo: "Artículo de divulgación",
    curso: "5º-6º",
    fuente: "Texto original",
    datos: ["Ministerio para la Transición Ecológica y el Reto Demográfico (MITECO): censos del lince ibérico de 2024 y 2025 (España y Portugal)", "Prensa especializada sobre el cambio de categoría del lince en la Lista Roja de la UICN (2024)"],
    antes: "¿Has oído hablar del lince ibérico? ¿Sabes por qué estuvo a punto de desaparecer?",
    texto: [
      { p: "El lince ibérico es un felino que solo vive en la península ibérica. Hace poco más de veinte años era el felino más amenazado del planeta. Hoy su población no deja de crecer gracias a un gran esfuerzo de conservación en el que Andalucía ha tenido un papel protagonista." },
      { h: "Cómo reconocerlo" },
      { p: "El lince pesa alrededor de diez kilos, más o menos el doble que un gato doméstico grande. Tiene las patas largas y la cola corta, rematada en una mancha negra. Su pelaje es pardo, con manchas oscuras. Sus rasgos más característicos son los pinceles, unos mechones de pelo negro en la punta de las orejas, y las patillas que le cuelgan a ambos lados de la cara." },
      { h: "Un cazador especialista" },
      { p: "El lince es un depredador muy especializado: su presa principal es el conejo de monte. Por eso, cuando en el siglo XX varias enfermedades redujeron mucho el número de conejos, los linces también empezaron a desaparecer. A esto se sumaron la destrucción del monte mediterráneo, la caza ilegal y los atropellos." },
      { h: "De casi desaparecer a batir récords" },
      { p: "A comienzos de este siglo quedaban menos de cien ejemplares, repartidos en dos pequeños núcleos de Andalucía: Doñana y Sierra Morena. Entonces se pusieron en marcha programas de cría en cautividad, se recuperaron las poblaciones de conejo y se liberaron linces en nuevas zonas de España y Portugal." },
      { p: "Los resultados son espectaculares. Según el censo del Ministerio para la Transición Ecológica, en 2025 se contaron 2.663 linces ibéricos, un 10,9 % más que el año anterior. En 2024, la Unión Internacional para la Conservación de la Naturaleza (UICN) lo pasó de la categoría «en peligro» a la de «vulnerable»." },
      { h: "Un peligro en la carretera" },
      { p: "El lince todavía tiene problemas. En 2024 murieron 214 linces en la península, y tres de cada cuatro de esas muertes se debieron a atropellos. Por eso se construyen pasos de fauna bajo las carreteras y se colocan señales para que los conductores reduzcan la velocidad." },
      { h: "Conclusión" },
      { p: "La historia del lince demuestra que, cuando la ciencia, las administraciones y la gente del campo trabajan juntas, es posible salvar una especie. Pero su futuro depende de que sigamos cuidando su hábitat." },
    ],
    vocabulario: [
      { p: "felino", d: "Mamífero de la familia del gato, como el lince, el león o el tigre." },
      { p: "depredador", d: "Animal que caza a otros para alimentarse." },
      { p: "cautividad", d: "Situación de un animal que vive encerrado o controlado por personas." },
      { p: "hábitat", d: "Lugar con las condiciones adecuadas para que viva una especie." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Escribe dos rasgos físicos que sirven para reconocer al lince ibérico.", r: "Los pinceles negros de las orejas, las patillas de la cara, la cola corta con punta negra, el pelaje pardo con manchas.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la desaparición de los conejos puso en peligro al lince? Elige:", opciones: ["Porque los conejos le contagiaban enfermedades", "Porque el conejo es su presa principal y se quedó sin alimento", "Porque los conejos le quitaban el territorio"], r: "Porque el conejo es su presa principal y se quedó sin alimento" },
      { tipo: "comprension", q: "¿Cuántos linces se contaron en 2025 y quién hizo el censo?", r: "2.663 linces; el censo lo publicó el Ministerio para la Transición Ecológica.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que fue importante liberar linces en nuevas zonas y no dejarlos solo en Doñana y Sierra Morena?", r: "Porque si todos viven en pocos lugares, una enfermedad, un incendio u otro problema podría acabar con ellos; repartirlos hace la especie más segura y le da más territorio.", lineas: 2 },
      { tipo: "comprension", q: "El lince ya no está «en peligro». ¿Significa eso que ya no hay que protegerlo? Justifícalo con el texto.", r: "No: sigue siendo «vulnerable» y cada año mueren muchos linces atropellados; su futuro depende de seguir cuidando su hábitat.", lineas: 2 },
      { tipo: "texto", q: "El texto científico se organiza en introducción, desarrollo y conclusión. ¿Qué idea principal presenta la introducción y qué idea resume la conclusión?", r: "Introducción: el lince, que era el felino más amenazado, hoy se recupera gracias a la conservación. Conclusión: la colaboración entre ciencia, administraciones y gente del campo puede salvar una especie, pero hay que seguir cuidando su hábitat.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué medida te parece más útil para proteger al lince: los pasos de fauna, las señales o la cría en cautividad? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que merece la pena gastar dinero en salvar una sola especie? Razona tu respuesta.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "La recuperación del lince fue posible porque mucha gente trabajó unida. ¿Qué problema de tu entorno podría resolverse si todos colaboraran?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-07-volcanes",
    titulo: "¿Qué ocurre dentro de un volcán?",
    subtipo: "Artículo de divulgación",
    curso: "5º-6º",
    fuente: "Texto original",
    datos: ["Instituto Geológico y Minero de España (IGME-CSIC): Inventario de Lugares de Interés Geológico, ficha IC6031 «Volcán, coladas y piroclastos de la erupción de Tajogaite de 2021»"],
    antes: "¿Has visto alguna vez imágenes de un volcán en erupción? ¿De dónde crees que sale la lava?",
    texto: [
      { p: "Los volcanes son una de las muestras más impresionantes de la energía de nuestro planeta. Pero ¿qué sucede bajo tierra para que una montaña expulse fuego, rocas y cenizas?" },
      { h: "Un planeta caliente por dentro" },
      { p: "La Tierra está formada por capas. La más externa, sobre la que vivimos, es la corteza. Debajo está el manto y, en el centro, el núcleo. En el interior del planeta las temperaturas son altísimas, y en algunas zonas las rocas llegan a fundirse. Esa roca fundida, mezclada con gases, se llama magma." },
      { h: "Cómo se produce una erupción" },
      { p: "La corteza terrestre no es una pieza única: está dividida en grandes placas tectónicas que se mueven muy despacio. En los bordes de las placas, y en algunos puntos especialmente calientes, el magma puede ascender por grietas. Como es menos denso que las rocas que lo rodean, sube y se acumula en una cámara magmática. Cuando la presión de los gases es suficiente, el magma sale al exterior: es la erupción." },
      { p: "Al llegar a la superficie, el magma pierde gases y pasa a llamarse lava. Un volcán puede expulsar coladas de lava, que avanzan como ríos incandescentes; piroclastos, que son fragmentos de roca y ceniza lanzados al aire; y gases, sobre todo vapor de agua y dióxido de carbono. La abertura por donde sale todo se llama cráter, y el conducto que la comunica con la cámara, chimenea." },
      { h: "Volcanes en España" },
      { p: "En 2021, la isla canaria de La Palma vivió la erupción del volcán de Tajogaite. Según el Instituto Geológico y Minero de España, comenzó el 19 de septiembre y terminó el 13 de diciembre: 85 días de actividad. Sus coladas cubrieron casas, carreteras y cultivos, aunque la evacuación a tiempo de la población evitó una tragedia mayor. Andalucía también tiene un pasado volcánico: muchas rocas y acantilados del Cabo de Gata, en Almería, se formaron por volcanes que estuvieron activos hace millones de años." },
      { h: "Conclusión" },
      { p: "Los volcanes destruyen, pero también crean: forman islas nuevas y dejan suelos muy fértiles. Los vulcanólogos vigilan los volcanes activos midiendo los terremotos, los gases y las deformaciones del terreno para avisar a la población antes de una erupción." },
    ],
    vocabulario: [
      { p: "incandescente", d: "Tan caliente que brilla y da luz." },
      { p: "denso", d: "Que tiene mucha materia en poco espacio; que pesa mucho para su tamaño." },
      { p: "vulcanólogo", d: "Científico que estudia los volcanes." },
      { p: "fértil", d: "Se dice de la tierra en la que crecen bien las plantas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué diferencia hay entre magma y lava?", r: "El magma es roca fundida con gases que está en el interior de la Tierra; cuando sale a la superficie y pierde gases se llama lava.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué son los piroclastos? Elige:", opciones: ["Ríos de lava", "Fragmentos de roca y ceniza lanzados al aire", "Grietas de la corteza"], r: "Fragmentos de roca y ceniza lanzados al aire" },
      { tipo: "comprension", q: "¿Cuánto duró la erupción del Tajogaite y entre qué fechas?", r: "85 días, del 19 de septiembre al 13 de diciembre de 2021.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué sube el magma hacia la superficie?", r: "Porque es menos denso que las rocas que lo rodean y porque la presión de los gases lo empuja hacia fuera.", lineas: 2 },
      { tipo: "comprension", q: "El texto dice que los volcanes «destruyen, pero también crean». Explica esta idea con ejemplos del texto.", r: "Destruyen casas, carreteras y cultivos, como en La Palma; pero crean islas nuevas, suelos fértiles y paisajes como el del Cabo de Gata.", lineas: 2 },
      { tipo: "texto", q: "Explica qué significan estos tecnicismos: cámara magmática, cráter y chimenea. ¿Por qué crees que el autor los explica dentro del propio texto?", r: "Cámara magmática: lugar donde se acumula el magma; cráter: abertura por donde sale; chimenea: conducto que une la cámara con el cráter. Los explica porque es un texto de divulgación dirigido a lectores no especialistas.", lineas: 3 },
      { tipo: "opinion", q: "¿Vivirías cerca de un volcán activo si estuviera vigilado por científicos? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "opinion", q: "¿Cómo crees que se sintieron los habitantes de La Palma al tener que dejar sus casas? ¿Cómo se puede ayudar en una situación así?", r: "Respuesta libre. Valorar la empatía y las propuestas concretas.", lineas: 3 },
      { tipo: "reflexion", q: "Los científicos no pueden impedir una erupción, pero sí avisar. ¿Por qué es tan importante hacer caso a los expertos en una emergencia?", r: "Respuesta libre. Valorar la relación entre conocimiento científico y seguridad.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-08-termosolar",
    titulo: "Espejos que atrapan el sol",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["SENER: «Gemasolar: 24 horas de energía solar» (ficha del proyecto)", "Revista Energías Renovables: noticias sobre la puesta en marcha de Gemasolar", "Datos técnicos de la central PS10 de Sanlúcar la Mayor (Wikipedia en inglés, «PS10 solar power plant», y prensa)"],
    antes: "¿Sabes cómo se puede producir electricidad con el sol? ¿Has visto alguna vez placas solares?",
    texto: [
      { p: "Andalucía recibe muchísimas horas de sol al año. Aprovechar esa luz para producir electricidad es una de las grandes apuestas de las energías renovables, las que proceden de fuentes que no se agotan. Una de las tecnologías más curiosas para conseguirlo se desarrolló, en buena parte, en la provincia de Sevilla: la energía termosolar." },
      { h: "Fotovoltaica y termosolar: no es lo mismo" },
      { p: "Las placas solares de los tejados son paneles fotovoltaicos: transforman la luz directamente en electricidad gracias a materiales como el silicio. Las centrales termosolares funcionan de otra manera. No aprovechan la luz, sino el calor del sol, que concentran con espejos para calentar un líquido. Ese calor produce vapor de agua, el vapor mueve una turbina y la turbina hace girar un generador eléctrico." },
      { h: "Una torre rodeada de espejos" },
      { p: "En las centrales de torre, cientos o miles de espejos llamados heliostatos siguen el movimiento del sol a lo largo del día, dirigidos por ordenador. Todos reflejan la luz hacia un mismo punto: un receptor situado en lo alto de una torre, donde se alcanzan temperaturas muy elevadas." },
      { p: "En 2007 se inauguró en Sanlúcar la Mayor (Sevilla) la PS10, considerada la primera central comercial de torre del mundo. Tiene 624 heliostatos y una torre de 115 metros. Unos años después empezó a funcionar en Fuentes de Andalucía (Sevilla) la central Gemasolar, con 2.650 heliostatos que ocupan unas 185 hectáreas." },
      { h: "El secreto de las sales fundidas" },
      { p: "El gran problema de la energía solar es que de noche no hay sol. Gemasolar fue la primera central comercial de torre que usó sales fundidas para recoger y almacenar el calor. Estas sales, parecidas a algunos abonos, se calientan durante el día y guardan la energía en grandes tanques. Así, la central puede seguir produciendo electricidad hasta 15 horas sin sol, y ha llegado a funcionar las 24 horas del día." },
      { p: "En la provincia de Granada, en la comarca del Marquesado del Zenete, las centrales Andasol usan otra técnica: largas filas de espejos curvos, llamados colectores cilindroparabólicos, que calientan un aceite especial." },
      { h: "Conclusión" },
      { p: "La energía termosolar apenas emite gases contaminantes al producir electricidad y aprovecha un recurso abundante en el sur de España. Sus inconvenientes son que necesita mucho terreno y cielos despejados. Aun así, las centrales andaluzas han servido de modelo para proyectos de todo el mundo." },
    ],
    vocabulario: [
      { p: "renovable", d: "Que se renueva de forma natural y no se agota, como el sol o el viento." },
      { p: "turbina", d: "Máquina con una rueda de paletas que gira empujada por un fluido, como el vapor." },
      { p: "generador", d: "Aparato que transforma el movimiento en electricidad." },
      { p: "hectárea", d: "Medida de superficie de 10.000 metros cuadrados, algo más que un campo de fútbol." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué diferencia principal hay entre una placa fotovoltaica y una central termosolar?", r: "La placa fotovoltaica transforma la luz directamente en electricidad; la central termosolar concentra el calor del sol para producir vapor que mueve una turbina.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué es un heliostato? Elige:", opciones: ["Un tanque de sales fundidas", "Un espejo que sigue al sol y refleja su luz hacia la torre", "El generador de una central"], r: "Un espejo que sigue al sol y refleja su luz hacia la torre" },
      { tipo: "comprension", q: "¿Qué problema resuelven las sales fundidas?", r: "Que de noche no hay sol: almacenan el calor y permiten producir electricidad hasta 15 horas sin sol.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que estas centrales se construyen en Andalucía y no, por ejemplo, en el norte de Europa?", r: "Porque Andalucía tiene muchas horas de sol y cielos despejados, imprescindibles para que funcionen.", lineas: 2 },
      { tipo: "comprension", q: "Ordena los pasos para producir electricidad en una central de torre: vapor, turbina, heliostatos, receptor, generador.", r: "Heliostatos → receptor en la torre → vapor → turbina → generador.", lineas: 2 },
      { tipo: "texto", q: "Un texto científico objetivo muestra ventajas e inconvenientes sin exagerar. Copia un inconveniente de la energía termosolar. ¿Por qué debe incluirse?", r: "Necesita mucho terreno y cielos despejados. Porque la objetividad exige dar la información completa, no solo lo positivo, para que el lector saque sus propias conclusiones.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parecería bien que se construyera una central termosolar cerca de tu localidad? Da un argumento a favor y otro en contra.", r: "Respuesta libre. Valorar que den argumentos de ambos lados.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué fuente de energía crees que se usará más cuando seas adulto? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Los inventos se mejoran con el trabajo de muchas personas a lo largo de los años. ¿Qué ejemplo del texto lo demuestra? ¿Conoces otro?", r: "Respuesta libre. Valorar que relacionen la PS10 con Gemasolar, que añadió el almacenamiento con sales, y que las centrales andaluzas sirvieron de modelo a otras.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-09-vacuna",
    titulo: "La vacuna, una idea que cambió la historia",
    subtipo: "Artículo de divulgación (historia de la ciencia)",
    curso: "6º",
    fuente: "Texto original",
    datos: ["Organización Mundial de la Salud (OMS): «La OMS conmemora el 40.º aniversario de la erradicación de la viruela» (2019)", "CSIC: «Balmis: la expedición española que llevó la vacuna de la viruela a Asia y América»", "Comité Asesor de Vacunas de la Asociación Española de Pediatría: «Isabel Zendal y la expedición Balmis»"],
    antes: "¿Sabes por qué nos ponemos vacunas? ¿Recuerdas alguna que te hayan puesto?",
    texto: [
      { p: "Durante siglos, la viruela fue una de las enfermedades más temidas del mundo. Era muy contagiosa, provocaba fiebre alta y ampollas por todo el cuerpo, y dejaba cicatrices en muchas personas. Hoy ya no existe. ¿Cómo se consiguió? Con uno de los inventos más importantes de la medicina: la vacuna." },
      { h: "Una observación en el campo" },
      { p: "A finales del siglo XVIII, el médico inglés Edward Jenner se fijó en algo curioso: las lecheras que se contagiaban de la viruela de las vacas, una enfermedad leve, no solían enfermar después de la viruela humana. En 1796 hizo un experimento: tomó material de una lesión de viruela vacuna y lo introdujo en un pequeño corte en el brazo de un niño. Más tarde comprobó que el niño no enfermaba de viruela. De la palabra latina vacca, «vaca», procede el nombre de vacuna." },
      { h: "¿Cómo funciona una vacuna?" },
      { p: "Nuestro cuerpo tiene un sistema de defensa llamado sistema inmunitario. Cuando entra un microbio, fabrica unas sustancias llamadas anticuerpos para combatirlo y, además, lo recuerda. Una vacuna contiene el microbio debilitado o inactivado, o solo una parte de él, de modo que no causa la enfermedad. Así, el sistema inmunitario aprende a reconocerlo. Si más tarde llega el microbio real, las defensas actúan con rapidez." },
      { h: "Una expedición española alrededor del mundo" },
      { p: "En 1803, el médico alicantino Francisco Javier Balmis dirigió la Real Expedición Filantrópica de la Vacuna, que partió de La Coruña. Como entonces no había neveras, la vacuna viajó en los brazos de 22 niños: se vacunaba a dos de ellos y, cuando les aparecían las lesiones, se pasaba el material a otros dos, en cadena. Los cuidaba Isabel Zendal, a quien la OMS considera la primera enfermera de una misión sanitaria internacional. La expedición llevó la vacuna a América y a Asia." },
      { h: "Un éxito mundial" },
      { p: "Gracias a campañas de vacunación en todos los países, en 1980 la Organización Mundial de la Salud declaró erradicada la viruela. Es la única enfermedad humana que se ha conseguido eliminar por completo. Hoy existen vacunas contra muchas otras, como el sarampión, la polio o el tétanos." },
      { h: "Conclusión" },
      { p: "La historia de la vacuna muestra cómo funciona la ciencia: observación, hipótesis, experimento y comprobación. También enseña que la salud de cada persona depende, en parte, de la de los demás: cuantas más personas se vacunan, más difícil es que una enfermedad se propague." },
    ],
    vocabulario: [
      { p: "erradicar", d: "Eliminar algo por completo." },
      { p: "inmunitario", d: "Relacionado con las defensas del cuerpo contra las enfermedades." },
      { p: "filantrópico", d: "Que se hace por amor a los demás, para ayudarlos." },
      { p: "hipótesis", d: "Explicación posible que hay que comprobar." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué observó Edward Jenner en las lecheras?", r: "Que las que se contagiaban de la viruela de las vacas, que era leve, no solían enfermar después de la viruela humana.", lineas: 2 },
      { tipo: "comprension", q: "¿De dónde procede la palabra vacuna? Elige:", opciones: ["Del apellido de su inventor", "De la palabra latina vacca, «vaca»", "De vacío, porque se inyecta vacía"], r: "De la palabra latina vacca, «vaca»" },
      { tipo: "comprension", q: "¿Por qué la vacuna viajó en los brazos de niños en la expedición de Balmis?", r: "Porque no había neveras para conservarla; se mantenía activa pasando el material de un niño vacunado a otro, en cadena.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que el sistema inmunitario «recuerda» un microbio? ¿Por qué es importante?", r: "Que es capaz de reconocerlo si vuelve a entrar; así reacciona rápido y evita la enfermedad.", lineas: 2 },
      { tipo: "comprension", q: "La conclusión dice que la salud de cada persona depende en parte de la de los demás. Explica esta idea.", r: "Si muchas personas están vacunadas, el microbio encuentra pocas personas a las que contagiar y se propaga menos; así también se protege a quien no puede vacunarse.", lineas: 2 },
      { tipo: "texto", q: "La conclusión nombra los pasos del método científico. Relaciona cada uno con lo que hizo Jenner.", r: "Observación: las lecheras no enfermaban. Hipótesis: la viruela vacuna protege de la humana. Experimento: vacunar a un niño en 1796. Comprobación: el niño no enfermó de viruela.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué opinas de la labor de Isabel Zendal? ¿Por qué crees que durante mucho tiempo fue poco conocida?", r: "Respuesta libre. Valorar la reflexión sobre el reconocimiento del trabajo de las mujeres y de los cuidados.", lineas: 3 },
      { tipo: "opinion", q: "Los niños de la expedición no pudieron elegir si participaban. ¿Qué te parece? Razona tu respuesta pensando en aquella época y en la actual.", r: "Respuesta libre. Valorar que distingan los valores de la época y los derechos de la infancia actuales.", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué enfermedad o problema te gustaría que la ciencia consiguiera eliminar? ¿Qué haría falta para lograrlo?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-10-clima",
    titulo: "El cambio climático, explicado con calma",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["IPCC (Grupo Intergubernamental de Expertos sobre el Cambio Climático): Sexto Informe de Evaluación, Grupo de Trabajo I (2021), Resumen para responsables de políticas", "Organización Meteorológica Mundial (OMM): confirmación de 2024 como año más cálido registrado (Noticias ONU, enero de 2025)"],
    antes: "¿Qué has oído sobre el cambio climático? ¿Te preocupa? ¿Por qué?",
    texto: [
      { h: "Tiempo y clima" },
      { p: "Si mañana llueve en Sevilla, hablamos del tiempo atmosférico: lo que ocurre en un lugar durante unas horas o unos días. El clima, en cambio, es el tiempo habitual de una región a lo largo de muchos años, normalmente treinta o más. Un día frío en agosto no cambia el clima; lo que lo cambia son las tendencias que se repiten durante décadas." },
      { h: "El efecto invernadero" },
      { p: "La Tierra está rodeada por la atmósfera, una capa de gases. Algunos de ellos, como el vapor de agua, el dióxido de carbono (CO2) y el metano, dejan pasar la luz del Sol, pero retienen parte del calor que la Tierra devuelve al espacio. Es el efecto invernadero natural, y es imprescindible: sin él, la temperatura media del planeta sería de unos 18 grados bajo cero." },
      { h: "¿Qué está cambiando?" },
      { p: "Desde el siglo XIX, la humanidad quema grandes cantidades de carbón, petróleo y gas para producir energía, mover vehículos y fabricar objetos. Esa combustión libera CO2, que se acumula en la atmósfera y refuerza el efecto invernadero. Además, la tala de bosques reduce el número de árboles que absorben ese gas." },
      { p: "El Grupo Intergubernamental de Expertos sobre el Cambio Climático (IPCC), formado por científicos de todo el mundo, concluyó en su informe de 2021 que es inequívoco que la actividad humana ha calentado el planeta. Según la Organización Meteorológica Mundial, 2024 fue el año más cálido desde que hay registros: la temperatura media global superó en unos 1,55 °C la de la época preindustrial." },
      { h: "Consecuencias" },
      { p: "Un grado y medio puede parecer poco, pero para el planeta es mucho. Los científicos observan que los glaciares retroceden, el nivel del mar sube y las olas de calor son más frecuentes e intensas. En regiones como el sur de España se esperan veranos más largos y calurosos y sequías más frecuentes." },
      { h: "Qué podemos hacer" },
      { p: "La buena noticia es que conocemos las causas y, por tanto, las soluciones. Muchos países se comprometieron a reducir sus emisiones en el Acuerdo de París de 2015. Las energías renovables, el transporte público, la bicicleta, el ahorro de energía y la protección de los bosques ayudan a frenar el calentamiento." },
      { h: "Conclusión" },
      { p: "El cambio climático es un problema serio, pero no es un motivo para el miedo, sino para la acción. La ciencia nos da la información; usarla bien depende de todos." },
    ],
    vocabulario: [
      { p: "inequívoco", d: "Que no deja lugar a dudas." },
      { p: "preindustrial", d: "Anterior a la aparición de las grandes industrias (en este caso, el periodo de 1850 a 1900)." },
      { p: "combustión", d: "Acción de quemar algo." },
      { p: "emisión", d: "Expulsión de gases u otras sustancias al aire." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué diferencia hay entre tiempo atmosférico y clima?", r: "El tiempo es lo que ocurre en un lugar durante horas o días; el clima es el tiempo habitual de una región durante muchos años (treinta o más).", lineas: 2 },
      { tipo: "comprension", q: "Según el texto, sin el efecto invernadero natural, la Tierra… Elige:", opciones: ["sería más cálida que ahora", "tendría una temperatura media de unos 18 grados bajo cero", "no tendría atmósfera"], r: "tendría una temperatura media de unos 18 grados bajo cero" },
      { tipo: "comprension", q: "¿Por qué la quema de carbón, petróleo y gas calienta el planeta?", r: "Porque libera CO2, que se acumula en la atmósfera, refuerza el efecto invernadero y retiene más calor.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice el autor que «un día frío en agosto no cambia el clima»?", r: "Porque el clima se estudia con tendencias de muchos años; un día aislado es solo tiempo atmosférico y no demuestra nada sobre el clima.", lineas: 2 },
      { tipo: "comprension", q: "El título dice «explicado con calma». ¿Qué frases muestran que el autor quiere informar sin asustar?", r: "Por ejemplo: «La buena noticia es que conocemos las causas y, por tanto, las soluciones» o «no es un motivo para el miedo, sino para la acción».", lineas: 2 },
      { tipo: "texto", q: "¿Por qué el texto cita al IPCC y a la Organización Meteorológica Mundial en lugar de decir «yo creo que el planeta se calienta»? ¿Qué característica del texto científico demuestra?", r: "Porque se apoya en fuentes expertas y datos comprobables, no en opiniones personales. Demuestra su objetividad.", lineas: 2 },
      { tipo: "opinion", q: "De las soluciones que propone el texto, ¿cuál crees que es más fácil de aplicar en tu familia? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "Algunas personas sienten angustia al oír hablar del cambio climático. ¿Qué le dirías a un compañero que se siente así?", r: "Respuesta libre. Valorar mensajes realistas y esperanzadores basados en el texto.", lineas: 3 },
      { tipo: "reflexion", q: "Las decisiones de hoy afectarán a quienes vivan dentro de cincuenta años. ¿Es justo pensar en las personas del futuro al tomar decisiones? ¿Por qué?", r: "Respuesta libre. Valorar la argumentación.", lineas: 3 },
    ],
  },
];
