// Lecturas · Texto científico (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["cientifico"] = [
  {
    id: "cientifico-01-ciclo-agua",
    titulo: "El viaje sin fin del agua",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["USGS (Servicio Geológico de Estados Unidos), Water Science School: «Where is Earth's Water?» y «How Much Water is There on Earth?»"],
    antes: "¿Crees que el agua que bebes hoy pudo ser antes nieve, nube o mar? ¿Por qué?",
    texto: [
      { h: "Siempre la misma agua" },
      { p: "El agua de la Tierra no se gasta ni se fabrica de nuevo: se mueve sin parar de un lugar a otro y cambia de estado. Los científicos llaman a este recorrido ciclo del agua o ciclo hidrológico. Gracias a él, el agua que hoy sale de tu grifo pudo formar parte, hace miles de años, de un glaciar, de una nube o de un océano." },
      { h: "Las etapas del ciclo" },
      { p: "Todo empieza con la energía del Sol. Cuando calienta los mares, los ríos y los lagos, una parte del agua líquida se convierte en vapor y sube a la atmósfera. Este proceso se llama evaporación. Las plantas también expulsan vapor de agua por sus hojas: es la transpiración." },
      { p: "A medida que asciende, el vapor se enfría y se transforma en gotitas diminutas que forman las nubes. Es la condensación. Cuando las gotas se unen y pesan demasiado, caen en forma de lluvia, nieve o granizo: es la precipitación." },
      { p: "El agua que llega al suelo puede seguir dos caminos. Una parte corre por la superficie hacia arroyos y ríos, y acaba en el mar; esto se conoce como escorrentía. Otra parte se filtra en la tierra, lo que se llama infiltración, y forma depósitos de agua subterránea: los acuíferos. Tarde o temprano, el Sol vuelve a evaporarla y el ciclo comienza otra vez." },
      { h: "El viaje de una gota andaluza" },
      { p: "Imaginemos una gota del mar Mediterráneo, frente a la costa de Motril. Un día caluroso de verano, el Sol la calienta y la gota se evapora sin que nadie la vea. El viento empuja el vapor tierra adentro, hacia las montañas. Al subir por las laderas de Sierra Nevada, el aire se enfría, el vapor se condensa y forma una nube. Llega el invierno y la gota cae convertida en un copo de nieve sobre una cumbre." },
      { p: "Allí pasa varios meses quieta, formando parte del manto blanco. En primavera, el deshielo la libera: baja por un arroyo, se une al río Genil, que nace en esa sierra, y viaja hacia el Guadalquivir. Quizá en el camino alguien la use para regar un huerto o la beba en un vaso. Al final, llegará de nuevo al mar, y el viaje volverá a empezar." },
      { h: "¿Cuánta agua dulce hay?" },
      { p: "Aunque nuestro planeta se ve azul desde el espacio, casi toda su agua es salada. Según el Servicio Geológico de Estados Unidos (USGS), más del 96 % del agua de la Tierra está en los océanos. Solo alrededor de un 3 % es agua dulce, y la mayor parte de ella está congelada en glaciares y casquetes polares o escondida bajo tierra. El agua de ríos y lagos que usamos cada día es una parte muy pequeña del total." },
      { lista: ["Pon un poco de agua en el fondo de un bol grande y, en el centro, un vaso vacío.", "Tapa el bol con film transparente y coloca una piedrecita encima, justo sobre el vaso.", "Deja el bol al sol durante unas horas.", "Observa: el agua se evapora, se condensa en gotitas bajo el film y gotea dentro del vaso."], ordenada: true, titulo: "Experimento: un ciclo del agua en un bol" },
      { h: "Conclusión" },
      { p: "El ciclo del agua reparte y renueva el agua del planeta de forma natural. Sin embargo, el agua dulce disponible es escasa, sobre todo en regiones con pocas lluvias, como gran parte de Andalucía. Por eso es tan importante no contaminarla y no malgastarla." },
    ],
    vocabulario: [
      { p: "atmósfera", d: "Capa de gases que rodea la Tierra." },
      { p: "glaciar", d: "Gran masa de hielo que se forma en las montañas altas o en las zonas polares." },
      { p: "acuífero", d: "Depósito de agua que se acumula bajo tierra, entre las rocas." },
      { p: "deshielo", d: "Momento en que la nieve y el hielo se derriten." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cómo se llama el paso del vapor de agua a las gotitas que forman las nubes? Elige:", opciones: ["Evaporación", "Condensación", "Infiltración"], r: "Condensación" },
      { tipo: "comprension", q: "Ordena el viaje de la gota andaluza: río Genil, nube, mar, nieve en la cumbre, vapor.", r: "Mar → vapor → nube → nieve en la cumbre → río Genil (y de nuevo al mar).", lineas: 2 },
      { tipo: "comprension", q: "En el experimento del bol, ¿qué hace el papel del Sol y qué hace el papel de las nubes? ¿Por qué el agua cae dentro del vaso?", r: "El Sol es el mismo Sol que calienta el bol; el film transparente hace de nubes, porque en él se condensa el vapor. La piedrecita hunde el film justo encima del vaso y las gotas resbalan hasta allí, como la lluvia.", lineas: 2 },
      { tipo: "texto", q: "Los textos científicos usan tecnicismos. Copia tres palabras técnicas del texto. ¿Por qué crees que el autor añade la historia de una gota si ya ha explicado las etapas?", r: "Por ejemplo: ciclo hidrológico, evaporación, transpiración, condensación, precipitación, escorrentía, infiltración, acuífero. La historia de la gota sirve de ejemplo concreto y cercano para que el lector entienda y recuerde las etapas.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué dos cosas podrías hacer en casa o en el colegio para no malgastar agua? ¿Por qué son útiles?", r: "Respuesta libre. Valorar que propongan acciones concretas (cerrar el grifo, duchas cortas, reutilizar agua…) y expliquen su efecto.", lineas: 3 },
      { tipo: "reflexion", q: "En algunos lugares del mundo conseguir agua potable cuesta horas de camino cada día. ¿Cómo cambiaría tu vida si te pasara a ti?", r: "Respuesta libre. Valorar la empatía y la relación con el valor del agua.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-02-abejas",
    titulo: "Las abejas, pequeñas jardineras del planeta",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["FAO (Organización de las Naciones Unidas para la Alimentación y la Agricultura): Día Mundial de las Abejas y datos sobre polinizadores", "The Nobel Prize: Premio Nobel de Fisiología o Medicina de 1973 (Karl von Frisch)"],
    antes: "¿Qué sabes de las abejas, además de que fabrican miel? ¿Crees que son importantes para nosotros?",
    texto: [
      { p: "Cuando pensamos en abejas, solemos acordarnos de la miel o de sus picaduras. Sin embargo, su trabajo más importante es otro: la polinización. Sin ella, muchas de las frutas y verduras que comemos no existirían." },
      { h: "¿Qué es la polinización?" },
      { p: "Las flores producen un polvo muy fino llamado polen. Para que una planta forme frutos y semillas, el polen tiene que viajar desde la parte masculina de una flor, los estambres, hasta la parte femenina, el pistilo, de la misma flor o de otra de su especie. Como las plantas no pueden moverse, necesitan ayuda: el viento, el agua o los animales polinizadores." },
      { p: "Las abejas visitan las flores para alimentarse de néctar, un líquido azucarado, y para recoger polen para sus crías. Mientras lo hacen, los granos de polen se pegan a los pelillos de su cuerpo y pasan de una flor a otra. Así, sin saberlo, hacen posible la fecundación de las plantas." },
      { h: "Una ciudad llamada colmena" },
      { p: "La abeja de la miel vive en colmenas muy organizadas. La reina es la única hembra que pone huevos, y puede poner cientos en un solo día. Los zánganos son los machos y su tarea es fecundar a las reinas jóvenes. Todo lo demás lo hacen las obreras, y cambian de trabajo a medida que se hacen mayores." },
      { lista: ["Limpiadoras: dejan relucientes las celdillas donde crecerán nuevas abejas.", "Nodrizas: alimentan a las larvas.", "Constructoras: fabrican con cera los panales, formados por celdillas de seis lados.", "Guardianas: vigilan la entrada para que no se cuelen intrusos.", "Pecoreadoras: salen al campo a recoger néctar, polen y agua."], titulo: "Los oficios de una obrera" },
      { p: "Cuando una pecoreadora encuentra buenas flores, vuelve a la colmena y hace una especie de baile. Con la dirección y la duración de sus movimientos indica a sus compañeras hacia dónde deben volar y a qué distancia están las flores. El científico austriaco Karl von Frisch descubrió el significado de este baile y recibió por sus estudios el Premio Nobel en 1973." },
      { h: "Muchas más abejas de las que imaginamos" },
      { p: "La abeja de la miel no es la única. Según la FAO, la organización de las Naciones Unidas para la alimentación, en el mundo hay unas 20.000 especies de abejas. Muchas son solitarias y viven en pequeños agujeros en la tierra o en la madera. Además, las mariposas, los abejorros, algunas moscas e incluso ciertos murciélagos y aves también polinizan." },
      { p: "La FAO calcula que tres de cada cuatro cultivos que producen frutos o semillas para la alimentación humana dependen, al menos en parte, de los polinizadores. Entre ellos están los almendros, los manzanos, los melones o las fresas." },
      { h: "Un trabajo en peligro" },
      { p: "En las últimas décadas, las poblaciones de abejas y de otros polinizadores han disminuido en muchos lugares. Entre las causas, los expertos señalan el uso de plaguicidas, la pérdida de flores silvestres, las especies invasoras y los cambios en el clima." },
      { h: "Conclusión" },
      { p: "Las abejas son esenciales para la naturaleza y para nuestra alimentación. Por eso la ONU declaró el 20 de mayo Día Mundial de las Abejas. Plantar flores, respetar a los insectos y no usar venenos en jardines y huertos son pequeñas acciones que ayudan a protegerlas." },
    ],
    vocabulario: [
      { p: "polinizador", d: "Animal que transporta el polen de una flor a otra." },
      { p: "zángano", d: "Macho de la abeja de la miel." },
      { p: "larva", d: "Cría de un insecto recién salida del huevo, con forma distinta a la del adulto." },
      { p: "plaguicida", d: "Producto químico que se usa para eliminar insectos u otras plagas." },
      { p: "cultivo", d: "Planta que se siembra y se cuida para obtener alimentos u otros productos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Para qué visitan las abejas las flores? Elige:", opciones: ["Para ayudar a las plantas a tener frutos", "Para alimentarse de néctar y recoger polen", "Para construir sus colmenas"], r: "Para alimentarse de néctar y recoger polen" },
      { tipo: "comprension", q: "¿Qué información da a sus compañeras una pecoreadora con su baile? ¿Por qué crees que eso es útil para la colmena?", r: "Hacia dónde deben volar y a qué distancia están las flores. Es útil porque las demás no pierden tiempo ni energía buscando y la colmena consigue más alimento.", lineas: 2 },
      { tipo: "comprension", q: "Si desaparecieran muchas abejas, ¿qué pasaría en una frutería? Razónalo con un dato del texto.", r: "Habría menos fruta y probablemente más cara, porque tres de cada cuatro cultivos que dan frutos o semillas dependen en parte de los polinizadores.", lineas: 2 },
      { tipo: "texto", q: "Un texto científico apoya lo que dice en datos. Copia un dato numérico y di de qué fuente procede. ¿Por qué es importante citar la fuente?", r: "Por ejemplo: unas 20.000 especies de abejas, o tres de cada cuatro cultivos; procede de la FAO. Citar la fuente permite comprobar que el dato es fiable.", lineas: 2 },
      { tipo: "opinion", q: "¿Te importaría que hubiera colmenas cerca de tu colegio? Da un argumento a favor y otro en contra.", r: "Respuesta libre. Valorar que den argumentos de ambos lados.", lineas: 3 },
      { tipo: "reflexion", q: "En la colmena cada obrera hace un trabajo distinto y todos son necesarios. ¿Pasa lo mismo en tu clase o en tu familia? Pon un ejemplo.", r: "Respuesta libre. Valorar que reconozcan el valor de trabajos poco visibles y la cooperación.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-03-corazon",
    titulo: "El corazón, un motor que no descansa",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["National Heart, Lung, and Blood Institute (NHLBI, Institutos Nacionales de Salud de EE. UU.): «How the Heart Works»"],
    antes: "Pon la mano en el pecho. ¿Qué notas? ¿Sabes para qué sirve ese movimiento?",
    texto: [
      { p: "Pon la mano en el lado izquierdo de tu pecho y quédate quieto unos segundos. Ese golpeteo rítmico es tu corazón, un órgano que trabaja día y noche desde antes de que nacieras." },
      { h: "¿Cómo es?" },
      { p: "El corazón es un músculo hueco, más o menos del tamaño de un puño, situado en el centro del pecho, entre los dos pulmones y un poco inclinado hacia la izquierda. Por dentro está dividido en cuatro cavidades: dos superiores, llamadas aurículas, y dos inferiores, llamadas ventrículos. Unas válvulas, que funcionan como puertas que solo se abren en un sentido, impiden que la sangre retroceda." },
      { h: "¿Cómo funciona?" },
      { p: "El corazón actúa como una bomba doble. La parte derecha recibe la sangre que vuelve del cuerpo cargada de dióxido de carbono y la envía a los pulmones. Allí la sangre suelta ese gas y se carga de oxígeno. Después regresa a la parte izquierda del corazón, que la impulsa con fuerza hacia todo el organismo a través de las arterias. Las venas se encargan de devolverla al corazón. Este recorrido completo se llama circulación sanguínea." },
      { p: "Cada latido tiene dos fases: la sístole, cuando el músculo se contrae y expulsa la sangre, y la diástole, cuando se relaja y se vuelve a llenar. Según el Instituto Nacional del Corazón, los Pulmones y la Sangre de Estados Unidos (NHLBI), el corazón late unas 100.000 veces al día." },
      { h: "Tres tipos de tubos" },
      { p: "La sangre viaja por una red enorme de conductos llamados vasos sanguíneos. Las arterias tienen las paredes gruesas y elásticas, porque soportan el empujón de cada latido. Las venas tienen paredes más finas y, en las piernas y los brazos, unas pequeñas válvulas que ayudan a la sangre a subir de vuelta al corazón. Entre unas y otras están los capilares, tan finos como un pelo o más. A través de sus paredes, la sangre entrega a las células el oxígeno y los nutrientes, y recoge los desechos." },
      { h: "Experimento: toma tu pulso" },
      { p: "Cada vez que el corazón se contrae, la sangre golpea las paredes de las arterias. Ese golpe se llama pulso y se puede notar en la muñeca o en el cuello." },
      { lista: ["Coloca las yemas de los dedos índice y corazón en la cara interna de la muñeca, por debajo del pulgar. No uses el pulgar, porque tiene pulso propio.", "Cuenta los latidos durante 15 segundos y multiplica el resultado por 4: así sabrás cuántas veces late tu corazón en un minuto.", "Salta a la comba o sube y baja escaleras durante dos minutos.", "Vuelve a tomarte el pulso y compara los dos resultados."], ordenada: true, titulo: "Pasos" },
      { p: "Verás que después del ejercicio el corazón late más deprisa. Tus músculos necesitan más oxígeno, y el corazón bombea más rápido para dárselo." },
      { h: "Cómo cuidarlo" },
      { p: "El corazón es un músculo y, como todos, se fortalece con el ejercicio. Correr, nadar, montar en bici o jugar al aire libre lo ayudan a trabajar mejor. También le sientan bien una alimentación variada, con frutas y verduras, y dormir lo suficiente." },
      { h: "Conclusión" },
      { p: "El corazón es el motor del aparato circulatorio: reparte oxígeno y nutrientes a todas las células del cuerpo. Conocer cómo funciona nos ayuda a entender por qué merece la pena cuidarlo." },
    ],
    vocabulario: [
      { p: "cavidad", d: "Espacio hueco dentro de algo." },
      { p: "válvula", d: "Pieza que deja pasar un líquido en un sentido y le impide volver atrás." },
      { p: "nutriente", d: "Sustancia de los alimentos que el cuerpo necesita para vivir y crecer." },
      { p: "desecho", d: "Resto que ya no sirve y que el cuerpo tiene que expulsar." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántas cavidades tiene el corazón y cómo se llaman?", r: "Cuatro: dos aurículas (arriba) y dos ventrículos (abajo).", lineas: 1 },
      { tipo: "comprension", q: "¿Qué tipo de vaso sanguíneo entrega el oxígeno a las células? Elige:", opciones: ["Las arterias", "Los capilares", "Las venas"], r: "Los capilares" },
      { tipo: "comprension", q: "¿Por qué crees que las arterias necesitan paredes más gruesas que las venas?", r: "Porque reciben la sangre que sale del corazón con fuerza en cada latido y tienen que aguantar ese empujón sin romperse.", lineas: 2 },
      { tipo: "texto", q: "Este texto incluye un experimento con pasos numerados. ¿Por qué crees que el autor lo añade a un texto que explica? ¿Qué se comprueba con él?", r: "Para que el lector compruebe por sí mismo lo que dice el texto, como hacen los científicos. Se comprueba que el corazón late más deprisa después del ejercicio.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece buena idea medir el pulso antes y después de Educación Física? ¿Por qué?", r: "Respuesta libre. Valorar que relacionen ejercicio y ritmo cardiaco.", lineas: 3 },
      { tipo: "reflexion", q: "El corazón trabaja sin que lo notemos. ¿Qué otras cosas importantes de tu vida funcionan sin que las veas gracias al trabajo de otros?", r: "Respuesta libre. Valorar ejemplos concretos (agua corriente, luz, limpieza, cuidados…).", lineas: 3 },
    ],
  },
  {
    id: "cientifico-04-luna",
    titulo: "La Luna, nuestra vecina",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["NASA Science: «Moon Facts» y «Moon Formation»", "Natural History Museum de Londres: «The Moon» (ficha divulgativa)", "NASA: «July 20, 1969: One Giant Leap For Mankind»"],
    antes: "¿Has observado que la Luna cambia de forma? ¿Por qué crees que ocurre?",
    texto: [
      { p: "La Luna es el único satélite natural de la Tierra y el astro más cercano a nosotros. Aunque de noche parece brillar con luz propia, en realidad no la tiene: refleja la luz del Sol." },
      { lista: ["Distancia media a la Tierra: unos 384.400 kilómetros.", "Diámetro: unos 3.475 kilómetros, más o menos la cuarta parte que el de la Tierra.", "Gravedad: la sexta parte de la terrestre.", "Tiempo que tarda en repetir sus fases: unos 29 días y medio."], titulo: "Ficha de la Luna" },
      { p: "Como su gravedad es mucho menor, una mochila que en la Tierra cuesta levantar parecería seis veces más ligera en la Luna." },
      { h: "¿De dónde salió la Luna?" },
      { p: "La explicación que hoy aceptan más científicos es sorprendente. Hace unos 4.500 millones de años, cuando la Tierra era muy joven, un cuerpo del tamaño de un planeta pequeño chocó contra ella. El golpe lanzó al espacio una enorme cantidad de roca fundida y restos. Poco a poco, esos trozos se juntaron por efecto de la gravedad y formaron la Luna. Las rocas que trajeron los astronautas han ayudado a comprobar esta idea." },
      { h: "¿Por qué cambia de forma?" },
      { p: "La Luna gira alrededor de la Tierra y, a la vez, sobre sí misma. Tarda lo mismo en dar una vuelta completa alrededor de nuestro planeta que en girar sobre su eje; por eso siempre nos muestra la misma cara. La mitad de la Luna está siempre iluminada por el Sol, pero desde la Tierra vemos una parte distinta de esa mitad según su posición. Así se producen las fases: luna nueva, cuarto creciente, luna llena y cuarto menguante." },
      { p: "A veces, el Sol, la Tierra y la Luna quedan perfectamente alineados y se produce un eclipse. Si la Tierra se coloca entre el Sol y la Luna, su sombra cubre la Luna llena y la tiñe de un color rojizo: es un eclipse de Luna. Si es la Luna la que se interpone entre el Sol y la Tierra, tapa el Sol durante unos minutos: es un eclipse de Sol." },
      { h: "Una superficie llena de cicatrices" },
      { p: "La Luna casi no tiene atmósfera que la proteja. Por eso su superficie está cubierta de cráteres, huecos producidos por el choque de meteoritos durante miles de millones de años. Las manchas oscuras que vemos a simple vista son llanuras de lava solidificada. Los primeros astrónomos las confundieron con mares, y todavía hoy se llaman así." },
      { h: "La influencia de la Luna" },
      { p: "La gravedad de la Luna atrae el agua de los océanos y es la causa principal de las mareas, la subida y bajada del nivel del mar que se observa cada día en las playas de Cádiz o de Huelva." },
      { p: "El 20 de julio de 1969, el astronauta Neil Armstrong, de la misión Apolo 11, se convirtió en la primera persona que pisó la Luna. Entre 1969 y 1972, doce astronautas de las misiones Apolo caminaron sobre su superficie. Como allí no hay viento ni lluvia, las huellas de sus botas siguen marcadas en el polvo lunar. Hoy varias agencias espaciales preparan el regreso de los seres humanos." },
      { h: "Conclusión" },
      { p: "La Luna no es solo un adorno del cielo nocturno: influye en los mares, nos ha ayudado a medir el tiempo y fue el primer paso de la humanidad fuera de la Tierra." },
    ],
    vocabulario: [
      { p: "satélite", d: "Astro que gira alrededor de un planeta." },
      { p: "eje", d: "Línea imaginaria alrededor de la cual gira un cuerpo." },
      { p: "eclipse", d: "Ocultación de un astro, total o parcial, por la interposición de otro." },
      { p: "meteorito", d: "Trozo de roca del espacio que choca contra un planeta o un satélite." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué son los «mares» de la Luna? Elige:", opciones: ["Lagos de agua helada", "Llanuras de lava solidificada", "Cráteres muy profundos"], r: "Llanuras de lava solidificada" },
      { tipo: "comprension", q: "¿Qué diferencia hay entre un eclipse de Luna y un eclipse de Sol?", r: "En el de Luna, la Tierra se pone entre el Sol y la Luna y su sombra cubre la Luna; en el de Sol, la Luna se pone entre el Sol y la Tierra y tapa el Sol.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que las huellas de los astronautas siguen en la Luna después de tantos años?", r: "Porque la Luna casi no tiene atmósfera: no hay viento ni lluvia que las borren.", lineas: 2 },
      { tipo: "texto", q: "En este texto hay una lista con datos. ¿Por qué crees que el autor organiza así esa información? ¿Qué rasgo del texto científico demuestra?", r: "Para que los datos se localicen y comparen con facilidad. Demuestra la precisión y el uso de datos comprobables propios del texto científico.", lineas: 2 },
      { tipo: "opinion", q: "Si pudieras viajar a la Luna, ¿irías? ¿Qué es lo que más y lo que menos te gustaría del viaje?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Durante siglos se pensó que las manchas de la Luna eran mares. ¿Qué nos enseña esto sobre cómo avanza la ciencia?", r: "Respuesta libre. Valorar la idea de que la ciencia corrige sus errores con nuevas observaciones.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-05-donana",
    titulo: "Doñana, un aeropuerto para las aves",
    subtipo: "Artículo de divulgación",
    curso: "5º",
    fuente: "Texto original",
    datos: ["UNESCO, Centro del Patrimonio Mundial: ficha del Parque Nacional de Doñana (n.º 685)", "Red de Parques Nacionales (CNIG): ficha de Doñana", "Estación Biológica de Doñana (CSIC): página institucional"],
    antes: "¿Por qué crees que algunas aves viajan miles de kilómetros cada año?",
    texto: [
      { p: "Cada otoño, miles de aves cruzan el cielo de Europa rumbo al sur. Muchas hacen una parada, o se quedan todo el invierno, en un lugar muy especial del suroeste de Andalucía: Doñana. Por eso se dice que este espacio natural funciona como un gran aeropuerto para las aves." },
      { h: "Un mosaico de paisajes" },
      { p: "Doñana se extiende por las provincias de Huelva, Sevilla y Cádiz, junto a la desembocadura del río Guadalquivir. Fue declarado parque nacional en 1969 y Patrimonio de la Humanidad por la UNESCO en 1994. Reúne ecosistemas muy distintos: la marisma, una enorme llanura que se inunda en otoño e invierno y se seca en verano; las dunas móviles, montañas de arena que el viento empuja lentamente tierra adentro; y los cotos, zonas de monte mediterráneo con alcornoques, pinos y matorral." },
      { h: "¿Por qué migran las aves?" },
      { p: "La migración es un viaje de ida y vuelta que muchas aves realizan cada año. En primavera y verano, numerosas especies crían en el norte de Europa, donde hay comida abundante y días largos. Cuando llega el frío, escasean los insectos, las semillas y el agua sin helar, y viajan hacia zonas más templadas. Doñana está en un lugar estratégico: cerca del estrecho de Gibraltar, el paso más corto entre Europa y África." },
      { h: "Un año en la marisma" },
      { p: "La marisma cambia tanto a lo largo del año que parece un lugar distinto en cada estación." },
      { lista: ["Otoño: llegan las primeras lluvias y la tierra seca empieza a encharcarse. Aparecen las primeras bandadas del norte.", "Invierno: la marisma se convierte en un lago poco profundo lleno de patos y gansos. Es la época de más aves.", "Primavera: los visitantes de invierno se marchan y llegan otras aves desde África para criar. Todo se llena de nidos y de flores.", "Verano: el agua se evapora, el barro se cuartea y los animales se concentran junto a las pocas lagunas que quedan."], titulo: "Las cuatro estaciones de Doñana" },
      { h: "Cifras de récord" },
      { p: "Según la UNESCO, Doñana sirve de refugio invernal a más de medio millón de aves acuáticas cada año. Entre ellas destacan los ánsares, unos gansos que llegan del norte de Europa, además de patos, flamencos, espátulas y garzas. En el parque se han observado cientos de especies de aves, algunas tan amenazadas como el águila imperial ibérica." },
      { h: "¿Cómo sabemos de dónde vienen?" },
      { p: "En Doñana trabaja desde hace décadas la Estación Biológica de Doñana, un centro de investigación del Consejo Superior de Investigaciones Científicas (CSIC). Una de las técnicas que usan los científicos para estudiar las migraciones es el anillamiento. Capturan un ave con cuidado, le colocan en la pata una anilla ligera con un código, anotan su peso y su tamaño, y la sueltan enseguida. Si otra persona la encuentra meses después en Holanda o en Senegal, el código permite reconstruir su viaje. Hoy también se usan pequeños emisores que envían la posición del ave por satélite." },
      { h: "Conclusión" },
      { p: "Doñana es uno de los humedales más importantes de Europa, y su vida depende del agua. Si la marisma y los acuíferos se secan, las aves pierden su lugar de descanso. Cuidar Doñana es cuidar un tesoro que pertenece a todo el planeta." },
    ],
    vocabulario: [
      { p: "humedal", d: "Terreno cubierto de agua de forma temporal o permanente." },
      { p: "desembocadura", d: "Lugar donde un río llega al mar." },
      { p: "ecosistema", d: "Conjunto de seres vivos y del lugar en el que viven." },
      { p: "anillamiento", d: "Colocación de una anilla con un código en la pata de un ave para estudiarla." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué son las dunas móviles? Elige:", opciones: ["Zonas que se inundan en invierno", "Montañas de arena que el viento desplaza", "Bosques de alcornoques y pinos"], r: "Montañas de arena que el viento desplaza" },
      { tipo: "comprension", q: "¿Por qué crees que en verano los animales se concentran junto a las pocas lagunas que quedan?", r: "Porque el agua de la marisma se evapora y solo allí encuentran agua para beber y comida.", lineas: 2 },
      { tipo: "comprension", q: "Explica cómo el anillamiento ayuda a saber de dónde vienen las aves.", r: "Se pone a un ave una anilla con un código; si alguien la encuentra en otro lugar, el código indica dónde fue anillada y se puede reconstruir su viaje.", lineas: 2 },
      { tipo: "texto", q: "Escribe dos datos del texto que se puedan comprobar (fechas, cifras…). ¿Por qué el autor escribe «según la UNESCO»?", r: "Parque nacional en 1969; Patrimonio de la Humanidad en 1994; más de medio millón de aves acuáticas en invierno. Escribe «según la UNESCO» para indicar la fuente del dato y dar objetividad al texto.", lineas: 2 },
      { tipo: "opinion", q: "¿En qué estación te gustaría visitar Doñana? ¿Qué te gustaría observar y cómo te comportarías para no molestar a los animales?", r: "Respuesta libre. Valorar que relacionen la estación con lo que describe el texto.", lineas: 3 },
      { tipo: "reflexion", q: "Las aves migratorias no entienden de fronteras. ¿Por qué crees que proteger la naturaleza necesita que distintos países colaboren?", r: "Respuesta libre. Valorar la idea de que las aves dependen de lugares de varios países a lo largo de su viaje.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-06-lince",
    titulo: "El lince ibérico, la vuelta de un superviviente",
    subtipo: "Artículo de divulgación",
    curso: "5º-6º",
    fuente: "Texto original",
    datos: ["Ministerio para la Transición Ecológica y el Reto Demográfico (MITECO): censos del lince ibérico de 2024 y 2025 (España y Portugal)", "Prensa especializada sobre el cambio de categoría del lince en la Lista Roja de la UICN (2024)", "Programa de Conservación Ex-situ del Lince Ibérico (lynxexsitu.es): centros de cría"],
    antes: "¿Has oído hablar del lince ibérico? ¿Sabes por qué estuvo a punto de desaparecer?",
    texto: [
      { p: "El lince ibérico es un felino que solo vive en la península ibérica. Hace poco más de veinte años era el felino más amenazado del planeta. Hoy su población no deja de crecer gracias a un gran esfuerzo de conservación en el que Andalucía ha tenido un papel protagonista." },
      { h: "Cómo reconocerlo" },
      { p: "El lince pesa alrededor de diez kilos, más o menos el doble que un gato doméstico grande. Tiene las patas largas y la cola corta, rematada en una mancha negra. Su pelaje es pardo, con manchas oscuras. Sus rasgos más característicos son los pinceles, unos mechones de pelo negro en la punta de las orejas, y las patillas que le cuelgan a ambos lados de la cara." },
      { h: "Un cazador especialista" },
      { p: "El lince es un depredador muy especializado: su presa principal es el conejo de monte. Caza sobre todo al amanecer y al atardecer. Se acerca en silencio, escondido entre el matorral, y cuando está muy cerca da un salto rápido y corto. Es un animal solitario: cada adulto defiende su propio territorio y lo marca con olores y arañazos en los árboles." },
      { p: "Precisamente por depender tanto del conejo, cuando en el siglo XX varias enfermedades redujeron mucho el número de conejos, los linces también empezaron a desaparecer. A esto se sumaron la destrucción del monte mediterráneo, la caza ilegal y los atropellos." },
      { h: "De casi desaparecer a batir récords" },
      { p: "A comienzos de este siglo quedaban menos de cien ejemplares, repartidos en dos pequeños núcleos de Andalucía: Doñana y Sierra Morena. Entonces se pusieron en marcha programas de cría en cautividad, se recuperaron las poblaciones de conejo y se liberaron linces en nuevas zonas de España y Portugal." },
      { p: "En los centros de cría, como el de El Acebuche, en Doñana, o el de La Olivilla, en Jaén, los cachorros crecen con el menor contacto posible con las personas, para que no pierdan su miedo natural. Los cuidadores los vigilan con cámaras y les dan presas vivas para que aprendan a cazar. Antes de liberarlos, les colocan un collar con un emisor que permite seguir sus movimientos. En el campo, los científicos también usan el fototrampeo: cámaras escondidas que se disparan solas cuando pasa un animal. Como las manchas del pelaje de cada lince son diferentes, sirven para reconocerlos uno a uno." },
      { p: "Los resultados son espectaculares. Según el censo del Ministerio para la Transición Ecológica, en 2025 se contaron 2.663 linces ibéricos, un 10,9 % más que el año anterior. En 2024, la Unión Internacional para la Conservación de la Naturaleza (UICN) lo pasó de la categoría «en peligro» a la de «vulnerable»." },
      { h: "Un peligro en la carretera" },
      { p: "El lince todavía tiene problemas. En 2024 murieron 214 linces en la península, y tres de cada cuatro de esas muertes se debieron a atropellos. Por eso se construyen pasos de fauna bajo las carreteras y se colocan señales para que los conductores reduzcan la velocidad." },
      { h: "Conclusión" },
      { p: "La historia del lince demuestra que, cuando la ciencia, las administraciones y la gente del campo trabajan juntas, es posible salvar una especie. Pero su futuro depende de que sigamos cuidando su hábitat." },
    ],
    vocabulario: [
      { p: "felino", d: "Mamífero de la familia del gato, como el lince, el león o el tigre." },
      { p: "depredador", d: "Animal que caza a otros para alimentarse." },
      { p: "cautividad", d: "Situación de un animal que vive encerrado o controlado por personas." },
      { p: "fototrampeo", d: "Uso de cámaras escondidas que hacen fotos solas cuando pasa un animal." },
      { p: "hábitat", d: "Lugar con las condiciones adecuadas para que viva una especie." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué la desaparición de los conejos puso en peligro al lince? Elige:", opciones: ["Porque los conejos le contagiaban enfermedades", "Porque el conejo es su presa principal y se quedó sin alimento", "Porque los conejos le quitaban el territorio"], r: "Porque el conejo es su presa principal y se quedó sin alimento" },
      { tipo: "comprension", q: "¿Por qué crees que en los centros de cría los cachorros tienen el menor contacto posible con las personas?", r: "Para que no pierdan el miedo natural a las personas; si se acostumbran a ellas, en libertad podrían acercarse a pueblos o carreteras y correr peligro.", lineas: 2 },
      { tipo: "comprension", q: "El lince ya no está «en peligro». ¿Significa eso que ya no hay que protegerlo? Justifícalo con el texto.", r: "No: sigue siendo «vulnerable» y cada año mueren muchos linces atropellados; su futuro depende de seguir cuidando su hábitat.", lineas: 2 },
      { tipo: "texto", q: "Los textos científicos explican cómo se obtienen los datos. ¿Qué dos técnicas usan los científicos para seguir a los linces? ¿Por qué da confianza al lector que el texto las explique?", r: "Los collares con emisor y el fototrampeo (cámaras que reconocen a cada lince por sus manchas). Da confianza porque el lector sabe de dónde salen las cifras y puede entender que no son inventadas.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué medida te parece más útil para proteger al lince: los pasos de fauna, las señales o la cría en cautividad? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "reflexion", q: "La recuperación del lince fue posible porque mucha gente trabajó unida. ¿Qué problema de tu entorno podría resolverse si todos colaboraran?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-07-volcanes",
    titulo: "¿Qué ocurre dentro de un volcán?",
    subtipo: "Artículo de divulgación",
    curso: "5º-6º",
    fuente: "Texto original",
    datos: ["Instituto Geológico y Minero de España (IGME-CSIC): Inventario de Lugares de Interés Geológico, ficha IC6031 «Volcán, coladas y piroclastos de la erupción de Tajogaite de 2021»", "Parque Nacional del Teide (Red de Parques Nacionales): ficha del parque"],
    antes: "¿Has visto alguna vez imágenes de un volcán en erupción? ¿De dónde crees que sale la lava?",
    texto: [
      { p: "Los volcanes son una de las muestras más impresionantes de la energía de nuestro planeta. Pero ¿qué sucede bajo tierra para que una montaña expulse fuego, rocas y cenizas?" },
      { h: "Un planeta caliente por dentro" },
      { p: "La Tierra está formada por capas. La más externa, sobre la que vivimos, es la corteza. Debajo está el manto y, en el centro, el núcleo. En el interior del planeta las temperaturas son altísimas, y en algunas zonas las rocas llegan a fundirse. Esa roca fundida, mezclada con gases, se llama magma." },
      { h: "Cómo se produce una erupción" },
      { p: "La corteza terrestre no es una pieza única: está dividida en grandes placas tectónicas que se mueven muy despacio. En los bordes de las placas, y en algunos puntos especialmente calientes, el magma puede ascender por grietas. Como es menos denso que las rocas que lo rodean, sube y se acumula en una cámara magmática. Cuando la presión de los gases es suficiente, el magma sale al exterior: es la erupción." },
      { p: "Al llegar a la superficie, el magma pierde gases y pasa a llamarse lava. Un volcán puede expulsar coladas de lava, que avanzan como ríos incandescentes; piroclastos, que son fragmentos de roca y ceniza lanzados al aire; y gases, sobre todo vapor de agua y dióxido de carbono. La abertura por donde sale todo se llama cráter, y el conducto que la comunica con la cámara, chimenea." },
      { h: "Erupciones tranquilas y explosivas" },
      { p: "No todos los volcanes entran en erupción de la misma manera. Todo depende de cómo sea su magma. Cuando el magma es muy líquido, como un jarabe caliente, los gases escapan con facilidad y la lava sale de forma tranquila, en coladas que bajan por las laderas. Son erupciones efusivas." },
      { p: "Cuando el magma es muy espeso y pegajoso, los gases quedan atrapados, como las burbujas de una botella de refresco agitada. La presión aumenta hasta que el volcán estalla y lanza al aire enormes nubes de ceniza y rocas. Son erupciones explosivas. Así ocurrió en el año 79 con el Vesubio, en Italia, cuyas cenizas sepultaron la ciudad romana de Pompeya. Gracias a ello, los arqueólogos han podido estudiar cómo vivían sus habitantes." },
      { h: "Volcanes en España" },
      { p: "Las islas Canarias nacieron del fondo del océano por la acumulación de lava de muchísimas erupciones. En Tenerife se alza el Teide, un volcán de 3.715 metros, el pico más alto de España." },
      { p: "En 2021, la isla canaria de La Palma vivió la erupción del volcán de Tajogaite. Según el Instituto Geológico y Minero de España, comenzó el 19 de septiembre y terminó el 13 de diciembre: 85 días de actividad. Sus coladas cubrieron casas, carreteras y cultivos, aunque la evacuación a tiempo de la población evitó una tragedia mayor. Andalucía también tiene un pasado volcánico: muchas rocas y acantilados del Cabo de Gata, en Almería, se formaron por volcanes que estuvieron activos hace millones de años." },
      { h: "Conclusión" },
      { p: "Los volcanes destruyen, pero también crean: forman islas nuevas y dejan suelos muy fértiles. Los vulcanólogos vigilan los volcanes activos midiendo los terremotos, los gases y las deformaciones del terreno para avisar a la población antes de una erupción." },
    ],
    vocabulario: [
      { p: "incandescente", d: "Tan caliente que brilla y da luz." },
      { p: "denso", d: "Que tiene mucha materia en poco espacio; que pesa mucho para su tamaño." },
      { p: "efusivo", d: "Aquí, se dice de la erupción en que la lava sale y se derrama sin explosiones." },
      { p: "vulcanólogo", d: "Científico que estudia los volcanes." },
      { p: "fértil", d: "Se dice de la tierra en la que crecen bien las plantas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué diferencia hay entre magma y lava?", r: "El magma es roca fundida con gases que está en el interior de la Tierra; cuando sale a la superficie y pierde gases se llama lava.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué ocurre en una erupción explosiva? Elige:", opciones: ["La lava líquida baja tranquila por las laderas", "Los gases atrapados en un magma espeso hacen estallar el volcán", "El volcán se apaga para siempre"], r: "Los gases atrapados en un magma espeso hacen estallar el volcán" },
      { tipo: "comprension", q: "El texto dice que los volcanes «destruyen, pero también crean». Explica esta idea con dos ejemplos del texto.", r: "Destruyen casas, carreteras y cultivos, como en La Palma, o ciudades como Pompeya; pero crean islas nuevas, como las Canarias, suelos fértiles y paisajes como el del Cabo de Gata.", lineas: 2 },
      { tipo: "texto", q: "Para explicar las erupciones, el autor compara el magma con un jarabe y con una botella de refresco agitada. ¿Por qué usa comparaciones en un texto científico? ¿A qué tipo de lector va dirigido?", r: "Porque relacionar algo desconocido con algo cotidiano ayuda a entenderlo. Va dirigido a lectores no especialistas: es un texto de divulgación.", lineas: 3 },
      { tipo: "opinion", q: "¿Vivirías cerca de un volcán activo si estuviera vigilado por científicos? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "reflexion", q: "Los científicos no pueden impedir una erupción, pero sí avisar. ¿Por qué es tan importante hacer caso a los expertos en una emergencia?", r: "Respuesta libre. Valorar la relación entre conocimiento científico y seguridad.", lineas: 2 },
    ],
  },
  {
    id: "cientifico-08-termosolar",
    titulo: "Espejos que atrapan el sol",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["SENER: «Gemasolar: 24 horas de energía solar» (ficha del proyecto)", "Revista Energías Renovables: noticias sobre la puesta en marcha de Gemasolar", "Datos técnicos de la central PS10 de Sanlúcar la Mayor (Wikipedia en inglés, «PS10 solar power plant», y prensa)", "CIEMAT: Plataforma Solar de Almería (página institucional)"],
    antes: "¿Sabes cómo se puede producir electricidad con el sol? ¿Has visto alguna vez placas solares?",
    texto: [
      { p: "Andalucía recibe muchísimas horas de sol al año. Aprovechar esa luz para producir electricidad es una de las grandes apuestas de las energías renovables, las que proceden de fuentes que no se agotan. Una de las tecnologías más curiosas para conseguirlo se desarrolló, en buena parte, en Andalucía: la energía termosolar." },
      { h: "Fotovoltaica y termosolar: no es lo mismo" },
      { p: "Las placas solares de los tejados son paneles fotovoltaicos: transforman la luz directamente en electricidad gracias a materiales como el silicio. Las centrales termosolares funcionan de otra manera. No aprovechan la luz, sino el calor del sol, que concentran con espejos para calentar un líquido. Ese calor produce vapor de agua, el vapor mueve una turbina y la turbina hace girar un generador eléctrico." },
      { p: "La idea de concentrar el sol es muy antigua. Si alguna vez has usado una lupa para juntar los rayos del sol en un punto, habrás notado que ese puntito se calienta muchísimo. Una central termosolar hace lo mismo, pero a lo grande y con espejos en lugar de lentes." },
      { h: "Una torre rodeada de espejos" },
      { p: "En las centrales de torre, cientos o miles de espejos llamados heliostatos siguen el movimiento del sol a lo largo del día, dirigidos por ordenador. Todos reflejan la luz hacia un mismo punto: un receptor situado en lo alto de una torre, donde se alcanzan temperaturas muy elevadas." },
      { p: "En 2007 se inauguró en Sanlúcar la Mayor (Sevilla) la PS10, considerada la primera central comercial de torre del mundo. Tiene 624 heliostatos y una torre de 115 metros. Unos años después empezó a funcionar en Fuentes de Andalucía (Sevilla) la central Gemasolar, con 2.650 heliostatos que ocupan unas 185 hectáreas." },
      { h: "El secreto de las sales fundidas" },
      { p: "El gran problema de la energía solar es que de noche no hay sol. Gemasolar fue la primera central comercial de torre que usó sales fundidas para recoger y almacenar el calor. Estas sales, parecidas a algunos abonos, se calientan durante el día y guardan la energía en grandes tanques, igual que un termo conserva caliente la leche. Así, la central puede seguir produciendo electricidad hasta 15 horas sin sol, y ha llegado a funcionar las 24 horas del día." },
      { p: "En la provincia de Granada, en la comarca del Marquesado del Zenete, las centrales Andasol usan otra técnica: largas filas de espejos curvos, llamados colectores cilindroparabólicos, que calientan un aceite especial." },
      { h: "Un laboratorio en el desierto" },
      { p: "Muchos de estos avances no habrían sido posibles sin la investigación. En el desierto de Tabernas, en Almería, se encuentra la Plataforma Solar de Almería, que pertenece al CIEMAT, un organismo público de investigación. Desde los años ochenta del siglo pasado, científicos e ingenieros de muchos países prueban allí nuevos espejos, receptores y formas de almacenar el calor. Tabernas es un lugar ideal: tiene muchísimos días despejados y muy pocas lluvias. Lo que funciona en la plataforma se aplica después en centrales de todo el mundo." },
      { h: "Conclusión" },
      { p: "La energía termosolar apenas emite gases contaminantes al producir electricidad y aprovecha un recurso abundante en el sur de España. Sus inconvenientes son que necesita mucho terreno y cielos despejados. Aun así, las centrales andaluzas han servido de modelo para proyectos de todo el mundo." },
    ],
    vocabulario: [
      { p: "renovable", d: "Que se renueva de forma natural y no se agota, como el sol o el viento." },
      { p: "turbina", d: "Máquina con una rueda de paletas que gira empujada por un fluido, como el vapor." },
      { p: "generador", d: "Aparato que transforma el movimiento en electricidad." },
      { p: "hectárea", d: "Medida de superficie de 10.000 metros cuadrados, algo más que un campo de fútbol." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué es un heliostato? Elige:", opciones: ["Un tanque de sales fundidas", "Un espejo que sigue al sol y refleja su luz hacia la torre", "El generador de una central"], r: "Un espejo que sigue al sol y refleja su luz hacia la torre" },
      { tipo: "comprension", q: "Ordena los pasos para producir electricidad en una central de torre: vapor, turbina, heliostatos, receptor, generador.", r: "Heliostatos → receptor en la torre → vapor → turbina → generador.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que la Plataforma Solar se construyó en Tabernas y no, por ejemplo, en el norte de Europa?", r: "Porque Tabernas tiene muchísimos días despejados y muy pocas lluvias, imprescindibles para probar la energía del sol.", lineas: 2 },
      { tipo: "texto", q: "Un texto científico objetivo muestra ventajas e inconvenientes sin exagerar. Copia una ventaja y un inconveniente de la energía termosolar. ¿Por qué deben aparecer los dos?", r: "Ventaja: apenas emite gases contaminantes y aprovecha un recurso abundante. Inconveniente: necesita mucho terreno y cielos despejados. Porque la objetividad exige dar la información completa para que el lector saque sus propias conclusiones.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parecería bien que se construyera una central termosolar cerca de tu localidad? Da un argumento a favor y otro en contra.", r: "Respuesta libre. Valorar que den argumentos de ambos lados.", lineas: 3 },
      { tipo: "reflexion", q: "Los inventos se mejoran con el trabajo de muchas personas a lo largo de los años. ¿Qué ejemplo del texto lo demuestra? ¿Conoces otro?", r: "Respuesta libre. Valorar que relacionen la PS10 con Gemasolar, que añadió el almacenamiento con sales, o la Plataforma Solar, cuyos avances se aplican en todo el mundo.", lineas: 2 },
    ],
  },
  {
    id: "cientifico-09-vacuna",
    titulo: "La vacuna, una idea que cambió la historia",
    subtipo: "Artículo de divulgación (historia de la ciencia)",
    curso: "6º",
    fuente: "Texto original",
    datos: ["Organización Mundial de la Salud (OMS): «La OMS conmemora el 40.º aniversario de la erradicación de la viruela» (2019)", "CSIC: «Balmis: la expedición española que llevó la vacuna de la viruela a Asia y América»", "Comité Asesor de Vacunas de la Asociación Española de Pediatría: «Isabel Zendal y la expedición Balmis»", "Institut Pasteur: biografía de Louis Pasteur y vacuna contra la rabia (1885)"],
    antes: "¿Sabes por qué nos ponemos vacunas? ¿Recuerdas alguna que te hayan puesto?",
    texto: [
      { p: "Durante siglos, la viruela fue una de las enfermedades más temidas del mundo. Era muy contagiosa, provocaba fiebre alta y ampollas por todo el cuerpo, y dejaba cicatrices en muchas personas. Hoy ya no existe. ¿Cómo se consiguió? Con uno de los inventos más importantes de la medicina: la vacuna." },
      { h: "Una observación en el campo" },
      { p: "A finales del siglo XVIII, el médico inglés Edward Jenner se fijó en algo curioso: las lecheras que se contagiaban de la viruela de las vacas, una enfermedad leve, no solían enfermar después de la viruela humana. En 1796 hizo un experimento: tomó material de una lesión de viruela vacuna y lo introdujo en un pequeño corte en el brazo de un niño. Más tarde comprobó que el niño no enfermaba de viruela. De la palabra latina vacca, «vaca», procede el nombre de vacuna." },
      { h: "Los microbios, unos enemigos invisibles" },
      { p: "Jenner no sabía qué causaba la viruela. Hoy sabemos que muchas enfermedades infecciosas las provocan microbios, seres tan pequeños que solo se ven con microscopio. Los más conocidos son las bacterias y los virus. La viruela, el sarampión o la gripe son enfermedades causadas por virus." },
      { p: "En el siglo XIX, el científico francés Louis Pasteur demostró que los microbios causan enfermedades y aprendió a debilitarlos en su laboratorio para fabricar nuevas vacunas. En 1885 aplicó con éxito su vacuna contra la rabia a un niño al que había mordido un perro enfermo. En honor a Jenner, Pasteur propuso llamar vacunas a todas estas preparaciones, aunque ya no tuvieran nada que ver con las vacas." },
      { h: "¿Cómo funciona una vacuna?" },
      { p: "Nuestro cuerpo tiene un sistema de defensa llamado sistema inmunitario. Cuando entra un microbio, fabrica unas sustancias llamadas anticuerpos para combatirlo y, además, lo recuerda. Una vacuna contiene el microbio debilitado o inactivado, o solo una parte de él, de modo que no causa la enfermedad. Así, el sistema inmunitario aprende a reconocerlo. Si más tarde llega el microbio real, las defensas actúan con rapidez." },
      { h: "Una expedición española alrededor del mundo" },
      { p: "En 1803, el médico alicantino Francisco Javier Balmis dirigió la Real Expedición Filantrópica de la Vacuna, que partió de La Coruña. Como entonces no había neveras, la vacuna viajó en los brazos de 22 niños: se vacunaba a dos de ellos y, cuando les aparecían las lesiones, se pasaba el material a otros dos, en cadena. Los cuidaba Isabel Zendal, a quien la OMS considera la primera enfermera de una misión sanitaria internacional. La expedición llevó la vacuna a América y a Asia." },
      { h: "Un éxito mundial" },
      { p: "Gracias a campañas de vacunación en todos los países, en 1980 la Organización Mundial de la Salud declaró erradicada la viruela. Es la única enfermedad humana que se ha conseguido eliminar por completo. Hoy existen vacunas contra muchas otras, como el sarampión, la polio o el tétanos. En España, las vacunas de la infancia siguen un calendario: cada una se pone a una edad determinada, y así los niños quedan protegidos desde muy pequeños." },
      { h: "Conclusión" },
      { p: "La historia de la vacuna muestra cómo funciona la ciencia: observación, hipótesis, experimento y comprobación. También enseña que la salud de cada persona depende, en parte, de la de los demás: cuantas más personas se vacunan, más difícil es que una enfermedad se propague." },
    ],
    vocabulario: [
      { p: "erradicar", d: "Eliminar algo por completo." },
      { p: "microbio", d: "Ser vivo tan pequeño que solo se puede ver con microscopio." },
      { p: "inmunitario", d: "Relacionado con las defensas del cuerpo contra las enfermedades." },
      { p: "filantrópico", d: "Que se hace por amor a los demás, para ayudarlos." },
      { p: "hipótesis", d: "Explicación posible que hay que comprobar." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿De dónde procede la palabra vacuna? Elige:", opciones: ["Del apellido de su inventor", "De la palabra latina vacca, «vaca»", "De vacío, porque se inyecta vacía"], r: "De la palabra latina vacca, «vaca»" },
      { tipo: "comprension", q: "¿Qué aportó Pasteur a la historia de las vacunas que Jenner no había podido explicar?", r: "Demostró que los microbios causan las enfermedades y aprendió a debilitarlos en el laboratorio para fabricar nuevas vacunas, como la de la rabia.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la vacuna viajó en los brazos de niños en la expedición de Balmis?", r: "Porque no había neveras para conservarla; se mantenía activa pasando el material de un niño vacunado a otro, en cadena.", lineas: 2 },
      { tipo: "texto", q: "La conclusión nombra los pasos del método científico. Relaciona cada uno con lo que hizo Jenner.", r: "Observación: las lecheras no enfermaban. Hipótesis: la viruela vacuna protege de la humana. Experimento: vacunar a un niño en 1796. Comprobación: el niño no enfermó de viruela.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué opinas de la labor de Isabel Zendal? ¿Por qué crees que durante mucho tiempo fue poco conocida?", r: "Respuesta libre. Valorar la reflexión sobre el reconocimiento del trabajo de las mujeres y de los cuidados.", lineas: 2 },
      { tipo: "reflexion", q: "La conclusión dice que la salud de cada persona depende en parte de la de los demás. ¿Qué quiere decir? ¿Se te ocurren otras situaciones en las que lo que haces tú afecta a los demás?", r: "Respuesta libre. Valorar que expliquen que si muchas personas están vacunadas el microbio se propaga menos y se protege a quien no puede vacunarse.", lineas: 3 },
    ],
  },
  {
    id: "cientifico-10-clima",
    titulo: "El cambio climático, explicado con calma",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["IPCC (Grupo Intergubernamental de Expertos sobre el Cambio Climático): Sexto Informe de Evaluación, Grupo de Trabajo I (2021), Resumen para responsables de políticas", "Organización Meteorológica Mundial (OMM): confirmación de 2024 como año más cálido registrado (Noticias ONU, enero de 2025)", "British Antarctic Survey: «Ice cores and climate change»"],
    antes: "¿Qué has oído sobre el cambio climático? ¿Te preocupa? ¿Por qué?",
    texto: [
      { h: "Tiempo y clima" },
      { p: "Si mañana llueve en Sevilla, hablamos del tiempo atmosférico: lo que ocurre en un lugar durante unas horas o unos días. El clima, en cambio, es el tiempo habitual de una región a lo largo de muchos años, normalmente treinta o más. Un día frío en agosto no cambia el clima; lo que lo cambia son las tendencias que se repiten durante décadas." },
      { h: "El efecto invernadero" },
      { p: "La Tierra está rodeada por la atmósfera, una capa de gases. Algunos de ellos, como el vapor de agua, el dióxido de carbono (CO2) y el metano, dejan pasar la luz del Sol, pero retienen parte del calor que la Tierra devuelve al espacio. Es el efecto invernadero natural, y es imprescindible: sin él, la temperatura media del planeta sería de unos 18 grados bajo cero." },
      { p: "Seguro que has notado algo parecido en un coche aparcado al sol con las ventanillas cerradas. La luz atraviesa los cristales y calienta los asientos, pero el calor no puede salir con la misma facilidad, y el interior acaba mucho más caliente que la calle. Los gases de efecto invernadero actúan de forma parecida, como una manta invisible." },
      { h: "¿Qué está cambiando?" },
      { p: "Desde el siglo XIX, la humanidad quema grandes cantidades de carbón, petróleo y gas para producir energía, mover vehículos y fabricar objetos. Esa combustión libera CO2, que se acumula en la atmósfera y refuerza el efecto invernadero. Además, la tala de bosques reduce el número de árboles que absorben ese gas." },
      { p: "El Grupo Intergubernamental de Expertos sobre el Cambio Climático (IPCC), formado por científicos de todo el mundo, concluyó en su informe de 2021 que es inequívoco que la actividad humana ha calentado el planeta. Según la Organización Meteorológica Mundial, 2024 fue el año más cálido desde que hay registros: la temperatura media global superó en unos 1,55 °C la de la época preindustrial." },
      { h: "¿Cómo lo saben los científicos?" },
      { p: "Para saber si el clima cambia, hay que compararlo con el del pasado. Desde hace más de un siglo, miles de estaciones meteorológicas miden cada día la temperatura y la lluvia, y hoy los satélites observan el planeta entero desde el espacio. Pero ¿cómo se conoce el clima de épocas en las que nadie lo medía?" },
      { p: "Una de las respuestas está en el hielo de la Antártida. Allí, la nieve se acumula año tras año y se convierte en hielo, atrapando pequeñas burbujas de aire. Los científicos perforan el hielo y sacan largos cilindros, llamados testigos de hielo. Analizando esas burbujas saben cuánto CO2 había en el aire hace cientos de miles de años. También los anillos de los troncos de los árboles guardan pistas: en los años cálidos y húmedos, los árboles crecen más y el anillo es más ancho." },
      { h: "Consecuencias" },
      { p: "Un grado y medio puede parecer poco, pero para el planeta es mucho. Los científicos observan que los glaciares retroceden, el nivel del mar sube y las olas de calor son más frecuentes e intensas. En regiones como el sur de España se esperan veranos más largos y calurosos y sequías más frecuentes." },
      { h: "Qué podemos hacer" },
      { p: "La buena noticia es que conocemos las causas y, por tanto, las soluciones. Muchos países se comprometieron a reducir sus emisiones en el Acuerdo de París de 2015. Las energías renovables, el transporte público, la bicicleta, el ahorro de energía y la protección de los bosques ayudan a frenar el calentamiento. Además, las ciudades pueden adaptarse al calor con más árboles, más sombra y edificios mejor aislados." },
      { h: "Conclusión" },
      { p: "El cambio climático es un problema serio, pero no es un motivo para el miedo, sino para la acción. La ciencia nos da la información; usarla bien depende de todos." },
    ],
    vocabulario: [
      { p: "inequívoco", d: "Que no deja lugar a dudas." },
      { p: "preindustrial", d: "Anterior a la aparición de las grandes industrias (en este caso, el periodo de 1850 a 1900)." },
      { p: "combustión", d: "Acción de quemar algo." },
      { p: "perforar", d: "Hacer un agujero atravesando algo." },
      { p: "emisión", d: "Expulsión de gases u otras sustancias al aire." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Según el texto, sin el efecto invernadero natural, la Tierra… Elige:", opciones: ["sería más cálida que ahora", "tendría una temperatura media de unos 18 grados bajo cero", "no tendría atmósfera"], r: "tendría una temperatura media de unos 18 grados bajo cero" },
      { tipo: "comprension", q: "¿Por qué el hielo de la Antártida sirve para conocer el clima del pasado?", r: "Porque al formarse atrapa burbujas de aire; analizándolas se sabe cuánto CO2 había en la atmósfera hace cientos de miles de años.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice el autor que «un día frío en agosto no cambia el clima»?", r: "Porque el clima se estudia con tendencias de muchos años; un día aislado es solo tiempo atmosférico y no demuestra nada sobre el clima.", lineas: 2 },
      { tipo: "texto", q: "¿Por qué el texto cita al IPCC y a la Organización Meteorológica Mundial en lugar de decir «yo creo que el planeta se calienta»? ¿Qué característica del texto científico demuestra?", r: "Porque se apoya en fuentes expertas y datos comprobables, no en opiniones personales. Demuestra su objetividad.", lineas: 2 },
      { tipo: "opinion", q: "Algunas personas sienten angustia al oír hablar del cambio climático. ¿Qué le dirías a un compañero que se siente así?", r: "Respuesta libre. Valorar mensajes realistas y esperanzadores basados en el texto.", lineas: 3 },
      { tipo: "reflexion", q: "Las decisiones de hoy afectarán a quienes vivan dentro de cincuenta años. ¿Es justo pensar en las personas del futuro al tomar decisiones? ¿Por qué?", r: "Respuesta libre. Valorar la argumentación.", lineas: 3 },
    ],
  },
];
