// Lecturas · Texto descriptivo (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["descriptivo"] = [
  {
    id: "descriptivo-01-camaleon",
    titulo: "El camaleón común, un reptil de otro mundo",
    subtipo: "Descripción de un animal",
    curso: "5º",
    fuente: "Texto original",
    datos: ["MITECO: Atlas y Libro Rojo de los Anfibios y Reptiles de España, ficha de Chamaeleo chamaeleon (camaleón común)"],
    antes: "¿Has visto alguna vez un camaleón? ¿Qué sabes de él?",
    texto: [
      { p: "En algunos pinares, huertos y jardines de la costa andaluza, desde Huelva hasta Almería, vive un animal que parece sacado de una película de ciencia ficción: el camaleón común. Es el único camaleón de Europa, y hay que tener muy buena vista para descubrirlo entre las ramas." },
      { p: "Empecemos por la cabeza. Es grande, con forma de casco, y termina en una cresta abultada. A los lados tiene dos ojos saltones, cubiertos casi por completo de piel escamosa, con un pequeño agujero en el centro para la pupila. Lo más asombroso es que cada ojo se mueve por su cuenta: puede mirar hacia delante con uno y hacia atrás con el otro, como si llevara dos cámaras de vigilancia." },
      { p: "Su cuerpo es estrecho y aplanado por los lados, como una hoja. La piel, rugosa y cubierta de escamas diminutas, suele ser verde, parda o amarillenta, con manchas y rayas más claras. El camaleón cambia de color, pero no solo para esconderse: su piel se oscurece o se aclara según la temperatura, la luz o si está tranquilo o alterado." },
      { p: "Bajando hacia las patas, encontramos otro invento curioso. Sus dedos están unidos en dos grupos enfrentados que funcionan como unas pinzas y le permiten agarrarse con fuerza a las ramas. Detrás, la cola, larga y prensil, se enrosca como un muelle y le sirve de quinta mano." },
      { p: "Pero su arma secreta está escondida en la boca. Cuando descubre un saltamontes o una mosca, dispara una lengua larguísima, pegajosa y con la punta ensanchada, y atrapa a su presa en un abrir y cerrar de ojos." },
      { p: "El camaleón es lento, tímido e inofensivo. En España se considera una especie casi amenazada por la destrucción de su hábitat, los atropellos, los ataques de animales domésticos y la captura ilegal. Si alguna vez ves uno, obsérvalo sin tocarlo y déjalo donde está." },
    ],
    vocabulario: [
      { p: "cresta", d: "Saliente que tienen algunos animales en lo alto de la cabeza." },
      { p: "pupila", d: "Círculo negro del centro del ojo por donde entra la luz." },
      { p: "rugoso", d: "Que tiene arrugas o una superficie áspera." },
      { p: "prensil", d: "Que sirve para agarrar o sujetar." },
      { p: "hábitat", d: "Lugar con las condiciones adecuadas para que viva una especie." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Dónde vive el camaleón común en España?", r: "En pinares, huertos y jardines de la costa andaluza, desde Huelva hasta Almería.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué la cola del camaleón es como una «quinta mano»? Elige:", opciones: ["Porque tiene dedos", "Porque puede enroscarse y agarrarse a las ramas", "Porque le sirve para atrapar insectos"], r: "Porque puede enroscarse y agarrarse a las ramas" },
      { tipo: "comprension", q: "Según el texto, ¿el camaleón cambia de color solo para esconderse? Explícalo.", r: "No: también cambia según la temperatura, la luz o si está tranquilo o alterado.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué ventaja tiene para el camaleón poder mover cada ojo por separado?", r: "Puede vigilar dos direcciones a la vez: buscar presas y descubrir peligros sin mover el cuerpo.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el texto aconseja no tocar al camaleón ni llevárselo a casa?", r: "Porque es una especie casi amenazada y la captura le perjudica; además es un animal tímido y delicado.", lineas: 2 },
      { tipo: "texto", q: "Esta descripción de un animal sigue un orden. ¿Qué partes describe y en qué orden? Copia dos comparaciones que ayuden a imaginarlo.", r: "Cabeza y ojos → cuerpo y piel → patas y cola → lengua (de delante hacia atrás y de arriba abajo). Comparaciones: «como si llevara dos cámaras de vigilancia», «aplanado por los lados, como una hoja», «funcionan como unas pinzas», «se enrosca como un muelle».", lineas: 3 },
      { tipo: "opinion", q: "¿Qué característica del camaleón te parece más sorprendente? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "Si pudieras tener durante un día un «poder» del camaleón, ¿cuál elegirías? ¿Para qué lo usarías?", r: "Respuesta libre. Valorar que justifiquen la elección.", lineas: 3 },
      { tipo: "reflexion", q: "Muchos animales pequeños y discretos están en peligro sin que casi nadie lo sepa. ¿Por qué crees que reciben menos atención que los animales grandes? ¿Te parece justo?", r: "Respuesta libre. Valorar la argumentación.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-02-abuela",
    titulo: "Mi abuela Carmen",
    subtipo: "Retrato",
    curso: "5º",
    fuente: "Texto original",
    antes: "Piensa en una persona mayor a la que quieras mucho. ¿Cómo es por fuera? ¿Y por dentro?",
    texto: [
      { p: "Mi abuela Carmen tiene setenta y dos años y la risa más contagiosa del barrio. Es bajita, tan bajita que tiene que ponerse de puntillas para darme un beso en la frente, aunque ella dice que es porque yo crezco demasiado deprisa." },
      { p: "Tiene el pelo corto y blanco como la espuma, siempre algo despeinado por el viento de la azotea, donde cuida sus macetas. Su cara es redonda y morena, llena de arrugas finas que se juntan en las esquinas de los ojos cuando sonríe, como los rayos de un sol dibujado por un niño. Sus ojos son pequeños, castaños y vivísimos: no se les escapa nada. Lleva colgadas de un cordón unas gafas de montura roja que casi nunca usa, porque, según ella, ya se sabe el mundo de memoria." },
      { p: "Lo que más me gusta de ella son sus manos. Son anchas, suaves por la palma y ásperas por los nudillos, con restos de tierra de las macetas y olor a limón. Con esas manos amasa las mejores tortas del mundo, arregla enchufes y cose botones a una velocidad que parece magia." },
      { p: "Pero la abuela no solo es especial por fuera. Es curiosa como un gato: se ha apuntado a clases de informática y ahora me manda mensajes con más emoticonos que palabras. Es paciente, muy paciente, sobre todo cuando me explica las fracciones con trozos de bizcocho. También es terca: cuando dice que va a llover, coge el paraguas aunque el cielo esté azul. Y casi siempre acierta." },
      { p: "Es generosa sin hacer ruido. Si una vecina está enferma, aparece en su puerta con un táper de puchero; si alguien del barrio se siente solo, lo invita a jugar al dominó en la plaza. Nunca presume de nada, pero todo el mundo la conoce." },
      { p: "No sé si de mayor seré bajita o alta, rubia o morena. Lo que sí sé es que quiero tener unas manos como las suyas: manos que siempre están haciendo algo por los demás." },
    ],
    vocabulario: [
      { p: "azotea", d: "Terraza en lo alto de un edificio." },
      { p: "nudillo", d: "Parte abultada de las articulaciones de los dedos." },
      { p: "terco", d: "Que mantiene su opinión aunque otros piensen distinto." },
      { p: "puchero", d: "Guiso de garbanzos, verduras y carne; cocido." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cómo es físicamente la abuela Carmen? Escribe tres rasgos.", r: "Bajita; pelo corto y blanco; cara redonda y morena con arrugas finas; ojos pequeños, castaños y vivos; gafas de montura roja; manos anchas.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué casi nunca usa las gafas? Elige:", opciones: ["Porque las ha perdido", "Porque dice que ya se sabe el mundo de memoria", "Porque no le gusta el color rojo"], r: "Porque dice que ya se sabe el mundo de memoria" },
      { tipo: "comprension", q: "¿Qué hace la abuela cuando alguien del barrio la necesita?", r: "Lleva puchero a la vecina enferma e invita a jugar al dominó a quien se siente solo.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir la nieta con la expresión «es generosa sin hacer ruido»?", r: "Que ayuda a los demás sin presumir ni buscar que se lo agradezcan.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que la nieta admira tanto las manos de su abuela?", r: "Porque representan todo lo que hace: cocinar, arreglar cosas, cuidar plantas y ayudar a los demás.", lineas: 2 },
      { tipo: "texto", q: "Este texto es un retrato. ¿Qué párrafos son prosopografía y cuáles etopeya? ¿Es una descripción objetiva o subjetiva? Justifícalo con una expresión del texto.", r: "Prosopografía: párrafos 1 a 3 (aspecto físico y manos). Etopeya: párrafos 4 y 5 (curiosa, paciente, terca, generosa). Es subjetiva: «la risa más contagiosa del barrio», «las mejores tortas del mundo», «lo que más me gusta».", lineas: 3 },
      { tipo: "opinion", q: "¿Qué persona mayor de tu entorno te gustaría describir? ¿Qué rasgo de su carácter destacarías y por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "La abuela aprende informática a los setenta y dos años. ¿Crees que nunca es tarde para aprender? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten con ejemplos.", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué pueden aprender los niños de las personas mayores? ¿Y qué pueden enseñarles ellos a cambio?", r: "Respuesta libre. Valorar el respeto y la idea de aprendizaje mutuo.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-03-objeto-misterioso",
    titulo: "El objeto del trastero",
    subtipo: "Descripción de un objeto",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has encontrado alguna vez un objeto antiguo y no sabías para qué servía? ¿Cómo lo averiguaste?",
    texto: [
      { p: "El sábado, mientras ayudábamos a ordenar el trastero de la tía Rosario, mi amigo Iker y yo encontramos una caja de madera cubierta de polvo. Dentro había un objeto que ninguno de los dos supo reconocer. Decidimos hacer lo que hacen los científicos: describirlo con detalle antes de sacar conclusiones. Esta es nuestra ficha." },
      { h: "Descripción del objeto" },
      { p: "Es un objeto pequeño y pesado. La base es un cubo de madera oscura, de unos quince centímetros de alto, con las esquinas redondeadas por el uso. En la parte delantera tiene un cajoncito con un tirador de latón, redondo y del tamaño de un botón." },
      { p: "Sobre el cubo hay una pieza de metal gris oscuro con forma de cuenco. En el centro del cuenco sobresale un eje vertical y, encima, una manivela curvada que termina en un pomo de madera torneada. Cuando giramos la manivela, se oye un chirrido metálico, como el de una bicicleta vieja, y dentro algo da vueltas." },
      { p: "Al abrir el cajoncito encontramos un polvillo marrón que olía un poco a desayuno. En un lateral del cubo, casi borrada, se lee una inscripción: «Hecho a mano, 1953»." },
      { h: "Nuestra hipótesis" },
      { p: "Iker pensó primero que era una caja de música, porque tenía manivela. Yo creí que era un sacapuntas antiguo. Pero el olor del cajón nos dio la pista definitiva. Se lo enseñamos a la tía Rosario, que se echó a reír." },
      { p: "—Es el molinillo de café de mi madre —nos explicó—. Se echaban los granos en el cuenco, se giraba la manivela y el café molido caía en el cajón. Antes casi nadie compraba el café ya molido." },
      { p: "Esa tarde lo limpiamos, le pusimos un poco de aceite en el eje y molimos café de verdad. El chirrido desapareció, pero el olor a desayuno llenó toda la casa." },
    ],
    vocabulario: [
      { p: "latón", d: "Metal de color dorado, mezcla de cobre y cinc." },
      { p: "manivela", d: "Pieza en forma de codo que se gira con la mano para mover un mecanismo." },
      { p: "torneado", d: "Trabajado en una máquina (torno) que le da forma redondeada." },
      { p: "inscripción", d: "Texto escrito o grabado sobre un objeto." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Dónde encontraron los niños el objeto?", r: "En una caja de madera cubierta de polvo, en el trastero de la tía Rosario.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué pista les ayudó a descubrir qué era? Elige:", opciones: ["La inscripción del lateral", "El olor del polvillo del cajón", "El chirrido de la manivela"], r: "El olor del polvillo del cajón" },
      { tipo: "comprension", q: "¿Para qué servía el objeto y cómo se usaba?", r: "Para moler café: se echaban los granos en el cuenco, se giraba la manivela y el café molido caía en el cajón.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que los niños decidieron describir el objeto antes de adivinar qué era?", r: "Para no equivocarse con suposiciones rápidas: al observar con detalle aparecen pistas, como hacen los científicos.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué desapareció el chirrido al final?", r: "Porque pusieron aceite en el eje y así lo engrasaron.", lineas: 1 },
      { tipo: "texto", q: "La ficha de los niños es una descripción objetiva. Copia un ejemplo de medida, uno de material, uno de forma y uno de color. ¿En qué orden describen el objeto?", r: "Medida: unos quince centímetros de alto. Material: madera, latón, metal. Forma: cubo, cuenco, manivela curvada. Color: madera oscura, gris oscuro, polvillo marrón. Orden: de abajo arriba (base y cajón, cuenco, eje y manivela) y después el interior del cajón y la inscripción.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué objeto antiguo de tu casa te gustaría investigar? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece buena idea conservar objetos antiguos aunque ya no se usen? Da tus razones.", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "reflexion", q: "Los objetos cuentan cómo vivían las personas. ¿Qué objeto actual crees que sorprenderá a los niños dentro de setenta años? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-04-mercado",
    titulo: "El mercado de abastos de mi pueblo",
    subtipo: "Topografía (descripción de un lugar)",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has ido alguna vez a un mercado de abastos? ¿Qué es lo que más te llamó la atención?",
    texto: [
      { p: "Los sábados por la mañana acompaño a mi padre al mercado de abastos de mi pueblo, en la costa de Huelva. Es un edificio antiguo, blanco y alargado, con un tejado de tejas rojas y un gran portón verde. Nada más cruzarlo, el ruido, los colores y los olores te envuelven como una ola." },
      { p: "A la izquierda de la entrada están los puestos de pescado. Sobre montañas de hielo picado brillan las sardinas plateadas, las gambas rosadas, los chocos de piel manchada y las coquinas diminutas, apretadas como botones en una caja. Los pescaderos, con sus delantales de goma, cantan los precios a voces. El suelo siempre está mojado y huele a mar." },
      { p: "En el centro, formando un pasillo ancho, se alinean las fruterías. Parecen un cuadro lleno de colores: tomates rojos y brillantes, pimientos verdes y amarillos, naranjas perfumadas, fresas que parecen pequeños corazones y sandías enormes, rayadas como balones de playa. La frutera, Remedios, siempre me regala una mandarina y me pregunta qué tal van las notas." },
      { p: "Al fondo, junto a una ventana grande, están los puestos más tranquilos. En la tienda de especias hay sacos abiertos de pimentón, comino y canela que llenan el aire de un olor cálido. En un rincón hay un pequeño bar donde los vendedores toman café en taburetes altos. Por encima de todo, bajo el techo de vigas de hierro, revolotean dos gorriones atentos a las migas." },
      { p: "Me gusta el mercado porque es mucho más que un lugar para comprar. Allí la gente se saluda por su nombre, se cuentan las noticias del pueblo y se aprende a elegir un buen melón. Cuando salimos con las bolsas llenas, siempre pienso que el mercado es el corazón del pueblo, y que late con más fuerza los sábados." },
    ],
    vocabulario: [
      { p: "abastos", d: "Productos de alimentación que se venden para abastecer a la población." },
      { p: "portón", d: "Puerta grande." },
      { p: "especia", d: "Sustancia vegetal que da sabor y olor a las comidas, como el pimentón o la canela." },
      { p: "taburete", d: "Asiento sin brazos ni respaldo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué se vende a la izquierda de la entrada? ¿Y en el centro del mercado?", r: "A la izquierda, pescado y marisco; en el centro, frutas y verduras.", lineas: 2 },
      { tipo: "comprension", q: "¿Con qué compara el narrador las coquinas? Elige:", opciones: ["Con pequeños corazones", "Con botones apretados en una caja", "Con balones de playa"], r: "Con botones apretados en una caja" },
      { tipo: "comprension", q: "¿Quién es Remedios y qué hace cada sábado?", r: "Es la frutera; le regala una mandarina al narrador y le pregunta por sus notas.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el narrador cuando afirma que el mercado es «el corazón del pueblo»?", r: "Que es el centro de la vida del pueblo: allí la gente se reúne, se conoce y se cuenta las noticias.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el suelo de la zona del pescado siempre está mojado?", r: "Por el hielo picado que se derrite y el agua con la que se limpia el pescado.", lineas: 1 },
      { tipo: "texto", q: "Esta topografía sigue un orden espacial. Copia las expresiones que indican dónde está cada zona. ¿A qué sentidos se dirige el autor? Pon un ejemplo de dos de ellos.", r: "A la izquierda de la entrada, en el centro, al fondo, en un rincón, por encima de todo. Vista (colores de las frutas), oído (cantan los precios a voces), olfato (huele a mar, olor cálido de las especias), tacto (suelo mojado), gusto (la mandarina).", lineas: 3 },
      { tipo: "opinion", q: "¿Prefieres comprar en un mercado de abastos o en un supermercado? Da dos razones.", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "opinion", q: "¿En qué lugar de tu barrio o pueblo se reúne más la gente? ¿Por qué crees que es así?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "En los pequeños comercios conocen a los clientes por su nombre. ¿Qué se gana y qué se pierde cuando desaparecen?", r: "Respuesta libre. Valorar la reflexión sobre la convivencia y la vida del barrio.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-05-patio-cordobes",
    titulo: "Un patio de Córdoba en mayo",
    subtipo: "Topografía (descripción de un lugar)",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Sabes qué son los patios cordobeses? ¿Por qué crees que en mayo mucha gente va a visitarlos?",
    texto: [
      { p: "En mayo, Córdoba abre sus patios, y mi prima Aurora y yo fuimos a visitar el de la señora Pilar, en el barrio de San Basilio. Desde la calle solo se veía una fachada encalada y una puerta de madera. Nadie diría que detrás se escondía un pequeño paraíso." },
      { p: "Primero cruzamos el zaguán, un pasillo fresco y en penumbra con el suelo de losas de barro. Al fondo, una cancela de hierro llena de rizos y espirales, como un encaje negro, dejaba ver un rectángulo de luz y de verde. Al atravesarla, nos quedamos con la boca abierta." },
      { p: "El patio es cuadrado y no muy grande. En el centro hay un pozo antiguo con un brocal de piedra gastada, rodeado de un suelo de chinos, piedrecitas blancas y negras que forman dibujos de estrellas. Junto al pozo, una fuente pequeña deja caer un hilo de agua con un murmullo que calma el calor." },
      { p: "Pero lo que de verdad asombra son las paredes. Están pintadas de un blanco tan intenso que casi hace daño a los ojos, y cubiertas de arriba abajo por decenas de macetas azules. De ellas cuelgan geranios rojos, gitanillas rosas y claveles que parecen pequeñas llamas. En una esquina, un limonero perfuma el aire." },
      { p: "A la derecha, una escalera estrecha sube hasta una galería de arcos desde la que se ve el patio entero, como un cuadro enmarcado. Arriba del todo, el cielo de mayo parece un techo azul hecho a medida." },
      { p: "La señora Pilar nos contó que regar las macetas le lleva cada día más de una hora, y que usa una caña larga con una lata en la punta para llegar a las más altas. Al despedirnos, nos regaló un clavel a cada una. Cuando salimos, el ruido y el sol de la calle nos parecieron de otro mundo." },
    ],
    vocabulario: [
      { p: "encalado", d: "Pintado de blanco con cal." },
      { p: "zaguán", d: "Espacio cubierto que hay a la entrada de una casa, junto a la puerta de la calle." },
      { p: "cancela", d: "Verja de hierro que separa el zaguán del patio." },
      { p: "brocal", d: "Borde de piedra que rodea la boca de un pozo." },
      { p: "galería", d: "Pasillo con arcos o columnas abierto hacia un patio." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿En qué mes y en qué barrio de Córdoba está el patio que visitan?", r: "En mayo, en el barrio de San Basilio.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué es el zaguán? Elige:", opciones: ["El pozo del patio", "El pasillo de entrada desde la calle", "La galería de arcos"], r: "El pasillo de entrada desde la calle" },
      { tipo: "comprension", q: "Nombra cuatro plantas que hay en el patio.", r: "Geranios, gitanillas, claveles y un limonero.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que, al salir, el ruido y el sol de la calle les parecieron «de otro mundo»?", r: "Porque el patio era fresco, tranquilo y silencioso, muy distinto de la calle; el contraste era muy grande.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué nos dice de la señora Pilar que dedique más de una hora al día a regar?", r: "Que es constante y cuidadosa, y que quiere mucho su patio.", lineas: 2 },
      { tipo: "texto", q: "¿Dónde empieza y dónde termina el recorrido de esta descripción? ¿Por qué ayuda este orden al lector? Copia una comparación.", r: "Empieza en la calle (la fachada), sigue por el zaguán y la cancela, el centro del patio, las paredes, la escalera y la galería, y termina en el cielo. Ayuda porque el lector recorre el lugar como si entrara en él. Comparaciones: «como un encaje negro», «claveles que parecen pequeñas llamas», «como un cuadro enmarcado», «un techo azul hecho a medida».", lineas: 3 },
      { tipo: "opinion", q: "¿Te gustaría cuidar un patio como el de la señora Pilar? ¿Qué te gustaría y qué no?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que muchas familias cordobesas abren sus casas a desconocidos en mayo?", r: "Respuesta libre. Valorar ideas como el orgullo por la tradición o el deseo de compartir.", lineas: 2 },
      { tipo: "reflexion", q: "Las tradiciones se mantienen gracias a personas que les dedican su tiempo. ¿Qué tradición de tu localidad te gustaría que no se perdiera? ¿Qué podrías hacer tú?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-06-sierra-nevada",
    titulo: "Sierra Nevada, el techo blanco de Andalucía",
    subtipo: "Topografía (descripción de un paisaje)",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Has estado alguna vez en la nieve? ¿Qué sensaciones recuerdas?",
    texto: [
      { p: "Aquella mañana de enero, desde la ventanilla del autobús que subía hacia Sierra Nevada, vi cómo el paisaje cambiaba a medida que ganábamos altura, como si alguien pasara las páginas de un libro." },
      { p: "Abajo, en la vega de Granada, todo era verde y marrón: huertas cuadriculadas, filas de chopos desnudos por el invierno y pueblos de casas blancas agarrados a las lomas. El sol brillaba sin fuerza y el aire olía a leña quemada." },
      { p: "Poco a poco aparecieron los primeros pinos, oscuros y apretados, y entre ellos las primeras manchas de nieve, sucias y dispersas, como trozos de papel olvidados en el suelo. La carretera se retorcía en curvas cerradas y los oídos se nos taponaban." },
      { p: "Más arriba, los árboles desaparecieron. Entonces, de golpe, la montaña se mostró entera: una enorme sábana blanca, lisa y brillante, extendida sobre las lomas redondeadas. La nieve reflejaba tanto la luz que tuvimos que ponernos las gafas de sol. El cielo era de un azul intenso, casi oscuro, y el silencio solo se rompía con el crujido de nuestras botas." },
      { p: "Al fondo, las cumbres más altas se recortaban contra el cielo como dientes de azúcar. Nuestro monitor, Julián, nos señaló dos: el Veleta, de perfil afilado, y el Mulhacén, más redondeado, que es el pico más alto de la península ibérica. Nos contó que, en los días muy claros, desde allí arriba se distinguen las montañas del norte de África." },
      { p: "El frío era seco y cortante. Se nos colaba por las mangas y nos ponía la nariz roja como un tomate. Aun así, nadie quería volver al autobús. Hicimos un muñeco de nieve con nariz de piña, nos tiramos por una ladera suave en un trineo de plástico y, al final de la tarde, vimos cómo el sol teñía las cumbres de rosa y naranja." },
      { p: "Cuando bajábamos hacia Granada, ya de noche, miré por la ventanilla. Allá arriba, la sierra seguía brillando, pálida bajo la luna, como un gigante dormido que vigila la ciudad." },
    ],
    vocabulario: [
      { p: "vega", d: "Terreno bajo, llano y fértil, junto a un río." },
      { p: "loma", d: "Altura pequeña y alargada del terreno." },
      { p: "ladera", d: "Cada uno de los lados en pendiente de una montaña." },
      { p: "cumbre", d: "Parte más alta de una montaña." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué se veía en la vega de Granada al principio del viaje?", r: "Huertas cuadriculadas, chopos sin hojas y pueblos de casas blancas en las lomas.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué tuvieron que ponerse las gafas de sol? Elige:", opciones: ["Porque nevaba mucho", "Porque la nieve reflejaba mucha luz", "Porque hacía mucho viento"], r: "Porque la nieve reflejaba mucha luz" },
      { tipo: "comprension", q: "¿Qué dos cumbres señaló el monitor y en qué se diferencian?", r: "El Veleta, de perfil afilado, y el Mulhacén, más redondeado y el pico más alto de la península ibérica.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que los árboles desaparecen a medida que se sube?", r: "Porque en lo alto hace demasiado frío y hay mucha nieve y viento, y los árboles no pueden crecer.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué siente el narrador por Sierra Nevada? Justifícalo con alguna expresión del texto.", r: "Admiración y cariño: «nadie quería volver al autobús», «como un gigante dormido que vigila la ciudad».", lineas: 2 },
      { tipo: "texto", q: "El paisaje se describe de abajo arriba, siguiendo el viaje. Copia las expresiones que marcan ese orden. ¿Es una descripción objetiva o subjetiva? Justifícalo.", r: "Abajo, poco a poco, más arriba, al fondo, allá arriba. Es subjetiva: el narrador expresa impresiones y usa comparaciones personales («como dientes de azúcar», «como un gigante dormido»).", lineas: 3 },
      { tipo: "opinion", q: "¿Prefieres un paisaje de montaña nevada o uno de playa? Explica por qué con detalles.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "Si tuvieras que describir un paisaje de tu localidad, ¿qué orden seguirías? ¿Por qué?", r: "Respuesta libre. Valorar que elijan un orden (de cerca a lejos, de abajo arriba…) y lo justifiquen.", lineas: 2 },
      { tipo: "reflexion", q: "En muchas montañas cada vez nieva menos. ¿Qué perderíamos si Sierra Nevada dejara de tener nieve?", r: "Respuesta libre. Valorar referencias al agua de los ríos, la naturaleza, el paisaje y el turismo.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-07-ciudad-futuro",
    titulo: "Carta desde Nueva Almedina",
    subtipo: "Descripción de un lugar imaginario (en forma de carta)",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Cómo te imaginas las ciudades dentro de setenta años? ¿Qué cosas crees que cambiarán?",
    texto: [
      { p: "Querido amigo del pasado: mi profesora dice que esta carta se guardará en una cápsula del tiempo y que la abrirán niños de otra época. Así que voy a describirte mi ciudad, Nueva Almedina, tal como la veo desde la ventana de mi clase, en el piso veinte de un edificio con forma de árbol." },
      { p: "Lo primero que llama la atención es el color verde. Los edificios más altos están cubiertos de plantas de arriba abajo, como si llevaran un abrigo de hojas. Tienen terrazas llenas de huertos donde crecen tomates, lechugas y fresas, y en sus tejados giran unos molinos pequeños y silenciosos que parecen flores de metal." },
      { p: "Entre los edificios, a media altura, pasan los tranvías aéreos: unos vagones transparentes, ligeros como burbujas, que se deslizan por raíles colgantes sin hacer ruido. Por las calles no circulan coches. El suelo de las avenidas es de un material blando y claro que recoge la energía de nuestros pasos y, por la noche, brilla con una luz suave, como un río de luciérnagas." },
      { p: "Abajo, en el centro de la ciudad, está mi lugar favorito: la Plaza del Agua. Es redonda y enorme, con una fuente en espiral que recoge la lluvia y la limpia para que podamos beberla. Alrededor hay árboles altísimos, bancos a la sombra y robots jardineros, pequeños y redondos como tortugas, que recortan el césped muy despacito." },
      { p: "Las casas tienen formas curiosas: unas parecen conchas; otras, colmenas; y todas tienen el tejado cubierto de placas que atrapan el sol. En los barrios no hay vallas: los patios son compartidos y los vecinos cocinan juntos los domingos." },
      { p: "Aun así, no creas que todo es perfecto. A veces los robots se equivocan y riegan a la gente en vez de a las plantas, y mi hermano pequeño dice que echa de menos los charcos de verdad para saltar." },
      { p: "Me gustaría saber cómo era tu ciudad. ¿Había humo? ¿Se oían pájaros? Si puedes, contéstame. Guardaré tu respuesta en mi colección de cosas antiguas. Un abrazo desde el futuro, Aya." },
    ],
    vocabulario: [
      { p: "cápsula del tiempo", d: "Recipiente en el que se guardan objetos o mensajes para que se abran muchos años después." },
      { p: "raíl", d: "Barra de metal por la que se deslizan las ruedas de un tren o tranvía." },
      { p: "espiral", d: "Línea curva que da vueltas alrededor de un punto y se va alejando de él." },
      { p: "luciérnaga", d: "Insecto que despide una luz verdosa en la oscuridad." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Desde dónde describe Aya su ciudad?", r: "Desde la ventana de su clase, en el piso veinte de un edificio con forma de árbol.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué tiene de especial el suelo de las avenidas? Elige:", opciones: ["Es de cristal transparente", "Recoge la energía de los pasos y brilla por la noche", "Se mueve solo como una cinta"], r: "Recoge la energía de los pasos y brilla por la noche" },
      { tipo: "comprension", q: "¿Cómo se consigue agua para beber en la Plaza del Agua?", r: "La fuente en espiral recoge la lluvia y la limpia.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que en Nueva Almedina no hay coches por las calles?", r: "Porque la gente se desplaza en tranvías aéreos silenciosos; así se evitan el humo y el ruido y queda más espacio para las personas y los árboles.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué nos dice el párrafo de los robots y los charcos sobre la forma de ser de Aya?", r: "Que es sincera y tiene sentido del humor: reconoce que su ciudad no es perfecta.", lineas: 2 },
      { tipo: "texto", q: "Copia tres comparaciones con «como» o «parecen». ¿Por qué crees que la autora las usa tanto para describir algo que no existe?", r: "«como si llevaran un abrigo de hojas», «parecen flores de metal», «ligeros como burbujas», «como un río de luciérnagas», «redondos como tortugas», «unas parecen conchas». Porque comparar con cosas conocidas ayuda al lector a imaginar lo desconocido.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué invento de Nueva Almedina te gustaría tener hoy en tu ciudad? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "Contesta brevemente a Aya: ¿cómo es tu ciudad o tu pueblo? Usa al menos dos adjetivos y una comparación.", r: "Respuesta libre. Valorar el uso de adjetivos y comparaciones.", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué decisiones de hoy crees que harán que las ciudades del futuro sean mejores o peores para vivir? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-08-alhambra",
    titulo: "La Alhambra al atardecer",
    subtipo: "Topografía (descripción subjetiva de un lugar)",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Has visto alguna vez un atardecer que te impresionara? ¿Dónde fue y qué recuerdas?",
    texto: [
      { p: "Hay un lugar en Granada donde, al caer la tarde, la gente deja de hablar. Es el mirador de San Nicolás, en lo alto del Albaicín, el antiguo barrio de calles estrechas y casas blancas. Aquel día de octubre, mi familia y yo llegamos justo a tiempo, cuando el sol empezaba a bajar." },
      { p: "El mirador es una plaza pequeña y empedrada, con un pretil de piedra al que se asoma todo el mundo. Había turistas con cámaras, abuelos sentados en los bancos y un chico que tocaba la guitarra muy bajito, como si no quisiera molestar al paisaje." },
      { p: "A nuestros pies se abría el valle del río Darro, estrecho y profundo, lleno de árboles que empezaban a amarillear. Y al otro lado, sobre una colina alargada, estaba ella: la Alhambra. Parecía un enorme barco de piedra varado entre bosques, con las murallas como costados y las torres como mástiles." },
      { p: "A la derecha se alzaba la Alcazaba, la parte más antigua, con sus torres cuadradas y robustas, que parecían soldados de guardia. En el centro, más delicados, asomaban los palacios nazaríes y la torre de Comares. A la izquierda, entre cipreses oscuros y afilados como lápices, se adivinaban los jardines del Generalife." },
      { p: "Entonces empezó el espectáculo. El sol, que se ocultaba a nuestra derecha, iluminó las murallas con una luz cada vez más cálida. Primero se volvieron doradas; después, anaranjadas; y al final, de un rojo intenso, como brasas a punto de apagarse. Entendí por qué su nombre en árabe significa «la roja»." },
      { p: "Detrás de la Alhambra, muy lejos, las cumbres de Sierra Nevada, cubiertas por la primera nieve, se tiñeron de rosa. El cielo pasó del azul al violeta, y abajo, en la ciudad, se encendieron las primeras luces, como luciérnagas despistadas." },
      { p: "Cuando el sol desapareció del todo, la gente del mirador aplaudió, igual que al final de una función de teatro. Yo no aplaudí. Me quedé quieto, intentando guardar aquellos colores en la memoria, porque sabía que ninguna fotografía sería capaz de copiarlos." },
    ],
    vocabulario: [
      { p: "pretil", d: "Muro bajo que protege del peligro de caer en un mirador, un puente o una terraza." },
      { p: "varado", d: "Se dice del barco detenido en la arena o en la tierra." },
      { p: "nazarí", d: "De la dinastía que gobernó el reino de Granada entre los siglos XIII y XV." },
      { p: "ciprés", d: "Árbol alto, estrecho y puntiagudo, de hojas verde oscuro." },
      { p: "brasa", d: "Trozo de leña o carbón encendido, rojo y sin llama." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Desde dónde contempla el narrador la Alhambra y en qué momento del día?", r: "Desde el mirador de San Nicolás, en el Albaicín, al atardecer.", lineas: 1 },
      { tipo: "comprension", q: "¿Con qué compara el narrador la Alhambra vista de lejos? Elige:", opciones: ["Con un castillo de arena", "Con un enorme barco de piedra", "Con un soldado de guardia"], r: "Con un enorme barco de piedra" },
      { tipo: "comprension", q: "Explica cómo cambia el color de las murallas mientras se pone el sol.", r: "Primero se vuelven doradas; después, anaranjadas; y al final, de un rojo intenso.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que la gente aplaudió cuando se puso el sol?", r: "Porque el atardecer les pareció un espectáculo tan emocionante como una función de teatro.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué no aplaudió el narrador? ¿Qué nos dice eso de cómo se sentía?", r: "Porque estaba emocionado y concentrado en guardar los colores en la memoria; se sentía impresionado y quería vivir el momento en silencio.", lineas: 2 },
      { tipo: "texto", q: "Esta topografía combina un orden espacial y un orden temporal. Copia dos expresiones de lugar y dos de tiempo. ¿Es una descripción objetiva o subjetiva? ¿Por qué?", r: "Lugar: a nuestros pies, al otro lado, a la derecha, en el centro, a la izquierda, detrás. Tiempo: entonces, primero, después, al final, cuando el sol desapareció. Es subjetiva: expresa sentimientos y usa comparaciones personales.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué lugar te ha emocionado tanto como al narrador la Alhambra? Descríbelo con dos adjetivos y una comparación.", r: "Respuesta libre. Valorar el uso de adjetivos y comparaciones.", lineas: 3 },
      { tipo: "opinion", q: "El narrador piensa que ninguna fotografía podría copiar aquellos colores. ¿Estás de acuerdo? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 3 },
      { tipo: "reflexion", q: "La Alhambra se construyó hace siglos y hoy la visitan personas de todo el mundo. ¿Por qué es importante conservar los monumentos del pasado?", r: "Respuesta libre. Valorar ideas como la memoria, la historia compartida y el respeto a otras culturas.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-09-quijote",
    titulo: "Retrato de un hidalgo",
    subtipo: "Retrato (fragmento de novela)",
    curso: "6º",
    fuente: "Miguel de Cervantes, El ingenioso hidalgo don Quijote de la Mancha (1605), primera parte, capítulo I. Fragmento reproducido literalmente de la edición del Centro Virtual Cervantes (Instituto Cervantes); el signo […] indica que se omite un pasaje.",
    antes: "¿Qué sabes de don Quijote? ¿Cómo te lo imaginas?",
    texto: [
      { p: "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino. Tenía en su casa una ama que pasaba de los cuarenta y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años. Era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de «Quijada», o «Quesada», que en esto hay alguna diferencia en los autores que deste caso escriben, aunque por conjeturas verisímiles se deja entender que se llamaba «Quijana». Pero esto importa poco a nuestro cuento: basta que en la narración dél no se salga un punto de la verdad." },
      { p: "Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso —que eran los más del año—, se daba a leer libros de caballerías, con tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la caza y aun la administración de su hacienda; y llegó a tanto su curiosidad y desatino en esto, que vendió muchas hanegas de tierra de sembradura para comprar libros de caballerías en que leer, y, así, llevó a su casa todos cuantos pudo haber dellos […]" },
      { p: "En resolución, él se enfrascó tanto en su letura, que se le pasaban las noches leyendo de claro en claro, y los días de turbio en turbio; y así, del poco dormir y del mucho leer, se le secó el celebro de manera que vino a perder el juicio." },
      { dato: "¿Sabías que los «duelos y quebrantos» que comía el hidalgo los sábados eran, probablemente, huevos con tocino? Y «lantejas» es la forma antigua de «lentejas»." },
    ],
    vocabulario: [
      { p: "hidalgo", d: "Noble de la categoría más baja, que solía tener poco dinero." },
      { p: "rocín", d: "Caballo de mala raza, flaco y de poca alzada." },
      { p: "frisar", d: "Acercarse a una edad o a una cantidad." },
      { p: "enjuto", d: "Delgado, flaco." },
      { p: "celebro", d: "Forma antigua de «cerebro»." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué edad tenía aproximadamente el hidalgo?", r: "Unos cincuenta años («Frisaba la edad de nuestro hidalgo con los cincuenta años»).", lineas: 1 },
      { tipo: "comprension", q: "¿Qué significa «seco de carnes, enjuto de rostro»? Elige:", opciones: ["Que estaba muy delgado y tenía la cara flaca", "Que tenía la piel muy seca por el sol", "Que comía muy poca carne"], r: "Que estaba muy delgado y tenía la cara flaca" },
      { tipo: "comprension", q: "¿Con quién vivía el hidalgo?", r: "Con un ama de más de cuarenta años, una sobrina de menos de veinte y un mozo de campo y plaza.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué nos dicen las comidas y las ropas del hidalgo sobre su economía?", r: "Que no era rico: gastaba casi toda su hacienda en comida sencilla y ropa modesta, y solo en las fiestas vestía algo mejor.", lineas: 2 },
      { tipo: "comprension", q: "Según el texto, ¿por qué el hidalgo perdió el juicio?", r: "Por leer libros de caballerías día y noche: del poco dormir y del mucho leer se le secó el cerebro.", lineas: 2 },
      { tipo: "texto", q: "Este fragmento es un retrato. Copia una frase de prosopografía y otra de etopeya. ¿Describe el narrador con total objetividad o con humor? Pon un ejemplo.", r: "Prosopografía: «Era de complexión recia, seco de carnes, enjuto de rostro». Etopeya: «gran madrugador y amigo de la caza» o «los ratos que estaba ocioso —que eran los más del año—». Hay humor e ironía: «que eran los más del año», «se le secó el celebro» o la duda sobre su apellido.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece posible que alguien lea tanto que llegue a confundir los libros con la realidad? ¿Te ha pasado algo parecido con un libro, una serie o un videojuego?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "El narrador dice que no quiere acordarse del nombre del lugar. ¿Por qué crees que lo hace? ¿Qué efecto produce en el lector?", r: "Respuesta libre. Valorar ideas como el misterio, el humor o que el lugar podría ser cualquier pueblo.", lineas: 3 },
      { tipo: "reflexion", q: "El hidalgo vende tierras para comprar libros. ¿Qué cosa valoras tanto que estarías dispuesto a renunciar a otras por ella? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-10-ojos-verdes",
    titulo: "La fuente de los Álamos",
    subtipo: "Topografía y prosopografía (fragmentos de leyenda)",
    curso: "6º",
    fuente: "Gustavo Adolfo Bécquer, «Los ojos verdes» (leyenda, 1861). Fragmentos reproducidos literalmente según sus Obras (1885) en Wikisource, cotejados con la Biblioteca Virtual Miguel de Cervantes; se actualiza la acentuación (a por á). Los subtítulos son añadidos para esta ficha.",
    antes: "¿Has estado alguna vez junto a un arroyo o una fuente en el campo? ¿Qué sonidos recuerdas?",
    texto: [
      { dato: "¿Sabías que Bécquer situó esta leyenda en el Moncayo, entre Soria y Zaragoza? En ella, un joven cazador, Fernando, le describe a su criado una fuente misteriosa donde cree haber visto a una mujer de ojos verdes." },
      { h: "La fuente" },
      { p: "Tú no conoces aquel sitio. Mira, la fuente brota escondida en el seno de una peña, y cae resbalándose gota a gota por entre las verdes y flotantes hojas de las plantas que crecen al borde de su cuna. Aquellas gotas que al desprenderse brillan como puntos de oro y suenan como las notas de un instrumento, se reúnen entre los céspedes, y susurrando, susurrando como un ruido semejante al de las abejas que zumban en torno de las flores, se alejan por entre las arenas, y forman un cauce, y luchan con los obstáculos que se oponen a su camino, y se repliegan sobre sí mismas, y saltan, y huyen, y corren, unas veces con risa, otras con suspiros, hasta caer en un lago. En el lago caen con un rumor indescriptible. Lamentos, palabras, nombres, cantares, yo no sé lo que he oído en aquel rumor cuando me he sentado solo y febril sobre el peñasco, a cuyos pies saltan las aguas de la fuente misteriosa para estancarse en una balsa profunda, cuya inmóvil superficie apenas riza el viento de la tarde." },
      { p: "Todo es allí grande. La soledad con sus mil rumores desconocidos, vive en aquellos lugares y embriaga el espíritu en su inefable melancolía. En las plateadas hojas de los álamos, en los huecos de las peñas, en las ondas del agua, parece que nos hablan los invisibles espíritus de la naturaleza, que reconocen un hermano en el inmortal espíritu del hombre." },
      { h: "Al caer la tarde" },
      { p: "El sol había traspuesto la cumbre del monte; las sombras bajaban a grandes pasos por su falda; la brisa gemía entre los álamos de la fuente, y la niebla, elevándose poco a poco de la superficie del lago, comenzaba a envolver las rocas de su margen." },
      { h: "La dama de la fuente" },
      { p: "Ella era hermosa, hermosa y pálida, como una estatua de alabastro. Uno de sus rizos caía sobre sus hombros, deslizándose entre los pliegues del velo como un rayo de sol que atraviesa las nubes, y en el cerco de sus pestañas rubias brillaban sus pupilas como dos esmeraldas sujetas en una joya de oro." },
    ],
    vocabulario: [
      { p: "peña", d: "Roca grande." },
      { p: "febril", d: "Con fiebre; muy agitado o nervioso." },
      { p: "inefable", d: "Tan intenso que no se puede explicar con palabras." },
      { p: "traspuesto", d: "Que ha pasado al otro lado de algo; aquí, que el sol se ha escondido tras el monte." },
      { p: "alabastro", d: "Piedra blanca y algo transparente que se usa en esculturas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿De dónde brota el agua de la fuente y adónde va a parar?", r: "Brota escondida en el seno de una peña y termina cayendo en un lago, una balsa profunda.", lineas: 2 },
      { tipo: "comprension", q: "¿Con qué compara Bécquer el susurro del agua? Elige:", opciones: ["Con el zumbido de las abejas en torno a las flores", "Con el canto de los pájaros", "Con el ruido del viento entre los álamos"], r: "Con el zumbido de las abejas en torno a las flores" },
      { tipo: "comprension", q: "¿Cómo son los ojos de la dama y con qué los compara el autor?", r: "Son verdes y brillantes; los compara con dos esmeraldas sujetas en una joya de oro.", lineas: 2 },
      { tipo: "comprension", q: "El agua corre «unas veces con risa, otras con suspiros». ¿Qué recurso usa aquí el autor y qué efecto consigue?", r: "Una personificación: atribuye al agua acciones humanas, y así la fuente parece viva y misteriosa.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué ambiente crea el fragmento «Al caer la tarde»? ¿Qué palabras lo consiguen?", r: "Un ambiente misterioso y melancólico: «las sombras bajaban», «la brisa gemía», «la niebla… comenzaba a envolver las rocas».", lineas: 2 },
      { tipo: "texto", q: "Estos fragmentos combinan una topografía y una prosopografía. ¿Qué parte es cada una? ¿La descripción es objetiva o subjetiva? Copia dos adjetivos y una comparación que lo demuestren.", r: "Topografía: la fuente y el atardecer. Prosopografía: la dama. Es subjetiva: adjetivos como «flotantes», «indescriptible», «inefable», «plateadas», «pálida»; comparaciones como «brillan como puntos de oro», «como una estatua de alabastro», «como dos esmeraldas».", lineas: 3 },
      { tipo: "opinion", q: "¿Qué fragmento te ha gustado más: la fuente, el atardecer o la dama? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "Bécquer repite palabras, como en «susurrando, susurrando» o «hermosa, hermosa y pálida». ¿Crees que así el texto es más bello o más difícil? Razona tu respuesta.", r: "Respuesta libre. Valorar que relacionen la repetición con el ritmo y la intensidad.", lineas: 3 },
      { tipo: "reflexion", q: "Fernando siente que en la naturaleza «nos hablan los invisibles espíritus». ¿Te ha transmitido algo alguna vez un paisaje? ¿Por qué crees que la naturaleza nos emociona?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
];
