// Lecturas · Texto descriptivo (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["descriptivo"] = [
  {
    id: "descriptivo-01-camaleon",
    titulo: "El camaleón común, un reptil de otro mundo",
    subtipo: "Descripción de un animal",
    curso: "5º",
    fuente: "Texto original",
    datos: ["MITECO: Atlas y Libro Rojo de los Anfibios y Reptiles de España, ficha de Chamaeleo chamaeleon (camaleón común)", "Fundación Biodiversidad (MITECO): publicación divulgativa sobre el camaleón común (puesta de huevos)"],
    antes: "¿Has visto alguna vez un camaleón? ¿Qué sabes de él?",
    texto: [
      { p: "En algunos pinares, huertos y jardines de la costa andaluza, desde Huelva hasta Almería, vive un animal que parece sacado de una película de ciencia ficción: el camaleón común. Es el único camaleón de Europa, y hay que tener muy buena vista para descubrirlo entre las ramas." },
      { p: "El verano pasado, en una excursión por un pinar cerca de la costa, nuestra monitora, Lucía, se detuvo de repente junto a una retama y nos pidió silencio. Tardamos un buen rato en verlo: estaba quieto sobre una rama, tan verde como las hojas, y solo lo descubrimos cuando uno de sus ojos giró hacia nosotros. Aquel día aprendimos a describirlo de la cabeza a la cola." },
      { p: "—No busquéis un color, buscad una forma —nos susurró Lucía—. El camaleón se parece a las hojas, pero ninguna hoja tiene un ojo que se mueve." },
      { h: "La cabeza y los ojos" },
      { p: "Empecemos por la cabeza. Es grande, con forma de casco, y termina en una cresta abultada. A los lados tiene dos ojos saltones, cubiertos casi por completo de piel escamosa, con un pequeño agujero en el centro para la pupila. Lo más asombroso es que cada ojo se mueve por su cuenta: puede mirar hacia delante con uno y hacia atrás con el otro, como si llevara dos cámaras de vigilancia." },
      { h: "El cuerpo y la piel" },
      { p: "Su cuerpo es estrecho y aplanado por los lados, como una hoja. Sin contar la cola, no es mucho más largo que la mano de un adulto. La piel, rugosa y cubierta de escamas diminutas, suele ser verde, parda o amarillenta, con manchas y rayas más claras. El camaleón cambia de color, pero no solo para esconderse: su piel se oscurece o se aclara según la temperatura, la luz o si está tranquilo o alterado." },
      { h: "Las patas y la cola" },
      { p: "Bajando hacia las patas, encontramos otro invento curioso. Sus dedos están unidos en dos grupos enfrentados que funcionan como unas pinzas y le permiten agarrarse con fuerza a las ramas. Detrás, la cola, larga y prensil, se enrosca como un muelle y le sirve de quinta mano." },
      { p: "Su forma de caminar es muy peculiar. Avanza despacio, levantando una pata, parándose y balanceándose hacia delante y hacia atrás antes de apoyarla, como una hoja que mueve el viento. Así, sus enemigos lo confunden con la vegetación." },
      { p: "Come sobre todo insectos: saltamontes, grillos, moscas y mariposas. No suele beber en charcos, sino que lame las gotas de rocío que se quedan en las hojas por la mañana. De noche, cuando duerme agarrado a una rama, su piel se vuelve muy pálida, casi blanca, y por eso los naturalistas lo buscan a veces con una linterna." },
      { h: "Un arma secreta" },
      { p: "Pero su arma secreta está escondida en la boca. Cuando descubre un saltamontes o una mosca, dispara una lengua larguísima, pegajosa y con la punta ensanchada, y atrapa a su presa en un abrir y cerrar de ojos. Si se siente amenazado, en cambio, se hincha, se oscurece, abre la boca y bufa para parecer más peligroso de lo que es." },
      { p: "Casi toda su vida transcurre en los árboles y arbustos. Solo en otoño, las hembras bajan al suelo, cavan un agujero en la tierra blanda y entierran sus huevos. Las crías, diminutas copias de sus padres, no nacen hasta el verano siguiente." },
      { p: "El camaleón es lento, tímido e inofensivo. En España se considera una especie casi amenazada por la destrucción de su hábitat, los atropellos, los ataques de animales domésticos y la captura ilegal. Si alguna vez ves uno, obsérvalo sin tocarlo y déjalo donde está." },
      { p: "Cuando nos marchamos, el camaleón seguía en su retama, inmóvil, con un ojo clavado en nosotros y el otro mirando al cielo, como si vigilara a la vez a sus visitantes y a los pájaros. En el autobús de vuelta, todos intentamos mover los ojos por separado, como él." },
    ],
    vocabulario: [
      { p: "cresta", d: "Saliente que tienen algunos animales en lo alto de la cabeza." },
      { p: "rugoso", d: "Que tiene arrugas o una superficie áspera." },
      { p: "prensil", d: "Que sirve para agarrar o sujetar." },
      { p: "bufar", d: "Resoplar con fuerza, como hacen algunos animales cuando se enfadan o tienen miedo." },
      { p: "hábitat", d: "Lugar con las condiciones adecuadas para que viva una especie." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué la cola del camaleón es como una «quinta mano»? Elige:", opciones: ["Porque tiene dedos", "Porque se enrosca y se agarra a las ramas", "Porque atrapa insectos"], r: "Porque se enrosca y se agarra a las ramas" },
      { tipo: "comprension", q: "¿Por qué crees que el camaleón se balancea al caminar?", r: "Para parecer una hoja movida por el viento; así sus enemigos lo confunden con la vegetación y no lo descubren.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué hace el camaleón cuando se siente amenazado? ¿Para qué?", r: "Se hincha, se oscurece, abre la boca y bufa, para parecer más peligroso de lo que es.", lineas: 2 },
      { tipo: "texto", q: "¿En qué orden se describe el animal? Copia dos comparaciones que ayuden a imaginarlo.", r: "De la cabeza a la cola: cabeza y ojos → cuerpo y piel → patas y cola → lengua. Comparaciones: «como si llevara dos cámaras de vigilancia», «como una hoja», «como unas pinzas», «como un muelle».", lineas: 2 },
      { tipo: "opinion", q: "¿Qué característica del camaleón te parece más sorprendente? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que los animales pequeños y discretos reciben menos atención que los grandes? ¿Te parece justo?", r: "Respuesta libre. Valorar la argumentación.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-02-abuela",
    titulo: "Mi abuela Carmen",
    subtipo: "Retrato",
    curso: "5º",
    fuente: "Texto original",
    antes: "Piensa en una persona mayor a la que quieras mucho. ¿Cómo es por fuera? ¿Y por dentro?",
    texto: [
      { p: "Mi abuela Carmen tiene setenta y dos años y la risa más contagiosa del barrio. Es bajita, tan bajita que tiene que ponerse de puntillas para darme un beso en la frente, aunque ella dice que es porque yo crezco demasiado deprisa." },
      { p: "Tiene el pelo corto y blanco como la espuma, siempre algo despeinado por el viento de la azotea, donde cuida sus macetas. Su cara es redonda y morena, llena de arrugas finas que se juntan en las esquinas de los ojos cuando sonríe, como los rayos de un sol dibujado por un niño. Sus ojos son pequeños, castaños y vivísimos: no se les escapa nada. Lleva colgadas de un cordón unas gafas de montura roja que casi nunca usa, porque, según ella, ya se sabe el mundo de memoria." },
      { p: "Casi siempre viste igual: una rebeca de punto de color mostaza, con los bolsillos llenos de cosas útiles, y unas zapatillas de cuadros con las que camina tan deprisa que parece que se desliza. En esos bolsillos hay de todo: caramelos de menta, un lápiz corto, pinzas de la ropa, un pañuelo bordado y, a veces, una semilla que ha encontrado por la calle y que piensa plantar." },
      { p: "Su voz es aguda y cantarina, y se oye desde la esquina cuando llama a los gatos del patio. Tiene un refrán para cada ocasión. Si llego tarde, dice que no por mucho madrugar amanece más temprano; si me quejo de los deberes, me recuerda que quien la sigue la consigue." },
      { p: "Lo que más me gusta de ella son sus manos. Son anchas, suaves por la palma y ásperas por los nudillos, con restos de tierra de las macetas y olor a limón. Con esas manos amasa las mejores tortas del mundo, arregla enchufes y cose botones a una velocidad que parece magia." },
      { p: "Cuando habla, mueve esas manos sin parar, como si dirigiera una orquesta invisible. Y cuando abraza, abraza de verdad: fuerte, largo y con palmaditas en la espalda, como si quisiera comprobar que sigues entero." },
      { p: "Su casa se le parece mucho. Es pequeña, luminosa y siempre huele a café recién hecho. En la cocina hay una mesa de madera con un hule de flores, y en la pared, un calendario lleno de anotaciones: cumpleaños, citas del médico, clases de informática y el día de regar los geranios." },
      { p: "Pero la abuela no solo es especial por fuera. Es curiosa como un gato: se ha apuntado a clases de informática y ahora me manda mensajes con más emoticonos que palabras. Es paciente, muy paciente, sobre todo cuando me explica las fracciones con trozos de bizcocho. También es terca: cuando dice que va a llover, coge el paraguas aunque el cielo esté azul. Y casi siempre acierta." },
      { p: "Es generosa sin hacer ruido. Si una vecina está enferma, aparece en su puerta con un táper de puchero; si alguien del barrio se siente solo, lo invita a jugar al dominó en la plaza. Nunca presume de nada, pero todo el mundo la conoce." },
      { p: "De joven fue modista, y todavía conserva su vieja máquina de coser, negra y con letras doradas, junto a la ventana del salón. Con ella me hizo el disfraz de pirata del último carnaval, con parche, fajín y un loro de fieltro cosido al hombro. Mientras cose, tararea canciones antiguas y se le olvida el mundo." },
      { p: "Tampoco es perfecta, y ella es la primera en reírse de sí misma. Canta fatal, aunque canta muchísimo. Se pierde con los botones del mando de la tele y confunde los nombres de todos mis amigos." },
      { p: "Los viernes vamos juntas a la biblioteca del barrio. Ella elige novelas de misterio y siempre adivina quién es el culpable antes de llegar a la mitad." },
      { p: "El domingo pasado, mientras pelábamos habas en la azotea, le pregunté cuál era su secreto para ser tan feliz. Se quedó pensando un momento, con una vaina en la mano, y me contestó:" },
      { p: "—Tener las manos ocupadas y el corazón abierto, hija. Lo demás viene solo." },
      { p: "No sé si de mayor seré bajita o alta, rubia o morena. Lo que sí sé es que quiero tener unas manos como las suyas: manos que siempre están haciendo algo por los demás." },
    ],
    vocabulario: [
      { p: "azotea", d: "Terraza en lo alto de un edificio." },
      { p: "rebeca", d: "Chaqueta de punto, sin cuello, que se abrocha por delante." },
      { p: "nudillo", d: "Parte abultada de las articulaciones de los dedos." },
      { p: "terco", d: "Que mantiene su opinión aunque otros piensen distinto." },
      { p: "puchero", d: "Guiso de garbanzos, verduras y carne; cocido." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué casi nunca usa las gafas? Elige:", opciones: ["Porque las ha perdido", "Porque dice que se sabe el mundo de memoria", "Porque no le gusta el rojo"], r: "Porque dice que se sabe el mundo de memoria" },
      { tipo: "comprension", q: "¿Qué dicen de la abuela las cosas que lleva en los bolsillos?", r: "Que es práctica, previsora y cariñosa (caramelos, lápiz, pinzas…) y que le encantan las plantas (guarda semillas para plantarlas).", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir la nieta con que su abuela «es generosa sin hacer ruido»?", r: "Que ayuda a los demás sin presumir ni buscar que se lo agradezcan.", lineas: 2 },
      { tipo: "texto", q: "¿Qué párrafos son prosopografía y cuáles etopeya? ¿Es un retrato objetivo o subjetivo? ¿Por qué?", r: "Prosopografía: los que describen su aspecto, ropa, voz y manos. Etopeya: los que cuentan que es curiosa, paciente, terca y generosa. Es subjetivo: «la risa más contagiosa del barrio», «las mejores tortas del mundo».", lineas: 3 },
      { tipo: "opinion", q: "La abuela aprende informática a los setenta y dos años. ¿Crees que nunca es tarde para aprender? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten con ejemplos.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué puedes aprender tú de las personas mayores? ¿Y qué puedes enseñarles?", r: "Respuesta libre. Valorar el respeto y la idea de aprendizaje mutuo.", lineas: 2 },
    ],
  },
  {
    id: "descriptivo-03-objeto-misterioso",
    titulo: "El objeto del trastero",
    subtipo: "Descripción de un objeto",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has encontrado alguna vez un objeto antiguo y no sabías para qué servía? ¿Cómo lo averiguaste?",
    texto: [
      { p: "El sábado, mientras ayudábamos a ordenar el trastero de la tía Rosario, mi amigo Iker y yo encontramos una caja de madera cubierta de polvo. Estaba en el fondo de un armario, detrás de unas maletas de cartón y de una lámpara sin bombilla. Dentro, envuelto en un periódico amarillento, había un objeto que ninguno de los dos supo reconocer." },
      { p: "Decidimos hacer lo que hacen los científicos: describirlo con detalle antes de sacar conclusiones. Iker tomaba las medidas con una regla y yo lo apuntaba todo en un cuaderno. Esta es nuestra ficha." },
      { h: "Descripción del objeto" },
      { p: "Es un objeto pequeño y pesado. La base es un cubo de madera oscura, de unos quince centímetros de alto, con las esquinas redondeadas por el uso. La madera es lisa y brillante en algunas zonas, como si muchas manos la hubieran sujetado durante años. En la parte delantera tiene un cajoncito con un tirador de latón, redondo y del tamaño de un botón." },
      { p: "Iker, que es muy impaciente, quería desmontarlo enseguida para ver qué había dentro. Yo le convencí de esperar: primero había que observar, medir y apuntar." },
      { p: "Sobre el cubo hay una pieza de metal gris oscuro con forma de cuenco. Por fuera tiene unos adornos en relieve, como hojas entrelazadas, y por dentro es liso y frío. En el centro del cuenco sobresale un eje vertical y, encima, una manivela curvada que termina en un pomo de madera torneada. Cuando giramos la manivela, se oye un chirrido metálico, como el de una bicicleta vieja, y dentro algo da vueltas." },
      { p: "Al abrir el cajoncito encontramos un polvillo marrón que olía un poco a desayuno. En un lateral del cubo, casi borrada, se lee una inscripción: «Hecho a mano, 1953»." },
      { p: "Le dimos la vuelta con cuidado. Por debajo, la base tiene cuatro pequeñas patas de goma, gastadas y agrietadas, y una etiqueta de papel tan descolorida que no pudimos leer nada. Al acercarlo a la nariz, la madera olía a armario viejo, pero el cuenco tenía otro olor distinto, más fuerte y más tostado." },
      { lista: ["Tamaño: unos quince centímetros de alto; cabe entre las dos manos.", "Peso: mucho para su tamaño.", "Materiales: madera oscura, metal gris y latón.", "Partes: base con cajoncito, cuenco, eje, manivela y pomo.", "Estado: polvoriento, con la manivela un poco dura, pero entero."], titulo: "Resumen de nuestra ficha" },
      { h: "Nuestra hipótesis" },
      { p: "Iker pensó primero que era una caja de música, porque tenía manivela. Yo creí que era un sacapuntas antiguo, aunque el agujero era demasiado grande para un lápiz. Pero el olor del cajón nos dio la pista definitiva. Se lo enseñamos a la tía Rosario, que se echó a reír." },
      { p: "—Es el molinillo de café de mi madre —nos explicó—. Se echaban los granos en el cuenco, se giraba la manivela y el café molido caía en el cajón. Antes casi nadie compraba el café ya molido." },
      { p: "—¿Y por qué no lo compraban molido? —preguntó Iker, que siempre quiere saberlo todo." },
      { p: "—Porque el café recién molido huele y sabe mucho mejor —contestó ella—. Mi madre compraba los granos en la tienda de la esquina, y a veces hasta los tostaba ella misma en una sartén." },
      { p: "Luego se sentó en una silla baja, se colocó el molinillo entre las rodillas y nos enseñó cómo lo hacía su madre cada mañana: con una mano sujetaba la caja y con la otra daba vueltas sin parar, mientras la cocina se llenaba de olor. Nos contó que ella, de pequeña, se despertaba con aquel ruido, que para ella era el sonido de los desayunos de invierno." },
      { p: "Esa tarde lo limpiamos, le pusimos un poco de aceite en el eje y molimos café de verdad. El chirrido desapareció, pero el olor a desayuno llenó toda la casa. Ahora el molinillo está en una estantería del salón, y la tía Rosario dice que es el objeto más valioso de la casa, aunque no valga casi nada de dinero. Iker dice que de mayor será detective de objetos antiguos." },
    ],
    vocabulario: [
      { p: "latón", d: "Metal de color dorado, mezcla de cobre y cinc." },
      { p: "manivela", d: "Pieza en forma de codo que se gira con la mano para mover un mecanismo." },
      { p: "torneado", d: "Trabajado en una máquina (torno) que le da forma redondeada." },
      { p: "inscripción", d: "Texto escrito o grabado sobre un objeto." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué pista les ayudó a descubrir qué era? Elige:", opciones: ["La inscripción del lateral", "El olor del polvillo del cajón", "El chirrido de la manivela"], r: "El olor del polvillo del cajón" },
      { tipo: "comprension", q: "¿Para qué servía el objeto y cómo se usaba?", r: "Para moler café: se echaban los granos en el cuenco, se giraba la manivela y el café molido caía en el cajón.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice la tía que es el objeto más valioso de la casa, si no vale casi nada de dinero?", r: "Porque tiene valor sentimental: le recuerda a su madre y los desayunos de su infancia.", lineas: 2 },
      { tipo: "texto", q: "Copia de la ficha un ejemplo de medida, uno de material y uno de forma. ¿En qué orden se describe el objeto?", r: "Medida: unos quince centímetros de alto. Material: madera, latón, metal. Forma: cubo, cuenco, manivela curvada. Orden: de abajo arriba (base y cajón, cuenco, eje y manivela) y después el interior del cajón y la inscripción.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece buena idea conservar objetos antiguos aunque ya no se usen? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué objeto actual crees que sorprenderá a los niños dentro de setenta años? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "descriptivo-04-mercado",
    titulo: "El mercado de abastos de mi pueblo",
    subtipo: "Topografía (descripción de un lugar)",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has ido alguna vez a un mercado de abastos? ¿Qué es lo que más te llamó la atención?",
    texto: [
      { p: "Los sábados por la mañana acompaño a mi padre al mercado de abastos de mi pueblo, en la costa de Huelva. Es un edificio antiguo, blanco y alargado, con un tejado de tejas rojas y un gran portón verde. Sobre la puerta, un reloj redondo marca la hora con un retraso de diez minutos que nadie arregla, porque todo el mundo ya lo sabe." },
      { p: "Llegamos temprano, cuando los vendedores todavía están colocando la mercancía. Desde fuera ya se oyen las voces, el ruido de las cajas al arrastrarse y el golpe seco de los cuchillos sobre las tablas. Nada más cruzar el portón, el ruido, los colores y los olores te envuelven como una ola." },
      { h: "El rincón del mar" },
      { p: "A la izquierda de la entrada están los puestos de pescado. Sobre montañas de hielo picado brillan las sardinas plateadas, las gambas rosadas, los chocos de piel manchada y las coquinas diminutas, apretadas como botones en una caja. Los pescaderos, con sus delantales de goma, cantan los precios a voces. El suelo siempre está mojado y huele a mar." },
      { p: "Frente a ellos hay un puesto que siempre tiene cola: el de las aceitunas. Sobre el mostrador se alinean barreños de colores con aceitunas de todas clases: gordales enormes, manzanillas pequeñas y verdes, negras arrugadas, aliñadas con ajo, tomillo e hinojo. El dueño deja probarlas con un palillo, y mi padre siempre acaba comprando más de las que pensaba." },
      { p: "El pescadero más antiguo se llama Manolo. Es alto y delgado, con los brazos morenos y una gorra de lana que no se quita ni en agosto. Tiene las manos rápidas y un ojo experto: con solo mirar un pescado sabe si lo pescaron ayer o esta misma madrugada." },
      { h: "El pasillo de los colores" },
      { p: "En el centro, formando un pasillo ancho, se alinean las fruterías. Parecen un cuadro lleno de colores: tomates rojos y brillantes, pimientos verdes y amarillos, naranjas perfumadas, fresas que parecen pequeños corazones y sandías enormes, rayadas como balones de playa. La frutera, Remedios, siempre me regala una mandarina y me pregunta qué tal van las notas." },
      { p: "A la derecha están la carnicería y el puesto de los quesos. Del techo cuelgan ristras de chorizos, como collares gigantes, y sobre el mostrador se apilan quesos redondos de corteza dorada. Al lado, un puesto pequeño vende pan de pueblo, tortas de aceite y roscos de anís que todavía están calientes." },
      { p: "Entre los puestos se mueve la gente de siempre: abuelas con carros de la compra que chirrían, niños pequeños que señalan las sandías, un señor que discute amablemente el precio de los tomates y turistas que hacen fotos a las gambas como si fueran joyas. Todos hablan a la vez, y el mercado suena como una orquesta que afina antes del concierto." },
      { h: "El fondo tranquilo" },
      { p: "Al fondo, junto a una ventana grande, están los puestos más tranquilos. En la tienda de especias hay sacos abiertos de pimentón, comino y canela que llenan el aire de un olor cálido. Junto a ella, una señora vende flores en cubos de cinc: margaritas, claveles y ramilletes de romero. En un rincón hay un pequeño bar donde los vendedores toman café en taburetes altos. Por encima de todo, bajo el techo de vigas de hierro, revolotean dos gorriones atentos a las migas." },
      { p: "A mediodía, el mercado cambia. Los puestos se vacían, las voces se apagan y los pescaderos riegan el suelo con mangueras. El silencio llega poco a poco, como la marea que baja." },
      { p: "Remedios tapa las frutas con una tela, Manolo guarda el hielo en cajas y el reloj de la entrada sigue marcando, con su retraso de siempre, la hora de volver a casa." },
      { p: "Me gusta el mercado porque es mucho más que un lugar para comprar. Allí la gente se saluda por su nombre, se cuentan las noticias del pueblo y se aprende a elegir un buen melón. Cuando salimos con las bolsas llenas, siempre pienso que el mercado es el corazón del pueblo, y que late con más fuerza los sábados." },
    ],
    vocabulario: [
      { p: "abastos", d: "Productos de alimentación que se venden para abastecer a la población." },
      { p: "portón", d: "Puerta grande." },
      { p: "ristra", d: "Fila de cosas atadas unas a otras, como ajos o chorizos." },
      { p: "especia", d: "Sustancia vegetal que da sabor y olor a las comidas, como el pimentón o la canela." },
      { p: "taburete", d: "Asiento sin brazos ni respaldo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Con qué compara el narrador las coquinas? Elige:", opciones: ["Con pequeños corazones", "Con botones en una caja", "Con balones de playa"], r: "Con botones en una caja" },
      { tipo: "comprension", q: "¿Por qué nadie arregla el reloj de la entrada?", r: "Porque todo el mundo sabe que va diez minutos retrasado.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué quiere decir el narrador cuando afirma que el mercado es «el corazón del pueblo»?", r: "Que es el centro de la vida del pueblo: allí la gente se reúne, se conoce y se cuenta las noticias.", lineas: 2 },
      { tipo: "texto", q: "Copia tres expresiones que indiquen dónde está cada zona. ¿A qué sentidos se dirige el autor? Pon dos ejemplos.", r: "A la izquierda de la entrada, en el centro, a la derecha, al fondo, en un rincón, por encima de todo. Vista (colores de las frutas), oído (cantan los precios), olfato (huele a mar, especias), tacto (suelo mojado), gusto (la mandarina).", lineas: 3 },
      { tipo: "opinion", q: "¿Prefieres comprar en un mercado de abastos o en un supermercado? Da dos razones.", r: "Respuesta libre. Valorar que argumenten.", lineas: 2 },
      { tipo: "reflexion", q: "En los pequeños comercios conocen a los clientes por su nombre. ¿Qué se pierde cuando desaparecen?", r: "Respuesta libre. Valorar la reflexión sobre la convivencia y la vida del barrio.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-05-patio-cordobes",
    titulo: "Un patio de Córdoba en mayo",
    subtipo: "Topografía (descripción de un lugar)",
    curso: "5º",
    fuente: "Texto original",
    datos: ["Wikipedia: «Festival de los Patios Cordobeses» (concurso desde 1921)", "UNESCO, Patrimonio Cultural Inmaterial: «La fiesta de los patios de Córdoba» (2012)"],
    antes: "¿Sabes qué son los patios cordobeses? ¿Por qué crees que en mayo mucha gente va a visitarlos?",
    texto: [
      { p: "En mayo, Córdoba abre sus patios, y mi prima Aurora y yo fuimos a visitar el de la señora Pilar, en el barrio de San Basilio. Para llegar recorrimos calles estrechas y empedradas, con rejas en las ventanas y macetas asomando por todas partes. Había colas de visitantes en algunas puertas y un murmullo alegre de gente que hablaba en muchos idiomas." },
      { p: "Desde la calle solo se veía una fachada encalada y una puerta de madera. Nadie diría que detrás se escondía un pequeño paraíso." },
      { p: "Junto a la puerta, un cartel escrito a mano decía: «Patio abierto. Pasen y vean». Aurora me agarró del brazo, emocionada, y entramos detrás de un grupo de turistas que hablaban en voz baja, como si entraran en un museo." },
      { p: "Primero cruzamos el zaguán, un pasillo fresco y en penumbra con el suelo de losas de barro. Al fondo, una cancela de hierro llena de rizos y espirales, como un encaje negro, dejaba ver un rectángulo de luz y de verde. Al atravesarla, nos quedamos con la boca abierta." },
      { p: "El patio es cuadrado y no muy grande. En el centro hay un pozo antiguo con un brocal de piedra gastada, rodeado de un suelo de chinos, piedrecitas blancas y negras que forman dibujos de estrellas. Junto al pozo, una fuente pequeña deja caer un hilo de agua con un murmullo que calma el calor." },
      { p: "Pero lo que de verdad asombra son las paredes. Están pintadas de un blanco tan intenso que casi hace daño a los ojos, y cubiertas de arriba abajo por decenas de macetas azules. De ellas cuelgan geranios rojos, gitanillas rosas y claveles que parecen pequeñas llamas. En una esquina, un limonero perfuma el aire, y junto a la puerta, un jazmín trepa por la pared como si quisiera escaparse hacia el tejado." },
      { p: "Si te fijas bien, no todas las macetas son iguales. Unas son de barro, pintadas de azul añil; otras son viejas latas de conserva, también pintadas, que la señora Pilar recicla desde hace años. Todas cuelgan de clavos y alcayatas colocados con mucho cuidado, formando filas ordenadas, como las notas de una partitura. Entre las macetas, en la pared, brillan algunos platos de cerámica con dibujos de pájaros." },
      { p: "El patio también se escucha y se huele. El agua de la fuente murmura sin parar, las golondrinas chillan al entrar y salir de sus nidos, bajo el tejado, y el aire mezcla el olor dulce del jazmín con el de la tierra recién regada." },
      { p: "A la derecha, una escalera estrecha sube hasta una galería de arcos desde la que se ve el patio entero, como un cuadro enmarcado. En la galería hay una mecedora de mimbre, una jaula con un canario que no deja de cantar y una mesa con un mantel de ganchillo. Arriba del todo, el cielo de mayo parece un techo azul hecho a medida." },
      { p: "La señora Pilar es una mujer menuda, de pelo gris recogido en un moño y ojos alegres. Llevaba un delantal lleno de bolsillos y hablaba de sus plantas como si fueran de la familia. Tenía las manos llenas de pequeños arañazos, y cuando nos enseñaba sus geranios preferidos le brillaban los ojos. Nos contó que regar las macetas le lleva cada día más de una hora, y que usa una caña larga con una lata en la punta para llegar a las más altas." },
      { p: "—Este patio era de mi abuela —nos dijo—. Antes vivían aquí cuatro familias, y todas compartían el pozo y las flores. Por eso lo cuido tanto: aquí dentro está la historia de mucha gente." },
      { p: "También nos explicó que el Ayuntamiento organiza desde 1921 un concurso de patios, y que en 2012 la UNESCO declaró la fiesta de los patios de Córdoba Patrimonio Cultural Inmaterial de la Humanidad." },
      { p: "Al despedirnos, nos regaló un clavel a cada una. Cuando salimos, el ruido y el sol de la calle nos parecieron de otro mundo." },
      { p: "Antes de volver a casa, entramos en otro patio de la misma calle. Era muy distinto: alargado y estrecho, con el suelo de ladrillo rojo y una parra que lo cubría como un toldo verde. Aurora dijo que ese le gustaba más, porque parecía un túnel secreto. Yo seguí prefiriendo el de la señora Pilar, con su pozo, su canario y sus paredes llenas de flores." },
    ],
    vocabulario: [
      { p: "encalado", d: "Pintado de blanco con cal." },
      { p: "zaguán", d: "Espacio cubierto que hay a la entrada de una casa, junto a la puerta de la calle." },
      { p: "cancela", d: "Verja de hierro que separa el zaguán del patio." },
      { p: "brocal", d: "Borde de piedra que rodea la boca de un pozo." },
      { p: "galería", d: "Pasillo con arcos o columnas abierto hacia un patio." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué es el zaguán? Elige:", opciones: ["El pozo del patio", "El pasillo de entrada desde la calle", "La galería de arcos"], r: "El pasillo de entrada desde la calle" },
      { tipo: "comprension", q: "¿Por qué cuida tanto la señora Pilar su patio? Explica lo que cuenta de él.", r: "Porque era de su abuela; allí vivieron cuatro familias que compartían el pozo y las flores, y para ella el patio guarda la historia de mucha gente.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que, al salir, la calle les pareció «de otro mundo»?", r: "Porque el patio era fresco, tranquilo y silencioso, muy distinto del ruido y el sol de la calle.", lineas: 2 },
      { tipo: "texto", q: "¿Dónde empieza y dónde termina el recorrido de la descripción? ¿Por qué ayuda ese orden? Copia una comparación.", r: "Empieza en la calle y sigue por el zaguán, la cancela, el centro del patio, las paredes, la escalera y la galería, hasta el cielo. Ayuda porque el lector entra en el lugar como si lo recorriera. Comparaciones: «como un encaje negro», «como un cuadro enmarcado».", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que muchas familias abren sus casas a desconocidos en mayo?", r: "Respuesta libre. Valorar ideas como el orgullo por la tradición o el deseo de compartir.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué tradición de tu localidad te gustaría que no se perdiera? ¿Qué podrías hacer tú?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "descriptivo-06-sierra-nevada",
    titulo: "Sierra Nevada, el techo blanco de Andalucía",
    subtipo: "Topografía (descripción de un paisaje)",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Has estado alguna vez en la nieve? ¿Qué sensaciones recuerdas?",
    texto: [
      { p: "Aquella mañana de enero, desde la ventanilla del autobús que subía hacia Sierra Nevada, vi cómo el paisaje cambiaba a medida que ganábamos altura, como si alguien pasara las páginas de un libro." },
      { p: "Abajo, en la vega de Granada, todo era verde y marrón: huertas cuadriculadas, filas de chopos desnudos por el invierno y pueblos de casas blancas agarrados a las lomas. El sol brillaba sin fuerza y el aire olía a leña quemada." },
      { p: "Poco a poco aparecieron los primeros pinos, oscuros y apretados, y entre ellos las primeras manchas de nieve, sucias y dispersas, como trozos de papel olvidados en el suelo. La carretera se retorcía en curvas cerradas y los oídos se nos taponaban. Por el cristal, un arroyo bajaba saltando entre las piedras, y en sus orillas colgaban carámbanos de hielo, largos y transparentes, como dedos de cristal." },
      { p: "A mitad de camino, el autobús paró en un mirador. Desde allí, Granada parecía una maqueta: se distinguían los tejados, las torres de las iglesias y, sobre una colina, las murallas rojizas de la Alhambra, diminutas como un juguete. Una neblina fina flotaba sobre la vega, y los pueblos brillaban al sol como puñados de azúcar." },
      { p: "Más arriba, los árboles desaparecieron. Entonces, de golpe, la montaña se mostró entera: una enorme sábana blanca, lisa y brillante, extendida sobre las lomas redondeadas. La nieve reflejaba tanto la luz que tuvimos que ponernos las gafas de sol. El cielo era de un azul intenso, casi oscuro, y el silencio solo se rompía con el crujido de nuestras botas." },
      { p: "De cerca, la nieve no era igual en todas partes. En las zonas de sombra estaba dura y crujiente, como el azúcar de una tarta; al sol, en cambio, era blanda y húmeda, y se nos quedaba pegada a los guantes. Julián nos enseñó a mirar de cerca un copo sobre la manga oscura del anorak: tenía seis puntas, como una estrella diminuta de encaje. Junto a unas rocas descubrimos unas huellas pequeñas con forma de corazón partido. Julián, nuestro monitor, nos explicó que eran de cabra montés, y un poco después vimos a tres de ellas saltando por una ladera, tan tranquilas como si caminaran por una acera." },
      { p: "Al otro lado de la ladera se veía la estación de esquí. Los esquiadores, con sus trajes de colores, bajaban haciendo eses por las pistas, tan pequeños desde lejos que parecían hormigas sobre un mantel blanco. Los telesillas subían y bajaban sin descanso, y de vez en cuando se oía la risa de alguien que se había caído. Nosotros no íbamos a esquiar: nuestro plan era explorar, jugar y aprender a mirar la montaña de cerca." },
      { p: "Al fondo, las cumbres más altas se recortaban contra el cielo como dientes de azúcar. Julián nos señaló dos: el Veleta, de perfil afilado, y el Mulhacén, más redondeado, que es el pico más alto de la península ibérica. Nos contó que, en los días muy claros, desde allí arriba se distinguen las montañas del norte de África." },
      { p: "El frío era seco y cortante. Se nos colaba por las mangas y nos ponía la nariz roja como un tomate. Aun así, nadie quería volver al autobús. A mediodía comimos en un refugio de piedra con el tejado cubierto de nieve, sentados junto a una estufa que olía a resina. Después hicimos un muñeco de nieve con nariz de piña, nos tiramos por una ladera suave en un trineo de plástico y, al final de la tarde, vimos cómo el sol teñía las cumbres de rosa y naranja." },
      { p: "A media tarde, unas nubes grises taparon el sol durante un rato y empezaron a caer copos pequeños, tan ligeros que parecían bailar en el aire antes de posarse. Todo se volvió silencioso y borroso, como si alguien hubiera bajado el volumen del mundo. Luego, igual que habían llegado, las nubes se marcharon, y el cielo volvió a ser azul." },
      { p: "Cuando bajábamos hacia Granada, ya de noche, miré por la ventanilla. Allá arriba, la sierra seguía brillando, pálida bajo la luna, como un gigante dormido que vigila la ciudad." },
      { p: "Aquella noche, en casa, todavía notaba el frío en las mejillas, el cansancio en las piernas y el olor a nieve en el pelo, aunque ya me había duchado dos veces. Me dormí pensando que había estado en el techo de Andalucía, y que desde allí arriba el mundo parecía mucho más grande y mucho más tranquilo." },
    ],
    vocabulario: [
      { p: "vega", d: "Terreno bajo, llano y fértil, junto a un río." },
      { p: "loma", d: "Altura pequeña y alargada del terreno." },
      { p: "carámbano", d: "Trozo de hielo largo y puntiagudo que cuelga de un sitio." },
      { p: "ladera", d: "Cada uno de los lados en pendiente de una montaña." },
      { p: "cumbre", d: "Parte más alta de una montaña." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué tuvieron que ponerse las gafas de sol? Elige:", opciones: ["Porque nevaba mucho", "Porque la nieve reflejaba mucha luz", "Porque hacía viento"], r: "Porque la nieve reflejaba mucha luz" },
      { tipo: "comprension", q: "¿En qué se diferencia la nieve de la sombra de la nieve del sol?", r: "La de la sombra está dura y crujiente, como azúcar; la del sol está blanda y húmeda y se pega a los guantes.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que los árboles desaparecen a medida que se sube?", r: "Porque en lo alto hace demasiado frío y hay mucha nieve y viento, y los árboles no pueden crecer.", lineas: 2 },
      { tipo: "texto", q: "Copia tres expresiones que marquen el orden de abajo arriba. ¿Es una descripción objetiva o subjetiva? ¿Por qué?", r: "Abajo, poco a poco, más arriba, al fondo, allá arriba. Es subjetiva: el narrador expresa impresiones y usa comparaciones personales («como dientes de azúcar», «como un gigante dormido»).", lineas: 3 },
      { tipo: "opinion", q: "¿Prefieres un paisaje de montaña nevada o uno de playa? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "En muchas montañas cada vez nieva menos. ¿Qué perderíamos si Sierra Nevada se quedara sin nieve?", r: "Respuesta libre. Valorar referencias al agua de los ríos, los animales, el paisaje y el turismo.", lineas: 2 },
    ],
  },
  {
    id: "descriptivo-07-ciudad-futuro",
    titulo: "Carta desde Nueva Almedina",
    subtipo: "Descripción de un lugar imaginario (en forma de carta)",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Cómo te imaginas las ciudades dentro de setenta años? ¿Qué cosas crees que cambiarán?",
    texto: [
      { p: "Querido amigo del pasado: mi profesora dice que esta carta se guardará en una cápsula del tiempo y que la abrirán niños de otra época. Así que voy a describirte mi ciudad, Nueva Almedina, tal como la veo desde la ventana de mi clase, en el piso veinte de un edificio con forma de árbol." },
      { p: "Lo primero que llama la atención es el color verde. Los edificios más altos están cubiertos de plantas de arriba abajo, como si llevaran un abrigo de hojas. Tienen terrazas llenas de huertos donde crecen tomates, lechugas y fresas, y en sus tejados giran unos molinos pequeños y silenciosos que parecen flores de metal." },
      { p: "Entre los edificios, a media altura, pasan los tranvías aéreos: unos vagones transparentes, ligeros como burbujas, que se deslizan por raíles colgantes sin hacer ruido. Por las calles no circulan coches. El suelo de las avenidas es de un material blando y claro que recoge la energía de nuestros pasos y, por la noche, brilla con una luz suave, como un río de luciérnagas." },
      { p: "Mi colegio también te sorprendería. Las paredes de las aulas son de un cristal que se oscurece solo cuando el sol aprieta, y en vez de pizarra tenemos una pantalla que ocupa toda una pared. Pero lo que más me gusta es el patio: está en la azotea, rodeado de árboles frutales, y tiene un huerto donde cada clase cuida sus propias plantas. Al lado hay un gallinero, y los lunes nos toca recoger los huevos." },
      { p: "Mi casa está en un barrio que se llama Los Almendros. Es pequeña y redonda, con paredes gruesas de un material parecido a la arcilla que mantiene el fresco en verano y el calor en invierno. Las ventanas son ovaladas, como ojos de buey de un barco, y en la cocina hay una despensa que te avisa cuando un alimento está a punto de estropearse. Mi habitación tiene el techo transparente, y por las noches me duermo mirando las nubes." },
      { p: "Abajo, en el centro de la ciudad, está mi lugar favorito: la Plaza del Agua. Es redonda y enorme, con una fuente en espiral que recoge la lluvia y la limpia para que podamos beberla. Alrededor hay árboles altísimos, bancos a la sombra y robots jardineros, pequeños y redondos como tortugas, que recortan el césped muy despacito." },
      { p: "Desde la plaza sale un paseo que sigue el antiguo cauce del río. Mi abuela cuenta que, cuando ella era niña, el río estaba escondido bajo el asfalto de una carretera. Ahora corre al aire libre, entre juncos y sauces, y en sus orillas hay patos, ranas y hasta una pareja de garzas que vive allí todo el año. Los sábados, las familias van a merendar a la orilla y los niños buscan renacuajos." },
      { p: "Las casas tienen formas curiosas: unas parecen conchas; otras, colmenas; y todas tienen el tejado cubierto de placas que atrapan el sol. En los barrios no hay vallas: los patios son compartidos y los vecinos cocinan juntos los domingos." },
      { p: "Cerca de mi casa está la biblioteca, que tiene forma de libro abierto. En su interior hay sillones colgantes, como nidos, en los que te puedes mecer mientras lees. Se pueden tomar prestados libros, pero también herramientas, juegos y hasta bicicletas. Mi madre dice que es la mejor idea que ha tenido nunca la ciudad." },
      { p: "Por la noche, Nueva Almedina parece otra ciudad. Las farolas no existen: la luz sale del suelo y de las fachadas, que brillan con un tono azulado muy suave para no molestar a los pájaros. Desde mi balcón se ven las estrellas, porque casi no hay luces que las tapen. Mi abuela dice que, cuando ella era pequeña, en las ciudades solo se veía la luna." },
      { p: "Los domingos, la Plaza del Agua se llena de puestos. Los vecinos cambian lo que les sobra de sus huertos: tomates por huevos, fresas por pan, lechugas por miel." },
      { p: "Aun así, no creas que todo es perfecto. A veces los robots se equivocan y riegan a la gente en vez de a las plantas, y mi hermano pequeño dice que echa de menos los charcos de verdad para saltar." },
      { p: "Me gustaría saber cómo era tu ciudad. ¿Había humo? ¿Se oían pájaros? Si puedes, contéstame. Guardaré tu respuesta en mi colección de cosas antiguas. Un abrazo desde el futuro, Aya." },
    ],
    vocabulario: [
      { p: "cápsula del tiempo", d: "Recipiente en el que se guardan objetos o mensajes para que se abran muchos años después." },
      { p: "raíl", d: "Barra de metal por la que se deslizan las ruedas de un tren o tranvía." },
      { p: "espiral", d: "Línea curva que da vueltas alrededor de un punto y se va alejando de él." },
      { p: "luciérnaga", d: "Insecto que despide una luz verdosa en la oscuridad." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tiene de especial el suelo de las avenidas? Elige:", opciones: ["Es de cristal", "Recoge la energía de los pasos y brilla de noche", "Se mueve solo"], r: "Recoge la energía de los pasos y brilla de noche" },
      { tipo: "comprension", q: "¿Por qué desde el balcón de Aya se ven las estrellas?", r: "Porque casi no hay luces que las tapen: la luz sale del suelo y de las fachadas y es muy suave.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué nos dice de Aya el párrafo de los robots y los charcos?", r: "Que es sincera y tiene sentido del humor: reconoce que su ciudad no es perfecta.", lineas: 2 },
      { tipo: "texto", q: "Copia dos comparaciones. ¿Por qué crees que la autora las usa tanto para describir algo que no existe?", r: "«como si llevaran un abrigo de hojas», «parecen flores de metal», «ligeros como burbujas», «como un río de luciérnagas», «redondos como tortugas». Porque comparar con cosas conocidas ayuda a imaginar lo desconocido.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué invento de Nueva Almedina te gustaría tener hoy en tu ciudad? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué decisiones de hoy harán que las ciudades del futuro sean mejores para vivir? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "descriptivo-08-alhambra",
    titulo: "La Alhambra al atardecer",
    subtipo: "Topografía (descripción subjetiva de un lugar)",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Has visto alguna vez un atardecer que te impresionara? ¿Dónde fue y qué recuerdas?",
    texto: [
      { p: "Hay un lugar en Granada donde, al caer la tarde, la gente deja de hablar. Es el mirador de San Nicolás, en lo alto del Albaicín, el antiguo barrio de calles estrechas y casas blancas. Aquel día de octubre, mi familia y yo llegamos justo a tiempo, cuando el sol empezaba a bajar." },
      { p: "Para llegar hasta allí subimos a pie desde el río. Las calles del Albaicín son tan estrechas que, en algunas, casi puedes tocar las dos paredes a la vez con los brazos abiertos. Suben y bajan, se retuercen y a veces terminan en escaleras. El suelo está empedrado con cantos rodados que forman dibujos, y sobre las tapias asoman las ramas de los cármenes, casas con huerto y jardín de las que salían olores de jazmín y de naranjo. En una esquina, un gato dormía sobre una maceta, indiferente a los turistas." },
      { p: "A mitad de la subida nos paramos a descansar en una placita con una fuente de piedra. Mi hermana bebió agua con las manos y mi padre aprovechó para contarnos que muchas de aquellas calles tienen más de quinientos años. Desde allí ya se escuchaba, a lo lejos, el rumor de gente que venía del mirador." },
      { p: "El mirador es una plaza pequeña y empedrada, con un pretil de piedra al que se asoma todo el mundo. Había turistas con cámaras, abuelos sentados en los bancos y un chico que tocaba la guitarra muy bajito, como si no quisiera molestar al paisaje." },
      { p: "Junto al pretil, unos vendedores ofrecían pulseras de colores y dibujos de la Alhambra sobre una manta. Olía a castañas asadas y a pan recién hecho de una tienda cercana. La gente hablaba en muchos idiomas, pero todos miraban en la misma dirección, como si alguien les hubiera dado una señal." },
      { p: "A nuestros pies se abría el valle del río Darro, estrecho y profundo, lleno de árboles que empezaban a amarillear. Y al otro lado, sobre una colina alargada, estaba ella: la Alhambra. Parecía un enorme barco de piedra varado entre bosques, con las murallas como costados y las torres como mástiles." },
      { p: "A la derecha se alzaba la Alcazaba, la parte más antigua, con sus torres cuadradas y robustas, que parecían soldados de guardia. En el centro, más delicados, asomaban los palacios nazaríes y la torre de Comares. A la izquierda, entre cipreses oscuros y afilados como lápices, se adivinaban los jardines del Generalife." },
      { p: "Si mirabas con atención, podías ver los detalles: las pequeñas ventanas de las torres, estrechas como ranuras; las almenas recortadas contra el cielo, como los dientes de un peine; y los tejados de las casas del interior, casi escondidos detrás de los muros. A nuestra izquierda, más allá de las últimas casas del Albaicín, asomaban las cuevas blancas del Sacromonte, con sus chumberas y sus chimeneas." },
      { p: "Entonces empezó el espectáculo. El sol, que se ocultaba a nuestra derecha, iluminó las murallas con una luz cada vez más cálida. Primero se volvieron doradas; después, anaranjadas; y al final, de un rojo intenso, como brasas a punto de apagarse. Entendí por qué su nombre en árabe significa «la roja»." },
      { p: "Detrás de la Alhambra, muy lejos, las cumbres de Sierra Nevada, cubiertas por la primera nieve, se tiñeron de rosa. El cielo pasó del azul al violeta, y abajo, en la ciudad, se encendieron las primeras luces, como luciérnagas despistadas. Una bandada de vencejos cruzó chillando por delante de las torres, y el aire empezó a oler a humedad y a tierra." },
      { p: "Cuando el sol desapareció del todo, la gente del mirador aplaudió, igual que al final de una función de teatro. Yo no aplaudí. Me quedé quieto, intentando guardar aquellos colores en la memoria, porque sabía que ninguna fotografía sería capaz de copiarlos." },
      { p: "Mi madre me pasó el brazo por los hombros y no dijo nada. Creo que ella también estaba intentando guardarlo todo: el color de las torres, la música bajita de la guitarra, el frescor del aire y aquel silencio de tanta gente junta mirando lo mismo. Mi hermana, en cambio, se había quedado dormida en el banco." },
      { p: "Bajamos por la Carrera del Darro, junto al río, cuando ya era de noche. Al mirar hacia arriba, la Alhambra seguía allí, iluminada por los focos, dorada y silenciosa, como un barco que por fin hubiera encendido sus luces para pasar la noche." },
    ],
    vocabulario: [
      { p: "carmen", d: "En Granada, casa con huerto o jardín rodeada de tapias." },
      { p: "pretil", d: "Muro bajo que protege del peligro de caer en un mirador, un puente o una terraza." },
      { p: "varado", d: "Se dice del barco detenido en la arena o en la tierra." },
      { p: "nazarí", d: "De la dinastía que gobernó el reino de Granada entre los siglos XIII y XV." },
      { p: "brasa", d: "Trozo de leña o carbón encendido, rojo y sin llama." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Con qué compara el narrador la Alhambra vista de lejos? Elige:", opciones: ["Con un castillo de arena", "Con un enorme barco de piedra", "Con un soldado"], r: "Con un enorme barco de piedra" },
      { tipo: "comprension", q: "Explica cómo cambia el color de las murallas mientras se pone el sol.", r: "Primero se vuelven doradas; después, anaranjadas; y al final, de un rojo intenso.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué no aplaudió el narrador? ¿Qué nos dice eso de cómo se sentía?", r: "Porque quería guardar los colores en la memoria; estaba emocionado e impresionado y quería vivir el momento en silencio.", lineas: 2 },
      { tipo: "texto", q: "Copia dos expresiones de lugar y dos de tiempo. ¿Es una descripción objetiva o subjetiva? ¿Por qué?", r: "Lugar: a nuestros pies, al otro lado, a la derecha, en el centro, a la izquierda, detrás. Tiempo: entonces, primero, después, al final, cuando el sol desapareció. Es subjetiva: expresa sentimientos y usa comparaciones personales.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que una fotografía puede copiar un atardecer como ese? ¿Por qué?", r: "Respuesta libre. Valorar que argumenten.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante conservar monumentos del pasado como la Alhambra?", r: "Respuesta libre. Valorar ideas como la memoria, la historia compartida y el respeto a otras culturas.", lineas: 2 },
    ],
  },
  {
    id: "descriptivo-09-quijote",
    titulo: "Retrato de un hidalgo",
    subtipo: "Retrato (fragmento de novela)",
    curso: "6º",
    fuente: "Miguel de Cervantes, El ingenioso hidalgo don Quijote de la Mancha (1605), primera parte, capítulo I. Fragmentos reproducidos literalmente de la edición del Centro Virtual Cervantes (Instituto Cervantes); el signo […] indica que se omite un pasaje. El apartado «Para saber más» es un texto original para esta ficha.",
    antes: "¿Qué sabes de don Quijote? ¿Cómo te lo imaginas?",
    texto: [
      { p: "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino. Tenía en su casa una ama que pasaba de los cuarenta y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años. Era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de «Quijada», o «Quesada», que en esto hay alguna diferencia en los autores que deste caso escriben, aunque por conjeturas verisímiles se deja entender que se llamaba «Quijana». Pero esto importa poco a nuestro cuento: basta que en la narración dél no se salga un punto de la verdad." },
      { p: "Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso —que eran los más del año—, se daba a leer libros de caballerías, con tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la caza y aun la administración de su hacienda; y llegó a tanto su curiosidad y desatino en esto, que vendió muchas hanegas de tierra de sembradura para comprar libros de caballerías en que leer, y, así, llevó a su casa todos cuantos pudo haber dellos […]" },
      { p: "En resolución, él se enfrascó tanto en su letura, que se le pasaban las noches leyendo de claro en claro, y los días de turbio en turbio; y así, del poco dormir y del mucho leer, se le secó el celebro de manera que vino a perder el juicio. Llenósele la fantasía de todo aquello que leía en los libros, así de encantamentos como de pendencias, batallas, desafíos, heridas, requiebros, amores, tormentas y disparates imposibles; y asentósele de tal modo en la imaginación que era verdad toda aquella máquina de aquellas soñadas invenciones que leía, que para él no había otra historia más cierta en el mundo. […]" },
      { p: "En efeto, rematado ya su juicio, vino a dar en el más estraño pensamiento que jamás dio loco en el mundo, y fue que le pareció convenible y necesario, así para el aumento de su honra como para el servicio de su república, hacerse caballero andante y irse por todo el mundo con sus armas y caballo a buscar las aventuras y a ejercitarse en todo aquello que él había leído que los caballeros andantes se ejercitaban, deshaciendo todo género de agravio y poniéndose en ocasiones y peligros donde, acabándolos, cobrase eterno nombre y fama. […] Y lo primero que hizo fue limpiar unas armas que habían sido de sus bisabuelos, que, tomadas de orín y llenas de moho, luengos siglos había que estaban puestas y olvidadas en un rincón. […]" },
      { p: "Fue luego a ver su rocín, y aunque tenía más cuartos que un real y más tachas que el caballo de Gonela, que «tantum pellis et ossa fuit», le pareció que ni el Bucéfalo de Alejandro ni Babieca el del Cid con él se igualaban. Cuatro días se le pasaron en imaginar qué nombre le pondría; […] y así, después de muchos nombres que formó, borró y quitó, añadió, deshizo y tornó a hacer en su memoria e imaginación, al fin le vino a llamar «Rocinante», nombre, a su parecer, alto, sonoro y significativo de lo que había sido cuando fue rocín, antes de lo que ahora era, que era antes y primero de todos los rocines del mundo." },
      { h: "Para saber más" },
      { p: "Cervantes publicó la primera parte del Quijote en 1605 y la segunda en 1615. Quiso burlarse de los libros de caballerías, muy leídos en su época, y acabó escribiendo una de las novelas más importantes de la historia. Aquí dibuja un retrato lleno de humor: un hombre flaco y madrugador y un caballo que, según una frase en latín, era solo piel y huesos. Hasta el nombre de don Quijote tiene gracia: el quijote era la pieza de la armadura que protegía el muslo." },
    ],
    vocabulario: [
      { p: "hidalgo", d: "Noble de la categoría más baja, que solía tener poco dinero." },
      { p: "rocín", d: "Caballo de mala raza, flaco y de poca alzada." },
      { p: "enjuto", d: "Delgado, flaco." },
      { p: "celebro", d: "Forma antigua de «cerebro»." },
      { p: "orín", d: "Óxido rojizo que se forma en el hierro; herrumbre." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué significa «seco de carnes, enjuto de rostro»? Elige:", opciones: ["Que estaba muy delgado", "Que tenía la piel seca", "Que comía poca carne"], r: "Que estaba muy delgado" },
      { tipo: "comprension", q: "Según el texto, ¿por qué el hidalgo perdió el juicio?", r: "Por leer libros de caballerías día y noche: del poco dormir y del mucho leer se le secó el cerebro.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo era de verdad el caballo y cómo lo veía el hidalgo? ¿Qué nos dice eso de él?", r: "Era un rocín flaco, lleno de defectos, solo piel y huesos; pero a él le parecía mejor que Bucéfalo o Babieca. Muestra que ya confundía la realidad con sus fantasías.", lineas: 2 },
      { tipo: "texto", q: "Copia una frase de prosopografía y otra de etopeya. ¿El narrador describe con humor? Pon un ejemplo.", r: "Prosopografía: «Era de complexión recia, seco de carnes, enjuto de rostro». Etopeya: «gran madrugador y amigo de la caza». Hay humor: «que eran los más del año», «se le secó el celebro», el nombre de «Rocinante».", lineas: 3 },
      { tipo: "opinion", q: "¿Te ha pasado alguna vez que un libro, una serie o un juego te atrapara tanto que no podías pensar en otra cosa?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "El hidalgo vende tierras para comprar libros. ¿Por qué cosa renunciarías tú a otras? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "descriptivo-10-ojos-verdes",
    titulo: "La fuente de los Álamos",
    subtipo: "Topografía y prosopografía (fragmentos de leyenda)",
    curso: "6º",
    fuente: "Gustavo Adolfo Bécquer, «Los ojos verdes» (leyenda, 1861). Fragmentos reproducidos literalmente según sus Obras (1885) en Wikisource (los de la fuente, la tarde y la dama, cotejados además con la Biblioteca Virtual Miguel de Cervantes); se actualiza la acentuación (a por á). El signo […] indica que se omite un pasaje. Los subtítulos y el apartado «Para saber más» son añadidos para esta ficha.",
    antes: "¿Has estado alguna vez junto a un arroyo o una fuente en el campo? ¿Qué sonidos recuerdas?",
    texto: [
      { dato: "¿Sabías que Bécquer situó esta leyenda en el Moncayo, entre Soria y Zaragoza? En ella, un joven cazador, Fernando, le describe a su criado una fuente misteriosa donde cree haber visto a una mujer de ojos verdes." },
      { h: "Unos ojos soñados" },
      { p: "Yo creo que he visto unos ojos como los que he pintado en esta leyenda. No sé si en sueños, pero yo los he visto. De seguro no los podré describir tales cuales ellos eran, luminosos, trasparentes como las gotas de la lluvia que se resbalan sobre las hojas de los árboles después de una tempestad de verano." },
      { h: "La fuente" },
      { p: "Tú no conoces aquel sitio. Mira, la fuente brota escondida en el seno de una peña, y cae resbalándose gota a gota por entre las verdes y flotantes hojas de las plantas que crecen al borde de su cuna. Aquellas gotas que al desprenderse brillan como puntos de oro y suenan como las notas de un instrumento, se reúnen entre los céspedes, y susurrando, susurrando como un ruido semejante al de las abejas que zumban en torno de las flores, se alejan por entre las arenas, y forman un cauce, y luchan con los obstáculos que se oponen a su camino, y se repliegan sobre sí mismas, y saltan, y huyen, y corren, unas veces con risa, otras con suspiros, hasta caer en un lago. En el lago caen con un rumor indescriptible. Lamentos, palabras, nombres, cantares, yo no sé lo que he oído en aquel rumor cuando me he sentado solo y febril sobre el peñasco, a cuyos pies saltan las aguas de la fuente misteriosa para estancarse en una balsa profunda, cuya inmóvil superficie apenas riza el viento de la tarde." },
      { p: "Todo es allí grande. La soledad con sus mil rumores desconocidos, vive en aquellos lugares y embriaga el espíritu en su inefable melancolía. En las plateadas hojas de los álamos, en los huecos de las peñas, en las ondas del agua, parece que nos hablan los invisibles espíritus de la naturaleza, que reconocen un hermano en el inmortal espíritu del hombre." },
      { p: "[…] Tal vez sería un rayo de sol que serpeó fugitivo entre su espuma; tal vez una de esas flores que flotan entre las algas de su seno, y cuyos cálices parecen esmeraldas... no sé: yo creí ver una mirada que se clavó en la mía; una mirada que encendió en mi pecho un deseo absurdo, irrealizable: el de encontrar una persona con unos ojos como aquellos." },
      { h: "Al caer la tarde" },
      { p: "El sol había traspuesto la cumbre del monte; las sombras bajaban a grandes pasos por su falda; la brisa gemía entre los álamos de la fuente, y la niebla, elevándose poco a poco de la superficie del lago, comenzaba a envolver las rocas de su margen." },
      { h: "La dama de la fuente" },
      { p: "Ella era hermosa, hermosa y pálida, como una estatua de alabastro. Uno de sus rizos caía sobre sus hombros, deslizándose entre los pliegues del velo como un rayo de sol que atraviesa las nubes, y en el cerco de sus pestañas rubias brillaban sus pupilas como dos esmeraldas sujetas en una joya de oro." },
      { h: "Para saber más" },
      { p: "Gustavo Adolfo Bécquer nació en Sevilla en 1836 y murió en Madrid en 1870. Es uno de los grandes autores del Romanticismo español. Sus obras más conocidas son las Rimas, poemas breves sobre el amor y la poesía, y las Leyendas, relatos de misterio situados en lugares antiguos, muchos de ellos en Soria y en Toledo. «Los ojos verdes», por ejemplo, se publicó en 1861 en un periódico de Madrid, El Contemporáneo. Bécquer escribía como si pintara: por eso sus descripciones están llenas de luces, colores y sonidos." },
    ],
    vocabulario: [
      { p: "peña", d: "Roca grande." },
      { p: "febril", d: "Con fiebre; muy agitado o nervioso." },
      { p: "inefable", d: "Tan intenso que no se puede explicar con palabras." },
      { p: "cáliz", d: "Parte exterior de la flor, formada por hojitas verdes que sujetan los pétalos." },
      { p: "alabastro", d: "Piedra blanca y algo transparente que se usa en esculturas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Con qué compara Bécquer el susurro del agua? Elige:", opciones: ["Con el zumbido de las abejas", "Con el canto de los pájaros", "Con el viento en los álamos"], r: "Con el zumbido de las abejas" },
      { tipo: "comprension", q: "¿Cómo son los ojos de la dama y con qué los compara el autor?", r: "Verdes y brillantes; los compara con dos esmeraldas sujetas en una joya de oro.", lineas: 2 },
      { tipo: "comprension", q: "El agua corre «unas veces con risa, otras con suspiros». ¿Qué recurso es y qué efecto consigue?", r: "Una personificación: atribuye al agua acciones humanas, y así la fuente parece viva y misteriosa.", lineas: 2 },
      { tipo: "texto", q: "¿Qué partes son topografía y cuál es prosopografía? ¿Es una descripción subjetiva? Copia un adjetivo y una comparación.", r: "Topografía: la fuente y el atardecer. Prosopografía: la dama. Es subjetiva: adjetivos como «indescriptible», «inefable», «plateadas», «pálida»; comparaciones como «como puntos de oro», «como una estatua de alabastro».", lineas: 3 },
      { tipo: "opinion", q: "¿Qué fragmento te ha gustado más: la fuente, el atardecer o la dama? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Te ha transmitido algo alguna vez un paisaje? ¿Por qué crees que la naturaleza nos emociona?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
];
