// Lecturas · Diálogo y debate (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["dialogo"] = [
  // ------------------------------------------------------------------ 01
  {
    id: "dialogo-01-huerto-escolar",
    titulo: "¿Quién se ha comido las lechugas?",
    subtipo: "Conversación en estilo directo",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Tenéis huerto en el colegio o conocéis alguno? ¿Qué se cultiva en él?",
    texto: [
      { p: "El lunes, al llegar al huerto del colegio, los alumnos de quinto se quedaron de piedra. Las lechugas que habían plantado en octubre estaban llenas de agujeros." },
      { p: "El huerto era un rectángulo de tierra junto a la valla, con cuatro bancales: lechugas, habas, fresas y plantas aromáticas. Cada semana, un grupo distinto se encargaba de regarlo y de apuntar en un cuaderno cómo crecían las plantas. Hasta ese día, todo había ido de maravilla." },
      { p: "—¡Alguien se ha comido nuestras lechugas! —gritó Mateo, con las manos en la cabeza." },
      { p: "—No exageres —dijo Lucía—. Solo tienen agujeritos. Se pueden salvar." },
      { p: "—¿Y quién ha sido? —preguntó Iván—. Yo apuesto por los de sexto. Siempre están mirando nuestro huerto." },
      { p: "—Pues yo creo que ha sido un conejo —opinó Mateo—. Los conejos se vuelven locos con las lechugas. Lo he visto en los dibujos animados." },
      { p: "—¿Un conejo en mitad del barrio? —se rio Lucía—. Serán los gorriones, que siempre andan picoteando por aquí." },
      { p: "Cada uno defendía su idea, cada vez más alto, hasta que la maestra, Inmaculada, levantó la mano para pedir calma." },
      { p: "—Tres culpables distintos y ninguna prueba —dijo—. Antes de acusar a nadie, vamos a observar. ¿Qué veis en las hojas?" },
      { p: "Julia, que hasta entonces no había dicho nada, se agachó y apartó una hoja con cuidado." },
      { p: "—Aquí hay un rastro brillante, como de baba —explicó—. Y debajo de esta piedra… ¡mirad!" },
      { p: "Todos se acercaron. Tres caracoles descansaban tan tranquilos a la sombra." },
      { p: "—¡Los culpables! —exclamó Mateo—. Pues los de sexto tienen coartada." },
      { p: "—Y los gorriones también —admitió Lucía." },
      { p: "—Perdón por lo que he dicho de los de sexto —murmuró Iván, un poco avergonzado." },
      { p: "—Los caracoles salen de noche y con humedad —explicó la maestra—. Este fin de semana ha llovido, así que han tenido una fiesta. ¿Sabéis que tienen la lengua cubierta de dientecillos diminutos? Con ella raspan las hojas como si fuera una lima." },
      { p: "—¡Qué asco! —dijo Mateo—. Bueno… y qué interesante." },
      { p: "Uno de los caracoles, como si supiera que hablaban de él, asomó muy despacio los cuernos y se puso a pasear por la piedra." },
      { p: "—¿Y qué hacemos? —preguntó Lucía—. No quiero hacerles daño." },
      { p: "—Mi tío les echa sal y se acabó el problema —dijo Mateo." },
      { p: "—¡Eso es cruel! —protestó Lucía—. Los caracoles no saben que las lechugas son nuestras. Para ellos, esto es un restaurante gratis." },
      { p: "—Lucía tiene razón —dijo la maestra—. Además, en la naturaleza todo está conectado: los caracoles sirven de alimento a erizos, lagartijas y pájaros. Si los eliminamos, también les quitamos comida a ellos." },
      { p: "—Podemos llevarlos al parque de al lado, lejos del huerto —propuso Julia—. Y poner cáscaras de huevo trituradas alrededor de las lechugas. Mi abuelo dice que a los caracoles no les gusta pasar por encima." },
      { p: "—Me parece una idea estupenda —respondió la maestra, sonriendo—. Iván, ¿quieres encargarte de avisar a los de sexto para que nos guarden cáscaras?" },
      { p: "—Vale —contestó Iván—. Y de paso les pido perdón en persona." },
      { p: "Aquella mañana, los caracoles se mudaron al parque y las lechugas recibieron un collar de cáscaras. Al día siguiente, los de sexto aparecieron con una caja llena de cáscaras y un cartel pintado a mano: «Prohibido el paso a caracoles». Iván les pidió perdón y ellos se rieron: también les habían desaparecido unas fresas el año anterior y habían culpado a los de cuarto." },
      { p: "Desde entonces, en el cuaderno del huerto hay una norma nueva, escrita con la letra de Julia: «Antes de buscar culpables, conviene buscar pistas»." },
    ],
    vocabulario: [
      { p: "quedarse de piedra", d: "quedarse muy sorprendido, sin saber qué decir." },
      { p: "coartada", d: "prueba de que alguien no estaba donde ocurrió algo y, por tanto, es inocente." },
      { p: "triturado", d: "partido en trozos muy pequeños." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué culpables proponen Iván, Mateo y Lucía? ¿Qué pistas descubren al final quién fue?", r: "Iván culpa a los de sexto; Mateo, a un conejo; Lucía, a los gorriones. Las pistas son el rastro brillante de baba en las hojas y los caracoles escondidos debajo de una piedra.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Mateo con «los de sexto tienen coartada»? Elige:", opciones: ["Que los de sexto han hecho trampa.", "Que ya se sabe que los de sexto no han sido.", "Que los de sexto tienen un huerto más grande."], r: "Que ya se sabe que los de sexto no han sido." },
      { tipo: "comprension", q: "¿Por qué crees que la maestra le encarga a Iván que hable con los de sexto?", r: "Para que tenga la oportunidad de disculparse y arreglar la situación con ellos, ya que los había acusado sin pruebas.", lineas: 2 },
      { tipo: "texto", q: "En «—Aquí hay un rastro brillante, como de baba —explicó—.», ¿qué dice Julia y qué es del narrador? ¿Para qué sirve la raya (—)?", r: "Julia dice «Aquí hay un rastro brillante, como de baba». «Explicó» es del narrador. La raya indica que empieza a hablar un personaje y separa sus palabras de los comentarios del narrador.", lineas: 2 },
      { tipo: "opinion", q: "¿Alguna vez te han acusado de algo que no hiciste? ¿Cómo te sentiste?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante buscar pruebas antes de sacar conclusiones en una conversación o una discusión?", r: "Respuesta libre. Valorar que se relacione con el respeto y con no dañar a otros con acusaciones falsas.", lineas: 2 },
    ],
  },

  // ------------------------------------------------------------------ 02
  {
    id: "dialogo-02-llamada-abuela",
    titulo: "Abuela, ¿me oyes?",
    subtipo: "Conversación telefónica",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Con quién sueles hablar por teléfono? ¿En qué se diferencia hablar por teléfono de hablar cara a cara?",
    texto: [
      { p: "Adrián tenía que llevar a clase una receta típica de su familia. Así que, el martes por la tarde, llamó a su abuela Encarna, que vive en Úbeda, en la provincia de Jaén." },
      { p: "—¿Diga? —contestó la abuela." },
      { p: "—¡Hola, abuela! Soy Adrián." },
      { p: "—¡Hola, cariño! ¿Qué tal estás? ¿Ha pasado algo?" },
      { p: "—No, no, todo bien. Bueno, ayer perdimos el partido de baloncesto, pero metí dos canastas." },
      { p: "—¡Dos canastas! Eso hay que celebrarlo. ¿Y tu hermana?" },
      { p: "—Está en clase de guitarra. Abuela, te llamo porque necesito la receta de la pipirrana para el cole." },
      { p: "—¿De la piscina? ¿Qué piscina?" },
      { p: "—¡No, abuela! ¡La pi-pi-rra-na! Es que aquí hay poca cobertura. Espera, que me acerco a la ventana. ¿Me oyes ahora?" },
      { p: "—Ahora sí, como si estuvieras en la cocina. A ver, apunta: tomates bien maduros, un pimiento verde, media cebolla y, si quieres, un pepino." },
      { p: "—Tomates, pimiento, cebolla, pepino… Vale. ¿Y ahora?" },
      { p: "—Lo cortas todo en trocitos muy pequeños. Luego lo aliñas con aceite de oliva, un chorreón de vinagre y sal. Aquí, en Jaén, le añadimos huevo duro y un poco de atún." },
      { p: "—¿Y cuánta sal?" },
      { p: "—Una pizca." },
      { p: "—¿Una pizza? ¡Abuela, que se ha vuelto a cortar!" },
      { p: "—¡Una PIZ-CA, hijo! —dijo la abuela, muerta de risa—. Lo que cabe entre dos dedos. Con esta cobertura vas a acabar haciendo una receta italiana." },
      { p: "—¿Y el aceite de oliva de cuál?" },
      { p: "—¡Del bueno, hijo, del de aquí! —rio la abuela—. Y un consejo: déjala un rato en el frigorífico antes de comerla, que en verano sabe a gloria." },
      { p: "—Apuntado. Abuela, ¿y quién te enseñó a ti?" },
      { p: "—Mi madre, cuando yo tenía tu edad. Ella la hacía en un lebrillo de barro grandísimo, para toda la familia. En verano, después de trabajar en el olivar, nos sentábamos todos alrededor, cada uno con su trozo de pan, y mojábamos directamente del lebrillo." },
      { p: "—¿Sin platos?" },
      { p: "—Sin platos. Y nadie se quejaba, te lo aseguro. Lo mejor era el caldito del fondo." },
      { p: "—¡Eso lo pongo también en el trabajo! Muchas gracias, abuela." },
      { p: "—De nada, cariño. Y cuando la hagas, me mandas una foto, que quiero ver si te ha salido bien picada." },
      { p: "—Prometido. ¡Un beso muy grande!" },
      { p: "—Otro para ti. Adiós, mi vida." },
      { p: "Adrián colgó y miró su libreta. Además de una receta, tenía un trocito de la historia de su familia." },
      { p: "El sábado la preparó con su padre. Picaron las verduras muy despacio, para que quedaran pequeñitas, y la dejaron una hora en el frigorífico. Antes de probarla, Adrián le mandó una foto a la abuela. La respuesta llegó en un minuto: «¡Así se pica! Ya puedes venir a Úbeda a enseñar a tus primos»." },
    ],
    vocabulario: [
      { p: "pipirrana", d: "ensalada fría andaluza de tomate, pimiento y cebolla muy picados." },
      { p: "cobertura", d: "señal que necesita un teléfono móvil para funcionar bien." },
      { p: "aliñar", d: "echar aceite, vinagre, sal u otros condimentos a una comida." },
      { p: "lebrillo", d: "recipiente de barro, más ancho por arriba que por abajo, que se usaba para lavar o preparar comidas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué llama Adrián a su abuela?", r: "Porque necesita la receta de la pipirrana para un trabajo del colegio.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué ingredientes lleva la pipirrana según la abuela?", r: "Tomates maduros, pimiento verde, media cebolla, pepino (opcional), aceite de oliva, vinagre y sal; en Jaén, también huevo duro y atún.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la abuela entiende «piscina» en lugar de «pipirrana»? Elige:", opciones: ["Porque no sabe qué es la pipirrana.", "Porque hay poca cobertura y se oye mal.", "Porque Adrián lo dice mal a propósito."], r: "Porque hay poca cobertura y se oye mal." },
      { tipo: "comprension", q: "¿Qué quiere decir el narrador con la última frase: «tenía un trocito de la historia de su familia»?", r: "Que, además de la receta, ha descubierto cómo la preparaba su bisabuela: una costumbre que pasa de generación en generación.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo se nota que la abuela y Adrián se quieren mucho? Busca dos pistas.", r: "Por las palabras cariñosas («cariño», «mi vida»), los besos al despedirse, la preocupación de la abuela y la promesa de mandarle una foto.", lineas: 2 },
      { tipo: "texto", q: "¿Qué fórmulas se usan para empezar y terminar la conversación telefónica? ¿Por qué son necesarias?", r: "Para empezar: «¿Diga?», «Hola, soy Adrián». Para terminar: «Muchas gracias», «Un beso», «Adiós». Son necesarias porque por teléfono no nos vemos: hay que saber quién habla y dejar claro cuándo acaba la conversación.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué receta de tu familia te gustaría aprender? ¿A quién se la preguntarías?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Prefieres hablar por teléfono, mandar mensajes o hablar en persona? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante conservar las recetas y costumbres de nuestros mayores?", r: "Respuesta libre. Valorar referencias a la identidad, la memoria familiar y la cultura.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 03
  {
    id: "dialogo-03-entrevista-bombera",
    titulo: "Entrevista a una bombera",
    subtipo: "Entrevista",
    curso: "5º",
    fuente: "Texto original. Entrevista a un personaje inventado",
    antes: "¿Qué crees que hacen los bomberos además de apagar incendios?",
    texto: [
      { p: "Rocío Navarro es bombera en Córdoba desde hace doce años. La semana pasada visitó nuestro colegio y los alumnos de quinto le hicimos esta entrevista para el periódico escolar." },
      { h: "¿Por qué quisiste ser bombera?" },
      { p: "Cuando tenía vuestra edad, hubo un incendio en el monte cerca de mi pueblo. Vi cómo trabajaban los bomberos, todos juntos, sin descansar, y pensé: «Yo quiero ayudar así»." },
      { h: "¿Fue difícil conseguirlo?" },
      { p: "Sí. Hay que estudiar mucho y superar pruebas físicas muy duras: correr, nadar, subir por una cuerda… Entrené durante dos años. Y lo conseguí." },
      { h: "¿Solo apagáis fuegos?" },
      { p: "¡Qué va! Rescatamos a personas atrapadas en ascensores o en accidentes de tráfico, sacamos agua de casas inundadas, quitamos nidos de avispas peligrosos… Una vez rescatamos a un gato que llevaba dos días en lo alto de una palmera." },
      { h: "¿Qué es lo que más te gusta de tu trabajo?" },
      { p: "Trabajar en equipo. En un rescate, cada uno sabe lo que tiene que hacer y confiamos los unos en los otros. Mis compañeros son como mi familia." },
      { h: "¿Y lo más difícil?" },
      { p: "Las guardias largas, de veinticuatro horas, y no saber nunca qué va a pasar cuando suena la alarma. Pero para eso entrenamos todos los días." },
      { h: "¿Qué pueden hacer los niños para prevenir accidentes?" },
      { p: "Muchas cosas. No jugar con fuego ni con enchufes, no dejar basura en el campo, y aprender el número de emergencias: el 112. Y, en casa, tener un plan: saber por dónde salir y dónde reunirse si pasa algo." },
      { h: "Por último, ¿qué le dirías a quien quiera ser bombero o bombera?" },
      { p: "Que cuide su cuerpo, que estudie y que no tenga miedo de trabajar duro. Y que este oficio es para chicas y para chicos. Lo importante son las ganas de ayudar." },
    ],
    vocabulario: [
      { p: "rescatar", d: "sacar a alguien de un peligro." },
      { p: "guardia", d: "turno de trabajo en el que hay que estar preparado para actuar." },
      { p: "prevenir", d: "tomar medidas para que algo malo no ocurra." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién es la persona entrevistada y dónde trabaja?", r: "Rocío Navarro, una bombera que trabaja en Córdoba desde hace doce años.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué le hizo querer ser bombera?", r: "Un incendio en el monte cerca de su pueblo, cuando era niña: vio cómo trabajaban los bomberos en equipo y quiso ayudar como ellos.", lineas: 2 },
      { tipo: "comprension", q: "Nombra tres trabajos que hacen los bomberos además de apagar fuegos.", r: "Rescatar personas de ascensores o accidentes, sacar agua de casas inundadas, quitar nidos de avispas, rescatar animales.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Rocío con «Mis compañeros son como mi familia»? Elige:", opciones: ["Que trabaja con sus hermanos.", "Que confía en ellos y se siente muy unida a ellos.", "Que vive en el parque de bomberos."], r: "Que confía en ellos y se siente muy unida a ellos." },
      { tipo: "comprension", q: "¿Por qué crees que Rocío insiste en que el oficio es para chicas y para chicos?", r: "Porque todavía hay gente que piensa que es un trabajo solo de hombres, y quiere animar a las niñas a que también lo elijan.", lineas: 2 },
      { tipo: "texto", q: "En una entrevista, ¿quién pregunta y quién responde? ¿Cómo se distinguen las preguntas de las respuestas en este texto? ¿Para qué sirve el primer párrafo?", r: "Preguntan los alumnos (entrevistadores) y responde Rocío (entrevistada). Las preguntas van destacadas y separadas, y las respuestas debajo. El primer párrafo presenta a la entrevistada y explica el motivo de la entrevista.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué otra pregunta le habrías hecho tú a Rocío? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría ser bombero o bombera? Explica por qué.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Rocío habla de tener un plan en casa por si pasa algo. ¿Qué incluiría el plan de tu familia?", r: "Respuesta libre. Valorar ideas como salidas, punto de encuentro, número 112.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 04
  {
    id: "dialogo-04-directo-indirecto",
    titulo: "Lo que dijo Hugo",
    subtipo: "Diálogo en estilo directo y en estilo indirecto",
    curso: "5º",
    fuente: "Texto original",
    antes: "Cuando cuentas a alguien lo que te ha dicho otra persona, ¿repites sus palabras exactas o lo cuentas a tu manera?",
    texto: [
      { h: "Primera versión: en estilo directo" },
      { p: "En el recreo, Hugo se acercó a Nerea con cara de misterio." },
      { p: "—Tengo que contarte un secreto —susurró—. Mañana es el cumpleaños de la seño Pilar." },
      { p: "—¿En serio? —preguntó Nerea—. ¿Cómo lo sabes?" },
      { p: "—Lo he visto en el calendario de la sala de profesores —respondió Hugo—. Podríamos prepararle una sorpresa." },
      { p: "—¡Qué buena idea! —exclamó Nerea—. Yo traigo cartulinas y rotuladores." },
      { p: "—Y yo hablo con los demás. Pero no se lo digas a nadie de otra clase, que se corre la voz." },
      { h: "Segunda versión: en estilo indirecto" },
      { p: "Por la tarde, Nerea se lo contó a su madre así:" },
      { p: "En el recreo, Hugo se me acercó con cara de misterio. Me susurró que tenía que contarme un secreto: que al día siguiente era el cumpleaños de la seño Pilar. Yo le pregunté si lo decía en serio y cómo lo sabía. Él me respondió que lo había visto en el calendario de la sala de profesores y que podíamos prepararle una sorpresa. Yo le dije que era una idea buenísima y que llevaría cartulinas y rotuladores. Hugo añadió que él hablaría con los demás, y me pidió que no se lo dijera a nadie de otra clase, porque se correría la voz." },
      { h: "Lo que pasó al día siguiente" },
      { p: "Al entrar en clase, la seño Pilar vio una pancarta enorme que decía «¡Feliz cumpleaños!». Se quedó mirándola, sonrió y dijo que muchas gracias, que era precioso, pero que su cumpleaños era en junio. Hugo se puso rojo como un tomate: lo que había visto en el calendario era el cumpleaños del conserje, que también se llama Pilar." },
      { p: "Al final, toda la clase bajó a cantarle al conserje. Y Pilar, el conserje, dijo que era la primera vez en treinta años que le cantaban en el colegio." },
    ],
    vocabulario: [
      { p: "susurrar", d: "hablar en voz muy baja." },
      { p: "correrse la voz", d: "difundirse una noticia de persona en persona." },
      { p: "conserje", d: "persona que cuida un edificio, abre y cierra las puertas y ayuda en tareas del centro." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué secreto le cuenta Hugo a Nerea?", r: "Que al día siguiente es el cumpleaños de la seño Pilar y que podrían prepararle una sorpresa.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué se equivocó Hugo?", r: "Porque en el calendario ponía «Pilar», pero era el cumpleaños del conserje, que se llama igual que la maestra.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Hugo se pone «rojo como un tomate»? Elige:", opciones: ["Porque tiene fiebre.", "Porque le da vergüenza haberse equivocado.", "Porque está enfadado con Nerea."], r: "Porque le da vergüenza haberse equivocado." },
      { tipo: "comprension", q: "¿Crees que el error terminó siendo algo bueno? ¿Por qué?", r: "Sí: el conserje recibió una felicitación que nunca había tenido en treinta años y se sintió valorado.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que Hugo no quería que se enterasen otras clases?", r: "Para que la noticia no llegara a oídos de la maestra y se estropeara la sorpresa.", lineas: 2 },
      { tipo: "texto", q: "Compara las dos versiones. Transforma a estilo directo esta frase: «Yo le pregunté si lo decía en serio». ¿Qué cambia entre el estilo directo y el indirecto?", r: "—¿Lo dices en serio? —le pregunté. En estilo directo se reproducen las palabras exactas de los personajes con raya; en el indirecto, el narrador las cuenta con verbos como «dijo que» o «preguntó si», sin raya, y cambian los tiempos verbales, las personas y palabras como «mañana» por «al día siguiente».", lineas: 3 },
      { tipo: "opinion", q: "¿Qué versión te parece más viva y divertida de leer? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece bien que la clase fuera a cantarle al conserje? ¿Qué habrías hecho tú?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Las personas que trabajan en un colegio (conserjes, limpieza, comedor) también forman parte de él. ¿Cómo podríamos mostrarles nuestro agradecimiento?", r: "Respuesta libre. Valorar propuestas concretas.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 05
  {
    id: "dialogo-05-entrevista-abuela",
    titulo: "Cuando mi abuela tenía diez años",
    subtipo: "Entrevista",
    curso: "5º",
    fuente: "Texto original. Entrevista a un personaje inventado",
    antes: "¿Qué crees que ha cambiado más desde que tus abuelos eran niños?",
    texto: [
      { p: "Para el proyecto «Así vivían nuestros mayores», Samira entrevistó a su abuela Dolores, de 72 años, que se crio en un pueblo de la Alpujarra, en Granada." },
      { h: "Abuela, ¿cómo era tu casa cuando eras pequeña?" },
      { p: "Era una casa blanca, con el tejado plano de launa, una tierra gris que se ponía encima para que no entrara el agua. En invierno nos calentábamos con la chimenea y en verano dormíamos con la ventana abierta." },
      { h: "¿Teníais televisión?" },
      { p: "En mi casa, no. En el pueblo había una en el bar, y los domingos íbamos todos a verla. ¡Nos parecía magia! Lo que sí teníamos era una radio, y escuchábamos cuentos y canciones." },
      { h: "¿Cómo era tu escuela?" },
      { p: "Había una sola aula para niños de todas las edades, con una estufa en el centro. Los mayores ayudaban a los pequeños. Cada uno llevaba su cuaderno y su pizarrín." },
      { h: "¿A qué jugabas?" },
      { p: "A la comba, a la rayuela, a las chapas, al escondite… Y en verano bajábamos al río a coger renacuajos. No teníamos muchos juguetes, pero con una cuerda y cuatro piedras nos pasábamos la tarde." },
      { h: "¿Ayudabas en casa?" },
      { p: "¡Claro! Iba a por agua a la fuente, daba de comer a las gallinas y ayudaba en la cosecha de almendras. Todos los niños lo hacíamos." },
      { h: "¿Qué echas de menos de aquella época?" },
      { p: "Que la gente estaba mucho en la calle y los vecinos se ayudaban. Pero no lo echo todo de menos, ¿eh? Ahora hay agua en casa, médicos cerca y todas las niñas pueden estudiar. Eso es una suerte." },
      { h: "¿Qué consejo me darías?" },
      { p: "Que no pierdas la curiosidad. Pregunta, lee y sal a jugar. Y que de vez en cuando apagues la pantalla y mires las estrellas, que en mi pueblo se ven preciosas." },
    ],
    vocabulario: [
      { p: "criarse", d: "crecer y pasar la infancia en un lugar." },
      { p: "launa", d: "tierra arcillosa de color gris que se usa en la Alpujarra para cubrir los tejados planos." },
      { p: "pizarrín", d: "barrita para escribir sobre una pizarra pequeña." },
      { p: "renacuajo", d: "cría de la rana, que vive en el agua." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién hace la entrevista, a quién y para qué?", r: "Samira entrevista a su abuela Dolores para el proyecto escolar «Así vivían nuestros mayores».", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo era la escuela de la abuela? Di dos diferencias con la tuya.", r: "Una sola aula con niños de todas las edades, una estufa en el centro, pizarrín. Diferencias posibles: ahora hay varias clases por edades, calefacción, pizarra digital, libros…", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir la abuela con «con una cuerda y cuatro piedras nos pasábamos la tarde»? Elige:", opciones: ["Que jugaban solo a la comba.", "Que se divertían mucho con muy pocas cosas.", "Que construían casas de piedra."], r: "Que se divertían mucho con muy pocas cosas." },
      { tipo: "comprension", q: "¿Por qué dice la abuela que no lo echa todo de menos?", r: "Porque hoy hay avances importantes: agua en casa, médicos cerca y todas las niñas pueden estudiar.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que, en su infancia, ver la televisión era un acontecimiento para todo el pueblo?", r: "Porque casi nadie tenía televisión en casa; solo había una en el bar y era algo nuevo y sorprendente.", lineas: 2 },
      { tipo: "texto", q: "En esta entrevista, ¿cómo se respetan los turnos de palabra? ¿Qué papel tiene la entrevistadora?", r: "Se alternan pregunta y respuesta: Samira pregunta y espera, la abuela responde completa. La entrevistadora guía la conversación con preguntas ordenadas por temas, sin interrumpir.", lineas: 3 },
      { tipo: "opinion", q: "¿Te habría gustado ser niño o niña en la época de la abuela? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué pregunta le harías tú a una persona mayor de tu familia?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "La abuela dice que antes los vecinos se ayudaban más. ¿Crees que hoy también ocurre? ¿Cómo podríamos mejorar la convivencia en el barrio?", r: "Respuesta libre.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 06
  {
    id: "dialogo-06-debate-deberes",
    titulo: "¿Deberes el fin de semana?",
    subtipo: "Debate de clase transcrito",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Qué opinas de los deberes? ¿Te ayudan a aprender o te quitan tiempo para otras cosas?",
    texto: [
      { p: "Esta es la transcripción del debate celebrado en la clase de 5.º B. El moderador es Álvaro. Cada participante tiene un minuto por turno." },
      { personaje: "ÁLVARO (MODERADOR)", dice: "Buenos días. El tema de hoy es: ¿deberían mandarnos deberes el fin de semana? Recuerdo las normas: pedir la palabra levantando la mano, no interrumpir y respetar las opiniones. Empieza Carla, que está en contra." },
      { personaje: "CARLA", dice: "Gracias. Yo creo que el fin de semana es para descansar, estar con la familia y hacer deporte. Si trabajamos toda la semana, necesitamos desconectar para volver con más energía el lunes." },
      { personaje: "ÁLVARO (MODERADOR)", dice: "Gracias, Carla. Ahora Marcos, que está a favor." },
      { personaje: "MARCOS", dice: "Yo pienso que un poco de tarea ayuda a no olvidar lo aprendido. Si en dos días no repasamos nada, el lunes nos cuesta más arrancar. No digo muchos deberes, sino un ratito." },
      { personaje: "CARLA", acot: "sin pedir la palabra", dice: "¡Pero un ratito siempre acaba siendo una hora!" },
      { personaje: "ÁLVARO (MODERADOR)", dice: "Carla, por favor, espera tu turno. Marcos, ¿has terminado?" },
      { personaje: "MARCOS", dice: "Sí. Solo añado que leer un libro también cuenta como deber, y eso no cansa." },
      { personaje: "ÁLVARO (MODERADOR)", dice: "Tiene la palabra Yasmina." },
      { personaje: "YASMINA", dice: "Yo estoy entre las dos posturas. Hay familias que el fin de semana trabajan o viajan, y no todos tenemos a alguien en casa que nos ayude. Por eso propongo que los deberes del fin de semana sean voluntarios o de leer." },
      { personaje: "ÁLVARO (MODERADOR)", dice: "Carla, ahora sí puedes responder." },
      { personaje: "CARLA", dice: "Perdón por interrumpir antes. Estoy de acuerdo con Yasmina: leer por gusto no es lo mismo que hacer fichas." },
      { personaje: "MARCOS", dice: "A mí también me parece bien, siempre que se lea de verdad." },
      { personaje: "ÁLVARO (MODERADOR)", dice: "Se acaba el tiempo. Resumo las conclusiones: Carla defiende el descanso; Marcos, repasar un poco para no olvidar; y Yasmina propone una solución intermedia, la lectura voluntaria, que al final apoyan los tres. Llevaremos esta propuesta a la tutora. Gracias a todos por respetar los turnos." },
    ],
    vocabulario: [
      { p: "transcripción", d: "texto escrito que recoge exactamente lo que se ha dicho en voz alta." },
      { p: "moderador", d: "persona que dirige un debate: da los turnos y controla el tiempo." },
      { p: "postura", d: "opinión que alguien defiende sobre un tema." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuál es el tema del debate?", r: "Si deberían mandar deberes a los alumnos el fin de semana.", lineas: 1 },
      { tipo: "comprension", q: "Resume la postura y el argumento principal de Carla y de Marcos.", r: "Carla está en contra: el fin de semana es para descansar y estar con la familia. Marcos está a favor: un poco de tarea ayuda a no olvidar lo aprendido.", lineas: 3 },
      { tipo: "comprension", q: "¿Qué norma del debate incumple Carla? Elige:", opciones: ["No se prepara el tema.", "Interrumpe sin pedir la palabra.", "Habla más de un minuto."], r: "Interrumpe sin pedir la palabra." },
      { tipo: "comprension", q: "¿Por qué crees que Yasmina menciona que no todos tienen a alguien en casa que les ayude?", r: "Porque los deberes pueden ser injustos para quienes no tienen ayuda; quiere que se piense en todos los compañeros.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo demuestra Carla que ha entendido su error?", r: "Pide perdón por haber interrumpido antes de dar su opinión.", lineas: 1 },
      { tipo: "texto", q: "Explica qué hace el moderador en este debate. Da al menos tres ejemplos.", r: "Presenta el tema, recuerda las normas, da los turnos de palabra, corrige a Carla cuando interrumpe, controla el tiempo y resume las conclusiones al final.", lineas: 3 },
      { tipo: "opinion", q: "¿Con qué postura estás más de acuerdo? Da un argumento propio.", r: "Respuesta libre. Valorar que se aporte un argumento razonado.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece buena la solución final? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante que en un debate haya normas y un moderador? ¿Qué pasaría sin ellos?", r: "Respuesta libre. Valorar que se mencione el orden, el respeto y que todos puedan hablar.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 07
  {
    id: "dialogo-07-entrevista-paralimpico",
    titulo: "Correr con los ojos de otro",
    subtipo: "Entrevista",
    curso: "5º-6º",
    fuente: "Texto original. Entrevista a personajes inventados",
    antes: "¿Qué sabes de los Juegos Paralímpicos? ¿Conoces algún deporte adaptado?",
    texto: [
      { p: "Rubén Olmedo es atleta paralímpico. Es ciego desde los nueve años y corre los 400 metros con su guía, Sergio. Los dos entrenan en Málaga. Hablamos con ellos en la pista, después de un entrenamiento." },
      { h: "Rubén, ¿cómo empezaste a correr?" },
      { p: "RUBÉN: Siempre me gustó el deporte. Cuando perdí la vista pensé que se había acabado, pero un profesor de Educación Física me habló del atletismo adaptado. Probé y me enganché." },
      { h: "¿Cómo corréis juntos?" },
      { p: "SERGIO: Vamos unidos por una cinta corta, atada a la mano. Tenemos que mover los brazos y las piernas a la vez, como si fuéramos una sola persona con cuatro piernas." },
      { p: "RUBÉN: Y Sergio me va hablando: «curva», «recta», «últimos cien». Su voz es mi mapa." },
      { h: "Sergio, ¿puedes tirar de Rubén para que vaya más rápido?" },
      { p: "SERGIO: No, está prohibido. Yo le guío, pero la carrera la corre él. Además, al llegar, Rubén tiene que cruzar la meta antes que yo. Si no, nos descalifican." },
      { h: "¿Por qué lleváis un antifaz los dos en algunas fotos?" },
      { p: "RUBÉN: Solo lo llevo yo en competición, para que todos los atletas de mi categoría corramos en igualdad. A veces, para entrenar la confianza, Sergio se lo pone y soy yo quien le habla. ¡Os aseguro que corre mucho más despacio!" },
      { p: "SERGIO: Es verdad. Es la mejor forma de entender lo que siente él." },
      { h: "¿Qué es lo más importante entre vosotros?" },
      { p: "RUBÉN: La confianza. Pongo mi seguridad en manos de Sergio. Si él duda, yo lo noto." },
      { p: "SERGIO: Y comunicarse. Después de cada carrera hablamos de lo que ha salido bien y de lo que podemos mejorar, sin enfadarnos." },
      { h: "¿Qué os gustaría decir a los niños y niñas que leen esta entrevista?" },
      { p: "RUBÉN: Que nadie os diga lo que no podéis hacer. Buscad la manera. Y si necesitáis ayuda, pedidla: no es de débiles, es de listos." },
      { p: "SERGIO: Y que ayudar a otro a cumplir su sueño también es un sueño cumplido." },
    ],
    vocabulario: [
      { p: "paralímpico", d: "relacionado con las competiciones deportivas para personas con discapacidad." },
      { p: "adaptado", d: "cambiado para que pueda practicarlo cualquier persona, según sus necesidades." },
      { p: "descalificar", d: "expulsar a un deportista de una competición por no cumplir las reglas." },
      { p: "antifaz", d: "tela que tapa los ojos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quiénes son Rubén y Sergio? ¿Qué relación tienen?", r: "Rubén es un atleta paralímpico ciego que corre los 400 metros, y Sergio es su guía. Entrenan y compiten juntos.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo corren juntos y cómo se comunican durante la carrera?", r: "Unidos por una cinta corta atada a la mano, moviéndose a la vez. Sergio le va diciendo en voz alta dónde están: «curva», «recta», «últimos cien».", lineas: 2 },
      { tipo: "comprension", q: "¿Qué norma deben cumplir al llegar a la meta? Elige:", opciones: ["Tienen que llegar a la vez.", "Rubén debe cruzarla antes que Sergio.", "Sergio debe soltar la cinta antes de la meta."], r: "Rubén debe cruzarla antes que Sergio." },
      { tipo: "comprension", q: "¿Qué quiere decir Rubén con «Su voz es mi mapa»?", r: "Que las indicaciones de Sergio le permiten saber dónde está y hacia dónde ir, igual que un mapa.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que Sergio se pone a veces el antifaz para entrenar?", r: "Para ponerse en el lugar de Rubén, entender lo que siente y mejorar la confianza y la comunicación entre los dos.", lineas: 2 },
      { tipo: "texto", q: "En esta entrevista responden dos personas. ¿Cómo se sabe quién habla en cada momento? ¿Por qué es importante marcarlo en una entrevista escrita?", r: "Cada respuesta empieza con el nombre del que habla (RUBÉN, SERGIO) seguido de dos puntos. Es importante para que el lector sepa quién dice cada cosa y no se confundan los turnos.", lineas: 3 },
      { tipo: "opinion", q: "Rubén dice que pedir ayuda «no es de débiles, es de listos». ¿Estás de acuerdo? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría practicar algún deporte adaptado en Educación Física para ponerte en el lugar de otros? ¿Cuál?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué cosas de tu barrio o de tu colegio pueden ser un obstáculo para una persona ciega? ¿Cómo se podrían mejorar?", r: "Respuesta libre. Valorar ideas sobre accesibilidad: semáforos con sonido, suelos con relieve, carteles en braille, no dejar objetos en las aceras.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 08
  {
    id: "dialogo-08-entrevista-donana",
    titulo: "La científica de los linces",
    subtipo: "Entrevista",
    curso: "6º",
    fuente: "Texto original. Entrevista a un personaje inventado con datos reales",
    datos: ["Junta de Andalucía, Consejería de Sostenibilidad y Medio Ambiente: censo del lince ibérico 2024", "WWF España: «2400 linces ibéricos en la Península Ibérica» (censo 2024)", "CSIC: ficha de la Estación Biológica de Doñana", "Revista Quercus: «Lince ibérico: menor grado de amenaza, pero no está salvado»"],
    antes: "¿Qué sabes del lince ibérico? ¿Por qué crees que estuvo a punto de desaparecer?",
    texto: [
      { p: "Elena Márquez es bióloga y trabaja en la Estación Biológica de Doñana, un centro de investigación del CSIC (Consejo Superior de Investigaciones Científicas) fundado en 1964. Lleva quince años estudiando el lince ibérico. Nos atiende por videollamada desde su despacho en Sevilla." },
      { h: "¿Cómo es un día de trabajo para usted?" },
      { p: "Depende. Unos días estoy en el campo, en Doñana o en Sierra Morena, revisando cámaras de fototrampeo que se activan cuando pasa un animal. Otros días estoy en el ordenador analizando esas fotos: cada lince tiene un dibujo de manchas diferente, como nuestras huellas dactilares, y así sabemos quién es quién." },
      { h: "¿Es verdad que el lince estuvo a punto de extinguirse?" },
      { p: "Sí. A principios de este siglo quedaban menos de cien linces en todo el mundo, casi todos en Doñana y en Sierra Morena. Era el felino más amenazado del planeta." },
      { h: "¿Qué le pasaba?" },
      { p: "Varias cosas a la vez. Su comida principal es el conejo, y las enfermedades acabaron con muchísimos conejos. Además, perdió parte de su hábitat y muchos linces morían atropellados en las carreteras." },
      { h: "¿Y cómo se ha salvado?" },
      { p: "Con mucho trabajo en equipo: científicos, administraciones, agricultores, cazadores y asociaciones ecologistas. Se crearon centros de cría, se recuperaron las poblaciones de conejos, se construyeron pasos bajo las carreteras y se soltaron linces en nuevas zonas de España y Portugal. En el censo de 2024 se contaron más de 2.400 ejemplares." },
      { h: "¡Es una gran noticia!" },
      { p: "Lo es. En 2024, la Unión Internacional para la Conservación de la Naturaleza dejó de considerarlo en peligro y pasó a clasificarlo como vulnerable. Pero cuidado: vulnerable no significa salvado. Todavía hay que protegerlo." },
      { h: "¿Qué pueden hacer los niños y las niñas?" },
      { p: "Primero, conocer y querer la naturaleza que tenemos cerca. Segundo, respetarla: no dejar basura, no salir de los caminos y, cuando vayan en coche, recordar a los mayores que respeten las señales de paso de fauna. Y tercero, preguntar mucho. Todos los científicos empezamos siendo niños curiosos." },
      { h: "Una última pregunta: ¿ha visto muchos linces en persona?" },
      { p: "Unos cuantos. Pero cada vez que uno me mira desde el matorral, con esas orejas terminadas en pincel, se me acelera el corazón como el primer día." },
    ],
    vocabulario: [
      { p: "fototrampeo", d: "técnica para fotografiar animales salvajes con cámaras que se disparan solas al detectar movimiento." },
      { p: "extinguirse", d: "desaparecer para siempre una especie." },
      { p: "hábitat", d: "lugar con las condiciones adecuadas para que viva una especie." },
      { p: "censo", d: "recuento de los individuos de una población." },
      { p: "vulnerable", d: "que corre peligro, aunque menos grave que otras especies amenazadas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién es Elena Márquez y dónde trabaja?", r: "Una bióloga que estudia el lince ibérico en la Estación Biológica de Doñana, un centro del CSIC en Sevilla.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo distinguen los científicos a un lince de otro?", r: "Por el dibujo de sus manchas, que es diferente en cada lince, como las huellas dactilares; lo ven en las fotos de las cámaras de fototrampeo.", lineas: 2 },
      { tipo: "comprension", q: "Explica tres causas por las que el lince estuvo a punto de desaparecer.", r: "Las enfermedades de los conejos (su comida principal), la pérdida de hábitat y los atropellos en las carreteras.", lineas: 3 },
      { tipo: "comprension", q: "¿Qué quiere decir la científica con «vulnerable no significa salvado»? Elige:", opciones: ["Que el lince ya no necesita protección.", "Que ha mejorado, pero todavía está en peligro y hay que seguir protegiéndolo.", "Que el censo está mal hecho."], r: "Que ha mejorado, pero todavía está en peligro y hay que seguir protegiéndolo." },
      { tipo: "comprension", q: "¿Por qué crees que fue necesario el trabajo de grupos tan distintos (agricultores, cazadores, científicos…) para salvar al lince?", r: "Porque el lince vive en fincas y montes donde trabaja mucha gente; sin la colaboración de todos no se habrían recuperado los conejos ni protegido su hábitat.", lineas: 2 },
      { tipo: "texto", q: "Esta entrevista se hizo por videollamada. ¿Qué tienen en común una entrevista y una conversación? ¿En qué se diferencian?", r: "En las dos hay turnos de palabra y varias personas que hablan. En la entrevista, los papeles son fijos (uno pregunta, otro responde), las preguntas se preparan antes y tiene un objetivo: informar a los lectores.", lineas: 3 },
      { tipo: "opinion", q: "¿Te gustaría trabajar como científico o científica en la naturaleza? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que merece la pena gastar dinero y esfuerzo en salvar una especie? Da un argumento.", r: "Respuesta libre. Valorar que se argumente (equilibrio de los ecosistemas, responsabilidad humana…).", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué especie o espacio natural de tu entorno te gustaría proteger? ¿Qué harías para conseguirlo?", r: "Respuesta libre.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 09
  {
    id: "dialogo-09-debate-calle-colegio",
    titulo: "¿Una calle sin coches a la puerta del cole?",
    subtipo: "Debate de clase transcrito",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Cómo llegas al colegio cada mañana? ¿Cómo está la calle de la entrada a esa hora?",
    texto: [
      { p: "El Ayuntamiento ha preguntado a los colegios si quieren cerrar al tráfico su calle a la hora de entrada y salida. La clase de 6.º A lo ha debatido antes de votar. Modera Irene y toma notas Pablo, el secretario." },
      { personaje: "IRENE (MODERADORA)", dice: "Buenos días. Hoy debatimos si la calle del colegio debe cerrarse a los coches de ocho y media a nueve y cuarto, y de dos a dos y media. Habrá dos rondas: una para exponer argumentos y otra para responder. Cada intervención dura un minuto. Empieza el grupo a favor. Nerea, adelante." },
      { personaje: "NEREA", dice: "Estamos a favor por tres razones. La primera, la seguridad: a esa hora hay coches en doble fila y niños pequeños cruzando entre ellos. La segunda, el aire: los motores encendidos contaminan justo donde respiramos. Y la tercera, que así más familias vendrían andando o en bici, que es más sano." },
      { personaje: "IRENE (MODERADORA)", dice: "Gracias. Turno del grupo en contra. Tomás, tienes la palabra." },
      { personaje: "TOMÁS", dice: "Nosotros entendemos lo de la seguridad, pero hay familias que viven lejos o que después van a trabajar en coche. Y los vecinos de la calle tendrían problemas para entrar y salir de sus garajes. Si se cierra la calle, los coches irán a las calles de al lado y el atasco se moverá de sitio." },
      { personaje: "NEREA", acot: "levantando la mano", dice: "¿Puedo contestar?" },
      { personaje: "IRENE (MODERADORA)", dice: "Todavía no, Nerea. Primero termina la primera ronda. Wafaa, del grupo en contra." },
      { personaje: "WAFAA", dice: "Solo añado que mi hermano va en silla de ruedas y lo traemos en coche. Necesitamos poder llegar cerca de la puerta." },
      { personaje: "IRENE (MODERADORA)", dice: "Empieza la segunda ronda. Ahora sí, Nerea." },
      { personaje: "NEREA", dice: "Tomás y Wafaa tienen razón en algo importante. Pero se podría cerrar la calle y dejar pasar a los vecinos y a los coches de personas con movilidad reducida. Y para quien viene de lejos, se podría habilitar un aparcamiento a cinco minutos andando." },
      { personaje: "TOMÁS", dice: "Si se permite eso, nuestro grupo lo vería mejor. Pero habría que probarlo antes de decidirlo para siempre." },
      { personaje: "IRENE (MODERADORA)", dice: "Se ha terminado el tiempo. Pablo, lee las conclusiones, por favor." },
      { personaje: "PABLO (SECRETARIO)", dice: "Conclusiones: los dos grupos están de acuerdo en que hay que mejorar la seguridad. La propuesta final es cerrar la calle a las horas de entrada y salida, dejando pasar a vecinos y a personas con movilidad reducida, y probarlo durante tres meses." },
      { personaje: "IRENE (MODERADORA)", dice: "Pasamos a votar esta propuesta. Gracias a todos por respetar los turnos." },
    ],
    vocabulario: [
      { p: "doble fila", d: "coches parados junto a otros que ya están aparcados, ocupando un carril." },
      { p: "movilidad reducida", d: "dificultad para desplazarse o moverse." },
      { p: "habilitar", d: "preparar un lugar para un uso concreto." },
      { p: "secretario", d: "persona que toma notas de lo que se dice y se decide en una reunión." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué debate la clase este tema?", r: "Porque el Ayuntamiento ha preguntado a los colegios si quieren cerrar al tráfico su calle a la hora de entrada y salida.", lineas: 2 },
      { tipo: "comprension", q: "Escribe los tres argumentos del grupo a favor.", r: "La seguridad (coches en doble fila y niños cruzando), el aire limpio (menos contaminación) y que más familias irían andando o en bici.", lineas: 3 },
      { tipo: "comprension", q: "¿Por qué Irene no deja contestar a Nerea la primera vez? Elige:", opciones: ["Porque Nerea ya había hablado demasiado.", "Porque todavía no había terminado la primera ronda.", "Porque estaba en contra de su opinión."], r: "Porque todavía no había terminado la primera ronda." },
      { tipo: "comprension", q: "¿Qué argumento de Wafaa hace que el grupo a favor cambie su propuesta?", r: "Que su hermano va en silla de ruedas y necesitan llegar en coche cerca de la puerta; por eso Nerea propone dejar pasar a personas con movilidad reducida.", lineas: 2 },
      { tipo: "comprension", q: "¿Crees que alguien «ha ganado» el debate? Explica por qué.", r: "No exactamente: los dos grupos escucharon los argumentos del otro y llegaron a una propuesta común que recoge ideas de ambos.", lineas: 2 },
      { tipo: "texto", q: "Explica las funciones del moderador y del secretario en este debate. ¿Qué normas se siguen?", r: "La moderadora presenta el tema, explica las rondas, da y quita la palabra y controla el tiempo. El secretario toma notas y lee las conclusiones. Normas: pedir la palabra, respetar los turnos, un minuto por intervención, no interrumpir.", lineas: 3 },
      { tipo: "opinion", q: "¿Votarías a favor de la propuesta final? ¿Por qué?", r: "Respuesta libre. Valorar que se argumente.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué otro problema de tu colegio o de tu barrio te gustaría llevar a un debate?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "En este debate, escuchar al otro grupo sirvió para mejorar la propuesta. ¿Por qué es importante escuchar las opiniones contrarias?", r: "Respuesta libre. Valorar ideas como descubrir puntos de vista nuevos, pensar en todas las personas y llegar a acuerdos.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 10
  {
    id: "dialogo-10-mapa-desvan",
    titulo: "El mapa del desván",
    subtipo: "Relato dialogado en estilo directo",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Has encontrado alguna vez un objeto antiguo en casa? ¿Qué historia imaginaste sobre él?",
    texto: [
      { p: "Aquel sábado de lluvia, Martín y su prima Ainhoa subieron al desván de la casa del abuelo a buscar la caja de los adornos de Navidad. Entre sábanas polvorientas y maletas viejas, Ainhoa encontró un tubo de cartón." },
      { p: "—¿Qué será esto? —preguntó, sacudiéndole el polvo." },
      { p: "Dentro había un papel amarillento, enrollado y atado con una cinta roja. Martín lo desplegó con cuidado sobre un baúl." },
      { p: "—¡Es un mapa! —exclamó—. Mira: aquí está el río, esto parece la ermita… y aquí hay una cruz." },
      { p: "—Una cruz en un mapa solo puede significar una cosa —dijo Ainhoa, bajando la voz—: un tesoro." },
      { p: "—No corras tanto —respondió Martín, aunque los ojos le brillaban—. Lee lo que pone abajo." },
      { p: "Ainhoa acercó la linterna del móvil. Con una letra muy redonda, alguien había escrito: «Al pie del árbol más viejo, lo más valioso que tengo»." },
      { p: "—¡Lo sabía! —gritó Ainhoa, y dio un salto que levantó una nube de polvo—. ¡Vamos a buscarlo!" },
      { p: "—Espera —la frenó Martín—. Antes deberíamos preguntar al abuelo. El mapa es suyo." },
      { p: "Bajaron las escaleras de dos en dos. El abuelo Ramón estaba en la cocina, pelando castañas. Cuando vio el mapa, se quedó muy quieto y, después, soltó una carcajada." },
      { p: "—¡No me lo puedo creer! —dijo—. Este mapa lo dibujé yo cuando tenía vuestra edad." },
      { p: "—¿Y el tesoro? —preguntaron los dos a la vez." },
      { p: "—Enterré una lata con mis cosas más valiosas bajo la encina que hay junto a la ermita —explicó el abuelo, secándose las manos—. Luego nos mudamos al pueblo de al lado y nunca volví a buscarla." },
      { p: "Al día siguiente, ya sin lluvia, los tres fueron a la encina con una pala. Tardaron un buen rato, pero al fin sonó un «clonc» metálico. Dentro de la lata oxidada había una canica azul, una foto de tres niños sonrientes y una nota: «Amigos para siempre: Ramón, Julián y Rosario»." },
      { p: "—¿Esto era lo más valioso? —preguntó Martín, algo decepcionado." },
      { p: "El abuelo tomó la foto entre las manos y tardó en contestar." },
      { p: "—Julián vive todavía en el pueblo —dijo por fin, con la voz temblorosa—. Hace años que no hablamos. Creo que ha llegado el momento de llamarle." },
      { p: "Ainhoa le pasó el móvil sin decir nada. Aquella tarde, el tesoro sonó dos veces antes de que alguien contestara al otro lado." },
    ],
    vocabulario: [
      { p: "desván", d: "parte más alta de una casa, bajo el tejado, donde se guardan cosas viejas." },
      { p: "desplegar", d: "abrir y extender algo que estaba doblado o enrollado." },
      { p: "ermita", d: "pequeña capilla, normalmente a las afueras de un pueblo." },
      { p: "encina", d: "árbol grande de hoja perenne que da bellotas, muy común en Andalucía." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué encuentran Martín y Ainhoa en el desván y qué creen que significa?", r: "Un mapa antiguo con una cruz y una nota. Creen que señala un tesoro escondido.", lineas: 2 },
      { tipo: "comprension", q: "¿Quién dibujó el mapa y por qué no volvió a buscar la lata?", r: "El abuelo Ramón, cuando era niño. No volvió porque su familia se mudó al pueblo de al lado.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué había dentro de la lata? Elige:", opciones: ["Monedas antiguas y joyas.", "Una canica, una foto de tres amigos y una nota.", "Otro mapa."], r: "Una canica, una foto de tres amigos y una nota." },
      { tipo: "comprension", q: "¿Por qué el abuelo tarda en contestar y le tiembla la voz?", r: "Porque la foto le emociona: le recuerda a sus amigos de la infancia y a Julián, con quien hace años que no habla.", lineas: 2 },
      { tipo: "comprension", q: "Explica el sentido de la última frase: «el tesoro sonó dos veces antes de que alguien contestara».", r: "El verdadero tesoro es la amistad: la llamada a Julián (el teléfono suena) es la forma de recuperarla.", lineas: 2 },
      { tipo: "texto", q: "Observa: «—Una cruz en un mapa solo puede significar una cosa —dijo Ainhoa, bajando la voz—: un tesoro.» Explica para qué sirve cada raya y escribe tú una intervención de Martín con un comentario del narrador.", r: "La primera raya indica que empieza a hablar Ainhoa; la segunda y la tercera encierran el comentario del narrador («dijo Ainhoa, bajando la voz»), y después continúan las palabras del personaje. Ejemplo: —Vamos a preguntarle —dijo Martín— antes de salir.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué guardarías tú en una lata para abrirla dentro de muchos años? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que Martín tenía razón al querer preguntar al abuelo antes de buscar el tesoro? ¿Por qué?", r: "Respuesta libre. Valorar el respeto a lo que pertenece a otros.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que a veces dejamos de hablar con amigos a los que queremos? ¿Qué podemos hacer para no perderlos?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
];
