// Lecturas · Textos discontinuos (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["discontinuo"] = [
  // 1 ─────────────────────────────────────────────
  {
    id: "discontinuo-01-autobus-cazorla",
    titulo: "El autobús de la sierra",
    subtipo: "Horario de autobuses",
    curso: "5º",
    fuente: "Texto original. Horario inventado para esta ficha (las localidades son reales).",
    antes: "¿Has consultado alguna vez un horario de autobús o de tren? ¿Cómo encontraste la hora que buscabas?",
    texto: [
      { h: "Línea Cazorla – Úbeda (provincia de Jaén)" },
      { p: "Lucía tiene once años y vive en Peal de Becerro, un pueblo entre la sierra de Cazorla y Úbeda. Los martes tiene clase de violín en el conservatorio de Úbeda a las 11:00 y va en autobús con su abuela Rosario. Antes de salir, las dos miran siempre el horario que hay pegado en la parada. Está dividido en dos tablas, una para cada sentido del viaje, y va acompañado de los precios y de algunos avisos." },
      { tabla: { titulo: "IDA: Cazorla → Úbeda (lunes a viernes)", cab: ["Parada", "Bus 1", "Bus 2", "Bus 3", "Bus 4"], filas: [
        ["Cazorla", "07:15", "09:30", "13:45", "18:00"],
        ["Peal de Becerro", "07:35", "09:50", "14:05", "18:20"],
        ["Torreperogil", "07:55", "10:10", "14:25", "18:40"],
        ["Úbeda (estación)", "08:10", "10:25", "14:40", "18:55"],
      ] } },
      { tabla: { titulo: "VUELTA: Úbeda → Cazorla (lunes a viernes)", cab: ["Parada", "Bus 1", "Bus 2", "Bus 3", "Bus 4"], filas: [
        ["Úbeda (estación)", "08:30", "12:00", "15:30", "20:00"],
        ["Torreperogil", "08:45", "12:15", "15:45", "20:15"],
        ["Peal de Becerro", "09:05", "12:35", "16:05", "20:35"],
        ["Cazorla", "09:25", "12:55", "16:25", "20:55"],
      ] } },
      { tabla: { titulo: "Precios del billete sencillo", cab: ["Trayecto", "Billete normal", "Con bonobús joven"], filas: [
        ["Cazorla – Peal de Becerro", "1,40 €", "0,70 €"],
        ["Cazorla – Torreperogil", "2,30 €", "1,15 €"],
        ["Cazorla – Úbeda", "3,20 €", "1,60 €"],
        ["Peal de Becerro – Úbeda", "2,10 €", "1,05 €"],
        ["Torreperogil – Úbeda", "1,10 €", "0,55 €"],
      ] }, nota: "Menores de 4 años: gratis. El bonobús joven es para personas de 6 a 26 años." },
      { lista: [
        "Sábados: solo circulan los autobuses 2 y 4 de cada sentido, con el mismo horario.",
        "Domingos y festivos: no hay servicio.",
        "Llega a la parada cinco minutos antes de la hora indicada.",
        "Las bicicletas pueden viajar en el maletero, si hay sitio.",
        "Los menores de 12 años deben viajar acompañados por una persona adulta.",
      ], titulo: "Avisos importantes" },
      { lista: [
        "Busca la tabla del sentido en que viajas: ida o vuelta.",
        "Localiza la fila de tu parada de salida.",
        "Recorre esa fila hasta encontrar una hora que te venga bien: esa columna es tu autobús.",
        "Baja por la misma columna hasta la fila de tu destino: ahí está la hora de llegada.",
      ], ordenada: true, titulo: "Cómo leer el horario" },
      { p: "El martes pasado, la abuela Rosario se entretuvo charlando con una vecina y llegaron a la parada de Peal a las 09:55. El autobús acababa de irse. Lucía miró el horario, suspiró y sacó el móvil para avisar a su profesora: ese día llegaría tarde a clase." },
      { p: "Para la vuelta, la abuela quiere pasar antes por el mercado de Úbeda, que está a diez minutos andando de la estación. Si la clase termina a las 12:00, ¿les dará tiempo a comprar y a coger el autobús de las 12:00? Está claro que no. Tendrán que elegir otro." },
      { dato: "Las horas de los horarios se escriben en formato de 24 horas: 13:45 son las dos menos cuarto de la tarde y 20:55, las nueve menos cinco de la noche. Así no hay que escribir «de la mañana» o «de la tarde»." },
    ],
    vocabulario: [
      { p: "sentido", d: "Dirección en la que va un vehículo: de ida o de vuelta." },
      { p: "festivo", d: "Día en que no se trabaja ni hay colegio, aunque no sea domingo." },
      { p: "bonobús", d: "Tarjeta que permite viajar en autobús a un precio más barato." },
      { p: "conservatorio", d: "Centro donde se estudia música." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Lucía tiene clase a las 11:00. ¿Qué autobús debe coger en Peal y a qué hora llega a Úbeda?", r: "El autobús 2, que sale de Peal a las 09:50 y llega a Úbeda a las 10:25.", lineas: 2 },
      { tipo: "comprension", q: "Si después de clase van al mercado, ¿qué autobús de vuelta pueden coger? ¿A qué hora llegan a Peal?", r: "El autobús 3 de vuelta, que sale de Úbeda a las 15:30 y llega a Peal de Becerro a las 16:05 (el de las 12:00 no les da tiempo).", lineas: 2 },
      { tipo: "comprension", q: "¿Cuánto pagan Lucía (con bonobús joven) y su abuela (billete normal) por ir de Peal a Úbeda? Elige:", opciones: ["3,15 €", "4,20 €", "2,10 €"], r: "3,15 €" },
      { tipo: "texto", q: "¿Por qué un horario es un texto discontinuo? ¿Para qué sirve la lista numerada que lo acompaña?", r: "Porque la información no va en párrafos seguidos, sino organizada en tablas. La lista numerada explica, paso a paso, cómo cruzar filas y columnas para encontrar una hora.", lineas: 2 },
      { tipo: "opinion", q: "¿Es importante que los pueblos pequeños tengan autobús aunque viaje poca gente? ¿Por qué?", r: "Respuesta libre. Valorar que piense en quienes no tienen coche: niños, mayores, estudiantes.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué podría pasar si en un horario hubiera una sola hora equivocada? Piensa en quienes lo usan cada día.", r: "Respuesta libre. Valorar que relacione la precisión de los datos con sus consecuencias (perder citas, esperar, enfadarse…).", lineas: 2 },
    ],
  },
  // 2 ─────────────────────────────────────────────
  {
    id: "discontinuo-02-menu-comedor",
    titulo: "¿Qué comemos esta semana?",
    subtipo: "Menú escolar semanal",
    curso: "5º",
    fuente: "Texto original. Menú inventado para esta ficha.",
    antes: "¿Qué plato del comedor o de casa te gusta más? ¿Y cuál te cuesta más comer?",
    texto: [
      { h: "Comedor escolar · Menú de la semana del 13 al 17 de octubre" },
      { p: "Cada viernes, el colegio envía a las familias el menú de la semana siguiente. Así en casa pueden saber qué comerán sus hijos a mediodía y preparar cenas que lo completen. El menú lo revisa una especialista en nutrición para que sea variado y equilibrado." },
      { tabla: { titulo: "Menú de mediodía", cab: ["Día", "Primer plato", "Segundo plato", "Postre"], filas: [
        ["Lunes", "Lentejas con verduras", "Tortilla de patatas con ensalada", "Naranja"],
        ["Martes", "Crema de calabacín", "Merluza al horno con patatas", "Yogur natural"],
        ["Miércoles", "Arroz con tomate", "Pollo asado con zanahoria", "Plátano"],
        ["Jueves", "Garbanzos con espinacas", "Filete de pavo con pimientos", "Manzana"],
        ["Viernes", "Macarrones con tomate", "Boquerones al horno con ensalada", "Natillas caseras"],
      ] } },
      { lista: [
        "Huevo: lunes (tortilla) y viernes (natillas).",
        "Pescado: martes y viernes.",
        "Leche: martes (yogur y crema) y viernes (natillas).",
        "Gluten: viernes (macarrones).",
      ], titulo: "Alérgenos del menú" },
      { p: "El alumnado con alergias o intolerancias recibirá un menú alternativo. Las familias deben avisar en secretaría, con un informe médico, antes del jueves de la semana anterior." },
      { h: "El menú alternativo de Ahmed" },
      { p: "Ahmed, de 5.º, es alérgico al huevo. Su familia entregó el informe del médico en septiembre, así que cada semana la cocina le prepara un menú alternativo. Los platos que no puede comer se cambian por otros parecidos, para que coma lo mismo que sus compañeros siempre que sea posible." },
      { tabla: { titulo: "Cambios en el menú de Ahmed", cab: ["Día", "Plato del menú", "Plato alternativo"], filas: [
        ["Lunes", "Tortilla de patatas con ensalada", "Filete de ternera a la plancha con ensalada"],
        ["Viernes", "Natillas caseras", "Mandarina"],
      ] } },
      { h: "¿Por qué este menú es equilibrado?" },
      { p: "Un menú equilibrado combina alimentos de muchos tipos a lo largo de la semana. En este hay legumbres dos días, pescado otros dos, carne blanca, huevo, arroz y pasta. Todos los días aparecen verduras u hortalizas, y el postre es casi siempre fruta. Los fritos y los dulces se dejan para días sueltos." },
      { dato: "Consejo para la cena: si a mediodía has comido carne o huevo, cena pescado. Si has comido pescado, cena carne o huevo. ¡Y siempre verdura y fruta!" },
      { tabla: { titulo: "Cenas que proponemos para completar el día", cab: ["Día", "Cena sugerida", "Postre"], filas: [
        ["Lunes", "Crema de verduras y sardinas a la plancha", "Pera"],
        ["Martes", "Ensalada de tomate y tortilla francesa", "Mandarina"],
        ["Miércoles", "Judías verdes y merluza a la plancha", "Yogur natural"],
        ["Jueves", "Sopa de fideos y pescado al horno", "Uvas"],
        ["Viernes", "Pisto con pechuga de pollo", "Manzana asada"],
      ] } },
      { lista: [
        "Lavarse las manos antes de entrar al comedor.",
        "Probar un poco de cada plato, aunque sea nuevo.",
        "Servirse el pan y el agua con calma, sin desperdiciar.",
        "Hablar en voz baja para que todos estemos a gusto.",
        "Recoger la bandeja y separar los restos al terminar.",
      ], titulo: "Normas del comedor" },
    ],
    vocabulario: [
      { p: "alérgeno", d: "Sustancia de un alimento que a algunas personas les produce alergia." },
      { p: "alternativo", d: "Que sustituye a otra cosa; en este caso, otro menú distinto." },
      { p: "legumbre", d: "Semilla que se cría en vainas, como las lentejas o los garbanzos." },
      { p: "intolerancia", d: "Problema del cuerpo para digerir bien un alimento." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué cambia el menú de Ahmed solo el lunes y el viernes? ¿Qué come él esos días?", r: "Porque es alérgico al huevo y solo esos días hay platos con huevo (tortilla y natillas). Come filete de ternera con ensalada el lunes y mandarina de postre el viernes.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la cena sugerida del martes lleva tortilla y no pescado? Usa el consejo del recuadro.", r: "Porque el martes a mediodía se come merluza (pescado), y el consejo dice que, si a mediodía has comido pescado, cenes carne o huevo.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuántos días hay legumbres de primer plato a mediodía? Elige:", opciones: ["Uno", "Dos", "Tres"], r: "Dos" },
      { tipo: "texto", q: "¿Qué información dan las dos tablas y qué dan las listas? ¿Por qué crees que se separan?", r: "Las tablas organizan por días los menús de mediodía y las cenas; las listas reúnen los alérgenos y las normas. Se separan para que cada lector encuentre rápido lo que busca.", lineas: 2 },
      { tipo: "opinion", q: "Si pudieras cambiar un plato del menú por otro igual de sano, ¿cuál cambiarías? ¿Por qué?", r: "Respuesta libre. Valorar que proponga un plato equilibrado.", lineas: 2 },
      { tipo: "reflexion", q: "¿Cómo te sentirías si fueras alérgico a un alimento y nadie lo tuviera en cuenta? ¿Cómo puedes ayudar tú?", r: "Respuesta libre. Valorar la empatía y propuestas concretas (no compartir comida, avisar a un adulto…).", lineas: 2 },
    ],
  },
  // 3 ─────────────────────────────────────────────
  {
    id: "discontinuo-03-centro-civico",
    titulo: "Otoño en el centro cívico",
    subtipo: "Cartelera de actividades",
    curso: "5º",
    fuente: "Texto original. Cartelera inventada para esta ficha.",
    antes: "¿Haces alguna actividad por las tardes? ¿Cómo la elegiste?",
    texto: [
      { h: "Centro Cívico Las Moreras · Actividades de octubre" },
      { p: "Este otoño, el centro cívico del barrio abre sus puertas con talleres para todas las edades. Hay actividades de ciencia, de arte, de deporte y de naturaleza, y algunas son gratuitas. Lee con atención la cartelera: fíjate en el día, la hora, la edad y el precio antes de elegir. Todos los talleres empiezan la semana del 13 de octubre y terminan en diciembre. ¡Elige el tuyo!" },
      { tabla: { titulo: "Cartelera de actividades", cab: ["Actividad", "Día", "Hora", "Edad", "Precio"], filas: [
        ["Taller de robótica", "Lunes", "17:30 a 19:00", "9 a 12 años", "12 € al mes"],
        ["Ajedrez", "Martes y jueves", "18:00 a 19:00", "Desde 7 años", "Gratis"],
        ["Baile flamenco", "Martes", "17:00 a 18:00", "8 a 14 años", "10 € al mes"],
        ["Teatro juvenil", "Miércoles", "17:00 a 18:00", "10 a 14 años", "8 € al mes"],
        ["Huerto urbano", "Miércoles", "18:00 a 19:00", "Desde 9 años", "Gratis"],
        ["Móviles sin miedo", "Jueves", "17:00 a 18:00", "Mayores de 60 y voluntarios desde 11 años", "Gratis"],
        ["Cómic y dibujo", "Viernes", "17:30 a 18:30", "8 a 13 años", "10 € al mes"],
        ["Cuentacuentos en familia", "Sábado", "11:00 a 12:00", "4 a 8 años", "Gratis"],
      ] } },
      { lista: [
        "Inscripciones en la recepción del centro, del 1 al 5 de octubre, de 9:00 a 14:00.",
        "Cada taller tiene 15 plazas. Se adjudican por orden de inscripción.",
        "Los menores de 12 años deben venir acompañados por un adulto a la inscripción.",
        "Si te apuntas a dos talleres de pago, el más barato de los dos te cuesta la mitad.",
      ], titulo: "Cómo apuntarse" },
      { tabla: { titulo: "¿Dónde es cada taller?", cab: ["Sala", "Planta", "Talleres"], filas: [
        ["Sala Azul", "Baja", "Robótica y Móviles sin miedo"],
        ["Sala Verde", "Primera", "Ajedrez y Cómic y dibujo"],
        ["Salón de actos", "Baja", "Teatro juvenil, Baile flamenco y Cuentacuentos en familia"],
        ["Patio trasero", "–", "Huerto urbano"],
      ] } },
      { tabla: { titulo: "Horario del centro cívico", cab: ["Días", "Mañana", "Tarde"], filas: [
        ["Lunes a viernes", "9:00 a 14:00", "16:30 a 21:00"],
        ["Sábados", "10:00 a 14:00", "Cerrado"],
        ["Domingos y festivos", "Cerrado", "Cerrado"],
      ] }, nota: "La recepción solo atiende inscripciones por la mañana." },
      { h: "Un taller diferente: «Móviles sin miedo»" },
      { p: "En este taller, chicos y chicas desde 11 años ayudan a personas mayores del barrio a usar el móvil: hacer una videollamada, enviar una foto o pedir cita en el médico. A cambio, los mayores cuentan cómo era el barrio cuando ellos eran niños. Los voluntarios reciben un diploma al terminar el curso." },
      { lista: [
        "«El huerto fue lo mejor: me llevé a casa mis propios tomates». (Leo, 10 años)",
        "«En robótica construimos un coche que esquivaba las sillas». (Marta, 12 años)",
        "«Mi nieta me enseñó a mandar fotos. Ahora no paro». (Aurelio, 74 años)",
      ], titulo: "Lo que dijeron el año pasado" },
      { dato: "Domingo 19 de octubre, a las 10:00: paseo en bici por el barrio para todas las edades. ¡Trae casco!" },
    ],
    vocabulario: [
      { p: "cartelera", d: "Lista o cartel que anuncia actividades, películas o espectáculos." },
      { p: "adjudicar", d: "Dar o asignar algo a alguien." },
      { p: "inscripción", d: "Acción de apuntarse a una actividad." },
      { p: "voluntario", d: "Persona que ayuda a otras sin cobrar por ello." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Nora tiene 11 años y los lunes sale de inglés a las 18:00. ¿Puede ir a robótica? ¿Por qué?", r: "No, porque el taller empieza a las 17:30, antes de que ella salga de inglés.", lineas: 2 },
      { tipo: "comprension", q: "Pablo tiene 8 años y su hermana Irene, 11. ¿Qué actividad gratuita pueden hacer juntos? ¿Por qué?", r: "Ajedrez: es gratis y es desde 7 años. Al huerto (desde 9) no puede ir Pablo, y al cuentacuentos (hasta 8), Irene tampoco.", lineas: 2 },
      { tipo: "comprension", q: "Marta se apunta a robótica y a teatro. ¿Cuánto paga al mes con el descuento? Elige:", opciones: ["20 €", "16 €", "10 €"], r: "16 €" },
      { tipo: "texto", q: "La cartelera mezcla tablas, listas y párrafos. ¿Qué ventaja tiene frente a un texto solo en párrafos?", r: "Se localiza cada dato (día, hora, edad, precio) de un vistazo, sin leer todo el texto seguido; los párrafos explican lo que necesita más detalle.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué actividad elegirías tú? Justifica tu respuesta con datos de la tabla.", r: "Respuesta libre. Valorar que use datos de la tabla (edad, horario, precio).", lineas: 2 },
      { tipo: "reflexion", q: "En «Móviles sin miedo» los jóvenes enseñan a los mayores. ¿Qué pueden aprender unos de otros?", r: "Respuesta libre. Valorar la idea de convivencia y ayuda entre generaciones.", lineas: 2 },
    ],
  },
  // 4 ─────────────────────────────────────────────
  {
    id: "discontinuo-04-clasificacion-liga",
    titulo: "La liga del barrio",
    subtipo: "Clasificación deportiva",
    curso: "5º",
    fuente: "Texto original. Liga y equipos inventados para esta ficha.",
    antes: "¿Sabes cómo se reparten los puntos en una liga de fútbol? ¿Qué significa ir primero en la clasificación?",
    texto: [
      { h: "Liga alevín mixta de fútbol sala · Clasificación tras la jornada 8" },
      { p: "Seis equipos de chicos y chicas de los colegios del barrio compiten cada fin de semana en el polideportivo municipal. La liga tiene diez jornadas: quedan dos y la lucha por el primer puesto está más emocionante que nunca. El equipo campeón recibirá el trofeo en la fiesta de fin de curso." },
      { h: "Resultados de la jornada 8" },
      { tabla: { titulo: "Jornada 8", cab: ["Equipo local", "Resultado", "Equipo visitante"], filas: [
        ["Los Linces", "3 – 2", "Rayo Veloz"],
        ["Atlético Olivar", "2 – 2", "Las Gaviotas"],
        ["CD Barrio Alto", "4 – 1", "Club Tortugas"],
      ] } },
      { p: "Crónica: Los Linces sufrieron para ganar al Rayo Veloz, que empató en el último minuto de la primera parte; un gol de Carla a falta de dos minutos les dio la victoria. En el partido más esperado, el Atlético Olivar y Las Gaviotas firmaron un empate lleno de ocasiones. El Club Tortugas perdió, pero su portero, Rubén, paró un penalti y el público lo aplaudió en pie." },
      { tabla: { titulo: "Clasificación", cab: ["Pos.", "Equipo", "PJ", "G-E-P", "GF", "GC", "Puntos"], filas: [
        ["1.º", "Los Linces", "8", "6-1-1", "30", "12", "19"],
        ["2.º", "Atlético Olivar", "8", "5-2-1", "26", "13", "17"],
        ["3.º", "Las Gaviotas", "8", "4-3-1", "22", "14", "15"],
        ["4.º", "CD Barrio Alto", "8", "3-2-3", "19", "18", "11"],
        ["5.º", "Rayo Veloz", "8", "1-1-6", "11", "25", "4"],
        ["6.º", "Club Tortugas", "8", "0-1-7", "8", "34", "1"],
      ] }, nota: "PJ: partidos jugados. G: ganados. E: empatados. P: perdidos. GF: goles a favor. GC: goles en contra." },
      { lista: [
        "Victoria: 3 puntos.",
        "Empate: 1 punto.",
        "Derrota: 0 puntos.",
        "Si dos equipos acaban con los mismos puntos, gana el que tenga más diferencia entre goles a favor y en contra.",
      ], titulo: "Reglas de la liga" },
      { p: "¿Quién puede ganar todavía la liga? Como quedan dos jornadas, cada equipo puede sumar como máximo 6 puntos más. Por eso Los Linces, el Atlético Olivar y Las Gaviotas siguen teniendo opciones, mientras que los demás ya solo pueden luchar por mejorar su puesto." },
      { tabla: { titulo: "Máximos goleadores", cab: ["Jugador o jugadora", "Equipo", "Goles"], filas: [
        ["Carla Ruiz", "Los Linces", "12"],
        ["Iker Moreno", "Atlético Olivar", "10"],
        ["Aya Benali", "Las Gaviotas", "9"],
        ["Samuel Díaz", "CD Barrio Alto", "7"],
        ["Lucía Campos", "Los Linces", "7"],
      ] } },
      { lista: [
        "Los Linces – Atlético Olivar (sábado, 10:00).",
        "Las Gaviotas – Club Tortugas (sábado, 11:30).",
        "CD Barrio Alto – Rayo Veloz (domingo, 10:00).",
      ], titulo: "Próxima jornada (jornada 9)" },
      { dato: "El Club Tortugas ha recibido el premio al juego limpio del primer trimestre: ¡ninguna tarjeta en ocho partidos!" },
    ],
    vocabulario: [
      { p: "jornada", d: "Conjunto de partidos que se juegan en las mismas fechas de una liga." },
      { p: "alevín", d: "Categoría deportiva para niños y niñas de unos 10 a 12 años." },
      { p: "crónica", d: "Texto que cuenta lo que ha pasado en un acontecimiento, en orden." },
      { p: "juego limpio", d: "Forma de jugar respetando las reglas, al rival y al árbitro." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Explica, con los datos de la tabla, cómo ha conseguido Las Gaviotas sus 15 puntos.", r: "Ha ganado 4 partidos (4 × 3 = 12) y ha empatado 3 (3 × 1 = 3): 12 + 3 = 15.", lineas: 2 },
      { tipo: "comprension", q: "Si el Atlético Olivar gana a Los Linces en la jornada 9, ¿quién irá primero? ¿Con cuántos puntos?", r: "El Atlético Olivar, con 20 puntos; Los Linces se quedarían con 19.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuántos goles ha marcado entre las dos goleadoras de Los Linces? Elige:", opciones: ["12", "19", "30"], r: "19" },
      { tipo: "texto", q: "La tabla usa abreviaturas como PJ o GF. ¿Dónde se explican? ¿En qué se diferencia la crónica de la tabla?", r: "En la nota de debajo de la tabla. La crónica cuenta lo que pasó en párrafos, con detalles; la tabla resume los datos de forma ordenada.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué es más importante para ti en un equipo: ganar o jugar limpio? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
      { tipo: "reflexion", q: "Imagina que juegas en el Club Tortugas. ¿Qué le dirías a tu equipo para seguir con ganas?", r: "Respuesta libre. Valorar mensajes de ánimo, esfuerzo y aprendizaje (por ejemplo, el penalti de Rubén o el premio al juego limpio).", lineas: 2 },
    ],
  },
  // 5 ─────────────────────────────────────────────
  {
    id: "discontinuo-05-reciclaje",
    titulo: "Cada residuo a su contenedor",
    subtipo: "Infografía",
    curso: "5º",
    fuente: "Texto original basado en las normas habituales de separación de residuos en España.",
    antes: "¿Separáis la basura en casa? ¿Cuántos cubos o bolsas usáis?",
    texto: [
      { h: "Guía rápida para reciclar en casa" },
      { p: "Separar los residuos en casa es el primer paso para que puedan convertirse en objetos nuevos. Si cada cosa va a su contenedor, las plantas de reciclaje pueden aprovecharla; si se mezcla, a menudo acaba enterrada en un vertedero. Busca en la tabla el color del contenedor y comprueba qué puedes echar en él y qué no." },
      { tabla: { titulo: "¿Qué va en cada contenedor?", cab: ["Contenedor", "Qué SÍ va", "Qué NO va"], filas: [
        ["Amarillo", "Envases de plástico, latas, briks, tapas metálicas, papel de aluminio", "Juguetes, cubos, biberones y otros objetos de plástico que no son envases"],
        ["Azul", "Papel y cartón: periódicos, cajas, folios, cuadernos", "Pañuelos y servilletas usados, papel de cocina sucio"],
        ["Verde", "Botellas y tarros de vidrio, sin tapa", "Vasos y copas de cristal, platos, espejos, bombillas"],
        ["Marrón (orgánico)", "Restos de comida, cáscaras, posos de café, servilletas de papel usadas", "Pañales, colillas, envases"],
        ["Gris (resto)", "Lo que no va en los demás: pañales, colillas, polvo de barrer", "Cualquier residuo que se pueda reciclar"],
      ] }, nota: "Las normas pueden cambiar un poco según el ayuntamiento." },
      { lista: [
        "Pilas: contenedor especial de pilas (en tiendas y edificios públicos).",
        "Medicamentos: punto de recogida de la farmacia.",
        "Aceite usado y aparatos eléctricos: punto limpio.",
        "Ropa y zapatos en buen estado: contenedor de ropa.",
      ], titulo: "Otros residuos" },
      { lista: [
        "Vacía bien los envases antes de tirarlos; no hace falta lavarlos.",
        "Aplasta las latas y las botellas de plástico y pliega las cajas de cartón: así caben más.",
        "Quita las tapas a los tarros de vidrio: el tarro va al verde y la tapa, al amarillo.",
        "Si dudas, pregunta en tu ayuntamiento antes de echarlo al gris.",
      ], titulo: "Consejos para separar bien" },
      { tabla: { titulo: "¿Y después, qué pasa?", cab: ["Contenedor", "En qué se puede convertir"], filas: [
        ["Amarillo", "Nuevos envases, bolsas, bancos de parque, fibras para tejidos"],
        ["Azul", "Papel y cartón reciclados: cajas, cuadernos, periódicos"],
        ["Verde", "Nuevas botellas y tarros"],
        ["Marrón", "Compost (un abono para el campo y los jardines) y biogás"],
        ["Gris", "Casi nada: va al vertedero o se quema para obtener algo de energía"],
      ] } },
      { dato: "El vidrio de los envases se puede reciclar una y otra vez sin perder calidad. En cambio, el cristal de los vasos y las copas no es igual: funde a otra temperatura y estropea el vidrio reciclado." },
      { h: "Mejor que reciclar: las tres erres" },
      { lista: [
        "Reducir: comprar solo lo necesario y evitar los envases de usar y tirar.",
        "Reutilizar: dar una segunda vida a las cosas (un tarro como lapicero, una camiseta vieja como trapo).",
        "Reciclar: separar lo que ya no sirve para que se convierta en algo nuevo.",
      ], ordenada: true, titulo: "Por este orden" },
      { p: "En casa de Hugo tenían un solo cubo de basura. Este curso han puesto tres cubos más debajo del fregadero, cada uno con una pegatina del color de su contenedor. Al principio se equivocaban mucho; ahora es Hugo quien corrige a su familia." },
    ],
    vocabulario: [
      { p: "residuo", d: "Lo que queda de algo después de usarlo y se tira." },
      { p: "brik", d: "Envase de cartón forrado por dentro, como los de leche o zumo." },
      { p: "punto limpio", d: "Lugar del municipio donde se llevan los residuos especiales." },
      { p: "vertedero", d: "Lugar donde se amontonan o entierran las basuras." },
      { p: "compost", d: "Abono que se obtiene al descomponerse los restos orgánicos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Tienes un tarro de mermelada vacío con su tapa metálica. ¿Qué haces con cada parte?", r: "El tarro, al verde (sin tapa); la tapa metálica, al amarillo.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué se convierte lo que echamos al contenedor marrón? ¿Por qué es mejor que tirarlo al gris?", r: "En compost (abono) y biogás. Si va al gris, casi no se aprovecha: acaba en el vertedero o se quema.", lineas: 2 },
      { tipo: "comprension", q: "¿Dónde se llevan los medicamentos que ya no se usan? Elige:", opciones: ["Al contenedor gris", "A la farmacia", "Al contenedor amarillo"], r: "A la farmacia" },
      { tipo: "texto", q: "¿Por qué esta guía usa tablas y listas en vez de un texto largo? ¿Qué ventaja tienen las columnas «SÍ» y «NO»?", r: "Porque así se encuentra enseguida la información. Las columnas permiten comparar de un vistazo lo que va y lo que no va en cada contenedor.", lineas: 2 },
      { tipo: "opinion", q: "Algunas personas dicen que separar la basura da mucho trabajo. ¿Qué les responderías?", r: "Respuesta libre. Valorar argumentos sobre el medio ambiente y los hábitos (por ejemplo, el ejemplo de la familia de Hugo).", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que reducir y reutilizar van antes que reciclar? Pon un ejemplo de tu vida diaria.", r: "Respuesta libre. Valorar que entienda que lo mejor es no producir el residuo (botella rellenable, fiambrera, comprar a granel…).", lineas: 2 },
    ],
  },
  // 6 ─────────────────────────────────────────────
  {
    id: "discontinuo-06-tabla-naranja",
    titulo: "Lo que esconde una naranja",
    subtipo: "Tabla de información nutricional",
    curso: "5º-6º",
    fuente: "Texto original con datos nutricionales reales (valores redondeados).",
    datos: ["USDA FoodData Central: «Oranges, raw, all commercial varieties» (FDC 169097)", "Valor de referencia de nutrientes de la Unión Europea (vitamina C: 80 mg/día)"],
    antes: "¿Has leído alguna vez la etiqueta de un alimento? ¿Qué información crees que aparece en ella?",
    texto: [
      { h: "Información nutricional: naranja cruda" },
      { p: "Andalucía es una de las principales zonas productoras de naranjas de España. Pero ¿qué nos aporta esta fruta? La tabla lo muestra para 100 gramos y para una naranja mediana, que pesa unos 150 gramos sin cáscara. Después, la compararemos con otras frutas muy conocidas." },
      { tabla: { titulo: "Composición de la naranja", cab: ["Nutriente", "Por 100 g", "Por naranja (150 g)"], filas: [
        ["Energía", "47 kcal", "71 kcal"],
        ["Hidratos de carbono", "11,8 g", "17,7 g"],
        ["… de los cuales azúcares", "9,4 g", "14,1 g"],
        ["Fibra", "2,4 g", "3,6 g"],
        ["Proteínas", "0,9 g", "1,4 g"],
        ["Grasas", "0,1 g", "0,2 g"],
        ["Vitamina C", "53 mg", "80 mg"],
      ] }, nota: "Fuente: USDA FoodData Central. Valores redondeados." },
      { dato: "La cantidad diaria de vitamina C de referencia para una persona adulta en la Unión Europea es de 80 mg." },
      { h: "¿Para qué sirve la vitamina C?" },
      { p: "Nuestro cuerpo no puede fabricar vitamina C, así que tenemos que tomarla con la comida, sobre todo con frutas y verduras. Ayuda a que funcionen bien las defensas, a que las heridas cicatricen y a aprovechar mejor el hierro de los alimentos. Como se estropea con el calor y con el aire, las frutas crudas y recién cortadas la conservan mejor." },
      { lista: [
        "Mira primero a qué cantidad se refieren los datos: ¿100 g, una ración, una pieza?",
        "Fíjate en las unidades: kcal para la energía, g (gramos) y mg (miligramos) para los nutrientes.",
        "Un miligramo es la milésima parte de un gramo: 80 mg son 0,08 g.",
        "Para comparar alimentos entre sí, usa siempre la columna de 100 g.",
      ], titulo: "Cómo leer una tabla nutricional" },
      { h: "La naranja frente a otras frutas" },
      { tabla: { titulo: "Comparación por cada 100 g", cab: ["Alimento", "Energía", "Azúcares", "Fibra", "Vitamina C"], filas: [
        ["Naranja", "47 kcal", "9,4 g", "2,4 g", "53 mg"],
        ["Zumo de naranja natural", "45 kcal", "8,4 g", "0,2 g", "50 mg"],
        ["Manzana con piel", "52 kcal", "10,4 g", "2,4 g", "4,6 mg"],
        ["Plátano", "89 kcal", "12,2 g", "2,6 g", "8,7 mg"],
        ["Kiwi verde", "61 kcal", "9,0 g", "3,0 g", "93 mg"],
        ["Fresa", "32 kcal", "4,9 g", "2,0 g", "59 mg"],
      ] }, nota: "Fuente: USDA FoodData Central. Valores redondeados." },
      { h: "¿Entera o en zumo?" },
      { p: "Los azúcares de la naranja son naturales y vienen acompañados de fibra, que ayuda a la digestión y hace que nos sintamos saciados. Al exprimirla, casi toda la fibra se queda en el colador, junto con la pulpa. Además, para llenar un vaso hacen falta unas dos o tres naranjas, que nos bebemos en un momento. Por eso es mejor comer la fruta entera que tomar solo el zumo." },
    ],
    vocabulario: [
      { p: "nutriente", d: "Sustancia de los alimentos que el cuerpo necesita para vivir y crecer." },
      { p: "kcal", d: "Kilocaloría: unidad que mide la energía que aporta un alimento." },
      { p: "fibra", d: "Parte de los vegetales que no se digiere y ayuda al intestino." },
      { p: "saciado", d: "Que ha comido lo suficiente y no tiene más hambre." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Una naranja mediana cubre la vitamina C diaria de referencia de un adulto? Justifícalo.", r: "Sí: una naranja de 150 g aporta unos 80 mg, justo la cantidad de referencia (80 mg).", lineas: 2 },
      { tipo: "comprension", q: "Compara la fibra de 100 g de naranja entera y de 100 g de zumo. ¿Qué conclusión sacas?", r: "La naranja tiene 2,4 g y el zumo solo 0,2 g: doce veces menos. Conviene comer la fruta entera, porque al exprimirla se pierde casi toda la fibra.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué alimento de la comparación tiene más vitamina C por cada 100 g? Elige:", opciones: ["Naranja", "Kiwi verde", "Fresa"], r: "Kiwi verde" },
      { tipo: "texto", q: "¿Por qué la primera tabla da los datos por 100 g y también por naranja? ¿Para qué sirve cada columna?", r: "Por 100 g sirve para comparar alimentos entre sí; por naranja, para saber lo que tomamos de verdad al comer una pieza.", lineas: 2 },
      { tipo: "opinion", q: "¿Prefieres la naranja entera o en zumo? Después de leer el texto, ¿cambiarías algo? ¿Por qué?", r: "Respuesta libre. Valorar que use la información sobre la fibra.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante que las cifras de una tabla nutricional sean exactas y de una fuente fiable?", r: "Respuesta libre. Valorar que piense en la salud de las personas y en la confianza en la información.", lineas: 2 },
    ],
  },
  // 7 ─────────────────────────────────────────────
  {
    id: "discontinuo-07-formulario-campamento",
    titulo: "Inscripción al campamento",
    subtipo: "Formulario",
    curso: "5º-6º",
    fuente: "Texto original. Campamento y formulario inventados para esta ficha.",
    antes: "¿Has rellenado alguna vez un formulario? ¿Qué datos te pedían?",
    texto: [
      { h: "Campamento de verano «Sierra Verde» · Hoja de inscripción" },
      { p: "Daniela tiene 11 años y está deseando pasar una semana en la naturaleza con chicos y chicas de su edad. Esta mañana ha rellenado la hoja de inscripción a toda prisa, antes de ir al colegio. ¿Lo habrá hecho bien?" },
      { lista: [
        "Escribe con letras MAYÚSCULAS.",
        "Los campos marcados con asterisco (*) son obligatorios.",
        "Entrega la hoja antes del 15 de mayo.",
        "Hermanos: 20 € de descuento en la inscripción del segundo hermano.",
      ], titulo: "Instrucciones" },
      { tabla: { titulo: "Datos del participante (hoja rellenada por Daniela)", cab: ["Campo", "Respuesta"], filas: [
        ["Nombre y apellidos *", "Daniela Ruiz Ortega"],
        ["Fecha de nacimiento *", "14/03/2015"],
        ["Turno elegido *", "Turno 2"],
        ["Alergias o intolerancias *", "Frutos secos"],
        ["¿Sabe nadar? *", "Sí"],
        ["Teléfono de la familia *", "(en blanco)"],
        ["Firma del padre, madre o tutor *", "(en blanco)"],
      ] } },
      { tabla: { titulo: "Turnos y precios", cab: ["Turno", "Fechas", "Edades", "Precio"], filas: [
        ["Turno 1", "1 al 7 de julio", "8 a 10 años", "180 €"],
        ["Turno 2", "8 al 14 de julio", "11 a 13 años", "195 €"],
        ["Turno 3", "15 al 21 de julio", "14 a 16 años", "210 €"],
      ] } },
      { dato: "Actividades: senderismo, piragüismo en el embalse, talleres de naturaleza y observación de estrellas." },
    ],
    vocabulario: [
      { p: "formulario", d: "Documento con espacios en blanco para escribir unos datos determinados." },
      { p: "campo", d: "En un formulario, cada espacio donde se escribe un dato." },
      { p: "obligatorio", d: "Que hay que hacer sin falta." },
      { p: "tutor", d: "Persona adulta que se encarga legalmente de un menor." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Daniela tiene 11 años. ¿Por qué no podría haber elegido el turno 1? ¿Qué otro turno podría elegir?", r: "Porque el turno 1 es para 8 a 10 años. No podría elegir otro: el turno 3 es de 14 a 16 años, así que solo le vale el 2.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué campos obligatorios ha dejado sin rellenar Daniela?", r: "El teléfono de la familia y la firma del padre, madre o tutor.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué instrucción no ha cumplido al escribir su nombre?", r: "No lo ha escrito en mayúsculas.", lineas: 1 },
      { tipo: "comprension", q: "Hugo, el hermano de Daniela, tiene 9 años y también va al campamento. ¿Cuánto pagará la familia en total?", r: "355 €: 195 € (turno 2) + 180 € (turno 1) − 20 € de descuento.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el formulario pregunta si sabe nadar? Elige:", opciones: ["Para organizar un concurso de natación", "Porque hay piragüismo en el embalse y deben cuidar su seguridad", "Porque es obligatorio saber nadar para ir"], r: "Porque hay piragüismo en el embalse y deben cuidar su seguridad" },
      { tipo: "texto", q: "¿En qué se diferencia un formulario de otros textos discontinuos, como un horario? ¿Quién lo completa?", r: "El formulario no solo se lee: tiene campos vacíos que debe rellenar la persona interesada con sus datos.", lineas: 2 },
      { tipo: "opinion", q: "¿Por qué crees que es importante escribir las alergias en un formulario así? ¿Qué podría pasar si no se hiciera?", r: "Respuesta libre. Valorar que relacione el dato con la seguridad en las comidas.", lineas: 3 },
      { tipo: "opinion", q: "¿Te gustaría ir a un campamento como este? ¿Qué actividad te apetecería más y por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "En internet también nos piden datos personales. ¿Qué datos no deberías escribir nunca en un formulario sin preguntar antes a un adulto? ¿Por qué?", r: "Respuesta libre. Valorar la prudencia: dirección, teléfono, fotos, contraseñas…", lineas: 3 },
    ],
  },
  // 8 ─────────────────────────────────────────────
  {
    id: "discontinuo-08-museo-ciencia",
    titulo: "Un día en el museo",
    subtipo: "Horarios y tarifas",
    curso: "5º-6º",
    fuente: "Texto original. Museo inventado para esta ficha.",
    antes: "¿Qué museo has visitado? ¿Recuerdas cuánto costó la entrada o a qué hora abría?",
    texto: [
      { h: "Museo de la Ciencia y el Juego · Información para visitantes" },
      { p: "En este museo está prohibido no tocar: se puede experimentar con imanes, espejos, sonidos y engranajes. Antes de venir, consulta el horario y elige la entrada que más te convenga." },
      { tabla: { titulo: "Horario", cab: ["Temporada", "Martes a sábado", "Domingos y festivos", "Lunes"], filas: [
        ["Invierno (septiembre a junio)", "10:00 a 14:00 y 17:00 a 20:00", "10:00 a 15:00", "Cerrado"],
        ["Verano (julio y agosto)", "9:00 a 15:00", "9:00 a 14:00", "Cerrado"],
      ] } },
      { tabla: { titulo: "Precios", cab: ["Tipo de entrada", "Precio"], filas: [
        ["General", "8 €"],
        ["Reducida (estudiantes y mayores de 65 años)", "5 €"],
        ["Niños de 6 a 12 años", "3 €"],
        ["Menores de 6 años", "Gratis"],
        ["Familiar (2 adultos y hasta 3 niños)", "20 €"],
        ["Suplemento planetario (por persona)", "2 €"],
      ] } },
      { lista: [
        "La taquilla cierra 45 minutos antes que el museo.",
        "Sesiones del planetario: 11:00, 12:30 y 18:00 (esta última, solo en invierno).",
        "Entrada gratuita el 18 de mayo, Día Internacional de los Museos.",
      ], titulo: "Tenga en cuenta" },
      { dato: "¡Novedad! Sala de ilusiones ópticas: descubre por qué tus ojos a veces te engañan." },
    ],
    vocabulario: [
      { p: "tarifa", d: "Lista de precios de un servicio." },
      { p: "taquilla", d: "Lugar donde se venden las entradas." },
      { p: "suplemento", d: "Cantidad que se paga de más por un servicio extra." },
      { p: "planetario", d: "Sala con una cúpula donde se proyectan el cielo y las estrellas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Una familia de dos adultos y dos niños de 8 y 11 años va al museo. ¿Cuánto pagarían con entradas sueltas? ¿Y con la familiar? ¿Cuánto ahorran?", r: "Sueltas: 8 + 8 + 3 + 3 = 22 €. Familiar: 20 €. Ahorran 2 €.", lineas: 2 },
      { tipo: "comprension", q: "¿Se puede visitar el museo un lunes de agosto? ¿Por qué?", r: "No, porque los lunes está cerrado todo el año.", lineas: 1 },
      { tipo: "comprension", q: "Irene llega un sábado de octubre a las 15:30. ¿Podrá entrar? ¿A qué hora debería volver?", r: "No, porque en invierno cierra de 14:00 a 17:00. Debe volver a partir de las 17:00 (y antes de las 19:15, cuando cierra la taquilla).", lineas: 2 },
      { tipo: "comprension", q: "Un abuelo de 70 años quiere visitar el museo. ¿Cuánto paga? Elige:", opciones: ["8 €", "5 €", "Nada"], r: "5 €" },
      { tipo: "comprension", q: "Nerea, de 10 años, va con su madre y las dos quieren ver el planetario. ¿Cuánto pagan en total?", r: "15 €: 3 € (Nerea) + 8 € (madre) + 2 € + 2 € de planetario.", lineas: 1 },
      { tipo: "texto", q: "Para saber si el museo está abierto, ¿qué dos datos de la tabla de horario hay que cruzar? Pon un ejemplo.", r: "La temporada (fila) y el día de la semana (columna). Ejemplo: verano y domingo → de 9:00 a 14:00.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece justo que las personas mayores y los estudiantes paguen menos? ¿Por qué?", r: "Respuesta libre. Valorar que argumente pensando en la igualdad de acceso a la cultura.", lineas: 3 },
      { tipo: "opinion", q: "Si pudieras diseñar una sala nueva para este museo, ¿de qué sería? ¿Por qué atraería a chicos y chicas de tu edad?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué crees que existe un Día Internacional de los Museos con entrada gratuita? ¿Qué se consigue con ello?", r: "Respuesta libre. Valorar que relacione la gratuidad con acercar la cultura a más personas.", lineas: 2 },
    ],
  },
  // 9 ─────────────────────────────────────────────
  {
    id: "discontinuo-09-cabo-de-gata",
    titulo: "Cabo de Gata: volcanes junto al mar",
    subtipo: "Folleto turístico",
    curso: "6º",
    fuente: "Texto original con datos reales del parque.",
    datos: ["Junta de Andalucía, Ventana del Visitante: Parque Natural Cabo de Gata-Níjar", "UNESCO: Reserva de la Biosfera y Geoparque Mundial Cabo de Gata-Níjar", "AEMET: valores climatológicos normales 1981-2010, Almería Aeropuerto"],
    antes: "¿Has estado en algún parque natural? ¿Qué normas había que cumplir allí?",
    texto: [
      { h: "Parque Natural Cabo de Gata-Níjar (Almería)" },
      { p: "Acantilados negros, calas de agua transparente y montañas nacidas de antiguos volcanes. Cabo de Gata es uno de los paisajes más secos de Europa: en el cercano aeropuerto de Almería caen de media unos 200 litros de lluvia por metro cuadrado al año." },
      { tabla: { titulo: "El parque en cifras", cab: ["Dato", "Valor"], filas: [
        ["Declarado parque natural", "1987"],
        ["Superficie terrestre", "unos 38.000 hectáreas"],
        ["Superficie marina", "unos 12.000 hectáreas"],
        ["Costa", "más de 60 km"],
        ["Reserva de la Biosfera (UNESCO)", "desde 1997"],
        ["Geoparque Mundial (UNESCO)", "Sí"],
      ] } },
      { lista: [
        "Salinas de Cabo de Gata: observatorio de aves, con flamencos.",
        "Faro de Cabo de Gata y arrecife de las Sirenas.",
        "Playas de los Genoveses y de Mónsul.",
        "Fondos marinos con praderas de posidonia (para bucear con gafas y tubo).",
      ], titulo: "Qué ver" },
      { lista: [
        "No arranques plantas ni te lleves piedras.",
        "Lleva tu basura de vuelta.",
        "Respeta las señales y los caminos marcados.",
        "No se permite la acampada libre.",
      ], titulo: "Normas del visitante" },
    ],
    vocabulario: [
      { p: "hectárea", d: "Medida de superficie: un cuadrado de 100 metros de lado." },
      { p: "cala", d: "Playa pequeña y resguardada entre rocas." },
      { p: "posidonia", d: "Planta marina del Mediterráneo que forma praderas bajo el agua." },
      { p: "geoparque", d: "Territorio protegido por el gran valor de sus rocas y su paisaje." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Sumando la parte terrestre y la marina, ¿qué superficie aproximada tiene el parque?", r: "Unas 50.000 hectáreas (38.000 + 12.000).", lineas: 1 },
      { tipo: "comprension", q: "¿Cuántos años pasaron desde que se declaró parque natural hasta que fue Reserva de la Biosfera?", r: "10 años (de 1987 a 1997).", lineas: 1 },
      { tipo: "comprension", q: "¿Qué origen tiene el relieve de Cabo de Gata? Elige:", opciones: ["Glaciar", "Volcánico", "Formado por un río"], r: "Volcánico" },
      { tipo: "comprension", q: "Una familia quiere ver flamencos. ¿A qué lugar del parque debe ir? ¿En qué apartado del folleto lo has encontrado?", r: "A las salinas de Cabo de Gata. Está en el apartado «Qué ver».", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el folleto pide no llevarse piedras, si en el parque hay muchísimas?", r: "Porque las rocas volcánicas son lo que se protege (es un geoparque); si cada visitante se llevara una, el paisaje se estropearía.", lineas: 2 },
      { tipo: "texto", q: "Este folleto mezcla un párrafo, una tabla y dos listas. ¿Qué tipo de información va en cada parte? ¿Por qué es útil para un turista?", r: "El párrafo presenta y describe el lugar; la tabla da las cifras; las listas indican qué visitar y qué normas cumplir. Así el turista encuentra rápido lo que necesita.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué lugar del folleto te gustaría visitar primero? Explica por qué con datos del texto.", r: "Respuesta libre. Valorar que use información del folleto.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece bien que no se permita acampar libremente en el parque? Da tus razones.", r: "Respuesta libre. Valorar que piense en la conservación y el riesgo de incendios o basura.", lineas: 3 },
      { tipo: "reflexion", q: "Muchos visitantes llegan al parque en verano. ¿Cómo se puede disfrutar de un lugar natural sin dañarlo? Propón dos ideas.", r: "Respuesta libre. Valorar propuestas de turismo responsable.", lineas: 3 },
    ],
  },
  // 10 ────────────────────────────────────────────
  {
    id: "discontinuo-10-clima-andalucia",
    titulo: "El clima de cinco capitales andaluzas",
    subtipo: "Tabla de datos climáticos",
    curso: "6º",
    fuente: "Texto original con datos climáticos reales.",
    datos: ["AEMET: valores climatológicos normales 1981-2010 de las estaciones de Almería, Córdoba, Granada, Málaga y Sevilla Aeropuerto"],
    antes: "¿Crees que en toda Andalucía hace el mismo calor y llueve lo mismo? ¿Por qué?",
    texto: [
      { h: "¿Frío, calor, lluvia? Depende de dónde vivas" },
      { p: "La Agencia Estatal de Meteorología (AEMET) calcula los valores medios del clima a partir de treinta años de observaciones. La tabla recoge los de cinco capitales andaluzas, medidos en las estaciones de sus aeropuertos." },
      { tabla: { titulo: "Temperaturas medias y lluvia (1981-2010)", cab: ["Capital", "Enero (°C)", "Julio (°C)", "Año (°C)", "Lluvia al año (mm)"], filas: [
        ["Almería", "12,6", "26,1", "19,1", "200"],
        ["Córdoba", "9,3", "28,0", "18,2", "605"],
        ["Granada", "6,5", "25,3", "15,4", "365"],
        ["Málaga", "12,1", "25,5", "18,5", "534"],
        ["Sevilla", "10,9", "28,2", "19,2", "539"],
      ] }, nota: "Fuente: AEMET, valores climatológicos normales 1981-2010. Un milímetro (mm) de lluvia equivale a un litro de agua por metro cuadrado." },
      { p: "El aeropuerto de Granada está a más de 500 metros de altitud, mientras que los de Almería y Málaga están junto al mar. El mar se calienta y se enfría despacio, por eso suaviza las temperaturas de la costa: inviernos más templados y veranos menos extremos." },
      { dato: "En el valle del Guadalquivir, donde están Córdoba y Sevilla, se registran algunas de las temperaturas más altas de España en verano." },
    ],
    vocabulario: [
      { p: "valor medio", d: "Resultado de repartir por igual el total de varios datos." },
      { p: "altitud", d: "Altura de un lugar sobre el nivel del mar." },
      { p: "suavizar", d: "Hacer que algo sea menos fuerte o menos extremo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué capital tiene el mes de enero más frío? ¿Con qué temperatura media?", r: "Granada, con 6,5 °C.", lineas: 1 },
      { tipo: "comprension", q: "¿Cuántos milímetros llueve al año en Córdoba más que en Almería?", r: "405 mm más (605 − 200).", lineas: 1 },
      { tipo: "comprension", q: "¿Qué capital es la más calurosa en julio? Elige:", opciones: ["Córdoba", "Sevilla", "Almería"], r: "Sevilla" },
      { tipo: "comprension", q: "Calcula la diferencia entre julio y enero en Granada y en Málaga. ¿En cuál es mayor?", r: "Granada: 25,3 − 6,5 = 18,8 °C. Málaga: 25,5 − 12,1 = 13,4 °C. Es mayor en Granada.", lineas: 2 },
      { tipo: "comprension", q: "Usa el texto para explicar por qué Málaga tiene un invierno más templado que Granada.", r: "Porque Málaga está junto al mar, que suaviza las temperaturas, y Granada está en el interior y a más de 500 metros de altitud.", lineas: 2 },
      { tipo: "texto", q: "¿Por qué es importante leer la nota que hay bajo la tabla? ¿Qué información nos da?", r: "Porque indica la fuente (AEMET), el periodo de los datos (1981-2010) y explica la unidad mm, sin la cual no entenderíamos bien la tabla.", lineas: 2 },
      { tipo: "opinion", q: "Según la tabla, ¿en qué capital te gustaría vivir? Justifica tu elección con al menos dos datos.", r: "Respuesta libre. Valorar que use datos concretos de la tabla.", lineas: 3 },
      { tipo: "opinion", q: "Almería recibe muy poca lluvia. ¿Qué consejos darías para ahorrar agua en una ciudad así? ¿Por qué?", r: "Respuesta libre. Valorar propuestas razonadas.", lineas: 3 },
      { tipo: "reflexion", q: "Estos datos son de 1981 a 2010. ¿Crees que si se midieran ahora serían iguales? ¿Qué sabes del cambio climático que te ayude a responder?", r: "Respuesta libre. Valorar que relacione los datos con el aumento de las temperaturas.", lineas: 3 },
    ],
  },
];
