// Lecturas · Textos discontinuos (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["discontinuo"] = [
  // 1 ─────────────────────────────────────────────
  {
    id: "discontinuo-01-autobus-cazorla",
    titulo: "El autobús de la sierra",
    subtipo: "Horario de autobuses",
    curso: "5º",
    fuente: "Texto original. Horario inventado para esta ficha (las localidades son reales).",
    antes: "¿Has consultado alguna vez un horario de autobús o de tren? ¿Cómo encontraste la hora que buscabas?",
    texto: [
      { h: "Línea Cazorla – Úbeda (provincia de Jaén)" },
      { p: "Lucía vive en Peal de Becerro y los martes tiene clase de violín en Úbeda a las 11:00. Antes de salir, siempre mira el horario que hay pegado en la parada." },
      { tabla: { titulo: "IDA: Cazorla → Úbeda (lunes a viernes)", cab: ["Parada", "Bus 1", "Bus 2", "Bus 3", "Bus 4"], filas: [
        ["Cazorla", "07:15", "09:30", "13:45", "18:00"],
        ["Peal de Becerro", "07:35", "09:50", "14:05", "18:20"],
        ["Torreperogil", "07:55", "10:10", "14:25", "18:40"],
        ["Úbeda (estación)", "08:10", "10:25", "14:40", "18:55"],
      ] } },
      { tabla: { titulo: "VUELTA: Úbeda → Cazorla (lunes a viernes)", cab: ["Parada", "Bus 1", "Bus 2", "Bus 3", "Bus 4"], filas: [
        ["Úbeda (estación)", "08:30", "12:00", "15:30", "20:00"],
        ["Torreperogil", "08:45", "12:15", "15:45", "20:15"],
        ["Peal de Becerro", "09:05", "12:35", "16:05", "20:35"],
        ["Cazorla", "09:25", "12:55", "16:25", "20:55"],
      ] } },
      { lista: [
        "Sábados: solo circulan los autobuses 2 y 4 de cada sentido, con el mismo horario.",
        "Domingos y festivos: no hay servicio.",
        "Billete Cazorla – Úbeda: 3,20 €. Con el bonobús joven, la mitad de precio.",
        "Llega a la parada cinco minutos antes de la hora indicada.",
      ], titulo: "Avisos importantes" },
      { dato: "Los horarios se leen cruzando una fila (la parada) con una columna (el autobús). ¡Así encuentras la hora exacta!" },
    ],
    vocabulario: [
      { p: "sentido", d: "Dirección en la que va un vehículo: de ida o de vuelta." },
      { p: "festivo", d: "Día en que no se trabaja ni hay colegio, aunque no sea domingo." },
      { p: "bonobús", d: "Tarjeta que permite viajar en autobús a un precio más barato." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuánto tarda el autobús 1 en ir de Cazorla a Úbeda?", r: "55 minutos (sale a las 07:15 y llega a las 08:10).", lineas: 1 },
      { tipo: "comprension", q: "Lucía tiene clase en Úbeda a las 11:00 y sale desde Peal de Becerro. ¿Qué autobús debe coger y a qué hora llegará?", r: "El autobús 2, que sale de Peal a las 09:50 y llega a Úbeda a las 10:25. El 3 llegaría tarde.", lineas: 2 },
      { tipo: "comprension", q: "Un sábado, Marcos quiere ir de Cazorla a Úbeda lo antes posible. ¿A qué hora puede salir? ¿Por qué no antes?", r: "A las 09:30 (autobús 2), porque los sábados solo circulan los autobuses 2 y 4; el de las 07:15 no pasa.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuánto cuesta el billete Cazorla – Úbeda con el bonobús joven? Elige:", opciones: ["3,20 €", "1,60 €", "6,40 €"], r: "1,60 €" },
      { tipo: "comprension", q: "¿Cuál es el último autobús con el que Lucía puede volver de Úbeda a Peal de Becerro? ¿A qué hora llega a casa?", r: "El autobús 4 de vuelta: sale de Úbeda a las 20:00 y llega a Peal de Becerro a las 20:35.", lineas: 2 },
      { tipo: "texto", q: "¿Por qué un horario de autobuses es un texto discontinuo? Explica cómo se encuentra en él una hora concreta.", r: "Porque la información no está en párrafos seguidos, sino organizada en una tabla. Se busca la fila de la parada y la columna del autobús, y en la casilla donde se cruzan está la hora.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es importante que los pueblos pequeños tengan autobús aunque viaje poca gente? ¿Por qué?", r: "Respuesta libre. Valorar que piense en quienes no tienen coche: niños, mayores, estudiantes.", lineas: 3 },
      { tipo: "opinion", q: "¿Prefieres consultar un horario en papel o en el móvil? Da dos razones.", r: "Respuesta libre. Valorar que argumente con ventajas e inconvenientes.", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué podría pasar si en un horario hubiera una sola hora equivocada? Piensa en las personas que lo usan cada día.", r: "Respuesta libre. Valorar que relacione la precisión de los datos con sus consecuencias (perder citas, esperar, enfadarse…).", lineas: 3 },
    ],
  },
  // 2 ─────────────────────────────────────────────
  {
    id: "discontinuo-02-menu-comedor",
    titulo: "¿Qué comemos esta semana?",
    subtipo: "Menú escolar semanal",
    curso: "5º",
    fuente: "Texto original. Menú inventado para esta ficha.",
    antes: "¿Qué plato del comedor o de casa te gusta más? ¿Y cuál te cuesta más comer?",
    texto: [
      { h: "Comedor escolar · Menú de la semana del 13 al 17 de octubre" },
      { tabla: { titulo: "Menú semanal", cab: ["Día", "Primer plato", "Segundo plato", "Postre"], filas: [
        ["Lunes", "Lentejas con verduras", "Tortilla de patatas con ensalada", "Naranja"],
        ["Martes", "Crema de calabacín", "Merluza al horno con patatas", "Yogur natural"],
        ["Miércoles", "Arroz con tomate", "Pollo asado con zanahoria", "Plátano"],
        ["Jueves", "Garbanzos con espinacas", "Filete de pavo con pimientos", "Manzana"],
        ["Viernes", "Macarrones con tomate", "Boquerones al horno con ensalada", "Natillas caseras"],
      ] } },
      { lista: [
        "Huevo: lunes (tortilla) y viernes (natillas).",
        "Pescado: martes y viernes.",
        "Leche: martes (yogur y crema) y viernes (natillas).",
        "Gluten: viernes (macarrones).",
      ], titulo: "Alérgenos del menú" },
      { p: "El alumnado con alergias recibirá un menú alternativo. Avisad en secretaría antes del jueves de la semana anterior." },
      { dato: "Consejo para la cena: si a mediodía has comido carne o huevo, cena pescado. Si has comido pescado, cena carne o huevo. ¡Y siempre verdura y fruta!" },
    ],
    vocabulario: [
      { p: "alérgeno", d: "Sustancia de un alimento que a algunas personas les produce alergia." },
      { p: "alternativo", d: "Que sustituye a otra cosa; en este caso, otro menú distinto." },
      { p: "legumbre", d: "Semilla que se cría en vainas, como las lentejas o los garbanzos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué días hay pescado de segundo plato? ¿Qué pescados son?", r: "El martes (merluza) y el viernes (boquerones).", lineas: 1 },
      { tipo: "comprension", q: "Ahmed es alérgico al huevo. ¿Qué días necesita el menú alternativo y en qué platos?", r: "El lunes (tortilla de patatas) y el viernes (natillas).", lineas: 2 },
      { tipo: "comprension", q: "¿Cuántos días hay legumbres de primer plato? Elige:", opciones: ["Uno", "Dos", "Tres"], r: "Dos" },
      { tipo: "comprension", q: "Según el consejo, ¿qué le convendría cenar a Sara el miércoles? Explica por qué.", r: "Pescado (con verdura y fruta), porque el miércoles a mediodía come pollo, que es carne.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuántos días de la semana el postre es fruta? ¿Cuáles?", r: "Tres días: lunes (naranja), miércoles (plátano) y jueves (manzana).", lineas: 1 },
      { tipo: "texto", q: "¿Qué información da la tabla y qué información da la lista? ¿Por qué crees que se separan?", r: "La tabla organiza los platos por días; la lista reúne los alérgenos. Se separan para que cada lector encuentre rápido lo que busca.", lineas: 2 },
      { tipo: "opinion", q: "Si pudieras cambiar un plato de este menú, ¿cuál sería y por cuál lo cambiarías para que siguiera siendo sano? ¿Por qué?", r: "Respuesta libre. Valorar que proponga un plato equilibrado.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece bien que el menú se publique con una semana de antelación? ¿A quién ayuda?", r: "Respuesta libre. Valorar que piense en las familias y en quienes tienen alergias.", lineas: 3 },
      { tipo: "reflexion", q: "¿Cómo te sentirías si fueras alérgico a un alimento y nadie lo tuviera en cuenta? ¿Qué puedes hacer tú para ayudar a un compañero con alergia?", r: "Respuesta libre. Valorar la empatía y propuestas concretas (no compartir comida, avisar a un adulto…).", lineas: 3 },
    ],
  },
  // 3 ─────────────────────────────────────────────
  {
    id: "discontinuo-03-centro-civico",
    titulo: "Otoño en el centro cívico",
    subtipo: "Cartelera de actividades",
    curso: "5º",
    fuente: "Texto original. Cartelera inventada para esta ficha.",
    antes: "¿Haces alguna actividad por las tardes? ¿Cómo la elegiste?",
    texto: [
      { h: "Centro Cívico Las Moreras · Actividades de octubre" },
      { p: "Este otoño, el centro cívico del barrio abre sus puertas con talleres para todas las edades. ¡Elige el tuyo!" },
      { tabla: { titulo: "Cartelera de actividades", cab: ["Actividad", "Día", "Hora", "Edad", "Precio"], filas: [
        ["Taller de robótica", "Lunes", "17:30 a 19:00", "9 a 12 años", "12 € al mes"],
        ["Ajedrez", "Martes y jueves", "18:00 a 19:00", "Desde 7 años", "Gratis"],
        ["Teatro juvenil", "Miércoles", "17:00 a 18:00", "10 a 14 años", "8 € al mes"],
        ["Cómic y dibujo", "Viernes", "17:30 a 18:30", "8 a 13 años", "10 € al mes"],
        ["Cuentacuentos en familia", "Sábado", "11:00 a 12:00", "4 a 8 años", "Gratis"],
      ] } },
      { lista: [
        "Inscripciones en la recepción del centro, del 1 al 5 de octubre, de 9:00 a 14:00.",
        "Cada taller tiene 15 plazas. Se adjudican por orden de inscripción.",
        "Los menores de 12 años deben venir acompañados por un adulto a la inscripción.",
      ], titulo: "Cómo apuntarse" },
      { dato: "Domingo 19 de octubre, a las 10:00: paseo en bici por el barrio para todas las edades. ¡Trae casco!" },
    ],
    vocabulario: [
      { p: "cartelera", d: "Lista o cartel que anuncia actividades, películas o espectáculos." },
      { p: "adjudicar", d: "Dar o asignar algo a alguien." },
      { p: "inscripción", d: "Acción de apuntarse a una actividad." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Nora tiene 11 años y los lunes sale de clase de inglés a las 18:00. ¿Puede ir al taller de robótica? ¿Por qué?", r: "No, porque el taller empieza a las 17:30, antes de que ella salga de inglés.", lineas: 2 },
      { tipo: "comprension", q: "Pablo tiene 8 años y su hermana Irene, 11. Quieren hacer juntos una actividad gratuita. ¿Cuál pueden elegir?", r: "Ajedrez, porque es gratis y es desde 7 años. El cuentacuentos es solo hasta 8 años, así que Irene no podría.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuánto pagaría al mes una persona apuntada a robótica y a teatro?", r: "20 € al mes (12 € + 8 €).", lineas: 1 },
      { tipo: "comprension", q: "¿Qué actividad tiene las sesiones más largas? Elige:", opciones: ["Teatro juvenil", "Taller de robótica", "Cómic y dibujo"], r: "Taller de robótica" },
      { tipo: "comprension", q: "Si llegas a apuntarte el 6 de octubre, ¿qué ocurrirá? ¿Y si eres el número 16 en un taller?", r: "El 6 ya no se puede, porque el plazo termina el 5. Si eres el 16, no tendrás plaza, porque solo hay 15.", lineas: 2 },
      { tipo: "texto", q: "Una cartelera mezcla una tabla, una lista y un recuadro. ¿Qué ventaja tiene presentar así la información en lugar de escribirla en párrafos?", r: "Se localiza cada dato (día, hora, edad, precio) de un vistazo, sin leer todo el texto seguido.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué actividad de la cartelera elegirías tú? Justifica tu respuesta con datos de la tabla.", r: "Respuesta libre. Valorar que use datos de la tabla (edad, horario, precio).", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que es bueno que haya actividades gratuitas en los barrios? ¿Por qué?", r: "Respuesta libre. Valorar que piense en la igualdad de oportunidades.", lineas: 3 },
      { tipo: "reflexion", q: "Imagina que diriges el centro cívico. ¿Qué actividad nueva añadirías para que participaran personas mayores y niños juntos? Explica por qué.", r: "Respuesta libre. Valorar la creatividad y la idea de convivencia entre generaciones.", lineas: 3 },
    ],
  },
  // 4 ─────────────────────────────────────────────
  {
    id: "discontinuo-04-clasificacion-liga",
    titulo: "La liga del barrio",
    subtipo: "Clasificación deportiva",
    curso: "5º",
    fuente: "Texto original. Liga y equipos inventados para esta ficha.",
    antes: "¿Sabes cómo se reparten los puntos en una liga de fútbol? ¿Qué significa ir primero en la clasificación?",
    texto: [
      { h: "Liga alevín mixta de fútbol sala · Clasificación tras la jornada 8" },
      { p: "Seis equipos de chicos y chicas de los colegios del barrio compiten cada fin de semana en el polideportivo municipal. Quedan dos jornadas y la lucha por el primer puesto está más emocionante que nunca." },
      { tabla: { titulo: "Clasificación", cab: ["Pos.", "Equipo", "PJ", "G-E-P", "Puntos"], filas: [
        ["1.º", "Los Linces", "8", "6-1-1", "19"],
        ["2.º", "Atlético Olivar", "8", "5-2-1", "17"],
        ["3.º", "Las Gaviotas", "8", "4-3-1", "15"],
        ["4.º", "CD Barrio Alto", "8", "3-2-3", "11"],
        ["5.º", "Rayo Veloz", "8", "1-1-6", "4"],
        ["6.º", "Club Tortugas", "8", "0-1-7", "1"],
      ] }, nota: "PJ: partidos jugados. G: ganados. E: empatados. P: perdidos." },
      { lista: [
        "Victoria: 3 puntos.",
        "Empate: 1 punto.",
        "Derrota: 0 puntos.",
      ], titulo: "Reparto de puntos" },
      { lista: [
        "Los Linces – Atlético Olivar (sábado, 10:00).",
        "Las Gaviotas – Club Tortugas (sábado, 11:30).",
        "CD Barrio Alto – Rayo Veloz (domingo, 10:00).",
      ], titulo: "Próxima jornada (jornada 9)" },
      { dato: "El Club Tortugas ha recibido el premio al juego limpio del primer trimestre: ¡ninguna tarjeta en ocho partidos!" },
    ],
    vocabulario: [
      { p: "jornada", d: "Conjunto de partidos que se juegan en las mismas fechas de una liga." },
      { p: "alevín", d: "Categoría deportiva para niños y niñas de unos 10 a 12 años." },
      { p: "juego limpio", d: "Forma de jugar respetando las reglas, al rival y al árbitro." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántos puntos de diferencia hay entre el primero y el segundo clasificado?", r: "2 puntos (19 − 17).", lineas: 1 },
      { tipo: "comprension", q: "Explica, con los datos de la tabla, cómo ha conseguido Las Gaviotas sus 15 puntos.", r: "Ha ganado 4 partidos (4 × 3 = 12) y ha empatado 3 (3 × 1 = 3): 12 + 3 = 15.", lineas: 2 },
      { tipo: "comprension", q: "Si el Atlético Olivar gana a Los Linces en la jornada 9, ¿quién irá primero? ¿Con cuántos puntos?", r: "El Atlético Olivar, con 20 puntos; Los Linces se quedarían con 19.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuántos partidos ha empatado el CD Barrio Alto? Elige:", opciones: ["Tres", "Dos", "Ocho"], r: "Dos" },
      { tipo: "comprension", q: "¿Por qué crees que el Club Tortugas ha recibido un premio aunque va el último?", r: "Porque el premio no es por ganar, sino por jugar limpio: no ha tenido ninguna tarjeta.", lineas: 2 },
      { tipo: "texto", q: "La tabla usa abreviaturas como PJ o G-E-P. ¿Dónde se explican y por qué es necesario leer esa nota?", r: "En la nota que hay debajo de la tabla (la leyenda). Sin ella no sabríamos qué significa cada abreviatura.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué es más importante para ti en un equipo: ganar o jugar limpio? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece buena idea que las ligas infantiles sean mixtas? Razona tu respuesta.", r: "Respuesta libre. Valorar argumentos basados en la igualdad y el compañerismo.", lineas: 3 },
      { tipo: "reflexion", q: "Imagina que juegas en el Club Tortugas. ¿Qué le dirías a tu equipo para seguir con ganas después de tantas derrotas?", r: "Respuesta libre. Valorar mensajes de ánimo, esfuerzo y aprendizaje.", lineas: 3 },
    ],
  },
  // 5 ─────────────────────────────────────────────
  {
    id: "discontinuo-05-reciclaje",
    titulo: "Cada residuo a su contenedor",
    subtipo: "Infografía",
    curso: "5º",
    fuente: "Texto original basado en las normas habituales de separación de residuos en España.",
    antes: "¿Separáis la basura en casa? ¿Cuántos cubos o bolsas usáis?",
    texto: [
      { h: "Guía rápida para reciclar en casa" },
      { p: "Separar los residuos en casa es el primer paso para que puedan convertirse en objetos nuevos. Busca en la tabla el color del contenedor y comprueba qué puedes echar en él y qué no." },
      { tabla: { titulo: "¿Qué va en cada contenedor?", cab: ["Contenedor", "Qué SÍ va", "Qué NO va"], filas: [
        ["Amarillo", "Envases de plástico, latas, briks, tapas metálicas, papel de aluminio", "Juguetes, cubos, biberones y otros objetos de plástico que no son envases"],
        ["Azul", "Papel y cartón: periódicos, cajas, folios, cuadernos", "Pañuelos y servilletas usados, papel de cocina sucio"],
        ["Verde", "Botellas y tarros de vidrio, sin tapa", "Vasos y copas de cristal, platos, espejos, bombillas"],
        ["Marrón (orgánico)", "Restos de comida, cáscaras, posos de café, servilletas de papel usadas", "Pañales, colillas, envases"],
        ["Gris (resto)", "Lo que no va en los demás: pañales, colillas, polvo de barrer", "Cualquier residuo que se pueda reciclar"],
      ] }, nota: "Las normas pueden cambiar un poco según el ayuntamiento." },
      { lista: [
        "Pilas: contenedor especial de pilas (en tiendas y edificios públicos).",
        "Medicamentos: punto de recogida de la farmacia.",
        "Aceite usado y aparatos eléctricos: punto limpio.",
        "Ropa y zapatos en buen estado: contenedor de ropa.",
      ], titulo: "Otros residuos" },
      { dato: "El cristal de los vasos y las copas no es igual que el vidrio de los envases: funde a otra temperatura y estropea el vidrio reciclado." },
    ],
    vocabulario: [
      { p: "residuo", d: "Lo que queda de algo después de usarlo y se tira." },
      { p: "brik", d: "Envase de cartón forrado por dentro, como los de leche o zumo." },
      { p: "punto limpio", d: "Lugar del municipio donde se llevan los residuos especiales." },
      { p: "orgánico", d: "Que procede de seres vivos, como los restos de comida." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿A qué contenedor va un brik de zumo vacío?", r: "Al amarillo.", lineas: 1 },
      { tipo: "comprension", q: "Tienes un tarro de mermelada vacío con su tapa metálica. ¿Qué haces con cada parte?", r: "El tarro, al verde (sin tapa); la tapa metálica, al amarillo.", lineas: 2 },
      { tipo: "comprension", q: "Se te ha roto un vaso de cristal. ¿Puedes tirarlo al contenedor verde? Explica por qué con datos del texto.", r: "No. La tabla lo pone en «Qué NO va» del verde, porque el cristal funde a otra temperatura y estropea el vidrio reciclado.", lineas: 2 },
      { tipo: "comprension", q: "¿Dónde se llevan los medicamentos que ya no se usan? Elige:", opciones: ["Al contenedor gris", "A la farmacia", "Al contenedor amarillo"], r: "A la farmacia" },
      { tipo: "comprension", q: "Al vaciar una caja de cereales quedan la caja de cartón y la bolsa de plástico de dentro. ¿A qué contenedor va cada una?", r: "La caja, al azul; la bolsa de plástico, al amarillo, porque es un envase.", lineas: 2 },
      { tipo: "texto", q: "Una infografía combina textos breves y datos organizados. ¿Por qué esta guía usa una tabla con columnas de «SÍ» y «NO» en vez de un texto largo?", r: "Porque así se encuentra enseguida el contenedor y se comparan los residuos que van y no van; es más rápido de consultar.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que en tu casa se recicla bien? ¿Qué cambiarías después de leer esta guía?", r: "Respuesta libre. Valorar propuestas concretas.", lineas: 3 },
      { tipo: "opinion", q: "Algunas personas dicen que separar la basura da mucho trabajo. ¿Qué les responderías?", r: "Respuesta libre. Valorar argumentos sobre el medio ambiente y los hábitos.", lineas: 3 },
      { tipo: "reflexion", q: "Además de reciclar, ¿qué podríamos hacer para producir menos basura? Pon dos ejemplos de tu vida diaria.", r: "Respuesta libre. Valorar ideas de reducir y reutilizar (botella rellenable, fiambrera, comprar a granel…).", lineas: 3 },
    ],
  },
  // 6 ─────────────────────────────────────────────
  {
    id: "discontinuo-06-tabla-naranja",
    titulo: "Lo que esconde una naranja",
    subtipo: "Tabla de información nutricional",
    curso: "5º-6º",
    fuente: "Texto original con datos nutricionales reales (valores redondeados).",
    datos: ["USDA FoodData Central: «Oranges, raw, all commercial varieties» (FDC 169097)", "Valor de referencia de nutrientes de la Unión Europea (vitamina C: 80 mg/día)"],
    antes: "¿Has leído alguna vez la etiqueta de un alimento? ¿Qué información crees que aparece en ella?",
    texto: [
      { h: "Información nutricional: naranja cruda" },
      { p: "Andalucía es una de las principales zonas productoras de naranjas de España. Pero ¿qué nos aporta esta fruta? La tabla lo muestra para 100 gramos y para una naranja mediana, que pesa unos 150 gramos sin cáscara." },
      { tabla: { titulo: "Composición de la naranja", cab: ["Nutriente", "Por 100 g", "Por naranja (150 g)"], filas: [
        ["Energía", "47 kcal", "71 kcal"],
        ["Hidratos de carbono", "11,8 g", "17,7 g"],
        ["… de los cuales azúcares", "9,4 g", "14,1 g"],
        ["Fibra", "2,4 g", "3,6 g"],
        ["Proteínas", "0,9 g", "1,4 g"],
        ["Grasas", "0,1 g", "0,2 g"],
        ["Vitamina C", "53 mg", "80 mg"],
      ] }, nota: "Fuente: USDA FoodData Central. Valores redondeados." },
      { dato: "La cantidad diaria de vitamina C de referencia para una persona adulta en la Unión Europea es de 80 mg." },
      { p: "Los azúcares de la naranja son naturales y vienen acompañados de fibra, que ayuda a la digestión. Por eso es mejor comer la fruta entera que tomar solo el zumo." },
    ],
    vocabulario: [
      { p: "nutriente", d: "Sustancia de los alimentos que el cuerpo necesita para vivir y crecer." },
      { p: "kcal", d: "Kilocaloría: unidad que mide la energía que aporta un alimento." },
      { p: "fibra", d: "Parte de los vegetales que no se digiere y ayuda al intestino." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántos gramos de azúcares tiene una naranja mediana de 150 g?", r: "14,1 g.", lineas: 1 },
      { tipo: "comprension", q: "¿Cuántas kilocalorías más aporta una naranja mediana que 100 g de naranja?", r: "24 kcal más (71 − 47).", lineas: 1 },
      { tipo: "comprension", q: "¿Una naranja mediana cubre la vitamina C diaria de referencia para un adulto? Justifícalo con los datos.", r: "Sí: una naranja de 150 g aporta unos 80 mg, justo la cantidad de referencia (80 mg).", lineas: 2 },
      { tipo: "comprension", q: "¿De qué nutriente tiene menos cantidad la naranja? Elige:", opciones: ["Proteínas", "Grasas", "Fibra"], r: "Grasas" },
      { tipo: "comprension", q: "Si te comes dos naranjas medianas, ¿cuánta fibra tomas? ¿Por qué el texto dice que es mejor la fruta entera que el zumo?", r: "7,2 g de fibra (3,6 × 2). Porque la fruta entera conserva la fibra, que acompaña a los azúcares y ayuda a la digestión.", lineas: 2 },
      { tipo: "texto", q: "La tabla tiene tres columnas. ¿Por qué crees que da los datos por 100 g y también por una naranja? ¿Para qué sirve cada columna?", r: "Por 100 g sirve para comparar alimentos entre sí; por naranja, para saber lo que tomamos de verdad al comer una pieza.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es útil leer las etiquetas de los alimentos antes de comprarlos? ¿Por qué?", r: "Respuesta libre. Valorar que relacione la información con la salud.", lineas: 3 },
      { tipo: "opinion", q: "¿Prefieres la naranja entera o en zumo? Después de leer el texto, ¿cambiarías algo? Explícalo.", r: "Respuesta libre. Valorar que use la información sobre la fibra.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante que las cifras de una tabla nutricional sean exactas y vengan de una fuente fiable?", r: "Respuesta libre. Valorar que piense en la salud de las personas y en la confianza en la información.", lineas: 2 },
    ],
  },
  // 7 ─────────────────────────────────────────────
  {
    id: "discontinuo-07-formulario-campamento",
    titulo: "Inscripción al campamento",
    subtipo: "Formulario",
    curso: "5º-6º",
    fuente: "Texto original. Campamento y formulario inventados para esta ficha.",
    antes: "¿Has rellenado alguna vez un formulario? ¿Qué datos te pedían?",
    texto: [
      { h: "Campamento de verano «Sierra Verde» · Hoja de inscripción" },
      { p: "Daniela tiene 11 años y está deseando pasar una semana en la naturaleza con chicos y chicas de su edad. Esta mañana ha rellenado la hoja de inscripción a toda prisa, antes de ir al colegio. ¿Lo habrá hecho bien?" },
      { lista: [
        "Escribe con letras MAYÚSCULAS.",
        "Los campos marcados con asterisco (*) son obligatorios.",
        "Entrega la hoja antes del 15 de mayo.",
        "Hermanos: 20 € de descuento en la inscripción del segundo hermano.",
      ], titulo: "Instrucciones" },
      { tabla: { titulo: "Datos del participante (hoja rellenada por Daniela)", cab: ["Campo", "Respuesta"], filas: [
        ["Nombre y apellidos *", "Daniela Ruiz Ortega"],
        ["Fecha de nacimiento *", "14/03/2015"],
        ["Turno elegido *", "Turno 2"],
        ["Alergias o intolerancias *", "Frutos secos"],
        ["¿Sabe nadar? *", "Sí"],
        ["Teléfono de la familia *", "(en blanco)"],
        ["Firma del padre, madre o tutor *", "(en blanco)"],
      ] } },
      { tabla: { titulo: "Turnos y precios", cab: ["Turno", "Fechas", "Edades", "Precio"], filas: [
        ["Turno 1", "1 al 7 de julio", "8 a 10 años", "180 €"],
        ["Turno 2", "8 al 14 de julio", "11 a 13 años", "195 €"],
        ["Turno 3", "15 al 21 de julio", "14 a 16 años", "210 €"],
      ] } },
      { dato: "Actividades: senderismo, piragüismo en el embalse, talleres de naturaleza y observación de estrellas." },
    ],
    vocabulario: [
      { p: "formulario", d: "Documento con espacios en blanco para escribir unos datos determinados." },
      { p: "campo", d: "En un formulario, cada espacio donde se escribe un dato." },
      { p: "obligatorio", d: "Que hay que hacer sin falta." },
      { p: "tutor", d: "Persona adulta que se encarga legalmente de un menor." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Daniela tiene 11 años. ¿Por qué no podría haber elegido el turno 1? ¿Qué otro turno podría elegir?", r: "Porque el turno 1 es para 8 a 10 años. No podría elegir otro: el turno 3 es de 14 a 16 años, así que solo le vale el 2.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué campos obligatorios ha dejado sin rellenar Daniela?", r: "El teléfono de la familia y la firma del padre, madre o tutor.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué instrucción no ha cumplido al escribir su nombre?", r: "No lo ha escrito en mayúsculas.", lineas: 1 },
      { tipo: "comprension", q: "Hugo, el hermano de Daniela, tiene 9 años y también va al campamento. ¿Cuánto pagará la familia en total?", r: "355 €: 195 € (turno 2) + 180 € (turno 1) − 20 € de descuento.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el formulario pregunta si sabe nadar? Elige:", opciones: ["Para organizar un concurso de natación", "Porque hay piragüismo en el embalse y deben cuidar su seguridad", "Porque es obligatorio saber nadar para ir"], r: "Porque hay piragüismo en el embalse y deben cuidar su seguridad" },
      { tipo: "texto", q: "¿En qué se diferencia un formulario de otros textos discontinuos, como un horario? ¿Quién lo completa?", r: "El formulario no solo se lee: tiene campos vacíos que debe rellenar la persona interesada con sus datos.", lineas: 2 },
      { tipo: "opinion", q: "¿Por qué crees que es importante escribir las alergias en un formulario así? ¿Qué podría pasar si no se hiciera?", r: "Respuesta libre. Valorar que relacione el dato con la seguridad en las comidas.", lineas: 3 },
      { tipo: "opinion", q: "¿Te gustaría ir a un campamento como este? ¿Qué actividad te apetecería más y por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "En internet también nos piden datos personales. ¿Qué datos no deberías escribir nunca en un formulario sin preguntar antes a un adulto? ¿Por qué?", r: "Respuesta libre. Valorar la prudencia: dirección, teléfono, fotos, contraseñas…", lineas: 3 },
    ],
  },
  // 8 ─────────────────────────────────────────────
  {
    id: "discontinuo-08-museo-ciencia",
    titulo: "Un día en el museo",
    subtipo: "Horarios y tarifas",
    curso: "5º-6º",
    fuente: "Texto original. Museo inventado para esta ficha.",
    antes: "¿Qué museo has visitado? ¿Recuerdas cuánto costó la entrada o a qué hora abría?",
    texto: [
      { h: "Museo de la Ciencia y el Juego · Información para visitantes" },
      { p: "En este museo está prohibido no tocar: se puede experimentar con imanes, espejos, sonidos y engranajes. Antes de venir, consulta el horario y elige la entrada que más te convenga." },
      { tabla: { titulo: "Horario", cab: ["Temporada", "Martes a sábado", "Domingos y festivos", "Lunes"], filas: [
        ["Invierno (septiembre a junio)", "10:00 a 14:00 y 17:00 a 20:00", "10:00 a 15:00", "Cerrado"],
        ["Verano (julio y agosto)", "9:00 a 15:00", "9:00 a 14:00", "Cerrado"],
      ] } },
      { tabla: { titulo: "Precios", cab: ["Tipo de entrada", "Precio"], filas: [
        ["General", "8 €"],
        ["Reducida (estudiantes y mayores de 65 años)", "5 €"],
        ["Niños de 6 a 12 años", "3 €"],
        ["Menores de 6 años", "Gratis"],
        ["Familiar (2 adultos y hasta 3 niños)", "20 €"],
        ["Suplemento planetario (por persona)", "2 €"],
      ] } },
      { lista: [
        "La taquilla cierra 45 minutos antes que el museo.",
        "Sesiones del planetario: 11:00, 12:30 y 18:00 (esta última, solo en invierno).",
        "Entrada gratuita el 18 de mayo, Día Internacional de los Museos.",
      ], titulo: "Tenga en cuenta" },
      { dato: "¡Novedad! Sala de ilusiones ópticas: descubre por qué tus ojos a veces te engañan." },
    ],
    vocabulario: [
      { p: "tarifa", d: "Lista de precios de un servicio." },
      { p: "taquilla", d: "Lugar donde se venden las entradas." },
      { p: "suplemento", d: "Cantidad que se paga de más por un servicio extra." },
      { p: "planetario", d: "Sala con una cúpula donde se proyectan el cielo y las estrellas." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Una familia de dos adultos y dos niños de 8 y 11 años va al museo. ¿Cuánto pagarían con entradas sueltas? ¿Y con la familiar? ¿Cuánto ahorran?", r: "Sueltas: 8 + 8 + 3 + 3 = 22 €. Familiar: 20 €. Ahorran 2 €.", lineas: 2 },
      { tipo: "comprension", q: "¿Se puede visitar el museo un lunes de agosto? ¿Por qué?", r: "No, porque los lunes está cerrado todo el año.", lineas: 1 },
      { tipo: "comprension", q: "Irene llega un sábado de octubre a las 15:30. ¿Podrá entrar? ¿A qué hora debería volver?", r: "No, porque en invierno cierra de 14:00 a 17:00. Debe volver a partir de las 17:00 (y antes de las 19:15, cuando cierra la taquilla).", lineas: 2 },
      { tipo: "comprension", q: "Un abuelo de 70 años quiere visitar el museo. ¿Cuánto paga? Elige:", opciones: ["8 €", "5 €", "Nada"], r: "5 €" },
      { tipo: "comprension", q: "Nerea, de 10 años, va con su madre y las dos quieren ver el planetario. ¿Cuánto pagan en total?", r: "15 €: 3 € (Nerea) + 8 € (madre) + 2 € + 2 € de planetario.", lineas: 1 },
      { tipo: "texto", q: "Para saber si el museo está abierto, ¿qué dos datos de la tabla de horario hay que cruzar? Pon un ejemplo.", r: "La temporada (fila) y el día de la semana (columna). Ejemplo: verano y domingo → de 9:00 a 14:00.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece justo que las personas mayores y los estudiantes paguen menos? ¿Por qué?", r: "Respuesta libre. Valorar que argumente pensando en la igualdad de acceso a la cultura.", lineas: 3 },
      { tipo: "opinion", q: "Si pudieras diseñar una sala nueva para este museo, ¿de qué sería? ¿Por qué atraería a chicos y chicas de tu edad?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué crees que existe un Día Internacional de los Museos con entrada gratuita? ¿Qué se consigue con ello?", r: "Respuesta libre. Valorar que relacione la gratuidad con acercar la cultura a más personas.", lineas: 2 },
    ],
  },
  // 9 ─────────────────────────────────────────────
  {
    id: "discontinuo-09-cabo-de-gata",
    titulo: "Cabo de Gata: volcanes junto al mar",
    subtipo: "Folleto turístico",
    curso: "6º",
    fuente: "Texto original con datos reales del parque.",
    datos: ["Junta de Andalucía, Ventana del Visitante: Parque Natural Cabo de Gata-Níjar", "UNESCO: Reserva de la Biosfera y Geoparque Mundial Cabo de Gata-Níjar", "AEMET: valores climatológicos normales 1981-2010, Almería Aeropuerto"],
    antes: "¿Has estado en algún parque natural? ¿Qué normas había que cumplir allí?",
    texto: [
      { h: "Parque Natural Cabo de Gata-Níjar (Almería)" },
      { p: "Acantilados negros, calas de agua transparente y montañas nacidas de antiguos volcanes. Cabo de Gata es uno de los paisajes más secos de Europa: en el cercano aeropuerto de Almería caen de media unos 200 litros de lluvia por metro cuadrado al año." },
      { tabla: { titulo: "El parque en cifras", cab: ["Dato", "Valor"], filas: [
        ["Declarado parque natural", "1987"],
        ["Superficie terrestre", "unos 38.000 hectáreas"],
        ["Superficie marina", "unos 12.000 hectáreas"],
        ["Costa", "más de 60 km"],
        ["Reserva de la Biosfera (UNESCO)", "desde 1997"],
        ["Geoparque Mundial (UNESCO)", "Sí"],
      ] } },
      { lista: [
        "Salinas de Cabo de Gata: observatorio de aves, con flamencos.",
        "Faro de Cabo de Gata y arrecife de las Sirenas.",
        "Playas de los Genoveses y de Mónsul.",
        "Fondos marinos con praderas de posidonia (para bucear con gafas y tubo).",
      ], titulo: "Qué ver" },
      { lista: [
        "No arranques plantas ni te lleves piedras.",
        "Lleva tu basura de vuelta.",
        "Respeta las señales y los caminos marcados.",
        "No se permite la acampada libre.",
      ], titulo: "Normas del visitante" },
    ],
    vocabulario: [
      { p: "hectárea", d: "Medida de superficie: un cuadrado de 100 metros de lado." },
      { p: "cala", d: "Playa pequeña y resguardada entre rocas." },
      { p: "posidonia", d: "Planta marina del Mediterráneo que forma praderas bajo el agua." },
      { p: "geoparque", d: "Territorio protegido por el gran valor de sus rocas y su paisaje." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Sumando la parte terrestre y la marina, ¿qué superficie aproximada tiene el parque?", r: "Unas 50.000 hectáreas (38.000 + 12.000).", lineas: 1 },
      { tipo: "comprension", q: "¿Cuántos años pasaron desde que se declaró parque natural hasta que fue Reserva de la Biosfera?", r: "10 años (de 1987 a 1997).", lineas: 1 },
      { tipo: "comprension", q: "¿Qué origen tiene el relieve de Cabo de Gata? Elige:", opciones: ["Glaciar", "Volcánico", "Formado por un río"], r: "Volcánico" },
      { tipo: "comprension", q: "Una familia quiere ver flamencos. ¿A qué lugar del parque debe ir? ¿En qué apartado del folleto lo has encontrado?", r: "A las salinas de Cabo de Gata. Está en el apartado «Qué ver».", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el folleto pide no llevarse piedras, si en el parque hay muchísimas?", r: "Porque las rocas volcánicas son lo que se protege (es un geoparque); si cada visitante se llevara una, el paisaje se estropearía.", lineas: 2 },
      { tipo: "texto", q: "Este folleto mezcla un párrafo, una tabla y dos listas. ¿Qué tipo de información va en cada parte? ¿Por qué es útil para un turista?", r: "El párrafo presenta y describe el lugar; la tabla da las cifras; las listas indican qué visitar y qué normas cumplir. Así el turista encuentra rápido lo que necesita.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué lugar del folleto te gustaría visitar primero? Explica por qué con datos del texto.", r: "Respuesta libre. Valorar que use información del folleto.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece bien que no se permita acampar libremente en el parque? Da tus razones.", r: "Respuesta libre. Valorar que piense en la conservación y el riesgo de incendios o basura.", lineas: 3 },
      { tipo: "reflexion", q: "Muchos visitantes llegan al parque en verano. ¿Cómo se puede disfrutar de un lugar natural sin dañarlo? Propón dos ideas.", r: "Respuesta libre. Valorar propuestas de turismo responsable.", lineas: 3 },
    ],
  },
  // 10 ────────────────────────────────────────────
  {
    id: "discontinuo-10-clima-andalucia",
    titulo: "El clima de cinco capitales andaluzas",
    subtipo: "Tabla de datos climáticos",
    curso: "6º",
    fuente: "Texto original con datos climáticos reales.",
    datos: ["AEMET: valores climatológicos normales 1981-2010 de las estaciones de Almería, Córdoba, Granada, Málaga y Sevilla Aeropuerto"],
    antes: "¿Crees que en toda Andalucía hace el mismo calor y llueve lo mismo? ¿Por qué?",
    texto: [
      { h: "¿Frío, calor, lluvia? Depende de dónde vivas" },
      { p: "La Agencia Estatal de Meteorología (AEMET) calcula los valores medios del clima a partir de treinta años de observaciones. La tabla recoge los de cinco capitales andaluzas, medidos en las estaciones de sus aeropuertos." },
      { tabla: { titulo: "Temperaturas medias y lluvia (1981-2010)", cab: ["Capital", "Enero (°C)", "Julio (°C)", "Año (°C)", "Lluvia al año (mm)"], filas: [
        ["Almería", "12,6", "26,1", "19,1", "200"],
        ["Córdoba", "9,3", "28,0", "18,2", "605"],
        ["Granada", "6,5", "25,3", "15,4", "365"],
        ["Málaga", "12,1", "25,5", "18,5", "534"],
        ["Sevilla", "10,9", "28,2", "19,2", "539"],
      ] }, nota: "Fuente: AEMET, valores climatológicos normales 1981-2010. Un milímetro (mm) de lluvia equivale a un litro de agua por metro cuadrado." },
      { p: "El aeropuerto de Granada está a más de 500 metros de altitud, mientras que los de Almería y Málaga están junto al mar. El mar se calienta y se enfría despacio, por eso suaviza las temperaturas de la costa: inviernos más templados y veranos menos extremos." },
      { dato: "En el valle del Guadalquivir, donde están Córdoba y Sevilla, se registran algunas de las temperaturas más altas de España en verano." },
    ],
    vocabulario: [
      { p: "valor medio", d: "Resultado de repartir por igual el total de varios datos." },
      { p: "altitud", d: "Altura de un lugar sobre el nivel del mar." },
      { p: "suavizar", d: "Hacer que algo sea menos fuerte o menos extremo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué capital tiene el mes de enero más frío? ¿Con qué temperatura media?", r: "Granada, con 6,5 °C.", lineas: 1 },
      { tipo: "comprension", q: "¿Cuántos milímetros llueve al año en Córdoba más que en Almería?", r: "405 mm más (605 − 200).", lineas: 1 },
      { tipo: "comprension", q: "¿Qué capital es la más calurosa en julio? Elige:", opciones: ["Córdoba", "Sevilla", "Almería"], r: "Sevilla" },
      { tipo: "comprension", q: "Calcula la diferencia entre julio y enero en Granada y en Málaga. ¿En cuál es mayor?", r: "Granada: 25,3 − 6,5 = 18,8 °C. Málaga: 25,5 − 12,1 = 13,4 °C. Es mayor en Granada.", lineas: 2 },
      { tipo: "comprension", q: "Usa el texto para explicar por qué Málaga tiene un invierno más templado que Granada.", r: "Porque Málaga está junto al mar, que suaviza las temperaturas, y Granada está en el interior y a más de 500 metros de altitud.", lineas: 2 },
      { tipo: "texto", q: "¿Por qué es importante leer la nota que hay bajo la tabla? ¿Qué información nos da?", r: "Porque indica la fuente (AEMET), el periodo de los datos (1981-2010) y explica la unidad mm, sin la cual no entenderíamos bien la tabla.", lineas: 2 },
      { tipo: "opinion", q: "Según la tabla, ¿en qué capital te gustaría vivir? Justifica tu elección con al menos dos datos.", r: "Respuesta libre. Valorar que use datos concretos de la tabla.", lineas: 3 },
      { tipo: "opinion", q: "Almería recibe muy poca lluvia. ¿Qué consejos darías para ahorrar agua en una ciudad así? ¿Por qué?", r: "Respuesta libre. Valorar propuestas razonadas.", lineas: 3 },
      { tipo: "reflexion", q: "Estos datos son de 1981 a 2010. ¿Crees que si se midieran ahora serían iguales? ¿Qué sabes del cambio climático que te ayude a responder?", r: "Respuesta libre. Valorar que relacione los datos con el aumento de las temperaturas.", lineas: 3 },
    ],
  },
];
