// Lecturas · Textos instructivos (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["instructivo"] = [
  {
    id: "instructivo-01-semillas-en-un-vaso",
    titulo: "Un huerto en un vaso de yogur",
    subtipo: "Instrucciones de jardinería",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has plantado alguna vez una semilla? ¿Qué crees que necesita una planta para crecer?",
    texto: [
      { p: "No hace falta tener un gran jardín para ver crecer una planta. Con un vaso de yogur vacío, un poco de tierra y mucha paciencia, puedes montar tu propio huerto en la ventana. Estas instrucciones sirven para plantar semillas de lentejas, de judías o de albahaca, que germinan deprisa y son fáciles de cuidar. Si lo hacéis en clase, cada alumno puede plantar su vaso y después comparar cuál crece más." },
      { h: "Lo que necesita una semilla" },
      { p: "Una semilla parece una piedrecita sin vida, pero dentro guarda una planta diminuta dormida. Para despertarla necesita tres cosas: agua, aire y una temperatura templada, ni muy fría ni muy caliente. La luz todavía no le hace falta; la necesitará después, cuando salgan las primeras hojas verdes. Por eso, en los primeros días lo más importante es que la tierra esté húmeda y esponjosa." },
      { lista: [
        "Un vaso de yogur vacío y bien limpio.",
        "Un lápiz o un palillo para hacer agujeros.",
        "Tierra para macetas (sustrato).",
        "Tres o cuatro semillas.",
        "Un plato pequeño para poner debajo.",
        "Agua y una cuchara.",
        "Una etiqueta y un rotulador.",
      ], titulo: "Materiales" },
      { lista: [
        "En primer lugar, pide a un adulto que haga dos o tres agujeritos en el fondo del vaso con la punta de un lápiz. Así el agua que sobre podrá salir y las raíces no se pudrirán.",
        "A continuación, llena el vaso de tierra hasta dos dedos por debajo del borde. No la aprietes demasiado: las raíces necesitan aire.",
        "Después, haz con el dedo tres hoyitos poco profundos, de un centímetro más o menos, y coloca una semilla en cada uno.",
        "Luego, cubre las semillas con una capa fina de tierra.",
        "Riega con dos o tres cucharadas de agua. La tierra debe quedar húmeda, pero no encharcada.",
        "Escribe en la etiqueta el nombre de la semilla y la fecha, y pégala en el vaso.",
        "Por último, coloca el vaso sobre el plato, cerca de una ventana con luz, pero sin sol muy fuerte.",
      ], ordenada: true, titulo: "Pasos" },
      { h: "Cuidados de cada día" },
      { p: "Toca la tierra cada mañana: si está seca, riégala con una cucharada de agua. En pocos días verás asomar un tallito verde. Cuando la planta tenga cuatro o cinco hojas, puedes pasarla a una maceta más grande." },
      { h: "¿Algo va mal? Soluciones" },
      { lista: [
        "Si pasan dos semanas y no brota nada, quizá enterraste la semilla demasiado hondo o la tierra se secó. Vuelve a intentarlo con semillas nuevas.",
        "Si sale una capa blanca y peluda sobre la tierra, es moho: estás regando demasiado. Deja secar un poco la superficie.",
        "Si el tallo crece muy largo, fino y pálido, a la planta le falta luz. Acércala a la ventana.",
      ], titulo: "Problemas frecuentes" },
      { h: "El diario del huerto" },
      { p: "Si anotas cada día lo que mide la planta, tendrás tu propio diario de científico. Mira cómo lo hizo Nerea, de quinto: «Día 1: planto tres lentejas. Día 3: nada. Día 4: ¡asoma una cosa blanca! Día 6: ya mide dos centímetros y tiene dos hojitas. Día 10: seis centímetros; la de mi compañero Álex solo mide cuatro, pero su vaso está más lejos de la ventana»." },
    ],
    vocabulario: [
      { p: "germinar", d: "empezar a brotar una semilla." },
      { p: "sustrato", d: "tierra especial, con nutrientes, para plantas de maceta." },
      { p: "encharcada", d: "tan llena de agua que se forman charcos." },
      { p: "moho", d: "capa de hongos que sale donde hay demasiada humedad." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el primer paso y el vaso no tuviera agujeros?", r: "El agua sobrante no podría salir, la tierra se encharcaría y las raíces se pudrirían.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que la planta de Álex medía menos que la de Nerea?", r: "Porque su vaso estaba más lejos de la ventana y recibía menos luz.", lineas: 2 },
      { tipo: "comprension", q: "Si el tallo sale largo, fino y pálido, significa que la planta… Elige:", opciones: ["tiene demasiada agua", "necesita más luz", "está enferma de moho"], r: "necesita más luz" },
      { tipo: "texto", q: "Copia dos conectores de orden del texto y dos verbos en imperativo.", r: "Conectores: en primer lugar, a continuación, después, luego, por último. Verbos: llena, haz, coloca, cubre, riega, escribe…", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es mejor aprender cómo crece una planta leyendo el libro o cultivándola? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
      { tipo: "reflexion", q: "Casi todo lo que comemos empieza siendo una semilla. ¿Qué pasaría si nadie supiera cultivar la tierra?", r: "Respuesta libre. Valorar que relacione la agricultura con la alimentación.", lineas: 2 },
    ],
  },
  {
    id: "instructivo-02-normas-biblioteca",
    titulo: "Normas de la biblioteca Las Mil Páginas",
    subtipo: "Normas de uso",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Hay biblioteca en tu colegio o en tu barrio? ¿Qué normas crees que tiene y para qué sirven?",
    texto: [
      { p: "La biblioteca de nuestro colegio se llama Las Mil Páginas, aunque en realidad tiene más de tres mil libros. Es un lugar de todos, y para que todo el mundo pueda leer, buscar información y disfrutar, el equipo de bibliotecarios de sexto ha preparado estas normas. Léelas con atención antes de tu primera visita." },
      { h: "Nuestros rincones" },
      { p: "La biblioteca tiene tres zonas. En el rincón de lectura hay cojines y una alfombra para leer tranquilamente. En la mesa grande se hacen los trabajos y se puede hablar en voz baja con el equipo. Junto a la ventana están los dos ordenadores, que sirven para buscar libros en el catálogo y consultar información para los trabajos de clase, no para jugar." },
      { lista: [
        "Entrar en silencio o hablando en voz muy baja.",
        "Lavarse las manos antes de tocar los libros si vienes del recreo.",
        "Dejar mochilas y abrigos en las perchas de la entrada.",
        "No comer ni beber dentro de la sala.",
      ], titulo: "Al llegar" },
      { lista: [
        "Buscar el libro por el color de su etiqueta: verde para cuentos, azul para ciencia, naranja para cómics y rojo para poesía.",
        "Sacar el libro con cuidado, tirando del lomo por el centro y no por arriba.",
        "Si decides no llevártelo, dejarlo en el carrito gris. El equipo de bibliotecarios lo colocará en su sitio.",
        "Pasar las páginas por la esquina, sin mojar el dedo.",
      ], titulo: "Para elegir un libro" },
      { lista: [
        "En primer lugar, llevar el libro y el carné de lector al mostrador.",
        "A continuación, esperar a que anoten el título y la fecha.",
        "Después, guardar el libro en una bolsa para que no se estropee en la mochila.",
        "Por último, devolverlo en un plazo de dos semanas. Si no lo has terminado, puedes pedir una semana más.",
      ], ordenada: true, titulo: "Para llevarte un libro prestado" },
      { lista: [
        "Busca su título en el catálogo del ordenador: te dirá si está en la biblioteca o prestado.",
        "Si está prestado, pide en el mostrador que te lo reserven. Te avisarán cuando lo devuelvan.",
        "Si no lo tenemos, escríbelo en el buzón de sugerencias.",
      ], titulo: "Si no encuentras un libro" },
      { h: "Si un libro se rompe" },
      { p: "No intentes arreglarlo con celo. Avisa en el mostrador: tenemos un botiquín de libros con cinta especial. Nadie se va a enfadar por un accidente, pero sí por esconderlo." },
      { h: "Actividades de la biblioteca" },
      { p: "Los jueves en el recreo se reúne el club de lectura. Cada mes elegimos un libro entre todos, lo leemos en casa y después lo comentamos: qué nos ha gustado, qué cambiaríamos y qué personaje nos gustaría ser. También tenemos la mochila viajera: cada fin de semana, una familia se lleva a casa tres libros y un cuaderno donde escribe o dibuja lo que ha leído. Y en el buzón de sugerencias puedes pedir los libros que te gustaría encontrar en las estanterías." },
      { h: "Cómo entrar en el equipo" },
      { p: "Los alumnos de quinto y sexto pueden apuntarse al equipo de bibliotecarios. Sus tareas son colocar los libros, atender el mostrador en el recreo y recomendar lecturas a los más pequeños. Solo se pide una cosa: que te gusten los libros y tener paciencia." },
      { cita: "Un libro cuidado hoy es un libro que leerá otro niño mañana." },
    ],
    vocabulario: [
      { p: "lomo", d: "parte del libro donde están cosidas o pegadas las hojas." },
      { p: "carné de lector", d: "tarjeta que te permite llevarte libros prestados." },
      { p: "plazo", d: "tiempo que tienes para hacer algo." },
      { p: "catálogo", d: "lista ordenada de todos los libros de una biblioteca." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Si buscas un libro sobre los planetas, ¿de qué color será su etiqueta? ¿Y si buscas un cómic?", r: "Azul, porque es un libro de ciencia. Los cómics llevan etiqueta naranja.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que no hay que colocar tú mismo el libro en la estantería?", r: "Porque podría quedar en un sitio equivocado y luego nadie lo encontraría. El equipo lo coloca en su lugar correcto.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué consiste la mochila viajera y para qué crees que sirve?", r: "Una familia se lleva tres libros a casa el fin de semana y escribe o dibuja en un cuaderno lo que ha leído. Sirve para que se lea también en familia.", lineas: 2 },
      { tipo: "texto", q: "En la mayoría de las normas de este texto los verbos están en infinitivo (entrar, dejar…). Escribe dos normas cambiando el verbo a imperativo.", r: "Por ejemplo: Entra en silencio. Deja la mochila en la percha. No comas ni bebas.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría formar parte del equipo de bibliotecarios? ¿Qué norma nueva añadirías y por qué?", r: "Respuesta libre. Valorar que justifique.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante que existan bibliotecas públicas y gratuitas?", r: "Respuesta libre. Valorar que mencione que todo el mundo pueda leer aunque no pueda comprar libros.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-03-comba-barca",
    titulo: "Al pasar la barca: cómo jugar a la comba",
    subtipo: "Instrucciones de un juego popular",
    curso: "5º",
    fuente: "Texto original (la canción es popular)",
    antes: "¿Conoces algún juego de comba? ¿Recuerdas alguna canción que se cante mientras se salta?",
    texto: [
      { p: "La comba es uno de los juegos de patio más antiguos. En los recreos de muchos colegios de Andalucía se sigue oyendo el golpeteo de la cuerda contra el suelo y las canciones que marcan el ritmo. Estas canciones han pasado de abuelas a nietas y de hermanos mayores a pequeños sin que nadie las escribiera. Aquí tienes las instrucciones para jugar a una de las más conocidas: «Al pasar la barca»." },
      { lista: [
        "Una cuerda larga, de unos cuatro o cinco metros.",
        "Un espacio llano y sin obstáculos.",
        "Un grupo de cuatro jugadores o más.",
        "Calzado deportivo bien atado.",
      ], titulo: "Materiales" },
      { h: "Antes de empezar: calentamiento" },
      { p: "Saltar la comba cansa más de lo que parece. Antes de jugar, mueve los tobillos haciendo círculos, da diez saltitos suaves en el sitio y estira un poco las piernas. Así evitarás torceduras." },
      { lista: [
        "Primero, elegid a dos personas para que den a la comba. Cada una se coloca en un extremo, sujetando la cuerda con firmeza.",
        "Después, las que dan empiezan a mover la cuerda formando un arco, siempre al mismo ritmo y en el mismo sentido.",
        "A continuación, el resto forma una fila a un lado. La primera jugadora espera a que la cuerda toque el suelo y entra saltando.",
        "Mientras salta, todo el grupo canta: «Al pasar la barca, me dijo el barquero: las niñas bonitas no pagan dinero».",
        "Luego, cuando la canción termina, la saltadora sale de la cuerda sin tocarla y se coloca al final de la fila.",
        "Por último, entra la siguiente persona de la fila y se repite la canción.",
      ], ordenada: true, titulo: "Cómo se juega" },
      { h: "Normas importantes" },
      { p: "Si alguien pisa la cuerda o se enreda, pasa a dar a la comba y la persona que daba se une a la fila. Así todos saltan y todos dan. Quien da a la comba debe hacerlo despacio con los más pequeños y más rápido con quien lo pida. Nunca se tira de la cuerda de golpe para hacer caer a nadie." },
      { lista: [
        "Mantén el brazo firme y gira desde el hombro, no solo con la muñeca.",
        "Mira a tu compañera del otro extremo para llevar las dos el mismo ritmo.",
        "Avisa con un «¡va!» antes de acelerar, para que quien salta esté preparado.",
      ], titulo: "Consejos para quien da a la comba" },
      { h: "Retos para expertos" },
      { lista: [
        "Saltar toda la canción a la pata coja, primero con un pie y luego con el otro.",
        "Entrar de dos en dos, cogidos de la mano, y saltar juntos sin soltarse.",
        "Agacharse a tocar el suelo con la mano entre salto y salto.",
        "Entrar y salir sin que la cuerda se detenga ni una sola vez en toda la ronda.",
        "Dar la vuelta completa mientras se salta, mirando primero a un lado y después al otro.",
      ], titulo: "Cuando ya domines el juego" },
      { p: "Un consejo de quienes más saben: no mires la cuerda, mira a quien la da. Sus brazos te avisan del ritmo antes que la cuerda. Y si fallas, no pasa nada: dar a la comba también es un arte, porque de un buen ritmo depende que los demás salten bien." },
      { p: "Cuando ya dominéis el juego, podéis inventar vuestra propia versión de la canción. En muchos patios, por ejemplo, se cambia la letra para que diga «los niños y niñas no pagan dinero», y así la canción es de todos. También podéis inventar canciones nuevas sobre vuestro colegio, vuestro barrio o vuestro equipo favorito." },
    ],
    vocabulario: [
      { p: "extremo", d: "cada una de las puntas de algo alargado." },
      { p: "obstáculo", d: "algo que estorba el paso." },
      { p: "torcedura", d: "lesión que se produce al doblarse mal una articulación, como el tobillo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué ocurre si alguien pisa la cuerda? ¿Por qué crees que la norma es así?", r: "Pasa a dar a la comba y quien daba se une a la fila. Así todos saltan y todos dan por turnos.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el texto aconseja mirar a quien da la comba y no a la cuerda?", r: "Porque sus brazos avisan del ritmo antes que la cuerda, así puedes prepararte para saltar a tiempo.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el texto propone cambiar la letra de la canción? Elige:", opciones: ["Porque es muy larga", "Para que la canción incluya a todos", "Porque la original no rima"], r: "Para que la canción incluya a todos" },
      { tipo: "texto", q: "Además de materiales y pasos, este texto tiene otras partes. Nombra dos y explica para qué sirve una de ellas.", r: "Calentamiento (para evitar torceduras), normas importantes (para jugar de forma justa y segura) y retos para expertos (para hacer el juego más difícil).", lineas: 2 },
      { tipo: "opinion", q: "¿Qué juego de patio te gustaría enseñar a tus compañeros? ¿Cuál sería su norma más importante?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Estos juegos pasan de unos niños a otros sin estar escritos. ¿Por qué crees que es bueno escribirlos?", r: "Respuesta libre. Valorar que hable de conservar la tradición y enseñar a otros.", lineas: 2 },
    ],
  },
  {
    id: "instructivo-04-salmorejo",
    titulo: "Salmorejo cordobés para cuatro personas",
    subtipo: "Receta",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has probado el salmorejo? ¿Qué platos típicos de tu pueblo o ciudad sabrías preparar?",
    texto: [
      { p: "El salmorejo es una crema fría de tomate y pan muy típica de Córdoba. Es perfecto para los días de calor y no necesita horno ni fuego. Nació como una comida sencilla, hecha con lo que había en casa: pan del día anterior, tomates de la huerta y aceite de oliva. Hoy se sirve en casas y restaurantes de toda Andalucía." },
      { p: "Eso sí: en esta receta hay dos tareas que solo puede hacer un adulto, porque hay que usar un cuchillo y una batidora. Las verás marcadas con la palabra ADULTO." },
      { h: "Antes de empezar" },
      { lista: [
        "Lávate bien las manos con agua y jabón.",
        "Recógete el pelo si lo llevas largo y ponte un delantal.",
        "Limpia la encimera y prepara todos los ingredientes antes de empezar.",
        "Repartid las tareas: una persona adulta y uno o dos ayudantes.",
      ], titulo: "Normas de la cocina" },
      { lista: [
        "1 kilo de tomates rojos y bien maduros.",
        "200 gramos de pan del día anterior.",
        "Medio diente de ajo (si os gusta).",
        "100 mililitros de aceite de oliva virgen extra.",
        "Una pizca de sal.",
        "Para decorar: un huevo duro y unos taquitos de jamón.",
      ], titulo: "Ingredientes" },
      { lista: [
        "Lavar bien los tomates con agua fría y secarlos con un paño.",
        "ADULTO: cortar los tomates en cuartos y quitarles la parte dura del tallo.",
        "Trocear el pan con las manos en pedazos pequeños.",
        "Poner los tomates en un recipiente alto. ADULTO: triturarlos con la batidora hasta que quede un líquido sin grumos.",
        "Añadir el pan y el ajo, y dejarlo reposar diez minutos para que el pan se empape.",
        "ADULTO: volver a batir mientras el ayudante echa el aceite poco a poco, en un chorro muy fino. La crema se volverá más espesa y de color anaranjado.",
        "Añadir la sal, probar y remover.",
        "Guardar el salmorejo en el frigorífico al menos una hora.",
        "Servirlo en cuencos y decorarlo con el huevo duro picado y el jamón.",
      ], ordenada: true, titulo: "Preparación" },
      { h: "Trucos de la cocina" },
      { p: "Cuanto más maduros estén los tomates, más sabroso quedará. Si la crema está muy espesa, se puede añadir un poco de agua fría; si está muy líquida, un poco más de pan. Para una versión vegetariana, basta con no poner jamón. El salmorejo aguanta uno o dos días en el frigorífico, en un recipiente cerrado." },
      { h: "Cómo se sirve" },
      { p: "El salmorejo se sirve muy frío, en cuenco o en plato hondo. En Córdoba es costumbre acompañarlo con un buen trozo de pan para mojar, o ponerlo en el centro de la mesa para que cada uno se sirva. También se puede usar como salsa: con unas tiras de pimiento o unas patatas cocidas queda riquísimo. Y si os sobra, al día siguiente estará todavía más sabroso." },
      { h: "La familia de las cremas frías" },
      { p: "El salmorejo tiene primos por toda Andalucía. El gazpacho es más líquido, lleva también pepino y pimiento, y muchas familias lo toman en vaso. La porra antequerana, de Antequera, en Málaga, se parece mucho al salmorejo, pero es todavía más espesa. Y el ajoblanco, típico de Málaga, no es rojo sino blanco, porque se hace con almendras. Todos tienen algo en común: son platos frescos, baratos y pensados para el verano." },
    ],
    vocabulario: [
      { p: "triturar", d: "deshacer algo en trozos muy pequeños hasta que queda como un puré." },
      { p: "grumo", d: "bolita que se forma en una crema cuando no está bien mezclada." },
      { p: "empaparse", d: "llenarse de líquido." },
      { p: "encimera", d: "superficie plana de la cocina donde se preparan los alimentos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tareas de la receta debe hacer un adulto y por qué?", r: "Cortar los tomates y usar la batidora, porque se usan un cuchillo y un aparato eléctrico que pueden ser peligrosos.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el paso de dejar reposar el pan diez minutos?", r: "El pan no se empaparía bien y el salmorejo quedaría con trozos o grumos.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué se diferencia el ajoblanco del salmorejo? Elige:", opciones: ["Se toma caliente", "Es blanco porque se hace con almendras", "Lleva pepino y pimiento"], r: "Es blanco porque se hace con almendras" },
      { tipo: "texto", q: "Los pasos de esta receta están escritos en infinitivo. Reescribe el primer paso en imperativo y añádele un conector de orden.", r: "En primer lugar, lava bien los tomates con agua fría y sécalos con un paño.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es importante que los niños ayuden en la cocina? ¿Qué tareas podrían hacer sin peligro?", r: "Respuesta libre. Valorar que distinga tareas seguras.", lineas: 2 },
      { tipo: "reflexion", q: "El salmorejo aprovecha el pan duro. ¿Por qué crees que antes se aprovechaba tanto la comida? ¿Lo hacemos hoy?", r: "Respuesta libre. Valorar que hable de no desperdiciar comida.", lineas: 2 },
    ],
  },
  {
    id: "instructivo-05-comedero-pajaros",
    titulo: "Un comedero para los pájaros del patio",
    subtipo: "Instrucciones de manualidad",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Qué pájaros ves en tu calle o en el patio del colegio? ¿Cómo crees que encuentran comida en invierno?",
    texto: [
      { p: "Gorriones, verdecillos, jilgueros y carboneros viven muy cerca de nosotros, pero en invierno les cuesta encontrar semillas e insectos. Con un brik de leche vacío puedes construir un comedero y observar de cerca a tus vecinos con plumas. Este proyecto se hace en equipo y con un adulto que se encargue de los cortes." },
      { lista: [
        "Un brik de leche o de zumo vacío, lavado y seco.",
        "Tijeras (solo para el adulto) y un rotulador.",
        "Un palito de unos quince centímetros.",
        "Un cordel resistente de un metro.",
        "Pintura y pinceles (opcional).",
        "Alpiste o una mezcla de semillas para pájaros.",
      ], titulo: "Materiales" },
      { lista: [
        "Primero, lava el brik por dentro y déjalo secar un día entero. Si queda húmedo, las semillas se llenarán de moho.",
        "Después, dibuja con un rotulador una ventana en dos lados opuestos del brik, a unos cinco centímetros de la base.",
        "A continuación, el adulto recorta las ventanas con las tijeras. Tienen que ser lo bastante grandes para que un pájaro meta la cabeza.",
        "Luego, el adulto hace un agujero pequeño debajo de cada ventana. Mete el palito por los dos agujeros: servirá de posadero.",
        "Si quieres, pinta el comedero con colores naturales, como verdes y marrones. Espera a que se seque.",
        "Después, pasa el cordel por la parte de arriba del brik y haz un nudo fuerte.",
        "Por último, llena la base con semillas y cuelga el comedero de una rama, a más de metro y medio del suelo.",
      ], ordenada: true, titulo: "Pasos" },
      { h: "Qué NO debes poner" },
      { p: "Nunca eches pan, galletas, patatas fritas ni restos de comida: tienen sal y otros ingredientes que les sientan mal. Tampoco pongas agua en el mismo comedero, porque mojaría las semillas. Si quieres ofrecerles de beber, coloca aparte un plato poco hondo y cambia el agua cada día." },
      { h: "¿Quién vendrá a comer?" },
      { lista: [
        "Gorrión: marrón y gris; el macho tiene una mancha negra en la garganta, como un babero.",
        "Jilguero: cara roja y una franja amarilla muy llamativa en las alas.",
        "Verdecillo: muy pequeño, de color amarillo verdoso y con el pico corto.",
        "Carbonero: cabeza negra, mejillas blancas y pecho amarillo con una raya negra en el centro, como una corbata.",
      ], titulo: "Guía rápida" },
      { h: "Consejos para observar" },
      { p: "Cuelga el comedero lejos de lugares donde puedan esconderse los gatos. Los pájaros tardarán unos días en confiar en él, así que ten paciencia. Observa desde lejos y en silencio, y apunta en una tabla como esta qué especies vienen y a qué hora. Cambia las semillas cada semana y limpia el comedero para que no enfermen. En primavera, cuando haya comida de sobra en el campo, puedes retirarlo." },
      { tabla: { titulo: "Ejemplo de ficha de observación", cab: ["Día", "Hora", "Especie", "Cuántos"], filas: [
        ["Lunes", "9:15", "Gorrión", "3"],
        ["Lunes", "11:30", "Carbonero", "1"],
        ["Martes", "9:10", "Gorrión", "5"],
        ["Martes", "13:00", "Jilguero", "2"],
      ] } },
    ],
    vocabulario: [
      { p: "posadero", d: "palo o lugar donde se posan los pájaros." },
      { p: "moho", d: "capa de hongos que sale en la comida húmeda o estropeada." },
      { p: "alpiste", d: "semilla pequeña que se da de comer a los pájaros." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué crees que hay que colgar el comedero a más de metro y medio y lejos de donde se esconden los gatos?", r: "Para que los gatos no puedan cazar a los pájaros mientras comen.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué no hay que poner pan ni restos de comida en el comedero?", r: "Porque tienen sal y otros ingredientes que les sientan mal a los pájaros.", lineas: 1 },
      { tipo: "comprension", q: "Ves un pájaro con la cara roja y una franja amarilla en las alas. ¿Qué es? Elige:", opciones: ["Un gorrión", "Un jilguero", "Un carbonero"], r: "Un jilguero" },
      { tipo: "texto", q: "Además de los pasos, este texto tiene consejos, una guía y una tabla. ¿Para qué sirve la ficha de observación? Copia un verbo en imperativo de los consejos.", r: "Para anotar de forma ordenada qué pájaros vienen, cuándo y cuántos. Verbos: cuelga, observa, apunta, cambia, limpia.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es buena idea dar de comer a los animales salvajes? ¿Siempre o solo a veces? Explica por qué.", r: "Respuesta libre. Valorar que matice (solo en invierno, sin pan ni restos de comida humana…).", lineas: 2 },
      { tipo: "reflexion", q: "Reutilizar un brik es una forma de cuidar el planeta. ¿Qué otros objetos que tiramos podrían tener una segunda vida?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "instructivo-06-origami-vaso",
    titulo: "Un vaso de papel sin pegamento",
    subtipo: "Instrucciones de origami",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Sabes qué es el origami? ¿Has hecho alguna vez una figura de papel doblado, como un barco o una pajarita?",
    texto: [
      { p: "El origami es el arte de hacer figuras doblando papel, sin tijeras ni pegamento. Nació en Japón hace siglos, y en España tenemos nuestra propia figura estrella: la pajarita. Al escritor Miguel de Unamuno le gustaba tanto hacer pajaritas de papel que incluso escribió, medio en broma, un tratado sobre ellas." },
      { p: "Hoy empezaremos por algo más sencillo y útil: un vaso de papel que, si está bien doblado, aguanta un poco de agua durante un rato. Lee todos los pasos antes de empezar y dobla sobre una mesa dura." },
      { h: "Dos palabras que debes conocer" },
      { p: "En los libros de origami casi todos los pasos son de dos tipos. Un doblez en valle es el que forma una V, como un valle entre montañas: el papel se dobla hacia ti. Un doblez en montaña es justo al revés: el papel se dobla hacia atrás y el pliegue queda en lo alto, como la cima de una montaña. Nuestro vaso solo usa dobleces en valle. En los esquemas, el doblez en valle se dibuja con una línea de rayas y el de montaña, con rayas y puntos, pero aquí te lo explicaremos todo con palabras." },
      { lista: [
        "Una hoja cuadrada de papel de unos 20 centímetros de lado. Si solo tienes un folio, pide ayuda para cortar la tira que sobra.",
        "Una mesa lisa.",
        "Paciencia y uñas para marcar bien los pliegues.",
      ], titulo: "Materiales" },
      { lista: [
        "En primer lugar, coloca el cuadrado como si fuera un rombo, con una punta hacia ti.",
        "Dobla la hoja por la mitad llevando la punta de abajo hasta la de arriba. Tendrás un triángulo con el lado largo abajo. Marca bien el pliegue.",
        "A continuación, dobla la punta derecha del triángulo hacia la izquierda, de forma que toque el borde izquierdo. El borde de arriba de esa solapa debe quedar recto, horizontal.",
        "Después, haz lo mismo con la punta izquierda: llévala hacia la derecha, por encima de la anterior, hasta que toque el borde contrario.",
        "Ahora, arriba quedan dos puntas sueltas. Baja la primera hacia ti, metiéndola dentro de la solapa delantera.",
        "Da la vuelta a la figura y baja la otra punta hacia el otro lado.",
        "Finalmente, aprieta suavemente los laterales para abrir la boca del vaso.",
      ], ordenada: true, titulo: "Pasos" },
      { h: "Si algo sale mal" },
      { p: "Si el vaso queda torcido, seguramente el paso tres no está bien hecho: el borde de la solapa debe quedar paralelo al lado largo de abajo. Desdobla hasta ese punto y vuelve a intentarlo. Si las puntas no se quedan dentro, es que no marcaste bien los pliegues: repásalos con la uña." },
      { h: "Reto: ¿cuánto aguanta tu vaso?" },
      { p: "Haced tres vasos iguales con tres papeles distintos: un folio, una hoja de periódico y papel de colores. Echad en cada uno la misma cantidad de agua, sobre una bandeja, y medid con un reloj cuántos segundos tarda en empezar a gotear. ¿Qué papel gana? Antes de probar, escribid vuestra predicción y comprobad después si acertasteis." },
      { p: "Si el vaso aguanta bien, prueba a hacer una segunda versión: la misma figura, pero con una hoja el doble de grande. ¿Aguantará también el doble de agua? Anota lo que pase y compáralo con lo que habías imaginado." },
      { p: "Con papel de periódico puedes hacer vasos grandes para guardar lápices; con papel de colores, pequeños cestitos para una fiesta." },
      { dato: "¿Sabías que el origami también se estudia en ciencia? Sus pliegues se han usado para diseñar objetos que deben plegarse y desplegarse, como algunos paneles de satélites." },
    ],
    vocabulario: [
      { p: "pliegue", d: "señal que queda en el papel al doblarlo." },
      { p: "solapa", d: "parte doblada que queda encima de otra." },
      { p: "paralelo", d: "que va en la misma dirección que otra línea, sin tocarla nunca." },
      { p: "tratado", d: "libro o escrito que explica un tema con detalle." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué diferencia hay entre un doblez en valle y un doblez en montaña?", r: "En el doblez en valle el papel se dobla hacia ti y forma una V; en el de montaña se dobla hacia atrás y el pliegue queda arriba, como una cima.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué ocurre si el paso tres no se hace bien? ¿Cómo se soluciona?", r: "El vaso queda torcido. Hay que desdoblar hasta ese paso y repetirlo dejando el borde paralelo al lado largo de abajo.", lineas: 2 },
      { tipo: "comprension", q: "En el reto hay que echar la misma cantidad de agua en los tres vasos porque… Elige:", opciones: ["así se gasta menos agua", "así la comparación es justa y solo cambia el papel", "así los vasos pesan igual"], r: "así la comparación es justa y solo cambia el papel" },
      { tipo: "texto", q: "Copia cuatro palabras del texto que indican posición (por ejemplo: arriba…). ¿Por qué son necesarias en unas instrucciones?", r: "Abajo, arriba, derecha, izquierda, hacia ti, encima, dentro… Son necesarias para que el lector sepa exactamente dónde doblar.", lineas: 2 },
      { tipo: "opinion", q: "¿Te resulta más fácil aprender a hacer algo leyendo instrucciones, viendo dibujos o viendo a alguien hacerlo? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
      { tipo: "reflexion", q: "Un vaso de papel se estropea pronto y los de plástico duran siglos en la naturaleza. ¿Qué vaso usarías en una excursión? ¿Por qué?", r: "Respuesta libre. Valorar que proponga un vaso reutilizable y argumente.", lineas: 2 },
    ],
  },
  {
    id: "instructivo-07-volcan-bicarbonato",
    titulo: "Experimento: un volcán en la mesa de la cocina",
    subtipo: "Experimento científico",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Qué es una reacción química? ¿Has visto alguna vez algo que hace burbujas al mezclarlo?",
    texto: [
      { p: "Los volcanes de verdad expulsan lava que sale a más de mil grados. El nuestro será mucho más tranquilo: una espuma fría que brota por una reacción química entre dos productos que hay en casi todas las cocinas. Es un experimento seguro, pero hazlo con un adulto y sigue todas las normas." },
      { h: "Normas de seguridad" },
      { p: "Ponte gafas protectoras durante todo el experimento. No pruebes ninguna de las mezclas. Si te salpica en los ojos, lávalos con mucha agua y avisa a un adulto. Al terminar, tira los restos por el fregadero con abundante agua y lávate las manos." },
      { h: "Antes de empezar: tu hipótesis" },
      { p: "Los científicos no se limitan a mezclar cosas: primero se hacen una pregunta y escriben lo que creen que pasará. Eso se llama hipótesis. Nuestra pregunta es: ¿qué ocurrirá al echar vinagre sobre bicarbonato? Escribe tu respuesta en el cuaderno antes de seguir leyendo. Al final comprobarás si acertaste." },
      { lista: [
        "Una botella pequeña de plástico vacía.",
        "Una bandeja grande o un barreño.",
        "Plastilina o papel de periódico y cinta adhesiva para modelar la montaña.",
        "Dos cucharadas de bicarbonato de sodio.",
        "Medio vaso de vinagre.",
        "Un chorrito de lavavajillas y unas gotas de colorante alimentario rojo.",
        "Un embudo y gafas protectoras.",
      ], titulo: "Materiales" },
      { lista: [
        "Primero, ponte las gafas y coloca la botella en el centro de la bandeja.",
        "A continuación, modela una montaña alrededor de la botella con plastilina o periódico, dejando libre la boca.",
        "Después, con ayuda del embudo, echa el bicarbonato dentro de la botella.",
        "Luego, mezcla en un vaso el vinagre, el lavavajillas y el colorante.",
        "Pide a todos que se aparten un paso. Entonces, vierte la mezcla del vaso de golpe dentro de la botella y retira la mano.",
        "Por último, observa lo que ocurre y anota en tu cuaderno cuánto tiempo dura la erupción.",
      ], ordenada: true, titulo: "Procedimiento" },
      { h: "¿Qué ha pasado?" },
      { p: "El vinagre es un ácido y el bicarbonato es una base. Al juntarse, reaccionan y producen un gas llamado dióxido de carbono. Las burbujas de gas empujan el líquido hacia arriba y el lavavajillas las atrapa, formando una espuma que se desborda como si fuera lava." },
      { h: "Investiga más" },
      { p: "Repite el experimento cambiando una sola cosa cada vez: más bicarbonato, vinagre templado, una botella más estrecha… y compara los resultados. Si cambias dos cosas a la vez, no sabrás cuál de ellas ha provocado la diferencia. Así lo anotó el equipo de Aitana en su cuaderno:" },
      { tabla: { titulo: "Resultados del equipo de Aitana", cab: ["Prueba", "Qué cambiamos", "Duración de la erupción"], filas: [
        ["1", "Nada (receta normal)", "12 segundos"],
        ["2", "El doble de bicarbonato", "18 segundos"],
        ["3", "Botella más estrecha", "15 segundos, y la espuma subió más alto"],
      ] }, nota: "Resultados de un ejemplo; los tuyos pueden ser distintos." },
      { p: "Por cierto, en España también hay volcanes de verdad. El más reciente entró en erupción en la isla de La Palma, en 2021. Y en Andalucía, las rocas del Cabo de Gata, en Almería, nacieron de antiguos volcanes que hoy están apagados." },
    ],
    vocabulario: [
      { p: "reacción química", d: "cambio en el que unas sustancias se transforman en otras distintas." },
      { p: "erupción", d: "salida violenta de materia de un volcán." },
      { p: "hipótesis", d: "lo que suponemos que va a pasar, antes de comprobarlo." },
      { p: "desbordarse", d: "salirse un líquido por encima del borde." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué gas se produce en la reacción y qué papel tiene el lavavajillas?", r: "Dióxido de carbono. El lavavajillas atrapa las burbujas y forma la espuma.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué no se deben cambiar dos cosas a la vez al repetir el experimento?", r: "Porque entonces no se sabría cuál de los dos cambios ha provocado la diferencia en el resultado.", lineas: 2 },
      { tipo: "comprension", q: "Según la tabla del equipo de Aitana, ¿qué cambio hizo que la erupción durara más? Elige:", opciones: ["No cambiar nada", "Echar el doble de bicarbonato", "Usar una botella más estrecha"], r: "Echar el doble de bicarbonato" },
      { tipo: "texto", q: "Este texto tiene más partes que una receta. Nombra tres y explica para qué sirve la parte «¿Qué ha pasado?».", r: "Normas de seguridad, hipótesis, materiales, procedimiento, explicación, investiga más. La explicación dice por qué ocurre la reacción.", lineas: 2 },
      { tipo: "opinion", q: "Si pudieras cambiar una sola cosa del experimento, ¿cuál cambiarías y qué crees que pasaría?", r: "Respuesta libre. Valorar que formule una hipótesis.", lineas: 2 },
      { tipo: "reflexion", q: "Los científicos repiten sus experimentos muchas veces antes de dar un resultado por bueno. ¿Por qué crees que lo hacen?", r: "Respuesta libre. Valorar que hable de comprobar y evitar errores o casualidades.", lineas: 2 },
    ],
  },
  {
    id: "instructivo-08-brujula-grazalema",
    titulo: "Cómo usar una brújula en la Sierra de Grazalema",
    subtipo: "Instrucciones de uso de un objeto",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Cómo te orientarías si te perdieras en el campo sin móvil? ¿Qué es el norte?",
    texto: [
      { p: "La próxima semana, los alumnos de sexto haremos una ruta de senderismo por la Sierra de Grazalema, en la provincia de Cádiz, para visitar un bosque de pinsapos, un abeto que en España solo crece de forma natural en unas pocas sierras andaluzas. Iremos con guías y monitores, pero cada equipo llevará una brújula y un mapa. Estas instrucciones explican cómo usarla." },
      { h: "Qué debe llevar cada mochila" },
      { lista: [
        "Agua (al menos litro y medio por persona) y comida para el día.",
        "Gorra, crema solar y un chubasquero, porque en la sierra el tiempo cambia deprisa.",
        "Un silbato por equipo, para avisar si hay algún problema.",
        "La brújula, el mapa de la ruta y una bolsa para traer de vuelta la basura.",
      ], titulo: "Mochila" },
      { h: "Partes de la brújula" },
      { lista: [
        "Base transparente: la placa de plástico sobre la que va todo. Tiene una flecha grabada, la flecha de dirección.",
        "Aguja magnética: flota dentro de una cápsula con líquido. Su punta roja señala siempre el norte magnético.",
        "Limbo: el anillo que gira alrededor de la cápsula, con las letras N, S, E y O.",
      ], titulo: "Partes" },
      { lista: [
        "En primer lugar, aléjate un par de metros de objetos de metal, del móvil y de los imanes de la mochila, porque desvían la aguja.",
        "A continuación, coloca la brújula plana sobre la palma de la mano, a la altura del pecho, con la flecha de dirección apuntando hacia delante.",
        "Espera a que la aguja deje de moverse. Su punta roja señala el norte.",
        "Después, gira el limbo hasta que la N quede justo encima de la punta roja de la aguja.",
        "Para orientar el mapa, ponlo sobre el suelo o una piedra plana, con la brújula encima. Gira el mapa, no la brújula, hasta que el norte del mapa mire hacia donde apunta la aguja.",
        "Por último, busca en el mapa dónde estás y hacia dónde quieres ir. Ahora el mapa y el paisaje coinciden.",
      ], ordenada: true, titulo: "Cómo orientarse" },
      { h: "Un ejemplo en la ruta" },
      { p: "Imagina que el equipo de Hugo, Salma y Daniel llega a un cruce de caminos. En el mapa, el bosque de pinsapos queda hacia el norte y el pueblo, hacia el sur. Orientan el mapa como explica el paso cinco y descubren que el camino de la derecha sube hacia el norte. ¡Es el suyo! Antes de seguir, Salma comprueba que en el mapa también aparece un arroyo junto al sendero. Diez minutos después, lo oyen correr: van bien. Aun así, en el siguiente cruce vuelven a sacar la brújula, porque un buen orientador comprueba el rumbo muchas veces, no solo al principio." },
      { h: "Y si no tienes brújula" },
      { p: "El sol también ayuda. Sale más o menos por el este y se pone por el oeste, y a mediodía, en España, queda hacia el sur. Pero es una ayuda aproximada: úsala solo para comprobar, no para decidir un camino tú solo. Y no mires nunca directamente al sol, porque puede dañarte la vista." },
      { h: "Cuidados y recuerda" },
      { p: "No dejes la brújula al sol mucho tiempo ni cerca de altavoces. Guárdala en su funda. Y lo más importante: la brújula ayuda, pero no sustituye al sentido común. Si tu equipo duda del camino, no sigáis adelante: parad en un lugar seguro, avisad al monitor con el silbato y esperad juntos." },
    ],
    vocabulario: [
      { p: "pinsapo", d: "árbol de la familia de los abetos, propio de algunas sierras de Andalucía." },
      { p: "norte magnético", d: "punto hacia el que apuntan las agujas de las brújulas." },
      { p: "desviar", d: "hacer que algo cambie de dirección." },
      { p: "chubasquero", d: "chaqueta fina que protege de la lluvia." },
    ],
    preguntas: [
      { tipo: "comprension", q: "En el paso cinco, ¿qué se gira: el mapa o la brújula? ¿Por qué crees que es así?", r: "El mapa. La aguja siempre apunta al norte, así que hay que mover el mapa para que coincida con ella.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo supo el equipo de Hugo que iba por el buen camino?", r: "Porque el mapa mostraba un arroyo junto al sendero y, al poco tiempo, lo oyeron correr.", lineas: 2 },
      { tipo: "comprension", q: "Si el equipo duda del camino, el texto dice que hay que… Elige:", opciones: ["separarse para buscar el camino", "parar, avisar con el silbato y esperar juntos", "seguir hacia el norte"], r: "parar, avisar con el silbato y esperar juntos" },
      { tipo: "texto", q: "Este texto describe primero las partes del objeto y después da los pasos. ¿Por qué crees que está organizado así?", r: "Porque para entender los pasos hay que saber antes cómo se llama cada parte (limbo, aguja, flecha de dirección).", lineas: 2 },
      { tipo: "opinion", q: "Hoy casi todo el mundo usa el móvil para orientarse. ¿Crees que sigue siendo útil aprender a usar una brújula? ¿Por qué?", r: "Respuesta libre. Valorar que piense en la batería, la cobertura, etc.", lineas: 2 },
      { tipo: "reflexion", q: "Los pinsapos solo crecen de forma natural en unos pocos lugares. ¿Qué responsabilidades tenemos cuando visitamos un espacio natural protegido?", r: "Respuesta libre. Valorar que mencione no salirse de los senderos, no dejar basura, no arrancar plantas…", lineas: 2 },
    ],
  },
  {
    id: "instructivo-09-plan-evacuacion",
    titulo: "Suena la alarma: plan de evacuación del colegio",
    subtipo: "Protocolo de seguridad",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Habéis hecho alguna vez un simulacro en el colegio? ¿Qué recuerdas de lo que hicisteis?",
    texto: [
      { p: "Un simulacro es un ensayo de lo que haríamos ante una emergencia de verdad, como un incendio o un terremoto. Nuestro colegio, en Granada, hace uno cada trimestre. Algunos alumnos lo ven como un rato divertido fuera de clase, pero su objetivo es muy serio: que todas las personas del edificio salgan en orden, deprisa y sin hacerse daño. Cada clase tiene este protocolo pegado junto a la puerta." },
      { h: "Cómo leer el plano" },
      { p: "Junto al protocolo hay un plano del edificio. Un punto rojo con las palabras «Usted está aquí» señala tu aula. Las flechas verdes marcan el camino de salida más corto y el dibujo de varias personas juntas indica el punto de encuentro. Los extintores aparecen en rojo. Mira el plano con calma un día normal: en una emergencia no habrá tiempo." },
      { h: "Encargos de cada clase" },
      { lista: [
        "Responsable de cabeza: va el primero de la fila y sigue las flechas verdes.",
        "Responsable de cola: va el último y comprueba que nadie se queda atrás.",
        "Responsable de ventanas: cierra las ventanas antes de salir.",
        "La maestra o el maestro: coge la lista de clase, comprueba que el aula queda vacía y cierra la puerta sin llave.",
      ], titulo: "Funciones" },
      { lista: [
        "Al oír la alarma (un timbre largo y repetido), deja inmediatamente lo que estés haciendo.",
        "No recojas la mochila ni el abrigo. Las cosas se pueden recuperar; el tiempo, no.",
        "Colócate en fila junto a la puerta, en silencio, para poder oír las indicaciones.",
        "Sal detrás del responsable de cabeza, caminando rápido pero sin correr ni empujar.",
        "Baja las escaleras pegado a la pared, agarrado a la barandilla. No uses nunca el ascensor.",
        "Si encuentras humo en el camino, agáchate y avanza cerca del suelo, donde el aire está más limpio.",
        "Sigue las flechas verdes hasta el punto de encuentro: la pista deportiva.",
        "Allí, espera en fila mientras el maestro pasa lista. No vuelvas atrás por ningún motivo.",
      ], ordenada: true, titulo: "Qué hacer en caso de incendio" },
      { h: "¿Y si es un terremoto?" },
      { p: "Granada es una de las zonas de España donde más tiembla la tierra, aunque casi siempre son temblores tan suaves que ni se notan. Si hay un terremoto, el orden cambia: no hay que salir corriendo mientras el suelo se mueve, porque lo más peligroso es que caigan cosas encima. Recuerda tres palabras: agáchate, cúbrete y agárrate. Métete debajo de tu mesa, protégete la cabeza con los brazos y sujeta una pata de la mesa. Aléjate de ventanas y estanterías. Solo cuando pare el temblor, y cuando lo indique el maestro, se sigue el plan de salida." },
      { h: "¿Y si estoy en el baño o en otra clase?" },
      { p: "Si la alarma te pilla fuera de tu aula, no vayas a buscar a tu grupo. Únete a la fila más cercana y sal con ella. En el punto de encuentro, díselo a un adulto para que avise a tu maestro, que te estará buscando en su lista." },
      { h: "Después de salir" },
      { p: "En el punto de encuentro, cada clase se coloca en su sitio, siempre el mismo, marcado con el nombre del grupo en la valla. Nadie puede irse a casa ni volver al edificio hasta que la directora lo diga, aunque la alarma haya dejado de sonar. Si alguien se encuentra mal, lo dice en voz alta al maestro, que avisará al equipo de primeros auxilios. Mientras tanto, el resto espera sentado y en calma." },
      { p: "Después de cada simulacro, cada clase comenta qué ha salido bien y qué hay que mejorar. El último, por ejemplo, tardamos cuatro minutos en salir; el objetivo para el próximo es bajar de tres, sin correr y sin que nadie se quede atrás." },
    ],
    vocabulario: [
      { p: "evacuación", d: "salida ordenada de las personas de un lugar peligroso." },
      { p: "simulacro", d: "ensayo de lo que se haría en una situación real." },
      { p: "protocolo", d: "conjunto de pasos que se siguen siempre en una situación concreta." },
      { p: "extintor", d: "aparato que lanza un producto para apagar fuegos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué crees que el maestro coge la lista de clase antes de salir?", r: "Para pasar lista en el punto de encuentro y comprobar que no falta nadie.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué en un terremoto no hay que salir corriendo mientras el suelo se mueve? ¿Qué hay que hacer?", r: "Porque lo más peligroso es que caigan cosas encima. Hay que agacharse, cubrirse bajo la mesa y agarrarse a ella hasta que pare el temblor.", lineas: 2 },
      { tipo: "comprension", q: "Si la alarma suena mientras estás en el baño, debes… Elige:", opciones: ["volver a tu clase a buscar a tu grupo", "unirte a la fila más cercana y avisar en el punto de encuentro", "esperar en el baño"], r: "unirte a la fila más cercana y avisar en el punto de encuentro" },
      { tipo: "texto", q: "En un protocolo el orden de los pasos es fundamental. Explica por qué no se podrían cambiar de orden los pasos 7 y 8.", r: "Porque primero hay que llegar al punto de encuentro y solo allí se puede esperar en fila y pasar lista.", lineas: 2 },
      { tipo: "opinion", q: "Algunos alumnos ven el simulacro como un juego. ¿Qué les dirías para que se lo tomaran en serio?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
      { tipo: "reflexion", q: "¿Cómo adaptarías este plan para que un compañero en silla de ruedas o con dificultades para oír la alarma pudiera salir igual de seguro?", r: "Respuesta libre. Valorar propuestas como un compañero de apoyo, señales luminosas, rutas sin escaleras…", lineas: 2 },
    ],
  },
  {
    id: "instructivo-10-goalball",
    titulo: "Goalball: el deporte que se juega con los oídos",
    subtipo: "Reglamento de un deporte adaptado",
    curso: "6º",
    fuente: "Texto original (reglas simplificadas para el colegio)",
    datos: ["IBSA (Federación Internacional de Deportes para Ciegos): historia del goalball"],
    antes: "¿Qué deportes conoces que practiquen personas con discapacidad? ¿Has jugado alguna vez con los ojos tapados?",
    texto: [
      { p: "El goalball es un deporte paralímpico creado para personas ciegas o con poca visión. Se juega por equipos, con un balón que lleva cascabeles dentro, y todos los jugadores llevan los ojos tapados. Así nadie tiene ventaja: el partido se gana escuchando. En nuestro colegio lo jugamos en la semana del deporte inclusivo con estas reglas adaptadas." },
      { h: "Un poco de historia" },
      { p: "El goalball lo inventaron en 1946 el austriaco Hanz Lorenzen y el alemán Sepp Reindle. Querían ayudar a los soldados que se habían quedado ciegos en la Segunda Guerra Mundial a recuperar la forma física y la confianza. Poco a poco, el juego se volvió un deporte de competición, y en 1976, en los Juegos Paralímpicos de Toronto, entró por primera vez en el programa oficial." },
      { lista: [
        "Un balón con cascabeles (en el cole usamos uno de goma con cascabeles dentro de una bolsa de red).",
        "Antifaces opacos para todos los jugadores.",
        "Cinta adhesiva gruesa para marcar las líneas en el suelo, de modo que se puedan notar con los dedos.",
        "Dos porterías que ocupen todo el ancho de la pista (valen dos bancos tumbados o conos unidos con cuerda).",
        "Rodilleras y coderas.",
      ], titulo: "Material" },
      { lista: [
        "Formad dos equipos de tres jugadores. Cada equipo se coloca delante de su portería.",
        "Antes de empezar, todos se ponen el antifaz. A partir de ese momento, nadie puede tocárselo.",
        "El árbitro dice «¡Silencio!» y después «¡Juego!». El público debe estar callado mientras el balón rueda.",
        "El equipo que saca lanza el balón rodando o botando por el suelo, nunca por el aire, intentando meterlo en la portería contraria.",
        "Los defensores escuchan los cascabeles y se tumban de lado en el suelo para parar el balón con el cuerpo.",
        "Quien para el balón tiene diez segundos para lanzarlo de nuevo.",
        "Cada balón que cruza la línea de portería es un gol. Gana el equipo que marque más goles en dos partes de cinco minutos.",
      ], ordenada: true, titulo: "Cómo se juega" },
      { h: "Faltas" },
      { p: "Es falta tocarse el antifaz, tardar más de diez segundos en lanzar o lanzar el balón por el aire. También se castiga el ruido del propio equipo para despistar al rival. Tras una falta, el otro equipo lanza un penalti: un solo defensor contra el lanzador." },
      { h: "Cómo defender bien" },
      { p: "Cuando el rival va a lanzar, quédate agachado, quieto y en silencio, con las manos en el suelo para notar las vibraciones. En cuanto oigas los cascabeles, tírate de lado, con el cuerpo estirado y los brazos por encima de la cabeza, para tapar todo el espacio posible. Protege siempre la cara con los brazos y no te levantes hasta tener el balón bien sujeto. Los tres defensores se reparten la portería: uno en el centro, un poco adelantado, y los otros dos cubriendo los lados." },
      { h: "Para orientarse" },
      { p: "Como nadie ve, los jugadores se guían tocando las líneas de cinta y hablando entre ellos en voz baja antes de cada lanzamiento. Al principio cuesta, pero en pocos minutos el oído se vuelve sorprendentemente fino. Al acabar, muchos alumnos dicen lo mismo: «Nunca había escuchado tanto un partido»." },
    ],
    vocabulario: [
      { p: "paralímpico", d: "de los Juegos Paralímpicos, la gran competición de deportistas con discapacidad." },
      { p: "opaco", d: "que no deja pasar la luz." },
      { p: "inclusivo", d: "que tiene en cuenta a todas las personas para que nadie quede fuera." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Para quién se inventó el goalball y con qué objetivo?", r: "Para soldados que se habían quedado ciegos en la Segunda Guerra Mundial, para ayudarles a recuperar la forma física y la confianza.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el balón tiene que ir rodando o botando y nunca por el aire?", r: "Porque si va por el aire los cascabeles casi no suenan contra el suelo y los defensores no podrían oírlo ni pararlo con seguridad.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si el árbitro se saltara el paso de pedir silencio?", r: "El ruido taparía el sonido de los cascabeles y los jugadores no sabrían dónde está el balón.", lineas: 1 },
      { tipo: "texto", q: "Un reglamento es un texto instructivo con partes especiales. ¿En qué se diferencia de una receta? Pon un ejemplo del texto.", r: "Incluye normas y castigos, no solo pasos. Por ejemplo, las faltas: tocarse el antifaz se castiga con un penalti.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que los deportes adaptados deberían practicarse en todas las clases de Educación Física? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
      { tipo: "reflexion", q: "Muchos alumnos dicen: «Nunca había escuchado tanto un partido». ¿Qué crees que aprendieron sobre cómo viven el deporte las personas ciegas?", r: "Respuesta libre. Valorar la empatía y que mencione que usan otros sentidos con gran habilidad.", lineas: 2 },
    ],
  },
];
