// Lecturas · Textos instructivos (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["instructivo"] = [
  {
    id: "instructivo-01-semillas-en-un-vaso",
    titulo: "Un huerto en un vaso de yogur",
    subtipo: "Instrucciones de jardinería",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has plantado alguna vez una semilla? ¿Qué crees que necesita una planta para crecer?",
    texto: [
      { p: "No hace falta tener un gran jardín para ver crecer una planta. Con un vaso de yogur vacío, un poco de tierra y mucha paciencia, puedes montar tu propio huerto en la ventana. Estas instrucciones sirven para plantar semillas de lentejas, de judías o de albahaca, que germinan deprisa y son fáciles de cuidar." },
      { lista: [
        "Un vaso de yogur vacío y bien limpio.",
        "Un lápiz o un palillo para hacer agujeros.",
        "Tierra para macetas (sustrato).",
        "Tres o cuatro semillas.",
        "Un plato pequeño para poner debajo.",
        "Agua y una cuchara.",
        "Una etiqueta y un rotulador.",
      ], titulo: "Materiales" },
      { lista: [
        "En primer lugar, pide a un adulto que haga dos o tres agujeritos en el fondo del vaso con la punta de un lápiz. Así el agua que sobre podrá salir y las raíces no se pudrirán.",
        "A continuación, llena el vaso de tierra hasta dos dedos por debajo del borde. No la aprietes demasiado: las raíces necesitan aire.",
        "Después, haz con el dedo tres hoyitos poco profundos, de un centímetro más o menos, y coloca una semilla en cada uno.",
        "Luego, cubre las semillas con una capa fina de tierra.",
        "Riega con dos o tres cucharadas de agua. La tierra debe quedar húmeda, pero no encharcada.",
        "Escribe en la etiqueta el nombre de la semilla y la fecha, y pégala en el vaso.",
        "Por último, coloca el vaso sobre el plato, cerca de una ventana con luz, pero sin sol muy fuerte.",
      ], ordenada: true, titulo: "Pasos" },
      { h: "Cuidados de cada día" },
      { p: "Toca la tierra cada mañana: si está seca, riégala con una cucharada de agua. En pocos días verás asomar un tallito verde. Cuando la planta tenga cuatro o cinco hojas, puedes pasarla a una maceta más grande. Si anotas cada día lo que mide en un cuaderno, tendrás además tu propio diario de científico." },
      { dato: "¿Sabías que las semillas guardan dentro el alimento que la planta necesita para sus primeros días? Por eso pueden brotar antes de tener hojas." },
    ],
    vocabulario: [
      { p: "germinar", d: "empezar a brotar una semilla." },
      { p: "sustrato", d: "tierra especial, con nutrientes, para plantas de maceta." },
      { p: "encharcada", d: "tan llena de agua que se forman charcos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tipo de semillas recomienda el texto y por qué?", r: "Lentejas, judías o albahaca, porque germinan deprisa y son fáciles de cuidar.", lineas: 2 },
      { tipo: "comprension", q: "Ordena estos pasos del 1 al 4: ☐ cubrir las semillas con tierra · ☐ hacer agujeros en el fondo del vaso · ☐ regar · ☐ llenar el vaso de tierra.", r: "1 hacer agujeros en el fondo, 2 llenar el vaso de tierra, 3 cubrir las semillas con tierra, 4 regar.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el primer paso y el vaso no tuviera agujeros?", r: "El agua sobrante no podría salir, la tierra se encharcaría y las raíces se pudrirían.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que hay que poner una etiqueta con el nombre y la fecha?", r: "Para saber qué se ha plantado y cuántos días tarda en brotar, sobre todo si hay varios vasos.", lineas: 2 },
      { tipo: "comprension", q: "Según el texto, la tierra debe quedar… Elige:", opciones: ["muy seca", "húmeda, pero no encharcada", "cubierta de agua"], r: "húmeda, pero no encharcada" },
      { tipo: "texto", q: "Copia dos conectores de orden del texto y dos verbos en imperativo.", r: "Conectores: en primer lugar, a continuación, después, luego, por último. Verbos: llena, haz, coloca, cubre, riega, escribe…", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría tener un huerto en clase? ¿Qué plantarías y quién lo cuidaría en vacaciones?", r: "Respuesta libre. Valorar que proponga un reparto de tareas.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que es mejor aprender cómo crece una planta leyendo el libro o cultivándola? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "reflexion", q: "Casi todo lo que comemos empieza siendo una semilla. ¿Qué pasaría si nadie supiera cultivar la tierra?", r: "Respuesta libre. Valorar que relacione la agricultura con la alimentación.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-02-normas-biblioteca",
    titulo: "Normas de la biblioteca Las Mil Páginas",
    subtipo: "Normas de uso",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Hay biblioteca en tu colegio o en tu barrio? ¿Qué normas crees que tiene y para qué sirven?",
    texto: [
      { p: "La biblioteca de nuestro colegio se llama Las Mil Páginas, aunque en realidad tiene más de tres mil libros. Es un lugar de todos, y para que todo el mundo pueda leer, buscar información y disfrutar, el equipo de bibliotecarios de sexto ha preparado estas normas. Léelas con atención antes de tu primera visita." },
      { lista: [
        "Entrar en silencio o hablando en voz muy baja.",
        "Lavarse las manos antes de tocar los libros si vienes del recreo.",
        "Dejar mochilas y abrigos en las perchas de la entrada.",
        "No comer ni beber dentro de la sala.",
      ], titulo: "Al llegar" },
      { lista: [
        "Buscar el libro por el color de su etiqueta: verde para cuentos, azul para ciencia, naranja para cómics y rojo para poesía.",
        "Sacar el libro con cuidado, tirando del lomo por el centro y no por arriba.",
        "Si decides no llevártelo, dejarlo en el carrito gris. El equipo de bibliotecarios lo colocará en su sitio.",
        "Pasar las páginas por la esquina, sin mojar el dedo.",
      ], titulo: "Para elegir un libro" },
      { lista: [
        "En primer lugar, llevar el libro y el carné de lector al mostrador.",
        "A continuación, esperar a que anoten el título y la fecha.",
        "Después, guardar el libro en una bolsa para que no se estropee en la mochila.",
        "Por último, devolverlo en un plazo de dos semanas. Si no lo has terminado, puedes pedir una semana más.",
      ], ordenada: true, titulo: "Para llevarte un libro prestado" },
      { p: "Si un libro se rompe, no intentes arreglarlo con celo. Avisa en el mostrador: tenemos un botiquín de libros con cinta especial. Nadie se va a enfadar por un accidente, pero sí por esconderlo." },
      { cita: "Un libro cuidado hoy es un libro que leerá otro niño mañana." },
    ],
    vocabulario: [
      { p: "lomo", d: "parte del libro donde están cosidas o pegadas las hojas." },
      { p: "carné de lector", d: "tarjeta que te permite llevarte libros prestados." },
      { p: "plazo", d: "tiempo que tienes para hacer algo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién ha escrito estas normas y con qué objetivo?", r: "El equipo de bibliotecarios de sexto, para que todo el mundo pueda leer, buscar información y disfrutar de la biblioteca.", lineas: 2 },
      { tipo: "comprension", q: "Si buscas un libro sobre los planetas, ¿de qué color será su etiqueta?", r: "Azul, porque es un libro de ciencia.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que no hay que colocar tú mismo el libro en la estantería?", r: "Porque podría quedar en un sitio equivocado y luego nadie lo encontraría. El equipo lo coloca en su lugar correcto.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el segundo paso del préstamo y no anotaran el libro?", r: "La biblioteca no sabría quién lo tiene ni cuándo debe devolverse; el libro podría perderse.", lineas: 2 },
      { tipo: "comprension", q: "La frase «Nadie se va a enfadar por un accidente, pero sí por esconderlo» quiere decir que… Elige:", opciones: ["romper un libro está prohibido", "lo importante es decir la verdad cuando algo se estropea", "los libros rotos se tiran"], r: "lo importante es decir la verdad cuando algo se estropea" },
      { tipo: "texto", q: "En este texto los verbos de las normas están en infinitivo (entrar, dejar…). Escribe dos normas cambiando el verbo a imperativo.", r: "Por ejemplo: Entra en silencio. Deja la mochila en la percha. No comas ni bebas.", lineas: 2 },
      { tipo: "opinion", q: "¿Cuál de estas normas te parece más importante? ¿Por qué?", r: "Respuesta libre. Valorar que justifique.", lineas: 3 },
      { tipo: "opinion", q: "¿Te gustaría formar parte del equipo de bibliotecarios? ¿Qué norma nueva añadirías?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante que existan bibliotecas públicas y gratuitas?", r: "Respuesta libre. Valorar que mencione que todo el mundo pueda leer aunque no pueda comprar libros.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-03-comba-barca",
    titulo: "Al pasar la barca: cómo jugar a la comba",
    subtipo: "Instrucciones de un juego popular",
    curso: "5º",
    fuente: "Texto original (la canción es popular)",
    antes: "¿Conoces algún juego de comba? ¿Recuerdas alguna canción que se cante mientras se salta?",
    texto: [
      { p: "La comba es uno de los juegos de patio más antiguos. En los recreos de muchos colegios de Andalucía se sigue oyendo el golpeteo de la cuerda contra el suelo y las canciones que marcan el ritmo. Aquí tienes las instrucciones para jugar a una de las más conocidas: «Al pasar la barca»." },
      { lista: [
        "Una cuerda larga, de unos cuatro o cinco metros.",
        "Un espacio llano y sin obstáculos.",
        "Un grupo de cuatro jugadores o más.",
      ], titulo: "Materiales" },
      { lista: [
        "Primero, elegid a dos personas para que den a la comba. Cada una se coloca en un extremo, sujetando la cuerda con firmeza.",
        "Después, las que dan empiezan a mover la cuerda formando un arco, siempre al mismo ritmo y en el mismo sentido.",
        "A continuación, el resto forma una fila a un lado. La primera jugadora espera a que la cuerda toque el suelo y entra saltando.",
        "Mientras salta, todo el grupo canta: «Al pasar la barca, me dijo el barquero: las niñas bonitas no pagan dinero».",
        "Luego, cuando la canción termina, la saltadora sale de la cuerda sin tocarla y se coloca al final de la fila.",
        "Por último, entra la siguiente persona de la fila y se repite la canción.",
      ], ordenada: true, titulo: "Cómo se juega" },
      { h: "Normas importantes" },
      { p: "Si alguien pisa la cuerda o se enreda, pasa a dar a la comba y la persona que daba se une a la fila. Así todos saltan y todos dan. Quien da a la comba debe hacerlo despacio con los más pequeños y más rápido con quien lo pida. Nunca se tira de la cuerda de golpe para hacer caer a nadie." },
      { p: "Cuando ya domines el juego, podéis inventar vuestra propia versión de la canción. En muchos patios, por ejemplo, se cambia la letra para que diga «los niños y niñas no pagan dinero», y así la canción es de todos." },
    ],
    vocabulario: [
      { p: "extremo", d: "cada una de las puntas de algo alargado." },
      { p: "obstáculo", d: "algo que estorba el paso." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántas personas hacen falta como mínimo y qué papeles hay en el juego?", r: "Cuatro o más: dos dan a la comba y las demás saltan por turnos.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué ocurre si alguien pisa la cuerda?", r: "Pasa a dar a la comba y quien daba se une a la fila.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que hay que esperar a que la cuerda toque el suelo para entrar?", r: "Porque en ese momento la cuerda está abajo y hay espacio para entrar sin que te golpee ni te enrede.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si las personas que dan cambiaran de ritmo sin avisar?", r: "La saltadora perdería el ritmo, pisaría la cuerda o se enredaría.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el texto propone cambiar la letra de la canción? Elige:", opciones: ["Porque es muy larga", "Para que la canción incluya a todos", "Porque la original no rima"], r: "Para que la canción incluya a todos" },
      { tipo: "texto", q: "¿Qué tres partes tiene este texto instructivo? ¿Qué parte cambiarías de sitio si quisieras que las normas se leyeran antes de jugar?", r: "Materiales, pasos (cómo se juega) y normas. Colocaría las normas antes de los pasos.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que la norma de que quien falla pasa a dar a la comba es justa? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué juego de patio te gustaría enseñar a tus compañeros? ¿Cuál sería su norma más importante?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Estos juegos pasan de unos niños a otros sin estar escritos. ¿Por qué crees que es bueno escribirlos?", r: "Respuesta libre. Valorar que hable de conservar la tradición y enseñar a otros.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-04-salmorejo",
    titulo: "Salmorejo cordobés para cuatro personas",
    subtipo: "Receta",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has probado el salmorejo? ¿Qué platos típicos de tu pueblo o ciudad sabrías preparar?",
    texto: [
      { p: "El salmorejo es una crema fría de tomate y pan muy típica de Córdoba. Es perfecto para los días de calor y no necesita horno ni fuego. Eso sí: en esta receta hay dos tareas que solo puede hacer un adulto, porque hay que usar un cuchillo y una batidora. Las verás marcadas con la palabra ADULTO." },
      { lista: [
        "1 kilo de tomates rojos y bien maduros.",
        "200 gramos de pan del día anterior.",
        "Medio diente de ajo (si os gusta).",
        "100 mililitros de aceite de oliva virgen extra.",
        "Una pizca de sal.",
        "Para decorar: un huevo duro y unos taquitos de jamón.",
      ], titulo: "Ingredientes" },
      { lista: [
        "Lavar bien los tomates con agua fría y secarlos con un paño.",
        "ADULTO: cortar los tomates en cuartos y quitarles la parte dura del tallo.",
        "Trocear el pan con las manos en pedazos pequeños.",
        "Poner los tomates en un recipiente alto. ADULTO: triturarlos con la batidora hasta que quede un líquido sin grumos.",
        "Añadir el pan y el ajo, y dejarlo reposar diez minutos para que el pan se empape.",
        "ADULTO: volver a batir mientras el ayudante echa el aceite poco a poco, en un chorro muy fino. La crema se volverá más espesa y de color anaranjado.",
        "Añadir la sal, probar y remover.",
        "Guardar el salmorejo en el frigorífico al menos una hora.",
        "Servirlo en cuencos y decorarlo con el huevo duro picado y el jamón.",
      ], ordenada: true, titulo: "Preparación" },
      { h: "Trucos de la cocina" },
      { p: "Cuanto más maduros estén los tomates, más sabroso quedará. Si la crema está muy espesa, se puede añadir un poco de agua fría; si está muy líquida, un poco más de pan. Para una versión vegetariana, basta con no poner jamón. Y recuerda: antes de empezar, lávate las manos y recoge el pelo si lo llevas largo." },
    ],
    vocabulario: [
      { p: "triturar", d: "deshacer algo en trozos muy pequeños hasta que queda como un puré." },
      { p: "grumo", d: "bolita que se forma en una crema cuando no está bien mezclada." },
      { p: "empaparse", d: "llenarse de líquido." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tareas de la receta debe hacer un adulto y por qué?", r: "Cortar los tomates y usar la batidora, porque se usan un cuchillo y un aparato eléctrico que pueden ser peligrosos.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que la receta pide pan del día anterior y no pan recién hecho?", r: "Porque el pan duro absorbe mejor el tomate y da una crema más espesa. (Se valora cualquier inferencia razonable).", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el paso de dejar reposar el pan diez minutos?", r: "El pan no se empaparía bien y el salmorejo quedaría con trozos o grumos.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué harías si el salmorejo te queda demasiado líquido? Elige:", opciones: ["Añadir agua fría", "Añadir un poco más de pan", "Meterlo en el horno"], r: "Añadir un poco más de pan" },
      { tipo: "comprension", q: "¿Cuál es el último paso antes de decorar el salmorejo?", r: "Guardarlo en el frigorífico al menos una hora.", lineas: 1 },
      { tipo: "texto", q: "Los pasos de esta receta están escritos en infinitivo. Reescribe el primer paso en imperativo y añádele un conector de orden.", r: "En primer lugar, lava bien los tomates con agua fría y sécalos con un paño.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es importante que los niños ayuden en la cocina? ¿Qué tareas podrían hacer sin peligro?", r: "Respuesta libre. Valorar que distinga tareas seguras.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué plato típico de tu familia te gustaría aprender a preparar? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "El salmorejo nació como una comida sencilla, hecha con lo que había en casa. ¿Por qué crees que se aprovechaba el pan duro? ¿Se hace eso hoy?", r: "Respuesta libre. Valorar que hable de no desperdiciar comida.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-05-comedero-pajaros",
    titulo: "Un comedero para los pájaros del patio",
    subtipo: "Instrucciones de manualidad",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Qué pájaros ves en tu calle o en el patio del colegio? ¿Cómo crees que encuentran comida en invierno?",
    texto: [
      { p: "Gorriones, verdecillos, jilgueros y carboneros viven muy cerca de nosotros, pero en invierno les cuesta encontrar semillas e insectos. Con un brick de leche vacío puedes construir un comedero y observar de cerca a tus vecinos con plumas. Este proyecto se hace en equipo y con un adulto que se encargue de los cortes." },
      { lista: [
        "Un brick de leche o de zumo vacío, lavado y seco.",
        "Tijeras (solo para el adulto).",
        "Un palito de unos quince centímetros.",
        "Un cordel resistente de un metro.",
        "Pintura y pinceles (opcional).",
        "Alpiste o una mezcla de semillas para pájaros.",
      ], titulo: "Materiales" },
      { lista: [
        "Primero, lava el brick por dentro y déjalo secar un día entero. Si queda húmedo, las semillas se llenarán de moho.",
        "Después, dibuja con un rotulador una ventana en dos lados opuestos del brick, a unos cinco centímetros de la base.",
        "A continuación, el adulto recorta las ventanas con las tijeras. Tienen que ser lo bastante grandes para que un pájaro meta la cabeza.",
        "Luego, el adulto hace un agujero pequeño debajo de cada ventana. Mete el palito por los dos agujeros: servirá de posadero.",
        "Si quieres, pinta el comedero con colores naturales, como verdes y marrones. Espera a que se seque.",
        "Después, pasa el cordel por la parte de arriba del brick y haz un nudo fuerte.",
        "Por último, llena la base con semillas y cuelga el comedero de una rama, a más de metro y medio del suelo.",
      ], ordenada: true, titulo: "Pasos" },
      { h: "Consejos para observar" },
      { p: "Cuelga el comedero lejos de lugares donde puedan esconderse los gatos. Los pájaros tardarán unos días en confiar en él, así que ten paciencia. Observa desde lejos y en silencio, y apunta en un cuaderno qué especies vienen y a qué hora. Cambia las semillas cada semana y limpia el comedero para que no enfermen. En primavera, cuando haya comida de sobra en el campo, puedes retirarlo." },
    ],
    vocabulario: [
      { p: "posadero", d: "palo o lugar donde se posan los pájaros." },
      { p: "moho", d: "capa de hongos que sale en la comida húmeda o estropeada." },
      { p: "alpiste", d: "semilla pequeña que se da de comer a los pájaros." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Para qué sirve el palito que se mete por los agujeros?", r: "Sirve de posadero: los pájaros se apoyan en él para comer.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el primer paso y no dejaras secar el brick?", r: "La humedad haría que las semillas se llenaran de moho.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que hay que colgar el comedero a más de metro y medio y lejos de donde se esconden los gatos?", r: "Para que los gatos no puedan cazar a los pájaros mientras comen.", lineas: 2 },
      { tipo: "comprension", q: "Ordena: ☐ colgar el comedero · ☐ recortar las ventanas · ☐ pintar · ☐ dibujar las ventanas.", r: "1 dibujar las ventanas, 2 recortar las ventanas, 3 pintar, 4 colgar el comedero.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué el texto aconseja retirar el comedero en primavera? Elige:", opciones: ["Porque los pájaros se van de vacaciones", "Porque en el campo ya hay comida suficiente", "Porque el brick se derrite"], r: "Porque en el campo ya hay comida suficiente" },
      { tipo: "texto", q: "Además de los pasos, este texto tiene una parte de consejos. ¿Por qué crees que el autor la ha separado de los pasos? Copia un verbo en imperativo de esa parte.", r: "Porque no son pasos para construir el comedero, sino recomendaciones para después. Verbos: cuelga, observa, apunta, cambia, limpia.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es buena idea dar de comer a los animales salvajes? ¿Siempre o solo a veces? Explica por qué.", r: "Respuesta libre. Valorar que matice (solo en invierno, sin pan ni restos de comida humana…).", lineas: 3 },
      { tipo: "opinion", q: "Si pusierais un comedero en clase, ¿cómo os organizaríais para cuidarlo?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Reutilizar un brick es una forma de cuidar el planeta. ¿Qué otros objetos que tiramos podrían tener una segunda vida?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-06-origami-vaso",
    titulo: "Un vaso de papel sin pegamento",
    subtipo: "Instrucciones de origami",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Sabes qué es el origami? ¿Has hecho alguna vez una figura de papel doblado, como un barco o una pajarita?",
    texto: [
      { p: "El origami es el arte de hacer figuras doblando papel, sin tijeras ni pegamento. Nació en Japón hace siglos, y en España tenemos nuestra propia figura estrella: la pajarita. Hoy empezaremos por algo más sencillo y útil: un vaso de papel que, si está bien doblado, aguanta un poco de agua durante un rato. Lee todos los pasos antes de empezar y dobla sobre una mesa dura." },
      { lista: [
        "Una hoja cuadrada de papel de unos 20 centímetros de lado. Si solo tienes un folio, pide ayuda para cortar la tira que sobra.",
        "Una mesa lisa.",
        "Paciencia y uñas para marcar bien los pliegues.",
      ], titulo: "Materiales" },
      { lista: [
        "En primer lugar, coloca el cuadrado como si fuera un rombo, con una punta hacia ti.",
        "Dobla la hoja por la mitad llevando la punta de abajo hasta la de arriba. Tendrás un triángulo con el lado largo abajo. Marca bien el pliegue.",
        "A continuación, dobla la punta derecha del triángulo hacia la izquierda, de forma que toque el borde izquierdo. El borde de arriba de esa solapa debe quedar recto, horizontal.",
        "Después, haz lo mismo con la punta izquierda: llévala hacia la derecha, por encima de la anterior, hasta que toque el borde contrario.",
        "Ahora, arriba quedan dos puntas sueltas. Baja la primera hacia ti, metiéndola dentro de la solapa delantera.",
        "Da la vuelta a la figura y baja la otra punta hacia el otro lado.",
        "Finalmente, aprieta suavemente los laterales para abrir la boca del vaso.",
      ], ordenada: true, titulo: "Pasos" },
      { p: "Si el vaso queda torcido, seguramente el paso tres no está bien hecho: el borde de la solapa debe quedar paralelo a la mesa. Desdobla hasta ese punto y vuelve a intentarlo. Con papel de periódico puedes hacer vasos grandes para guardar lápices; con papel de colores, pequeños cestitos para una fiesta." },
      { dato: "¿Sabías que en muchos museos y congresos de ciencia se estudia el origami? Sus pliegues se han usado para diseñar objetos que deben plegarse y desplegarse, como algunos paneles de satélites." },
    ],
    vocabulario: [
      { p: "pliegue", d: "señal que queda en el papel al doblarlo." },
      { p: "solapa", d: "parte doblada que queda encima de otra." },
      { p: "paralelo", d: "que va en la misma dirección que otra línea, sin tocarla nunca." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué dos reglas tiene el origami, según el texto?", r: "No se usan tijeras ni pegamento: solo se dobla papel.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué forma tiene el papel después del segundo paso?", r: "Un triángulo con el lado largo abajo.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué ocurre si el paso tres no se hace bien? ¿Cómo se soluciona?", r: "El vaso queda torcido. Hay que desdoblar hasta ese paso y repetirlo dejando el borde paralelo a la mesa.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el texto recomienda leer todos los pasos antes de empezar?", r: "Para entender el proceso completo y no equivocarse: en origami un error en un paso estropea los siguientes.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué hay que hacer justo después de bajar la primera punta? Elige:", opciones: ["Abrir la boca del vaso", "Dar la vuelta a la figura y bajar la otra punta", "Doblar el triángulo por la mitad"], r: "Dar la vuelta a la figura y bajar la otra punta" },
      { tipo: "texto", q: "En instrucciones de manualidades, las palabras que indican posición son muy importantes. Copia cuatro del texto (por ejemplo: arriba…). ¿Por qué son necesarias?", r: "Abajo, arriba, derecha, izquierda, hacia ti, encima, dentro… Son necesarias para que el lector sepa exactamente dónde doblar.", lineas: 2 },
      { tipo: "opinion", q: "¿Te resulta más fácil aprender a hacer algo leyendo instrucciones, viendo dibujos o viendo a alguien hacerlo? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué dibujo añadirías a este texto para que se entendiera mejor? Descríbelo.", r: "Respuesta libre. Valorar que elija un paso difícil (por ejemplo, el tres).", lineas: 2 },
      { tipo: "reflexion", q: "Un vaso de papel se estropea pronto y los de plástico duran siglos en la naturaleza. ¿Qué vaso usarías en una excursión? ¿Por qué?", r: "Respuesta libre. Valorar que proponga un vaso reutilizable y argumente.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-07-volcan-bicarbonato",
    titulo: "Experimento: un volcán en la mesa de la cocina",
    subtipo: "Experimento científico",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Qué es una reacción química? ¿Has visto alguna vez algo que hace burbujas al mezclarlo?",
    texto: [
      { p: "Los volcanes de verdad expulsan lava que sale a más de mil grados. El nuestro será mucho más tranquilo: una espuma fría que brota por una reacción química entre dos productos que hay en casi todas las cocinas. Es un experimento seguro, pero hazlo con un adulto y sigue todas las normas." },
      { lista: [
        "Una botella pequeña de plástico vacía.",
        "Una bandeja grande o un barreño.",
        "Plastilina o papel de periódico y cinta adhesiva para modelar la montaña.",
        "Dos cucharadas de bicarbonato de sodio.",
        "Medio vaso de vinagre.",
        "Un chorrito de lavavajillas y unas gotas de colorante alimentario rojo.",
        "Un embudo y gafas protectoras.",
      ], titulo: "Materiales" },
      { lista: [
        "Primero, ponte las gafas y coloca la botella en el centro de la bandeja.",
        "A continuación, modela una montaña alrededor de la botella con plastilina o periódico, dejando libre la boca.",
        "Después, con ayuda del embudo, echa el bicarbonato dentro de la botella.",
        "Luego, mezcla en un vaso el vinagre, el lavavajillas y el colorante.",
        "Pide a todos que se aparten un paso. Entonces, vierte la mezcla del vaso de golpe dentro de la botella y retira la mano.",
        "Por último, observa lo que ocurre y anota en tu cuaderno cuánto tiempo dura la erupción.",
      ], ordenada: true, titulo: "Procedimiento" },
      { h: "¿Qué ha pasado?" },
      { p: "El vinagre es un ácido y el bicarbonato es una base. Al juntarse, reaccionan y producen un gas llamado dióxido de carbono. Las burbujas de gas empujan el líquido hacia arriba y el lavavajillas las atrapa, formando una espuma que se desborda como si fuera lava." },
      { h: "Normas de seguridad" },
      { p: "No pruebes ninguna de las mezclas. Si te salpica en los ojos, lávalos con mucha agua y avisa a un adulto. Al terminar, tira los restos por el fregadero con abundante agua y lávate las manos." },
      { p: "¿Quieres investigar más? Repite el experimento cambiando una sola cosa cada vez: más bicarbonato, vinagre templado, una botella más estrecha… y compara los resultados." },
    ],
    vocabulario: [
      { p: "reacción química", d: "cambio en el que unas sustancias se transforman en otras distintas." },
      { p: "erupción", d: "salida violenta de materia de un volcán." },
      { p: "desbordarse", d: "salirse un líquido por encima del borde." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué gas se produce en la reacción y qué papel tiene el lavavajillas?", r: "Dióxido de carbono. El lavavajillas atrapa las burbujas y forma la espuma.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué se diferencia la lava del volcán del experimento de la lava de un volcán real?", r: "La del experimento es una espuma fría; la real sale a más de mil grados.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el paso de dejar libre la boca de la botella al modelar la montaña?", r: "No se podría echar el bicarbonato ni el vinagre, o la espuma no tendría por dónde salir.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que hay que poner la botella sobre una bandeja?", r: "Porque la espuma se desborda y así no se mancha la mesa ni el suelo.", lineas: 1 },
      { tipo: "comprension", q: "Para investigar bien, el texto aconseja… Elige:", opciones: ["cambiar todo a la vez", "cambiar una sola cosa cada vez", "no repetir nunca el experimento"], r: "cambiar una sola cosa cada vez" },
      { tipo: "texto", q: "Este texto tiene más partes que una receta. Nómbralas en orden y explica para qué sirve la parte «¿Qué ha pasado?».", r: "Introducción, materiales, procedimiento, explicación (¿Qué ha pasado?), normas de seguridad y propuesta final. La explicación dice por qué ocurre la reacción.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que las normas de seguridad deberían ir al principio del texto y no casi al final? ¿Por qué?", r: "Respuesta libre. Valorar que argumente (por ejemplo, conviene leerlas antes de empezar).", lineas: 3 },
      { tipo: "opinion", q: "Si pudieras cambiar una sola cosa del experimento, ¿cuál cambiarías y qué crees que pasaría?", r: "Respuesta libre. Valorar que formule una hipótesis.", lineas: 2 },
      { tipo: "reflexion", q: "Los científicos repiten sus experimentos muchas veces antes de dar un resultado por bueno. ¿Por qué crees que lo hacen?", r: "Respuesta libre. Valorar que hable de comprobar y evitar errores o casualidades.", lineas: 3 },
    ],
  },
  {
    id: "instructivo-08-brujula-grazalema",
    titulo: "Cómo usar una brújula en la Sierra de Grazalema",
    subtipo: "Instrucciones de uso de un objeto",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Cómo te orientarías si te perdieras en el campo sin móvil? ¿Qué es el norte?",
    texto: [
      { p: "La próxima semana, los alumnos de sexto haremos una ruta de senderismo por la Sierra de Grazalema, en la provincia de Cádiz, para visitar un bosque de pinsapos, un abeto que en España solo crece de forma natural en unas pocas sierras andaluzas. Iremos con guías y monitores, pero cada equipo llevará una brújula y un mapa. Estas instrucciones explican cómo usarla." },
      { h: "Partes de la brújula" },
      { lista: [
        "Base transparente: la placa de plástico sobre la que va todo. Tiene una flecha grabada, la flecha de dirección.",
        "Aguja magnética: flota dentro de una cápsula con líquido. Su punta roja señala siempre el norte magnético.",
        "Limbo: el anillo que gira alrededor de la cápsula, con las letras N, S, E y O.",
      ], titulo: "Partes" },
      { lista: [
        "En primer lugar, aléjate un par de metros de objetos de metal, del móvil y de los imanes de la mochila, porque desvían la aguja.",
        "A continuación, coloca la brújula plana sobre la palma de la mano, a la altura del pecho, con la flecha de dirección apuntando hacia delante.",
        "Espera a que la aguja deje de moverse. Su punta roja señala el norte.",
        "Después, gira el limbo hasta que la N quede justo encima de la punta roja de la aguja.",
        "Para orientar el mapa, ponlo sobre el suelo o una piedra plana, con la brújula encima. Gira el mapa, no la brújula, hasta que el norte del mapa mire hacia donde apunta la aguja.",
        "Por último, busca en el mapa dónde estás y hacia dónde quieres ir. Ahora el mapa y el paisaje coinciden.",
      ], ordenada: true, titulo: "Cómo orientarse" },
      { h: "Cuidados y recuerda" },
      { p: "No dejes la brújula al sol mucho tiempo ni cerca de altavoces. Guárdala en su funda. Y lo más importante: la brújula ayuda, pero no sustituye al sentido común. Si tu equipo duda del camino, no sigáis adelante: parad en un lugar seguro, avisad al monitor con el silbato y esperad juntos." },
    ],
    vocabulario: [
      { p: "pinsapo", d: "árbol de la familia de los abetos, propio de algunas sierras de Andalucía." },
      { p: "norte magnético", d: "punto hacia el que apuntan las agujas de las brújulas." },
      { p: "desviar", d: "hacer que algo cambie de dirección." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué hay que alejarse del móvil y de los objetos de metal antes de usar la brújula?", r: "Porque desvían la aguja y la lectura sería incorrecta.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué parte de la brújula gira y qué parte señala el norte?", r: "Gira el limbo; el norte lo señala la punta roja de la aguja.", lineas: 2 },
      { tipo: "comprension", q: "En el paso cinco, ¿qué se gira: el mapa o la brújula? ¿Por qué crees que es así?", r: "El mapa. La aguja siempre apunta al norte, así que hay que mover el mapa para que coincida con ella.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si te saltaras el tercer paso y no esperaras a que la aguja se quedara quieta?", r: "Leerías una dirección equivocada y podrías orientar mal el mapa y perderte.", lineas: 2 },
      { tipo: "comprension", q: "Si el equipo duda del camino, el texto dice que hay que… Elige:", opciones: ["separarse para buscar el camino", "parar, avisar con el silbato y esperar juntos", "seguir hacia el norte"], r: "parar, avisar con el silbato y esperar juntos" },
      { tipo: "texto", q: "Este texto describe primero las partes del objeto y después da los pasos. ¿Por qué crees que está organizado así?", r: "Porque para entender los pasos hay que saber antes cómo se llama cada parte (limbo, aguja, flecha de dirección).", lineas: 2 },
      { tipo: "opinion", q: "Hoy casi todo el mundo usa el móvil para orientarse. ¿Crees que sigue siendo útil aprender a usar una brújula? ¿Por qué?", r: "Respuesta libre. Valorar que piense en la batería, la cobertura, etc.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué otras normas añadirías para una excursión segura a la sierra?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Los pinsapos solo crecen de forma natural en unos pocos lugares. ¿Qué responsabilidades tenemos cuando visitamos un espacio natural protegido?", r: "Respuesta libre. Valorar que mencione no salirse de los senderos, no dejar basura, no arrancar plantas…", lineas: 3 },
    ],
  },
  {
    id: "instructivo-09-plan-evacuacion",
    titulo: "Suena la alarma: plan de evacuación del colegio",
    subtipo: "Protocolo de seguridad",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Habéis hecho alguna vez un simulacro en el colegio? ¿Qué recuerdas de lo que hicisteis?",
    texto: [
      { p: "Un simulacro es un ensayo de lo que haríamos ante una emergencia de verdad, como un incendio o un terremoto. Nuestro colegio, en Granada, hace uno cada trimestre. Algunos alumnos lo ven como un rato divertido fuera de clase, pero su objetivo es muy serio: que todas las personas del edificio salgan en orden, deprisa y sin hacerse daño. Cada clase tiene este protocolo pegado junto a la puerta." },
      { h: "Encargos de cada clase" },
      { lista: [
        "Responsable de cabeza: va el primero de la fila y sigue las flechas verdes.",
        "Responsable de cola: va el último y comprueba que nadie se queda atrás.",
        "Responsable de ventanas: cierra las ventanas antes de salir.",
        "La maestra o el maestro: coge la lista de clase, cierra la puerta sin llave y sale el último.",
      ], titulo: "Funciones" },
      { lista: [
        "Al oír la alarma (un timbre largo y repetido), deja inmediatamente lo que estés haciendo.",
        "No recojas la mochila ni el abrigo. Las cosas se pueden recuperar; el tiempo, no.",
        "Colócate en fila junto a la puerta, en silencio, para poder oír las indicaciones.",
        "Sal detrás del responsable de cabeza, caminando rápido pero sin correr ni empujar.",
        "Baja las escaleras pegado a la pared, agarrado a la barandilla. No uses nunca el ascensor.",
        "Si encuentras humo en el camino, agáchate y avanza cerca del suelo, donde el aire está más limpio.",
        "Sigue las flechas verdes hasta el punto de encuentro: la pista deportiva.",
        "Allí, espera en fila mientras el maestro pasa lista. No vuelvas atrás por ningún motivo.",
      ], ordenada: true, titulo: "Qué hacer" },
      { h: "¿Y si estoy en el baño o en otra clase?" },
      { p: "Si la alarma te pilla fuera de tu aula, no vayas a buscar a tu grupo. Únete a la fila más cercana y sal con ella. En el punto de encuentro, díselo a un adulto para que avise a tu maestro, que te estará buscando en su lista." },
      { p: "Después de cada simulacro, cada clase comenta qué ha salido bien y qué hay que mejorar. El último, por ejemplo, tardamos cuatro minutos en salir; el objetivo para el próximo es bajar de tres." },
    ],
    vocabulario: [
      { p: "evacuación", d: "salida ordenada de las personas de un lugar peligroso." },
      { p: "simulacro", d: "ensayo de lo que se haría en una situación real." },
      { p: "protocolo", d: "conjunto de pasos que se siguen siempre en una situación concreta." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué es un simulacro y cuál es su objetivo?", r: "Un ensayo de lo que se haría en una emergencia real. Su objetivo es que todos salgan en orden, deprisa y sin hacerse daño.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el maestro coge la lista de clase antes de salir?", r: "Para pasar lista en el punto de encuentro y comprobar que no falta nadie.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si alguien se saltara el paso dos y se entretuviera recogiendo la mochila?", r: "Retrasaría a toda la fila y podría quedarse atrás en una emergencia real.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué hay que ir en silencio, según el texto?", r: "Para poder oír las indicaciones.", lineas: 1 },
      { tipo: "comprension", q: "Si la alarma suena mientras estás en el baño, debes… Elige:", opciones: ["volver a tu clase a buscar a tu grupo", "unirte a la fila más cercana y avisar en el punto de encuentro", "esperar en el baño"], r: "unirte a la fila más cercana y avisar en el punto de encuentro" },
      { tipo: "texto", q: "En un protocolo el orden de los pasos es fundamental. Explica por qué no se podrían cambiar de orden los pasos 7 y 8.", r: "Porque primero hay que llegar al punto de encuentro y solo allí se puede esperar en fila y pasar lista.", lineas: 2 },
      { tipo: "opinion", q: "Algunos alumnos ven el simulacro como un juego. ¿Qué les dirías para que se lo tomaran en serio?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué función te gustaría tener en tu clase durante un simulacro? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Cómo adaptarías este plan para que un compañero en silla de ruedas o con dificultades para oír la alarma pudiera salir igual de seguro?", r: "Respuesta libre. Valorar propuestas como un compañero de apoyo, señales luminosas, rutas sin escaleras…", lineas: 3 },
    ],
  },
  {
    id: "instructivo-10-goalball",
    titulo: "Goalball: el deporte que se juega con los oídos",
    subtipo: "Reglamento de un deporte adaptado",
    curso: "6º",
    fuente: "Texto original (reglas simplificadas para el colegio)",
    antes: "¿Qué deportes conoces que practiquen personas con discapacidad? ¿Has jugado alguna vez con los ojos tapados?",
    texto: [
      { p: "El goalball es un deporte paralímpico creado para personas ciegas o con poca visión. Se juega por equipos, con un balón que lleva cascabeles dentro, y todos los jugadores llevan los ojos tapados. Así nadie tiene ventaja: el partido se gana escuchando. En nuestro colegio lo jugamos en la semana del deporte inclusivo con estas reglas adaptadas." },
      { lista: [
        "Un balón con cascabeles (en el cole usamos uno de goma con cascabeles dentro de una bolsa de red).",
        "Antifaces opacos para todos los jugadores.",
        "Cinta adhesiva gruesa para marcar las líneas en el suelo, de modo que se puedan notar con los dedos.",
        "Dos porterías que ocupen todo el ancho de la pista (valen dos bancos tumbados o conos unidos con cuerda).",
        "Rodilleras y coderas.",
      ], titulo: "Material" },
      { lista: [
        "Formad dos equipos de tres jugadores. Cada equipo se coloca delante de su portería.",
        "Antes de empezar, todos se ponen el antifaz. A partir de ese momento, nadie puede tocárselo.",
        "El árbitro dice «¡Silencio!» y después «¡Juego!». El público debe estar callado mientras el balón rueda.",
        "El equipo que saca lanza el balón rodando o botando por el suelo, nunca por el aire, intentando meterlo en la portería contraria.",
        "Los defensores escuchan los cascabeles y se tumban de lado en el suelo para parar el balón con el cuerpo.",
        "Quien para el balón tiene diez segundos para lanzarlo de nuevo.",
        "Cada balón que cruza la línea de portería es un gol. Gana el equipo que marque más goles en dos partes de cinco minutos.",
      ], ordenada: true, titulo: "Cómo se juega" },
      { h: "Faltas" },
      { p: "Es falta tocarse el antifaz, tardar más de diez segundos en lanzar o lanzar el balón por el aire. También se castiga el ruido del propio equipo para despistar al rival. Tras una falta, el otro equipo lanza un penalti: un solo defensor contra el lanzador." },
      { h: "Para orientarse" },
      { p: "Como nadie ve, los jugadores se guían tocando las líneas de cinta y hablando entre ellos en voz baja antes de cada lanzamiento. Al principio cuesta, pero en pocos minutos el oído se vuelve sorprendentemente fino. Al acabar, muchos alumnos dicen lo mismo: «Nunca había escuchado tanto un partido»." },
      { dato: "¿Sabías que el goalball forma parte de los Juegos Paralímpicos? En él compiten deportistas con discapacidad visual de todo el mundo." },
    ],
    vocabulario: [
      { p: "paralímpico", d: "de los Juegos Paralímpicos, la gran competición de deportistas con discapacidad." },
      { p: "opaco", d: "que no deja pasar la luz." },
      { p: "inclusivo", d: "que tiene en cuenta a todas las personas para que nadie quede fuera." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué todos los jugadores llevan los ojos tapados, aunque algunos vean bien?", r: "Para que nadie tenga ventaja: todos juegan en las mismas condiciones, escuchando.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el balón tiene que ir rodando o botando y nunca por el aire?", r: "Porque si va por el aire los cascabeles casi no suenan contra el suelo y los defensores no podrían oírlo ni pararlo con seguridad.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pasaría si el árbitro se saltara el paso de pedir silencio?", r: "El ruido taparía el sonido de los cascabeles y los jugadores no sabrían dónde está el balón.", lineas: 2 },
      { tipo: "comprension", q: "¿Para qué se marcan las líneas con cinta adhesiva gruesa?", r: "Para que los jugadores puedan notarlas con los dedos y orientarse sin ver.", lineas: 1 },
      { tipo: "comprension", q: "Tras una falta, el otro equipo… Elige:", opciones: ["gana el partido", "lanza un penalti contra un solo defensor", "cambia de portería"], r: "lanza un penalti contra un solo defensor" },
      { tipo: "texto", q: "Un reglamento es un texto instructivo con partes especiales. ¿Qué partes tiene este y en qué se diferencia de una receta?", r: "Introducción, material, cómo se juega, faltas y orientación. Se diferencia en que incluye normas y castigos (faltas y penaltis), no solo pasos.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría jugar al goalball? ¿Qué crees que sería lo más difícil?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que los deportes adaptados deberían practicarse en todas las clases de Educación Física? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "reflexion", q: "Muchos alumnos dicen: «Nunca había escuchado tanto un partido». ¿Qué crees que aprendió sobre cómo viven el deporte las personas ciegas?", r: "Respuesta libre. Valorar la empatía y que mencione que usan otros sentidos con gran habilidad.", lineas: 3 },
    ],
  },
];
