// Lecturas · Narrativa (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["narrativa"] = [
  {
    id: "narrativa-01-la-lechera",
    titulo: "La lechera",
    subtipo: "Fábula",
    curso: "5º",
    fuente: "Adaptación de «La lechera», fábula de Félix María de Samaniego (Fábulas morales, siglo XVIII)",
    antes: "¿Alguna vez has hecho muchos planes con algo que todavía no tenías? ¿Salieron como pensabas?",
    texto: [
      { p: "Por un camino de tierra, entre olivos y campos de trigo, caminaba una joven lechera llamada Clara. Llevaba sobre la cabeza un cántaro lleno de leche fresca que pensaba vender en el mercado del pueblo. Iba tan contenta que casi daba saltitos y, mientras andaba, empezó a hacer planes." },
      { p: "—Con el dinero que me den por esta leche —pensaba— compraré una cesta de huevos. De los huevos saldrán cien pollitos, que criaré en el corral de casa. Les daré buen grano y crecerán sanos y gordos." },
      { p: "Clara sonreía y seguía imaginando: —Cuando los pollos sean grandes, los venderé y compraré un cerdito. Lo alimentaré con bellotas y castañas hasta que sea el cerdo más hermoso de la comarca. Después lo venderé a buen precio y con ese dinero me compraré una vaca y un ternero que saltará por el prado." },
      { p: "Tan emocionada estaba pensando en el ternero que ella también dio un salto de alegría. Y entonces… ¡zas! El cántaro resbaló de su cabeza, cayó al suelo y se rompió en mil pedazos. La leche se extendió por el camino y la tierra seca se la bebió en un momento." },
      { p: "Adiós, leche; adiós, huevos; adiós, pollitos; adiós, cerdo; adiós, vaca, y adiós, ternero. Clara se quedó mirando los trozos de barro, sin saber si reír o llorar." },
      { p: "—Bueno —suspiró al fin—, la próxima vez primero llegaré al mercado y después haré planes." },
      { cita: "Moraleja: no te dejes llevar por la impaciencia pensando en lo que tendrás mañana; cuida bien lo que tienes hoy." },
    ],
    vocabulario: [
      { p: "cántaro", d: "vasija grande de barro, con asas, para llevar líquidos" },
      { p: "impaciencia", d: "prisa por que algo llegue enseguida" },
      { p: "moraleja", d: "enseñanza que se saca de una fábula o de un cuento" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué llevaba Clara sobre la cabeza y adónde iba?", r: "Llevaba un cántaro lleno de leche e iba al mercado del pueblo para venderla.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «comarca»? Elige:", opciones: ["Un corral grande para animales", "Un territorio formado por varios pueblos cercanos", "Una feria de ganado"], r: "Un territorio formado por varios pueblos cercanos" },
      { tipo: "comprension", q: "Ordena los planes de Clara, desde el primero hasta el último.", r: "Vender la leche, comprar huevos, criar pollitos, venderlos y comprar un cerdo, venderlo y comprar una vaca con un ternero.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué se le cayó el cántaro? ¿Qué tuvieron que ver sus pensamientos?", r: "Se le cayó porque dio un salto de alegría. Estaba tan metida en sus planes, imaginando al ternero saltando, que se olvidó de lo que llevaba en la cabeza.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice el narrador «adiós» a los huevos, los pollitos, el cerdo y la vaca, si Clara todavía no los tenía?", r: "Porque todos esos planes dependían del dinero de la leche. Al perder la leche, perdió también todo lo que había imaginado conseguir con ella.", lineas: 2 },
      { tipo: "texto", q: "¿Esta fábula tiene un narrador en 1ª o en 3ª persona? Copia una expresión que lo demuestre. ¿Qué parte tienen las fábulas que no suelen tener otros cuentos?", r: "Narrador en 3ª persona («caminaba una joven lechera», «Clara sonreía»). Las fábulas terminan con una moraleja o enseñanza.", lineas: 2 },
      { tipo: "opinion", q: "¿Te ha pasado alguna vez algo parecido a lo de Clara? Cuéntalo y explica qué aprendiste.", r: "Respuesta libre. Valorar que relacione la fábula con una experiencia propia.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece acertada la decisión final de Clara? ¿Qué consejo le darías tú? ¿Por qué?", r: "Respuesta libre. Valorar que justifique su consejo.", lineas: 3 },
      { tipo: "reflexion", q: "¿Es malo soñar con el futuro? ¿Qué diferencia hay entre tener ilusiones y descuidar lo que tienes hoy?", r: "Respuesta libre. Valorar que distinga entre soñar y hacer planes con los pies en el suelo.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-02-traje-emperador",
    titulo: "El traje nuevo del emperador",
    subtipo: "Cuento popular",
    curso: "5º",
    fuente: "Adaptación de «El traje nuevo del emperador», de Hans Christian Andersen (1837)",
    antes: "¿Alguna vez has dicho que algo te gustaba solo porque a todos los demás les gustaba?",
    texto: [
      { p: "Hace muchos años vivía un emperador al que le gustaban tanto los trajes nuevos que se gastaba todo su dinero en ropa. No le importaban sus soldados ni los paseos por el bosque: solo quería lucir un traje diferente a cada hora del día." },
      { p: "Un día llegaron a la ciudad dos pícaros que decían ser tejedores. Contaban que sabían fabricar la tela más bonita del mundo, con colores y dibujos preciosos. Además, aquella tela tenía una propiedad asombrosa: era invisible para cualquier persona tonta o que no mereciera su cargo." },
      { p: "«¡Qué tela tan maravillosa! —pensó el emperador—. Con un traje así sabré quién es listo y quién no en mi reino». Y pagó a los tejedores una gran cantidad de oro para que empezaran a trabajar." },
      { p: "Los pícaros montaron dos telares y fingieron tejer día y noche, aunque no había nada en ellos. El emperador envió a su viejo ministro a ver cómo iba el trabajo. El pobre hombre abrió mucho los ojos, pero no vio nada. «¿Seré tonto?», pensó asustado. Y para que nadie lo sospechara, exclamó: —¡Es precioso! ¡Qué colores tan elegantes!" },
      { p: "Lo mismo les pasó a todos los que fueron a verlo, y también al propio emperador, que tampoco veía nada, pero no quiso reconocerlo." },
      { p: "Por fin llegó el día del gran desfile. Los tejedores hicieron como que le ponían el traje, pieza a pieza, y el emperador salió a la calle bajo un gran palio. La gente, desde las ventanas, gritaba: —¡Qué traje tan magnífico! ¡Qué bien le sienta!" },
      { p: "Nadie quería parecer tonto. Pero entonces un niño pequeño señaló al emperador y dijo con toda naturalidad: —¡Pero si va en calzoncillos!" },
      { p: "La gente empezó a murmurar: —El niño tiene razón… ¡No lleva ningún traje! Al final, toda la ciudad lo gritaba. El emperador sintió un escalofrío, porque sabía que era verdad. Sin embargo, pensó que ya no podía parar el desfile, así que siguió caminando más orgulloso que nunca, mientras sus ayudantes sujetaban una cola que no existía." },
    ],
    vocabulario: [
      { p: "pícaro", d: "persona astuta que engaña a los demás para sacar provecho" },
      { p: "telar", d: "máquina para tejer telas" },
      { p: "palio", d: "techo de tela sujeto con varas que se lleva sobre una persona importante en un desfile" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Según los tejedores, ¿qué tenía de especial la tela que iban a fabricar?", r: "Que era invisible para las personas tontas o que no merecían su cargo.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el ministro dijo que la tela era preciosa? Elige:", opciones: ["Porque de verdad veía una tela bonita", "Porque tenía miedo de que pensaran que era tonto", "Porque los tejedores le pagaron"], r: "Porque tenía miedo de que pensaran que era tonto" },
      { tipo: "comprension", q: "¿Quiénes eran en realidad los tejedores y qué querían conseguir?", r: "Eran unos estafadores (pícaros) que querían quedarse con el oro del emperador sin trabajar.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el niño fue el único que se atrevió a decir la verdad?", r: "Porque no tenía ningún cargo que perder, no le preocupaba lo que pensaran de él y decía con sinceridad lo que veía.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué hizo el emperador al darse cuenta de que el niño tenía razón? ¿Por qué lo hizo?", r: "Siguió desfilando, más orgulloso que nunca, porque no quería reconocer su error ni parar el desfile delante de todos.", lineas: 2 },
      { tipo: "texto", q: "Divide el cuento en planteamiento, nudo y desenlace. Escribe qué ocurre en cada parte.", r: "Planteamiento: un emperador obsesionado con los trajes; llegan dos falsos tejedores. Nudo: fingen tejer una tela invisible y nadie se atreve a decir que no ve nada. Desenlace: en el desfile, un niño dice la verdad y el emperador sigue caminando.", lineas: 3 },
      { tipo: "opinion", q: "Si hubieras sido el ministro, ¿qué habrías hecho? ¿Por qué?", r: "Respuesta libre. Valorar que argumente su decisión.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que es difícil decir la verdad cuando todos opinan lo contrario? Pon un ejemplo.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Hoy en día, ¿hay situaciones en las que la gente dice que algo le gusta solo porque lo dicen los demás? ¿Por qué crees que ocurre?", r: "Respuesta libre. Valorar ejemplos cercanos (modas, redes sociales) y la reflexión sobre la presión del grupo.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-03-almendros-medina-azahara",
    titulo: "Los almendros de Medina Azahara",
    subtipo: "Leyenda",
    curso: "5º",
    fuente: "Adaptación de una leyenda popular cordobesa",
    datos: ["Ministerio de Asuntos Exteriores y Junta de Andalucía: inscripción de la Ciudad Califal de Medina Azahara en la Lista del Patrimonio Mundial de la UNESCO (1 de julio de 2018)"],
    antes: "¿Qué echarías de menos si te fueras a vivir muy lejos de tu casa?",
    texto: [
      { p: "Hace más de mil años, Córdoba era una de las ciudades más grandes y hermosas del mundo. Allí gobernaba el califa Abderramán III, un hombre poderoso que mandó construir, al pie de la sierra, una ciudad palacio llena de jardines, fuentes y salones de mármol: Medina Azahara." },
      { p: "Cuenta la leyenda que el califa le puso ese nombre en honor de Azahara, la joven a la que amaba. Azahara había nacido en unas tierras del norte, donde en invierno las montañas se cubrían de nieve. Al principio vivía feliz en su nuevo hogar, pero con el paso del tiempo se fue poniendo triste. Pasaba las horas en silencio, asomada a una ventana, mirando la sierra." },
      { p: "—¿Qué te ocurre? —le preguntó un día el califa—. Tienes todo lo que puedes desear: palacios, jardines, joyas…" },
      { p: "—Echo de menos la nieve —respondió ella—. En mi tierra, cada invierno los montes se volvían blancos. Aquí nunca nieva, y siento que me falta algo." },
      { p: "El califa sabía que ni el hombre más poderoso puede ordenar al cielo que nieve. Pero no se rindió. Reunió a sus jardineros y les dio una orden extraña: plantar miles de almendros en las laderas de la sierra, alrededor de la ciudad." },
      { p: "Pasaron los meses. Un día de finales de invierno, el califa llevó a Azahara hasta la ventana más alta del palacio. Ella se quedó sin palabras: toda la sierra estaba cubierta por un manto blanco. Pero no era nieve. Eran las flores de los almendros, que se habían abierto a la vez y temblaban con la brisa." },
      { p: "Azahara sonrió por primera vez en mucho tiempo. Y dicen que, desde entonces, cada año, cuando el invierno se despide, los almendros de la sierra de Córdoba se visten de blanco para recordar aquel regalo." },
      { dato: "¿Sabías que Medina Azahara existe de verdad? Sus restos se pueden visitar a pocos kilómetros de Córdoba y en 2018 la UNESCO la declaró Patrimonio Mundial." },
    ],
    vocabulario: [
      { p: "califa", d: "gobernante musulmán con el máximo poder político y religioso" },
      { p: "ladera", d: "cada uno de los lados en pendiente de una montaña" },
      { p: "brisa", d: "viento suave" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién era Abderramán III y qué mandó construir?", r: "Era el califa que gobernaba en Córdoba. Mandó construir la ciudad palacio de Medina Azahara.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué estaba triste Azahara?", r: "Porque echaba de menos la nieve de su tierra, en el norte.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «manto» en la expresión «un manto blanco»? Elige:", opciones: ["Una capa que cubre algo por completo", "Una lluvia muy fuerte", "Un tipo de flor"], r: "Una capa que cubre algo por completo" },
      { tipo: "comprension", q: "¿Por qué el califa no podía cumplir directamente el deseo de Azahara? ¿Cómo lo solucionó?", r: "Porque nadie puede hacer que nieve, ni siquiera un califa. Lo solucionó plantando miles de almendros, cuyas flores blancas parecían nieve.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir que los almendros «se visten de blanco para recordar aquel regalo»?", r: "Que cada año florecen y la sierra se pone blanca, como si recordaran la historia del califa y Azahara. Es una forma poética de decir que florecen.", lineas: 2 },
      { tipo: "texto", q: "¿Por qué este texto es una leyenda y no un cuento? Escribe algo real que aparezca en él y algo que no se pueda comprobar.", r: "Porque mezcla hechos reales (Córdoba, el califa Abderramán III, Medina Azahara, los almendros de la sierra) con otros que no se pueden comprobar (la historia de Azahara y la plantación de los almendros), explica el origen de algo y se transmite de generación en generación («cuenta la leyenda», «dicen que»).", lineas: 3 },
      { tipo: "opinion", q: "Si tuvieras que alegrar a alguien que echa de menos su tierra, ¿qué harías? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué lugar o qué cosa echarías tú de menos si te fueras a vivir lejos? Explica por qué es importante para ti.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Muchas personas viven lejos del lugar donde nacieron. ¿Qué podemos hacer para que se sientan en casa en nuestro pueblo o ciudad?", r: "Respuesta libre. Valorar la empatía y las propuestas concretas.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-04-pipo-el-loro",
    titulo: "Pipo, el loro que sabía demasiado",
    subtipo: "Cuento de humor",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Sabes cómo aprenden a hablar los loros? ¿Qué palabras crees que aprendería un loro en tu clase?",
    texto: [
      { p: "El lunes por la mañana, la señorita Aurora entró en la clase de 5.º B con una jaula enorme cubierta por una sábana. —Os presento a Pipo —anunció—. Es el loro de mi vecino Anselmo, que se ha ido una semana de viaje. Se quedará con nosotros hasta el viernes." },
      { p: "Al quitar la sábana apareció un loro verde con la cabeza amarilla que miró a todos con desconfianza. Durante dos días no dijo ni pío. Los niños intentaron enseñarle a hablar: —¡Hola, Pipo! ¡Pipo guapo! Pero el loro solo se rascaba el pico y bostezaba." },
      { p: "El miércoles, sin embargo, todo cambió. En mitad del dictado, cuando la clase estaba en completo silencio, Pipo gritó: —¡Marcos, deja de copiar!" },
      { p: "Marcos se puso rojo como un tomate y todos se echaron a reír. Y aquello solo fue el principio. Pipo había estado escuchando en silencio y ahora lo soltaba todo. Cuando Lucía sacó el bocadillo antes del recreo, el loro chilló: —¡Aún no es la hora! Cuando Hugo se quedó mirando por la ventana, gritó: —¡Tierra llamando a Hugo!, que era justo lo que decía siempre la señorita Aurora." },
      { p: "El jueves llegó el director para ver los murales de la clase. Justo cuando iba a felicitarlos, Pipo carraspeó y dijo con la misma voz que la maestra: —¡Ay, que viene el director, recoged eso rápido!" },
      { p: "Se hizo un silencio muy largo. La señorita Aurora cerró los ojos. Pero el director soltó una carcajada tan fuerte que hasta Pipo se asustó. —Tranquila, Aurora —dijo secándose las lágrimas—. Cuando yo era maestro, en mi clase decíamos lo mismo." },
      { p: "El viernes, cuando el vecino Anselmo vino a recoger a Pipo, los niños se despidieron con pena. Ya en la puerta, el loro se giró hacia ellos y gritó: —¡Deberes para el lunes!" },
      { p: "Y todos protestaron a la vez, aunque ninguno pudo dejar de reír." },
    ],
    vocabulario: [
      { p: "desconfianza", d: "falta de seguridad en alguien o en algo" },
      { p: "carcajada", d: "risa fuerte y ruidosa" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué estaba Pipo en la clase de 5.º B?", r: "Porque su dueño, Anselmo, vecino de la maestra, se había ido una semana de viaje.", lineas: 2 },
      { tipo: "comprension", q: "Pipo no dijo nada los dos primeros días. ¿Qué crees que estaba haciendo en realidad?", r: "Estaba escuchando con atención y aprendiendo las frases que se decían en la clase.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que Pipo «carraspeó»? Elige:", opciones: ["Tosió un poco para aclararse la voz", "Se rascó con la pata", "Abrió las alas"], r: "Tosió un poco para aclararse la voz" },
      { tipo: "comprension", q: "¿Por qué la señorita Aurora cerró los ojos cuando Pipo habló delante del director?", r: "Porque le dio vergüenza: el loro había repetido una frase suya que dejaba ver que querían ocultar algo al director.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo reaccionó el director? ¿Qué nos dice eso de cómo es él?", r: "Se echó a reír y tranquilizó a la maestra. Demuestra que tiene sentido del humor y que es comprensivo.", lineas: 2 },
      { tipo: "texto", q: "¿El narrador de este cuento está en 1ª o en 3ª persona? Copia una frase que lo demuestre. ¿Dónde y cuándo ocurre la historia?", r: "En 3ª persona (por ejemplo, «Marcos se puso rojo como un tomate y todos se echaron a reír»). Ocurre en la clase de 5.º B de un colegio, durante una semana, de lunes a viernes.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué frase crees que aprendería un loro que pasara una semana en tu clase? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece buena idea tener un animal en clase durante una semana? Da una razón a favor y otra en contra.", r: "Respuesta libre. Valorar que tenga en cuenta el bienestar del animal.", lineas: 3 },
      { tipo: "reflexion", q: "Pipo repetía todo lo que oía sin pensar. ¿Qué puede pasar cuando las personas repiten cosas sin pensar si son verdad o si pueden hacer daño?", r: "Respuesta libre. Valorar que hable de rumores, bulos o comentarios que hieren.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-05-primer-dia-granada",
    titulo: "El mar de Granada",
    subtipo: "Cuento realista",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Te has cambiado alguna vez de colegio o de casa? ¿Cómo te sentiste el primer día?",
    texto: [
      { p: "Me llamo Nerea y tengo diez años. Hasta este verano había vivido siempre en Huelva, a diez minutos de la playa. Pero a mi madre le ofrecieron un trabajo en Granada, y en agosto metimos toda nuestra vida en cajas de cartón." },
      { p: "El primer día de colegio me desperté antes de que sonara el despertador. Tenía un nudo en el estómago del tamaño de una sandía. Mi madre me acompañó hasta la puerta y me dio un abrazo. —Vas a hacer amigos enseguida, ya lo verás —me dijo. Yo no estaba tan segura." },
      { p: "La maestra, Carmen, me presentó a la clase. Veinticinco caras me miraban a la vez. Dije «hola» con una voz tan bajita que creo que solo me oyó la pizarra. Me senté al final, al lado de la ventana, y durante toda la mañana apenas hablé." },
      { p: "En el recreo, todos corrieron a sus grupos. Yo me senté en un banco y saqué mi cuaderno. Sin pensarlo, empecé a dibujar el mar: las olas, las gaviotas, la arena de mi playa… No me di cuenta de que alguien me miraba por encima del hombro." },
      { p: "—¡Qué bien dibujas! —dijo un chico de pelo rizado—. Yo soy Yusuf. ¿Eres la nueva? Asentí. Él se sentó a mi lado. —Yo llegué el año pasado, desde Almería. Al principio también echaba de menos el mar. Todos los días." },
      { p: "—¿Y ya no? —le pregunté. Yusuf sonrió y señaló hacia el fondo del patio. Allí, detrás de los tejados, se veían unas montañas altísimas. —Es Sierra Nevada —me explicó—. En invierno se pone blanquita y podemos ir a la nieve. En mi casa decimos que la nieve es el mar de Granada." },
      { p: "Me reí por primera vez en todo el día. Luego Yusuf me presentó a Irene y a Pablo, que estaban jugando al pañuelo, y me uní al juego. Aquella tarde, al salir, mi madre me preguntó qué tal me había ido. —Bien —le dije—. Mañana te cuento lo del mar de Granada." },
    ],
    vocabulario: [
      { p: "asentir", d: "decir que sí, por ejemplo moviendo la cabeza" },
      { p: "echar de menos", d: "sentir tristeza por no tener cerca algo o a alguien" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué se mudó Nerea de Huelva a Granada?", r: "Porque a su madre le ofrecieron un trabajo en Granada.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir que Nerea tenía «un nudo en el estómago del tamaño de una sandía»? Elige:", opciones: ["Que había comido demasiada fruta", "Que estaba muy nerviosa", "Que tenía hambre"], r: "Que estaba muy nerviosa" },
      { tipo: "comprension", q: "¿Por qué crees que Nerea dibujó el mar en el recreo?", r: "Porque echaba de menos su playa y su ciudad, y se sentía sola en el colegio nuevo.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Yusuf entendía tan bien lo que sentía Nerea?", r: "Porque a él le había pasado lo mismo: llegó el año anterior desde Almería y también echaba de menos el mar.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Yusuf con la frase «la nieve es el mar de Granada»?", r: "Que Granada no tiene mar, pero tiene la nieve de Sierra Nevada, algo especial que puede disfrutar y que puede ocupar el lugar del mar que añora.", lineas: 2 },
      { tipo: "texto", q: "Este cuento está narrado en 1ª persona. ¿Quién es la narradora? Copia dos expresiones del texto que lo demuestren.", r: "La narradora es Nerea, la protagonista. Por ejemplo: «Me llamo Nerea», «me desperté», «Yo me senté en un banco».", lineas: 2 },
      { tipo: "opinion", q: "¿Qué harías tú para ayudar a un compañero o compañera nuevo en su primer día? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué lugar de tu pueblo o ciudad le enseñarías a alguien que acaba de llegar? ¿Por qué ese?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué es tan importante que alguien se acerque a hablarnos cuando estamos solos? ¿Cómo cambió el día de Nerea gracias a Yusuf?", r: "Respuesta libre. Valorar que reconozca la importancia de la empatía y de dar el primer paso.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-06-bocadillos-voladores",
    titulo: "El misterio de los bocadillos voladores",
    subtipo: "Cuento de misterio",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Te gustan las historias de detectives? ¿Qué hace un buen detective para resolver un caso?",
    texto: [
      { p: "En el colegio Bahía, a dos calles de la playa de la Caleta, en Cádiz, estaba ocurriendo algo muy extraño. Desde hacía una semana, cada mañana desaparecía un bocadillo de la clase de 6.º A. Primero fue el de tortilla de Rubén; después, el de queso de Martina; el jueves, el del propio maestro, don Julián." },
      { p: "—Esto es un caso para nosotros —dijo Alba, que había leído todas las novelas de detectives de la biblioteca. Y se puso manos a la obra con Rubén, que todavía no había superado lo de su tortilla." },
      { p: "Lo primero que hicieron fue anotar los datos en una libreta. Los bocadillos siempre desaparecían entre las once y las once y media, justo cuando la clase iba al gimnasio. La puerta quedaba cerrada con llave. Solo se quedaba abierta la ventana, para ventilar." },
      { p: "—Entonces nadie pudo entrar —dijo Rubén. —Nadie que camine por el pasillo —respondió Alba, pensativa." },
      { p: "Al día siguiente examinaron la clase con una lupa. En la repisa de la ventana encontraron migas de pan, una pluma blanca y gris y unas marcas extrañas en el polvo: huellas pequeñas con tres dedos hacia delante, unidos por una especie de piel. —¿Un pato? —preguntó Rubén. —En Cádiz no hay patos paseando por los tejados —dijo Alba—. Pero sí hay otra cosa…" },
      { p: "Decidieron tender una trampa. El viernes dejaron un bocadillo de chorizo sobre la mesa de don Julián, junto a la ventana abierta, y, con permiso del maestro, en lugar de ir al gimnasio se escondieron detrás de la puerta. Pasaron cinco minutos. Diez. Y de pronto, una sombra cruzó la ventana." },
      { p: "Una gaviota enorme, de patas amarillas, se posó en la repisa, miró a un lado y a otro, saltó a la mesa y atrapó el bocadillo con el pico. —¡Alto! —gritó Rubén. La gaviota lo miró sin ninguna vergüenza y salió volando con su botín hacia el mar." },
      { p: "Aquella tarde, Alba presentó su informe a la clase: la ladrona era una gaviota patiamarilla que había descubierto que en 6.º A se desayunaba muy bien. Desde entonces, los bocadillos se guardan en las mochilas y la ventana se abre solo un poco." },
      { p: "—Caso resuelto —dijo Alba, cerrando su libreta. —Sí —suspiró Rubén—, pero mi tortilla no vuelve." },
    ],
    vocabulario: [
      { p: "repisa", d: "saliente en la parte de abajo de una ventana" },
      { p: "ventilar", d: "dejar que entre aire fresco en un lugar" },
      { p: "patiamarilla", d: "que tiene las patas amarillas" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué misterio ocurría en la clase de 6.º A?", r: "Cada mañana desaparecía un bocadillo mientras la clase estaba en el gimnasio.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pistas encontraron Alba y Rubén en la repisa de la ventana?", r: "Migas de pan, una pluma blanca y gris y huellas de tres dedos unidos por una piel.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Alba dice «Nadie que camine por el pasillo»? ¿Qué estaba empezando a sospechar?", r: "Porque la puerta estaba cerrada y sospechaba que el ladrón había entrado volando por la ventana: un animal, un ave.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «botín» en este texto? Elige:", opciones: ["Un tipo de zapato", "Lo que se consigue robando", "Una bolsa de tela"], r: "Lo que se consigue robando" },
      { tipo: "comprension", q: "¿Por qué crees que la gaviota volvía todos los días a la misma hora?", r: "Porque había aprendido que a esa hora la clase estaba vacía, la ventana abierta y había comida fácil.", lineas: 3 },
      { tipo: "texto", q: "Este cuento es de misterio. ¿Cuál es el enigma? Resume brevemente el planteamiento, el nudo y el desenlace.", r: "El enigma: quién se lleva los bocadillos. Planteamiento: desaparecen bocadillos en 6.º A. Nudo: Alba y Rubén investigan, encuentran pistas y tienden una trampa. Desenlace: descubren que es una gaviota y guardan los bocadillos en las mochilas.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué te parece la forma de investigar de Alba? ¿Qué habrías hecho tú?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que la solución que encontró la clase es buena? ¿Se te ocurre otra?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Muchas gaviotas buscan comida en las ciudades porque encuentran restos que dejamos. ¿Qué podemos hacer para no cambiar las costumbres de los animales salvajes? ¿Por qué es importante?", r: "Respuesta libre. Valorar ideas como no darles de comer, usar bien las papeleras y no dejar restos.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-07-niebla-en-cazorla",
    titulo: "Niebla en Cazorla",
    subtipo: "Relato de aventuras",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Has hecho alguna vez una ruta por la montaña? ¿Qué harías si de repente no vieras el camino?",
    texto: [
      { p: "Aquella mañana de octubre salimos temprano del pueblo: mi abuelo Ramón, mi prima Candela y yo. Íbamos a hacer una ruta por la sierra de Cazorla, en Jaén, hasta un mirador desde el que, según el abuelo, se veía media Andalucía. Yo llevaba la mochila con los bocadillos; Candela, el mapa y la brújula, porque decía que ella era la exploradora oficial." },
      { p: "Durante la primera hora todo fue perfecto. Caminábamos entre pinos enormes, oíamos el agua de los arroyos y, en una curva, vimos una cabra montés que nos miraba desde una roca como si los animales raros fuéramos nosotros." },
      { p: "Pero, al llegar a una pradera, el cielo cambió. Una niebla espesa empezó a bajar por la ladera, tan blanca que parecía leche. En pocos minutos no veíamos ni los árboles que teníamos a diez pasos. —Nos quedamos juntos —dijo el abuelo con voz tranquila—. Nadie se separa." },
      { p: "Yo intenté parecer valiente, pero el corazón me iba a mil. El sendero había desaparecido bajo la hierba y todo parecía igual. Entonces el abuelo se agachó a nuestra altura y nos hizo una pregunta: —¿Qué señales hemos ido viendo por el camino?" },
      { p: "Candela se acordó enseguida: —¡Las marcas blancas y amarillas pintadas en las piedras y en los árboles! Son las del sendero." },
      { p: "Así que empezamos a buscarlas, muy despacio, como si fuera un juego de pistas. Yo encontré la primera en un tronco; Candela, la segunda en una roca. El abuelo nos dejaba ir delante, pero siempre a un paso de nosotros. Además, Candela miró el mapa: el camino de vuelta bajaba junto al arroyo. Si seguíamos oyendo el agua cerca, íbamos bien." },
      { p: "Tardamos casi una hora en llegar de nuevo al pinar, pero no nos perdimos ni una vez. Entonces la niebla se abrió de golpe y apareció un sol brillante, como si no hubiera pasado nada." },
      { p: "Nos sentamos a comer los bocadillos, que nunca me habían sabido tan ricos. —No hemos llegado al mirador —dije un poco decepcionado. —No —respondió el abuelo—, pero habéis aprendido lo más importante de la montaña: que hay que saber cuándo volver." },
      { p: "Esa noche lo escribí todo en mi diario. Y al final añadí una frase: «La próxima vez, la brújula la llevo yo»." },
    ],
    vocabulario: [
      { p: "pradera", d: "terreno llano cubierto de hierba" },
      { p: "sendero", d: "camino estrecho, sobre todo en el campo o la montaña" },
      { p: "decepcionado", d: "triste porque algo no ha salido como esperaba" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quiénes hicieron la excursión y adónde querían llegar?", r: "El narrador, su abuelo Ramón y su prima Candela. Querían llegar a un mirador de la sierra de Cazorla.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué problema surgió al llegar a la pradera?", r: "Bajó una niebla muy espesa y dejaron de ver el sendero y los árboles cercanos.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el abuelo, en lugar de guiarlos él, les hizo una pregunta?", r: "Para que mantuvieran la calma, pensaran por sí mismos y aprendieran a orientarse; así lo convirtió en un juego.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que al narrador «el corazón le iba a mil»? Elige:", opciones: ["Que corría muy deprisa", "Que estaba muy nervioso o asustado", "Que estaba cansado de subir"], r: "Que estaba muy nervioso o asustado" },
      { tipo: "comprension", q: "¿Qué quiere decir el abuelo con «hay que saber cuándo volver»?", r: "Que en la montaña es más importante la seguridad que llegar a la meta: cuando hay peligro, lo sensato es darse la vuelta.", lineas: 2 },
      { tipo: "texto", q: "Este relato de aventuras está contado en 1ª persona. ¿Quién es el narrador? ¿Qué elementos de las historias de aventuras aparecen?", r: "El narrador es el nieto de Ramón y primo de Candela, un personaje de la historia (no se dice su nombre): «salimos», «Yo llevaba», «dije». Hay un viaje o excursión, un peligro (la niebla) y un desafío que los protagonistas superan.", lineas: 3 },
      { tipo: "opinion", q: "¿Cómo te habrías sentido tú en medio de la niebla? ¿Qué habrías hecho?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué tres cosas no deben faltar en una mochila de montaña? Explica por qué.", r: "Respuesta libre. Por ejemplo: agua, abrigo, mapa, teléfono cargado, comida.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante seguir las normas y las señales en la naturaleza, aunque creamos que conocemos el camino?", r: "Respuesta libre. Valorar que hable de la seguridad y del respeto al entorno.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-08-pinceles-en-marte",
    titulo: "Pinceles en Marte",
    subtipo: "Cuento de ciencia ficción",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Cómo crees que se podría cultivar comida en otro planeta? ¿Qué necesitan las plantas para dar fruto?",
    texto: [
      { p: "Año 2147. En la colonia Nueva Esperanza, construida bajo una cúpula transparente en Marte, vivían trescientas personas. Afuera, el cielo era de color caramelo y por la noche la temperatura bajaba a más de sesenta grados bajo cero. Dentro, gracias al gran invernadero, crecían tomates, lechugas, fresas y hasta un pequeño limonero." },
      { p: "Amina, de doce años, pasaba allí todas las tardes. Le gustaba ayudar a Brote, el robot jardinero, un aparato con forma de araña que regaba, medía la humedad y hablaba demasiado." },
      { p: "Una mañana, la alarma del invernadero sonó por todos los pasillos. —Producción de tomates: cero —anunció la voz de la colonia—. Las flores se secan sin dar fruto." },
      { p: "Los científicos revisaron el agua, la luz, la tierra y el aire. Todo estaba perfecto. Nadie entendía nada. Si el invernadero dejaba de producir, habría que pedir comida a la Tierra, y la próxima nave tardaría meses en llegar." },
      { p: "Aquella tarde, Amina se sentó frente a las tomateras con Brote. —¿Qué ha cambiado esta semana? —le preguntó. —Nada importante —respondió el robot—. Solo se averiaron los abejorros mecánicos. Los he guardado en el almacén. No afecta a la producción." },
      { p: "Amina se quedó muy quieta. Recordó una videollamada con su abuela, que vivía en un pueblo de Almería y cultivaba tomates en un invernadero. «Sin abejorros no hay tomates —le había dicho—. Ellos mueven el polen de las flores. Sin polen, la flor no se convierte en fruto»." },
      { p: "—¡Brote! —gritó—. ¡Los abejorros sí afectan! ¡Son los que polinizan!" },
      { p: "El robot giró la cabeza tres veces, que era lo que hacía cuando se equivocaba. —Error en mis cálculos —admitió—. Reparación de abejorros: tres semanas." },
      { p: "—No podemos esperar tanto —dijo Amina. Entonces tuvo una idea. Fue corriendo al taller de arte de la escuela y volvió con una caja llena de pinceles." },
      { p: "Durante toda la semana, Amina, sus compañeros de clase y hasta algunos científicos recorrieron el invernadero tocando las flores una por una con pinceles suaves, llevando el polen de flor en flor. Brote los seguía para contar cuántas faltaban." },
      { p: "Diez días después apareció el primer tomate: pequeño, verde y un poco torcido. A Amina le pareció lo más bonito de todo Marte. Esa noche envió un mensaje a la Tierra, que tardaría varios minutos en llegar: «Abuela, tenías razón. En Marte también hacen falta abejorros»." },
    ],
    vocabulario: [
      { p: "colonia", d: "grupo de personas que se instala a vivir en un lugar nuevo y lejano" },
      { p: "cúpula", d: "techo con forma de media esfera" },
      { p: "polen", d: "polvillo de las flores necesario para que se formen los frutos" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Dónde y cuándo transcurre la historia?", r: "En la colonia Nueva Esperanza, en Marte, en el año 2147.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué problema tenía el invernadero y por qué era tan grave?", r: "Las flores se secaban sin dar fruto. Era grave porque sin esa comida habría que pedirla a la Tierra y la próxima nave tardaría meses.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Brote no se dio cuenta de la causa del problema?", r: "Porque pensaba que los abejorros mecánicos no eran importantes; no sabía que sin ellos las flores no se polinizaban.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo ayudó a Amina lo que le había contado su abuela? ¿Qué nos enseña eso?", r: "Le hizo recordar que los abejorros mueven el polen y así descubrió la causa. Enseña que el conocimiento de las personas mayores y de la experiencia es muy valioso.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «polinizar»? Elige:", opciones: ["Regar las plantas con agua caliente", "Llevar el polen de una flor a otra para que se forme el fruto", "Quitar las hojas secas de las plantas"], r: "Llevar el polen de una flor a otra para que se forme el fruto" },
      { tipo: "texto", q: "¿A qué subgénero pertenece esta narración? Escribe dos elementos del texto que lo demuestren.", r: "A la ciencia ficción: ocurre en el futuro (año 2147), en una colonia en Marte, con un robot que habla y abejorros mecánicos.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría vivir en una colonia en Marte? Da al menos dos razones.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "Amina resolvió el problema con una idea sencilla. ¿Crees que la tecnología lo resuelve todo? ¿Por qué?", r: "Respuesta libre. Valorar que argumente con ejemplos.", lineas: 3 },
      { tipo: "reflexion", q: "En la Tierra, las abejas y otros insectos polinizadores están en peligro. ¿Por qué deberíamos protegerlos? ¿Qué puedes hacer tú?", r: "Respuesta libre. Valorar que relacione polinizadores y alimentos, y proponga acciones (plantar flores, no usar venenos…).", lineas: 3 },
    ],
  },
  {
    id: "narrativa-09-lazarillo-uvas",
    titulo: "Lázaro y el racimo de uvas",
    subtipo: "Fragmento de novela picaresca",
    curso: "6º",
    fuente: "Adaptación de un episodio del tratado primero de «La vida de Lazarillo de Tormes», novela anónima (1554)",
    antes: "¿Qué es un trato? ¿Qué pasa cuando alguien no cumple lo que ha prometido?",
    texto: [
      { p: "Yo me llamo Lázaro y nací a orillas del río Tormes, en Salamanca; por eso me llaman Lazarillo de Tormes. Siendo muy niño, mi madre me puso al servicio de un ciego para que lo guiara por los caminos. A cambio, él me daría de comer y me enseñaría a ganarme la vida. Pero mi amo era tan listo como tacaño: nunca vi hombre más avariento, y yo pasaba tanta hambre que tuve que aprender a ser más listo que él." },
      { p: "Un día llegamos a un pueblo llamado Almorox en tiempo de vendimia. Un vendimiador, para hacerle un favor a mi amo, le dio un racimo de uvas. Como las uvas estaban muy maduras y se deshacían en la mano, el ciego decidió que nos las comiéramos allí mismo, sentados junto a una cerca." },
      { p: "—Hoy quiero ser generoso contigo —me dijo—. Comeremos este racimo entre los dos, y tendrás tanta parte como yo. Lo haremos así: tú picarás una vez y yo otra, con tal de que me prometas no tomar más de una uva cada vez. Yo haré lo mismo hasta que lo acabemos, y así no habrá engaño." },
      { p: "Hecho el trato, empezamos. Pero ya en el segundo turno, el muy tramposo cambió de idea y empezó a tomar las uvas de dos en dos, pensando que yo haría lo mismo. Como vi que él rompía el acuerdo, no me conformé con ir a la par, sino que pasé adelante: comía las uvas de dos en dos, de tres en tres y como podía." },
      { p: "Cuando se acabó el racimo, el ciego se quedó un buen rato con el escobajo en la mano. Luego meneó la cabeza y dijo: —Lázaro, me has engañado. Apostaría cualquier cosa a que tú has comido las uvas de tres en tres." },
      { p: "—No las comí así —respondí yo—. Pero ¿por qué sospecha eso?" },
      { p: "Y aquel ciego tan astuto me contestó: —¿Sabes en qué veo que las comiste de tres en tres? En que yo comía de dos en dos y tú callabas." },
      { p: "Me reí por dentro y, aunque era un muchacho, me admiró la agudeza del ciego. Aquel día comprendí que, para sobrevivir a su lado, tendría que tener los ojos bien abiertos, justo los que a él le faltaban." },
    ],
    vocabulario: [
      { p: "avariento", d: "que acumula y no quiere gastar ni compartir nada" },
      { p: "vendimia", d: "recogida de la uva" },
      { p: "escobajo", d: "lo que queda del racimo cuando se le quitan las uvas" },
      { p: "agudeza", d: "inteligencia rápida para darse cuenta de las cosas" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién es Lázaro y por qué estaba con el ciego?", r: "Es un niño nacido junto al río Tormes. Su madre lo puso al servicio del ciego para que lo guiara a cambio de comida.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué consistía el trato para comer el racimo?", r: "Cada uno tomaría una sola uva por turno, de uno en uno, hasta acabarlo.", lineas: 2 },
      { tipo: "comprension", q: "¿Quién rompió primero el trato? ¿Cómo reaccionó Lázaro?", r: "Lo rompió el ciego, que empezó a tomar las uvas de dos en dos. Lázaro se dio cuenta y comió aún más deprisa, de tres en tres.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo descubrió el ciego el engaño si no podía ver?", r: "Razonando: si él comía de dos en dos y Lázaro no protestaba, era porque Lázaro comía todavía más deprisa que él.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Lázaro con que tendría que tener «los ojos bien abiertos, justo los que a él le faltaban»? Elige:", opciones: ["Que tendría que estar muy atento y ser más listo que el ciego", "Que iba a curar al ciego", "Que tenía sueño"], r: "Que tendría que estar muy atento y ser más listo que el ciego" },
      { tipo: "texto", q: "Este fragmento pertenece a una novela. ¿Qué tipo de narrador tiene? ¿En qué se diferencia una novela de un cuento?", r: "Narrador en 1ª persona: Lázaro cuenta su propia vida («Yo me llamo Lázaro»). La novela es más extensa, está dividida en partes o capítulos (aquí, tratados), tiene más personajes y varias historias.", lineas: 3 },
      { tipo: "opinion", q: "¿Quién te parece más listo en este episodio, Lázaro o el ciego? ¿Por qué?", r: "Respuesta libre. Valorar que argumente con datos del texto.", lineas: 3 },
      { tipo: "opinion", q: "Lázaro engaña porque pasa hambre. ¿Crees que eso justifica su comportamiento? Da tus razones.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Esta novela se escribió hace más de 450 años y habla de un niño que trabajaba y pasaba hambre. ¿Sigue ocurriendo hoy en algunos lugares del mundo? ¿Qué se podría hacer?", r: "Respuesta libre. Valorar la reflexión sobre los derechos de la infancia.", lineas: 3 },
    ],
  },
  {
    id: "narrativa-10-quijote-molinos",
    titulo: "Don Quijote y los molinos de viento",
    subtipo: "Fragmento de novela",
    curso: "6º",
    fuente: "Adaptación del capítulo VIII de la primera parte de «Don Quijote de la Mancha» (1605), de Miguel de Cervantes",
    antes: "¿Has visto alguna vez un molino de viento? ¿Qué crees que podría confundir con él alguien con mucha imaginación?",
    texto: [
      { p: "En un lugar de la Mancha vivía un hidalgo llamado Alonso Quijano que había leído tantos libros de caballerías que acabó creyendo que todo lo que contaban era verdad. Un día decidió hacerse caballero andante: se puso una armadura vieja, se llamó a sí mismo don Quijote de la Mancha, montó en su flaco caballo Rocinante y salió por los caminos a deshacer injusticias. Como escudero se llevó a Sancho Panza, un labrador vecino suyo, sencillo y bonachón, que viajaba en su burro." },
      { p: "Iban los dos por el campo de Montiel cuando descubrieron treinta o cuarenta molinos de viento. En cuanto don Quijote los vio, dijo a su escudero:" },
      { p: "—La fortuna nos es favorable, amigo Sancho. ¿Ves allí aquellos desaforados gigantes? Pienso luchar con ellos y vencerlos a todos." },
      { p: "—¿Qué gigantes? —preguntó Sancho." },
      { p: "—Aquellos que ves allí, de los brazos largos, que algunos los tienen de casi dos leguas." },
      { p: "—Mire vuestra merced —respondió Sancho— que aquellos que allí se ven no son gigantes, sino molinos de viento, y lo que en ellos parecen brazos son las aspas, que, movidas por el viento, hacen andar la piedra del molino." },
      { p: "—Bien se ve que no sabes nada de aventuras —contestó don Quijote—. Ellos son gigantes; y si tienes miedo, quítate de ahí mientras yo me enfrento a ellos en fiera y desigual batalla." },
      { p: "Y, diciendo esto, espoleó a Rocinante sin hacer caso a las voces de Sancho, que seguía gritando que eran molinos. En ese momento se levantó un poco de viento y las grandes aspas comenzaron a moverse. Don Quijote, protegido con su escudo y con la lanza preparada, se lanzó al galope contra el primer molino. Pero, al clavar la lanza en el aspa, el viento la hizo girar con tanta fuerza que rompió la lanza en pedazos y arrastró tras de sí al caballo y al caballero, que fue rodando por el campo, muy maltrecho." },
      { p: "Sancho acudió a socorrerlo tan deprisa como pudo su burro. —¡Ay, señor! —dijo—. ¿No le dije a vuestra merced que mirase bien lo que hacía, que no eran sino molinos de viento?" },
      { p: "—Calla, amigo Sancho —respondió don Quijote—, que las cosas de la guerra cambian mucho. Yo pienso que el sabio Frestón, mi enemigo, ha convertido estos gigantes en molinos para quitarme la gloria de vencerlos. Pero al final poco podrán sus malas artes contra mi espada." },
      { p: "Sancho lo ayudó a levantarse y a subir otra vez sobre Rocinante, que también estaba medio dolorido, y juntos siguieron su camino: uno, soñando con nuevas aventuras; el otro, pensando sobre todo en la hora de comer." },
    ],
    vocabulario: [
      { p: "hidalgo", d: "noble de la categoría más baja, que a menudo tenía poco dinero" },
      { p: "escudero", d: "ayudante que acompañaba a un caballero" },
      { p: "legua", d: "antigua medida de longitud, de unos cinco kilómetros y medio" },
      { p: "maltrecho", d: "en mal estado, lleno de golpes" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué Alonso Quijano decidió hacerse caballero andante?", r: "Porque había leído tantos libros de caballerías que creía que todo lo que contaban era verdad.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué veía don Quijote y qué había en realidad? ¿Quién se lo explicó?", r: "Don Quijote veía gigantes con brazos largos, pero eran molinos de viento con aspas. Se lo explicó Sancho.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «desaforados» en el texto? Elige:", opciones: ["Enormes, fuera de lo normal", "Muy pequeños", "Asustados"], r: "Enormes, fuera de lo normal" },
      { tipo: "comprension", q: "¿Por qué crees que don Quijote no hace caso a Sancho?", r: "Porque confunde la realidad con lo que ha leído en los libros de caballerías y está convencido de ser un caballero que debe luchar contra gigantes.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo explica don Quijote lo que ha ocurrido? ¿Por qué crees que no reconoce su error?", r: "Dice que el sabio Frestón convirtió a los gigantes en molinos. No reconoce su error porque sigue viviendo en su mundo de fantasía y no quiere admitir que se ha equivocado.", lineas: 2 },
      { tipo: "texto", q: "¿Qué tipo de narrador tiene este fragmento? Compara a los dos personajes principales: ¿cómo es cada uno?", r: "Narrador en 3ª persona. Don Quijote es idealista, soñador, valiente e imaginativo; Sancho es realista, práctico, sencillo y piensa en comer.", lineas: 3 },
      { tipo: "opinion", q: "¿Con quién te identificas más, con don Quijote o con Sancho? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que es bueno tener mucha imaginación? ¿Puede ser un problema a veces? Razona tu respuesta.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Hoy decimos «luchar contra molinos de viento» cuando alguien se enfrenta a problemas imaginarios o imposibles. ¿Se te ocurre algún ejemplo? ¿Por qué crees que esta expresión ha llegado hasta nuestros días?", r: "Respuesta libre. Valorar la relación con la influencia del Quijote en nuestra lengua.", lineas: 3 },
    ],
  },
];
