// Lecturas · Narrativa (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["narrativa"] = [
  {
    id: "narrativa-01-la-lechera",
    titulo: "La lechera",
    subtipo: "Fábula",
    curso: "5º",
    fuente: "Adaptación de «La lechera», fábula de Félix María de Samaniego (Fábulas morales, siglo XVIII)",
    antes: "¿Alguna vez has hecho muchos planes con algo que todavía no tenías? ¿Salieron como pensabas?",
    texto: [
      { p: "En una casita blanca, a las afueras de un pueblo rodeado de olivos, vivía una joven llamada Clara con su madre y una vaca vieja y tranquila que se llamaba Canela. Cada mañana, Clara ordeñaba a Canela antes de que saliera el sol, y una vez por semana llevaba la leche al mercado del pueblo para venderla." },
      { p: "Aquel sábado, la leche había salido tan espesa y tan blanca que Clara llenó hasta arriba el cántaro más grande de la casa. Su madre la ayudó a colocárselo sobre la cabeza, encima de un rodete de trapo para que no se moviera." },
      { p: "—Ve despacio, hija, y mira dónde pisas —le dijo—. El camino tiene piedras y la leche no se recoge del suelo." },
      { p: "—Sí, madre, no se preocupe —respondió Clara, y echó a andar muy derecha, con una mano en el asa del cántaro y la otra balanceándose al compás de sus pasos. Canela la despidió con un mugido desde el establo." },
      { p: "Por un camino de tierra, entre olivos y campos de trigo, caminaba la joven lechera. Hacía una mañana espléndida: cantaban los gorriones, olía a tomillo y el sol empezaba a calentar las piedras. Iba tan contenta que casi daba saltitos y, mientras andaba, empezó a hacer planes para el futuro." },
      { p: "—Con el dinero que me den por esta leche —pensaba— compraré una cesta de huevos. De los huevos saldrán cien pollitos, que criaré en el corral de casa. Les daré buen grano y crecerán sanos y gordos." },
      { p: "Al pasar junto al pozo se cruzó con Tomás, el pastor, que llevaba sus ovejas al monte. —¡Buenos días, Clara! ¿En qué vas pensando, que sonríes tanto? —En nada, en nada —contestó ella, porque no quería que nadie le estropeara sus sueños. Y siguió su camino más deprisa." },
      { p: "Un poco más adelante pasó junto al huerto de la señora Remedios, que regaba sus tomateras. —¡Qué cántaro tan lleno llevas, muchacha! Cuidado con la cuesta del arroyo, que está resbaladiza. —¡Gracias, señora Remedios! —dijo Clara, aunque apenas la escuchó, porque en su cabeza ya estaba en el mercado. Se imaginaba la plaza llena de puestos, el del panadero, el del quesero, el de las telas de colores, y a todos los vecinos haciendo cola para comprar su leche, la mejor de la comarca." },
      { p: "Clara sonreía y seguía imaginando: —Cuando los pollos sean grandes, los venderé y compraré un cerdito. Lo alimentaré con bellotas y castañas hasta que sea el cerdo más hermoso de la comarca. Después lo venderé a buen precio y con ese dinero me compraré una vaca y un ternero que saltará por el prado. Y con lo que sobre, me haré un vestido nuevo para la feria, y todo el pueblo dirá: ¡mirad qué suerte ha tenido Clara!" },
      { p: "Justo cuando empezaba a bajar la cuesta del arroyo, estaba tan emocionada pensando en el ternero que ella también dio un salto de alegría. Y entonces… ¡zas! El cántaro resbaló de su cabeza, cayó al suelo y se rompió en mil pedazos. La leche se extendió por el camino y la tierra seca se la bebió en un momento." },
      { p: "Adiós, leche; adiós, huevos; adiós, pollitos; adiós, cerdo; adiós, vaca, y adiós, ternero. Y adiós también al vestido de la feria. Clara se quedó mirando los trozos de barro, sin saber si reír o llorar." },
      { p: "Volvió a casa despacito, con la cabeza gacha y sin cántaro. Su madre la vio llegar desde la puerta y no tuvo que preguntar nada. Le dio un abrazo y le dijo: —No llores, hija. Canela nos dará más leche mañana. Lo que se ha roto es un cántaro, no tus ganas de trabajar." },
      { p: "—Bueno —suspiró al fin Clara, secándose los ojos—, la próxima vez primero llegaré al mercado y después haré planes." },
      { p: "Y así lo hizo. El sábado siguiente fue hasta el pueblo mirando cada piedra del camino; en la cuesta del arroyo se acordó de la señora Remedios y bajó paso a paso. Vendió toda la leche y, solo cuando tuvo las monedas en la mano, se permitió soñar un poquito con la cesta de huevos. Al volver, Tomás, el pastor, le preguntó otra vez en qué iba pensando. —En que hoy he llegado al mercado —respondió ella, riendo—. Lo demás, ya veremos." },
      { cita: "Moraleja: no te dejes llevar por la impaciencia pensando en lo que tendrás mañana; cuida bien lo que tienes hoy." },
    ],
    vocabulario: [
      { p: "cántaro", d: "vasija grande de barro, con asas, para llevar líquidos" },
      { p: "rodete", d: "rosca de tela que se pone en la cabeza para llevar peso encima" },
      { p: "comarca", d: "territorio formado por varios pueblos cercanos" },
      { p: "moraleja", d: "enseñanza que se saca de una fábula o de un cuento" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué consejo le dio su madre a Clara? ¿Por qué crees que lo olvidó?", r: "Que fuera despacio y mirara dónde pisaba. Lo olvidó porque iba tan metida en sus planes e ilusiones que dejó de prestar atención a lo que llevaba en la cabeza.", lineas: 2 },
      { tipo: "comprension", q: "Ordena los planes de Clara, desde el primero hasta el último.", r: "Vender la leche, comprar huevos, criar pollitos, venderlos y comprar un cerdo, venderlo y comprar una vaca con un ternero, y hacerse un vestido para la feria.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice el narrador «adiós» a los huevos, los pollitos, el cerdo y la vaca, si Clara todavía no los tenía?", r: "Porque todos esos planes dependían del dinero de la leche. Al perder la leche, perdió también todo lo que había imaginado conseguir con ella.", lineas: 2 },
      { tipo: "texto", q: "¿El narrador de esta fábula está en 1ª o en 3ª persona? ¿Con qué parte terminan las fábulas?", r: "Narrador en 3ª persona («caminaba la joven lechera», «Clara sonreía»). Las fábulas terminan con una moraleja o enseñanza.", lineas: 1 },
      { tipo: "opinion", q: "¿Qué te parece lo que le dijo la madre a Clara al volver a casa? ¿Qué le habrías dicho tú? ¿Por qué?", r: "Respuesta libre. Valorar que justifique su respuesta y valore el apoyo de la madre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Es malo soñar con el futuro? ¿Qué diferencia hay entre tener ilusiones y descuidar lo que tienes hoy?", r: "Respuesta libre. Valorar que distinga entre soñar y hacer planes con los pies en el suelo.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-02-traje-emperador",
    titulo: "El traje nuevo del emperador",
    subtipo: "Cuento popular",
    curso: "5º",
    fuente: "Adaptación de «El traje nuevo del emperador», de Hans Christian Andersen (1837)",
    antes: "¿Alguna vez has dicho que algo te gustaba solo porque a todos los demás les gustaba?",
    texto: [
      { p: "Hace muchos años vivía un emperador al que le gustaban tanto los trajes nuevos que se gastaba todo su dinero en ropa. No le importaban sus soldados ni los paseos por el bosque: solo quería lucir un traje diferente a cada hora del día. Si en otros palacios se decía «el rey está reunido con sus consejeros», en el suyo se decía siempre: «el emperador está en el vestidor»." },
      { p: "Un día llegaron a la ciudad dos pícaros que decían ser tejedores. Contaban que sabían fabricar la tela más bonita del mundo, con colores y dibujos preciosos. Además, aquella tela tenía una propiedad asombrosa: era invisible para cualquier persona tonta o que no mereciera su cargo." },
      { p: "«¡Qué tela tan maravillosa! —pensó el emperador—. Con un traje así sabré quién es listo y quién no en mi reino». Y pagó a los tejedores una gran cantidad de oro para que empezaran a trabajar. —Majestad —dijeron ellos con una gran reverencia—, será el traje más hermoso que se haya visto jamás. Solo le pedimos paciencia, porque una tela tan especial no se teje en un día. Y, sobre todo, mucha seda y mucho hilo de oro." },
      { p: "La noticia corrió por toda la ciudad. En los mercados, en las tabernas y en las plazas no se hablaba de otra cosa, y todo el mundo estaba deseando descubrir lo tontos o lo inútiles que eran sus vecinos." },
      { p: "Los pícaros montaron dos telares y fingieron tejer día y noche, aunque no había nada en ellos. Pedían sin parar la seda más fina y el hilo de oro más caro, pero lo guardaban todo en sus bolsas y seguían moviendo las manos en el aire." },
      { p: "Pasados unos días, el emperador envió a su viejo ministro a ver cómo iba el trabajo. El pobre hombre abrió mucho los ojos, pero no vio nada. «¿Seré tonto? —pensó asustado—. ¿No mereceré mi cargo?». Y para que nadie lo sospechara, exclamó: —¡Es precioso! ¡Qué colores tan elegantes! Se lo diré al emperador ahora mismo. Los tejedores se frotaron las manos y le explicaron, con mucho detalle, el nombre de cada color y la forma de cada dibujo, para que pudiera repetirlo en palacio." },
      { p: "Poco después fue un consejero, y le ocurrió lo mismo. Miró y miró, pero en los telares no había nada. «Tonto no soy —pensó—, así que debe de ser que no merezco mi puesto. ¡Nadie debe enterarse!». Y alabó la tela todavía más que el ministro." },
      { p: "Al final, el propio emperador quiso verla con sus ojos, acompañado de toda su corte. Al entrar en la sala se quedó helado: ¡no veía absolutamente nada! «¡Esto es terrible! —pensó—. ¿Seré yo el tonto? ¿No valdré para emperador?». Pero, como todos a su alrededor aplaudían, sonrió y dijo en voz alta: —¡Es bellísima! Tiene toda mi aprobación." },
      { p: "La noche antes del desfile, los tejedores no durmieron. Encendieron más de dieciséis velas para que todos vieran lo mucho que trabajaban, hicieron como que quitaban la tela de los telares, cortaron el aire con unas tijeras enormes y cosieron con agujas sin hilo. Por la mañana anunciaron muy serios: —¡El traje está terminado! Los chambelanes, encargados de llevar la cola del manto, se agacharon e hicieron como que la recogían del suelo, porque tampoco querían que nadie notara que no veían nada." },
      { p: "Por fin llegó el día del gran desfile. Los tejedores hicieron como que le ponían el traje, pieza a pieza: los pantalones, la chaqueta, la capa… —Es tan ligero como una tela de araña —decían—. Parecerá que no lleva nada puesto, ¡pero esa es precisamente su gracia! Delante del espejo, el emperador se giraba a un lado y a otro, como si se admirara. Después salió a la calle bajo un gran palio. La gente, desde las ventanas, gritaba: —¡Qué traje tan magnífico! ¡Qué bien le sienta!" },
      { p: "Nadie quería parecer tonto. Pero entonces un niño pequeño, que estaba en primera fila de la mano de su padre, señaló al emperador y dijo con toda naturalidad: —¡Pero si va en calzoncillos!" },
      { p: "—¡Escuchad lo que dice este inocente! —exclamó su padre. Y la gente empezó a murmurar, contándose unos a otros lo que había dicho el niño: —¡No lleva ningún traje! Al final, toda la ciudad lo gritaba." },
      { p: "El emperador sintió un escalofrío, porque sabía que era verdad. Sin embargo, pensó que ya no podía parar el desfile, así que siguió caminando más orgulloso que nunca, mientras sus ayudantes sujetaban una cola que no existía. De los dos tejedores, por cierto, nunca más se supo: aquella misma mañana habían salido de la ciudad con las bolsas llenas de oro y de seda." },
    ],
    vocabulario: [
      { p: "pícaro", d: "persona astuta que engaña a los demás para sacar provecho" },
      { p: "telar", d: "máquina para tejer telas" },
      { p: "corte", d: "conjunto de personas que viven y trabajan junto a un rey o un emperador" },
      { p: "palio", d: "techo de tela sujeto con varas que se lleva sobre una persona importante en un desfile" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué el ministro, el consejero y el emperador dijeron que la tela era preciosa, si no veían nada?", r: "Porque tenían miedo de que los demás pensaran que eran tontos o que no merecían su cargo.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué hacían los tejedores con la seda y el oro que pedían? ¿Qué querían en realidad?", r: "Los guardaban en sus bolsas. Demuestra que eran estafadores que solo querían quedarse con el oro y los materiales sin trabajar.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el niño fue el único que se atrevió a decir la verdad?", r: "Porque no tenía ningún cargo que perder, no le preocupaba lo que pensaran de él y decía con sinceridad lo que veía.", lineas: 2 },
      { tipo: "texto", q: "Divide el cuento en planteamiento, nudo y desenlace. Escribe qué ocurre en cada parte.", r: "Planteamiento: un emperador obsesionado con los trajes; llegan dos falsos tejedores. Nudo: fingen tejer una tela invisible y nadie, ni el emperador, se atreve a decir que no ve nada. Desenlace: en el desfile, un niño dice la verdad, el emperador sigue caminando y los pícaros huyen con el oro.", lineas: 2 },
      { tipo: "opinion", q: "Si hubieras sido el ministro, ¿qué habrías hecho? ¿Por qué?", r: "Respuesta libre. Valorar que argumente su decisión.", lineas: 1 },
      { tipo: "reflexion", q: "Hoy en día, ¿hay situaciones en las que la gente dice que algo le gusta solo porque lo dicen los demás? ¿Por qué crees que ocurre?", r: "Respuesta libre. Valorar ejemplos cercanos (modas, redes sociales) y la reflexión sobre la presión del grupo.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-03-almendros-medina-azahara",
    titulo: "Los almendros de Medina Azahara",
    subtipo: "Leyenda",
    curso: "5º",
    fuente: "Adaptación de una leyenda popular cordobesa",
    datos: ["Ministerio de Asuntos Exteriores y Junta de Andalucía: inscripción de la Ciudad Califal de Medina Azahara en la Lista del Patrimonio Mundial de la UNESCO (1 de julio de 2018)"],
    antes: "¿Qué echarías de menos si te fueras a vivir muy lejos de tu casa?",
    texto: [
      { p: "Hace más de mil años, Córdoba era una de las ciudades más grandes y hermosas del mundo. Por sus calles se oían muchas lenguas, en sus bibliotecas se guardaban miles de libros y en sus mercados se vendían sedas, perfumes y especias llegados de tierras lejanas. Allí gobernaba el califa Abderramán III, un hombre poderoso que mandó construir, al pie de la sierra, una ciudad palacio llena de jardines, fuentes y salones de mármol: Medina Azahara." },
      { p: "Cuentan que para levantarla trabajaron durante años miles de canteros, carpinteros y jardineros. Se trajeron columnas de lugares lejanos, se abrieron canales para llevar el agua de la sierra hasta las fuentes y se plantaron naranjos, rosales y arrayanes. Desde sus terrazas se veía todo el valle del Guadalquivir, verde y brillante." },
      { p: "Cuenta la leyenda que el califa le puso ese nombre en honor de Azahara, la joven a la que amaba. Azahara había nacido en unas tierras del norte, donde en invierno las montañas se cubrían de nieve y los niños jugaban a tirarse bolas blancas y frías. Al principio vivía feliz en su nuevo hogar: paseaba por los jardines, escuchaba a los músicos y aprendía los nombres de las flores del sur. Pero con el paso del tiempo se fue poniendo triste. Pasaba las horas en silencio, asomada a una ventana, mirando la sierra." },
      { p: "—¿Qué te ocurre? —le preguntó un día el califa—. Tienes todo lo que puedes desear: palacios, jardines, joyas…" },
      { p: "—Echo de menos la nieve —respondió ella—. En mi tierra, cada invierno los montes se volvían blancos. Aquí nunca nieva, y siento que me falta algo." },
      { p: "—Cuando caía la primera nevada —siguió contando—, salíamos todos a la calle. Los tejados, los caminos y los árboles amanecían blancos, y el mundo entero se quedaba en silencio, como si alguien lo hubiera tapado con una sábana. Mi madre decía que la nieve era la manera que tenía el invierno de pedir perdón por el frío." },
      { p: "El califa intentó alegrarla de muchas maneras. Le regaló collares de perlas, mandó traer pájaros de colores y ordenó a los mejores poetas de Córdoba que le recitaran versos cada tarde. Azahara lo agradecía con amabilidad, pero su mirada seguía perdida en las montañas. Por las noches, a veces, le pedía a una criada que le contara cuentos de su tierra, solo para oír otra vez la palabra nieve." },
      { p: "El califa sabía que ni el hombre más poderoso puede ordenar al cielo que nieve. Pero no se rindió. Pasó muchas noches pensando, hasta que una mañana tuvo una idea. Reunió a sus jardineros y les dio una orden extraña: plantar miles de almendros en las laderas de la sierra, alrededor de la ciudad." },
      { p: "—¿Almendros, señor? ¿Tantos? —preguntó el jardinero mayor, sorprendido. —Tantos como podáis —respondió el califa—. Y que nadie le diga nada a Azahara. Es un secreto." },
      { p: "Los jardineros más viejos entendieron enseguida la idea. Eligieron almendros porque son de los primeros árboles en florecer, cuando todavía hace frío y los demás siguen dormidos. Y los plantaron muy juntos, fila tras fila, para que desde lejos no se viera el verde del monte." },
      { p: "Durante semanas, cientos de hombres subieron y bajaron por la sierra cargados de arbolitos, de palas y de cubos de agua. Cavaban los hoyos, plantaban los almendros y los regaban con cuidado. Cuando Azahara preguntaba por qué había tanto movimiento en el monte, todos contestaban lo mismo: —Cosas del jardín, señora." },
      { p: "Pasaron los meses. Un día de finales de invierno, el califa llevó a Azahara hasta la ventana más alta del palacio. —Mira —le dijo solamente. Ella se quedó sin palabras: toda la sierra estaba cubierta por un manto blanco. Por un momento creyó que había nevado. Pero no era nieve. Eran las flores de los almendros, que se habían abierto a la vez y temblaban con la brisa." },
      { p: "Azahara sonrió por primera vez en mucho tiempo. —Has hecho nevar en Córdoba —susurró. Y dicen que, desde entonces, cada año, cuando el invierno se despide, los almendros de la sierra de Córdoba se visten de blanco para recordar aquel regalo. Y dicen los abuelos que, si uno se queda muy quieto mirando las ramas blancas movidas por el viento, casi puede oír la risa de Azahara." },
      { dato: "¿Sabías que Medina Azahara existe de verdad? Sus restos se pueden visitar a pocos kilómetros de Córdoba y en 2018 la UNESCO la declaró Patrimonio Mundial." },
    ],
    vocabulario: [
      { p: "califa", d: "gobernante musulmán con el máximo poder político y religioso" },
      { p: "ladera", d: "cada uno de los lados en pendiente de una montaña" },
      { p: "manto", d: "capa que cubre algo por completo" },
      { p: "brisa", d: "viento suave" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué estaba triste Azahara? ¿Por qué no funcionaron los primeros regalos del califa?", r: "Porque echaba de menos la nieve de su tierra. Primero le regaló perlas, pájaros y versos, pero no funcionó porque lo que le faltaba no era riqueza, sino algo que le recordara su tierra.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el califa quiso que la plantación fuera un secreto?", r: "Para darle una sorpresa y que la emoción fuera mayor al ver la sierra blanca de repente.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir que los almendros «se visten de blanco para recordar aquel regalo»?", r: "Que cada año florecen y la sierra se pone blanca, como si recordaran la historia del califa y Azahara. Es una forma poética de decir que florecen.", lineas: 2 },
      { tipo: "texto", q: "¿Por qué este texto es una leyenda y no un cuento? Escribe algo real que aparezca en él y algo que no se pueda comprobar.", r: "Porque mezcla hechos reales (Córdoba, el califa Abderramán III, Medina Azahara, los almendros de la sierra) con otros que no se pueden comprobar (la historia de Azahara y la plantación de los almendros), explica el origen de algo y se transmite de generación en generación («cuenta la leyenda», «dicen que»).", lineas: 2 },
      { tipo: "opinion", q: "Si tuvieras que alegrar a alguien que echa de menos su tierra, ¿qué harías? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Muchas personas viven lejos del lugar donde nacieron. ¿Qué podemos hacer para que se sientan en casa en nuestro pueblo o ciudad?", r: "Respuesta libre. Valorar la empatía y las propuestas concretas.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-04-pipo-el-loro",
    titulo: "Pipo, el loro que sabía demasiado",
    subtipo: "Cuento de humor",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Sabes cómo aprenden a hablar los loros? ¿Qué palabras crees que aprendería un loro en tu clase?",
    texto: [
      { p: "El lunes por la mañana, la señorita Aurora entró en la clase de 5.º B con una jaula enorme cubierta por una sábana. —Os presento a Pipo —anunció—. Es el loro de mi vecino Anselmo, que se ha ido una semana de viaje. Se quedará con nosotros hasta el viernes. Tiene agua, comida y una percha para columpiarse, así que nada de darle bocadillo ni golosinas, ¿entendido?" },
      { p: "Al quitar la sábana apareció un loro verde con la cabeza amarilla que miró a todos con desconfianza. Cada vez que alguien se acercaba a la jaula, se escondía detrás del comedero y soltaba un gruñidito, como un perro pequeño y enfadado. Durante dos días no dijo ni pío. Los niños intentaron enseñarle a hablar: —¡Hola, Pipo! ¡Pipo guapo! Hugo le recitó la tabla del siete, Lucía le cantó una canción y Marcos incluso le silbó el himno de su equipo de fútbol. Pero el loro solo se rascaba el pico y bostezaba." },
      { p: "En clase de Música, mientras practicaban con la flauta, a nadie le salía bien la canción. Pipo, desde su percha, los miraba con la cabeza torcida, como si le dolieran los oídos." },
      { p: "—A lo mejor no sabe hablar —dijo Lucía, un poco decepcionada. —O a lo mejor es tímido —opinó Hugo." },
      { p: "El miércoles, sin embargo, todo cambió. En mitad del dictado, cuando la clase estaba en completo silencio, Pipo gritó: —¡Marcos, deja de copiar!" },
      { p: "Marcos se puso rojo como un tomate y todos se echaron a reír. Y aquello solo fue el principio. Pipo había estado escuchando en silencio y ahora lo soltaba todo. Cuando Lucía sacó el bocadillo antes del recreo, el loro chilló: —¡Aún no es la hora! Cuando Hugo se quedó mirando por la ventana, gritó: —¡Tierra llamando a Hugo!, que era justo lo que decía siempre la señorita Aurora." },
      { p: "En clase de Matemáticas, Sara se quedó atascada en la pizarra con una multiplicación. Antes de que nadie pudiera ayudarla, Pipo dijo muy serio: —¡Siete por ocho, cincuenta y seis! Sara lo escribió, la maestra dijo «correcto» y toda la clase aplaudió… al loro." },
      { p: "Por la tarde ocurrió lo peor… o lo mejor, según se mire. Faltaban veinte minutos para el recreo cuando, de repente, sonó el timbre: ¡riiiing! Todos se levantaron de golpe, cogieron sus almuerzos y salieron corriendo al patio. Pero el patio estaba vacío y en silencio. Y desde la ventana de 5.º B llegó otra vez el sonido, ¡riiiing!, seguido de una risa exactamente igual que la de Marcos. —¡Ha sido Pipo! —gritó Lucía. Tuvieron que volver a clase muertos de vergüenza, aunque nadie consiguió enfadarse con él. Y, por si acaso, al día siguiente Pipo silbó entera la canción de la flauta sin equivocarse ni una nota. —Vaya —dijo la maestra de Música, mirando a la clase por encima de las gafas—, por lo menos alguien ha estudiado esta semana. Desde entonces, cada vez que alguien desafinaba, Pipo carraspeaba con mucha dignidad." },
      { p: "—Bueno —dijo Hugo, orgulloso—, al menos la tabla del siete se la enseñé yo." },
      { p: "Aquella tarde, la clase celebró una asamblea. Decidieron que, mientras Pipo estuviera allí, hablarían con más cuidado: nada de motes, nada de gritos y nada de chivatazos. —Si un loro puede repetirlo —dijo Sara—, es mejor que sea algo bonito. Y todos estuvieron de acuerdo." },
      { p: "El jueves llegó el director para ver los murales de la clase. Los niños habían trabajado mucho en ellos y todo estaba recogido y ordenado. Justo cuando iba a felicitarlos, Pipo carraspeó y dijo con la misma voz que la maestra: —¡Ay, que viene el director, recoged eso rápido!" },
      { p: "Se hizo un silencio muy largo. La señorita Aurora cerró los ojos. Pero el director soltó una carcajada tan fuerte que hasta Pipo se asustó. —Tranquila, Aurora —dijo secándose las lágrimas—. Cuando yo era maestro, en mi clase decíamos lo mismo." },
      { p: "El viernes, cuando el vecino Anselmo vino a recoger a Pipo, los niños le contaron todas sus hazañas y le regalaron un dibujo de Pipo firmado por toda la clase. Anselmo se rio mucho. —Los loros repiten lo que oyen muchas veces —les explicó—. Por eso ha aprendido vuestras frases favoritas. Si lo hubierais tenido un mes, ¡sabría hasta el horario de la clase!" },
      { p: "Los niños se despidieron de Pipo con pena. Ya en la puerta, el loro se giró hacia ellos y gritó: —¡Deberes para el lunes!" },
      { p: "Y todos protestaron a la vez, aunque ninguno pudo dejar de reír." },
    ],
    vocabulario: [
      { p: "desconfianza", d: "falta de seguridad en alguien o en algo" },
      { p: "carraspear", d: "toser un poco para aclararse la voz" },
      { p: "carcajada", d: "risa fuerte y ruidosa" },
      { p: "hazaña", d: "hecho importante o sorprendente" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Pipo no habló en dos días. ¿Qué crees que hacía en realidad? ¿Qué explicó Anselmo?", r: "Estaba escuchando y aprendiendo las frases de la clase. Anselmo explicó que los loros repiten lo que oyen muchas veces.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la señorita Aurora cerró los ojos cuando Pipo habló delante del director?", r: "Porque le dio vergüenza: el loro había repetido una frase suya que dejaba ver que querían ocultar algo al director.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo reaccionó el director? ¿Qué nos dice eso de él?", r: "Se echó a reír y tranquilizó a la maestra. Demuestra que tiene sentido del humor y que es comprensivo.", lineas: 1 },
      { tipo: "texto", q: "¿El narrador está en 1ª o en 3ª persona? Copia una frase que lo demuestre. ¿Dónde y cuándo ocurre?", r: "En 3ª persona (por ejemplo, «Marcos se puso rojo como un tomate y todos se echaron a reír»). Ocurre en la clase de 5.º B de un colegio, durante una semana, de lunes a viernes.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece buena idea tener un animal en clase durante una semana? Da una razón a favor y otra en contra.", r: "Respuesta libre. Valorar que tenga en cuenta el bienestar del animal.", lineas: 2 },
      { tipo: "reflexion", q: "Pipo repetía lo que oía sin pensar. ¿Qué puede pasar cuando las personas repiten cosas sin pensar si son verdad o si hacen daño?", r: "Respuesta libre. Valorar que hable de rumores, bulos o comentarios que hieren.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-05-primer-dia-granada",
    titulo: "El mar de Granada",
    subtipo: "Cuento realista",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Te has cambiado alguna vez de colegio o de casa? ¿Cómo te sentiste el primer día?",
    texto: [
      { p: "Me llamo Nerea y tengo diez años. Hasta este verano había vivido siempre en Huelva, a diez minutos de la playa. Pero a mi madre le ofrecieron un trabajo en Granada, y en agosto metimos toda nuestra vida en cajas de cartón. En la última caja, la que llevé yo en las rodillas durante todo el viaje, guardé un bote de cristal con arena de mi playa y tres conchas." },
      { p: "Nuestro piso nuevo está en un cuarto sin ascensor. Desde mi ventana no se ve el mar, sino tejados, antenas y, al fondo, unas montañas enormes. La primera noche no podía dormir. Echaba de menos el ruido de las olas, que antes me parecía tan normal que ni lo oía." },
      { p: "Los primeros días de septiembre los pasé ayudando a mi madre a desembalar. Cada caja que abríamos olía un poco a nuestra casa de antes. Mi abuela me llamaba todas las noches y me contaba cosas de Huelva: que había llovido, que el vecino había pintado la puerta de azul, que la playa ya estaba casi vacía. Yo la escuchaba y me entraban ganas de volver. Por las noches, antes de dormir, abría el bote de arena y lo olía, aunque ya casi no olía a nada." },
      { p: "El primer día de colegio me desperté antes de que sonara el despertador. Tenía un nudo en el estómago del tamaño de una sandía. Mi madre me acompañó hasta la puerta y me dio un abrazo. —Vas a hacer amigos enseguida, ya lo verás —me dijo. Yo no estaba tan segura." },
      { p: "La maestra, Carmen, me presentó a la clase. Veinticinco caras me miraban a la vez. —Nerea viene de Huelva —explicó—. ¿Quieres contarnos algo de tu ciudad? Dije «hola» con una voz tan bajita que creo que solo me oyó la pizarra, y después no me salió nada más. Me senté al final, al lado de la ventana, y durante toda la mañana apenas hablé." },
      { p: "En el recreo, todos corrieron a sus grupos. Yo me senté en un banco y saqué mi cuaderno. Sin pensarlo, empecé a dibujar el mar: las olas, las gaviotas, la arena de mi playa… No me di cuenta de que alguien me miraba por encima del hombro." },
      { p: "—¡Qué bien dibujas! —dijo un chico de pelo rizado—. Yo soy Yusuf. ¿Eres la nueva? Asentí. Él se sentó a mi lado. —Yo llegué el año pasado, desde Almería. Al principio también echaba de menos el mar. Todos los días." },
      { p: "—¿Y ya no? —le pregunté. Yusuf sonrió y señaló hacia el fondo del patio. Allí, detrás de los tejados, se veían las montañas que yo veía desde mi ventana. —Es Sierra Nevada —me explicó—. En invierno se pone blanquita y podemos ir a la nieve. En mi casa decimos que la nieve es el mar de Granada." },
      { p: "Me reí por primera vez en todo el día. Luego Yusuf me presentó a Irene y a Pablo, que estaban jugando al pañuelo, y me uní al juego. Irene corría tanto que nadie la alcanzaba, y Pablo hacía unas trampas tan evidentes que todos acabábamos riéndonos. Aquella tarde, al salir, mi madre me preguntó qué tal me había ido. —Bien —le dije—. Mañana te cuento lo del mar de Granada." },
      { p: "Al día siguiente, cuando entré en clase, Yusuf me había guardado el sitio a su lado. Y el otro, y el otro. En pocas semanas aprendí que Irene odiaba las matemáticas pero se sabía todos los ríos de España, que Pablo quería ser cocinero y que Yusuf tenía una hermana pequeña que lo seguía a todas partes. Ellos aprendieron que yo nado muy bien, que me dan miedo las avispas y que, cuando estoy nerviosa, dibujo olas en los márgenes del cuaderno." },
      { p: "Pasaron los meses. Aprendí el camino al colegio sin perderme, descubrí que en Granada, con algunas bebidas, te ponen una tapa, y me apunté con Irene al taller de dibujo. En diciembre, Carmen nos pidió que cada uno contara algo de su lugar favorito. Esta vez hablé en voz alta: llevé mi bote de arena y expliqué cómo son las marismas y las playas de Huelva. Al terminar, toda la clase aplaudió." },
      { p: "En enero, el colegio organizó una excursión a Sierra Nevada. El autobús subió por una carretera llena de curvas, y en cada curva el paisaje se volvía más blanco. Cuando llegamos arriba, me quedé con la boca abierta: todo era blanco, brillante y silencioso, como un mar quieto que se perdía en el horizonte. Yusuf me lanzó la primera bola de nieve y yo le lancé la segunda. Pasamos el día haciendo muñecos y deslizándonos por la nieve hasta tener las manos heladas. —Dicen que en los días muy claros, desde aquí arriba, se ve el mar de verdad —me contó Yusuf. Aquel día no se veía, pero no me importó." },
      { p: "Aquella noche, al volver a casa, puse junto al bote de arena una piedrecita que había recogido en la sierra. Ahora, en mi estantería, tengo un trocito de cada mar." },
    ],
    vocabulario: [
      { p: "asentir", d: "decir que sí, por ejemplo moviendo la cabeza" },
      { p: "echar de menos", d: "sentir tristeza por no tener cerca algo o a alguien" },
      { p: "marisma", d: "terreno bajo y húmedo junto al mar, que se inunda con las mareas" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué crees que Nerea dibujó el mar en el recreo del primer día?", r: "Porque echaba de menos su playa y su ciudad, y se sentía sola en el colegio nuevo.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Yusuf con la frase «la nieve es el mar de Granada»?", r: "Que Granada no tiene mar, pero tiene la nieve de Sierra Nevada, algo especial que puede disfrutar y que puede ocupar el lugar del mar que añora.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que al final Nerea tenga «un trocito de cada mar»? ¿En qué ha cambiado desde el primer día?", r: "Que no ha olvidado Huelva, pero también quiere a su nuevo hogar. El primer día casi no podía hablar; en diciembre habló en voz alta y ya tenía amigos.", lineas: 2 },
      { tipo: "texto", q: "Este cuento está narrado en 1ª persona. ¿Quién es la narradora? Copia dos expresiones del texto que lo demuestren.", r: "La narradora es Nerea, la protagonista. Por ejemplo: «Me llamo Nerea», «me desperté», «Yo me senté en un banco».", lineas: 1 },
      { tipo: "opinion", q: "¿Qué harías tú para ayudar a un compañero o compañera nuevo en su primer día? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante que alguien se acerque a hablarnos cuando estamos solos? ¿Cómo ayudó Yusuf a Nerea?", r: "Respuesta libre. Valorar que reconozca la importancia de la empatía y de dar el primer paso.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-06-bocadillos-voladores",
    titulo: "El misterio de los bocadillos voladores",
    subtipo: "Cuento de misterio",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Te gustan las historias de detectives? ¿Qué hace un buen detective para resolver un caso?",
    texto: [
      { p: "En el colegio Bahía, a dos calles de la playa de la Caleta, en Cádiz, estaba ocurriendo algo muy extraño. Desde hacía una semana, cada mañana desaparecía un bocadillo de la clase de 6.º A. Primero fue el de tortilla de Rubén; después, el de queso de Martina; el jueves, el del propio maestro, don Julián." },
      { p: "—Esto es un caso para nosotros —dijo Alba, que había leído todas las novelas de detectives de la biblioteca. Y se puso manos a la obra con Rubén, que todavía no había superado lo de su tortilla." },
      { p: "Mientras tanto, en la clase empezaron las sospechas. Martina miraba de reojo a Iker, porque siempre tenía hambre; Iker acusaba a Nora, porque un día la vio cerca de la mesa del maestro. Don Julián tuvo que pararlo: —Nadie acusa a nadie sin pruebas. Eso es lo primero que aprende un buen detective. Alba estaba totalmente de acuerdo, y lo apuntó en la primera página de su libreta, subrayado dos veces." },
      { p: "Lo primero que hicieron fue anotar los datos en una libreta. Los bocadillos siempre desaparecían entre las once y las once y media, justo cuando la clase iba al gimnasio. La puerta quedaba cerrada con llave. Solo se quedaba abierta la ventana, para ventilar." },
      { lista: ["Hora: entre las 11:00 y las 11:30.", "Puerta: cerrada con llave.", "Ventana: abierta.", "Víctimas: Rubén, Martina y don Julián."], titulo: "Libreta de Alba" },
      { p: "—Entonces nadie pudo entrar —dijo Rubén. —Nadie que camine por el pasillo —respondió Alba, pensativa." },
      { p: "Aun así, un buen detective no descarta a nadie sin comprobarlo, así que Alba escribió en la libreta una lista de sospechosos. El primero era Paco, el conserje, que tenía todas las llaves. Pero Paco les demostró que a esa hora estaba siempre en la puerta recibiendo al panadero, y el panadero lo confirmó. El segundo sospechoso era la clase de 6.º B, sus eternos rivales en el fútbol. Sin embargo, a las once ellos estaban haciendo un examen de Inglés, con la puerta abierta y la profesora delante. —Coartadas perfectas —resopló Rubén, tachando nombres." },
      { p: "Al día siguiente examinaron la clase con una lupa. En la repisa de la ventana encontraron migas de pan, una pluma blanca y gris y unas marcas extrañas en el polvo: huellas pequeñas con tres dedos hacia delante, unidos por una especie de piel. —¿Un pato? —preguntó Rubén. —En Cádiz no hay patos paseando por los tejados —dijo Alba—. Pero sí hay otra cosa…" },
      { p: "Esa tarde fueron a la biblioteca y buscaron una guía de aves. Alba pasó las páginas hasta que se detuvo en un dibujo y puso el dedo encima. —Patas palmeadas, plumas blancas y grises, vive en la costa y come casi de todo —leyó en voz alta—. Ya sé quién es nuestro ladrón. Pero no diré nada hasta tener pruebas." },
      { p: "Decidieron tender una trampa. El viernes dejaron un bocadillo de chorizo sobre la mesa de don Julián, junto a la ventana abierta, y, con permiso del maestro, en lugar de ir al gimnasio se escondieron detrás de la puerta. Rubén respiraba tan fuerte que Alba tuvo que mandarlo callar. Desde lejos llegaban los gritos del gimnasio y en la clase solo se oía el tictac del reloj. Pasaron cinco minutos. Diez. Y de pronto, una sombra cruzó la ventana." },
      { p: "Una gaviota enorme, de patas amarillas, se posó en la repisa, miró a un lado y a otro, saltó a la mesa y atrapó el bocadillo con el pico. —¡Alto! —gritó Rubén. La gaviota lo miró sin ninguna vergüenza y salió volando con su botín hacia el mar." },
      { p: "Aquella tarde, Alba presentó su informe a la clase: la ladrona era una gaviota patiamarilla que había descubierto que en 6.º A se desayunaba muy bien. Explicó que estas aves son muy listas: aprenden enseguida dónde hay comida fácil y vuelven una y otra vez. Explicó las pistas una por una, y don Julián, para felicitarla, le puso un diez en «investigación». Desde entonces, los bocadillos se guardan en las mochilas y la ventana se abre solo un poco." },
      { p: "—Caso resuelto —dijo Alba, cerrando su libreta. —Sí —suspiró Rubén—, pero mi tortilla no vuelve." },
    ],
    vocabulario: [
      { p: "repisa", d: "saliente en la parte de abajo de una ventana" },
      { p: "coartada", d: "prueba de que alguien estaba en otro sitio cuando ocurrió un delito" },
      { p: "palmeada", d: "se dice de la pata con los dedos unidos por una piel, como la de los patos" },
      { p: "patiamarilla", d: "que tiene las patas amarillas" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué Alba dice «Nadie que camine por el pasillo»? ¿Qué estaba empezando a sospechar?", r: "Porque la puerta estaba cerrada y sospechaba que el ladrón había entrado volando por la ventana: un animal, un ave.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué descartaron a Paco, el conserje, y a la clase de 6.º B?", r: "Porque tenían coartadas: Paco estaba en la puerta con el panadero, que lo confirmó, y 6.º B estaba haciendo un examen con la profesora delante.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «botín» en este texto? Elige:", opciones: ["Un tipo de zapato", "Lo que se consigue robando", "Una bolsa de tela"], r: "Lo que se consigue robando" },
      { tipo: "texto", q: "¿Cuál es el enigma de este cuento de misterio? Resume el planteamiento, el nudo y el desenlace.", r: "El enigma: quién se lleva los bocadillos. Planteamiento: desaparecen bocadillos en 6.º A. Nudo: Alba y Rubén investigan, descartan sospechosos, encuentran pistas y tienden una trampa. Desenlace: descubren que es una gaviota y guardan los bocadillos en las mochilas.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué te parece la forma de investigar de Alba? ¿Qué habrías hecho tú?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Muchas gaviotas comen en las ciudades los restos que dejamos. ¿Qué podemos hacer para no cambiar las costumbres de los animales salvajes? ¿Por qué?", r: "Respuesta libre. Valorar ideas como no darles de comer, usar bien las papeleras y no dejar restos.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-07-niebla-en-cazorla",
    titulo: "Niebla en Cazorla",
    subtipo: "Relato de aventuras",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Has hecho alguna vez una ruta por la montaña? ¿Qué harías si de repente no vieras el camino?",
    texto: [
      { p: "La noche anterior, el abuelo Ramón extendió el mapa sobre la mesa de la cocina y nos enseñó la ruta con el dedo. —Subiremos por aquí, junto al arroyo, cruzaremos el pinar y llegaremos a una pradera. Desde allí, el mirador está a media hora. Después preparamos juntos las mochilas: agua, fruta, un chubasquero, una linterna, el botiquín y un silbato. —¿Un silbato? —pregunté. —En la montaña, un silbato se oye mucho más lejos que una voz —me explicó." },
      { p: "Aquella mañana de octubre salimos temprano del pueblo: mi abuelo Ramón, mi prima Candela y yo. Íbamos a hacer una ruta por la sierra de Cazorla, en Jaén, hasta un mirador desde el que, según el abuelo, se veía media Andalucía. Yo llevaba la mochila con los bocadillos; Candela, el mapa y la brújula, porque decía que ella era la exploradora oficial. Candela tenía once años, uno más que yo, y se tomaba muy en serio su papel: cada cierto tiempo se paraba, miraba la brújula con el ceño fruncido y anunciaba: —Vamos bien. Dirección norte." },
      { p: "Durante la primera hora todo fue perfecto. Caminábamos entre pinos enormes, oíamos el agua de los arroyos y, en una curva, vimos una cabra montés que nos miraba desde una roca como si los animales raros fuéramos nosotros. Más arriba, un buitre enorme daba vueltas en el cielo sin mover las alas. —En estas sierras nace el Guadalquivir —nos contó el abuelo—. El mismo río que pasa por Córdoba y por Sevilla empieza aquí, como un hilito de agua." },
      { p: "Pero, al llegar a una pradera, el cielo cambió. Una niebla espesa empezó a bajar por la ladera, tan blanca que parecía leche. En pocos minutos no veíamos ni los árboles que teníamos a diez pasos. —Nos quedamos juntos —dijo el abuelo con voz tranquila—. Nadie se separa." },
      { p: "—¿Y si seguimos hasta el mirador? —preguntó Candela—. Seguro que está cerca. —Con esta niebla no veríamos nada desde allí —respondió el abuelo—. Y cada paso que demos hacia arriba es un paso más que tendremos que desandar a ciegas. En la montaña, el orgullo es mal compañero." },
      { p: "Yo intenté parecer valiente, pero el corazón me iba a mil. Candela, que siempre era la más decidida, me cogió de la mano sin decir nada, y noté que la suya temblaba un poco. El sendero había desaparecido bajo la hierba y todo parecía igual. Entonces el abuelo se agachó a nuestra altura y nos hizo una pregunta: —¿Qué señales hemos ido viendo por el camino?" },
      { p: "Candela se acordó enseguida: —¡Las marcas blancas y amarillas pintadas en las piedras y en los árboles! Son las del sendero." },
      { p: "Así que empezamos a buscarlas, muy despacio, como si fuera un juego de pistas. Yo encontré la primera en un tronco; Candela, la segunda en una roca. El abuelo nos dejaba ir delante, pero siempre a un paso de nosotros. Además, Candela miró el mapa: el camino de vuelta bajaba junto al arroyo. Si seguíamos oyendo el agua cerca, íbamos bien." },
      { p: "Hubo un momento difícil. Durante un buen rato no apareció ninguna marca, y yo empecé a pensar que nos habíamos perdido. Pero el abuelo nos pidió que nos quedáramos quietos y en silencio. Y entonces lo oímos: el murmullo del arroyo, un poco a la izquierda. Diez pasos más allá, en una piedra, brillaba otra mancha blanca y amarilla. Candela dio un salto de alegría. —¿Lo veis? —dijo el abuelo—. La montaña siempre deja pistas. Solo hay que tener paciencia para encontrarlas y calma para no confundirlas. Desde ese momento ya no sentí miedo, sino algo parecido a la emoción de un detective que por fin encuentra la pista buena." },
      { p: "Tardamos casi una hora en llegar de nuevo al pinar, pero no nos perdimos ni una vez. Entonces la niebla se abrió de golpe y apareció un sol brillante, como si no hubiera pasado nada." },
      { p: "Nos sentamos a comer los bocadillos, que nunca me habían sabido tan ricos. —No hemos llegado al mirador —dije un poco decepcionado. —No —respondió el abuelo—, pero habéis aprendido lo más importante de la montaña: que hay que saber cuándo volver. El mirador seguirá ahí la próxima vez." },
      { p: "Al llegar al pueblo nos encontramos con una agente de medio ambiente que bajaba en su todoterreno. Nos preguntó de dónde veníamos y, cuando se lo contamos, felicitó al abuelo. —Han hecho lo correcto —dijo—. Cada otoño tenemos que salir a buscar a excursionistas que se empeñan en seguir con niebla. Después nos regaló a cada uno una pegatina con la silueta de una cabra montés, que todavía llevo en la mochila." },
      { p: "Esa noche lo escribí todo en mi diario. Y al final añadí una frase: «La próxima vez, la brújula la llevo yo»." },
    ],
    vocabulario: [
      { p: "chubasquero", d: "chaqueta ligera que protege de la lluvia" },
      { p: "pradera", d: "terreno llano cubierto de hierba" },
      { p: "sendero", d: "camino estrecho, sobre todo en el campo o la montaña" },
      { p: "decepcionado", d: "triste porque algo no ha salido como esperaba" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué prepararon la noche anterior? ¿Por qué crees que el abuelo quiso llevar un silbato?", r: "Estudiaron la ruta en el mapa y prepararon las mochilas (agua, fruta, chubasquero, linterna, botiquín y silbato). El silbato sirve para avisar o pedir ayuda si alguien se pierde, porque se oye más lejos que la voz.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el abuelo, en lugar de guiarlos él, les hizo una pregunta?", r: "Para que mantuvieran la calma, pensaran por sí mismos y aprendieran a orientarse; así lo convirtió en un juego.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el abuelo con «hay que saber cuándo volver»?", r: "Que en la montaña es más importante la seguridad que llegar a la meta: cuando hay peligro, lo sensato es darse la vuelta.", lineas: 2 },
      { tipo: "texto", q: "Este relato de aventuras está contado en 1ª persona. ¿Quién es el narrador? ¿Qué elementos de las historias de aventuras aparecen?", r: "El narrador es el nieto de Ramón y primo de Candela, un personaje de la historia (no se dice su nombre): «salimos», «Yo llevaba», «dije». Hay un viaje o excursión, un peligro (la niebla) y un desafío que los protagonistas superan.", lineas: 2 },
      { tipo: "opinion", q: "¿Cómo te habrías sentido tú en medio de la niebla? ¿Qué habrías hecho?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante seguir las normas y las señales en la naturaleza, aunque creamos que conocemos el camino?", r: "Respuesta libre. Valorar que hable de la seguridad y del respeto al entorno.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-08-pinceles-en-marte",
    titulo: "Pinceles en Marte",
    subtipo: "Cuento de ciencia ficción",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Cómo crees que se podría cultivar comida en otro planeta? ¿Qué necesitan las plantas para dar fruto?",
    texto: [
      { p: "Año 2147. En la colonia Nueva Esperanza, construida bajo una cúpula transparente en Marte, vivían trescientas personas. Afuera, el cielo era de color caramelo y por la noche la temperatura bajaba a más de sesenta grados bajo cero. Dentro, gracias al gran invernadero, crecían tomates, lechugas, fresas y hasta un pequeño limonero." },
      { p: "La vida en la colonia era parecida a la de un pueblo pequeño. Había una escuela con veinte alumnos, un taller de arte, un comedor donde todos se conocían y una sala con una ventana enorme, la preferida de los niños, desde la que se veía Fobos, una de las lunas de Marte, cruzando el cielo. Lo único que no había era nada que sobrara: cada gota de agua y cada tomate contaban." },
      { p: "Amina había llegado a Marte con sus padres cuando tenía seis años. De la Tierra recordaba pocas cosas: el olor de la lluvia, el ruido del mar y, sobre todo, los veranos en el pueblo de su abuela, entre invernaderos de plástico que brillaban al sol. Todavía hablaba con ella, aunque no como en una llamada normal: cada mensaje tardaba varios minutos en llegar, así que se grababan vídeos largos, llenos de preguntas y de noticias." },
      { p: "Amina, de doce años, pasaba en el invernadero todas las tardes. Le gustaba ayudar a Brote, el robot jardinero, un aparato con forma de araña que regaba, medía la humedad y hablaba demasiado." },
      { p: "—Humedad del suelo: sesenta y dos por ciento. Temperatura: veintitrés grados. ¿Sabías que el tomate es, en realidad, un fruto? —decía sin parar mientras recorría las filas de plantas." },
      { p: "Una mañana, la alarma del invernadero sonó por todos los pasillos. —Producción de tomates: cero —anunció la voz de la colonia—. Las flores se secan sin dar fruto." },
      { p: "Los científicos revisaron el agua, la luz, la tierra y el aire. Todo estaba perfecto. Revisaron también las luces y los aspersores, uno por uno. Nadie entendía nada. Si el invernadero dejaba de producir, habría que pedir comida a la Tierra, y la próxima nave tardaría meses en llegar. Esa noche, en el comedor, las raciones fueron un poco más pequeñas, y nadie hablaba mucho." },
      { p: "Aquella tarde, Amina se sentó frente a las tomateras con Brote. —¿Qué ha cambiado esta semana? —le preguntó. —Nada importante —respondió el robot—. Solo se averiaron los abejorros mecánicos. Los he guardado en el almacén. No afecta a la producción." },
      { p: "Amina se quedó muy quieta. Recordó un videomensaje de su abuela, que vivía en un pueblo de Almería y cultivaba tomates en un invernadero. «Sin abejorros no hay tomates —le había dicho—. Ellos mueven el polen de las flores. Sin polen, la flor no se convierte en fruto»." },
      { p: "—¡Brote! —gritó—. ¡Los abejorros sí afectan! ¡Son los que polinizan!" },
      { p: "El robot giró la cabeza tres veces, que era lo que hacía cuando se equivocaba. —Error en mis cálculos —admitió—. Reparación de abejorros: tres semanas." },
      { p: "Amina corrió a buscar a la doctora Okafor, la jefa del invernadero. Al principio, la doctora la escuchó con cara de duda: una niña de doce años proponía una respuesta que a ella se le había escapado. Pero después fue a mirar las flores con una lupa, comprobó que no tenían polen en el centro y asintió despacio. —Tienes razón, Amina. Pero tres semanas es demasiado tiempo." },
      { p: "—No podemos esperar tanto —dijo Amina. Entonces tuvo una idea. Fue corriendo al taller de arte de la escuela y volvió con una caja llena de pinceles." },
      { p: "Durante toda la semana, Amina, sus compañeros de clase y hasta algunos científicos recorrieron el invernadero tocando las flores una por una con pinceles suaves, llevando el polen de flor en flor. Era un trabajo lento: había que hacerlo con cuidado, sin romper los pétalos. Brote los seguía para contar cuántas faltaban y, de vez en cuando, anunciaba: —Flores polinizadas: ciento doce. Eficiencia humana: aceptable." },
      { p: "Diez días después apareció el primer tomate: pequeño, verde y un poco torcido. A Amina le pareció lo más bonito de todo Marte. En las semanas siguientes, las tomateras se llenaron de frutos y el comedor volvió a oler a ensalada. Los abejorros mecánicos regresaron reparados, pero la escuela guardó los pinceles en una vitrina con un cartel: «Herramientas de emergencia agrícola». Esa noche grabó un mensaje para la Tierra, que tardaría varios minutos en llegar: «Abuela, tenías razón. En Marte también hacen falta abejorros»." },
    ],
    vocabulario: [
      { p: "colonia", d: "grupo de personas que se instala a vivir en un lugar nuevo y lejano" },
      { p: "cúpula", d: "techo con forma de media esfera" },
      { p: "polen", d: "polvillo de las flores necesario para que se formen los frutos" },
      { p: "eficiencia", d: "capacidad de hacer bien un trabajo gastando poco tiempo o pocos medios" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué problema tenía el invernadero y por qué era tan grave para la colonia?", r: "Las flores se secaban sin dar fruto. Era grave porque en la colonia no sobraba nada: habría que pedir comida a la Tierra y la próxima nave tardaría meses.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Brote no vio la causa del problema? ¿Cómo la descubrió Amina?", r: "Porque pensaba que los abejorros mecánicos no eran importantes. Amina lo descubrió al recordar lo que le había dicho su abuela: sin abejorros que muevan el polen, no hay tomates.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que la doctora Okafor escuchó a Amina «con cara de duda»? ¿Qué hizo después?", r: "Porque le costaba creer que una niña hubiera encontrado una respuesta que a ella se le había escapado. Después lo comprobó con una lupa y le dio la razón: es una buena científica, que comprueba las ideas en lugar de despreciarlas.", lineas: 2 },
      { tipo: "texto", q: "¿A qué subgénero pertenece esta narración? Escribe dos elementos del texto que lo demuestren.", r: "A la ciencia ficción: ocurre en el futuro (año 2147), en una colonia en Marte, con un robot que habla y abejorros mecánicos.", lineas: 2 },
      { tipo: "opinion", q: "Amina resolvió el problema con una idea sencilla. ¿Crees que la tecnología lo resuelve todo? ¿Por qué?", r: "Respuesta libre. Valorar que argumente con ejemplos.", lineas: 2 },
      { tipo: "reflexion", q: "En la Tierra, las abejas y otros polinizadores están en peligro. ¿Por qué hay que protegerlos? ¿Qué puedes hacer tú?", r: "Respuesta libre. Valorar que relacione polinizadores y alimentos, y proponga acciones (plantar flores, no usar venenos…).", lineas: 2 },
    ],
  },
  {
    id: "narrativa-09-lazarillo-uvas",
    titulo: "Lázaro y el racimo de uvas",
    subtipo: "Fragmento de novela picaresca",
    curso: "6º",
    fuente: "Adaptación de varios episodios del tratado primero de «La vida de Lazarillo de Tormes», novela anónima (1554)",
    antes: "¿Qué es un trato? ¿Qué pasa cuando alguien no cumple lo que ha prometido?",
    texto: [
      { p: "Yo me llamo Lázaro y nací a orillas del río Tormes, en Salamanca; por eso me llaman Lazarillo de Tormes. Siendo muy niño, mi madre me puso al servicio de un ciego para que lo guiara por los caminos. A cambio, él me daría de comer y me enseñaría a ganarme la vida. Mi madre, llorando, me dio su bendición y me dijo: —Hijo, ya sé que no te veré más. Procura ser bueno. Y así salí con mi amo." },
      { p: "Al salir de Salamanca llegamos a un puente, a cuya entrada hay un animal de piedra casi con forma de toro. El ciego me mandó acercarme y me dijo: —Lázaro, pon el oído junto a este toro y oirás un gran ruido dentro de él. Yo, inocente, acerqué la cabeza, y él me dio un empujón que me hizo darme un buen golpe contra la piedra. —Necio —me dijo riendo—, aprende que el mozo del ciego tiene que saber un punto más que el diablo. En aquel momento desperté de mi inocencia, y pensé: «Este dice verdad; tengo que abrir el ojo y avivar, pues estoy solo, y pensar cómo saberme valer»." },
      { p: "Pero mi amo era tan listo como tacaño: nunca vi hombre más avariento. Llevaba el pan y la comida en un fardel de lienzo que se cerraba por la boca con una argolla de hierro y un candado, y lo contaba todo tan bien que no se le podía quitar ni una miga. Yo pasaba tanta hambre que tuve que aprender a ser más listo que él: con cuidado, descosía un poquito el fardel por un lado, sacaba un buen pedazo de pan y un trozo de tocino, y después lo volvía a coser. El ciego nunca entendió por qué su comida se acababa tan pronto." },
      { p: "Mi amo se ganaba la vida rezando oraciones por las calles, a cambio de alguna moneda. Cuando alguien le daba una blanca, yo, que era muy rápido, me la metía en la boca y le entregaba a él media blanca, que valía la mitad. Él la tocaba con los dedos y enseguida notaba que no era entera. —¿Qué diablos es esto? —se quejaba—. Desde que estás conmigo no me dan más que medias blancas, y antes me pagaban una blanca y muchas veces más. La culpa debe de ser tuya. Yo ponía cara de no saber nada y le decía que la gente de aquel pueblo era muy tacaña, pero él, que no se fiaba de mí, empezó a vigilarme todavía más." },
      { p: "Un día llegamos a un pueblo llamado Almorox en tiempo de vendimia. Por los caminos se veían carros cargados de racimos y gente cantando entre las viñas. Un vendimiador, para hacerle un favor a mi amo, le dio un racimo de uvas. Como las uvas estaban muy maduras y se deshacían en la mano, el ciego decidió que nos las comiéramos allí mismo, sentados junto a una cerca. No lo hizo por generosidad, sino porque, si las guardaba en el fardel, se habrían convertido en mosto y lo habrían manchado todo. Yo, que no había probado bocado en todo el día, miraba aquel racimo como quien mira un tesoro." },
      { p: "—Hoy quiero ser generoso contigo —me dijo—. Comeremos este racimo entre los dos, y tendrás tanta parte como yo. Lo haremos así: tú picarás una vez y yo otra, con tal de que me prometas no tomar más de una uva cada vez. Yo haré lo mismo hasta que lo acabemos, y así no habrá engaño." },
      { p: "Hecho el trato, empezamos. Pero ya en el segundo turno, el muy tramposo cambió de idea y empezó a tomar las uvas de dos en dos, pensando que yo haría lo mismo. Como vi que él rompía el acuerdo, no me conformé con ir a la par, sino que pasé adelante: comía las uvas de dos en dos, de tres en tres y como podía." },
      { p: "Cuando se acabó el racimo, el ciego se quedó un buen rato con el escobajo en la mano. Luego meneó la cabeza y dijo: —Lázaro, me has engañado. Apostaría cualquier cosa a que tú has comido las uvas de tres en tres." },
      { p: "—No las comí así —respondí yo—. Pero ¿por qué sospecha eso?" },
      { p: "Y aquel ciego tan astuto me contestó: —¿Sabes en qué veo que las comiste de tres en tres? En que yo comía de dos en dos y tú callabas." },
      { p: "Me reí por dentro y, aunque era un muchacho, me admiró la agudeza del ciego. Aquel día comprendí que, para sobrevivir a su lado, tendría que tener los ojos bien abiertos, justo los que a él le faltaban. Muchos años después, ya hombre, pensaba a menudo que aquel ciego tacaño, sin querer, había sido mi primer maestro: siendo ciego, me abrió los ojos y me enseñó a vivir en un mundo donde nadie regala nada." },
    ],
    vocabulario: [
      { p: "avariento", d: "que acumula y no quiere gastar ni compartir nada" },
      { p: "fardel", d: "saco o talega en la que se llevaba la comida en los viajes" },
      { p: "vendimia", d: "recogida de la uva" },
      { p: "escobajo", d: "lo que queda del racimo cuando se le quitan las uvas" },
      { p: "agudeza", d: "inteligencia rápida para darse cuenta de las cosas" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué le ocurrió a Lázaro junto al toro de piedra? ¿Qué aprendió ese día?", r: "El ciego le dijo que escuchara un ruido dentro del toro y le hizo darse un golpe contra la piedra. Aprendió que tenía que dejar de ser inocente, estar atento y valerse por sí mismo.", lineas: 2 },
      { tipo: "comprension", q: "¿Quién rompió primero el trato de las uvas? ¿Cómo descubrió el ciego que Lázaro también lo rompió?", r: "Lo rompió el ciego, que empezó a tomar las uvas de dos en dos. Lo descubrió razonando: si él comía de dos en dos y Lázaro no protestaba, era porque Lázaro comía todavía más deprisa.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Lázaro con tener «los ojos bien abiertos, justo los que a él le faltaban»? Elige:", opciones: ["Que tendría que estar muy atento y ser más listo que el ciego", "Que iba a curar al ciego", "Que tenía sueño"], r: "Que tendría que estar muy atento y ser más listo que el ciego" },
      { tipo: "texto", q: "Este fragmento pertenece a una novela. ¿Qué tipo de narrador tiene? ¿En qué se diferencia una novela de un cuento?", r: "Narrador en 1ª persona: Lázaro cuenta su propia vida («Yo me llamo Lázaro»). La novela es más extensa, está dividida en partes o capítulos (aquí, tratados), tiene más personajes y varias historias.", lineas: 2 },
      { tipo: "opinion", q: "Lázaro engaña porque pasa hambre. ¿Crees que eso justifica su comportamiento? Da tus razones.", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Esta novela, de hace más de 450 años, habla de un niño que trabajaba y pasaba hambre. ¿Sigue ocurriendo hoy en el mundo? ¿Qué se podría hacer?", r: "Respuesta libre. Valorar la reflexión sobre los derechos de la infancia.", lineas: 2 },
    ],
  },
  {
    id: "narrativa-10-quijote-molinos",
    titulo: "Don Quijote y los molinos de viento",
    subtipo: "Fragmento de novela",
    curso: "6º",
    fuente: "Adaptación de los capítulos I y VIII de la primera parte de «Don Quijote de la Mancha» (1605), de Miguel de Cervantes",
    antes: "¿Has visto alguna vez un molino de viento? ¿Qué crees que podría confundir con él alguien con mucha imaginación?",
    texto: [
      { p: "En un lugar de la Mancha vivía un hidalgo llamado Alonso Quijano. Tenía unos cincuenta años, era delgado, madrugador y amigo de la caza. En sus ratos libres, que eran casi todos los del año, se dedicaba a leer libros de caballerías, y se aficionó tanto que llegó a vender tierras para comprar más. Tanto leyó, de día y de noche, que se le secó el cerebro y acabó creyendo que todo lo que contaban aquellos libros era verdad." },
      { p: "Un día decidió hacerse caballero andante: limpió una armadura vieja que había sido de sus bisabuelos, se llamó a sí mismo don Quijote de la Mancha, montó en su flaco caballo Rocinante y salió por los caminos a deshacer injusticias. Como escudero se llevó a Sancho Panza, un labrador vecino suyo, sencillo y bonachón, que viajaba en su burro y a quien don Quijote había prometido hacer gobernador de una ínsula. Sancho no sabía muy bien qué era una ínsula, pero le sonaba muy bien." },
      { p: "Iban los dos por el campo de Montiel cuando descubrieron treinta o cuarenta molinos de viento. En cuanto don Quijote los vio, dijo a su escudero:" },
      { p: "—La fortuna nos es favorable, amigo Sancho. ¿Ves allí aquellos desaforados gigantes? Pienso luchar con ellos y vencerlos a todos." },
      { p: "—¿Qué gigantes? —preguntó Sancho." },
      { p: "—Aquellos que ves allí, de los brazos largos, que algunos los tienen de casi dos leguas." },
      { p: "—Mire vuestra merced —respondió Sancho— que aquellos que allí se ven no son gigantes, sino molinos de viento, y lo que en ellos parecen brazos son las aspas, que, movidas por el viento, hacen andar la piedra del molino." },
      { p: "—Bien se ve que no sabes nada de aventuras —contestó don Quijote—. Ellos son gigantes; y si tienes miedo, quítate de ahí mientras yo me enfrento a ellos en fiera y desigual batalla." },
      { p: "Y, diciendo esto, espoleó a Rocinante sin hacer caso a las voces de Sancho, que seguía gritando que eran molinos. En ese momento se levantó un poco de viento y las grandes aspas comenzaron a moverse. Don Quijote, protegido con su escudo y con la lanza preparada, se lanzó al galope contra el primer molino. Pero, al clavar la lanza en el aspa, el viento la hizo girar con tanta fuerza que rompió la lanza en pedazos y arrastró tras de sí al caballo y al caballero, que fue rodando por el campo, muy maltrecho." },
      { p: "Sancho acudió a socorrerlo tan deprisa como pudo su burro. —¡Ay, señor! —dijo—. ¿No le dije a vuestra merced que mirase bien lo que hacía, que no eran sino molinos de viento?" },
      { p: "—Calla, amigo Sancho —respondió don Quijote—, que las cosas de la guerra cambian mucho. Yo pienso que el sabio Frestón, mi enemigo, ha convertido estos gigantes en molinos para quitarme la gloria de vencerlos. Pero al final poco podrán sus malas artes contra mi espada." },
      { p: "Sancho lo ayudó a levantarse y a subir otra vez sobre Rocinante, que también estaba medio dolorido, y tomaron el camino de Puerto Lápice. Don Quijote iba muy triste por haber perdido la lanza, pero recordó a un caballero de las historias que, habiendo roto su espada en una batalla, arrancó una rama gruesa de una encina y siguió luchando con ella. Decidió que haría lo mismo en cuanto encontrara un árbol apropiado." },
      { p: "—Vaya vuestra merced un poco más derecho —le dijo Sancho—, que parece que va de medio lado, y debe de ser del golpe." },
      { p: "—Así es —respondió don Quijote—, y si no me quejo del dolor es porque a los caballeros andantes no se les permite quejarse de ninguna herida." },
      { p: "—Pues yo, si me duele algo, me quejaré aunque sea un pinchazo —contestó Sancho—, a no ser que eso de no quejarse sea también para los escuderos." },
      { p: "Don Quijote se rio de la sencillez de su escudero y le dio permiso para quejarse cuanto quisiera. Así siguieron su camino: uno, soñando con nuevas aventuras; el otro, bien acomodado en su burro, sacando de las alforjas algo de comer y dando alegres tragos de su bota de vino, sin acordarse ya de ninguna promesa ni de ningún peligro." },
    ],
    vocabulario: [
      { p: "hidalgo", d: "noble de la categoría más baja, que a menudo tenía poco dinero" },
      { p: "escudero", d: "ayudante que acompañaba a un caballero" },
      { p: "ínsula", d: "isla; en el Quijote, el territorio que Sancho espera gobernar" },
      { p: "legua", d: "antigua medida de longitud, de unos cinco kilómetros y medio" },
      { p: "maltrecho", d: "en mal estado, lleno de golpes" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué Alonso Quijano decidió hacerse caballero andante?", r: "Porque había leído tantos libros de caballerías que se le secó el cerebro y creía que todo lo que contaban era verdad.", lineas: 1 },
      { tipo: "comprension", q: "¿Cómo explica don Quijote lo que ha ocurrido con los molinos? ¿Por qué crees que no reconoce su error?", r: "Dice que el sabio Frestón convirtió a los gigantes en molinos. No reconoce su error porque sigue viviendo en su mundo de fantasía y no quiere admitir que se ha equivocado.", lineas: 2 },
      { tipo: "comprension", q: "Don Quijote no se queja del dolor y Sancho dice que él se quejará de cualquier cosa. ¿Qué nos dice eso de cada uno?", r: "Don Quijote vive según las normas de los libros de caballerías, aunque le duela; Sancho es práctico y sincero, y dice lo que siente sin complicarse.", lineas: 2 },
      { tipo: "texto", q: "¿Qué tipo de narrador tiene este fragmento? Compara a los dos personajes principales: ¿cómo es cada uno?", r: "Narrador en 3ª persona. Don Quijote es idealista, soñador, valiente e imaginativo; Sancho es realista, práctico, sencillo y piensa en comer.", lineas: 2 },
      { tipo: "opinion", q: "¿Con quién te identificas más, con don Quijote o con Sancho? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Decimos «luchar contra molinos de viento» cuando alguien se enfrenta a problemas imaginarios o imposibles. ¿Se te ocurre algún ejemplo? ¿Por qué ha durado tanto esta expresión?", r: "Respuesta libre. Valorar la relación con la influencia del Quijote en nuestra lengua.", lineas: 2 },
    ],
  },
];
