// Lecturas · La noticia (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["noticia"] = [
  {
    id: "noticia-01-hotel-insectos",
    titulo: "Un hotel para insectos",
    subtipo: "Noticia escolar",
    curso: "5º",
    fuente: "Noticia inventada para esta ficha (el colegio y la localidad son ficticios)",
    antes: "¿Crees que los insectos son útiles? ¿Para qué sirven las abejas en un huerto?",
    texto: [
      { titular: "Alumnos de 5.º construyen un «hotel» para insectos en el patio de su colegio", subtitulo: "El proyecto del CEIP Los Olivos quiere atraer abejas, mariquitas y otros insectos beneficiosos a su huerto escolar", entradilla: "Villanueva del Olivar (Jaén), 14 de marzo. Los veinticuatro alumnos de 5.º del CEIP Los Olivos inauguraron ayer por la mañana, en el patio del colegio, un hotel para insectos construido por ellos mismos. Su objetivo es ayudar a los insectos polinizadores y mejorar la cosecha del huerto escolar." },
      { p: "La idea surgió en clase de Ciencias de la Naturaleza, cuando los alumnos estudiaron que muchas plantas necesitan insectos para dar fruto. «El año pasado nuestras calabazas casi no dieron nada, y la maestra nos explicó que quizá faltaban abejas», cuenta Lucía Moreno, de 10 años." },
      { p: "Los alumnos investigaron en libros y en internet y descubrieron que en los campos y en los pueblos cada vez hay menos lugares donde los insectos puedan refugiarse: se cortan los setos, se retiran los troncos viejos y se tapan los agujeros de las paredes. Un hotel de insectos es, precisamente, un refugio artificial que les ofrece esos escondites." },
      { h: "Tres semanas de trabajo" },
      { p: "Durante tres semanas, los estudiantes reunieron materiales reciclados: dos palés de madera, ladrillos huecos, cañas, piñas, paja y troncos con pequeños agujeros. Con la ayuda del conserje y de varias familias, montaron una estructura de más de un metro de altura con decenas de «habitaciones»." },
      { p: "Cada grupo se encargó de una planta del hotel. Unos cortaron las cañas a la misma medida con una sierra pequeña, siempre con un adulto al lado; otros lijaron los troncos para que no tuvieran astillas, y otros pintaron el cartel de la entrada. «Lo más difícil fue que las cañas no se cayeran: tuvimos que atarlas con cuerda y apretarlas mucho», explica Samuel Ortega, de 11 años. Encima colocaron un pequeño tejado de tejas viejas para proteger el hotel de la lluvia y, en la parte de abajo, unas piedras para que la humedad del suelo no pudriera la madera." },
      { tabla: { titulo: "¿Quién se aloja en cada habitación?", cab: ["Material", "Huésped que se espera"], filas: [["Cañas y troncos agujereados", "Abejas solitarias"], ["Piñas y paja", "Mariquitas"], ["Ladrillos huecos", "Escarabajos y otros pequeños insectos"], ["Corteza y madera vieja", "Ciempiés y cochinillas"]] }, nota: "Clasificación elaborada por los alumnos de 5.º." },
      { p: "El hotel está situado en un rincón soleado, junto al huerto, y orientado hacia el sur, porque a los insectos les gusta el calor. Alrededor, los alumnos han plantado romero, lavanda y tomillo para que los visitantes encuentren flores cerca." },
      { h: "Los primeros huéspedes" },
      { p: "Apenas unos días después de terminarlo, ya han llegado los primeros inquilinos. Los alumnos han visto varias mariquitas entre las piñas y algunas cañas tapadas con barro, una señal de que una abeja solitaria ha dejado dentro sus huevos. «Estas abejas no viven en colmenas ni fabrican miel, pero polinizan muchísimo», explica la tutora." },
      { p: "La tutora del grupo, Rosario Jiménez, cree que el proyecto sirve para aprender de forma práctica. «Los niños han medido, calculado, investigado y trabajado en equipo. Y, sobre todo, han entendido que los insectos no son enemigos, sino aliados», asegura." },
      { p: "A partir de ahora, cada semana un grupo de alumnos observará el hotel con lupas y anotará en un cuaderno de campo qué insectos se instalan. En junio presentarán sus resultados a las familias con un mural y una exposición de fotografías. Además, el colegio ha invitado a otros centros de la comarca a copiar la idea." },
    ],
    vocabulario: [
      { p: "polinizador", d: "animal, sobre todo insecto, que lleva el polen de una flor a otra" },
      { p: "palé", d: "plataforma de tablas de madera que se usa para transportar mercancías" },
      { p: "huésped", d: "quien se aloja en un lugar que no es su casa" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué relación hay entre las calabazas del año pasado y el hotel de insectos?", r: "Las calabazas dieron poco fruto quizá por falta de abejas; el hotel atraerá insectos polinizadores que ayudarán a que el huerto produzca más.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué señal indica que una abeja solitaria ya se ha instalado en el hotel?", r: "Que algunas cañas están tapadas con barro: la abeja ha dejado dentro sus huevos.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué el hotel está orientado hacia el sur? Elige:", opciones: ["Porque allí hay más sombra", "Porque a los insectos les gusta el calor", "Porque así se ve desde la calle"], r: "Porque a los insectos les gusta el calor" },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: la inauguración de un hotel para insectos. Quién: los 24 alumnos de 5.º del CEIP Los Olivos. Cuándo: ayer por la mañana (13 de marzo). Dónde: en el patio del colegio, en Villanueva del Olivar (Jaén). Cómo: con materiales reciclados y la ayuda del conserje y de las familias. Por qué: para ayudar a los polinizadores y mejorar el huerto.", lineas: 3 },
      { tipo: "opinion", q: "A mucha gente le dan miedo o asco los insectos. ¿Estás de acuerdo con que son aliados? ¿Por qué?", r: "Respuesta libre. Valorar que use información de la noticia.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante que los medios locales cuenten también noticias como esta?", r: "Respuesta libre. Valorar que hable de dar a conocer buenas ideas, inspirar a otros y contar lo que pasa cerca.", lineas: 2 },
    ],
  },
  {
    id: "noticia-02-espana-campeona-mundial",
    titulo: "¡España, campeona del mundo!",
    subtipo: "Noticia deportiva",
    curso: "5º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (final del Mundial femenino de fútbol, 20 de agosto de 2023)",
    datos: ["CNN en Español y ESPN Deportes: crónicas de la final España-Inglaterra (20 de agosto de 2023)", "Olympics.com: información sobre la final del Mundial femenino 2023", "Wikipedia en español: «Copa Mundial Femenina de Fútbol de 2023» (resultados de España, asistencia a la final y premios individuales)"],
    antes: "¿Recuerdas algún triunfo deportivo que se celebrara en todo el país? ¿Qué sentiste?",
    texto: [
      { titular: "¡España, campeona del mundo!", subtitulo: "Un gol de la sevillana Olga Carmona da a la selección femenina su primer Mundial de fútbol", entradilla: "Sídney (Australia), 20 de agosto de 2023. La selección española femenina de fútbol se ha proclamado hoy campeona del mundo por primera vez en su historia tras vencer por 1-0 a Inglaterra en la final, disputada en el Estadio Australia de Sídney ante más de 75.000 espectadores. El único gol del partido lo marcó la defensa Olga Carmona." },
      { p: "El tanto llegó en el minuto 29 de la primera parte. Olga Carmona recibió un pase de Mariona Caldentey, avanzó por la banda izquierda y disparó con la zurda, cruzado y pegado al palo. La portera inglesa, Mary Earps, no pudo hacer nada." },
      { p: "La victoria pudo ser más amplia. En la segunda parte, el árbitro señaló un penalti a favor de España, pero Earps detuvo el lanzamiento de Jennifer Hermoso. Inglaterra, que era la campeona de Europa, buscó el empate hasta el último minuto, aunque la defensa española resistió. Cuando sonó el pitido final, las jugadoras se abrazaron sobre el césped, muchas de ellas llorando de alegría." },
      { h: "Un camino con altibajos" },
      { p: "El torneo, que se disputó en Australia y Nueva Zelanda entre el 20 de julio y el 20 de agosto, fue el primero con 32 selecciones participantes. El camino de España hasta el título no fue fácil. Tras ganar sus dos primeros partidos, la selección sufrió una dura derrota por 4-0 ante Japón. Lejos de hundirse, el equipo reaccionó: goleó a Suiza en octavos, eliminó a los Países Bajos en la prórroga con un gol de Salma Paralluelo y superó a Suecia en una semifinal de infarto, decidida en los últimos minutos. En cada partido, las jugadoras demostraron que un mal resultado no tiene por qué ser el final del camino." },
      { tabla: { titulo: "El camino de España en el Mundial", cab: ["Fase", "Partido", "Resultado"], filas: [["Grupos", "España - Costa Rica", "3-0"], ["Grupos", "España - Zambia", "5-0"], ["Grupos", "Japón - España", "4-0"], ["Octavos de final", "España - Suiza", "5-1"], ["Cuartos de final", "España - Países Bajos", "2-1 (prórroga)"], ["Semifinal", "España - Suecia", "2-1"], ["Final", "España - Inglaterra", "1-0"]] } },
      { p: "Olga Carmona, nacida en Sevilla en el año 2000, fue una de las grandes protagonistas del torneo. En la semifinal ya había marcado el gol de la victoria contra Suecia, en el minuto 89. Con solo 23 años, se convirtió en la autora de dos de los goles más importantes de la historia de la selección femenina." },
      { p: "Además, la centrocampista Aitana Bonmatí recibió el Balón de Oro como mejor jugadora de todo el campeonato, y la delantera Salma Paralluelo, de 19 años, fue elegida mejor jugadora joven." },
      { p: "Con este triunfo, España se convierte en el segundo país, después de Alemania, que ha ganado el Mundial de fútbol tanto en categoría masculina como femenina. La selección masculina lo había conseguido en 2010, en Sudáfrica." },
      { p: "Como el partido se jugó a mediodía, hora española, miles de aficionados pudieron seguirlo en sus casas y en pantallas gigantes, y lo celebraron por todo el país." },
      { p: "En muchas plazas y polideportivos, niñas y niños con la camiseta de la selección saltaban y cantaban con el pitido final. Para muchas de las jugadoras de los equipos infantiles, fue la primera vez que vieron a un equipo de mujeres levantar la copa más importante del fútbol. Los clubes de fútbol base esperan que este triunfo anime a muchas más niñas a empezar a jugar." },
    ],
    vocabulario: [
      { p: "tanto", d: "en deporte, gol o punto" },
      { p: "zurda", d: "la pierna o la mano izquierda" },
      { p: "prórroga", d: "tiempo extra que se juega cuando un partido termina empatado" },
      { p: "centrocampista", d: "jugadora que juega en el centro del campo" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién marcó el gol de la final, en qué minuto y con qué pierna?", r: "Olga Carmona, en el minuto 29, con la pierna izquierda (la zurda).", lineas: 1 },
      { tipo: "comprension", q: "Mira la tabla. ¿Qué partido perdió España? ¿Qué quiere decir que el equipo «reaccionó»?", r: "Perdió 4-0 contra Japón en la fase de grupos. Dice que reaccionó porque, después de esa derrota, ganó todos los partidos hasta la final.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué fue decisiva Olga Carmona en el Mundial?", r: "Porque marcó el gol de la victoria en la semifinal contra Suecia y el único gol de la final.", lineas: 1 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué es importante?", r: "Qué: España gana el Mundial femenino de fútbol. Quién: la selección española (gol de Olga Carmona). Cuándo: el 20 de agosto de 2023. Dónde: en el Estadio Australia de Sídney. Cómo: venciendo 1-0 a Inglaterra en la final. Por qué es importante: es el primer Mundial de la selección femenina.", lineas: 3 },
      { tipo: "opinion", q: "¿Recibe el deporte femenino la misma atención que el masculino? ¿Por qué?", r: "Respuesta libre. Valorar que argumente con ejemplos.", lineas: 2 },
      { tipo: "reflexion", q: "Los deportistas famosos son un ejemplo para mucha gente. ¿Qué valores deben transmitir?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "noticia-03-ciguenas-colegio",
    titulo: "Cigüeñas en el tejado",
    subtipo: "Noticia local",
    curso: "5º",
    fuente: "Noticia inventada para esta ficha (el colegio, la localidad y las personas son ficticios)",
    antes: "¿Has visto alguna vez un nido de cigüeña? ¿Dónde suelen construirlo?",
    texto: [
      { titular: "Una pareja de cigüeñas retrasa las obras del tejado de un colegio", subtitulo: "Las aves han construido su nido sobre la chimenea del CEIP El Molino y la reforma tendrá que esperar hasta el verano", entradilla: "Torrecilla de la Vega (Sevilla), 2 de marzo. Las obras para reparar el tejado del CEIP El Molino, que debían comenzar ayer, se han aplazado hasta julio porque una pareja de cigüeñas blancas ha construido un gran nido sobre la antigua chimenea del edificio y ya está incubando sus huevos." },
      { p: "Los obreros llegaron el lunes a primera hora con andamios y herramientas, pero al subir al tejado se encontraron con dos inquilinos inesperados. El nido, hecho de ramas, paja y barro, mide casi un metro de ancho y ocupa toda la chimenea. «Nos quedamos con la boca abierta. Uno de los pájaros se levantó, nos miró y empezó a hacer ruido con el pico, como diciendo: aquí mando yo», cuenta entre risas uno de los albañiles." },
      { p: "No es la primera vez que las cigüeñas eligen el pueblo. Desde hace años, varias parejas crían en la torre del antiguo silo y en las torres de la luz de las afueras. «Nuestros abuelos decían que las cigüeñas llegaban por San Blas, a principios de febrero. Ahora muchas ni se van», comenta la directora del colegio, Pilar Navas." },
      { p: "La cigüeña blanca es una especie protegida, por lo que está prohibido molestarla o retirar su nido mientras cría. «No podemos tocar nada hasta que los pollos aprendan a volar y abandonen el nido», explicó el concejal de Obras del municipio, Andrés Castaño. Según los técnicos de medio ambiente, eso ocurrirá, previsiblemente, a principios del verano." },
      { h: "Un calendario marcado por las aves" },
      { p: "Los técnicos explican que las cigüeñas incuban los huevos durante alrededor de un mes, turnándose el macho y la hembra. Cuando nacen, los pollos pasan unos dos meses en el nido, alimentados por sus padres, hasta que sus alas son lo bastante fuertes para volar. Muchas parejas, además, vuelven cada año al mismo nido y lo agrandan con nuevas ramas, por eso algunos nidos llegan a ser enormes. Tradicionalmente, las cigüeñas blancas pasaban el invierno en África, pero desde hace unas décadas muchas se quedan todo el año en la península, porque encuentran comida suficiente en arrozales, campos y vertederos." },
      { p: "Mientras tanto, las goteras se arreglarán desde dentro del edificio con una reparación provisional, y las obras grandes se harán en julio, cuando no haya clases. Así, además, los alumnos no tendrán que soportar el ruido de las máquinas. Según el Ayuntamiento, el cambio de fechas no encarecerá la reforma. Cuando empiecen los trabajos, los obreros limpiarán la chimenea con cuidado, pero dejarán una plataforma firme para que las aves puedan volver a construir su nido el próximo año, si así lo decide el colegio." },
      { h: "Una clase con vistas al nido" },
      { p: "En el colegio, la noticia se ha recibido con entusiasmo. Los alumnos de 5.º, con ayuda de su maestro, han colocado una cámara en el patio para observar el nido desde la pizarra digital. «Ya les hemos puesto nombre: Paca y Paco», cuenta Adrián, de 11 años, muy orgulloso. Cada mañana, un encargado apunta en un cuaderno lo que hacen las aves: si están las dos en el nido, si traen ramas o si se turnan para dar calor a los huevos." },
      { lista: ["Mirar el nido desde el patio o a través de la cámara, nunca desde el tejado.", "No hacer ruidos fuertes ni lanzar objetos hacia la chimenea.", "Apuntar cada día lo que se observa, con fecha y hora.", "Avisar a un maestro si se ve un pollo o un huevo fuera del nido."], titulo: "Normas de la clase para observar el nido" },
      { p: "Esta semana, todo el alumnado votará si la chimenea seguirá siendo un «hotel de cigüeñas» después de la reforma. Por ahora, el sí va ganando por mucha diferencia, y en los pasillos ya se ven carteles pidiendo el voto para Paca y Paco." },
    ],
    vocabulario: [
      { p: "aplazar", d: "dejar algo para más adelante" },
      { p: "incubar", d: "dar calor a los huevos para que nazcan las crías" },
      { p: "provisional", d: "que sirve solo durante un tiempo, hasta que haya una solución definitiva" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué no se puede quitar el nido?", r: "Porque la cigüeña blanca es una especie protegida y está prohibido molestarla o retirar su nido mientras cría.", lineas: 1 },
      { tipo: "comprension", q: "¿Cuánto dura la incubación y cuánto tiempo pasan los pollos en el nido? ¿Por qué eso explica que las obras sean en julio?", r: "La incubación dura alrededor de un mes y los pollos pasan unos dos meses en el nido. Si los huevos se incuban en marzo, los pollos no volarán hasta el comienzo del verano.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que las obras «se han aplazado»? Elige:", opciones: ["Que se han dejado para más adelante", "Que se han cancelado para siempre", "Que se van a hacer más deprisa"], r: "Que se han dejado para más adelante" },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: se aplazan las obras del tejado. Quién: el Ayuntamiento y el colegio, por una pareja de cigüeñas. Cuándo: las obras debían empezar ayer (1 de marzo) y se harán en julio. Dónde: en el CEIP El Molino de Torrecilla de la Vega (Sevilla). Cómo: con una reparación provisional mientras tanto. Por qué: porque las cigüeñas son una especie protegida y están criando.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece bien que se retrasen unas obras por un nido? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante proteger a los animales, aunque a veces nos causen alguna molestia?", r: "Respuesta libre. Valorar que hable de biodiversidad y de convivir con la naturaleza.", lineas: 2 },
    ],
  },
  {
    id: "noticia-04-tesoro-carambolo",
    titulo: "El tesoro de El Carambolo",
    subtipo: "Noticia de historia",
    curso: "5º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (hallazgo del tesoro de El Carambolo, 30 de septiembre de 1958)",
    datos: ["Historia National Geographic: artículo sobre el origen del tesoro de El Carambolo", "Wikipedia en español: «Tesoro de El Carambolo» (descubridor, estudio de Juan de Mata Carriazo, análisis de 2018 sobre el origen del oro, lugar donde se guarda y réplicas)"],
    antes: "¿Qué hace un arqueólogo? ¿Qué harías si encontraras algo muy antiguo enterrado?",
    texto: [
      { titular: "El tesoro de El Carambolo cumple 65 años", subtitulo: "Unos obreros encontraron por casualidad, cerca de Sevilla, uno de los conjuntos de joyas de oro más importantes de la Antigüedad en la península ibérica", entradilla: "Camas (Sevilla), 30 de septiembre de 2023. Hoy se cumplen 65 años del hallazgo del tesoro de El Carambolo, un conjunto de 21 joyas de oro que unos obreros descubrieron por casualidad el 30 de septiembre de 1958 mientras hacían unas obras en el cerro de El Carambolo, en Camas, a unos tres kilómetros de Sevilla." },
      { p: "Aquel día, los trabajadores estaban ampliando el edificio de una sociedad de tiro. Mientras cavaban, uno de ellos, Alonso Hinojo del Pino, vio un objeto metálico entre la tierra: era un brazalete de oro. Siguieron excavando y encontraron una vasija de barro que guardaba el resto de las piezas." },
      { p: "El estudio de las joyas y de la zona lo dirigió el arqueólogo Juan de Mata Carriazo. Impresionado por su belleza, Carriazo lo describió como un tesoro digno de Argantonio, el legendario rey de Tartessos del que hablaban los antiguos historiadores griegos." },
      { h: "Casi tres kilos de oro" },
      { p: "Todas las piezas son de oro de 24 quilates, es decir, de oro prácticamente puro, y en total pesan unos 2.950 gramos, casi tres kilos. Fabricarlas exigió un trabajo de orfebrería de enorme precisión." },
      { tabla: { titulo: "Piezas del tesoro de El Carambolo", cab: ["Tipo de pieza", "Número"], filas: [["Placas", "16"], ["Pectorales", "2"], ["Collar", "1"], ["Brazaletes", "2"], ["Total", "21"]] } },
      { p: "Los arqueólogos creen que las joyas se fabricaron entre los siglos VII y VI antes de Cristo, hace más de 2.500 años, en la época de Tartessos, una cultura que se desarrolló en el suroeste de la península. Probablemente las llevaba una persona muy importante durante ceremonias religiosas o políticas." },
      { p: "Tartessos sigue siendo una de las culturas más misteriosas de la Antigüedad. Los antiguos griegos hablaban de un reino muy rico en metales situado en el extremo occidental del mundo que conocían, más allá del estrecho de Gibraltar. Por eso, cada hallazgo como el de El Carambolo ayuda a los historiadores a separar lo que es leyenda de lo que ocurrió de verdad." },
      { h: "Un oro de aquí" },
      { p: "Durante años se discutió si el oro había llegado de tierras lejanas. En 2018, un equipo de investigación analizó pequeños fragmentos de las joyas y comprobó que el oro procedía probablemente de las mismas minas que el de otras piezas encontradas en Valencina de la Concepción, también en la provincia de Sevilla. Es decir, el tesoro se hizo con oro de la zona, aunque con técnicas que mezclaban tradiciones de distintas culturas." },
      { p: "Hoy, el tesoro pertenece al Ayuntamiento de Sevilla. En el Museo Arqueológico de Sevilla se expone una réplica, porque el original, por su enorme valor, se guarda en la caja fuerte de un banco y solo se ha mostrado al público en contadas ocasiones, como durante la Exposición Universal de Sevilla de 1992." },
      { p: "Los expertos recuerdan que, si alguien encuentra restos arqueológicos, no debe llevárselos ni seguir cavando: tiene que avisar a las autoridades para que los estudien y los protejan. Gracias a eso, hoy todos podemos conocer mejor a quienes vivieron en Andalucía hace miles de años." },
    ],
    vocabulario: [
      { p: "hallazgo", d: "descubrimiento de algo" },
      { p: "pectoral", d: "adorno que se lleva colgado sobre el pecho" },
      { p: "orfebrería", d: "arte de trabajar el oro, la plata y otros metales para hacer joyas y objetos" },
      { p: "réplica", d: "copia exacta de una obra" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué pasó el 30 de septiembre de 1958? ¿Por qué fue «por casualidad»?", r: "Unos obreros encontraron el tesoro de El Carambolo en Camas (Sevilla). Fue por casualidad porque no buscaban ningún tesoro: estaban haciendo obras en un edificio.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué descubrió la investigación de 2018 sobre el oro del tesoro?", r: "Que el oro procedía probablemente de minas de la zona, las mismas que el de las piezas de Valencina de la Concepción (Sevilla); no había llegado de tierras lejanas.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que en el museo se expone una réplica y no el original?", r: "Por seguridad: el original tiene un valor enorme y así se evitan robos o daños.", lineas: 1 },
      { tipo: "texto", q: "Responde a las 6 preguntas sobre el hallazgo: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué es importante?", r: "Qué: el hallazgo de un tesoro de 21 joyas de oro. Quién: unos obreros (el primero en verlo fue Alonso Hinojo del Pino). Cuándo: el 30 de septiembre de 1958. Dónde: en el cerro de El Carambolo, en Camas (Sevilla). Cómo: por casualidad, cavando durante unas obras. Por qué es importante: es uno de los conjuntos de oro más importantes de la Antigüedad y nos ayuda a conocer Tartessos.", lineas: 3 },
      { tipo: "opinion", q: "Si encontraras algo muy antiguo enterrado, ¿qué harías? ¿Por qué?", r: "Respuesta libre. Valorar que mencione avisar a las autoridades.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es mejor que los restos del pasado se conserven en museos, en vez de que cada uno se quede con lo que encuentra?", r: "Respuesta libre. Valorar la idea de patrimonio común.", lineas: 2 },
    ],
  },
  {
    id: "noticia-05-recicla-bot",
    titulo: "Recicla-Bot",
    subtipo: "Noticia de tecnología",
    curso: "5º",
    fuente: "Noticia inventada para esta ficha (el colegio, el concurso y las personas son ficticios)",
    antes: "¿Sabes en qué contenedor va cada residuo? ¿Crees que un robot podría aprender a separarlos?",
    texto: [
      { titular: "Un robot que separa la basura da la victoria a un colegio de Almería", subtitulo: "Seis alumnos de 5.º del CEIP Las Salinas ganan el concurso provincial de robótica escolar con su invento, Recicla-Bot", entradilla: "Almería, 23 de mayo. Un equipo de seis alumnos de 5.º del CEIP Las Salinas ganó ayer el primer premio del concurso provincial de robótica escolar, celebrado en un pabellón de la ciudad, con un robot capaz de reconocer y separar envases, papel y restos orgánicos." },
      { p: "El robot, al que han llamado Recicla-Bot, tiene el tamaño de una caja de zapatos. Cuando alguien coloca un residuo en su bandeja, un sensor de color y otro de peso analizan el objeto, y un brazo mecánico lo empuja hacia el cubo correcto: amarillo, azul o marrón." },
      { lista: ["Una persona deja el residuo en la bandeja del robot.", "El sensor de color mira el objeto y el sensor de peso lo pesa.", "El programa compara esos datos con los que tiene guardados.", "El brazo mecánico empuja el residuo hacia el cubo que corresponde.", "Una luz verde se enciende si el robot está seguro; si duda, se enciende una luz naranja y pide ayuda a una persona."], ordenada: true, titulo: "Así funciona Recicla-Bot" },
      { p: "El equipo, formado por tres niñas y tres niños de 10 y 11 años, que se reparten las tareas de construcción, programación y presentación, trabajó en el proyecto durante cuatro meses, por las tardes, con piezas de un kit de robótica que el colegio ya tenía. «Lo más difícil fue programarlo para que no confundiera un brik con un cartón», explica Daniela Cortés, una de las integrantes. «Al principio lo mandaba todo al cubo azul. Tuvimos que probar más de cien residuos distintos hasta que aprendió», añade su compañero Héctor Pardo." },
      { h: "Una final muy reñida" },
      { p: "Al concurso se presentaron dieciocho equipos de toda la provincia. Había robots que regaban plantas, que ayudaban a cruzar la calle y hasta uno que tocaba el tambor. Cada equipo tenía cinco minutos para explicar su invento y otros cinco para demostrar que funcionaba. El jurado valoró la originalidad de la idea, el funcionamiento del robot y la presentación oral de los alumnos. En la prueba final, Recicla-Bot acertó con diecinueve de los veinte residuos que le pusieron. Solo falló con una servilleta de papel manchada de aceite, que envió al cubo azul." },
      { p: "«Ese fallo nos enseñó algo: el papel sucio de grasa no se recicla con el papel limpio. Lo vamos a corregir», explicó Daniela ante el jurado. Los miembros del jurado aplaudieron esa respuesta, porque demostraba que el equipo entendía de verdad el problema. Cuando anunciaron el primer premio, las familias que habían viajado para verlos saltaron de sus asientos. «Mi hija se pasaba las cenas hablando de sensores», contaba riendo la madre de una de las integrantes." },
      { p: "La idea nació después de una visita a una planta de reciclaje, donde los estudiantes vieron cuántos residuos llegan mal separados. «Si un robot tan pequeño puede aprenderlo, las personas también», bromea su maestro, Javier Fuentes." },
      { tabla: { titulo: "¿Dónde va cada residuo?", cab: ["Contenedor", "Qué se echa"], filas: [["Amarillo", "Envases de plástico, latas y briks"], ["Azul", "Papel y cartón limpios"], ["Verde", "Botellas y tarros de vidrio"], ["Marrón", "Restos orgánicos: cáscaras, restos de fruta…"]] } },
      { p: "Como premio, el colegio recibirá material de robótica para todos los cursos. En junio, el equipo presentará su invento a las familias y al resto del alumnado, y ya piensa en una nueva versión que reconozca también el vidrio. «Nos gustaría que algún día hubiera un Recicla-Bot en cada clase, aunque sea solo para recordarnos dónde va cada cosa», dice Daniela." },
    ],
    vocabulario: [
      { p: "sensor", d: "aparato que detecta algo (luz, color, peso…) y envía la información" },
      { p: "residuo", d: "lo que sobra o se tira después de usar algo" },
      { p: "jurado", d: "grupo de personas que decide quién gana un concurso" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Con qué residuo se equivocó Recicla-Bot en la final? ¿Qué aprendió el equipo de ese error?", r: "Con una servilleta de papel manchada de aceite, que mandó al cubo azul. Aprendieron que el papel sucio de grasa no se recicla con el papel limpio.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que era difícil que el robot distinguiera un brik de un cartón?", r: "Porque se parecen en color y en peso, pero van a contenedores diferentes: el brik al amarillo y el cartón al azul.", lineas: 2 },
      { tipo: "comprension", q: "Recicla-Bot acertó con 19 de los 20 residuos. Eso significa que… Elige:", opciones: ["se equivocó una vez", "se equivocó diecinueve veces", "no se equivocó nunca"], r: "se equivocó una vez" },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: un colegio gana el concurso provincial de robótica. Quién: seis alumnos de 5.º del CEIP Las Salinas. Cuándo: ayer (22 de mayo). Dónde: en Almería. Cómo: con un robot que separa residuos. Por qué: el jurado valoró su originalidad, su funcionamiento y la presentación; la idea surgió al ver residuos mal separados.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué robot inventarías tú para resolver un problema de tu colegio o de tu barrio? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Deberían los robots separar la basura por nosotros, o es mejor que aprendamos a hacerlo? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "noticia-06-perseverance-marte",
    titulo: "Perseverance llega a Marte",
    subtipo: "Noticia científica",
    curso: "5º-6º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (aterrizaje de Perseverance, 18 de febrero de 2021)",
    datos: ["NASA Ciencia (ciencia.nasa.gov y science.nasa.gov): misión Mars 2020 Perseverance y helicóptero Ingenuity", "NASA JPL: Mars 2020 Launch Press Kit", "CSIC y Centro de Astrobiología (CAB, CSIC-INTA): instrumento MEDA", "Wikipedia en inglés: «Perseverance (rover)» (cámaras, micrófonos, instrumentos, concurso para darle nombre y roca Cheyava Falls)"],
    antes: "¿Qué sabes de Marte? ¿Crees que alguna vez hubo vida allí?",
    texto: [
      { titular: "Perseverance ya está en Marte", subtitulo: "El vehículo de la NASA, que lleva a bordo una estación meteorológica fabricada en España, buscará señales de vida antigua en el planeta rojo", entradilla: "Pasadena (Estados Unidos), 18 de febrero de 2021. El vehículo explorador Perseverance, de la NASA, ha aterrizado hoy con éxito en el cráter Jezero de Marte, tras un viaje de casi siete meses. Su misión es buscar rastros de vida microscópica antigua y recoger muestras de rocas que en el futuro podrían traerse a la Tierra." },
      { p: "Perseverance despegó el 30 de julio de 2020 desde Cabo Cañaveral, en Florida, a bordo de un cohete Atlas V. El momento más difícil llegó al final: en solo siete minutos, la nave tuvo que frenar desde miles de kilómetros por hora hasta posarse con suavidad. Para lograrlo usó un escudo contra el calor, un paracaídas gigante y una especie de grúa voladora que bajó el vehículo colgado de cables. Como las señales de radio tardan varios minutos en viajar entre Marte y la Tierra, nadie podía manejarlo desde aquí: todo lo hizo la nave de forma automática." },
      { p: "En la sala de control, los ingenieros siguieron el descenso en silencio, mirando las pantallas. Cuando llegó la confirmación de que el vehículo estaba en el suelo, estallaron los aplausos, los gritos de alegría y los abrazos, después de años de trabajo." },
      { h: "Un laboratorio sobre ruedas" },
      { p: "El explorador tiene seis ruedas, es del tamaño de un coche y pesa alrededor de una tonelada. Lleva siete instrumentos científicos principales, un brazo robótico, 19 cámaras y dos micrófonos, que permitirán escuchar los sonidos de Marte. Su energía no procede de paneles solares, sino de un generador que produce electricidad a partir del calor de un material radiactivo." },
      { p: "Uno de esos instrumentos es MEDA, una estación meteorológica cuyo desarrollo ha dirigido el Centro de Astrobiología, en Madrid. MEDA medirá el viento, la temperatura, la presión, la humedad, la radiación del Sol y el polvo del aire marciano." },
      { p: "Los científicos eligieron el cráter Jezero porque hace miles de millones de años fue un lago. Si alguna vez hubo vida en Marte, quizá quedaron huellas de ella en el fondo de ese antiguo lago." },
      { p: "Para investigarlo, el vehículo perforará las rocas y guardará las muestras en 43 tubos especiales, que una futura misión podría recoger y traer a la Tierra. Además, uno de sus experimentos, llamado MOXIE, intentará fabricar oxígeno a partir del aire de Marte, que está formado casi todo por dióxido de carbono. Si funciona, esa tecnología podría servir algún día para que los futuros astronautas respiren en el planeta rojo o fabriquen combustible para volver a casa." },
      { h: "Un nombre elegido por un estudiante" },
      { p: "El nombre del vehículo no lo eligieron los científicos. La NASA organizó un concurso en el que participaron estudiantes de todo Estados Unidos con más de 28.000 redacciones. Ganó Alexander Mather, un alumno de séptimo curso de Virginia, que propuso la palabra perseverance, que en inglés significa perseverancia: la capacidad de seguir adelante aunque las cosas sean difíciles." },
      { p: "Perseverance transporta, además, un pequeño helicóptero llamado Ingenuity, cuyo nombre también propuso una estudiante, Vaneeza Rupani, de Alabama. Ingenuity intentará ser el primer aparato en realizar un vuelo controlado en otro planeta." },
      { dato: "Después de esta noticia: el 19 de abril de 2021, Ingenuity consiguió volar. Estaba previsto que hiciera como mucho cinco vuelos, pero llegó a completar 72 en casi tres años. El experimento MOXIE también funcionó: logró fabricar oxígeno. Y en julio de 2024, Perseverance encontró una roca con posibles señales de vida antigua, que los científicos siguen estudiando." },
    ],
    vocabulario: [
      { p: "cráter", d: "hoyo grande y redondo en la superficie de un planeta" },
      { p: "microscópico", d: "tan pequeño que solo se ve con microscopio" },
      { p: "meteorológico", d: "relacionado con el tiempo atmosférico: lluvia, viento, temperatura…" },
      { p: "perseverancia", d: "constancia para seguir intentando algo aunque sea difícil" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué eligieron los científicos el cráter Jezero?", r: "Porque hace miles de millones de años fue un lago, y allí podrían quedar huellas de vida.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué nadie podía manejar la nave desde la Tierra al aterrizar?", r: "Porque las señales tardan varios minutos en viajar entre Marte y la Tierra, y el aterrizaje duraba solo siete minutos: la nave tuvo que hacerlo todo de forma automática.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que Alexander Mather eligió el nombre «Perseverance» para una misión a Marte?", r: "Porque significa seguir adelante aunque las cosas sean difíciles, y explorar Marte exige mucho esfuerzo, paciencia y no rendirse ante los problemas.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: aterriza un vehículo explorador. Quién: Perseverance, de la NASA. Cuándo: el 18 de febrero de 2021. Dónde: en el cráter Jezero de Marte. Cómo: frenando con escudo, paracaídas y una grúa voladora. Por qué: para buscar rastros de vida antigua y recoger muestras.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que merece la pena dedicar dinero a explorar otros planetas? Da razones.", r: "Respuesta libre. Valorar que aporte argumentos a favor o en contra.", lineas: 2 },
      { tipo: "reflexion", q: "Si leyeras en internet que hay un extraterrestre en Marte, ¿cómo comprobarías si es verdad?", r: "Respuesta libre. Valorar que proponga fuentes oficiales (NASA, ESA, centros de investigación) y medios fiables, y comparar varias fuentes.", lineas: 2 },
    ],
  },
  {
    id: "noticia-07-dolmenes-antequera",
    titulo: "Los dólmenes de Antequera",
    subtipo: "Noticia de cultura",
    curso: "5º-6º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (declaración de Patrimonio Mundial, 15 de julio de 2016)",
    datos: ["Ministerio de Cultura: «La UNESCO declara Patrimonio Mundial el Sitio de los Dólmenes de Antequera» (15/07/2016)", "UNESCO, Centro del Patrimonio Mundial: Sitio de los Dólmenes de Antequera (n.º 1501)", "Junta de Andalucía: Sitio de los Dólmenes de Antequera, Patrimonio Mundial", "Wikipedia en español: «Dolmen de Menga» y «Sitio de los Dólmenes de Antequera» (medidas, fecha de construcción, pozo y orientación de El Romeral)"],
    antes: "¿Sabes qué es un dolmen? ¿Cómo crees que se movían piedras enormes hace miles de años?",
    texto: [
      { titular: "Los dólmenes de Antequera, Patrimonio Mundial", subtitulo: "La UNESCO reconoce el valor excepcional de estos monumentos de la Prehistoria y del paisaje que los rodea", entradilla: "Estambul (Turquía), 15 de julio de 2016. El Comité del Patrimonio Mundial de la UNESCO, reunido en Estambul, ha incluido hoy el Sitio de los Dólmenes de Antequera (Málaga) en la Lista del Patrimonio Mundial, que reúne los lugares de mayor valor cultural y natural del planeta." },
      { p: "El conjunto está formado por tres monumentos construidos por los antiguos pobladores de la zona: los dólmenes de Menga y de Viera y el tholos de El Romeral. También incluye dos lugares naturales: la Peña de los Enamorados y El Torcal de Antequera." },
      { p: "Los dólmenes son grandes construcciones de piedra levantadas en la Prehistoria, que se usaban como sepulcros y, probablemente, como lugares de reunión. Para construirlos, aquellos pobladores movieron enormes losas de piedra sin grúas ni máquinas, con cuerdas, rampas, troncos y mucho trabajo en equipo." },
      { h: "Menga, un gigante de piedra" },
      { p: "El más famoso es el dolmen de Menga, construido hace unos 5.700 años, en el Neolítico. Mide 27,5 metros de largo, y su cámara del fondo alcanza 3,5 metros de altura y 6 metros de anchura: cabría dentro una clase entera. Sus paredes están hechas con grandes piedras verticales y el techo, con enormes losas horizontales. La última de ellas pesa, según los cálculos, unas 150 toneladas, tanto como más de cien coches juntos. Al fondo de la cámara hay, además, un pozo profundo y estrecho que todavía hoy despierta preguntas entre los investigadores." },
      { tabla: { titulo: "Los monumentos del Sitio de los Dólmenes", cab: ["Monumento", "Tipo", "Dato destacado"], filas: [["Menga", "Dolmen", "Mide 27,5 m de largo y su entrada mira a la Peña de los Enamorados"], ["Viera", "Dolmen", "Está junto a Menga, en el mismo recinto"], ["El Romeral", "Tholos", "Su entrada mira a la sierra de El Torcal"]] } },
      { p: "Una de las razones de la UNESCO es muy especial. La mayoría de los dólmenes de Europa están orientados hacia el lugar por donde sale el sol. En cambio, la entrada de Menga mira hacia la Peña de los Enamorados, una montaña cuya silueta recuerda el perfil de una cara humana tumbada. Y El Romeral apunta hacia la sierra de El Torcal. Son casos únicos, que demuestran que aquellos pueblos unían sus monumentos con el paisaje." },
      { p: "Los dos parajes naturales del conjunto son también muy especiales. La Peña de los Enamorados se ve desde muchos kilómetros a la redonda y fue una referencia para los habitantes de la comarca durante miles de años. El Torcal de Antequera, muy visitado por excursionistas y escolares, es famoso por sus rocas de piedra caliza, que la lluvia y el viento han ido modelando muy lentamente hasta crear figuras que parecen torres, animales o montones de platos." },
      { p: "Menga se conoce desde hace siglos. Ya en los siglos XVII y XVIII aparecía en libros de historia, y en 1847 se escribió el primer estudio científico sobre él. Desde mediados del siglo XX se han hecho numerosos trabajos para conservarlo y facilitar las visitas. Hoy, quien entra en Menga suele quedarse en silencio unos segundos: cuesta creer que aquellas piedras gigantes se colocaran a mano, sin ninguna máquina, hace casi seis milenios." },
      { p: "Con esta declaración, Andalucía suma un nuevo lugar a la Lista del Patrimonio Mundial, en la que ya figuraban monumentos como la Alhambra de Granada o la Mezquita de Córdoba." },
      { p: "El reconocimiento supone también una responsabilidad: los lugares declarados Patrimonio Mundial deben protegerse y conservarse para que puedan conocerlos las generaciones futuras." },
    ],
    vocabulario: [
      { p: "dolmen", d: "construcción prehistórica hecha con grandes piedras, usada como sepulcro" },
      { p: "sepulcro", d: "lugar donde se entierra a una persona" },
      { p: "tholos", d: "sepulcro prehistórico con una cámara redonda cubierta por una falsa cúpula" },
      { p: "silueta", d: "forma o contorno de algo visto desde lejos" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué construir Menga fue una gran hazaña? Usa un dato de la noticia.", r: "Porque movieron losas enormes (la última pesa unas 150 toneladas) sin máquinas, solo con cuerdas, rampas, troncos y el esfuerzo de mucha gente organizada.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué tienen de especial las entradas de Menga y de El Romeral?", r: "Que no miran hacia donde sale el sol, como la mayoría de los dólmenes, sino hacia elementos del paisaje: Menga, a la Peña de los Enamorados, y El Romeral, a El Torcal.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué responsabilidad supone ser Patrimonio Mundial?", r: "Proteger y conservar el lugar para que puedan conocerlo las generaciones futuras.", lineas: 1 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: los dólmenes de Antequera son declarados Patrimonio Mundial. Quién: el Comité del Patrimonio Mundial de la UNESCO. Cuándo: el 15 de julio de 2016. Dónde: la reunión fue en Estambul; los dólmenes están en Antequera (Málaga). Cómo: incluyéndolos en la Lista del Patrimonio Mundial. Por qué: por su valor excepcional y su relación única con el paisaje.", lineas: 3 },
      { tipo: "opinion", q: "¿Es bueno que vayan muchos turistas a un lugar así? Da una razón a favor y otra en contra.", r: "Respuesta libre. Valorar que equilibre el beneficio económico y cultural con el cuidado del lugar.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué es importante cuidar lo que construyeron personas de hace miles de años?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "noticia-08-lince-iberico",
    titulo: "El regreso del lince",
    subtipo: "Noticia de medio ambiente",
    curso: "6º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (censo de lince ibérico de 2024, publicado en mayo de 2025)",
    datos: ["MITECO: Censo de lince ibérico en España y Portugal 2024 (informe publicado el 16/05/2025) y nota de prensa «La población de linces ibéricos creció un 19 % en 2024 respecto al año anterior» (22/05/2025)", "Agencia SINC: «Los linces ibéricos aumentan su población un 19 % en 2024 con más de 2.400 ejemplares»", "WWF: el lince ibérico pasa de «en peligro» a «vulnerable» en la Lista Roja de la UICN (2024)", "Wikipedia en inglés: «Iberian lynx» (aspecto, peso y alimentación)"],
    antes: "¿Qué sabes del lince ibérico? ¿Por qué crees que llegó a estar a punto de desaparecer?",
    texto: [
      { titular: "El lince ibérico bate su récord: ya hay más de 2.400", subtitulo: "El censo de 2024 registra 2.401 ejemplares en España y Portugal, un 19 % más que el año anterior. Hace poco más de veinte años quedaban menos de cien", entradilla: "Madrid, mayo de 2025. El lince ibérico, uno de los felinos más amenazados del planeta hace dos décadas, sigue recuperándose. Según el censo de 2024, presentado por el Ministerio para la Transición Ecológica, en la península ibérica viven 2.401 linces, la cifra más alta desde que se hacen recuentos." },
      { p: "El dato confirma una recuperación que parecía imposible. En 2002, los expertos contaron menos de cien ejemplares, repartidos en dos pequeñas poblaciones de Andalucía: Doñana y Sierra Morena. Entonces se temía que el lince desapareciera para siempre, como ya había ocurrido con otros animales en otras partes del mundo." },
      { p: "El lince ibérico solo vive en la península ibérica. Se reconoce por los pinceles de pelo negro de sus orejas, las patillas que le rodean la cara, las patas largas, la cola corta y el pelaje con manchas. Los machos pesan entre 7 y 16 kilos, y las hembras son algo más pequeñas. Su alimento principal es el conejo: un macho necesita un conejo al día, y una hembra que cría a sus cachorros, unos tres." },
      { p: "Contar linces no es fácil, porque son animales esquivos que se mueven sobre todo al amanecer y al anochecer. Los equipos de seguimiento recorren el monte buscando huellas y excrementos, y colocan cámaras que se disparan solas al paso de los animales, de día y de noche. Como el dibujo de manchas de cada lince es diferente, las fotografías permiten reconocer a cada ejemplar, casi como si fuera su huella dactilar." },
      { h: "Veinte años de trabajo en equipo" },
      { p: "Desde principios de este siglo, administraciones, científicos, asociaciones y propietarios de fincas han trabajado juntos. Se criaron linces en cuatro centros especiales: El Acebuche, en Doñana (Huelva); La Olivilla (Jaén); Zarza de Granadilla (Cáceres), y Silves, en Portugal. Desde 2011 se han liberado 403 linces nacidos en esos centros en zonas bien elegidas de Andalucía, Extremadura, Castilla-La Mancha y Portugal, y más recientemente en Murcia y Castilla y León. También se ha ayudado a recuperar al conejo." },
      { tabla: { titulo: "Linces ibéricos censados", cab: ["Año", "Ejemplares"], filas: [["2002", "menos de 100"], ["2020", "1.111"], ["2023", "2.021"], ["2024", "2.401"]] }, nota: "Fuente: censos oficiales de lince ibérico (MITECO)." },
      { p: "Del total de 2024, 2.047 linces viven en España y 354 en Portugal, repartidos por varias comunidades autónomas. Castilla-La Mancha es la comunidad con más ejemplares (942), seguida de Andalucía, donde empezó la recuperación y donde viven 836, más de un tercio del total. Ese año nacieron 844 cachorros y se contaron 470 hembras reproductoras." },
      { p: "Gracias a estos esfuerzos, en 2024 la Unión Internacional para la Conservación de la Naturaleza (UICN) cambió la categoría del lince: dejó de estar «en peligro» y pasó a ser «vulnerable». Sigue amenazado, pero su situación es mucho mejor. Para considerar que la especie está a salvo, los expertos se han marcado como objetivo llegar a 750 hembras reproductoras." },
      { p: "Sin embargo, el trabajo no ha terminado. En 2024 murieron 214 linces, y tres de cada cuatro de esas muertes se debieron a atropellos en carreteras y caminos. Por eso los expertos piden construir más pasos para fauna bajo las carreteras, reducir la velocidad en las zonas donde vive y seguir cuidando su hábitat, el monte mediterráneo." },
    ],
    vocabulario: [
      { p: "censo", d: "recuento oficial de personas o de animales" },
      { p: "ejemplar", d: "cada uno de los individuos de una especie" },
      { p: "hábitat", d: "lugar con las condiciones adecuadas para que viva una especie" },
      { p: "paso para fauna", d: "túnel o puente que permite a los animales cruzar una carretera sin peligro" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Mira la tabla. ¿Cuántos linces más había en 2024 que en 2020? ¿Qué te dice eso?", r: "1.290 más (2.401 - 1.111). Que en pocos años la población ha crecido muchísimo: se ha más que duplicado.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que recuperar al conejo era tan importante para salvar al lince?", r: "Porque el conejo es su alimento principal: sin conejos, los linces no pueden sobrevivir ni criar a sus cachorros.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuál es hoy el mayor peligro para el lince?", r: "Los atropellos en carreteras y caminos: causaron tres de cada cuatro muertes en 2024.", lineas: 1 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: el lince ibérico alcanza su récord de población. Quién: el lince; lo presenta el Ministerio para la Transición Ecológica. Cuándo: censo de 2024, presentado en mayo de 2025. Dónde: en España y Portugal (península ibérica). Cómo: gracias a la cría en centros, las liberaciones y la recuperación del conejo. Por qué es noticia: hace veinte años quedaban menos de cien.", lineas: 3 },
      { tipo: "opinion", q: "¿Merece la pena dedicar tanto dinero y esfuerzo a salvar una especie? ¿Por qué?", r: "Respuesta libre. Valorar que hable de biodiversidad y equilibrio de los ecosistemas.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué nos enseña la historia del lince sobre el trabajo en equipo?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "noticia-09-bulo-cocodrilo",
    titulo: "El cocodrilo que nunca existió",
    subtipo: "Noticia sobre un bulo",
    curso: "6º",
    fuente: "Noticia inventada para esta ficha (el suceso y las personas son ficticios)",
    antes: "¿Qué es una noticia falsa o bulo? ¿Te ha llegado alguna vez un mensaje que resultó ser mentira?",
    texto: [
      { titular: "No, no hay ningún cocodrilo en el río Guadalete", subtitulo: "Una fotografía trucada, compartida miles de veces en redes sociales y grupos de mensajería, causó alarma entre los vecinos de varios pueblos", entradilla: "Jerez de la Frontera (Cádiz), 12 de junio. Los técnicos de medio ambiente y la policía local han confirmado que la fotografía de un cocodrilo tomando el sol en la orilla del río Guadalete, que circula desde el pasado fin de semana por internet, es falsa. La imagen había sido manipulada con un programa de edición." },
      { p: "Todo empezó el sábado por la tarde, cuando alguien publicó la foto con un mensaje alarmante: «¡Cuidado! Han visto un cocodrilo en el Guadalete. Que nadie se bañe ni pasee a los perros por la orilla. ¡Pásalo!». En pocas horas, la imagen se había compartido miles de veces. Algunos vecinos llamaron asustados al teléfono de emergencias y varias familias suspendieron sus planes del domingo junto al río." },
      { tabla: { titulo: "Cómo se extendió el bulo", cab: ["Momento", "Qué pasó"], filas: [["Sábado, 18:00", "Se publica la foto con el mensaje «¡Pásalo!»"], ["Sábado, 22:00", "La imagen ya se ha compartido miles de veces"], ["Domingo, 9:00", "Primeras llamadas de vecinos a emergencias"], ["Domingo, 12:00", "Los técnicos revisan la orilla del río"], ["Lunes", "Se analiza la foto y se descubre el montaje"]] }, nota: "Cronología elaborada a partir de los datos de la policía local." },
      { p: "Los técnicos revisaron la zona el domingo y no encontraron ninguna huella ni rastro del animal. Además, al analizar la imagen descubrieron que el cocodrilo procedía de una fotografía tomada en un zoológico: alguien lo había recortado y pegado sobre una foto del río. Por ejemplo, la sombra del animal y la de los árboles iban en direcciones distintas, y el borde del cocodrilo estaba demasiado nítido comparado con el resto de la imagen." },
      { p: "«Sería muy difícil que un cocodrilo sobreviviera en libertad en nuestros ríos durante el invierno, y todavía más que pasara desapercibido», explicó Marta Ruiz, bióloga del servicio de medio ambiente, que pidió a la población calma y sentido común." },
      { h: "Un fin de semana de nervios" },
      { p: "Carmen Villalba, vecina de una de las barriadas cercanas al río, reconoce que se lo creyó. «Me llegó por tres grupos distintos, el de la familia, el del trabajo y el de las madres del colegio. Pensé: si tanta gente lo manda, será verdad. Y lo reenvié yo también», admite. «Ahora me da vergüenza, porque no me paré a pensar ni un segundo». Su hijo de once años fue quien le hizo dudar: en clase habían aprendido a buscar el origen de una foto." },
      { p: "Ese es precisamente el problema, según los expertos: los bulos se aprovechan de las emociones, como el miedo o la sorpresa, y de la confianza que tenemos en quien nos los envía. Cuantas más veces vemos un mensaje, más fácil es creer que es cierto, aunque nadie lo haya comprobado." },
      { p: "Los expertos aprovechan este caso para recordar algunos consejos antes de compartir una información:" },
      { lista: ["Comprueba quién la publica y si aparece en medios de comunicación serios o en fuentes oficiales.", "Desconfía de los mensajes que buscan asustarte o que te piden «pásalo».", "Fíjate en la fecha y en los detalles de las fotos.", "Ante la duda, no la reenvíes."], titulo: "Antes de compartir, comprueba" },
      { p: "Todavía no se sabe quién creó el montaje. Las autoridades recuerdan que las informaciones falsas pueden causar problemas reales, como las llamadas innecesarias a los servicios de emergencia, que deben estar libres para quien de verdad los necesita." },
    ],
    vocabulario: [
      { p: "bulo", d: "noticia falsa que se difunde, a menudo para engañar o asustar" },
      { p: "trucada", d: "cambiada con trucos para que parezca otra cosa" },
      { p: "desapercibido", d: "sin que nadie lo note" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué pruebas demostraron que la foto estaba trucada?", r: "No había huellas ni rastros; el cocodrilo procedía de una foto de un zoológico, las sombras iban en direcciones distintas y el borde del animal era demasiado nítido.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Carmen creyó el bulo y lo reenvió? ¿Qué explican los expertos sobre esto?", r: "Porque le llegó por tres grupos distintos y pensó que, si tanta gente lo mandaba, sería verdad. Los expertos dicen que los bulos se aprovechan del miedo y de la confianza en quien los envía, y que ver muchas veces un mensaje hace que parezca cierto.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el mensaje falso terminaba con «¡Pásalo!»?", r: "Para que la gente lo reenviara deprisa, sin pararse a comprobar si era verdad, y así se difundiera mucho.", lineas: 1 },
      { tipo: "texto", q: "Compara el mensaje del bulo con esta noticia. ¿En qué se diferencian? Piensa en la fuente, los datos y el tono.", r: "El bulo no dice quién lo escribe, no da datos comprobables y busca asustar. La noticia cita fuentes (técnicos, policía, una bióloga, una vecina), explica cómo se comprobó y usa un tono tranquilo y objetivo.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que quien reenvía un bulo sin saberlo también tiene algo de responsabilidad? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
      { tipo: "reflexion", q: "¿Cuál de los consejos de la noticia te parece más útil para no dejarte engañar? ¿Por qué?", r: "Respuesta libre. Valorar que justifique su elección.", lineas: 2 },
    ],
  },
  {
    id: "noticia-10-limpieza-playa",
    titulo: "Voluntarios por la playa",
    subtipo: "Noticia de medio ambiente",
    curso: "6º",
    fuente: "Noticia inventada para esta ficha (los datos de la tabla y las personas son ficticios)",
    antes: "¿Qué tipo de basura has visto alguna vez en una playa, un río o un parque? ¿Cómo crees que llegó allí?",
    texto: [
      { titular: "Doscientos voluntarios retiran 180 kilos de basura de una playa de Huelva", subtitulo: "Alumnos de 6.º de tres colegios organizaron la limpieza y clasificaron los residuos para estudiarlos en clase", entradilla: "Punta Umbría (Huelva), 6 de octubre. Unas doscientas personas, entre alumnos, familias y vecinos, recogieron ayer por la mañana 180 kilos de basura en la playa de la localidad. La actividad fue organizada por los alumnos de 6.º de tres colegios del municipio, dentro de un proyecto escolar sobre la contaminación del mar." },
      { p: "La preparación empezó un mes antes. Los alumnos pidieron permiso al Ayuntamiento, diseñaron carteles para invitar a los vecinos, consiguieron guantes y bolsas y dividieron la playa en zonas en un plano. También prepararon unas fichas para anotar lo que encontraba cada grupo." },
      { p: "La jornada comenzó a las nueve y media. Los voluntarios, con guantes y bolsas reutilizables, se repartieron en grupos a lo largo de dos kilómetros de arena y de la zona de dunas. En las dunas trabajaron con especial cuidado: caminaron solo por las pasarelas de madera y no arrancaron ninguna planta, porque la vegetación sujeta la arena y la protege del viento. A mediodía llevaron todo lo recogido a una carpa, donde los alumnos lo pesaron y lo separaron por tipos." },
      { tabla: { titulo: "Residuos recogidos en la playa", cab: ["Tipo de residuo", "Cantidad"], filas: [["Colillas", "más de 3.000 unidades"], ["Plásticos (botellas, envases, bolsas)", "75 kg"], ["Latas y otros metales", "30 kg"], ["Vidrio", "25 kg"], ["Restos de redes y cuerdas", "20 kg"], ["Otros (ropa, papel, juguetes…)", "30 kg"]] }, nota: "Recuento realizado por los alumnos al terminar la jornada." },
      { p: "Lo que más sorprendió a los participantes fueron las colillas: contaron más de tres mil. «Parecen pequeñas, pero tienen sustancias tóxicas y tardan años en desaparecer», explica Iván Rodríguez, alumno de 6.º. También encontraron un balón, dos chanclas desparejadas y hasta un patito de goma." },
      { h: "De todas las edades" },
      { p: "Entre los voluntarios había bebés en carrito y personas mayores. Manuel Garrido, de 74 años, vecino de toda la vida, se emocionó al ver a tantos jóvenes trabajando. «Cuando yo era niño, en esta playa lo que encontrabas eran conchas. Hoy he encontrado más plástico que conchas. Me alegra que sean los chiquillos los que nos hayan despertado», contaba mientras cerraba su tercera bolsa." },
      { p: "La coordinadora del proyecto, la maestra Elena Márquez, recordó que gran parte de la basura que llega al mar procede de tierra firme: de lo que se tira en la calle, en el campo o en los ríos. «Lo que hemos recogido no es solo de quien viene a la playa; es de todos», señaló." },
      { p: "Por la tarde, ya en clase, cada grupo repasó sus fichas y comparó lo que había encontrado en su zona. Los que limpiaron junto a la desembocadura de un arroyo recogieron el doble de plásticos que el resto, lo que confirma que muchos residuos llegan arrastrados por el agua desde tierra adentro." },
      { p: "Con los datos obtenidos, los alumnos prepararán gráficos y un informe que enviarán al Ayuntamiento. Entre sus propuestas están instalar más papeleras y ceniceros en los accesos a la playa y colocar carteles que expliquen cuánto tarda en desaparecer cada residuo. Además, se han comprometido a repetir la limpieza en primavera para comparar los resultados." },
    ],
    vocabulario: [
      { p: "voluntario", d: "persona que ayuda en una actividad sin cobrar por ello" },
      { p: "duna", d: "montaña de arena que forma el viento en las playas o en los desiertos" },
      { p: "colilla", d: "resto de un cigarrillo que ya se ha fumado" },
      { p: "tóxico", d: "que puede hacer daño a los seres vivos" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Observa la tabla: ¿qué tipo de residuo pesó más? ¿Cuál apareció en mayor número?", r: "Los plásticos pesaron más (75 kg). Las colillas fueron las más numerosas (más de 3.000).", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué los voluntarios caminaron solo por las pasarelas en la zona de dunas?", r: "Para no dañar las plantas, porque la vegetación sujeta la arena de las dunas y la protege del viento.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Manuel con que los niños «nos hayan despertado»?", r: "Que los niños han hecho que los mayores se den cuenta del problema de la basura.", lineas: 1 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: se recogen 180 kilos de basura. Quién: unas doscientas personas; lo organizan alumnos de 6.º de tres colegios. Cuándo: ayer por la mañana (5 de octubre). Dónde: en la playa de Punta Umbría (Huelva). Cómo: en grupos, con guantes y bolsas, pesando y separando los residuos. Por qué: por un proyecto escolar sobre la contaminación del mar.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué otra propuesta añadirías al informe para el Ayuntamiento? ¿Por qué funcionaría?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que un informe con datos convence más que las simples opiniones?", r: "Respuesta libre. Valorar que relacione datos comprobables con credibilidad.", lineas: 2 },
    ],
  },
];
