// Lecturas · La noticia (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["noticia"] = [
  {
    id: "noticia-01-hotel-insectos",
    titulo: "Un hotel para insectos",
    subtipo: "Noticia escolar",
    curso: "5º",
    fuente: "Noticia inventada para esta ficha (el colegio y la localidad son ficticios)",
    antes: "¿Crees que los insectos son útiles? ¿Para qué sirven las abejas en un huerto?",
    texto: [
      { titular: "Alumnos de 5.º construyen un «hotel» para insectos en el patio de su colegio", subtitulo: "El proyecto del CEIP Los Olivos quiere atraer abejas, mariquitas y otros insectos beneficiosos a su huerto escolar", entradilla: "Villanueva del Olivar (Jaén), 14 de marzo. Los veinticuatro alumnos de 5.º del CEIP Los Olivos inauguraron ayer por la mañana, en el patio del colegio, un hotel para insectos construido por ellos mismos. Su objetivo es ayudar a los insectos polinizadores y mejorar la cosecha del huerto escolar." },
      { p: "La idea surgió en clase de Ciencias de la Naturaleza, cuando los alumnos estudiaron que muchas plantas necesitan insectos para dar fruto. «El año pasado nuestras calabazas casi no dieron nada, y la maestra nos explicó que quizá faltaban abejas», cuenta Lucía Moreno, de 10 años." },
      { p: "Durante tres semanas, los estudiantes reunieron materiales reciclados: dos palés de madera, ladrillos huecos, cañas, piñas, paja y troncos con pequeños agujeros. Con la ayuda del conserje y de varias familias, montaron una estructura de más de un metro de altura con decenas de «habitaciones». Cada material atrae a un tipo de huésped: las cañas, a las abejas solitarias; las piñas y la paja, a las mariquitas; y la madera, a otros pequeños insectos." },
      { p: "El hotel está situado en un rincón soleado, junto al huerto, y orientado hacia el sur, porque a los insectos les gusta el calor. Alrededor, los alumnos han plantado romero, lavanda y tomillo para que los visitantes encuentren flores cerca." },
      { p: "La tutora del grupo, Rosario Jiménez, explica que el proyecto sirve para aprender de forma práctica. «Los niños han medido, calculado, investigado y trabajado en equipo. Y, sobre todo, han entendido que los insectos no son enemigos, sino aliados», asegura." },
      { p: "A partir de ahora, cada semana un grupo de alumnos observará el hotel con lupas y anotará en un cuaderno de campo qué insectos se instalan. En junio presentarán sus resultados a las familias. Además, el colegio ha invitado a otros centros de la comarca a copiar la idea." },
    ],
    vocabulario: [
      { p: "polinizador", d: "animal, sobre todo insecto, que lleva el polen de una flor a otra" },
      { p: "palé", d: "plataforma de tablas de madera que se usa para transportar mercancías" },
      { p: "huésped", d: "quien se aloja en un lugar que no es su casa" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué han construido los alumnos y con qué objetivo?", r: "Un hotel para insectos, para ayudar a los polinizadores y mejorar la cosecha del huerto escolar.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué materiales usaron? ¿Por qué crees que eligieron materiales reciclados?", r: "Palés, ladrillos huecos, cañas, piñas, paja y troncos agujereados. Probablemente para no gastar dinero, reutilizar y ser coherentes con el cuidado de la naturaleza.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el hotel está orientado hacia el sur? Elige:", opciones: ["Porque allí hay más sombra", "Porque a los insectos les gusta el calor", "Porque así se ve desde la calle"], r: "Porque a los insectos les gusta el calor" },
      { tipo: "comprension", q: "¿Qué relación hay entre las calabazas del año pasado y el hotel de insectos?", r: "Las calabazas dieron poco fruto quizá por falta de abejas; el hotel atraerá insectos polinizadores que ayudarán a que el huerto produzca más.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir la tutora con que los insectos son «aliados»?", r: "Que nos ayudan: polinizan las plantas y algunos, como las mariquitas, protegen el huerto.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: la inauguración de un hotel para insectos. Quién: los 24 alumnos de 5.º del CEIP Los Olivos. Cuándo: ayer por la mañana (13 de marzo). Dónde: en el patio del colegio, en Villanueva del Olivar (Jaén). Cómo: con materiales reciclados y la ayuda del conserje y de las familias. Por qué: para ayudar a los polinizadores y mejorar el huerto.", lineas: 4 },
      { tipo: "texto", q: "Señala en la noticia el titular, el subtítulo, la entradilla y el cuerpo. ¿Qué información nos da la entradilla?", r: "El titular y el subtítulo van al principio, en letra destacada; la entradilla es el primer párrafo, con lugar y fecha; el resto es el cuerpo. La entradilla resume lo esencial: quién, qué, cuándo, dónde y para qué.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría hacer un proyecto así en tu colegio? ¿Qué construiríais y por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "A mucha gente le dan miedo o asco los insectos. ¿Estás de acuerdo con que son aliados? ¿Por qué?", r: "Respuesta libre. Valorar que use información de la noticia.", lineas: 3 },
      { tipo: "reflexion", q: "Esta noticia cuenta algo que pasó en un solo colegio. ¿Por qué crees que es importante que los medios locales cuenten también noticias como esta?", r: "Respuesta libre. Valorar que hable de dar a conocer buenas ideas, inspirar a otros y contar lo que pasa cerca.", lineas: 3 },
    ],
  },
  {
    id: "noticia-02-espana-campeona-mundial",
    titulo: "¡España, campeona del mundo!",
    subtipo: "Noticia deportiva",
    curso: "5º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (final del Mundial femenino de fútbol, 20 de agosto de 2023)",
    datos: ["CNN en Español y ESPN Deportes: crónicas de la final España-Inglaterra (20 de agosto de 2023)", "Olympics.com: información sobre la final del Mundial femenino 2023"],
    antes: "¿Recuerdas algún triunfo deportivo que se celebrara en todo el país? ¿Qué sentiste?",
    texto: [
      { titular: "¡España, campeona del mundo!", subtitulo: "Un gol de la sevillana Olga Carmona da a la selección femenina su primer Mundial de fútbol", entradilla: "Sídney (Australia), 20 de agosto de 2023. La selección española femenina de fútbol se ha proclamado hoy campeona del mundo por primera vez en su historia tras vencer por 1-0 a Inglaterra en la final, disputada en el Estadio Australia de Sídney. El único gol del partido lo marcó la defensa Olga Carmona." },
      { p: "El tanto llegó en el minuto 29 de la primera parte. Olga Carmona recibió un pase de Mariona Caldentey, avanzó por la banda izquierda y disparó con la zurda, cruzado y pegado al palo. La portera inglesa, Mary Earps, no pudo hacer nada." },
      { p: "La victoria pudo ser más amplia. En la segunda parte, el árbitro señaló un penalti a favor de España, pero Earps detuvo el lanzamiento de Jennifer Hermoso. Inglaterra, que era la campeona de Europa, buscó el empate hasta el último minuto, aunque la defensa española resistió." },
      { p: "Olga Carmona, nacida en Sevilla en el año 2000, fue una de las grandes protagonistas del torneo. En la semifinal ya había marcado el gol de la victoria contra Suecia (2-1). Con solo 23 años, se convirtió en la autora de dos de los goles más importantes de la historia de la selección femenina." },
      { p: "Además, la centrocampista Aitana Bonmatí recibió el Balón de Oro como mejor jugadora de todo el campeonato, que se disputó en Australia y Nueva Zelanda." },
      { p: "Con este triunfo, España se convierte en el segundo país, después de Alemania, que ha ganado el Mundial de fútbol tanto en categoría masculina como femenina. La selección masculina lo había conseguido en 2010, en Sudáfrica." },
      { p: "Como el partido se jugó a mediodía, hora española, miles de aficionados pudieron seguirlo en sus casas y en pantallas gigantes, y lo celebraron por todo el país." },
    ],
    vocabulario: [
      { p: "tanto", d: "en deporte, gol o punto" },
      { p: "zurda", d: "la pierna o la mano izquierda" },
      { p: "centrocampista", d: "jugadora que juega en el centro del campo" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién marcó el gol de la final, en qué minuto y con qué pierna?", r: "Olga Carmona, en el minuto 29, con la pierna izquierda (la zurda).", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice la noticia que «la victoria pudo ser más amplia»?", r: "Porque España tuvo un penalti a favor en la segunda parte, pero la portera inglesa lo detuvo.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «proclamarse campeona»? Elige:", opciones: ["Ser declarada ganadora", "Jugar un partido amistoso", "Perder en la final"], r: "Ser declarada ganadora" },
      { tipo: "comprension", q: "¿Por qué se puede decir que Olga Carmona fue decisiva en el Mundial?", r: "Porque marcó el gol de la victoria en la semifinal contra Suecia y el único gol de la final.", lineas: 2 },
      { tipo: "comprension", q: "Además del título, ¿qué logro histórico consiguió España con esta victoria?", r: "Ser el segundo país, después de Alemania, que ha ganado el Mundial masculino y el femenino.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué es importante?", r: "Qué: España gana el Mundial femenino de fútbol. Quién: la selección española (gol de Olga Carmona). Cuándo: el 20 de agosto de 2023. Dónde: en el Estadio Australia de Sídney. Cómo: venciendo 1-0 a Inglaterra en la final. Por qué es importante: es el primer Mundial de la selección femenina.", lineas: 4 },
      { tipo: "texto", q: "El titular lleva signos de exclamación. ¿Qué información da el subtítulo que no da el titular?", r: "El subtítulo explica quién marcó el gol (la sevillana Olga Carmona) y que es el primer Mundial de la selección femenina.", lineas: 2 },
      { tipo: "opinion", q: "¿Por qué crees que este triunfo fue importante para muchas niñas que juegan al fútbol?", r: "Respuesta libre. Valorar que hable de referentes e igualdad.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que el deporte femenino recibe la misma atención que el masculino en la televisión y en los periódicos? ¿Por qué?", r: "Respuesta libre. Valorar que argumente con ejemplos.", lineas: 3 },
      { tipo: "reflexion", q: "Los deportistas famosos son un ejemplo para mucha gente. ¿Qué valores crees que deben transmitir? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "noticia-03-ciguenas-colegio",
    titulo: "Cigüeñas en el tejado",
    subtipo: "Noticia local",
    curso: "5º",
    fuente: "Noticia inventada para esta ficha (el colegio, la localidad y las personas son ficticios)",
    antes: "¿Has visto alguna vez un nido de cigüeña? ¿Dónde suelen construirlo?",
    texto: [
      { titular: "Una pareja de cigüeñas retrasa las obras del tejado de un colegio", subtitulo: "Las aves han construido su nido sobre la chimenea del CEIP El Molino y la reforma tendrá que esperar hasta el verano", entradilla: "Torrecilla de la Vega (Sevilla), 2 de marzo. Las obras para reparar el tejado del CEIP El Molino, que debían comenzar ayer, se han aplazado hasta julio porque una pareja de cigüeñas blancas ha construido un gran nido sobre la antigua chimenea del edificio y ya está incubando sus huevos." },
      { p: "Los obreros llegaron el lunes a primera hora con andamios y herramientas, pero al subir al tejado se encontraron con dos inquilinos inesperados. El nido, hecho de ramas, paja y barro, mide casi un metro de ancho y ocupa toda la chimenea." },
      { p: "La cigüeña blanca es una especie protegida, por lo que está prohibido molestarla o retirar su nido mientras cría. «No podemos tocar nada hasta que los pollos aprendan a volar y abandonen el nido», explicó el concejal de Obras del municipio, Andrés Castaño. Según los técnicos de medio ambiente, eso ocurrirá, previsiblemente, a principios del verano." },
      { p: "Mientras tanto, las goteras se arreglarán desde dentro del edificio con una reparación provisional, y las obras grandes se harán en julio, cuando no haya clases. Así, además, los alumnos no tendrán que soportar el ruido de las máquinas." },
      { p: "En el colegio, la noticia se ha recibido con entusiasmo. Los alumnos de 5.º, con ayuda de su maestro, han colocado una cámara en el patio para observar el nido desde la pizarra digital. «Ya les hemos puesto nombre: Paca y Paco», cuenta entre risas Adrián, de 11 años." },
      { p: "Esta semana, todo el alumnado votará si la chimenea seguirá siendo un «hotel de cigüeñas» después de la reforma. Por ahora, el sí va ganando." },
    ],
    vocabulario: [
      { p: "aplazar", d: "dejar algo para más adelante" },
      { p: "incubar", d: "dar calor a los huevos para que nazcan las crías" },
      { p: "provisional", d: "que sirve solo durante un tiempo, hasta que haya una solución definitiva" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué se han retrasado las obras del tejado?", r: "Porque una pareja de cigüeñas ha construido su nido en la chimenea y está incubando.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué no se puede quitar el nido?", r: "Porque la cigüeña blanca es una especie protegida y está prohibido molestarla o retirar su nido mientras cría.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que las obras «se han aplazado»? Elige:", opciones: ["Que se han dejado para más adelante", "Que se han cancelado para siempre", "Que se van a hacer más deprisa"], r: "Que se han dejado para más adelante" },
      { tipo: "comprension", q: "¿Qué ventajas tiene hacer las obras en julio?", r: "No hay clases, los alumnos no sufrirán el ruido y los pollos ya habrán dejado el nido.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que los alumnos han recibido la noticia «con entusiasmo»?", r: "Porque tener un nido tan cerca es una oportunidad para observar a las aves y aprender, y les resulta divertido.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: se aplazan las obras del tejado. Quién: el Ayuntamiento y el colegio, por una pareja de cigüeñas. Cuándo: las obras debían empezar ayer (1 de marzo) y se harán en julio. Dónde: en el CEIP El Molino de Torrecilla de la Vega (Sevilla). Cómo: con una reparación provisional mientras tanto. Por qué: porque las cigüeñas son una especie protegida y están criando.", lineas: 4 },
      { tipo: "texto", q: "¿Qué personas aparecen citadas en la noticia? ¿Por qué crees que el periodista copia sus palabras exactas entre comillas «»?", r: "El concejal Andrés Castaño y el alumno Adrián. Se copian sus palabras para que la noticia sea más fiable y más viva.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece bien que se retrasen unas obras por un nido? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "Si hubiera un nido en tu colegio, ¿cómo lo observarías sin molestar a las aves?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante proteger a los animales, aunque a veces nos causen alguna molestia?", r: "Respuesta libre. Valorar que hable de biodiversidad y de convivir con la naturaleza.", lineas: 3 },
    ],
  },
  {
    id: "noticia-04-tesoro-carambolo",
    titulo: "El tesoro de El Carambolo",
    subtipo: "Noticia de historia",
    curso: "5º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (hallazgo del tesoro de El Carambolo, 30 de septiembre de 1958)",
    datos: ["Historia National Geographic: artículo sobre el origen del tesoro de El Carambolo"],
    antes: "¿Qué hace un arqueólogo? ¿Qué harías si encontraras algo muy antiguo enterrado?",
    texto: [
      { titular: "El tesoro de El Carambolo cumple 65 años", subtitulo: "Unos obreros encontraron por casualidad, cerca de Sevilla, uno de los conjuntos de joyas de oro más importantes de la Antigüedad en la península ibérica", entradilla: "Camas (Sevilla), 30 de septiembre de 2023. Hoy se cumplen 65 años del hallazgo del tesoro de El Carambolo, un conjunto de 21 joyas de oro que unos obreros descubrieron por casualidad el 30 de septiembre de 1958 mientras hacían unas obras en el cerro de El Carambolo, en Camas, muy cerca de Sevilla." },
      { p: "Aquel día, los trabajadores estaban ampliando el edificio de una sociedad de tiro. Mientras cavaban, uno de ellos vio un objeto metálico entre la tierra: era un brazalete de oro. Siguieron excavando y encontraron una vasija de barro que guardaba el resto de las piezas." },
      { p: "El tesoro está formado por 16 placas, 2 pectorales, 1 collar y 2 brazaletes. Todas las piezas son de oro de 24 quilates, es decir, de oro prácticamente puro, y en total pesan casi tres kilos." },
      { p: "Los arqueólogos creen que las joyas se fabricaron entre los siglos VII y VI antes de Cristo, hace más de 2.500 años, en la época de Tartessos, una cultura que se desarrolló en el suroeste de la península. Probablemente las llevaba una persona muy importante durante ceremonias religiosas o políticas." },
      { p: "Hoy, el tesoro pertenece al Ayuntamiento de Sevilla. En el Museo Arqueológico de Sevilla se expone una réplica, porque el original, por su enorme valor, se guarda en un lugar seguro y solo se ha mostrado al público en contadas ocasiones." },
      { p: "Los expertos recuerdan que, si alguien encuentra restos arqueológicos, no debe llevárselos ni seguir cavando: tiene que avisar a las autoridades para que los estudien y los protejan. Gracias a eso, hoy todos podemos conocer mejor a quienes vivieron en Andalucía hace miles de años." },
    ],
    vocabulario: [
      { p: "hallazgo", d: "descubrimiento de algo" },
      { p: "pectoral", d: "adorno que se lleva colgado sobre el pecho" },
      { p: "réplica", d: "copia exacta de una obra" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué ocurrió el 30 de septiembre de 1958?", r: "Unos obreros encontraron por casualidad el tesoro de El Carambolo mientras hacían obras en Camas (Sevilla).", lineas: 2 },
      { tipo: "comprension", q: "¿De qué piezas está formado el tesoro?", r: "De 16 placas, 2 pectorales, 1 collar y 2 brazaletes: 21 piezas de oro.", lineas: 2 },
      { tipo: "comprension", q: "Si una joya es de oro de 24 quilates, significa que… Elige:", opciones: ["es de oro casi puro", "pesa 24 kilos", "tiene 24 piezas"], r: "es de oro casi puro" },
      { tipo: "comprension", q: "¿Por qué crees que en el museo se expone una réplica y no el original?", r: "Por seguridad: el original tiene un valor enorme y así se evitan robos o daños.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué se dice que el hallazgo fue «por casualidad»?", r: "Porque los obreros no buscaban ningún tesoro: estaban haciendo obras en un edificio.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas sobre el hallazgo: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué es importante?", r: "Qué: el hallazgo de un tesoro de 21 joyas de oro. Quién: unos obreros. Cuándo: el 30 de septiembre de 1958. Dónde: en el cerro de El Carambolo, en Camas (Sevilla). Cómo: por casualidad, cavando durante unas obras. Por qué es importante: es uno de los conjuntos de oro más importantes de la Antigüedad y nos ayuda a conocer Tartessos.", lineas: 4 },
      { tipo: "texto", q: "Las noticias siguen la estructura de pirámide invertida. ¿Qué información aparece al principio y cuál al final? ¿Por qué se ordena así?", r: "Al principio (titular y entradilla), lo más importante: qué se encontró, cuándo y dónde. Al final, detalles y consejos. Así, quien solo lee el principio conoce ya lo esencial.", lineas: 2 },
      { tipo: "opinion", q: "Si encontraras algo muy antiguo enterrado, ¿qué harías? ¿Por qué?", r: "Respuesta libre. Valorar que mencione avisar a las autoridades.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría ser arqueólogo o arqueóloga? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué es importante que los restos del pasado se conserven en los museos, en lugar de que cada persona se quede con lo que encuentra?", r: "Respuesta libre. Valorar la idea de patrimonio común.", lineas: 3 },
    ],
  },
  {
    id: "noticia-05-recicla-bot",
    titulo: "Recicla-Bot",
    subtipo: "Noticia de tecnología",
    curso: "5º",
    fuente: "Noticia inventada para esta ficha (el colegio, el concurso y las personas son ficticios)",
    antes: "¿Sabes en qué contenedor va cada residuo? ¿Crees que un robot podría aprender a separarlos?",
    texto: [
      { titular: "Un robot que separa la basura da la victoria a un colegio de Almería", subtitulo: "Seis alumnos de 5.º del CEIP Las Salinas ganan el concurso provincial de robótica escolar con su invento, Recicla-Bot", entradilla: "Almería, 23 de mayo. Un equipo de seis alumnos de 5.º del CEIP Las Salinas ganó ayer el primer premio del concurso provincial de robótica escolar, celebrado en un pabellón de la ciudad, con un robot capaz de reconocer y separar envases, papel y restos orgánicos." },
      { p: "El robot, al que han llamado Recicla-Bot, tiene el tamaño de una caja de zapatos. Cuando alguien coloca un residuo en su bandeja, un sensor de color y otro de peso analizan el objeto, y un brazo mecánico lo empuja hacia el cubo correcto: amarillo, azul o marrón." },
      { p: "El equipo, formado por tres niñas y tres niños de 10 y 11 años, trabajó en el proyecto durante cuatro meses, por las tardes, con piezas de un kit de robótica que el colegio ya tenía. «Lo más difícil fue programarlo para que no confundiera un brik con un cartón», explica Daniela Cortés, una de las integrantes." },
      { p: "Al concurso se presentaron dieciocho equipos de toda la provincia. El jurado valoró la originalidad de la idea, el funcionamiento del robot y la presentación oral de los alumnos. En la prueba final, Recicla-Bot acertó con diecinueve de los veinte residuos que le pusieron." },
      { p: "La idea nació después de una visita a una planta de reciclaje, donde los estudiantes vieron cuántos residuos llegan mal separados. «Si un robot tan pequeño puede aprenderlo, las personas también», bromea su maestro, Javier Fuentes." },
      { p: "Como premio, el colegio recibirá material de robótica para todos los cursos. En junio, el equipo presentará su invento a las familias y al resto del alumnado." },
    ],
    vocabulario: [
      { p: "sensor", d: "aparato que detecta algo (luz, color, peso…) y envía la información" },
      { p: "residuo", d: "lo que sobra o se tira después de usar algo" },
      { p: "jurado", d: "grupo de personas que decide quién gana un concurso" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué hace Recicla-Bot y cómo lo consigue?", r: "Separa residuos: un sensor de color y otro de peso analizan el objeto y un brazo mecánico lo empuja al cubo correcto.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué tres cosas valoró el jurado del concurso?", r: "La originalidad de la idea, el funcionamiento del robot y la presentación oral.", lineas: 2 },
      { tipo: "comprension", q: "Recicla-Bot acertó con 19 de los 20 residuos. Eso significa que… Elige:", opciones: ["se equivocó una vez", "se equivocó diecinueve veces", "no se equivocó nunca"], r: "se equivocó una vez" },
      { tipo: "comprension", q: "¿Por qué crees que era difícil que el robot distinguiera un brik de un cartón?", r: "Porque se parecen en color y en peso, pero van a contenedores diferentes: el brik al amarillo y el cartón al azul.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el maestro con «Si un robot tan pequeño puede aprenderlo, las personas también»?", r: "Que separar bien la basura no es tan difícil y que no tenemos excusa para hacerlo mal.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: un colegio gana el concurso provincial de robótica. Quién: seis alumnos de 5.º del CEIP Las Salinas. Cuándo: ayer (22 de mayo). Dónde: en Almería. Cómo: con un robot que separa residuos. Por qué: el jurado valoró su originalidad, su funcionamiento y la presentación; la idea surgió al ver residuos mal separados.", lineas: 4 },
      { tipo: "texto", q: "Copia el titular. ¿Para qué sirve el titular de una noticia? ¿Qué información añade el subtítulo?", r: "«Un robot que separa la basura da la victoria a un colegio de Almería». Sirve para resumir lo más importante y llamar la atención. El subtítulo añade quiénes son (seis alumnos de 5.º del CEIP Las Salinas), el concurso y el nombre del robot.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué robot inventarías tú para resolver un problema de tu colegio o de tu barrio? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que es importante que niñas y niños participen por igual en proyectos de ciencia y tecnología?", r: "Respuesta libre. Valorar argumentos sobre igualdad de oportunidades.", lineas: 2 },
      { tipo: "reflexion", q: "¿Deberían los robots hacer por nosotros tareas como separar la basura, o es mejor que aprendamos a hacerlo nosotros? Razona tu respuesta.", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "noticia-06-perseverance-marte",
    titulo: "Perseverance llega a Marte",
    subtipo: "Noticia científica",
    curso: "5º-6º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (aterrizaje de Perseverance, 18 de febrero de 2021)",
    datos: ["NASA Ciencia (ciencia.nasa.gov y science.nasa.gov): misión Mars 2020 Perseverance y helicóptero Ingenuity", "NASA JPL: Mars 2020 Launch Press Kit", "CSIC y Centro de Astrobiología (CAB, CSIC-INTA): instrumento MEDA"],
    antes: "¿Qué sabes de Marte? ¿Crees que alguna vez hubo vida allí?",
    texto: [
      { titular: "Perseverance ya está en Marte", subtitulo: "El vehículo de la NASA, que lleva a bordo una estación meteorológica fabricada en España, buscará señales de vida antigua en el planeta rojo", entradilla: "Pasadena (Estados Unidos), 18 de febrero de 2021. El vehículo explorador Perseverance, de la NASA, ha aterrizado hoy con éxito en el cráter Jezero de Marte, tras un viaje de casi siete meses. Su misión es buscar rastros de vida microscópica antigua y recoger muestras de rocas que en el futuro podrían traerse a la Tierra." },
      { p: "Perseverance despegó el 30 de julio de 2020 desde Cabo Cañaveral, en Florida. El momento más difícil llegó al final: en solo siete minutos, la nave tuvo que frenar desde miles de kilómetros por hora hasta posarse con suavidad. Para lograrlo usó un escudo contra el calor, un paracaídas gigante y una especie de grúa voladora que bajó el vehículo colgado de cables." },
      { p: "El explorador tiene seis ruedas, es del tamaño de un coche y pesa alrededor de una tonelada. Lleva cámaras, micrófonos, un brazo robótico y varios instrumentos científicos." },
      { p: "Uno de esos instrumentos es MEDA, una estación meteorológica cuyo desarrollo ha dirigido el Centro de Astrobiología, en Madrid. MEDA medirá el viento, la temperatura, la presión, la humedad, la radiación del Sol y el polvo del aire marciano." },
      { p: "Los científicos eligieron el cráter Jezero porque hace miles de millones de años fue un lago. Si alguna vez hubo vida en Marte, quizá quedaron huellas de ella en el fondo de ese antiguo lago." },
      { p: "Perseverance transporta, además, un pequeño helicóptero llamado Ingenuity, que intentará ser el primer aparato en realizar un vuelo controlado en otro planeta." },
      { dato: "Después de esta noticia: el 19 de abril de 2021, Ingenuity consiguió volar. Estaba previsto que hiciera como mucho cinco vuelos, pero llegó a completar 72 en casi tres años." },
    ],
    vocabulario: [
      { p: "cráter", d: "hoyo grande y redondo en la superficie de un planeta" },
      { p: "microscópico", d: "tan pequeño que solo se ve con microscopio" },
      { p: "meteorológico", d: "relacionado con el tiempo atmosférico: lluvia, viento, temperatura…" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué busca Perseverance en Marte?", r: "Rastros de vida microscópica antigua; además, recoge muestras de rocas.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué eligieron los científicos el cráter Jezero?", r: "Porque hace miles de millones de años fue un lago, y allí podrían quedar huellas de vida.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué es MEDA? Elige:", opciones: ["Un pequeño helicóptero", "Una estación meteorológica desarrollada en España", "El paracaídas de la nave"], r: "Una estación meteorológica desarrollada en España" },
      { tipo: "comprension", q: "¿Por qué crees que los últimos minutos del viaje fueron los más difíciles?", r: "Porque la nave tenía que frenar muchísimo en muy poco tiempo y posarse sin romperse, sin poder corregir nada desde la Tierra.", lineas: 2 },
      { tipo: "comprension", q: "El recuadro final empieza con «Después de esta noticia». ¿Qué información nueva aporta y por qué no podía estar en la noticia original?", r: "Que Ingenuity voló el 19 de abril de 2021 e hizo 72 vuelos. No podía estar porque ocurrió después del aterrizaje, cuando se escribió la noticia.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: aterriza un vehículo explorador. Quién: Perseverance, de la NASA. Cuándo: el 18 de febrero de 2021. Dónde: en el cráter Jezero de Marte. Cómo: frenando con escudo, paracaídas y una grúa voladora. Por qué: para buscar rastros de vida antigua y recoger muestras.", lineas: 4 },
      { tipo: "texto", q: "¿Por qué este texto es una noticia y no un texto expositivo sobre Marte?", r: "Porque cuenta un hecho reciente y concreto (el aterrizaje), con fecha y lugar, y responde a las 6 preguntas. Un texto expositivo explicaría el planeta de forma general, sin relatar un suceso.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría trabajar en una misión espacial? ¿En qué tarea y por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que merece la pena dedicar dinero a explorar otros planetas? Da razones.", r: "Respuesta libre. Valorar que aporte argumentos a favor o en contra.", lineas: 3 },
      { tipo: "reflexion", q: "Si leyeras en internet que en Marte se ha encontrado un extraterrestre, ¿cómo comprobarías si es verdad? ¿Qué fuentes consultarías?", r: "Respuesta libre. Valorar que proponga fuentes oficiales (NASA, ESA, centros de investigación) y medios fiables, y comparar varias fuentes.", lineas: 3 },
    ],
  },
  {
    id: "noticia-07-dolmenes-antequera",
    titulo: "Los dólmenes de Antequera",
    subtipo: "Noticia de cultura",
    curso: "5º-6º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (declaración de Patrimonio Mundial, 15 de julio de 2016)",
    datos: ["Ministerio de Cultura: «La UNESCO declara Patrimonio Mundial el Sitio de los Dólmenes de Antequera» (15/07/2016)", "UNESCO, Centro del Patrimonio Mundial: Sitio de los Dólmenes de Antequera (n.º 1501)", "Junta de Andalucía: Sitio de los Dólmenes de Antequera, Patrimonio Mundial"],
    antes: "¿Sabes qué es un dolmen? ¿Cómo crees que se movían piedras enormes hace miles de años?",
    texto: [
      { titular: "Los dólmenes de Antequera, Patrimonio Mundial", subtitulo: "La UNESCO reconoce el valor excepcional de estos monumentos de la Prehistoria y del paisaje que los rodea", entradilla: "Estambul (Turquía), 15 de julio de 2016. El Comité del Patrimonio Mundial de la UNESCO, reunido en Estambul, ha incluido hoy el Sitio de los Dólmenes de Antequera (Málaga) en la Lista del Patrimonio Mundial, que reúne los lugares de mayor valor cultural y natural del planeta." },
      { p: "El conjunto está formado por tres monumentos construidos por los antiguos pobladores de la zona: los dólmenes de Menga y de Viera y el tholos de El Romeral. También incluye dos lugares naturales: la Peña de los Enamorados y El Torcal de Antequera." },
      { p: "Los dólmenes son grandes construcciones de piedra levantadas en la Prehistoria, que se usaban como sepulcros y, probablemente, como lugares de reunión. Menga tiene más de 5.000 años. Para construirlo, aquellos pobladores movieron enormes losas de piedra de muchas toneladas sin grúas ni máquinas, con cuerdas, rampas, troncos y mucho trabajo en equipo." },
      { p: "Una de las razones de la UNESCO es muy especial. La mayoría de los dólmenes de Europa están orientados hacia el lugar por donde sale el sol. En cambio, la entrada de Menga mira hacia la Peña de los Enamorados, una montaña cuya silueta recuerda el perfil de una cara humana tumbada. Es un caso único, que demuestra que aquellos pueblos unían sus monumentos con el paisaje." },
      { p: "Con esta declaración, Andalucía suma un nuevo lugar a la Lista del Patrimonio Mundial, en la que ya figuraban monumentos como la Alhambra de Granada o la Mezquita de Córdoba." },
      { p: "El reconocimiento supone también una responsabilidad: los lugares declarados Patrimonio Mundial deben protegerse y conservarse para que puedan conocerlos las generaciones futuras." },
    ],
    vocabulario: [
      { p: "dolmen", d: "construcción prehistórica hecha con grandes piedras, usada como sepulcro" },
      { p: "sepulcro", d: "lugar donde se entierra a una persona" },
      { p: "tholos", d: "sepulcro prehistórico con una cámara redonda cubierta por una falsa cúpula" },
      { p: "silueta", d: "forma o contorno de algo visto desde lejos" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué monumentos y qué lugares naturales forman el Sitio de los Dólmenes de Antequera?", r: "Los dólmenes de Menga y de Viera y el tholos de El Romeral; y la Peña de los Enamorados y El Torcal.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué es un dolmen y para qué se usaba?", r: "Una gran construcción de piedra de la Prehistoria que servía de sepulcro y, probablemente, de lugar de reunión.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que construir Menga fue una gran hazaña?", r: "Porque movieron losas de muchas toneladas sin máquinas, solo con cuerdas, rampas, troncos y el esfuerzo de mucha gente organizada.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué tiene de especial la orientación del dolmen de Menga?", r: "Que no mira hacia donde sale el sol, como la mayoría, sino hacia la Peña de los Enamorados. Es un caso único.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que un lugar sea «Patrimonio Mundial»? Elige:", opciones: ["Que solo lo pueden visitar los habitantes del país", "Que tiene tanto valor que debe protegerse para toda la humanidad", "Que es el lugar más antiguo del mundo"], r: "Que tiene tanto valor que debe protegerse para toda la humanidad" },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: los dólmenes de Antequera son declarados Patrimonio Mundial. Quién: el Comité del Patrimonio Mundial de la UNESCO. Cuándo: el 15 de julio de 2016. Dónde: la reunión fue en Estambul; los dólmenes están en Antequera (Málaga). Cómo: incluyéndolos en la Lista del Patrimonio Mundial. Por qué: por su valor excepcional y su relación única con el paisaje.", lineas: 4 },
      { tipo: "texto", q: "Si solo tuvieras diez segundos, ¿qué partes de la noticia leerías? ¿Por qué? Relaciónalo con la pirámide invertida.", r: "El titular, el subtítulo y la entradilla, porque en la pirámide invertida lo más importante va al principio y los detalles al final.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué lugar de tu localidad o de Andalucía propondrías para ser Patrimonio Mundial? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Es bueno que vayan muchos turistas a un lugar como este? Da una razón a favor y otra en contra.", r: "Respuesta libre. Valorar que equilibre el beneficio económico y cultural con el cuidado del lugar.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué crees que es importante cuidar lo que construyeron personas que vivieron hace miles de años?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "noticia-08-lince-iberico",
    titulo: "El regreso del lince",
    subtipo: "Noticia de medio ambiente",
    curso: "6º",
    fuente: "Noticia redactada para esta ficha a partir de hechos reales (censo de lince ibérico de 2024, publicado en mayo de 2025)",
    datos: ["MITECO: Censo de lince ibérico en España y Portugal 2024 (informe publicado el 16/05/2025)", "Agencia SINC: «Los linces ibéricos aumentan su población un 19 % en 2024 con más de 2.400 ejemplares»", "WWF: el lince ibérico pasa de «en peligro» a «vulnerable» en la Lista Roja de la UICN (2024)", "Junta de Andalucía (vía prensa): 836 linces en Andalucía en 2024"],
    antes: "¿Qué sabes del lince ibérico? ¿Por qué crees que llegó a estar a punto de desaparecer?",
    texto: [
      { titular: "El lince ibérico bate su récord: ya hay más de 2.400", subtitulo: "El censo de 2024 registra 2.401 ejemplares en España y Portugal, un 19 % más que el año anterior. Hace poco más de veinte años quedaban menos de cien", entradilla: "Madrid, mayo de 2025. El lince ibérico, uno de los felinos más amenazados del planeta hace dos décadas, sigue recuperándose. Según el censo de 2024, presentado por el Ministerio para la Transición Ecológica, en la península ibérica viven 2.401 linces, la cifra más alta desde que se hacen recuentos." },
      { p: "El dato confirma una recuperación que parecía imposible. En 2002, los expertos contaron menos de cien ejemplares, repartidos en dos pequeñas poblaciones de Andalucía: Doñana y Sierra Morena. Entonces se temía que el lince desapareciera para siempre." },
      { p: "Desde entonces, administraciones, científicos, asociaciones y propietarios de fincas han trabajado juntos. Se criaron linces en centros especiales, como el de El Acebuche, en Doñana, y después se liberaron en zonas bien elegidas de Andalucía, Extremadura, Castilla-La Mancha y Portugal. También se ha ayudado a recuperar al conejo, su alimento principal." },
      { tabla: { titulo: "Linces ibéricos censados", cab: ["Año", "Ejemplares"], filas: [["2002", "menos de 100"], ["2023", "2.021"], ["2024", "2.401"]] }, nota: "Fuente: censos oficiales de lince ibérico (MITECO)." },
      { p: "Gracias a estos esfuerzos, en 2024 la Unión Internacional para la Conservación de la Naturaleza (UICN) cambió la categoría del lince: dejó de estar «en peligro» y pasó a ser «vulnerable». Sigue amenazado, pero su situación es mucho mejor. Andalucía, donde empezó la recuperación, sigue siendo uno de sus grandes refugios: allí viven unos 836 linces, más de un tercio del total." },
      { p: "Sin embargo, los expertos advierten de que el trabajo no ha terminado. En 2024 murieron 214 linces, y tres de cada cuatro de esas muertes se debieron a atropellos en carreteras y caminos. Por eso piden construir más pasos para fauna, reducir la velocidad en las zonas donde vive y seguir cuidando su hábitat, el monte mediterráneo." },
    ],
    vocabulario: [
      { p: "censo", d: "recuento oficial de personas o de animales" },
      { p: "ejemplar", d: "cada uno de los individuos de una especie" },
      { p: "hábitat", d: "lugar con las condiciones adecuadas para que viva una especie" },
      { p: "paso para fauna", d: "túnel o puente que permite a los animales cruzar una carretera sin peligro" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántos linces había en 2002 y cuántos en 2024?", r: "En 2002, menos de cien; en 2024, 2.401.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué medidas han ayudado a recuperar al lince?", r: "Criarlo en centros especiales, liberarlo en zonas bien elegidas, recuperar al conejo y el trabajo conjunto de administraciones, científicos, asociaciones y propietarios.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que recuperar al conejo era tan importante para salvar al lince?", r: "Porque el conejo es su alimento principal: sin conejos, los linces no pueden sobrevivir ni criar.", lineas: 2 },
      { tipo: "comprension", q: "Que el lince haya pasado de «en peligro» a «vulnerable» significa que… Elige:", opciones: ["ya no corre ningún riesgo", "sigue amenazado, pero su situación ha mejorado", "ha desaparecido de Andalucía"], r: "sigue amenazado, pero su situación ha mejorado" },
      { tipo: "comprension", q: "Según la noticia, ¿cuál es hoy el mayor peligro para el lince? ¿Qué soluciones se proponen?", r: "Los atropellos (tres de cada cuatro muertes). Se proponen más pasos para fauna, reducir la velocidad y cuidar el monte mediterráneo.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: el lince ibérico alcanza su récord de población. Quién: el lince; lo presenta el Ministerio para la Transición Ecológica. Cuándo: censo de 2024, presentado en mayo de 2025. Dónde: en España y Portugal (península ibérica). Cómo: gracias a la cría en centros, las liberaciones y la recuperación del conejo. Por qué es noticia: hace veinte años quedaban menos de cien.", lineas: 4 },
      { tipo: "texto", q: "La noticia da muchas cifras y dice quién las ha publicado (el Ministerio, la UICN). ¿Por qué es importante que una noticia indique de dónde saca sus datos?", r: "Para que sea fiable y el lector pueda comprobar la información en fuentes oficiales.", lineas: 2 },
      { tipo: "opinion", q: "Si vivieras cerca de una zona con linces, ¿qué harías para ayudar a protegerlos? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que merece la pena dedicar tanto dinero y esfuerzo a salvar una especie? Razona tu respuesta.", r: "Respuesta libre. Valorar que hable de biodiversidad y equilibrio de los ecosistemas.", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué nos enseña la historia del lince sobre lo que pueden conseguir las personas cuando trabajan juntas?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "noticia-09-bulo-cocodrilo",
    titulo: "El cocodrilo que nunca existió",
    subtipo: "Noticia sobre un bulo",
    curso: "6º",
    fuente: "Noticia inventada para esta ficha (el suceso y las personas son ficticios)",
    antes: "¿Qué es una noticia falsa o bulo? ¿Te ha llegado alguna vez un mensaje que resultó ser mentira?",
    texto: [
      { titular: "No, no hay ningún cocodrilo en el río Guadalete", subtitulo: "Una fotografía trucada, compartida miles de veces en redes sociales y grupos de mensajería, causó alarma entre los vecinos de varios pueblos", entradilla: "Jerez de la Frontera (Cádiz), 12 de junio. Los técnicos de medio ambiente y la policía local han confirmado que la fotografía de un cocodrilo tomando el sol en la orilla del río Guadalete, que circula desde el pasado fin de semana por internet, es falsa. La imagen había sido manipulada con un programa de edición." },
      { p: "Todo empezó el sábado por la tarde, cuando alguien publicó la foto con un mensaje alarmante: «¡Cuidado! Han visto un cocodrilo en el Guadalete. Que nadie se bañe ni pasee a los perros por la orilla. ¡Pásalo!». En pocas horas, la imagen se había compartido miles de veces. Algunos vecinos llamaron asustados al teléfono de emergencias y varias familias suspendieron sus planes del domingo junto al río." },
      { p: "Los técnicos revisaron la zona el domingo y no encontraron ninguna huella ni rastro del animal. Además, al analizar la imagen descubrieron que el cocodrilo procedía de una fotografía tomada en un zoológico: alguien lo había recortado y pegado sobre una foto del río. Por ejemplo, la sombra del animal y la de los árboles iban en direcciones distintas." },
      { p: "«Sería muy difícil que un cocodrilo sobreviviera en libertad en nuestros ríos durante el invierno, y todavía más que pasara desapercibido», explicó Marta Ruiz, bióloga del servicio de medio ambiente, que pidió a la población calma y sentido común." },
      { p: "Los expertos aprovechan este caso para recordar algunos consejos antes de compartir una información:" },
      { lista: ["Comprueba quién la publica y si aparece en medios de comunicación serios o en fuentes oficiales.", "Desconfía de los mensajes que buscan asustarte o que te piden «pásalo».", "Fíjate en la fecha y en los detalles de las fotos.", "Ante la duda, no la reenvíes."], titulo: "Antes de compartir, comprueba" },
      { p: "Todavía no se sabe quién creó el montaje. Las autoridades recuerdan que las informaciones falsas pueden causar problemas reales, como las llamadas innecesarias a los servicios de emergencia, que deben estar libres para quien de verdad los necesita." },
    ],
    vocabulario: [
      { p: "bulo", d: "noticia falsa que se difunde, a menudo para engañar o asustar" },
      { p: "trucada", d: "cambiada con trucos para que parezca otra cosa" },
      { p: "desapercibido", d: "sin que nadie lo note" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué información falsa se difundió y por qué medios?", r: "Que había un cocodrilo en el río Guadalete. Se difundió por redes sociales y grupos de mensajería.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué consecuencias tuvo el bulo?", r: "Alarma entre los vecinos, llamadas innecesarias a emergencias y familias que suspendieron sus planes junto al río.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué pruebas demostraron que la foto estaba trucada?", r: "No había huellas ni rastros; el cocodrilo procedía de una foto de un zoológico y las sombras iban en direcciones distintas.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué es un «bulo»? Elige:", opciones: ["Una noticia falsa que se difunde para engañar o asustar", "Una noticia muy antigua", "Una fotografía de un animal"], r: "Una noticia falsa que se difunde para engañar o asustar" },
      { tipo: "comprension", q: "¿Por qué crees que el mensaje falso terminaba con «¡Pásalo!»?", r: "Para que la gente lo reenviara deprisa, sin pararse a comprobar si era verdad, y así se difundiera mucho.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: se confirma que la foto del cocodrilo es falsa. Quién: los técnicos de medio ambiente y la policía local. Cuándo: el 12 de junio (la foto circulaba desde el fin de semana). Dónde: en el río Guadalete, Jerez de la Frontera (Cádiz). Cómo: revisando la zona y analizando la imagen. Por qué: porque el bulo había causado alarma.", lineas: 4 },
      { tipo: "texto", q: "Compara el mensaje del bulo con esta noticia. ¿En qué se diferencian? Piensa en la fuente, los datos y el tono.", r: "El bulo no dice quién lo escribe, no da datos comprobables y busca asustar. La noticia cita fuentes (técnicos, policía, una bióloga), explica cómo se comprobó y usa un tono tranquilo y objetivo.", lineas: 2 },
      { tipo: "opinion", q: "¿Has recibido alguna vez un mensaje que resultó ser falso? ¿Qué hiciste o qué harías ahora?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que quien reenvía un bulo sin saberlo también tiene algo de responsabilidad? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "reflexion", q: "¿Cuál de los consejos de la noticia te parece más útil para no dejarte engañar? ¿Por qué?", r: "Respuesta libre. Valorar que justifique su elección.", lineas: 3 },
    ],
  },
  {
    id: "noticia-10-limpieza-playa",
    titulo: "Voluntarios por la playa",
    subtipo: "Noticia de medio ambiente",
    curso: "6º",
    fuente: "Noticia inventada para esta ficha (los datos de la tabla y las personas son ficticios)",
    antes: "¿Qué tipo de basura has visto alguna vez en una playa, un río o un parque? ¿Cómo crees que llegó allí?",
    texto: [
      { titular: "Doscientos voluntarios retiran 180 kilos de basura de una playa de Huelva", subtitulo: "Alumnos de 6.º de tres colegios organizaron la limpieza y clasificaron los residuos para estudiarlos en clase", entradilla: "Punta Umbría (Huelva), 6 de octubre. Unas doscientas personas, entre alumnos, familias y vecinos, recogieron ayer por la mañana 180 kilos de basura en la playa de la localidad. La actividad fue organizada por los alumnos de 6.º de tres colegios del municipio, dentro de un proyecto escolar sobre la contaminación del mar." },
      { p: "La jornada comenzó a las nueve y media. Los voluntarios, con guantes y bolsas reutilizables, se repartieron en grupos a lo largo de dos kilómetros de arena y de la zona de dunas. A mediodía llevaron todo lo recogido a una carpa, donde los alumnos lo pesaron y lo separaron por tipos." },
      { tabla: { titulo: "Residuos recogidos en la playa", cab: ["Tipo de residuo", "Cantidad"], filas: [["Colillas", "más de 3.000 unidades"], ["Plásticos (botellas, envases, bolsas)", "75 kg"], ["Latas y otros metales", "30 kg"], ["Vidrio", "25 kg"], ["Restos de redes y cuerdas", "20 kg"], ["Otros (ropa, papel, juguetes…)", "30 kg"]] }, nota: "Recuento realizado por los alumnos al terminar la jornada." },
      { p: "Lo que más sorprendió a los participantes fueron las colillas: contaron más de tres mil. «Parecen pequeñas, pero tienen sustancias tóxicas y tardan años en desaparecer», explica Iván Rodríguez, alumno de 6.º. También encontraron un balón, dos chanclas desparejadas y hasta un patito de goma." },
      { p: "La coordinadora del proyecto, la maestra Elena Márquez, recordó que gran parte de la basura que llega al mar procede de tierra firme: de lo que se tira en la calle, en el campo o en los ríos. «Lo que hemos recogido no es solo de quien viene a la playa; es de todos», señaló." },
      { p: "Con los datos obtenidos, los alumnos prepararán gráficos y un informe que enviarán al Ayuntamiento. Entre sus propuestas están instalar más papeleras y ceniceros en los accesos a la playa y colocar carteles que expliquen cuánto tarda en desaparecer cada residuo." },
    ],
    vocabulario: [
      { p: "voluntario", d: "persona que ayuda en una actividad sin cobrar por ello" },
      { p: "colilla", d: "resto de un cigarrillo que ya se ha fumado" },
      { p: "tóxico", d: "que puede hacer daño a los seres vivos" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién organizó la limpieza y con qué motivo?", r: "Los alumnos de 6.º de tres colegios de Punta Umbría, dentro de un proyecto escolar sobre la contaminación del mar.", lineas: 2 },
      { tipo: "comprension", q: "Observa la tabla: ¿qué tipo de residuo pesó más? ¿Cuál apareció en mayor número?", r: "Los plásticos pesaron más (75 kg). Las colillas fueron las más numerosas (más de 3.000).", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que las colillas aparecen en la tabla por unidades y no por kilos?", r: "Porque pesan muy poco; en kilos parecería poca cosa y no se vería lo abundantes que son.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir la maestra con «es de todos»? Elige:", opciones: ["Que la basura pertenece al Ayuntamiento", "Que todos somos responsables, porque mucha basura llega al mar desde tierra", "Que cualquiera puede llevarse la basura a casa"], r: "Que todos somos responsables, porque mucha basura llega al mar desde tierra" },
      { tipo: "comprension", q: "¿Qué relación hay entre las propuestas de los alumnos y lo que encontraron en la playa?", r: "Como encontraron muchas colillas y basura, proponen ceniceros y papeleras para que no se tire al suelo, y carteles para concienciar del tiempo que tarda en desaparecer.", lineas: 2 },
      { tipo: "texto", q: "Responde a las 6 preguntas de la noticia: ¿qué?, ¿quién?, ¿cuándo?, ¿dónde?, ¿cómo? y ¿por qué?", r: "Qué: se recogen 180 kilos de basura. Quién: unas doscientas personas; lo organizan alumnos de 6.º de tres colegios. Cuándo: ayer por la mañana (5 de octubre). Dónde: en la playa de Punta Umbría (Huelva). Cómo: en grupos, con guantes y bolsas, pesando y separando los residuos. Por qué: por un proyecto escolar sobre la contaminación del mar.", lineas: 4 },
      { tipo: "texto", q: "Esta noticia incluye una tabla. ¿En qué parte de la noticia aparece (titular, entradilla o cuerpo)? ¿Qué aporta?", r: "Aparece en el cuerpo. Aporta datos concretos y ordenados que se entienden de un vistazo y hacen la noticia más completa y fiable.", lineas: 2 },
      { tipo: "opinion", q: "¿Participarías en una actividad como esta? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué otra propuesta añadirías al informe para el Ayuntamiento? Explica por qué funcionaría.", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Los alumnos van a enviar un informe con datos al Ayuntamiento. ¿Por qué crees que los datos convencen más que las simples opiniones?", r: "Respuesta libre. Valorar que relacione datos comprobables con credibilidad.", lineas: 3 },
    ],
  },
];
