// Lecturas · Poesía (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["poesia"] = [
  {
    id: "poesia-01-haikus-andaluces",
    titulo: "Cuatro haikus andaluces",
    subtipo: "Haiku (serie de cuatro)",
    curso: "5º",
    fuente: "Poema original",
    antes: "¿Qué cambia en el paisaje de tu pueblo o tu ciudad de una estación a otra? Di una cosa de cada estación.",
    texto: [
      { h: "Primavera en Doñana" },
      { estrofa: ["Flamencos rosas", "duermen sobre una pata", "en la marisma."] },
      { h: "Verano en Jaén" },
      { estrofa: ["Siesta de agosto", "y la cigarra canta", "bajo el olivo."] },
      { h: "Otoño en el pueblo" },
      { estrofa: ["Lluvia de octubre.", "Los caracoles salen", "a ver el mundo."] },
      { h: "Invierno en Granada" },
      { estrofa: ["Primera nieve", "en la Sierra Nevada:", "se pone el gorro."] },
    ],
    vocabulario: [
      { p: "marisma", d: "terreno llano y encharcado cerca de la desembocadura de un río" },
      { p: "cigarra", d: "insecto que en verano produce un sonido agudo y continuo" },
      { p: "siesta", d: "rato de descanso después de comer" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué animal aparece en cada uno de los tres primeros haikus y qué está haciendo?", r: "Los flamencos duermen sobre una pata; la cigarra canta bajo el olivo; los caracoles salen con la lluvia.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué momento del día describe el haiku de verano? Elige:", opciones: ["La madrugada, antes de salir el sol", "La siesta, después de comer", "La noche, bajo las estrellas"], r: "La siesta, después de comer" },
      { tipo: "comprension", q: "¿Quién «se pone el gorro» en el último haiku? ¿Cuál es ese gorro en realidad?", r: "La Sierra Nevada. El gorro es la primera nieve, que cubre de blanco las cumbres como si fuera un gorro.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que los caracoles salen precisamente cuando llueve?", r: "Porque les gusta la humedad: con la lluvia el suelo está mojado y pueden moverse sin secarse. El poema lo dice con humor, como si salieran a pasear para ver el mundo.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué se parecen los cuatro haikus? Elige:", opciones: ["Todos cuentan una historia con personajes que hablan", "Todos describen un pequeño momento de la naturaleza en una estación del año", "Todos explican cómo funciona un animal"], r: "Todos describen un pequeño momento de la naturaleza en una estación del año" },
      { tipo: "texto", q: "Cuenta las sílabas del haiku de invierno, verso a verso. ¿Cumple la medida 5-7-5? ¿Tiene rima? ¿Qué recurso literario hay en el último verso?", r: "Pri-me-ra-nie-ve (5) / en-la-Sie-rra-Ne-va-da (7) / se-po-neel-go-rro (5): sí cumple 5-7-5 y no tiene rima, como todo haiku. En «se pone el gorro» hay una personificación: la sierra hace algo propio de las personas.", lineas: 3 },
      { tipo: "opinion", q: "¿Cuál de los cuatro haikus te gusta más? ¿Por qué?", r: "Respuesta libre. Valorar que justifique su elección con alguna imagen del poema.", lineas: 3 },
      { tipo: "opinion", q: "Escribe tu propio haiku (5-7-5) sobre un lugar de tu localidad en la estación en la que estamos.", r: "Respuesta libre. Comprobar que respeta la medida 5-7-5 y que habla de la naturaleza o del paisaje.", lineas: 3 },
      { tipo: "reflexion", q: "Los haikus se fijan en detalles pequeños: una cigarra, un caracol… ¿Por qué crees que es importante pararse a observar la naturaleza que tenemos cerca?", r: "Respuesta libre. Valorar que hable de disfrutar, conocer y cuidar el entorno.", lineas: 3 },
    ],
  },
  {
    id: "poesia-02-cancioncilla-sevillana",
    titulo: "Cancioncilla sevillana",
    subtipo: "Canción lírica",
    curso: "5º",
    fuente: "Federico García Lorca, «Cancioncilla sevillana» (Canciones, 1927)",
    antes: "Lorca nació en Fuente Vaqueros (Granada) y escribió muchas canciones sobre Andalucía. ¿Qué árboles y flores crees que puede haber en un amanecer en Sevilla?",
    texto: [
      { estrofa: ["Amanecía", "en el naranjel.", "Abejitas de oro", "buscaban la miel."] },
      { estrofa: ["¿Dónde estará", "la miel?"] },
      { estrofa: ["Está en la flor azul,", "Isabel.", "En la flor,", "del romero aquel."] },
      { estrofa: ["(Sillita de oro", "para el moro.", "Silla de oropel", "para su mujer)."] },
      { estrofa: ["Amanecía,", "en el naranjel."] },
    ],
    vocabulario: [
      { p: "naranjel", d: "naranjal, huerto de naranjos" },
      { p: "romero", d: "arbusto oloroso de flores pequeñas y azuladas" },
      { p: "oropel", d: "lámina de metal que imita al oro: brilla mucho pero vale poco" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿En qué momento del día y en qué lugar ocurre el poema?", r: "Al amanecer, en un naranjal (naranjel). Por el título, en Sevilla.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué buscan las abejas? ¿Dónde está lo que buscan?", r: "Buscan la miel. Está en la flor azul del romero.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el poeta llama a las abejas «abejitas de oro»?", r: "Porque son amarillas y brillan con la luz del amanecer, como si fueran de oro. El diminutivo «abejitas» muestra cariño.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué es una «silla de oropel»? Elige:", opciones: ["Una silla de oro auténtico, muy cara", "Una silla que brilla como el oro, pero no es de oro", "Una silla de madera de naranjo"], r: "Una silla que brilla como el oro, pero no es de oro" },
      { tipo: "comprension", q: "El poema empieza y termina casi con los mismos versos. ¿Qué sensación te produce ese final?", r: "Da la sensación de canción que se repite, de círculo: el amanecer sigue en el naranjal, como si el tiempo se detuviera.", lineas: 2 },
      { tipo: "texto", q: "¿Cuántas estrofas y cuántos versos tiene el poema? Copia las palabras que riman con «miel». ¿Es rima consonante o asonante?", r: "5 estrofas y 16 versos. Riman con «miel»: naranjel, Isabel, aquel y oropel, en rima consonante (coincide -el). «Mujer» rima en asonante (solo coincide la e).", lineas: 3 },
      { tipo: "opinion", q: "Este poema parece una canción infantil. ¿Qué parte te gustaría cantar o recitar en voz alta? ¿Por qué?", r: "Respuesta libre. Valorar que se fije en el ritmo, la repetición o las rimas.", lineas: 3 },
      { tipo: "opinion", q: "Si tuvieras que dibujar este poema, ¿qué colores usarías? ¿Por qué?", r: "Respuesta libre. Valorar que relacione los colores con palabras del poema (oro, azul, naranjel, amanecer…).", lineas: 3 },
      { tipo: "reflexion", q: "Las abejas buscan la miel en las flores. ¿Por qué son tan importantes las abejas para el campo y para las personas?", r: "Respuesta libre. Valorar que mencione la polinización de plantas y cultivos y la necesidad de protegerlas.", lineas: 3 },
    ],
  },
  {
    id: "poesia-03-burro-flautista",
    titulo: "El burro flautista",
    subtipo: "Fábula en verso",
    curso: "5º",
    fuente: "Tomás de Iriarte, «El burro flautista» (Fábulas literarias, 1782)",
    antes: "¿Te ha salido alguna vez algo bien por pura suerte? ¿Te atreverías a presumir de ello?",
    texto: [
      { estrofa: ["Esta fabulilla,", "salga bien o mal,", "me ha ocurrido ahora", "por casualidad."] },
      { estrofa: ["Cerca de unos prados", "que hay en mi lugar,", "pasaba un borrico", "por casualidad."] },
      { estrofa: ["Una flauta en ellos", "halló, que un zagal", "se dejó olvidada", "por casualidad."] },
      { estrofa: ["Acercóse a olerla", "el dicho animal,", "y dio un resoplido", "por casualidad."] },
      { estrofa: ["En la flauta el aire", "se hubo de colar,", "y sonó la flauta", "por casualidad."] },
      { estrofa: ["«¡Oh! —dijo el borrico—,", "¡qué bien sé tocar!", "¡Y dirán que es mala", "la música asnal!»"] },
      { estrofa: ["Sin reglas del arte,", "borriquitos hay", "que una vez aciertan", "por casualidad."] },
    ],
    vocabulario: [
      { p: "zagal", d: "muchacho joven; a menudo, pastor" },
      { p: "resoplido", d: "soplido fuerte que se da por la nariz" },
      { p: "asnal", d: "de los asnos o burros" },
      { p: "mi lugar", d: "aquí, mi pueblo" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién había dejado olvidada la flauta y dónde la encontró el burro?", r: "La dejó olvidada un zagal (un muchacho) en unos prados cerca del pueblo del autor.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo consiguió el burro que sonara la flauta?", r: "Se acercó a olerla, dio un resoplido y el aire se coló por la flauta, que sonó por casualidad.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué verso se repite al final de casi todas las estrofas? Elige:", opciones: ["«¡qué bien sé tocar!»", "«por casualidad»", "«el dicho animal»"], r: "«por casualidad»" },
      { tipo: "comprension", q: "¿Por qué dice el burro «¡Qué bien sé tocar!»? ¿Tiene razón?", r: "Porque cree que tiene talento para la música. No tiene razón: la flauta sonó por casualidad, no porque supiera tocarla. Es un burro presumido.", lineas: 2 },
      { tipo: "comprension", q: "Explica con tus palabras la última estrofa, que es la moraleja.", r: "Quien no ha aprendido ni sigue las reglas de un arte puede acertar alguna vez, pero es por suerte, no por saber hacerlo.", lineas: 2 },
      { tipo: "texto", q: "¿Cuántas estrofas y versos tiene la fábula? Cuenta las sílabas del primer verso: ¿es de arte mayor o menor? ¿Qué versos riman y en qué vocal?", r: "7 estrofas de 4 versos: 28 versos. «Es-ta-fa-bu-li-lla» tiene 6 sílabas: arte menor. Riman los versos pares en «a» (mal, casualidad, lugar, zagal, animal, colar, tocar, asnal…); los impares quedan sueltos.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece bien que el burro presuma? ¿Qué le dirías si lo tuvieras delante?", r: "Respuesta libre. Valorar que argumente sobre la diferencia entre suerte y mérito.", lineas: 3 },
      { tipo: "opinion", q: "¿Recuerdas algo que te salió bien por casualidad y luego no te volvió a salir? Cuéntalo.", r: "Respuesta libre. Valorar que relacione la fábula con su experiencia.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué es importante practicar y aprender en lugar de confiar en la suerte? Pon un ejemplo del colegio o del deporte.", r: "Respuesta libre. Valorar que explique que el esfuerzo permite repetir los buenos resultados.", lineas: 3 },
    ],
  },
  {
    id: "poesia-04-mi-mochila",
    titulo: "Mi mochila",
    subtipo: "Poema humorístico",
    curso: "5º",
    fuente: "Poema original",
    antes: "¿Cuánto crees que pesa tu mochila? ¿Qué hay dentro que quizá no necesites?",
    texto: [
      { estrofa: ["Mi mochila pesa tanto", "como un camión de melones;", "cuando la subo, ¡qué espanto!,", "gimen los cuatro escalones."] },
      { estrofa: ["Dentro vive un bocadillo", "de hace un mes, o tal vez dos,", "que ya tiene bigotillo", "y me dice: «¡Adiós, adiós!»."] },
      { estrofa: ["Llevo libros, un compás,", "tres estuches, la merienda,", "una flauta y algo más:", "¡casi cabe media tienda!"] },
      { estrofa: ["Y mi abuela dice, riendo:", "«Esa mochila es un tren».", "Y yo contesto sonriendo:", "«¡Pues que me lleve también!»."] },
    ],
    vocabulario: [
      { p: "gemir", d: "quejarse con sonidos de pena o de dolor" },
      { p: "espanto", d: "susto muy grande" },
      { p: "compás", d: "instrumento para trazar circunferencias" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué cosas lleva el protagonista en la mochila? Nombra al menos cinco.", r: "Un bocadillo viejo, libros, un compás, tres estuches, la merienda, una flauta y algo más.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el bocadillo «ya tiene bigotillo»?", r: "Porque lleva uno o dos meses olvidado en la mochila y le ha salido moho, que parece un bigote. Es una forma graciosa de decir que está estropeado.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el protagonista con «¡Pues que me lleve también!»? Elige:", opciones: ["Que quiere hacer un viaje en tren", "Que, si la mochila es un tren, lo lleve a él y así no tiene que cargarla", "Que su abuela debe llevarle la mochila"], r: "Que, si la mochila es un tren, lo lleve a él y así no tiene que cargarla" },
      { tipo: "comprension", q: "¿Se enfada el protagonista por el peso de la mochila o se lo toma con humor? ¿Cómo lo sabes?", r: "Se lo toma con humor: exagera para hacer reír y contesta a su abuela «sonriendo» con un chiste.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que los escalones «gimen»? Elige:", opciones: ["Que crujen o suenan como si se quejaran del peso", "Que están rotos", "Que son muy altos"], r: "Que crujen o suenan como si se quejaran del peso" },
      { tipo: "texto", q: "Busca en el poema un ejemplo de cada recurso: comparación, metáfora, personificación e hipérbole.", r: "Comparación: «pesa tanto como un camión de melones». Metáfora: «Esa mochila es un tren». Personificación: «gimen los cuatro escalones» o el bocadillo que dice «¡Adiós, adiós!». Hipérbole: «¡casi cabe media tienda!» (o el peso de un camión).", lineas: 4 },
      { tipo: "opinion", q: "¿Qué verso te ha hecho más gracia? ¿Por qué?", r: "Respuesta libre. Valorar que explique en qué consiste la gracia (exageración, sorpresa…).", lineas: 2 },
      { tipo: "opinion", q: "Inventa una estrofa más de cuatro versos sobre otra cosa que podría esconderse en esa mochila. Intenta que rime.", r: "Respuesta libre. Valorar la rima y el humor.", lineas: 4 },
      { tipo: "reflexion", q: "Llevar demasiado peso a la espalda no es bueno para la salud. ¿Qué podrías hacer tú para que tu mochila pese menos?", r: "Respuesta libre. Valorar ideas prácticas: preparar la mochila con el horario, no llevar cosas innecesarias, usar la taquilla…", lineas: 3 },
    ],
  },
  {
    id: "poesia-05-las-moscas",
    titulo: "Las moscas (fragmento)",
    subtipo: "Poema lírico",
    curso: "5º",
    fuente: "Antonio Machado, «Las moscas» (Soledades. Galerías. Otros poemas, 1907), fragmento: los doce primeros versos",
    antes: "Las moscas suelen molestarnos. ¿Se te ocurre algo bueno que podría decirse de ellas en un poema?",
    texto: [
      { estrofa: ["Vosotras, las familiares,", "inevitables golosas;", "vosotras, moscas vulgares,", "me evocáis todas las cosas."] },
      { estrofa: ["¡Oh viejas moscas voraces", "como abejas en abril,", "viejas moscas pertinaces", "sobre mi calva infantil!"] },
      { estrofa: ["¡Moscas del primer hastío", "en el salón familiar,", "las claras tardes de estío", "en que yo empecé a soñar!"] },
    ],
    vocabulario: [
      { p: "evocar", d: "traer algo a la memoria, recordar" },
      { p: "voraz", d: "que come mucho y con ansia" },
      { p: "pertinaz", d: "que insiste mucho y no se rinde" },
      { p: "hastío", d: "aburrimiento" },
      { p: "estío", d: "verano" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿A quién le habla el poeta? Copia la palabra que lo demuestra.", r: "A las moscas: «Vosotras».", lineas: 1 },
      { tipo: "comprension", q: "¿Qué recuerdos le traen las moscas al poeta?", r: "Le recuerdan su infancia: las tardes claras de verano en el salón de su casa, cuando se aburría y empezaba a soñar.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué nos hace imaginar el verso «sobre mi calva infantil»?", r: "Que de niño llevaba el pelo muy corto o rapado y las moscas se le posaban en la cabeza sin parar. Es un toque de humor.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que las moscas son «pertinaces»? Elige:", opciones: ["Que se van enseguida", "Que insisten y vuelven una y otra vez", "Que son muy pequeñas"], r: "Que insisten y vuelven una y otra vez" },
      { tipo: "comprension", q: "¿Siente el poeta rabia o cariño por las moscas? Justifica tu respuesta con palabras del texto.", r: "Siente cariño y nostalgia: las llama «familiares» y «viejas», como a amigas de siempre, y las une a sus recuerdos de niño, aunque sean pesadas y golosas.", lineas: 2 },
      { tipo: "texto", q: "Copia la comparación que aparece en la segunda estrofa. Después, escribe las palabras que riman en la primera estrofa: ¿es rima consonante o asonante?", r: "Comparación: «voraces como abejas en abril». En la primera estrofa riman familiares/vulgares y golosas/cosas (esquema ABAB). Es rima consonante, porque coinciden vocales y consonantes.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece un tema raro para un poema? ¿Por qué crees que Machado escribió sobre las moscas?", r: "Respuesta libre. Valorar que relacione el tema con los recuerdos y con la idea de que cualquier cosa puede ser poética.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué animal, olor u objeto te recuerda a ti a cuando eras más pequeño o pequeña? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Machado escribe sobre algo que casi todo el mundo desprecia. ¿Crees que merece la pena fijarse en las cosas pequeñas o molestas? ¿Qué podemos aprender de ellas?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
    ],
  },
  {
    id: "poesia-06-recuerdo-infantil",
    titulo: "Recuerdo infantil",
    subtipo: "Poema lírico",
    curso: "5º-6º",
    fuente: "Antonio Machado, «Recuerdo infantil» (Soledades, Galerías y otros poemas, ed. de 1919)",
    antes: "Antonio Machado nació en Sevilla y fue alumno y también profesor. ¿Cómo imaginas una clase de hace más de cien años?",
    texto: [
      { estrofa: ["Una tarde parda y fría", "de invierno. Los colegiales", "estudian. Monotonía", "de lluvia tras los cristales."] },
      { estrofa: ["Es la clase. En un cartel", "se representa a Caín", "fugitivo, y muerto Abel,", "junto a una mancha carmín."] },
      { estrofa: ["Con timbre sonoro y hueco,", "truena el maestro, un anciano", "mal vestido, enjuto y seco,", "que lleva un libro en la mano."] },
      { estrofa: ["Y todo un coro infantil", "va cantando la lección:", "mil veces ciento, cien mil;", "mil veces mil, un millón."] },
      { estrofa: ["Una tarde parda y fría", "de invierno. Los colegiales", "estudian. Monotonía", "de la lluvia en los cristales."] },
    ],
    vocabulario: [
      { p: "pardo", d: "de color oscuro, entre gris y marrón" },
      { p: "monotonía", d: "falta de variedad: todo igual, aburrido" },
      { p: "carmín", d: "rojo intenso" },
      { p: "enjuto", d: "muy delgado" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tiempo hace y en qué estación del año ocurre el recuerdo?", r: "Es una tarde parda y fría de invierno, y llueve.", lineas: 1 },
      { tipo: "comprension", q: "Describe al maestro con las palabras del poema.", r: "Es un anciano mal vestido, enjuto y seco, con una voz sonora y hueca, que lleva un libro en la mano.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué lección están cantando los niños? ¿De qué asignatura es?", r: "Están cantando la tabla de multiplicar con números grandes («mil veces ciento, cien mil»). Es de Matemáticas.", lineas: 2 },
      { tipo: "comprension", q: "¿El poeta recuerda aquella clase como divertida o aburrida? ¿Qué palabras te dan la pista?", r: "Como aburrida y triste: «parda», «fría», «monotonía», la lluvia, la lección repetida en coro y el maestro que «truena».", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir «truena el maestro»? Elige:", opciones: ["Que el maestro habla muy alto y con voz fuerte", "Que hay tormenta dentro de la clase", "Que el maestro tiene miedo de los truenos"], r: "Que el maestro habla muy alto y con voz fuerte" },
      { tipo: "texto", q: "¿Cuántas estrofas y versos tiene el poema? ¿Qué versos riman y de qué tipo es la rima? ¿Qué tiene de especial la última estrofa?", r: "5 estrofas de 4 versos: 20 versos. Riman el 1.º con el 3.º y el 2.º con el 4.º (fría/Monotonía, colegiales/cristales, cartel/Abel…): rima consonante. La última estrofa repite la primera con un pequeño cambio («de la lluvia en los cristales»), así que el poema acaba como empezó (estructura circular).", lineas: 3 },
      { tipo: "opinion", q: "Compara esta clase con la tuya. ¿Qué diferencias y qué parecidos encuentras?", r: "Respuesta libre. Valorar que mencione aspectos concretos (forma de aprender, materiales, maestro, ambiente…).", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que cantar las tablas en coro sirve para aprenderlas? ¿Por qué?", r: "Respuesta libre. Valorar que argumente a favor o en contra.", lineas: 2 },
      { tipo: "reflexion", q: "Este recuerdo acompañó al poeta toda su vida. ¿Qué momento de tu colegio crees que recordarás de mayor? ¿Por qué será importante para ti?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "poesia-07-paisaje-lorca",
    titulo: "Paisaje",
    subtipo: "Poema lírico",
    curso: "5º-6º",
    fuente: "Federico García Lorca, «Paisaje» (Poema del cante jondo, 1931; sección «Poema de la siguiriya gitana»)",
    antes: "¿Has visto alguna vez un olivar? Andalucía es la tierra con más olivos del mundo. ¿Cómo se ve un olivar al atardecer?",
    texto: [
      { estrofa: ["El campo", "de olivos", "se abre y se cierra", "como un abanico.", "Sobre el olivar", "hay un cielo hundido", "y una lluvia oscura", "de luceros fríos.", "Tiembla junco y penumbra", "a la orilla del río.", "Se riza el aire gris.", "Los olivos", "están cargados", "de gritos.", "Una bandada", "de pájaros cautivos,", "que mueven sus larguísimas", "colas en lo sombrío."] },
    ],
    vocabulario: [
      { p: "penumbra", d: "sombra débil, con muy poca luz" },
      { p: "junco", d: "planta de tallo largo y flexible que crece junto al agua" },
      { p: "cautivo", d: "preso, que no puede escapar" },
      { p: "sombrío", d: "lugar con sombra, oscuro" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué árboles aparecen en el poema? ¿Qué otros elementos del paisaje nombra el poeta?", r: "Olivos. También el cielo, los luceros, el junco, el río, el aire gris y una bandada de pájaros.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué momento del día crees que ocurre la escena? Justifica tu respuesta.", r: "Al anochecer o de noche: hay luceros (estrellas), penumbra, el aire es gris y todo está «en lo sombrío».", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el campo de olivos «se abre y se cierra como un abanico»?", r: "Porque las filas de olivos, al mirarlas mientras uno se mueve (o al moverse con el viento), parecen abrirse y cerrarse como las varillas de un abanico.", lineas: 2 },
      { tipo: "comprension", q: "En el poema, los «luceros fríos» son… Elige:", opciones: ["Farolas de un pueblo cercano", "Estrellas", "Luciérnagas del río"], r: "Estrellas" },
      { tipo: "comprension", q: "¿Qué sensación transmite el paisaje: alegría, calma o inquietud? ¿Qué palabras lo muestran?", r: "Inquietud o tristeza: «cielo hundido», «lluvia oscura», «tiembla», «gris», «gritos», «cautivos», «sombrío».", lineas: 2 },
      { tipo: "texto", q: "Localiza en el poema una comparación y una personificación. Después, fíjate en los versos pares: ¿en qué vocales riman? ¿Es rima consonante o asonante?", r: "Comparación: «se abre y se cierra como un abanico». Personificación: «Los olivos están cargados de gritos» o «Tiembla junco y penumbra». Los versos pares (olivos, abanico, hundido, fríos, río…) riman en í-o: rima asonante.", lineas: 4 },
      { tipo: "opinion", q: "¿Te gustaría pasear por este olivar a esa hora? ¿Por qué?", r: "Respuesta libre. Valorar que se apoye en imágenes del poema.", lineas: 2 },
      { tipo: "opinion", q: "Lorca dice que los olivos están «cargados de gritos». ¿Qué crees que quiere decir? ¿De qué otra cosa podrías decir que están cargados?", r: "Respuesta libre. Puede interpretarse como el ruido de los pájaros, el viento o una sensación de pena. Valorar la creatividad.", lineas: 3 },
      { tipo: "reflexion", q: "El olivar es uno de los paisajes más típicos de Andalucía. ¿Por qué crees que es importante cuidar los paisajes de nuestra tierra?", r: "Respuesta libre. Valorar que hable de la naturaleza, del trabajo de las personas y de la identidad de un lugar.", lineas: 3 },
    ],
  },
  {
    id: "poesia-08-margarita-debayle",
    titulo: "A Margarita Debayle (fragmento)",
    subtipo: "Poema narrativo",
    curso: "6º",
    fuente: "Rubén Darío, «A Margarita Debayle» (1908), fragmento: primeras siete estrofas",
    antes: "Rubén Darío, poeta de Nicaragua, escribió este poema para una niña llamada Margarita. ¿Qué cuento le contarías tú a un niño pequeño?",
    texto: [
      { estrofa: ["Margarita, está linda la mar,", "y el viento", "lleva esencia sutil de azahar;", "yo siento", "en el alma una alondra cantar;", "tu acento.", "Margarita, te voy a contar", "un cuento."] },
      { estrofa: ["Este era un rey que tenía", "un palacio de diamantes,", "una tienda hecha del día", "y un rebaño de elefantes,", "un kiosko de malaquita,", "un gran manto de tisú,", "y una gentil princesita,", "tan bonita,", "Margarita,", "tan bonita como tú."] },
      { estrofa: ["Una tarde la princesa", "vio una estrella aparecer;", "la princesa era traviesa", "y la quiso ir a coger."] },
      { estrofa: ["La quería para hacerla", "decorar un prendedor,", "con un verso y una perla,", "y una pluma y una flor."] },
      { estrofa: ["Las princesas primorosas", "se parecen mucho a ti.", "Cortan lirios, cortan rosas,", "cortan astros. Son así."] },
      { estrofa: ["Pues se fue la niña bella,", "bajo el cielo y sobre el mar,", "a cortar la blanca estrella", "que la hacía suspirar."] },
      { estrofa: ["Y siguió camino arriba,", "por la luna y más allá;", "mas lo malo es que ella iba", "sin permiso del papá."] },
    ],
    vocabulario: [
      { p: "azahar", d: "flor blanca y muy olorosa del naranjo y del limonero" },
      { p: "alondra", d: "pájaro pequeño de canto muy alegre" },
      { p: "malaquita", d: "piedra de color verde intenso" },
      { p: "tisú", d: "tela de seda con hilos de oro o de plata" },
      { p: "prendedor", d: "broche, adorno que se prende en la ropa" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿A quién se dirige el poeta y qué le anuncia en la primera estrofa?", r: "A Margarita, una niña. Le anuncia que le va a contar un cuento.", lineas: 2 },
      { tipo: "comprension", q: "Enumera cuatro cosas que tenía el rey.", r: "Un palacio de diamantes, una tienda hecha del día, un rebaño de elefantes, un kiosko de malaquita, un manto de tisú y una princesita.", lineas: 2 },
      { tipo: "comprension", q: "¿Para qué quería la princesa la estrella? Elige:", opciones: ["Para iluminar el palacio por la noche", "Para decorar un prendedor", "Para regalársela a su padre"], r: "Para decorar un prendedor" },
      { tipo: "comprension", q: "¿Por qué dice el poeta que las princesas «se parecen mucho a ti»? ¿Qué quiere decirle a Margarita?", r: "Le hace un cumplido: Margarita es bonita, traviesa y soñadora como las princesas del cuento, capaz de querer hasta las estrellas.", lineas: 2 },
      { tipo: "comprension", q: "El fragmento acaba con «sin permiso del papá». ¿Qué crees que pasará después? ¿Por qué?", r: "Que el rey se enfadará y la castigará o le pedirá que devuelva la estrella, porque se fue sin permiso. (En el poema completo, el rey le ordena devolverla.)", lineas: 2 },
      { tipo: "texto", q: "Cuenta las sílabas de «y el viento» y de «Margarita, está linda la mar». ¿Son de arte menor o mayor? Copia las palabras que riman con «mar» y con «viento» en la primera estrofa. ¿Qué tipo de rima es? Busca también una hipérbole.", r: "«y el vien-to» → yel-vien-to: 3 sílabas, arte menor. «Mar-ga-ri-taes-tá-lin-da-la-mar»: 9 + 1 por acabar en aguda = 10 sílabas, arte mayor. Con «mar»: azahar, cantar, contar; con «viento»: siento, acento, cuento. Rima consonante. Hipérbole: «un palacio de diamantes» o «cortan astros».", lineas: 4 },
      { tipo: "opinion", q: "¿Qué te parece más bonito del palacio del rey? ¿Qué pondrías tú en un palacio imaginario?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "La princesa se va lejísimos sin avisar. ¿Te parece bien? ¿Qué harías tú si quisieras algo tan difícil de conseguir?", r: "Respuesta libre. Valorar que argumente sobre la importancia de pedir permiso y de perseguir los sueños con cabeza.", lineas: 3 },
      { tipo: "reflexion", q: "La princesa quiere «cortar» una estrella, algo imposible. ¿Qué «estrellas» (sueños difíciles) tienes tú? ¿Qué puedes hacer para acercarte a ellos?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "poesia-09-baladilla-tres-rios",
    titulo: "Baladilla de los tres ríos",
    subtipo: "Balada",
    curso: "6º",
    fuente: "Federico García Lorca, «Baladilla de los tres ríos» (Poema del cante jondo, 1931)",
    antes: "Lorca era de Granada. ¿Qué río pasa por Sevilla? ¿Sabes qué ríos pasan por Granada?",
    texto: [
      { estrofa: ["El río Guadalquivir", "va entre naranjos y olivos.", "Los dos ríos de Granada", "bajan de la nieve al trigo."] },
      { estrofa: ["¡Ay, amor", "que se fue y no vino!"] },
      { estrofa: ["El río Guadalquivir", "tiene las barbas granates.", "Los dos ríos de Granada,", "uno llanto y otro sangre."] },
      { estrofa: ["¡Ay, amor", "que se fue por el aire!"] },
      { estrofa: ["Para los barcos de vela", "Sevilla tiene un camino;", "por el agua de Granada", "sólo reman los suspiros."] },
      { estrofa: ["¡Ay, amor", "que se fue y no vino!"] },
      { estrofa: ["Guadalquivir, alta torre", "y viento en los naranjales.", "Dauro y Genil, torrecillas", "muertas sobre los estanques."] },
      { estrofa: ["¡Ay, amor", "que se fue por el aire!"] },
      { estrofa: ["¡Quién dirá que el agua lleva", "un fuego fatuo de gritos!"] },
      { estrofa: ["¡Ay, amor", "que se fue y no vino!"] },
      { estrofa: ["Lleva azahar, lleva olivas,", "Andalucía, a tus mares."] },
      { estrofa: ["¡Ay, amor", "que se fue por el aire!"] },
    ],
    vocabulario: [
      { p: "granate", d: "rojo oscuro" },
      { p: "Dauro y Genil", d: "los dos ríos de Granada (el Dauro es el río Darro)" },
      { p: "fuego fatuo", d: "llamita que a veces aparece de noche sobre el suelo" },
      { p: "azahar", d: "flor blanca del naranjo" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuáles son los tres ríos del título? ¿A qué ciudades pertenecen según el poema?", r: "El Guadalquivir, de Sevilla, y el Dauro (Darro) y el Genil, los dos ríos de Granada.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué diferencias hay entre el Guadalquivir y los ríos de Granada según el poema?", r: "El Guadalquivir es grande, lleva barcos de vela, pasa entre naranjos y olivos y llega al mar. Los ríos de Granada son pequeños, bajan de la nieve, parecen tristes (llanto, sangre, suspiros) y acaban en estanques.", lineas: 3 },
      { tipo: "comprension", q: "¿Qué quiere decir que por el agua de Granada «sólo reman los suspiros»?", r: "Que los ríos de Granada no son navegables, no pasan barcos: solo hay tristeza, suspiros.", lineas: 2 },
      { tipo: "comprension", q: "¿Adónde lleva el río el azahar y las olivas? Elige:", opciones: ["A la nieve de Sierra Nevada", "A los mares de Andalucía", "A los estanques de Granada"], r: "A los mares de Andalucía" },
      { tipo: "comprension", q: "¿Qué sentimiento expresan los versos «¡Ay, amor / que se fue y no vino!»?", r: "Tristeza y añoranza por un amor que se marchó y no volvió.", lineas: 2 },
      { tipo: "texto", q: "¿Qué es un estribillo? Copia el de este poema y di cuántas veces aparece. Busca también una personificación y di en qué vocales riman «olivos» y «trigo».", r: "Un estribillo es un verso o grupo de versos que se repite a lo largo del poema. Aquí es «¡Ay, amor / que se fue y no vino!» o «…que se fue por el aire!»: aparece 6 veces, alternando los dos finales. Personificación: «El río Guadalquivir tiene las barbas granates» o «reman los suspiros». Olivos/trigo riman en i-o: rima asonante.", lineas: 4 },
      { tipo: "opinion", q: "¿Cuál de los ríos te parece más alegre en el poema y cuál más triste? ¿Por qué?", r: "Respuesta libre. Valorar que se apoye en versos concretos.", lineas: 2 },
      { tipo: "opinion", q: "Si escribieras una baladilla sobre el río de tu provincia, ¿qué contarías de él?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Los ríos han dado vida a las ciudades andaluzas durante siglos. ¿Por qué crees que es importante cuidar los ríos y no contaminarlos?", r: "Respuesta libre. Valorar que mencione el agua, la fauna, la agricultura y la salud.", lineas: 3 },
    ],
  },
  {
    id: "poesia-10-golondrinas-becquer",
    titulo: "Volverán las oscuras golondrinas (fragmento)",
    subtipo: "Rima",
    curso: "6º",
    fuente: "Gustavo Adolfo Bécquer, Rima LIII (Rimas, 1871), fragmento: las cuatro primeras estrofas",
    antes: "Bécquer nació en Sevilla y es uno de los poetas más leídos en español. ¿Qué animales o plantas te anuncian que llega la primavera?",
    texto: [
      { estrofa: ["Volverán las oscuras golondrinas", "en tu balcón sus nidos a colgar,", "y otra vez con el ala a sus cristales", "jugando llamarán;"] },
      { estrofa: ["pero aquellas que el vuelo refrenaban", "tu hermosura y mi dicha al contemplar,", "aquellas que aprendieron nuestros nombres,", "ésas... ¡no volverán!"] },
      { estrofa: ["Volverán las tupidas madreselvas", "de tu jardín las tapias a escalar,", "y otra vez a la tarde, aún más hermosas,", "sus flores se abrirán;"] },
      { estrofa: ["pero aquellas cuajadas de rocío,", "cuyas gotas mirábamos temblar", "y caer, como lágrimas del día...", "ésas... ¡no volverán!"] },
    ],
    vocabulario: [
      { p: "refrenar", d: "frenar, detener" },
      { p: "dicha", d: "felicidad" },
      { p: "tupido", d: "espeso, con las hojas muy juntas" },
      { p: "madreselva", d: "planta trepadora de flores muy olorosas" },
      { p: "tapia", d: "muro que rodea un jardín o un terreno" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Según el poeta, ¿qué volverá con el paso del tiempo?", r: "Volverán las golondrinas a colgar sus nidos en el balcón y las madreselvas a trepar por las tapias del jardín y a abrir sus flores.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué golondrinas y qué madreselvas no volverán?", r: "Las golondrinas que se paraban a contemplar la felicidad de los dos y aprendieron sus nombres, y las madreselvas cubiertas de rocío que ellos miraban juntos.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el poeta con «ésas... ¡no volverán!»?", r: "Que, aunque la primavera vuelva cada año, los momentos felices que vivió no se repetirán: el pasado no vuelve. Siente tristeza y nostalgia.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa «tupidas madreselvas»? Elige:", opciones: ["Madreselvas secas y sin hojas", "Madreselvas espesas, con muchas hojas y flores", "Madreselvas pequeñas, recién plantadas"], r: "Madreselvas espesas, con muchas hojas y flores" },
      { tipo: "comprension", q: "¿En qué estación del año piensa el poeta al hablar de lo que volverá? ¿Cómo lo sabes?", r: "En la primavera: es cuando regresan las golondrinas a hacer sus nidos y cuando florecen las madreselvas.", lineas: 2 },
      { tipo: "texto", q: "¿Cuántas estrofas y versos tiene el fragmento? Cuenta las sílabas de «Volverán las oscuras golondrinas» y de «jugando llamarán». ¿Qué versos riman y en qué vocal? Copia una comparación.", r: "4 estrofas y 16 versos. «Vol-ve-rán-las-os-cu-ras-go-lon-dri-nas»: 11 sílabas (arte mayor); «ju-gan-do-lla-ma-rán»: 6 + 1 por ser aguda = 7 (arte menor). Riman los versos pares en «á» (colgar, llamarán, contemplar, volverán, escalar, abrirán, temblar): rima asonante. Comparación: «como lágrimas del día».", lineas: 4 },
      { tipo: "opinion", q: "¿Estás de acuerdo con el poeta en que los buenos momentos no vuelven? ¿Por qué?", r: "Respuesta libre. Valorar que argumente (pueden vivirse otros momentos nuevos, los recuerdos permanecen…).", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que este poema se sigue leyendo y recitando más de ciento cincuenta años después?", r: "Respuesta libre. Valorar que hable de sentimientos universales, de la música de los versos, de las imágenes…", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué momento feliz te gustaría guardar para siempre? ¿Qué podemos hacer para no olvidar los buenos recuerdos?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
];
