// Lecturas · Poesía (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["poesia"] = [
  {
    id: "poesia-01-haikus-andaluces",
    titulo: "Cuatro haikus andaluces",
    subtipo: "Haiku (serie de cuatro)",
    curso: "5º",
    fuente: "Poema original; apartado «Para saber más»: texto original",
    datos: ["Wikipedia: Haiku (métrica 5-7-5, kigo, Matsuo Bashō)"],
    antes: "¿Qué cambia en el paisaje de tu pueblo o tu ciudad de una estación a otra? Di una cosa de cada estación.",
    texto: [
      { h: "Primavera en Doñana" },
      { estrofa: ["Flamencos rosas", "duermen sobre una pata", "en la marisma."] },
      { h: "Verano en Jaén" },
      { estrofa: ["Siesta de agosto", "y la cigarra canta", "bajo el olivo."] },
      { h: "Otoño en el pueblo" },
      { estrofa: ["Lluvia de octubre.", "Los caracoles salen", "a ver el mundo."] },
      { h: "Invierno en Granada" },
      { estrofa: ["Primera nieve", "en la Sierra Nevada:", "se pone el gorro."] },
      { h: "Para saber más: ¿qué es un haiku?" },
      { p: "El haiku es un poema muy breve que nació en Japón. Tiene solo tres versos: el primero y el tercero son de cinco sílabas, y el del medio, de siete. En japonés no se cuentan sílabas como en español, sino unos sonidos parecidos, pero cuando escribimos haikus en nuestra lengua usamos la medida 5-7-5. Los haikus no suelen tener rima ni cuentan una historia: atrapan un instante, como si fueran una fotografía hecha con palabras. Hoy se escriben haikus en muchas lenguas del mundo, también en español." },
      { p: "El poeta de haikus más famoso es Matsuo Bashō, que vivió en Japón en el siglo XVII y recorrió a pie su país fijándose en todo lo que encontraba por el camino. Su haiku más conocido habla de un viejo estanque y de una rana que salta al agua. No pasa nada más, y sin embargo, al leerlo, casi se puede oír el chapuzón. Bashō sabía que, a veces, lo más pequeño es lo que más nos sorprende." },
      { p: "Muchos haikus tradicionales llevan una palabra que indica la estación del año: la nieve, las flores del cerezo, la cigarra, las hojas secas… Esa palabra es como una pista para el lector, que así imagina enseguida el frío, el calor o la lluvia. Por eso nuestros cuatro haikus andaluces siguen el orden de las estaciones y cada uno esconde la suya: los flamencos que vuelven en primavera, la siesta de agosto, la lluvia de octubre y la primera nieve." },
      { lista: ["Sal a mirar: el patio, un parque o la ventana de clase.", "Elige un solo detalle pequeño: un gorrión, un charco, una hoja que cae.", "Escríbelo en tres versos y cuenta las sílabas con los dedos: 5, 7 y 5.", "Añade una palabra que diga en qué estación estás.", "Léelo en voz alta y quita todo lo que sobre."], ordenada: true, titulo: "Cómo escribir tu propio haiku" },
    ],
    vocabulario: [
      { p: "marisma", d: "terreno llano y encharcado cerca de la desembocadura de un río" },
      { p: "cigarra", d: "insecto que en verano produce un sonido agudo y continuo" },
      { p: "siesta", d: "rato de descanso después de comer" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué animal aparece en cada uno de los tres primeros haikus y qué está haciendo?", r: "Los flamencos duermen sobre una pata; la cigarra canta bajo el olivo; los caracoles salen con la lluvia.", lineas: 2 },
      { tipo: "comprension", q: "¿Quién «se pone el gorro» en el último haiku? ¿Cuál es ese gorro en realidad?", r: "La Sierra Nevada. El gorro es la primera nieve, que cubre de blanco las cumbres como si fuera un gorro.", lineas: 2 },
      { tipo: "comprension", q: "Según «Para saber más», ¿por qué muchos haikus llevan palabras como nieve, cigarra u hojas secas? Elige:", opciones: ["Porque riman con los otros versos", "Porque son pistas que indican la estación del año", "Porque son palabras japonesas"], r: "Porque son pistas que indican la estación del año" },
      { tipo: "texto", q: "Cuenta las sílabas del haiku de invierno, verso a verso. ¿Cumple la medida 5-7-5? ¿Tiene rima? ¿Qué recurso literario hay en el último verso?", r: "Pri-me-ra-nie-ve (5) / en-la-Sie-rra-Ne-va-da (7) / se-po-neel-go-rro (5): sí cumple 5-7-5 y no tiene rima, como todo haiku. En «se pone el gorro» hay una personificación: la sierra hace algo propio de las personas.", lineas: 3 },
      { tipo: "opinion", q: "Sigue los pasos del texto y escribe tu propio haiku (5-7-5) sobre un lugar de tu localidad en la estación en la que estamos.", r: "Respuesta libre. Comprobar que respeta la medida 5-7-5 y que incluye una pista de la estación.", lineas: 3 },
      { tipo: "reflexion", q: "Los haikus se fijan en detalles pequeños: una cigarra, un caracol… ¿Por qué crees que es importante pararse a observar la naturaleza que tenemos cerca?", r: "Respuesta libre. Valorar que hable de disfrutar, conocer y cuidar el entorno.", lineas: 2 },
    ],
  },
  {
    id: "poesia-02-cancioncilla-sevillana",
    titulo: "Cancioncilla sevillana y Caracola",
    subtipo: "Canción lírica (dos canciones)",
    curso: "5º",
    fuente: "Federico García Lorca, «Cancioncilla sevillana» y «Caracola» (Canciones, 1927, sección «Canciones para niños»); apartado «Para saber más»: texto original",
    datos: ["Wikipedia: Federico García Lorca", "Wikisource: Canciones (1927), índice de «Canciones para niños»"],
    antes: "Lorca nació en Fuente Vaqueros (Granada) y escribió muchas canciones sobre Andalucía. ¿Qué árboles y flores crees que puede haber en un amanecer en Sevilla?",
    texto: [
      { h: "Cancioncilla sevillana" },
      { estrofa: ["Amanecía", "en el naranjel.", "Abejitas de oro", "buscaban la miel."] },
      { estrofa: ["¿Dónde estará", "la miel?"] },
      { estrofa: ["Está en la flor azul,", "Isabel.", "En la flor,", "del romero aquel."] },
      { estrofa: ["(Sillita de oro", "para el moro.", "Silla de oropel", "para su mujer)."] },
      { estrofa: ["Amanecía,", "en el naranjel."] },
      { h: "Caracola" },
      { estrofa: ["Me han traído una caracola."] },
      { estrofa: ["Dentro le canta", "un mar de mapa.", "Mi corazón", "se llena de agua", "con pececillos", "de sombra y plata."] },
      { estrofa: ["Me han traído una caracola."] },
      { h: "Para saber más: Lorca, poeta y músico" },
      { p: "Federico García Lorca nació en 1898 en Fuente Vaqueros, un pueblo de la vega de Granada. De joven le interesaba más la música que la literatura: estudió piano, y sus amigos de la universidad lo conocían antes como músico que como escritor. Quizá por eso sus poemas suenan tanto: tienen ritmo, repeticiones y estribillos, como las canciones que se cantan en la calle." },
      { p: "Los dos poemas de esta ficha forman parte de su libro Canciones, que se imprimió en Málaga en 1927. Están dentro de un apartado que el propio poeta tituló «Canciones para niños». En ellos Lorca juega con las palabras como se juega en el patio: usa diminutivos cariñosos como «abejitas», «sillita» o «pececillos», repite versos y rimas y escribe versos muy cortos que se pueden cantar." },
      { p: "En «Caracola» ocurre algo que seguro que conoces: al acercar una caracola al oído, parece que dentro suena el mar. El poeta imagina que ese mar pequeño, un mar de mapa, se le mete en el corazón y se lo llena de agua y de pececillos de sombra y plata. El poema empieza y termina con el mismo verso, como si el poeta no se cansara de enseñarnos su regalo." },
    ],
    vocabulario: [
      { p: "naranjel", d: "naranjal, huerto de naranjos" },
      { p: "romero", d: "arbusto oloroso de flores pequeñas y azuladas" },
      { p: "oropel", d: "lámina de metal que imita al oro: brilla mucho pero vale poco" },
      { p: "caracola", d: "concha grande en espiral de algunos caracoles de mar" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué crees que el poeta llama a las abejas «abejitas de oro»?", r: "Porque son amarillas y brillan con la luz del amanecer, como si fueran de oro. El diminutivo «abejitas» muestra cariño.", lineas: 2 },
      { tipo: "comprension", q: "En «Caracola», ¿qué se oye dentro de la caracola? ¿Qué le pasa al corazón del poeta al escucharla?", r: "Se oye el mar («un mar de mapa»). Su corazón se llena de agua con pececillos de sombra y plata: se emociona, como si el mar entrara dentro de él.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué es una «silla de oropel»? Elige:", opciones: ["Una silla de oro auténtico, muy cara", "Una silla que brilla como el oro, pero no es de oro", "Una silla de madera de naranjo"], r: "Una silla que brilla como el oro, pero no es de oro" },
      { tipo: "texto", q: "¿Cuántas estrofas y cuántos versos tiene «Cancioncilla sevillana»? Copia las palabras que riman con «miel». ¿Es rima consonante o asonante?", r: "5 estrofas y 16 versos. Riman con «miel»: naranjel, Isabel, aquel y oropel, en rima consonante (coincide -el). «Mujer» rima en asonante (solo coincide la e).", lineas: 3 },
      { tipo: "opinion", q: "Si tuvieras que dibujar uno de los dos poemas, ¿cuál elegirías y qué colores usarías? ¿Por qué?", r: "Respuesta libre. Valorar que relacione los colores con palabras del poema (oro, azul, naranjel, amanecer, sombra, plata…).", lineas: 3 },
      { tipo: "reflexion", q: "Las abejas buscan la miel en las flores. ¿Por qué son tan importantes las abejas para el campo y para las personas?", r: "Respuesta libre. Valorar que mencione la polinización de plantas y cultivos y la necesidad de protegerlas.", lineas: 2 },
    ],
  },
  {
    id: "poesia-03-burro-flautista",
    titulo: "El burro flautista",
    subtipo: "Fábula en verso",
    curso: "5º",
    fuente: "Tomás de Iriarte, «El burro flautista» (Fábulas literarias, 1782); apartado «Para saber más»: texto original",
    datos: ["Wikipedia: Tomás de Iriarte"],
    antes: "¿Te ha salido alguna vez algo bien por pura suerte? ¿Te atreverías a presumir de ello?",
    texto: [
      { estrofa: ["Esta fabulilla,", "salga bien o mal,", "me ha ocurrido ahora", "por casualidad."] },
      { estrofa: ["Cerca de unos prados", "que hay en mi lugar,", "pasaba un borrico", "por casualidad."] },
      { estrofa: ["Una flauta en ellos", "halló, que un zagal", "se dejó olvidada", "por casualidad."] },
      { estrofa: ["Acercóse a olerla", "el dicho animal,", "y dio un resoplido", "por casualidad."] },
      { estrofa: ["En la flauta el aire", "se hubo de colar,", "y sonó la flauta", "por casualidad."] },
      { estrofa: ["«¡Oh! —dijo el borrico—,", "¡qué bien sé tocar!", "¡Y dirán que es mala", "la música asnal!»"] },
      { estrofa: ["Sin reglas del arte,", "borriquitos hay", "que una vez aciertan", "por casualidad."] },
      { h: "Para saber más: Tomás de Iriarte, fabulista y músico" },
      { p: "Tomás de Iriarte nació en 1750 en el Puerto de la Cruz, en la isla de Tenerife. Cuando tenía catorce años se marchó a vivir a Madrid con su tío Juan de Iriarte, un gran estudioso y poeta, y allí se hizo escritor: compuso poemas y obras de teatro y tradujo libros de otras lenguas." },
      { p: "Además de escribir, Iriarte era un gran aficionado a la música. Tocaba el violín y la viola, y llegó a escribir un largo poema titulado «La música». Quizá por eso le hizo tanta gracia imaginar a un burro que, por un simple resoplido, se cree un gran flautista." },
      { p: "En 1782 publicó sus Fábulas literarias. Son unas fábulas especiales: sus animales no enseñan a ser prudentes o generosos, sino a hacer bien las cosas, sobre todo a escribir. En el prólogo, Iriarte presumía de ser el primer español en escribir una colección de fábulas totalmente originales. Aquello le costó una larga pelea con su amigo Félix María Samaniego, otro gran fabulista, que había publicado las suyas un año antes." },
      { p: "La fábula del burro se hizo tan popular que todavía hoy, cuando alguien acierta sin saber muy bien cómo, se dice que ha sonado la flauta por casualidad." },
    ],
    vocabulario: [
      { p: "zagal", d: "muchacho joven; a menudo, pastor" },
      { p: "resoplido", d: "soplido fuerte que se da por la nariz" },
      { p: "asnal", d: "de los asnos o burros" },
      { p: "mi lugar", d: "aquí, mi pueblo" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cómo consiguió el burro que sonara la flauta?", r: "Se acercó a olerla, dio un resoplido y el aire se coló por la flauta, que sonó por casualidad.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice el burro «¡Qué bien sé tocar!»? ¿Tiene razón?", r: "Porque cree que tiene talento para la música. No tiene razón: la flauta sonó por casualidad, no porque supiera tocarla. Es un burro presumido.", lineas: 2 },
      { tipo: "comprension", q: "Según «Para saber más», ¿qué tienen de especial las Fábulas literarias de Iriarte? Elige:", opciones: ["Que sus protagonistas son siempre personas", "Que sus moralejas enseñan a hacer bien las cosas, sobre todo a escribir", "Que no tienen moraleja"], r: "Que sus moralejas enseñan a hacer bien las cosas, sobre todo a escribir" },
      { tipo: "texto", q: "¿Cuántas estrofas y versos tiene la fábula? Cuenta las sílabas del primer verso: ¿es de arte mayor o menor? ¿Qué versos riman y en qué vocal?", r: "7 estrofas de 4 versos: 28 versos. «Es-ta-fa-bu-li-lla» tiene 6 sílabas: arte menor. Riman los versos pares en «a» (mal, casualidad, lugar, zagal, animal, colar, tocar, asnal…); los impares quedan sueltos.", lineas: 3 },
      { tipo: "opinion", q: "¿Recuerdas algo que te salió bien por casualidad y luego no te volvió a salir? Cuéntalo. ¿Presumiste como el burro?", r: "Respuesta libre. Valorar que relacione la fábula con su experiencia.", lineas: 3 },
      { tipo: "reflexion", q: "¿Por qué es importante practicar y aprender en lugar de confiar en la suerte? Pon un ejemplo del colegio o del deporte.", r: "Respuesta libre. Valorar que explique que el esfuerzo permite repetir los buenos resultados.", lineas: 2 },
    ],
  },
  {
    id: "poesia-04-mi-mochila",
    titulo: "Mi mochila",
    subtipo: "Poema humorístico (dos poemas)",
    curso: "5º",
    fuente: "Poemas originales",
    antes: "¿Cuánto crees que pesa tu mochila? ¿Qué hay dentro que quizá no necesites?",
    texto: [
      { h: "Mi mochila" },
      { estrofa: ["Mi mochila pesa tanto", "como un camión de melones;", "cuando la subo, ¡qué espanto!,", "gimen los cuatro escalones."] },
      { estrofa: ["Dentro vive un bocadillo", "de hace un mes, o tal vez dos,", "que ya tiene bigotillo", "y me dice: «¡Adiós, adiós!»."] },
      { estrofa: ["Llevo libros, un compás,", "tres estuches, la merienda,", "una flauta y algo más:", "¡casi cabe media tienda!"] },
      { estrofa: ["En el fondo hay un tesoro:", "una canica, un botón,", "un cromo que vale oro", "y la válvula de un balón."] },
      { estrofa: ["Si busco la goma nueva,", "meto el brazo hasta el codo;", "es negra como una cueva", "y allí dentro cabe todo."] },
      { estrofa: ["Y mi abuela dice, riendo:", "«Esa mochila es un tren».", "Y yo contesto sonriendo:", "«¡Pues que me lleve también!»."] },
      { h: "La mochila contesta" },
      { estrofa: ["Soy tu mochila y te escribo", "porque ya no puedo más:", "llevo un peso excesivo", "y me duele por detrás."] },
      { estrofa: ["Mis cremalleras son dientes", "que ya no pueden morder;", "mis tirantes, muy valientes,", "se empiezan a descoser."] },
      { estrofa: ["Ya no quiero el bocadillo", "que se esconde en mi rincón:", "tiene ya su bigotillo", "y me da mala impresión."] },
      { estrofa: ["Te propongo, pues, un trato:", "mira el horario al cenar,", "dedica a ordenarme un rato", "y déjame respirar."] },
      { estrofa: ["Los escalones, contentos,", "ya no tendrán que gemir,", "y tú, sin quejas ni lamentos,", "irás al cole a reír."] },
    ],
    vocabulario: [
      { p: "gemir", d: "quejarse con sonidos de pena o de dolor" },
      { p: "espanto", d: "susto muy grande" },
      { p: "compás", d: "instrumento para trazar circunferencias" },
      { p: "excesivo", d: "que es demasiado, que pasa de lo normal" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué el bocadillo «ya tiene bigotillo»?", r: "Porque lleva uno o dos meses olvidado en la mochila y le ha salido moho, que parece un bigote. Es una forma graciosa de decir que está estropeado.", lineas: 2 },
      { tipo: "comprension", q: "En «La mochila contesta», ¿qué le pide la mochila al protagonista y por qué?", r: "Le propone un trato: que mire el horario al cenar, dedique un rato a ordenarla y saque lo que sobra, porque lleva demasiado peso, le duele, sus cremalleras y tirantes se estropean y no quiere el bocadillo viejo.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el protagonista con «¡Pues que me lleve también!»? Elige:", opciones: ["Que quiere hacer un viaje en tren", "Que, si la mochila es un tren, lo lleve a él y así no tiene que cargarla", "Que su abuela debe llevarle la mochila"], r: "Que, si la mochila es un tren, lo lleve a él y así no tiene que cargarla" },
      { tipo: "texto", q: "Busca en los poemas un ejemplo de cada recurso: comparación, metáfora, personificación e hipérbole.", r: "Comparación: «pesa tanto como un camión de melones» o «es negra como una cueva». Metáfora: «Esa mochila es un tren» o «Mis cremalleras son dientes». Personificación: «gimen los cuatro escalones» o la mochila que escribe una carta. Hipérbole: «¡casi cabe media tienda!» o «allí dentro cabe todo».", lineas: 3 },
      { tipo: "opinion", q: "Inventa una estrofa más de cuatro versos sobre otra cosa que podría esconderse en esa mochila. Intenta que rime.", r: "Respuesta libre. Valorar la rima y el humor.", lineas: 3 },
      { tipo: "reflexion", q: "Llevar demasiado peso a la espalda no es bueno para la salud. ¿Qué podrías hacer tú para que tu mochila pese menos?", r: "Respuesta libre. Valorar ideas prácticas: preparar la mochila con el horario, no llevar cosas innecesarias, usar la taquilla…", lineas: 2 },
    ],
  },
  {
    id: "poesia-05-las-moscas",
    titulo: "Las moscas",
    subtipo: "Poema lírico",
    curso: "5º",
    fuente: "Antonio Machado, «Las moscas» (Soledades. Galerías. Otros poemas, 1907), poema completo",
    antes: "Las moscas suelen molestarnos. ¿Se te ocurre algo bueno que podría decirse de ellas en un poema?",
    texto: [
      { estrofa: ["Vosotras, las familiares,", "inevitables golosas;", "vosotras, moscas vulgares,", "me evocáis todas las cosas."] },
      { estrofa: ["¡Oh viejas moscas voraces", "como abejas en abril,", "viejas moscas pertinaces", "sobre mi calva infantil!"] },
      { estrofa: ["¡Moscas del primer hastío", "en el salón familiar,", "las claras tardes de estío", "en que yo empecé a soñar!"] },
      { estrofa: ["Y en la aborrecida escuela,", "raudas moscas divertidas,", "perseguidas", "por amor de lo que vuela"] },
      { estrofa: ["—que todo es volar—, sonoras,", "rebotando en los cristales", "en los días otoñales...", "Moscas de todas las horas,"] },
      { estrofa: ["de infancia y adolescencia,", "de mi juventud dorada;", "de esta segunda inocencia,", "que da en no creer en nada;"] },
      { estrofa: ["de siempre... Moscas vulgares,", "que de puro familiares", "no tendréis digno cantor:", "yo sé que os habéis posado"] },
      { estrofa: ["sobre el juguete encantado,", "sobre el librote cerrado,", "sobre la carta de amor,", "sobre los párpados yertos", "de los muertos."] },
      { estrofa: ["Inevitables golosas,", "que ni labráis como abejas", "ni brilláis cual mariposas;", "pequeñitas, revoltosas,", "vosotras, amigas viejas,", "me evocáis todas las cosas."] },
      { h: "Para saber más: un poema de la memoria" },
      { p: "Antonio Machado publicó «Las moscas» en 1907, en su libro Soledades. Galerías. Otros poemas. Es un poema de la memoria: unos insectos pequeños y molestos le traen al poeta todos los momentos de su vida, desde las tardes aburridas de la niñez hasta la edad adulta. Machado nos demuestra así que cualquier cosa, hasta una mosca, puede ser el tema de un gran poema." },
    ],
    vocabulario: [
      { p: "evocar", d: "traer algo a la memoria, recordar" },
      { p: "pertinaz", d: "que insiste mucho y no se rinde" },
      { p: "hastío", d: "aburrimiento" },
      { p: "estío", d: "verano" },
      { p: "raudo", d: "muy rápido" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿En qué lugares y momentos de su vida recuerda el poeta a las moscas?", r: "En el salón de su casa las tardes claras de verano, en la escuela en los días de otoño, y en todas las épocas de su vida: infancia, adolescencia, juventud y edad adulta.", lineas: 2 },
      { tipo: "comprension", q: "¿Siente el poeta rabia o cariño por las moscas? Justifica tu respuesta con palabras del texto.", r: "Siente cariño y nostalgia: las llama «familiares», «pequeñitas, revoltosas» y «amigas viejas», y las une a sus recuerdos, aunque sean pesadas y golosas.", lineas: 2 },
      { tipo: "comprension", q: "En la escuela, ¿por qué perseguían los niños a las moscas? Elige:", opciones: ["Porque les molestaban mientras estudiaban", "Por amor de lo que vuela: porque les encantaba todo lo que vuela", "Porque el maestro se lo mandaba"], r: "Por amor de lo que vuela: porque les encantaba todo lo que vuela" },
      { tipo: "texto", q: "Copia la comparación de la segunda estrofa. Después, compara la primera estrofa con la última: ¿qué versos se repiten? ¿Qué efecto produce?", r: "Comparación: «voraces como abejas en abril». Se repiten «inevitables golosas» y «me evocáis todas las cosas» (y «vosotras»). El poema termina casi como empieza: es una estructura circular que cierra el poema como un estribillo.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué animal, olor u objeto te recuerda a ti a cuando eras más pequeño o pequeña? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Machado escribe sobre algo que casi todo el mundo desprecia. ¿Crees que merece la pena fijarse en las cosas pequeñas o molestas? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
    ],
  },
  {
    id: "poesia-06-recuerdo-infantil",
    titulo: "Recuerdo infantil",
    subtipo: "Poema lírico",
    curso: "5º-6º",
    fuente: "Antonio Machado, «Recuerdo infantil» (Soledades, Galerías y otros poemas, ed. de 1919) y primera estrofa de «Retrato» (Campos de Castilla, 1912); apartado «Para saber más»: texto original",
    datos: ["Wikipedia: Antonio Machado"],
    antes: "Antonio Machado nació en Sevilla y fue alumno y también profesor. ¿Cómo imaginas una clase de hace más de cien años?",
    texto: [
      { estrofa: ["Una tarde parda y fría", "de invierno. Los colegiales", "estudian. Monotonía", "de lluvia tras los cristales."] },
      { estrofa: ["Es la clase. En un cartel", "se representa a Caín", "fugitivo, y muerto Abel,", "junto a una mancha carmín."] },
      { estrofa: ["Con timbre sonoro y hueco,", "truena el maestro, un anciano", "mal vestido, enjuto y seco,", "que lleva un libro en la mano."] },
      { estrofa: ["Y todo un coro infantil", "va cantando la lección:", "mil veces ciento, cien mil;", "mil veces mil, un millón."] },
      { estrofa: ["Una tarde parda y fría", "de invierno. Los colegiales", "estudian. Monotonía", "de la lluvia en los cristales."] },
      { h: "Otro recuerdo: el comienzo de «Retrato»" },
      { estrofa: ["Mi infancia son recuerdos de un patio de Sevilla", "y un huerto claro donde madura el limonero;", "mi juventud, veinte años en tierra de Castilla;", "mi historia, algunos casos que recordar no quiero."] },
      { h: "Para saber más: Antonio Machado, alumno y maestro" },
      { p: "Antonio Machado nació en Sevilla en 1875, en una de las viviendas del palacio de las Dueñas, un edificio con patios y jardines. Muchos años después, al escribir sobre su vida, lo primero que recordó fue aquel patio sevillano y el limonero del huerto. En 1883, cuando tenía ocho años, su familia se trasladó a Madrid, y Antonio tuvo que despedirse de Sevilla." },
      { p: "En Madrid estudió en la Institución Libre de Enseñanza, una escuela muy distinta de la del poema. Allí los maestros hacían excursiones con los alumnos, conversaban con ellos y procuraban que aprendieran pensando, no repitiendo de memoria. Machado escribió de mayor que conservaba un gran amor a sus maestros de entonces, a los que nombraba uno por uno." },
      { p: "Con el tiempo, él también fue profesor: dio clases de francés en institutos de Soria, de Baeza, en la provincia de Jaén, y de Segovia. Quizá por eso le gustaba tanto recordar cómo eran las clases de su niñez, las buenas y las aburridas." },
      { p: "Los dos poemas de esta ficha miran hacia la infancia, pero de forma distinta: «Recuerdo infantil» nos mete en una clase gris y aburrida, mientras que «Retrato» empieza con la luz de un patio y un limonero. Así es la memoria: guarda a la vez los ratos tristes y los felices." },
    ],
    vocabulario: [
      { p: "pardo", d: "de color oscuro, entre gris y marrón" },
      { p: "monotonía", d: "falta de variedad: todo igual, aburrido" },
      { p: "carmín", d: "rojo intenso" },
      { p: "enjuto", d: "muy delgado" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Describe al maestro de «Recuerdo infantil» con las palabras del poema.", r: "Es un anciano mal vestido, enjuto y seco, con una voz sonora y hueca, que lleva un libro en la mano.", lineas: 2 },
      { tipo: "comprension", q: "¿El poeta recuerda aquella clase como divertida o aburrida? ¿Qué palabras te dan la pista?", r: "Como aburrida y triste: «parda», «fría», «monotonía», la lluvia, la lección repetida en coro y el maestro que «truena».", lineas: 2 },
      { tipo: "comprension", q: "Según «Para saber más», ¿en qué se diferenciaba la escuela de Machado en Madrid de la clase del poema? Elige:", opciones: ["En que allí se aprendía cantando las tablas en coro", "En que los maestros procuraban que se aprendiera pensando, no repitiendo de memoria", "En que no había maestros"], r: "En que los maestros procuraban que se aprendiera pensando, no repitiendo de memoria" },
      { tipo: "texto", q: "¿Cuántas estrofas y versos tiene «Recuerdo infantil»? ¿Qué versos riman y de qué tipo es la rima? ¿Qué tiene de especial la última estrofa?", r: "5 estrofas de 4 versos: 20 versos. Riman el 1.º con el 3.º y el 2.º con el 4.º (fría/Monotonía, colegiales/cristales, cartel/Abel…): rima consonante. La última estrofa repite la primera con un pequeño cambio («de la lluvia en los cristales»), así que el poema acaba como empezó (estructura circular).", lineas: 3 },
      { tipo: "opinion", q: "Compara la clase del poema con la tuya. ¿Qué diferencias y qué parecidos encuentras?", r: "Respuesta libre. Valorar que mencione aspectos concretos (forma de aprender, materiales, maestro, ambiente…).", lineas: 3 },
      { tipo: "reflexion", q: "Machado recordó toda su vida el patio de Sevilla y aquella clase. ¿Qué momento de tu colegio crees que recordarás de mayor? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "poesia-07-paisaje-lorca",
    titulo: "Paisaje y La guitarra",
    subtipo: "Poema lírico (dos poemas)",
    curso: "5º-6º",
    fuente: "Federico García Lorca, «Paisaje» y «La guitarra» (Poema del cante jondo, 1931; sección «Poema de la siguiriya gitana»)",
    antes: "Lorca escribió estos dos poemas en 1921 para su Poema del cante jondo, inspirado en el flamenco. ¿Has visto alguna vez un olivar? ¿Y has oído una guitarra flamenca? ¿Qué te transmite su música?",
    texto: [
      { h: "Paisaje" },
      { estrofa: ["El campo", "de olivos", "se abre y se cierra", "como un abanico.", "Sobre el olivar", "hay un cielo hundido", "y una lluvia oscura", "de luceros fríos.", "Tiembla junco y penumbra", "a la orilla del río.", "Se riza el aire gris.", "Los olivos", "están cargados", "de gritos.", "Una bandada", "de pájaros cautivos,", "que mueven sus larguísimas", "colas en lo sombrío."] },
      { h: "La guitarra" },
      { estrofa: ["Empieza el llanto", "de la guitarra.", "Se rompen las copas", "de la madrugada.", "Empieza el llanto", "de la guitarra.", "Es inútil callarla.", "Es imposible", "callarla.", "Llora monótona", "como llora el agua,", "como llora el viento", "sobre la nevada.", "Es imposible", "callarla.", "Llora por cosas", "lejanas.", "Arena del Sur caliente", "que pide camelias blancas.", "Llora flecha sin blanco,", "la tarde sin mañana,", "y el primer pájaro muerto", "sobre la rama.", "¡Oh, guitarra!", "Corazón malherido", "por cinco espadas."] },
    ],
    vocabulario: [
      { p: "penumbra", d: "sombra débil, con muy poca luz" },
      { p: "junco", d: "planta de tallo largo y flexible que crece junto al agua" },
      { p: "cautivo", d: "preso, que no puede escapar" },
      { p: "monótono", d: "que suena siempre igual, sin cambios" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿En qué momento del día crees que ocurre la escena de «Paisaje»? Justifica tu respuesta.", r: "Al anochecer o de noche: hay luceros (estrellas), penumbra, el aire es gris y todo está «en lo sombrío».", lineas: 2 },
      { tipo: "comprension", q: "En «La guitarra», ¿con qué compara el poeta el llanto de la guitarra? ¿Por qué crees que es «imposible callarla»?", r: "Con el llanto del agua y del viento sobre la nevada. Es imposible callarla porque expresa una pena muy honda que necesita salir, como la música flamenca.", lineas: 2 },
      { tipo: "comprension", q: "Al final de «La guitarra», su corazón está «malherido por cinco espadas». ¿Qué crees que son esas cinco espadas? Elige:", opciones: ["Cinco guitarristas que tocan a la vez", "Los cinco dedos de la mano que toca las cuerdas", "Cinco espadas de verdad colgadas en la pared"], r: "Los cinco dedos de la mano que toca las cuerdas" },
      { tipo: "texto", q: "Localiza una comparación en cada poema y una personificación en cualquiera de los dos. En «Paisaje», ¿en qué vocales riman los versos pares? ¿Es rima consonante o asonante?", r: "Comparaciones: «se abre y se cierra como un abanico» y «Llora monótona como llora el agua». Personificación: «Los olivos están cargados de gritos», «Tiembla junco y penumbra» o la guitarra que llora. Los versos pares de «Paisaje» (olivos, abanico, hundido, fríos, río…) riman en í-o: rima asonante.", lineas: 3 },
      { tipo: "opinion", q: "Lorca dice que los olivos están «cargados de gritos» y que la guitarra «llora». ¿Qué crees que quiere decir? ¿Qué instrumento o sonido te emociona a ti?", r: "Respuesta libre. Puede interpretarse como el ruido de los pájaros, el viento o una sensación de pena. Valorar la creatividad.", lineas: 3 },
      { tipo: "reflexion", q: "El olivar y el flamenco son parte de la identidad de Andalucía. ¿Por qué crees que es importante cuidar los paisajes y conservar la música de nuestra tierra?", r: "Respuesta libre. Valorar que hable de la naturaleza, del trabajo de las personas, de la memoria y de la identidad de un lugar.", lineas: 2 },
    ],
  },
  {
    id: "poesia-08-margarita-debayle",
    titulo: "A Margarita Debayle (fragmento)",
    subtipo: "Poema narrativo",
    curso: "6º",
    fuente: "Rubén Darío, «A Margarita Debayle» (1908), fragmento: primeras siete estrofas; apartado «Para saber más»: texto original que resume el final del poema",
    datos: ["Wikipedia: Rubén Darío"],
    antes: "Rubén Darío, poeta de Nicaragua, escribió este poema para una niña llamada Margarita. ¿Qué cuento le contarías tú a un niño pequeño?",
    texto: [
      { estrofa: ["Margarita, está linda la mar,", "y el viento", "lleva esencia sutil de azahar;", "yo siento", "en el alma una alondra cantar;", "tu acento.", "Margarita, te voy a contar", "un cuento."] },
      { estrofa: ["Este era un rey que tenía", "un palacio de diamantes,", "una tienda hecha del día", "y un rebaño de elefantes,", "un kiosko de malaquita,", "un gran manto de tisú,", "y una gentil princesita,", "tan bonita,", "Margarita,", "tan bonita como tú."] },
      { estrofa: ["Una tarde la princesa", "vio una estrella aparecer;", "la princesa era traviesa", "y la quiso ir a coger."] },
      { estrofa: ["La quería para hacerla", "decorar un prendedor,", "con un verso y una perla,", "y una pluma y una flor."] },
      { estrofa: ["Las princesas primorosas", "se parecen mucho a ti.", "Cortan lirios, cortan rosas,", "cortan astros. Son así."] },
      { estrofa: ["Pues se fue la niña bella,", "bajo el cielo y sobre el mar,", "a cortar la blanca estrella", "que la hacía suspirar."] },
      { estrofa: ["Y siguió camino arriba,", "por la luna y más allá;", "mas lo malo es que ella iba", "sin permiso del papá."] },
      { h: "Para saber más: el final del cuento y su autor" },
      { p: "El poema continúa. Cuando la princesa vuelve, el rey le pregunta dónde ha estado y ella le dice la verdad. Su padre se enfada y la castiga: tendrá que devolver la estrella al cielo. Pero al final todo se arregla, la princesa se queda con la estrella para su prendedor y el rey, feliz, hace desfilar cuatrocientos elefantes a la orilla del mar." },
      { p: "Su autor, Rubén Darío, nació en 1867 en Nicaragua. Con trece años ya publicaba poemas en los periódicos, y en su tierra lo llamaban el «poeta niño». De mayor fue el gran maestro del modernismo, una forma de escribir llena de música, colores y palabras preciosas, como malaquita o tisú. Escribió este poema en 1908 para Margarita Debayle, una niña de su país." },
    ],
    vocabulario: [
      { p: "azahar", d: "flor blanca y muy olorosa del naranjo y del limonero" },
      { p: "alondra", d: "pájaro pequeño de canto muy alegre" },
      { p: "malaquita", d: "piedra de color verde intenso" },
      { p: "tisú", d: "tela de seda con hilos de oro o de plata" },
      { p: "prendedor", d: "broche, adorno que se prende en la ropa" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Enumera cuatro cosas que tenía el rey.", r: "Un palacio de diamantes, una tienda hecha del día, un rebaño de elefantes, un kiosko de malaquita, un manto de tisú y una princesita.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice el poeta que las princesas «se parecen mucho a ti»? ¿Qué quiere decirle a Margarita?", r: "Le hace un cumplido: Margarita es bonita, traviesa y soñadora como las princesas del cuento, capaz de querer hasta las estrellas.", lineas: 2 },
      { tipo: "comprension", q: "Según «Para saber más», ¿qué castigo le pone el rey a la princesa? Elige:", opciones: ["No salir del palacio en un mes", "Volver al cielo a devolver la estrella", "Regalar su prendedor"], r: "Volver al cielo a devolver la estrella" },
      { tipo: "texto", q: "Cuenta las sílabas de «y el viento» y de «Margarita, está linda la mar». ¿Son de arte menor o mayor? Copia las palabras que riman con «mar» y con «viento» en la primera estrofa. ¿Qué tipo de rima es?", r: "«y el vien-to» → yel-vien-to: 3 sílabas, arte menor. «Mar-ga-ri-taes-tá-lin-da-la-mar»: 9 + 1 por acabar en aguda = 10 sílabas, arte mayor. Con «mar»: azahar, cantar, contar; con «viento»: siento, acento, cuento. Rima consonante.", lineas: 3 },
      { tipo: "opinion", q: "La princesa se va lejísimos sin avisar, pero no miente cuando vuelve. ¿Qué te parece lo que hace? ¿Qué harías tú si quisieras algo tan difícil de conseguir?", r: "Respuesta libre. Valorar que argumente sobre pedir permiso, decir la verdad y perseguir los sueños con cabeza.", lineas: 3 },
      { tipo: "reflexion", q: "La princesa quiere «cortar» una estrella, algo imposible. ¿Qué «estrellas» (sueños difíciles) tienes tú? ¿Qué puedes hacer para acercarte a ellos?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "poesia-09-baladilla-tres-rios",
    titulo: "Baladilla de los tres ríos",
    subtipo: "Balada",
    curso: "6º",
    fuente: "Federico García Lorca, «Baladilla de los tres ríos» (Poema del cante jondo, 1931); apartado «Para saber más»: texto original",
    datos: ["Wikipedia: Guadalquivir", "Wikipedia: Río Genil", "Wikipedia: Río Darro"],
    antes: "Lorca era de Granada. ¿Qué río pasa por Sevilla? ¿Sabes qué ríos pasan por Granada?",
    texto: [
      { estrofa: ["El río Guadalquivir", "va entre naranjos y olivos.", "Los dos ríos de Granada", "bajan de la nieve al trigo."] },
      { estrofa: ["¡Ay, amor", "que se fue y no vino!"] },
      { estrofa: ["El río Guadalquivir", "tiene las barbas granates.", "Los dos ríos de Granada,", "uno llanto y otro sangre."] },
      { estrofa: ["¡Ay, amor", "que se fue por el aire!"] },
      { estrofa: ["Para los barcos de vela", "Sevilla tiene un camino;", "por el agua de Granada", "sólo reman los suspiros."] },
      { estrofa: ["¡Ay, amor", "que se fue y no vino!"] },
      { estrofa: ["Guadalquivir, alta torre", "y viento en los naranjales.", "Dauro y Genil, torrecillas", "muertas sobre los estanques."] },
      { estrofa: ["¡Ay, amor", "que se fue por el aire!"] },
      { estrofa: ["¡Quién dirá que el agua lleva", "un fuego fatuo de gritos!"] },
      { estrofa: ["¡Ay, amor", "que se fue y no vino!"] },
      { estrofa: ["Lleva azahar, lleva olivas,", "Andalucía, a tus mares."] },
      { estrofa: ["¡Ay, amor", "que se fue por el aire!"] },
      { h: "Para saber más: los tres ríos de verdad" },
      { p: "El Guadalquivir nace en la sierra de Cazorla, en la provincia de Jaén, y cruza Andalucía de este a oeste a lo largo de 657 kilómetros. Pasa por Córdoba y Sevilla y desemboca en el océano Atlántico, entre Sanlúcar de Barrameda y las marismas de Doñana. Su nombre viene del árabe y significa «el río grande». En su último tramo es tan ancho que los barcos pueden subir desde el mar hasta Sevilla: por eso el poema dice que la ciudad tiene un camino para los barcos de vela." },
      { p: "Los ríos de Granada son mucho más pequeños. El Genil nace en Sierra Nevada, y por eso Lorca dice que bajan «de la nieve al trigo». El Darro, al que el poeta llama Dauro, pasa entre la Alhambra y el barrio del Albaicín y, al llegar al centro de la ciudad, corre escondido bajo las calles hasta juntarse con el Genil." },
      { p: "Pero hay algo que el poema no cuenta. Después de salir de Granada, el Genil pasa por Fuente Vaqueros, el pueblo donde nació Lorca y desemboca en el Guadalquivir en Palma del Río, (Córdoba). Así que el agua que baja de Sierra Nevada también acaba llegando al mar." },
    ],
    vocabulario: [
      { p: "granate", d: "rojo oscuro" },
      { p: "Dauro y Genil", d: "los dos ríos de Granada (el Dauro es el río Darro)" },
      { p: "fuego fatuo", d: "llamita que a veces aparece de noche sobre el suelo" },
      { p: "afluente", d: "río que desemboca en otro más grande" },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué diferencias hay entre el Guadalquivir y los ríos de Granada según el poema?", r: "El Guadalquivir es grande, lleva barcos de vela, pasa entre naranjos y olivos y llega al mar. Los ríos de Granada son pequeños, bajan de la nieve, parecen tristes (llanto, sangre, suspiros) y acaban en estanques.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir que por el agua de Granada «sólo reman los suspiros»?", r: "Que los ríos de Granada no son navegables, no pasan barcos: solo hay tristeza, suspiros.", lineas: 2 },
      { tipo: "comprension", q: "Según «Para saber más», ¿dónde acaba el agua del Genil? Elige:", opciones: ["En los estanques de Granada", "En el Guadalquivir, y con él llega al mar", "En la sierra de Cazorla"], r: "En el Guadalquivir, y con él llega al mar" },
      { tipo: "texto", q: "¿Qué es un estribillo? Copia el de este poema y di cuántas veces aparece. Busca también una personificación y di en qué vocales riman «olivos» y «trigo».", r: "Un estribillo es un verso o grupo de versos que se repite a lo largo del poema. Aquí es «¡Ay, amor / que se fue y no vino!» o «…que se fue por el aire!»: aparece 6 veces, alternando los dos finales. Personificación: «El río Guadalquivir tiene las barbas granates» o «reman los suspiros». Olivos/trigo riman en i-o: rima asonante.", lineas: 3 },
      { tipo: "opinion", q: "Si escribieras una baladilla sobre el río de tu provincia, ¿qué contarías de él? ¿Sería un río alegre o triste? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Los ríos han dado vida a las ciudades andaluzas durante siglos. ¿Por qué crees que es importante cuidar los ríos y no contaminarlos?", r: "Respuesta libre. Valorar que mencione el agua, la fauna, la agricultura y la salud.", lineas: 2 },
    ],
  },
  {
    id: "poesia-10-golondrinas-becquer",
    titulo: "Volverán las oscuras golondrinas",
    subtipo: "Rima",
    curso: "6º",
    fuente: "Gustavo Adolfo Bécquer, Rima LIII (Rimas, 1871), completa; apartado «Para saber más»: texto original",
    datos: ["Wikipedia: Gustavo Adolfo Bécquer"],
    antes: "Bécquer nació en Sevilla y es uno de los poetas más leídos en español. ¿Qué animales o plantas te anuncian que llega la primavera?",
    texto: [
      { estrofa: ["Volverán las oscuras golondrinas", "en tu balcón sus nidos a colgar,", "y otra vez con el ala a sus cristales", "jugando llamarán;"] },
      { estrofa: ["pero aquellas que el vuelo refrenaban", "tu hermosura y mi dicha al contemplar,", "aquellas que aprendieron nuestros nombres,", "ésas... ¡no volverán!"] },
      { estrofa: ["Volverán las tupidas madreselvas", "de tu jardín las tapias a escalar,", "y otra vez a la tarde, aún más hermosas,", "sus flores se abrirán;"] },
      { estrofa: ["pero aquellas cuajadas de rocío,", "cuyas gotas mirábamos temblar", "y caer, como lágrimas del día...", "ésas... ¡no volverán!"] },
      { estrofa: ["Volverán del amor en tus oídos", "las palabras ardientes a sonar;", "tu corazón de su profundo sueño", "tal vez despertará;"] },
      { estrofa: ["pero mudo y absorto y de rodillas,", "como se adora a Dios ante su altar,", "como yo te he querido... desengáñate,", "¡así no te querrán!"] },
      { h: "Para saber más: Bécquer y el Libro de los gorriones" },
      { p: "Gustavo Adolfo Bécquer nació en Sevilla en 1836. De joven se marchó a Madrid con el sueño de ser escritor, y allí trabajó como periodista y escribió poemas y leyendas. Su hermano Valeriano era pintor, y gracias a él conocemos bien la cara del poeta: en 1862 le pintó un retrato que hoy es famosísimo." },
      { p: "En vida, Bécquer solo publicó una quincena de sus poemas en periódicos y revistas. Muchos los escribió a mano en un cuaderno que hoy conocemos como Libro de los gorriones, el manuscrito más importante que se conserva del poeta. Bécquer murió muy joven, con treinta y cuatro años, y fueron sus amigos quienes reunieron sus rimas y las publicaron en 1871, ordenadas con números romanos. Por eso este poema se llama Rima LIII, es decir, la rima cincuenta y tres." },
      { p: "En el parque de María Luisa de Sevilla hay una glorieta dedicada a Bécquer, con un monumento que se inauguró en 1911. Más de ciento cincuenta años después de su muerte, sus versos se siguen leyendo, recitando y hasta cantando." },
      { p: "La Rima LIII está construida como un juego de espejos: cada estrofa que empieza con «Volverán» anuncia algo que se repetirá, y la siguiente, que empieza con «pero», explica lo que ya nunca volverá." },
    ],
    vocabulario: [
      { p: "refrenar", d: "frenar, detener" },
      { p: "dicha", d: "felicidad" },
      { p: "tupido", d: "espeso, con las hojas muy juntas" },
      { p: "madreselva", d: "planta trepadora de flores muy olorosas" },
      { p: "absorto", d: "tan concentrado en algo que no se da cuenta de nada más" },
    ],
    preguntas: [
      { tipo: "comprension", q: "Según el poeta, ¿qué volverá con el paso del tiempo?", r: "Volverán las golondrinas a colgar sus nidos en el balcón, las madreselvas a trepar por las tapias y a abrir sus flores, y las palabras de amor a sonar en los oídos de la amada.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el poeta con «ésas... ¡no volverán!»?", r: "Que, aunque la primavera vuelva cada año, los momentos felices que vivió con la persona amada no se repetirán: el pasado no vuelve. Siente tristeza y nostalgia.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué dice el poeta en las dos últimas estrofas? Elige:", opciones: ["Que nadie volverá a hablarle de amor a la persona amada", "Que quizá otros le hablen de amor, pero nadie la querrá como él la ha querido", "Que él volverá a buscarla en primavera"], r: "Que quizá otros le hablen de amor, pero nadie la querrá como él la ha querido" },
      { tipo: "texto", q: "¿Cuántas estrofas y versos tiene la rima? Cuenta las sílabas de «Volverán las oscuras golondrinas» y de «jugando llamarán». ¿Qué versos riman y en qué vocal? Copia una comparación.", r: "6 estrofas y 24 versos. «Vol-ve-rán-las-os-cu-ras-go-lon-dri-nas»: 11 sílabas (arte mayor); «ju-gan-do-lla-ma-rán»: 6 + 1 por ser aguda = 7 (arte menor). Riman los versos pares en «á» (colgar, llamarán, contemplar, volverán, escalar, abrirán, temblar, sonar, despertará, altar, querrán): rima asonante. Comparación: «como lágrimas del día» o «como se adora a Dios ante su altar».", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que este poema se sigue leyendo y recitando más de ciento cincuenta años después?", r: "Respuesta libre. Valorar que hable de sentimientos universales, de la música de los versos, de las imágenes…", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué momento feliz te gustaría guardar para siempre? ¿Qué podemos hacer para no olvidar los buenos recuerdos?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
];
