// Lecturas · Textos predictivos (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["predictivo"] = [
  {
    id: "predictivo-01-tiempo-andalucia",
    titulo: "El tiempo en Andalucía este fin de semana",
    subtipo: "Previsión meteorológica",
    curso: "5º",
    fuente: "Texto original. Previsión inventada para esta ficha (los datos no son reales).",
    antes: "¿Miras el tiempo antes de salir de casa o de una excursión? ¿Dónde lo consultas?",
    texto: [
      { p: "Buenas tardes. Llega el primer fin de semana de octubre y, con él, un cambio de tiempo en Andalucía. Os contamos qué podemos esperar." },
      { h: "Sábado: sol y calor suave" },
      { p: "El sábado todavía mandará el buen tiempo. Tendremos cielos despejados en casi toda la comunidad y las temperaturas serán agradables, algo más altas en el valle del Guadalquivir. En la costa soplará un poniente flojo, así que el mar estará tranquilo en Cádiz y en Huelva. En las zonas altas de Sierra Nevada, en cambio, la noche será fresca y conviene llevar chaqueta." },
      { tabla: { titulo: "Previsión para el sábado (temperaturas en grados)", cab: ["Ciudad", "Máxima", "Mínima", "Cielo"], filas: [
        ["Almería", "26", "19", "Despejado"],
        ["Cádiz", "25", "19", "Despejado"],
        ["Córdoba", "30", "16", "Despejado"],
        ["Granada", "25", "12", "Poco nuboso"],
        ["Huelva", "27", "17", "Despejado"],
        ["Jaén", "26", "15", "Poco nuboso"],
        ["Málaga", "27", "18", "Despejado"],
        ["Sevilla", "29", "17", "Despejado"],
      ] }, nota: "Datos inventados para esta actividad." },
      { h: "Domingo: llega la lluvia por el oeste" },
      { p: "El domingo, en cambio, las cosas cambiarán. Una borrasca que se acerca desde el Atlántico entrará por Huelva a primera hora y avanzará hacia el este durante el día. Por eso, las nubes irán cubriendo el cielo y probablemente lloverá en el oeste de Andalucía a partir del mediodía. En Sevilla y Córdoba la probabilidad de lluvia será alta, de un 70 %. En Almería y Granada, sin embargo, es posible que no caiga ni una gota, porque las nubes llegarán muy debilitadas. Además, las temperaturas bajarán entre tres y cinco grados." },
      { h: "Nuestro consejo" },
      { p: "En resumen: si tenéis un plan al aire libre, mejor el sábado. Si salís el domingo, no olvidéis el paraguas. Y recordad que una previsión no es una certeza: la actualizaremos mañana con los últimos datos de los satélites." },
    ],
    vocabulario: [
      { p: "borrasca", d: "zona de bajas presiones que suele traer nubes, viento y lluvia." },
      { p: "poniente", d: "viento que sopla desde el oeste." },
      { p: "probabilidad", d: "posibilidad de que algo ocurra, que se puede expresar en tanto por ciento." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Según la tabla, ¿qué ciudad tendrá la temperatura más alta el sábado? ¿Y la más baja por la noche?", r: "Córdoba, con 30 grados. La mínima más baja será en Granada, con 12.", lineas: 1 },
      { tipo: "comprension", q: "¿Por dónde entrará la borrasca el domingo y hacia dónde avanzará?", r: "Entrará por Huelva, desde el Atlántico, y avanzará hacia el este.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que es posible que no llueva en Almería?", r: "Porque está en el este, lejos de donde entra la borrasca, y las nubes llegarán muy debilitadas.", lineas: 2 },
      { tipo: "comprension", q: "Una probabilidad de lluvia del 70 % significa que… Elige:", opciones: ["lloverá seguro", "es bastante probable que llueva", "lloverá el 70 % del día"], r: "es bastante probable que llueva" },
      { tipo: "comprension", q: "¿Por qué dice el presentador que la previsión se actualizará mañana?", r: "Porque una previsión no es una certeza; con datos más recientes de los satélites será más precisa.", lineas: 2 },
      { tipo: "texto", q: "Copia tres verbos en futuro del texto y el conector que se usa para la conclusión. ¿Qué palabra indica que algo no es seguro?", r: "Futuro: mandará, tendremos, serán, soplará, estará, cambiarán, entrará, lloverá, bajarán… Conclusión: En resumen. Duda: probablemente (también «es posible»).", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que las previsiones del tiempo son fiables? Cuenta alguna vez que acertaran o fallaran.", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué trabajos o actividades dependen mucho de la previsión del tiempo? ¿Por qué?", r: "Respuesta libre (agricultura, pesca, aviones, excursiones…).", lineas: 3 },
      { tipo: "reflexion", q: "Esta previsión es inventada. ¿Qué pasaría si alguien la difundiera como si fuera real? ¿Por qué es importante indicar la fuente?", r: "Respuesta libre. Valorar que hable de la desinformación y de la fiabilidad de las fuentes.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-02-horoscopo-patio",
    titulo: "El horóscopo del patio",
    subtipo: "Horóscopo humorístico",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has leído alguna vez un horóscopo? ¿Crees que las estrellas pueden saber lo que te va a pasar?",
    texto: [
      { p: "La revista de nuestro colegio estrena sección. Madame Tiza, nuestra adivina oficial, ha mirado las estrellas (y también el calendario de exámenes) y nos cuenta qué nos espera esta semana." },
      { h: "Aries" },
      { p: "El lunes encontrarás algo que creías perdido, probablemente en el fondo de tu mochila, debajo de un bocadillo de hace tres semanas. Te aconsejo abrirla con cuidado." },
      { h: "Tauro" },
      { p: "Un número misterioso aparecerá en tu vida. Será el 7, o tal vez el 12. Si tienes examen de Matemáticas, podría ser cualquiera." },
      { h: "Géminis" },
      { p: "Tu mejor amigo te dirá algo muy importante el miércoles. Seguramente será: «¿Me dejas la goma?»." },
      { h: "Leo" },
      { p: "Brillarás como el sol. Sobre todo si te olvidas la gorra en la excursión." },
      { h: "Escorpio" },
      { p: "Los astros anuncian un gran cambio: el viernes habrá lentejas en el comedor. Prepárate." },
      { h: "Nota de la redacción" },
      { p: "Madame Tiza no es adivina: es Marta, de sexto, que tiene mucho sentido del humor. Pero fijaos en cómo funciona su horóscopo, porque los de verdad se parecen bastante. En primer lugar, usa frases tan generales que le pueden pasar a cualquiera: todo el mundo pierde cosas y todos los amigos piden la goma. En segundo lugar, añade palabras como «probablemente» o «tal vez», así nunca falla del todo. Por último, no da ninguna razón: no explica por qué las estrellas iban a saber qué hay de comer el viernes. En realidad, lo sabe porque ha mirado el menú." },
      { p: "En definitiva, un horóscopo puede ser divertido, pero no es una predicción fiable, porque no se apoya en datos ni en pruebas. Para saber si lloverá, consultad la previsión del tiempo; para saber qué hay de comer, el menú del comedor." },
    ],
    vocabulario: [
      { p: "astros", d: "cuerpos del cielo, como las estrellas, los planetas o la Luna." },
      { p: "redacción", d: "equipo que escribe una revista o un periódico." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién es en realidad Madame Tiza?", r: "Marta, una alumna de sexto con mucho sentido del humor.", lineas: 1 },
      { tipo: "comprension", q: "¿Cómo sabe Madame Tiza que el viernes habrá lentejas?", r: "Porque ha mirado el menú del comedor, no las estrellas.", lineas: 1 },
      { tipo: "comprension", q: "Explica la broma de Leo. ¿Por qué brillarás si olvidas la gorra?", r: "Porque te pondrás rojo por el sol; juega con el doble sentido de «brillar».", lineas: 2 },
      { tipo: "comprension", q: "¿Qué tres trucos usa el horóscopo para parecer que acierta, según la nota de la redacción?", r: "Frases generales que le pasan a cualquiera, palabras como «probablemente» o «tal vez» para no fallar, y no dar razones.", lineas: 3 },
      { tipo: "comprension", q: "La nota de la redacción piensa que el horóscopo… Elige:", opciones: ["es una predicción científica", "es divertido pero no es fiable", "acierta siempre"], r: "es divertido pero no es fiable" },
      { tipo: "texto", q: "Un texto predictivo fiable se apoya en razones o datos. ¿Por qué el horóscopo no lo es? Copia además dos conectores de la nota de la redacción.", r: "Porque no da razones ni datos; solo afirma. Conectores: en primer lugar, en segundo lugar, por último, en definitiva.", lineas: 2 },
      { tipo: "opinion", q: "¿Por qué crees que a mucha gente le gusta leer el horóscopo aunque no sea fiable?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "Escribe una predicción divertida para tu clase, pero que esté basada en un dato real (el horario, el menú, el calendario…).", r: "Respuesta libre. Valorar que incluya un dato y un verbo en futuro.", lineas: 3 },
      { tipo: "reflexion", q: "¿Tomarías una decisión importante por lo que dice un horóscopo? ¿Qué harías en su lugar?", r: "Respuesta libre. Valorar el pensamiento crítico.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-03-cole-2050",
    titulo: "Mi cole en 2050",
    subtipo: "Redacción predictiva",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Cómo crees que será tu colegio cuando tus hijos o tus sobrinos vayan a él?",
    texto: [
      { p: "Me llamo Iker, estoy en quinto y mi abuela Carmen fue a este mismo colegio hace cincuenta años. Cuando me cuenta cómo era, me parece otro planeta: escribían con pluma y tinta, y en invierno se calentaban con una estufa en el centro de la clase. Por eso pienso que, en 2050, mi colegio también habrá cambiado muchísimo." },
      { p: "Para empezar, creo que los horarios serán diferentes. Ya ahora en algunos colegios se hacen proyectos que duran semanas en lugar de clases sueltas. Seguramente, en el futuro, las asignaturas se mezclarán más: estudiaremos Matemáticas midiendo el huerto y Lengua escribiendo el periódico del barrio." },
      { p: "En segundo lugar, los edificios cuidarán más el planeta. Cada vez hay más placas solares en los tejados y en mi pueblo ya han plantado árboles en el patio para que dé sombra. Por eso imagino que en 2050 los colegios producirán su propia energía y tendrán patios con más tierra y menos cemento." },
      { p: "Además, habrá más tecnología, pero no creo que los robots sustituyan a los maestros. Mi abuela dice que ella recuerda a su maestra, no la pizarra. Yo pienso lo mismo: una máquina podrá corregir cuentas, pero no sabrá cuándo estás triste." },
      { p: "Por último, me gustaría que llegar al cole fuera más fácil. Si hubiera carriles bici seguros en todas las calles, casi nadie vendría en coche. No sé si pasará, pero ya hay ciudades que lo están haciendo." },
      { p: "En conclusión, creo que el cole de 2050 será más verde, más práctico y con más tecnología, aunque lo más importante seguirá siendo lo mismo: las personas. Dentro de muchos años leeré esta redacción y comprobaré cuánto he acertado." },
    ],
    vocabulario: [
      { p: "sustituir", d: "poner a una persona o cosa en el lugar de otra." },
      { p: "placa solar", d: "panel que transforma la luz del sol en energía." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué piensa Iker que el colegio cambiará mucho de aquí a 2050?", r: "Porque su abuela le ha contado cuánto ha cambiado en los últimos cincuenta años.", lineas: 2 },
      { tipo: "comprension", q: "¿En qué pistas del presente se apoya Iker para decir que los colegios cuidarán más el planeta?", r: "En que cada vez hay más placas solares y en que en su pueblo han plantado árboles en el patio.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Iker con la frase «una máquina podrá corregir cuentas, pero no sabrá cuándo estás triste»?", r: "Que los maestros no se pueden sustituir porque, además de enseñar, entienden y cuidan a los alumnos.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuál de sus predicciones es más bien un deseo? Elige:", opciones: ["Que habrá más placas solares", "Que llegar al cole será más fácil en bici", "Que habrá más tecnología"], r: "Que llegar al cole será más fácil en bici" },
      { tipo: "comprension", q: "¿Cómo podrá saber Iker si sus predicciones eran acertadas?", r: "Leyendo la redacción dentro de muchos años y comparándola con la realidad.", lineas: 1 },
      { tipo: "texto", q: "Señala qué párrafo es la introducción, cuáles el desarrollo y cuál la conclusión. Copia el conector que abre la conclusión.", r: "Introducción: párrafo 1. Desarrollo: párrafos 2 a 5. Conclusión: párrafo 6, que empieza por «En conclusión».", lineas: 2 },
      { tipo: "opinion", q: "¿Estás de acuerdo con Iker en que los robots no sustituirán a los maestros? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
      { tipo: "opinion", q: "Escribe una predicción tuya sobre el cole del futuro y la razón en la que se apoya.", r: "Respuesta libre. Valorar que use el futuro y dé una razón.", lineas: 3 },
      { tipo: "reflexion", q: "Pregunta a una persona mayor cómo era su colegio. ¿Qué cambio te parece mejor y qué cosa crees que se ha perdido?", r: "Respuesta libre.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-04-previa-baloncesto",
    titulo: "Final alevín: ¿quién ganará?",
    subtipo: "Previa deportiva",
    curso: "5º",
    fuente: "Texto original. Noticia inventada para esta ficha.",
    antes: "¿Te gusta adivinar quién ganará un partido? ¿En qué te fijas para decidirlo?",
    texto: [
      { titular: "Poniente y Alcazaba se juegan el título alevín", subtitulo: "La final del torneo provincial de baloncesto se disputará el sábado en Almería", entradilla: "Almería. El Club Baloncesto Poniente y el Club Alcazaba se enfrentarán este sábado, a las once de la mañana, en la final alevín del torneo provincial. Analizamos quién tiene más papeletas para llevarse la copa." },
      { p: "Si miramos la clasificación, el Alcazaba parte como favorito. En primer lugar, ha ganado nueve de sus diez partidos de la temporada y es el equipo que más puntos anota por encuentro. En segundo lugar, jugará en su propio pabellón, con su afición, y eso siempre ayuda. Además, en la liga ya venció al Poniente por diez puntos de diferencia." },
      { p: "Sin embargo, el Poniente llega en su mejor momento. Ha ganado sus últimos cinco partidos y su defensa es la que menos puntos recibe de todo el torneo. Por otro lado, su base, Nadia Cortés, se recuperó de un esguince hace dos semanas y ya está en plena forma. Cuando jugaron en la liga, Nadia estaba lesionada, así que aquel resultado podría no repetirse." },
      { p: "Los entrenadores prefieren no mojarse. «Será un partido muy igualado», asegura Rocío Maldonado, del Alcazaba. «Si defendemos como en las últimas semanas, tendremos opciones», explica Samuel Ortega, del Poniente." },
      { p: "En conclusión, los números dicen que el Alcazaba ganará, pero la buena racha del Poniente y la vuelta de su base podrían dar la sorpresa. Lo que es seguro es que habrá emoción hasta el último segundo. Y no lo olvidemos: en el deporte, a veces el que parece más débil gana. Por eso se juegan los partidos." },
    ],
    vocabulario: [
      { p: "favorito", d: "quien tiene más posibilidades de ganar." },
      { p: "tener papeletas", d: "tener muchas posibilidades de conseguir algo." },
      { p: "mojarse", d: "(expresión) dar una opinión clara y comprometida." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tres razones apoyan que ganará el Alcazaba?", r: "Ha ganado nueve de diez partidos y es el que más anota, juega en casa con su afición y ya venció al Poniente en la liga.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el periodista dice que el resultado de la liga podría no repetirse?", r: "Porque entonces Nadia Cortés, la base del Poniente, estaba lesionada, y ahora ya está recuperada.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que los entrenadores «prefieren no mojarse»?", r: "Porque no quieren confiarse ni presionar a sus jugadores; saben que el resultado es incierto.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué información da la entradilla? Elige:", opciones: ["Quién ganará la final", "Quién juega, qué, cuándo y dónde", "Las opiniones de los entrenadores"], r: "Quién juega, qué, cuándo y dónde" },
      { tipo: "comprension", q: "¿Qué quiere decir la última frase: «Por eso se juegan los partidos»?", r: "Que una predicción nunca es segura y solo el partido decide quién gana.", lineas: 2 },
      { tipo: "texto", q: "Copia un conector que añada una razón, otro que presente una idea contraria y el de la conclusión. Escribe también una frase del texto en condicional.", r: "Añadir: en primer lugar, en segundo lugar, además, por otro lado. Contraria: sin embargo. Conclusión: en conclusión. Condicional: «aquel resultado podría no repetirse» o «podrían dar la sorpresa».", lineas: 3 },
      { tipo: "opinion", q: "¿Quién crees que ganará la final? Justifica tu predicción con dos datos del texto.", r: "Respuesta libre. Valorar que use datos del texto.", lineas: 3 },
      { tipo: "opinion", q: "¿Es justo que jugar en casa sea una ventaja? ¿Por qué crees que lo es?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Si tu equipo es el menos favorito, ¿te ayuda o te perjudica leer predicciones como esta? ¿Por qué?", r: "Respuesta libre. Valorar la reflexión sobre la motivación.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-05-buho-hormiga",
    titulo: "El búho profeta y la hormiga que miraba el cielo",
    subtipo: "Cuento",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Conoces algún truco de la naturaleza para saber si va a llover? ¿Te lo ha contado alguien?",
    texto: [
      { p: "En el bosque de los Alcornoques vivía un búho llamado Hilario que se hacía llamar el Gran Profeta. Todas las tardes subía a la rama más alta, se colocaba unas gafas que se había encontrado en una excursión humana y anunciaba el futuro con voz solemne." },
      { p: "—¡Escuchad, criaturas! —ululaba—. Mañana sucederá algo que nadie espera. Alguien encontrará lo que busca. Y el viento soplará… o no soplará." },
      { p: "Los animales aplaudían, maravillados. Al día siguiente, alguien siempre encontraba algo y el viento siempre soplaba o no soplaba, así que Hilario acertaba siempre." },
      { p: "Cerca del tronco vivía una hormiga llamada Adela que no hacía profecías: hacía observaciones. Una tarde de otoño notó tres cosas. El aire olía a tierra mojada, las golondrinas volaban muy bajo persiguiendo mosquitos y, a lo lejos, sobre la sierra, se amontonaban nubes grises." },
      { p: "—Esta noche lloverá fuerte —anunció—. Deberíamos mover las provisiones del hormiguero bajo, que es el que se inunda." },
      { p: "Los animales miraron a Hilario, que se ajustó las gafas." },
      { p: "—El Gran Profeta ha consultado a la Luna —declaró—. Y la Luna dice que mañana será un día… importante." },
      { p: "Todos se fueron a dormir tranquilos. Todos menos Adela y sus hermanas, que pasaron la tarde trasladando semillas al hormiguero de la loma." },
      { p: "Esa noche cayó una tormenta tremenda. El hormiguero bajo se llenó de barro y la madriguera de los conejos también. Por la mañana, empapados, los animales fueron a pedir explicaciones al búho." },
      { p: "—Os dije que sería un día importante —se defendió Hilario—. ¡Y lo ha sido!" },
      { p: "Entonces el conejo más joven se volvió hacia la hormiga." },
      { p: "—¿Cómo lo sabías tú?" },
      { p: "—No lo sabía —respondió Adela—. Lo deduje. El olor, las golondrinas y las nubes eran pistas. Podía haberme equivocado, pero tenía razones. Hilario habla mucho, pero nunca dice nada que se pueda comprobar." },
      { p: "Desde aquel día, cuando Hilario anuncia el futuro, los animales le hacen siempre la misma pregunta: «¿Y en qué te basas?». Desde entonces, el búho hace muchas menos profecías." },
    ],
    vocabulario: [
      { p: "profeta", d: "persona que dice anunciar el futuro." },
      { p: "solemne", d: "serio y muy importante, con mucha ceremonia." },
      { p: "deducir", d: "llegar a una conclusión a partir de pistas o datos." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué Hilario acertaba siempre?", r: "Porque sus profecías eran tan generales o tan ambiguas (el viento soplará o no) que era imposible que fallaran.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué tres pistas observó Adela para predecir la lluvia?", r: "El olor a tierra mojada, las golondrinas volando bajo y las nubes grises sobre la sierra.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que los animales hicieron caso a Hilario y no a Adela?", r: "Porque Hilario parecía importante (gafas, voz solemne, título de Gran Profeta) y le tenían confianza, aunque no diera razones.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Adela con «No lo sabía. Lo deduje»? Elige:", opciones: ["Que tuvo suerte", "Que llegó a la conclusión a partir de pistas", "Que se lo dijo la Luna"], r: "Que llegó a la conclusión a partir de pistas" },
      { tipo: "comprension", q: "¿Por qué el búho hace ahora menos profecías?", r: "Porque le preguntan en qué se basa y no tiene razones que dar.", lineas: 2 },
      { tipo: "texto", q: "Compara las dos predicciones: ¿cuál es un verdadero texto predictivo y por qué? Copia el verbo en futuro que usa cada personaje.", r: "La de Adela, porque se apoya en razones y pistas del presente. Adela: lloverá. Hilario: sucederá, encontrará, soplará, será.", lineas: 3 },
      { tipo: "opinion", q: "¿Conoces a alguien (en la vida real, en la tele o en internet) que hable como Hilario? ¿Cómo lo reconocerías?", r: "Respuesta libre. Valorar que identifique mensajes vagos o sin pruebas.", lineas: 3 },
      { tipo: "opinion", q: "Adela reconoce que podía haberse equivocado. ¿Crees que eso hace su predicción más o menos fiable? ¿Por qué?", r: "Respuesta libre. Valorar que entienda que reconocer la duda es propio de una predicción seria.", lineas: 3 },
      { tipo: "reflexion", q: "La pregunta «¿Y en qué te basas?» sirve para muchas situaciones. ¿Cuándo podrías usarla tú?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-06-cosecha-aceituna",
    titulo: "¿Cómo será la cosecha de aceituna?",
    subtipo: "Folleto informativo",
    curso: "5º-6º",
    fuente: "Texto original. Folleto de una cooperativa inventada; las cifras son ficticias.",
    antes: "¿Sabes cómo se hace el aceite de oliva? ¿Por qué crees que unos años hay más aceitunas que otros?",
    texto: [
      { h: "Cooperativa El Olivo Viejo · Boletín para las familias socias" },
      { p: "Queridas familias: como cada otoño, el equipo técnico de la cooperativa ha recorrido los olivares de la comarca, en la provincia de Jaén, para estimar cuántas aceitunas recogeremos en la próxima campaña, que empezará a mediados de noviembre. Os contamos nuestra previsión y en qué nos basamos." },
      { h: "Nuestra previsión" },
      { p: "Calculamos que este año la cosecha será buena, algo mejor que la del año pasado. En nuestros cálculos, los socios entregarán unos doce millones de kilos de aceituna, con los que podremos obtener cerca de dos millones y medio de litros de aceite." },
      { h: "¿En qué nos basamos?" },
      { p: "Para empezar, la primavera fue lluviosa. Los olivos necesitan agua cuando florecen, y este año la tuvieron. Para continuar, la floración de mayo fue abundante: en las ramas que revisamos contamos muchas flores y, después, muchos frutos pequeños. Por otro lado, el verano no ha sido tan caluroso como otros años, así que se han caído menos aceitunas antes de tiempo." },
      { tabla: { titulo: "Cosechas de la cooperativa (datos ficticios)", cab: ["Campaña", "Aceituna (millones de kg)", "Lluvia en primavera"], filas: [
        ["Hace 3 años", "9", "Escasa"],
        ["Hace 2 años", "7", "Muy escasa"],
        ["El año pasado", "11", "Normal"],
        ["Este año (previsión)", "12", "Abundante"],
      ] } },
      { h: "Lo que todavía puede cambiar" },
      { p: "Una previsión no es una promesa. Si en octubre lloviera muy poco, las aceitunas serían más pequeñas y darían menos aceite. Si hubiera una granizada, podría dañar los frutos. Por eso revisaremos estos cálculos a finales de octubre." },
      { p: "En definitiva, todo indica que tendremos una buena campaña. Os pedimos que tengáis las mantas y los vareadores a punto, y os recordamos que la almazara abrirá de siete de la mañana a nueve de la noche." },
    ],
    vocabulario: [
      { p: "cooperativa", d: "empresa formada por un grupo de personas que trabajan juntas y se reparten los beneficios." },
      { p: "almazara", d: "lugar donde se muele la aceituna para sacar el aceite." },
      { p: "floración", d: "momento en que las plantas se llenan de flores." },
      { p: "vareador", d: "herramienta o máquina que se usa para hacer caer las aceitunas del árbol." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué predice la cooperativa y cuándo empezará la campaña?", r: "Que la cosecha será buena, algo mejor que la del año pasado (unos doce millones de kilos). Empezará a mediados de noviembre.", lineas: 2 },
      { tipo: "comprension", q: "Observa la tabla. ¿Qué relación hay entre la lluvia de primavera y la cosecha?", r: "Cuanta más lluvia en primavera, más aceituna se recoge.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que el verano caluroso hace que se caigan aceitunas antes de tiempo?", r: "Porque con mucho calor y poca agua el árbol no puede alimentar todos los frutos y se desprende de algunos.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué podría hacer que la previsión fallara? Elige:", opciones: ["Una primavera lluviosa", "Un octubre muy seco o una granizada", "Que la almazara abra temprano"], r: "Un octubre muy seco o una granizada" },
      { tipo: "comprension", q: "¿Por qué la cooperativa volverá a revisar sus cálculos a finales de octubre?", r: "Porque el tiempo de otoño todavía puede cambiar el resultado y con nuevos datos la previsión será más precisa.", lineas: 2 },
      { tipo: "texto", q: "Copia dos conectores que ordenan las razones y una oración en condicional. ¿Por qué el folleto usa el condicional en la parte «Lo que todavía puede cambiar»?", r: "Para empezar, para continuar, por otro lado. Condicional: «las aceitunas serían más pequeñas y darían menos aceite» o «podría dañar los frutos». Porque son posibilidades, no hechos seguros.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece fiable esta previsión? Explica en qué te fijas para decidirlo.", r: "Respuesta libre. Valorar que mencione que se basa en observaciones y datos de otros años.", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que es importante para las familias conocer la previsión de la cosecha?", r: "Respuesta libre (organizar el trabajo, los gastos, contratar ayuda…).", lineas: 2 },
      { tipo: "reflexion", q: "El olivar depende mucho de la lluvia. ¿Cómo crees que afectaría a Jaén una serie de años muy secos?", r: "Respuesta libre. Valorar que relacione clima, trabajo y economía.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-07-aves-donana",
    titulo: "Doñana espera a sus visitantes de invierno",
    subtipo: "Folleto divulgativo",
    curso: "5º-6º",
    fuente: "Texto original. Folleto inventado para esta ficha, con datos reales del censo de 2026.",
    datos: ["CSIC · Estación Biológica de Doñana: censo de aves acuáticas invernantes de enero de 2026"],
    antes: "¿Por qué crees que muchas aves viajan miles de kilómetros cada año? ¿Has visto alguna vez una bandada migrando?",
    texto: [
      { p: "Cada otoño, cuando en el norte de Europa empiezan las heladas y las primeras nevadas, miles de aves emprenden un largo viaje hacia el sur. Muchas de ellas terminan su ruta en Doñana, entre Huelva, Sevilla y Cádiz, uno de los humedales más importantes de Europa. Allí pasarán el invierno, más o menos de octubre a febrero. ¿Cuántas vendrán este año? Os contamos lo que se espera." },
      { h: "Lo que sabemos" },
      { p: "Más de trescientas especies de aves usan Doñana para criar, pasar el invierno o descansar en su viaje. Entre las invernantes destaca el ánsar común, una especie de ganso. Cada enero, los científicos de la Estación Biológica de Doñana hacen un censo: cuentan las aves desde una avioneta, desde vehículos y en los lugares donde duermen. En enero de 2026 contaron más de 385.000 aves acuáticas de 88 especies. Fue una buena noticia, porque en los dos años anteriores la sequía había dejado la marisma casi seca y se habían registrado mínimos históricos." },
      { h: "Nuestra previsión" },
      { p: "La clave es el agua. Cuando la marisma se inunda, las aves encuentran comida y refugio; cuando está seca, siguen su viaje o se quedan en otros lugares. Por eso, si este otoño llueve lo normal o más, es muy probable que el número de aves se parezca al del último invierno o incluso lo supere. En cambio, si el otoño es seco, llegarán menos aves y se concentrarán en las pocas lagunas con agua." },
      { p: "Aun así, hay que ser prudentes. Durante los últimos veinte años, la media ha estado por encima de las 430.000 aves, y en 2026 todavía no se alcanzó. Una marisma necesita varios años buenos seguidos para recuperarse del todo." },
      { h: "Consejos para la visita" },
      { p: "Trae prismáticos y ropa de colores discretos, camina en silencio y no te salgas de los senderos. Recuerda: somos invitados en su casa de invierno." },
    ],
    vocabulario: [
      { p: "humedal", d: "terreno cubierto de agua poco profunda, como marismas y lagunas." },
      { p: "censo", d: "recuento ordenado de personas, animales o cosas." },
      { p: "marisma", d: "terreno bajo y llano que se inunda cerca de la desembocadura de un río." },
      { p: "prudente", d: "que piensa antes de actuar o de hablar para no equivocarse." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué viajan las aves del norte de Europa hacia Doñana en otoño?", r: "Porque en el norte empiezan las heladas y las nevadas, y en Doñana encuentran agua, comida y refugio para pasar el invierno.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo cuentan las aves los científicos?", r: "Desde una avioneta, desde vehículos y en los lugares donde duermen.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué el censo de 2026 fue una buena noticia?", r: "Porque se contaron más aves que en los dos años anteriores, en los que la sequía dejó mínimos históricos.", lineas: 2 },
      { tipo: "comprension", q: "¿De qué depende, sobre todo, la previsión para este invierno? Elige:", opciones: ["De la lluvia de otoño", "Del número de visitantes", "De la temperatura del mar"], r: "De la lluvia de otoño" },
      { tipo: "comprension", q: "¿Por qué dice el folleto que «hay que ser prudentes» aunque las cifras hayan mejorado?", r: "Porque todavía no se ha alcanzado la media de los últimos veinte años y la marisma necesita varios años buenos para recuperarse.", lineas: 2 },
      { tipo: "texto", q: "Este folleto separa «Lo que sabemos» de «Nuestra previsión». ¿Por qué es importante separar los datos de las predicciones? Copia una oración que exprese una condición (si…).", r: "Para que el lector sepa qué es seguro y qué es una estimación. Ejemplo: «si este otoño llueve lo normal o más, es muy probable que…» o «si el otoño es seco, llegarán menos aves».", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece fiable esta predicción? Explica qué fuentes usa y por qué crees que son de confianza o no.", r: "Respuesta libre. Valorar que mencione el censo científico de la Estación Biológica de Doñana.", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que el folleto pide ropa de colores discretos y caminar en silencio?", r: "Respuesta libre. Valorar que relacione con no asustar a las aves.", lineas: 2 },
      { tipo: "reflexion", q: "Doñana depende del agua y del cuidado de las personas. ¿Qué podemos hacer, desde casa o desde el colegio, para proteger humedales como este?", r: "Respuesta libre. Valorar propuestas de ahorro de agua, respeto, difusión…", lineas: 3 },
    ],
  },
  {
    id: "predictivo-08-poblacion-mundial",
    titulo: "¿Cuántos seremos en el año 2100?",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["Naciones Unidas: World Population Prospects 2024 (Perspectivas de la Población Mundial), resumen de resultados"],
    antes: "¿Cuántas personas crees que viven hoy en el planeta? ¿Crees que seremos más o menos dentro de cien años?",
    texto: [
      { p: "Hace unos doscientos años, en toda la Tierra vivían alrededor de mil millones de personas. En 2024 ya éramos unos 8.200 millones. Con un crecimiento así, es fácil imaginar un futuro con un planeta abarrotado, pero ¿qué dicen los expertos? Cada pocos años, la Organización de las Naciones Unidas (ONU) publica un informe llamado Perspectivas de la Población Mundial, en el que científicos de todo el mundo estudian cómo cambiará el número de habitantes." },
      { h: "La predicción" },
      { p: "Según el informe publicado en 2024, la población mundial seguirá creciendo durante unos sesenta años más, pero cada vez más despacio. Hacia mediados de la década de 2080 alcanzará su punto más alto, con unos 10.300 millones de personas. Después, empezará a bajar poco a poco, y en el año 2100 seremos unos 10.200 millones." },
      { h: "Las razones" },
      { p: "En primer lugar, las familias tienen menos hijos que antes. En 1990, cada mujer tenía de media 3,3 hijos; hoy la media mundial es de 2,3. Para que una población no disminuya, hacen falta unos 2,1 hijos por mujer, y más de la mitad de los países del mundo ya están por debajo de esa cifra. En segundo lugar, al mismo tiempo, la gente vive más años gracias a los avances en medicina y alimentación, lo que hace que la población siga aumentando durante un tiempo. Por último, estas tendencias no son iguales en todo el planeta: en algunos países la población crecerá mucho, mientras que en otros, como España, habrá cada vez más personas mayores y menos jóvenes." },
      { h: "¿Podría equivocarse?" },
      { p: "Sí. Los propios expertos explican que una predicción a tan largo plazo tiene un margen de error, porque depende de decisiones que todavía no se han tomado. De hecho, hace diez años la ONU calculaba que en 2100 habría unos 700 millones de personas más que lo que calcula ahora. Cada nuevo informe corrige al anterior con datos más recientes." },
      { p: "En conclusión, lo más probable es que la humanidad deje de crecer antes de que acabe este siglo. Eso cambiará muchas cosas: las ciudades, el trabajo, las pensiones y hasta los colegios." },
    ],
    vocabulario: [
      { p: "abarrotado", d: "lleno por completo, sin sitio libre." },
      { p: "tendencia", d: "dirección hacia la que va cambiando algo." },
      { p: "margen de error", d: "cantidad en la que un cálculo se puede equivocar." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántos habitantes tendrá la Tierra, según la ONU, en su punto más alto y cuándo?", r: "Unos 10.300 millones, hacia mediados de la década de 2080.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué la población seguirá creciendo un tiempo aunque las familias tengan menos hijos?", r: "Porque la gente vive más años gracias a los avances en medicina y alimentación.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que un país esté por debajo de 2,1 hijos por mujer?", r: "Que, sin inmigración, su población tenderá a disminuir.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que la ONU ha cambiado su cálculo para 2100 respecto al de hace diez años?", r: "Porque ha tenido datos más recientes, por ejemplo que las familias tienen menos hijos de lo que se esperaba.", lineas: 2 },
      { tipo: "comprension", q: "Según el texto, en España habrá… Elige:", opciones: ["cada vez más jóvenes", "cada vez más personas mayores y menos jóvenes", "el doble de habitantes"], r: "cada vez más personas mayores y menos jóvenes" },
      { tipo: "texto", q: "Esta predicción es fiable. Aplica las preguntas de fiabilidad: ¿quién lo dice?, ¿cuándo?, ¿se apoya en datos? Responde con información del texto.", r: "Lo dice la ONU, con científicos expertos; en un informe de 2024, reciente; se apoya en datos como el número de hijos por mujer y la esperanza de vida.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué cambios crees que habrá en tu pueblo o ciudad si cada vez hay más personas mayores?", r: "Respuesta libre. Valorar que dé ejemplos razonados.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece bien que los expertos reconozcan que pueden equivocarse? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Los datos de población sirven para planificar colegios, hospitales o viviendas. ¿Por qué crees que un gobierno necesita estas predicciones?", r: "Respuesta libre. Valorar que relacione predicción y planificación.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-09-clima-andalucia",
    titulo: "Andalucía, con más calor en el futuro",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["AEMET: escenarios regionalizados de cambio climático para España (proyecciones para Andalucía)"],
    antes: "¿Has oído hablar del cambio climático? ¿Notas que los veranos son distintos a los que recuerdan tus abuelos?",
    texto: [
      { p: "Predecir el tiempo que hará dentro de dos semanas es muy difícil. Entonces, ¿cómo pueden los científicos anunciar cómo será el clima de Andalucía dentro de cincuenta años? La respuesta es que no hablan del tiempo de un día concreto, sino del clima: lo que suele pasar a lo largo de muchos años. Para calcularlo usan modelos climáticos, programas de ordenador muy potentes que simulan cómo se comportan la atmósfera y los océanos." },
      { p: "La Agencia Estatal de Meteorología (AEMET) prepara escenarios de cambio climático para cada región de España. Un escenario no es una profecía: es una respuesta a la pregunta «¿qué pasará si…?». Por ejemplo, ¿qué pasará si seguimos emitiendo muchos gases contaminantes?, o ¿qué pasará si los reducimos?" },
      { h: "Lo que anuncian los escenarios" },
      { p: "En primer lugar, las temperaturas seguirán subiendo a lo largo de este siglo, sobre todo en verano. En segundo lugar, habrá más días de olas de calor y más noches tropicales, es decir, noches en las que el termómetro no baja de 20 grados y cuesta dormir. Según estos estudios, las noches cálidas aumentarán sobre todo en la costa mediterránea y en el sur de Andalucía. En tercer lugar, es probable que llueva menos y que las sequías sean más frecuentes. Por último, el mar estará más caliente y su nivel subirá, lo que afectará a playas y marismas." },
      { h: "No todo está escrito" },
      { p: "Los escenarios muestran varios futuros posibles. En los que se reducen los gases contaminantes, el aumento de la temperatura es menor. Por eso los científicos insisten en que todavía estamos a tiempo de cambiar el resultado." },
      { p: "Además, en muchos pueblos y ciudades andaluzas ya se están preparando: plantan árboles para dar sombra, crean refugios climáticos con aire fresco y aprovechan mejor el agua." },
      { p: "En definitiva, el clima de Andalucía será más cálido y más seco, pero cuánto dependerá, en buena parte, de lo que hagamos desde hoy. Esta vez, conocer la predicción sirve precisamente para intentar que no se cumpla del todo." },
    ],
    vocabulario: [
      { p: "clima", d: "tiempo atmosférico habitual de un lugar a lo largo de muchos años." },
      { p: "simular", d: "reproducir algo de forma artificial para estudiarlo." },
      { p: "emitir", d: "echar al aire gases, humo, etc." },
      { p: "refugio climático", d: "lugar fresco donde las personas pueden protegerse del calor extremo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuál es la diferencia entre el tiempo y el clima, según el texto?", r: "El tiempo es lo que pasa en un día concreto; el clima es lo que suele pasar a lo largo de muchos años.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué es una noche tropical?", r: "Una noche en la que la temperatura no baja de 20 grados.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué el texto dice que un escenario «no es una profecía»?", r: "Porque no afirma lo que pasará seguro, sino lo que pasaría según lo que hagamos, por ejemplo si emitimos más o menos gases.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir la última frase: conocer la predicción sirve «para intentar que no se cumpla del todo»?", r: "Que si sabemos lo que puede pasar, podemos reducir los gases y adaptarnos para que el cambio sea menor.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuál de estas acciones NO aparece en el texto como forma de prepararse? Elige:", opciones: ["Plantar árboles para dar sombra", "Construir más piscinas", "Crear refugios climáticos"], r: "Construir más piscinas" },
      { tipo: "texto", q: "Copia los conectores que ordenan las predicciones y el de la conclusión. ¿Por qué crees que el autor usa «es probable que» en una de ellas?", r: "En primer lugar, en segundo lugar, en tercer lugar, por último; conclusión: en definitiva. Usa «es probable» porque esa predicción (la lluvia) es menos segura que las demás.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece fiable esta predicción? Razona tu respuesta con las preguntas: ¿quién lo dice?, ¿se apoya en datos?", r: "Respuesta libre. Valorar que mencione a la AEMET y los modelos climáticos.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué cambiarías en tu colegio para que fuera más fresco en los días de calor?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Las personas que más sufrirán el cambio climático son niños como tú. ¿Crees que deberían participar en las decisiones sobre este tema? ¿Cómo?", r: "Respuesta libre. Valorar que argumente.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-10-viajes-espaciales",
    titulo: "Rumbo a la Luna… y después, a Marte",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["NASA: misión Artemis II (abril de 2026)", "ESA: misión ExoMars Rosalind Franklin"],
    antes: "¿Te gustaría viajar al espacio? ¿Crees que algún día vivirán personas en la Luna o en Marte?",
    texto: [
      { p: "En abril de 2026, cuatro astronautas despegaron a bordo de la nave Orión para rodear la Luna. Era la misión Artemis II de la NASA, la agencia espacial de Estados Unidos, y la primera vez desde 1972 que seres humanos viajaban hasta nuestro satélite. A bordo iban Reid Wiseman, Victor Glover, Christina Koch y el canadiense Jeremy Hansen. Durante diez días, recorrieron cientos de miles de kilómetros, pasaron por detrás de la cara oculta de la Luna y batieron el récord de la mayor distancia a la que han viajado personas desde la Tierra. El 10 de abril amerizaron en el océano Pacífico." },
      { p: "Artemis II no se posó en la Luna: era un ensayo. Pero, gracias a lo que aprendieron, ¿qué podemos esperar ahora?" },
      { h: "Lo que está previsto" },
      { p: "En primer lugar, la NASA planea que, en las próximas misiones Artemis, algunos astronautas vuelvan a caminar sobre la Luna. El objetivo, a largo plazo, es construir bases donde se pueda permanecer durante más tiempo. En segundo lugar, la Agencia Espacial Europea (ESA), de la que forma parte España, prepara el lanzamiento del explorador Rosalind Franklin, un robot que viajará a Marte. Si se cumple el calendario, despegará a finales de 2028 y llegará a Marte en 2030. Una vez allí, perforará el suelo hasta unos dos metros de profundidad para buscar señales de vida pasada." },
      { h: "Lo que es más difícil de predecir" },
      { p: "¿Y cuándo pisará Marte el primer ser humano? Aquí las predicciones son mucho menos seguras. El viaje duraría varios meses, los astronautas recibirían mucha radiación y todavía no existe una nave preparada para ir y volver. Por eso, cuando alguien anuncia una fecha exacta, conviene preguntarse en qué se basa. Además, la historia de la exploración espacial está llena de retrasos: las misiones se aplazan cuando hay problemas técnicos, porque la seguridad es lo primero." },
      { p: "En conclusión, es muy probable que en los próximos años veamos de nuevo huellas humanas en la Luna y robots europeos en Marte. Las personas en Marte, en cambio, son por ahora una posibilidad. Quién sabe: quizá alguien de tu clase trabaje algún día en una de esas misiones." },
    ],
    vocabulario: [
      { p: "satélite", d: "cuerpo que gira alrededor de un planeta, como la Luna alrededor de la Tierra." },
      { p: "amerizar", d: "posarse una nave en el agua del mar." },
      { p: "perforar", d: "hacer un agujero atravesando algo." },
      { p: "aplazar", d: "dejar algo para más adelante." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tuvo de especial la misión Artemis II?", r: "Fue la primera vez desde 1972 que personas viajaron hasta la Luna, y batieron el récord de distancia desde la Tierra.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué hará el explorador Rosalind Franklin cuando llegue a Marte?", r: "Perforará el suelo hasta unos dos metros para buscar señales de vida pasada.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué crees que Artemis II fue solo un ensayo y no se posó en la Luna?", r: "Para comprobar que la nave y los sistemas funcionan con personas a bordo antes de intentar algo más arriesgado.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué predicción es la MENOS segura, según el texto? Elige:", opciones: ["Que los astronautas vuelvan a pisar la Luna", "Que un robot europeo llegue a Marte", "La fecha en que una persona pisará Marte"], r: "La fecha en que una persona pisará Marte" },
      { tipo: "comprension", q: "¿Qué dificultades tendría un viaje tripulado a Marte?", r: "Duraría varios meses, los astronautas recibirían mucha radiación y aún no existe una nave preparada para ir y volver.", lineas: 2 },
      { tipo: "texto", q: "El texto distingue entre «es muy probable» y «una posibilidad». Explica la diferencia y copia una oración en condicional que hable del viaje a Marte.", r: "«Muy probable» indica una predicción con buenas razones; «posibilidad», algo incierto. Condicional: «El viaje duraría varios meses» o «los astronautas recibirían mucha radiación».", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que es importante gastar dinero en explorar el espacio? Da dos razones.", r: "Respuesta libre. Valorar que argumente con razones.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué pregunta le harías a un astronauta de Artemis II? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Si alguien en internet asegura que en cinco años habrá una ciudad en Marte, ¿cómo comprobarías si es una predicción fiable?", r: "Respuesta libre. Valorar que aplique las preguntas: quién lo dice, cuándo, si coincide con otras fuentes y si hay pruebas.", lineas: 3 },
    ],
  },
];
