// Lecturas · Textos predictivos (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["predictivo"] = [
  {
    id: "predictivo-01-tiempo-andalucia",
    titulo: "El tiempo en Andalucía este fin de semana",
    subtipo: "Previsión meteorológica",
    curso: "5º",
    fuente: "Texto original. Previsión inventada para esta ficha (los datos no son reales).",
    antes: "¿Miras el tiempo antes de salir de casa o de una excursión? ¿Dónde lo consultas?",
    texto: [
      { p: "Buenas tardes. Llega el primer fin de semana de octubre y, con él, un cambio de tiempo en Andalucía. Os contamos qué podemos esperar." },
      { h: "Sábado: sol y calor suave" },
      { p: "El sábado todavía mandará el buen tiempo. Tendremos cielos despejados en casi toda la comunidad y las temperaturas serán agradables, algo más altas en el valle del Guadalquivir. En la costa soplará un poniente flojo, así que el mar estará tranquilo en Cádiz y en Huelva. En las zonas altas de Sierra Nevada, en cambio, la noche será fresca y conviene llevar chaqueta." },
      { tabla: { titulo: "Previsión para el sábado (temperaturas en grados)", cab: ["Ciudad", "Máxima", "Mínima", "Cielo"], filas: [
        ["Almería", "26", "19", "Despejado"],
        ["Cádiz", "25", "19", "Despejado"],
        ["Córdoba", "30", "16", "Despejado"],
        ["Granada", "25", "12", "Poco nuboso"],
        ["Huelva", "27", "17", "Despejado"],
        ["Jaén", "26", "15", "Poco nuboso"],
        ["Málaga", "27", "18", "Despejado"],
        ["Sevilla", "29", "17", "Despejado"],
      ] }, nota: "Datos inventados para esta actividad." },
      { h: "Domingo: llega la lluvia por el oeste" },
      { p: "El domingo, en cambio, las cosas cambiarán. Una borrasca que se acerca desde el Atlántico entrará por Huelva a primera hora y avanzará hacia el este durante el día. Por eso, las nubes irán cubriendo el cielo y probablemente lloverá en el oeste de Andalucía a partir del mediodía. En Sevilla y Córdoba la probabilidad de lluvia será alta, de un 70 %. En Almería y Granada, sin embargo, es posible que no caiga ni una gota, porque las nubes llegarán muy debilitadas. Además, las temperaturas bajarán entre tres y cinco grados." },
      { h: "En el mar y en la montaña" },
      { p: "Con la llegada de la borrasca, el viento girará y soplará del suroeste con fuerza en el litoral de Huelva y de Cádiz. Habrá olas de hasta dos metros, así que no es un buen día para salir a navegar. En la montaña, las cumbres de Sierra Nevada y de la Sierra de Cazorla amanecerán con niebla y el termómetro podría bajar de cinco grados. Si pensáis hacer una ruta, revisad la previsión antes de salir y no subáis solos." },
      { h: "¿Y el lunes?" },
      { p: "Para el lunes todavía hay muchas dudas. Algunos cálculos dicen que la borrasca se marchará rápido hacia el Mediterráneo y volverá el sol; otros, que se quedará un día más sobre Andalucía oriental. Por eso preferimos no arriesgarnos: lo más probable es que el día empiece nublado y que las nubes se retiren poco a poco. Os lo confirmaremos en el próximo boletín." },
      { h: "¿Cómo sabemos todo esto?" },
      { p: "Una previsión no es una adivinanza. Los meteorólogos reúnen cada día millones de datos: los que miden las estaciones meteorológicas repartidas por todo el territorio, las imágenes de los satélites, los radares que detectan la lluvia y los globos sonda que suben a gran altura. Con todos ellos, unos ordenadores muy potentes calculan cómo se moverán las nubes y el viento en los próximos días." },
      { h: "Nuestro consejo" },
      { p: "En resumen: si tenéis un plan al aire libre, mejor el sábado. Si salís el domingo, no olvidéis el paraguas. Y recordad que una previsión no es una certeza: la actualizaremos mañana con los últimos datos de los satélites." },
    ],
    vocabulario: [
      { p: "borrasca", d: "zona de bajas presiones que suele traer nubes, viento y lluvia." },
      { p: "poniente", d: "viento que sopla desde el oeste." },
      { p: "probabilidad", d: "posibilidad de que algo ocurra, que se puede expresar en tanto por ciento." },
      { p: "globo sonda", d: "globo que lleva aparatos para medir el aire a mucha altura." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Según la tabla, ¿qué ciudad tendrá la temperatura más alta el sábado? ¿Y la más baja por la noche?", r: "Córdoba, con 30 grados. La mínima más baja será en Granada, con 12.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que es posible que no llueva en Almería?", r: "Porque está en el este, lejos de donde entra la borrasca, y las nubes llegarán muy debilitadas.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué datos usan los meteorólogos para hacer una previsión? Nombra tres.", r: "Los de las estaciones meteorológicas, las imágenes de los satélites, los radares y los globos sonda.", lineas: 2 },
      { tipo: "texto", q: "Copia tres verbos en futuro del texto. ¿Qué palabra o expresión indica que algo no es seguro?", r: "Futuro: mandará, tendremos, serán, soplará, estará, cambiarán, entrará, lloverá, bajarán… Duda: probablemente, es posible, podría.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué trabajos o actividades dependen mucho de la previsión del tiempo? ¿Por qué?", r: "Respuesta libre (agricultura, pesca, aviones, excursiones…).", lineas: 2 },
      { tipo: "reflexion", q: "Esta previsión es inventada. ¿Qué pasaría si alguien la difundiera como si fuera real? ¿Por qué es importante indicar la fuente?", r: "Respuesta libre. Valorar que hable de la desinformación y de la fiabilidad de las fuentes.", lineas: 3 },
    ],
  },
  {
    id: "predictivo-02-horoscopo-patio",
    titulo: "El horóscopo del patio",
    subtipo: "Horóscopo humorístico",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has leído alguna vez un horóscopo? ¿Crees que las estrellas pueden saber lo que te va a pasar?",
    texto: [
      { p: "La revista de nuestro colegio estrena sección. Madame Tiza, nuestra adivina oficial, ha mirado las estrellas (y también el calendario de exámenes) y nos cuenta qué nos espera esta semana. Busca tu signo (si no aparece, es que esta semana las estrellas estaban nubladas), lee con atención… y no te lo tomes muy en serio." },
      { h: "Aries" },
      { p: "El lunes encontrarás algo que creías perdido, probablemente en el fondo de tu mochila, debajo de un bocadillo de hace tres semanas. Te aconsejo abrirla con cuidado." },
      { h: "Tauro" },
      { p: "Un número misterioso aparecerá en tu vida. Será el 7, o tal vez el 12. Si tienes examen de Matemáticas, podría ser cualquiera." },
      { h: "Géminis" },
      { p: "Tu mejor amigo te dirá algo muy importante el miércoles. Seguramente será: «¿Me dejas la goma?»." },
      { h: "Cáncer" },
      { p: "Sentirás una fuerza misteriosa que te empuja hacia la cocina a las cinco de la tarde. Los astros la llaman merienda." },
      { h: "Leo" },
      { p: "Brillarás como el sol. Sobre todo si te olvidas la gorra en la excursión." },
      { h: "Libra" },
      { p: "Tendrás que tomar una decisión muy difícil: ¿fútbol o comba en el recreo? Las estrellas no se atreven a elegir por ti." },
      { h: "Escorpio" },
      { p: "Los astros anuncian un gran cambio: el viernes habrá lentejas en el comedor. Prepárate." },
      { h: "Capricornio" },
      { p: "Alguien pronunciará tu nombre en voz alta esta semana. Puede que sea tu maestra pasando lista, o puede que no." },
      { h: "Piscis" },
      { p: "Una persona cercana te sorprenderá con un regalo. O con deberes extra. Las estrellas lo ven un poco borroso." },
      { h: "Nota de la redacción" },
      { p: "Madame Tiza no es adivina: es Marta, de sexto, que tiene mucho sentido del humor. Pero fijaos en cómo funciona su horóscopo, porque los de verdad se parecen bastante. En primer lugar, usa frases tan generales que le pueden pasar a cualquiera: todo el mundo pierde cosas y todos los amigos piden la goma. En segundo lugar, añade palabras como «probablemente» o «tal vez», así nunca falla del todo. Por último, no da ninguna razón: no explica por qué las estrellas iban a saber qué hay de comer el viernes. En realidad, lo sabe porque ha mirado el menú." },
      { p: "Hemos hecho una prueba: leímos en voz alta el horóscopo de Piscis a toda la clase, sin decir de qué signo era. Veinte de los veinticuatro alumnos dijeron que era el suyo. ¿Por qué? Porque a todos nos pasan cosas parecidas, y cada uno se fija solo en lo que encaja con su vida." },
      { p: "En definitiva, un horóscopo puede ser divertido, pero no es una predicción fiable, porque no se apoya en datos ni en pruebas. Para saber si lloverá, consultad la previsión del tiempo; para saber qué hay de comer, el menú del comedor." },
    ],
    vocabulario: [
      { p: "astros", d: "cuerpos del cielo, como las estrellas, los planetas o la Luna." },
      { p: "redacción", d: "equipo que escribe una revista o un periódico." },
      { p: "signo", d: "cada una de las doce partes en que el horóscopo divide el año." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién es en realidad Madame Tiza y cómo sabe que el viernes habrá lentejas?", r: "Marta, una alumna de sexto. Lo sabe porque ha mirado el menú del comedor, no las estrellas.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué demuestra la prueba de leer el horóscopo de Piscis a toda la clase?", r: "Que las frases son tan generales que casi todo el mundo cree que hablan de él: veinte de veinticuatro alumnos dijeron que era el suyo.", lineas: 2 },
      { tipo: "comprension", q: "La nota de la redacción piensa que el horóscopo… Elige:", opciones: ["es una predicción científica", "es divertido pero no es fiable", "acierta siempre"], r: "es divertido pero no es fiable" },
      { tipo: "texto", q: "Un texto predictivo fiable se apoya en razones o datos. ¿Por qué el horóscopo no lo es? Copia dos conectores de la nota de la redacción.", r: "Porque no da razones ni datos; solo afirma. Conectores: en primer lugar, en segundo lugar, por último, en definitiva.", lineas: 2 },
      { tipo: "opinion", q: "Escribe una predicción divertida para tu clase, pero que esté basada en un dato real (el horario, el menú, el calendario…).", r: "Respuesta libre. Valorar que incluya un dato y un verbo en futuro.", lineas: 2 },
      { tipo: "reflexion", q: "¿Tomarías una decisión importante por lo que dice un horóscopo? ¿Qué harías en su lugar?", r: "Respuesta libre. Valorar el pensamiento crítico.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-03-cole-2050",
    titulo: "Mi cole en 2050",
    subtipo: "Redacción predictiva",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Cómo crees que será tu colegio cuando tus hijos o tus sobrinos vayan a él?",
    texto: [
      { p: "Me llamo Iker, estoy en quinto y mi abuela Carmen fue a este mismo colegio hace más de sesenta años. Cuando me cuenta cómo era, me parece otro planeta: escribían con pluma y tinta, y en invierno se calentaban con una estufa en el centro de la clase. Por eso pienso que, en 2050, mi colegio también habrá cambiado muchísimo." },
      { p: "Antes de escribir esta redacción, le hice una entrevista a mi abuela. Le pregunté qué era lo que más echaba de menos de su colegio. Se quedó pensando y me dijo: «Los recreos. Jugábamos a la comba, a la rayuela y al escondite, y no hacía falta nada más». Luego le pregunté qué le parecía mejor ahora, y me contestó que los niños y las niñas estudian juntos y que hay libros para todos. Con sus respuestas y con lo que veo a mi alrededor, he preparado mis predicciones." },
      { p: "Para empezar, creo que los horarios serán diferentes. Ya ahora en algunos colegios se hacen proyectos que duran semanas en lugar de clases sueltas. Seguramente, en el futuro, las asignaturas se mezclarán más: estudiaremos Matemáticas midiendo el huerto y Lengua escribiendo el periódico del barrio." },
      { p: "En segundo lugar, los edificios cuidarán más el planeta. Cada vez hay más placas solares en los tejados y en mi pueblo ya han plantado árboles en el patio para que den sombra. Por eso imagino que en 2050 los colegios producirán su propia energía y tendrán patios con más tierra y menos cemento. Puede que incluso recojan el agua de la lluvia para regar el huerto." },
      { p: "En tercer lugar, creo que el comedor cambiará. En nuestro colegio ya tenemos un huerto pequeño y, algunos días, las lechugas que plantamos acaban en la ensalada. Si cada colegio tuviera un huerto grande, los alumnos aprenderíamos de dónde viene la comida y tiraríamos menos. Me parece que eso pasará, porque cada vez se habla más de no desperdiciar alimentos." },
      { p: "También pienso que los colegios estarán preparados para todo el mundo. Mi amiga Sofía va en silla de ruedas y, aunque en nuestro colegio hay una rampa, todavía no puede subir sola al laboratorio, porque no hay ascensor. Cada año se hacen más obras para que los edificios sean accesibles, así que creo que en 2050 no quedará ningún colegio con escaleras que dejen a alguien fuera." },
      { p: "Además, habrá más tecnología, pero no creo que los robots sustituyan a los maestros. Mi abuela dice que ella recuerda a su maestra, no la pizarra. Yo pienso lo mismo: una máquina podrá corregir cuentas, pero no sabrá cuándo estás triste." },
      { p: "Por último, me gustaría que llegar al cole fuera más fácil. Si hubiera carriles bici seguros en todas las calles, casi nadie vendría en coche. No sé si pasará, pero ya hay ciudades que lo están haciendo." },
      { p: "No todos mis compañeros piensan como yo. Lucía cree que en 2050 no hará falta ir al colegio, porque cada uno aprenderá desde casa con una pantalla. Yo no estoy de acuerdo. Cuando tuvimos que dar clase desde casa unos días por una nevada, a todos nos pareció divertido el primer día y aburridísimo el tercero. Echábamos de menos el recreo, las bromas y hasta la voz de la maestra. Por eso creo que el colegio seguirá siendo un lugar al que se va, aunque se usen más pantallas." },
      { p: "Tampoco estamos de acuerdo en los libros. Marcos dice que desaparecerán los de papel. Yo creo que convivirán con los digitales, porque a mucha gente le gusta pasar las páginas y subrayar con lápiz. De hecho, la biblioteca de mi colegio tiene cada año más socios, y los libros más pedidos siempre son de papel." },
      { p: "Claro que puedo equivocarme. Cuando mi abuela era pequeña, nadie imaginaba que llevaríamos un ordenador en el bolsillo, así que seguro que en 2050 habrá inventos que hoy no puedo ni imaginar. Por eso mis predicciones no son adivinanzas: me baso en cosas que ya están empezando a pasar." },
      { p: "En conclusión, creo que el cole de 2050 será más verde, más práctico y con más tecnología, aunque lo más importante seguirá siendo lo mismo: las personas. Dentro de muchos años leeré esta redacción y comprobaré cuánto he acertado. A lo mejor se la leo a mis nietos, igual que mi abuela me cuenta a mí sus historias." },
    ],
    vocabulario: [
      { p: "sustituir", d: "poner a una persona o cosa en el lugar de otra." },
      { p: "placa solar", d: "panel que transforma la luz del sol en energía." },
      { p: "desperdiciar", d: "no aprovechar algo, tirarlo o gastarlo sin sacarle provecho." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué hizo Iker antes de escribir sus predicciones y para qué le sirvió?", r: "Entrevistó a su abuela. Le sirvió para saber cómo era el colegio antes y comparar con lo que ve ahora.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Iker con la frase «una máquina podrá corregir cuentas, pero no sabrá cuándo estás triste»?", r: "Que los maestros no se pueden sustituir porque, además de enseñar, entienden y cuidan a los alumnos.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuál de sus predicciones es más bien un deseo? Elige:", opciones: ["Que habrá más placas solares", "Que llegar al cole será más fácil en bici", "Que habrá más tecnología"], r: "Que llegar al cole será más fácil en bici" },
      { tipo: "texto", q: "¿En qué se basa Iker para decir que sus predicciones «no son adivinanzas»? Copia el conector que abre la conclusión.", r: "En cosas que ya están empezando a pasar (placas solares, huertos, proyectos, carriles bici). Conector: «En conclusión».", lineas: 2 },
      { tipo: "opinion", q: "¿Estás de acuerdo con Iker en que los robots no sustituirán a los maestros? ¿Por qué?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
      { tipo: "reflexion", q: "Pregunta a una persona mayor cómo era su colegio. ¿Qué cambio te parece mejor y qué cosa crees que se ha perdido?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-04-previa-baloncesto",
    titulo: "Final alevín: ¿quién ganará?",
    subtipo: "Previa deportiva",
    curso: "5º",
    fuente: "Texto original. Noticia inventada para esta ficha.",
    antes: "¿Te gusta adivinar quién ganará un partido? ¿En qué te fijas para decidirlo?",
    texto: [
      { titular: "Poniente y Alcazaba se juegan el título alevín", subtitulo: "La final del torneo provincial de baloncesto se disputará el sábado en Almería", entradilla: "Almería. El Club Baloncesto Poniente y el Club Alcazaba se enfrentarán este sábado, a las once de la mañana, en la final alevín del torneo provincial. Analizamos quién tiene más papeletas para llevarse la copa." },
      { p: "Si miramos la clasificación, el Alcazaba parte como favorito. En primer lugar, ha ganado nueve de sus diez partidos de la temporada y es el equipo que más puntos anota por encuentro. En segundo lugar, jugará en su propio pabellón, con su afición, y eso siempre ayuda. Además, en la liga ya venció al Poniente por diez puntos de diferencia." },
      { p: "Sin embargo, el Poniente llega en su mejor momento. Ha ganado sus últimos cinco partidos y su defensa es la que menos puntos recibe de todo el torneo. Por otro lado, su base, Nadia Cortés, se recuperó de un esguince hace dos semanas y ya está en plena forma. Cuando jugaron en la liga, Nadia estaba lesionada, así que aquel resultado podría no repetirse." },
      { tabla: { titulo: "Los dos finalistas en números", cab: ["", "Alcazaba", "Poniente"], filas: [
        ["Partidos ganados", "9 de 10", "7 de 10"],
        ["Puntos anotados por partido", "48", "41"],
        ["Puntos recibidos por partido", "35", "30"],
        ["Últimos cinco partidos", "4 victorias", "5 victorias"],
      ] }, nota: "Datos inventados para esta ficha." },
      { h: "El camino hasta la final" },
      { p: "Ninguno de los dos lo ha tenido fácil. El Alcazaba ganó su semifinal por solo tres puntos, con una canasta de Hugo Benítez a falta de diez segundos. El Poniente, en cambio, sufrió en la primera parte de la suya, pero remontó una desventaja de ocho puntos gracias a su defensa y acabó ganando por seis. Ambos equipos han demostrado que saben sufrir, y eso, en una final, vale mucho." },
      { h: "Las claves del partido" },
      { p: "La primera clave será el duelo entre las bases. Nadia Cortés, del Poniente, es rápida y reparte muy bien el balón. Enfrente estará Hugo Benítez, el máximo anotador del Alcazaba, que tira de maravilla desde lejos. Quien consiga frenar al otro dará un paso de gigante hacia la copa." },
      { p: "La segunda clave será el rebote. El Alcazaba tiene jugadores más altos y suele atrapar casi todos los balones que no entran. Si lo consigue también el sábado, tendrá más oportunidades de tirar. El Poniente, en cambio, tendrá que correr mucho y saltar con ganas para compensar la diferencia de altura." },
      { p: "Los entrenadores prefieren no mojarse. «Será un partido muy igualado», asegura Rocío Maldonado, del Alcazaba. «Si defendemos como en las últimas semanas, tendremos opciones», explica Samuel Ortega, del Poniente. Los jugadores, en cambio, lo tienen claro: todos quieren ganar, pero, sobre todo, disfrutar de su primera final." },
      { h: "Una fiesta para todos" },
      { p: "El pabellón abrirá sus puertas a las diez y media y la entrada será gratuita. La organización espera llenar las gradas y pide a las aficiones que animen a su equipo sin insultar al rival ni a los árbitros. Al terminar, los dos equipos recibirán una medalla, y el trofeo al juego limpio será para el equipo que haya mostrado mejor comportamiento durante todo el torneo, dentro y fuera de la pista." },
      { p: "En conclusión, los números dicen que el Alcazaba ganará, pero la buena racha del Poniente y la vuelta de su base podrían dar la sorpresa. Lo que es seguro es que habrá emoción hasta el último segundo. Y no lo olvidemos: en el deporte, a veces el que parece más débil gana. Por eso se juegan los partidos." },
    ],
    vocabulario: [
      { p: "favorito", d: "quien tiene más posibilidades de ganar." },
      { p: "tener papeletas", d: "tener muchas posibilidades de conseguir algo." },
      { p: "mojarse", d: "(expresión) dar una opinión clara y comprometida." },
      { p: "rebote", d: "en baloncesto, atrapar el balón después de un tiro que no entra." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tres razones apoyan que ganará el Alcazaba?", r: "Ha ganado nueve de diez partidos y es el que más anota, juega en casa con su afición y ya venció al Poniente en la liga.", lineas: 2 },
      { tipo: "comprension", q: "Según la tabla, ¿en qué dato es mejor el Poniente que el Alcazaba? ¿Por qué eso puede ser importante en la final?", r: "Recibe menos puntos (30 frente a 35) y ha ganado sus últimos cinco partidos. Una buena defensa puede frenar al equipo que más anota.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué el periodista dice que el resultado de la liga podría no repetirse?", r: "Porque entonces Nadia Cortés, la base del Poniente, estaba lesionada, y ahora ya está recuperada.", lineas: 2 },
      { tipo: "texto", q: "Copia un conector que añada una razón, otro que presente una idea contraria y el de la conclusión.", r: "Añadir: en primer lugar, en segundo lugar, además, por otro lado. Contraria: sin embargo, en cambio. Conclusión: en conclusión.", lineas: 2 },
      { tipo: "opinion", q: "¿Quién crees que ganará la final? Justifica tu predicción con dos datos del texto.", r: "Respuesta libre. Valorar que use datos del texto.", lineas: 2 },
      { tipo: "reflexion", q: "Si tu equipo es el menos favorito, ¿te ayuda o te perjudica leer predicciones como esta? ¿Por qué?", r: "Respuesta libre. Valorar la reflexión sobre la motivación.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-05-buho-hormiga",
    titulo: "El búho profeta y la hormiga que miraba el cielo",
    subtipo: "Cuento",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Conoces algún truco de la naturaleza para saber si va a llover? ¿Te lo ha contado alguien?",
    texto: [
      { p: "En el bosque de los Alcornoques vivía un búho llamado Hilario que se hacía llamar el Gran Profeta. Todas las tardes subía a la rama más alta, se colocaba unas gafas que se había encontrado en una excursión humana y anunciaba el futuro con voz solemne." },
      { p: "—¡Escuchad, criaturas! —ululaba—. Mañana sucederá algo que nadie espera. Alguien encontrará lo que busca. Y el viento soplará… o no soplará." },
      { p: "Los animales aplaudían, maravillados. Al día siguiente, alguien siempre encontraba algo y el viento siempre soplaba o no soplaba, así que Hilario acertaba siempre." },
      { p: "Cerca del tronco vivía una hormiga llamada Adela que no hacía profecías: hacía observaciones." },
      { p: "Una vez, la ardilla Remedios subió a preguntarle si debía guardar bellotas para el invierno. Hilario cerró los ojos, movió la cabeza en círculo y dijo:" },
      { p: "—El invierno llegará cuando tenga que llegar. Y quien guarde, tendrá. Y quien no guarde… ya veremos." },
      { p: "La ardilla bajó igual de confundida que había subido, pero con la sensación de haber escuchado algo muy sabio." },
      { p: "Adela, que lo había oído todo desde abajo, se acercó a ella." },
      { p: "—Cuenta cuántas encinas tienen todavía bellotas y cuántas semanas faltan para las primeras heladas —le dijo—. Si guardas un poco cada día, cuando llegue el frío tendrás de sobra." },
      { p: "Remedios le hizo caso, aunque no terminaba de fiarse de una hormiga tan pequeña. Al fin y al cabo, Adela no llevaba gafas ni hablaba con voz solemne." },
      { p: "Una tarde de otoño, Adela notó tres cosas. El aire olía a tierra mojada, las golondrinas volaban muy bajo persiguiendo mosquitos y, a lo lejos, sobre la sierra, se amontonaban nubes grises." },
      { p: "—Esta noche lloverá fuerte —anunció—. Deberíamos mover las provisiones del hormiguero bajo, que es el que se inunda." },
      { p: "Los animales miraron a Hilario, que se ajustó las gafas." },
      { p: "—El Gran Profeta ha consultado a la Luna —declaró—. Y la Luna dice que mañana será un día… importante." },
      { p: "Todos se fueron a dormir tranquilos. Todos menos Adela y sus hermanas, que pasaron la tarde trasladando semillas al hormiguero de la loma." },
      { p: "Esa noche cayó una tormenta tremenda. El hormiguero bajo se llenó de barro y la madriguera de los conejos también. Por la mañana, empapados, los animales fueron a pedir explicaciones al búho." },
      { p: "—Os dije que sería un día importante —se defendió Hilario—. ¡Y lo ha sido!" },
      { p: "Entonces el conejo más joven se volvió hacia la hormiga." },
      { p: "—¿Cómo lo sabías tú?" },
      { p: "—No lo sabía —respondió Adela—. Lo deduje. El olor, las golondrinas y las nubes eran pistas. Podía haberme equivocado, pero tenía razones. Hilario habla mucho, pero nunca dice nada que se pueda comprobar." },
      { p: "Aquel invierno, Adela dio clases a los animales jóvenes. Les enseñó a fijarse en el color del cielo al atardecer, en la dirección del viento y en la humedad de la hierba por la mañana. Les pidió que apuntaran cada día lo que veían y si después llovía o no. Al cabo de unas semanas, el conejo joven acertaba más veces que nadie. Y la ardilla Remedios, con su despensa llena, pasó el invierno más tranquilo de su vida." },
      { p: "—¿Ves? —le dijo Adela—. No es magia. Es mirar con atención y aprender de los errores." },
      { p: "Desde aquel día, cuando Hilario anuncia el futuro, los animales le hacen siempre la misma pregunta: «¿Y en qué te basas?». Desde entonces, el búho hace muchas menos profecías. Dicen que ahora, algunas tardes, se le ve en la rama más alta, sin gafas, mirando el cielo en silencio. Quizá, por fin, ha empezado a observar." },
    ],
    vocabulario: [
      { p: "profeta", d: "persona que dice anunciar el futuro." },
      { p: "solemne", d: "serio y muy importante, con mucha ceremonia." },
      { p: "deducir", d: "llegar a una conclusión a partir de pistas o datos." },
      { p: "ulular", d: "dar gritos o aullidos, como hacen el búho o el viento." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué Hilario acertaba siempre?", r: "Porque sus profecías eran tan generales o tan ambiguas (el viento soplará o no) que era imposible que fallaran.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué enseñó Adela a los animales jóvenes y por qué crees que el conejo empezó a acertar más que nadie?", r: "A fijarse en el cielo, el viento y la humedad, y a apuntar lo que veían y si llovía. Acertaba porque observaba y aprendía de sus errores.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Adela con «No lo sabía. Lo deduje»? Elige:", opciones: ["Que tuvo suerte", "Que llegó a la conclusión a partir de pistas", "Que se lo dijo la Luna"], r: "Que llegó a la conclusión a partir de pistas" },
      { tipo: "texto", q: "Compara las dos predicciones: ¿cuál es un verdadero texto predictivo y por qué? Copia el verbo en futuro que usa cada personaje.", r: "La de Adela, porque se apoya en razones y pistas del presente. Adela: lloverá. Hilario: sucederá, encontrará, soplará, será.", lineas: 2 },
      { tipo: "opinion", q: "Adela reconoce que podía haberse equivocado. ¿Crees que eso hace su predicción más o menos fiable? ¿Por qué?", r: "Respuesta libre. Valorar que entienda que reconocer la duda es propio de una predicción seria.", lineas: 2 },
      { tipo: "reflexion", q: "La pregunta «¿Y en qué te basas?» sirve para muchas situaciones. ¿Cuándo podrías usarla tú?", r: "Respuesta libre.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-06-cosecha-aceituna",
    titulo: "¿Cómo será la cosecha de aceituna?",
    subtipo: "Folleto informativo",
    curso: "5º-6º",
    fuente: "Texto original. Folleto de una cooperativa inventada; las cifras son ficticias.",
    antes: "¿Sabes cómo se hace el aceite de oliva? ¿Por qué crees que unos años hay más aceitunas que otros?",
    texto: [
      { h: "Cooperativa El Olivo Viejo · Boletín para las familias socias" },
      { p: "Queridas familias: como cada otoño, el equipo técnico de la cooperativa ha recorrido los olivares de la comarca, en la provincia de Jaén, para estimar cuántas aceitunas recogeremos en la próxima campaña, que empezará a mediados de noviembre. Os contamos nuestra previsión y en qué nos basamos." },
      { h: "Nuestra previsión" },
      { p: "Calculamos que este año la cosecha será buena, algo mejor que la del año pasado. En nuestros cálculos, los socios entregarán unos doce millones de kilos de aceituna, con los que podremos obtener cerca de dos millones y medio de litros de aceite." },
      { h: "¿Cómo lo calculamos?" },
      { p: "No podemos contar todas las aceitunas de todos los olivos, así que hacemos como los científicos: tomamos una muestra. Elegimos cien olivos repartidos por toda la comarca, unos en llano y otros en ladera, unos de regadío y otros de secano. En cada uno contamos los frutos de varias ramas y calculamos una media. Después multiplicamos por el número de olivos de los socios. Así obtenemos una cifra aproximada, nunca exacta." },
      { h: "¿En qué nos basamos?" },
      { p: "Para empezar, la primavera fue lluviosa. Los olivos necesitan agua cuando florecen, y este año la tuvieron. Para continuar, la floración de mayo fue abundante: en las ramas que revisamos contamos muchas flores y, después, muchos frutos pequeños. Por otro lado, el verano no ha sido tan caluroso como otros años, así que se han caído menos aceitunas antes de tiempo." },
      { tabla: { titulo: "Cosechas de la cooperativa (datos ficticios)", cab: ["Campaña", "Aceituna (millones de kg)", "Lluvia en primavera"], filas: [
        ["Hace 3 años", "9", "Escasa"],
        ["Hace 2 años", "7", "Muy escasa"],
        ["El año pasado", "11", "Normal"],
        ["Este año (previsión)", "12", "Abundante"],
      ] } },
      { h: "Lo que todavía puede cambiar" },
      { p: "Una previsión no es una promesa. Si en octubre lloviera muy poco, las aceitunas serían más pequeñas y darían menos aceite. Si hubiera una granizada, podría dañar los frutos. Por eso revisaremos estos cálculos a finales de octubre." },
      { h: "Del olivo a la botella" },
      { p: "Recordamos a las familias nuevas cómo funciona la campaña. Primero se extienden las mantas bajo el olivo y se hacen caer las aceitunas con el vareador. Después se recogen, se limpian de hojas y se llevan a la almazara el mismo día, porque la aceituna que espera amontonada pierde calidad. Allí se lavan, se muelen y se separa el aceite del agua y de la pasta. El mejor aceite, el virgen extra, sale de aceitunas sanas recogidas del árbol." },
      { h: "Seguridad en el olivar" },
      { p: "Cada campaña pedimos lo mismo, porque es lo más importante. Usad guantes y botas de trabajo, no os subáis a los olivos ni a escaleras sin que alguien las sujete y mantened a los niños lejos del vareador y de los tractores. Descansad cada cierto tiempo y bebed agua aunque haga fresco. Una buena cosecha no vale nada si alguien se hace daño." },
      { p: "En definitiva, todo indica que tendremos una buena campaña. Os pedimos que tengáis las mantas y los vareadores a punto, y os recordamos que la almazara abrirá de siete de la mañana a nueve de la noche." },
    ],
    vocabulario: [
      { p: "cooperativa", d: "empresa formada por un grupo de personas que trabajan juntas y se reparten los beneficios." },
      { p: "almazara", d: "lugar donde se muele la aceituna para sacar el aceite." },
      { p: "muestra", d: "pequeña parte de un conjunto que se estudia para conocer cómo es el todo." },
      { p: "vareador", d: "herramienta o máquina que se usa para hacer caer las aceitunas del árbol." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Observa la tabla. ¿Qué relación hay entre la lluvia de primavera y la cosecha?", r: "Cuanta más lluvia en primavera, más aceituna se recoge.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la cooperativa elige olivos de llano y de ladera, de regadío y de secano, para su muestra?", r: "Para que la muestra se parezca a todos los olivares de la comarca y el cálculo sea más fiable.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué podría hacer que la previsión fallara? Elige:", opciones: ["Una primavera lluviosa", "Un octubre muy seco o una granizada", "Que la almazara abra temprano"], r: "Un octubre muy seco o una granizada" },
      { tipo: "texto", q: "Copia una oración en condicional. ¿Por qué el folleto usa el condicional en la parte «Lo que todavía puede cambiar»?", r: "«Las aceitunas serían más pequeñas y darían menos aceite» o «podría dañar los frutos». Porque son posibilidades, no hechos seguros.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece fiable esta previsión? Explica en qué te fijas para decidirlo.", r: "Respuesta libre. Valorar que mencione la muestra, las observaciones y los datos de otros años.", lineas: 2 },
      { tipo: "reflexion", q: "El olivar depende mucho de la lluvia. ¿Cómo crees que afectaría a Jaén una serie de años muy secos?", r: "Respuesta libre. Valorar que relacione clima, trabajo y economía.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-07-aves-donana",
    titulo: "Doñana espera a sus visitantes de invierno",
    subtipo: "Folleto divulgativo",
    curso: "5º-6º",
    fuente: "Texto original. Folleto inventado para esta ficha, con datos reales del censo de 2026.",
    datos: ["CSIC · Estación Biológica de Doñana: censo de aves acuáticas invernantes de enero de 2026", "Junta de Andalucía y Ministerio de Cultura: Doñana, Patrimonio Mundial (1994)"],
    antes: "¿Por qué crees que muchas aves viajan miles de kilómetros cada año? ¿Has visto alguna vez una bandada migrando?",
    texto: [
      { p: "Cada otoño, cuando en el norte de Europa empiezan las heladas y las primeras nevadas, miles de aves emprenden un largo viaje hacia el sur. Muchas de ellas terminan su ruta en Doñana, entre Huelva, Sevilla y Cádiz, uno de los humedales más importantes de Europa. Allí pasarán el invierno, más o menos de octubre a febrero. ¿Cuántas vendrán este año? Os contamos lo que se espera." },
      { h: "Un lugar protegido" },
      { p: "Doñana es Parque Nacional desde 1969 y, en 1994, la UNESCO la declaró Patrimonio de la Humanidad. Su secreto es la mezcla de paisajes: playas y dunas junto al mar, bosques de pinos, lagunas y, sobre todo, la marisma, una enorme llanura que se llena de agua con las lluvias de otoño e invierno y se seca en verano." },
      { h: "Lo que sabemos" },
      { p: "Más de trescientas especies de aves usan Doñana para criar, pasar el invierno o descansar en su viaje. Entre las invernantes destaca el ánsar común, una especie de ganso que llega desde el norte de Europa. Cada enero, los científicos de la Estación Biológica de Doñana hacen un censo: cuentan las aves desde una avioneta, desde vehículos y en los lugares donde duermen. En enero de 2026 contaron más de 385.000 aves acuáticas de 88 especies. Fue una buena noticia, porque en los dos años anteriores la sequía había dejado la marisma casi seca y se habían registrado mínimos históricos." },
      { p: "Contar desde una avioneta no es fácil: las bandadas se mueven y algunas son enormes. Cuando no se pueden contar una a una, los científicos cuentan un grupo pequeño, por ejemplo de cien aves, y calculan cuántos grupos de ese tamaño caben en la bandada." },
      { h: "¿Para qué sirve contar aves?" },
      { p: "Contar aves no es solo curiosidad. Las aves acuáticas son como un termómetro de la salud del humedal: si hay agua limpia, plantas y pequeños animales para comer, llegan muchas; si algo va mal, son de las primeras en notarlo y se van a otro sitio. Por eso, comparar los censos de muchos años ayuda a los científicos a saber si Doñana mejora o empeora, y a decidir cómo protegerla." },
      { h: "Nuestra previsión" },
      { p: "La clave es el agua. Cuando la marisma se inunda, las aves encuentran comida y refugio; cuando está seca, siguen su viaje o se quedan en otros lugares. Por eso, si este otoño llueve lo normal o más, es muy probable que el número de aves se parezca al del último invierno o incluso lo supere. En cambio, si el otoño es seco, llegarán menos aves y se concentrarán en las pocas lagunas con agua." },
      { p: "Aun así, hay que ser prudentes. Aun así, los científicos explican que la cifra de 2026 sigue por debajo de la media de los últimos años. Una marisma necesita varios años buenos seguidos para recuperarse del todo." },
      { h: "Algunas invernantes que podrás ver" },
      { p: "El ánsar común es un ganso grande y gris, con el pico anaranjado; suele volar en grupos que forman una V en el cielo. El pato cuchara es fácil de reconocer por su pico ancho y aplanado, que usa como un colador para filtrar el alimento del agua. El ánade silbón recibe su nombre por el silbido agudo del macho. Y la cerceta común es un pato pequeño y rápido que suele moverse en grupos por las orillas de las lagunas." },
      { h: "Consejos para la visita" },
      { p: "Trae prismáticos y ropa de colores discretos, camina en silencio y no te salgas de los senderos. Las mejores horas para observar son las primeras de la mañana y las últimas de la tarde, cuando las aves están más activas. Recuerda: somos invitados en su casa de invierno." },
    ],
    vocabulario: [
      { p: "humedal", d: "terreno cubierto de agua poco profunda, como marismas y lagunas." },
      { p: "censo", d: "recuento ordenado de personas, animales o cosas." },
      { p: "marisma", d: "terreno bajo y llano que se inunda cerca de la desembocadura de un río." },
      { p: "prudente", d: "que piensa antes de actuar o de hablar para no equivocarse." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué el censo de 2026 fue una buena noticia?", r: "Porque se contaron más aves que en los dos años anteriores, en los que la sequía dejó mínimos históricos.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué dice el texto que las aves acuáticas son «como un termómetro» de la salud del humedal?", r: "Porque si el humedal está sano llegan muchas, y si algo va mal son de las primeras en notarlo y se van. Su número indica cómo está Doñana.", lineas: 2 },
      { tipo: "comprension", q: "¿De qué depende, sobre todo, la previsión para este invierno? Elige:", opciones: ["De la lluvia de otoño", "Del número de visitantes", "De la temperatura del mar"], r: "De la lluvia de otoño" },
      { tipo: "texto", q: "Este folleto separa «Lo que sabemos» de «Nuestra previsión». ¿Por qué es importante separar los datos de las predicciones?", r: "Para que el lector sepa qué es seguro (datos del censo) y qué es una estimación que puede cambiar.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece fiable esta predicción? Explica qué fuentes usa y por qué crees que son de confianza o no.", r: "Respuesta libre. Valorar que mencione el censo científico de la Estación Biológica de Doñana.", lineas: 2 },
      { tipo: "reflexion", q: "Doñana depende del agua y del cuidado de las personas. ¿Qué podemos hacer, desde casa o desde el colegio, para proteger humedales como este?", r: "Respuesta libre. Valorar propuestas de ahorro de agua, respeto, difusión…", lineas: 2 },
    ],
  },
  {
    id: "predictivo-08-poblacion-mundial",
    titulo: "¿Cuántos seremos en el año 2100?",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["Naciones Unidas: World Population Prospects 2024 (Perspectivas de la Población Mundial), resumen de resultados"],
    antes: "¿Cuántas personas crees que viven hoy en el planeta? ¿Crees que seremos más o menos dentro de cien años?",
    texto: [
      { p: "Hace unos doscientos años, en toda la Tierra vivían alrededor de mil millones de personas. En 2024 ya éramos unos 8.200 millones. Con un crecimiento así, es fácil imaginar un futuro con un planeta abarrotado, pero ¿qué dicen los expertos? Cada pocos años, la Organización de las Naciones Unidas (ONU) publica un informe llamado Perspectivas de la Población Mundial, en el que científicos de todo el mundo estudian cómo cambiará el número de habitantes." },
      { h: "¿Cómo se hace una predicción así?" },
      { p: "Los demógrafos, los científicos que estudian la población, no adivinan: trabajan con datos. Reúnen los censos de cada país, los registros de nacimientos y de fallecimientos, y encuestas. Con esa información calculan cuántos hijos suele tener cada mujer, cuántos años vive de media la gente y cuántas personas cambian de país. Después suponen cómo irán cambiando esas cifras y calculan la población año a año hasta el final del siglo." },
      { h: "La predicción" },
      { p: "Según el informe publicado en 2024, la población mundial seguirá creciendo durante unos sesenta años más, pero cada vez más despacio. Hacia mediados de la década de 2080 alcanzará su punto más alto, con unos 10.300 millones de personas. Después, empezará a bajar poco a poco, y en el año 2100 seremos unos 10.200 millones." },
      { h: "Las razones" },
      { p: "En primer lugar, las familias tienen menos hijos que antes. En 1990, cada mujer tenía de media 3,3 hijos; hoy la media mundial es de 2,3. Para que una población no disminuya, hacen falta unos 2,1 hijos por mujer, y más de la mitad de los países del mundo ya están por debajo de esa cifra. En segundo lugar, al mismo tiempo, la gente vive más años gracias a los avances en medicina y alimentación: en 2024, una persona que nacía podía esperar vivir de media unos 73 años, más de ocho años más que en 1995. Eso hace que la población siga aumentando durante un tiempo. Por último, estas tendencias no son iguales en todo el planeta: en algunos países la población crecerá mucho, mientras que en otros, como España, habrá cada vez más personas mayores y menos jóvenes." },
      { h: "Un mundo con más abuelos" },
      { p: "El informe anuncia un cambio que nunca había ocurrido en la historia: hacia finales de la década de 2070, en el mundo habrá más personas de 65 años o más que niños y adolescentes menores de 18. Eso significa que harán falta más cuidadores, más médicos especializados en personas mayores y ciudades pensadas para caminar despacio, con bancos, ascensores y buen transporte." },
      { h: "Un planeta desigual" },
      { p: "El crecimiento no se repartirá por igual. Mientras que en muchos países de Europa y de Asia la población ya ha empezado a bajar o lo hará pronto, en otros, sobre todo de África, seguirá aumentando durante décadas, porque allí la población es muy joven y las familias tienen todavía más hijos." },
      { p: "¿Y tú? Si ahora tienes once años, en el año 2100 tendrás unos ochenta y cinco. Verás con tus propios ojos si la ONU acertó." },
      { h: "¿Podría equivocarse?" },
      { p: "Sí. Los propios expertos explican que una predicción a tan largo plazo tiene un margen de error, porque depende de decisiones que todavía no se han tomado. De hecho, hace diez años la ONU calculaba que en 2100 habría unos 700 millones de personas más que lo que calcula ahora. Cada nuevo informe corrige al anterior con datos más recientes." },
      { p: "En conclusión, lo más probable es que la humanidad deje de crecer antes de que acabe este siglo. Eso cambiará muchas cosas: las ciudades, el trabajo, las pensiones y hasta los colegios." },
    ],
    vocabulario: [
      { p: "abarrotado", d: "lleno por completo, sin sitio libre." },
      { p: "demógrafo", d: "científico que estudia la población: cuántos somos, cómo nacemos, vivimos y nos movemos." },
      { p: "tendencia", d: "dirección hacia la que va cambiando algo." },
      { p: "margen de error", d: "cantidad en la que un cálculo se puede equivocar." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuántos habitantes tendrá la Tierra, según la ONU, en su punto más alto y cuándo?", r: "Unos 10.300 millones, hacia mediados de la década de 2080.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué la población seguirá creciendo un tiempo aunque las familias tengan menos hijos?", r: "Porque la gente vive más años gracias a los avances en medicina y alimentación.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué cambio nunca visto anuncia el informe para finales de la década de 2070? ¿Qué consecuencias tendrá?", r: "Que habrá más personas de 65 años o más que menores de 18. Harán falta más cuidadores, médicos para mayores y ciudades adaptadas.", lineas: 2 },
      { tipo: "texto", q: "Aplica las preguntas de fiabilidad a esta predicción: ¿quién lo dice?, ¿cuándo?, ¿se apoya en datos? Responde con información del texto.", r: "Lo dice la ONU, con científicos expertos; en un informe de 2024, reciente; se apoya en censos, registros y encuestas, y en datos como el número de hijos por mujer y la esperanza de vida.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué cambios crees que habrá en tu pueblo o ciudad si cada vez hay más personas mayores?", r: "Respuesta libre. Valorar que dé ejemplos razonados.", lineas: 2 },
      { tipo: "reflexion", q: "Los datos de población sirven para planificar colegios, hospitales o viviendas. ¿Por qué crees que un gobierno necesita estas predicciones?", r: "Respuesta libre. Valorar que relacione predicción y planificación.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-09-clima-andalucia",
    titulo: "Andalucía, con más calor en el futuro",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["AEMET: escenarios regionalizados de cambio climático para España (proyecciones para Andalucía)"],
    antes: "¿Has oído hablar del cambio climático? ¿Notas que los veranos son distintos a los que recuerdan tus abuelos?",
    texto: [
      { p: "Predecir el tiempo que hará dentro de dos semanas es muy difícil. Entonces, ¿cómo pueden los científicos anunciar cómo será el clima de Andalucía dentro de cincuenta años? La respuesta es que no hablan del tiempo de un día concreto, sino del clima: lo que suele pasar a lo largo de muchos años. Para calcularlo usan modelos climáticos, programas de ordenador muy potentes que simulan cómo se comportan la atmósfera y los océanos." },
      { h: "Un ejemplo para entenderlo" },
      { p: "Piensa en una clase de veinticinco alumnos. Nadie puede saber qué nota sacará cada uno en el próximo examen, pero la maestra sí puede predecir, con bastante acierto, la nota media de la clase, porque conoce cómo han trabajado durante todo el curso. Con el clima pasa algo parecido: no sabemos si el 15 de julio de 2070 hará calor en Sevilla, pero sí podemos calcular cómo serán, de media, los veranos de esa época." },
      { p: "La Agencia Estatal de Meteorología (AEMET) prepara escenarios de cambio climático para cada región de España. Un escenario no es una profecía: es una respuesta a la pregunta «¿qué pasará si…?». Por ejemplo, ¿qué pasará si seguimos emitiendo muchos gases contaminantes?, o ¿qué pasará si los reducimos?" },
      { h: "Lo que anuncian los escenarios" },
      { p: "En primer lugar, las temperaturas seguirán subiendo a lo largo de este siglo, sobre todo en verano. En segundo lugar, habrá más días de olas de calor y más noches tropicales, es decir, noches en las que el termómetro no baja de 20 grados y cuesta dormir. Según estos estudios, las noches cálidas aumentarán sobre todo en la costa mediterránea y en el sur de Andalucía. En tercer lugar, es probable que llueva menos y que las sequías sean más frecuentes. Por último, el mar estará más caliente y su nivel subirá, lo que afectará a playas y marismas." },
      { h: "No todo está escrito" },
      { p: "Los escenarios muestran varios futuros posibles. En los que se reducen los gases contaminantes, el aumento de la temperatura es menor. Por eso los científicos insisten en que todavía estamos a tiempo de cambiar el resultado." },
      { h: "Lo que ya sabíamos hacer" },
      { p: "Los andaluces llevan siglos adaptándose al calor, y muchas de esas soluciones siguen siendo útiles. Las casas encaladas de los pueblos blancos reflejan la luz del sol y se calientan menos. Los patios con plantas y fuentes refrescan el aire, como los que se pueden ver en Córdoba. Los toldos que cubren algunas calles dan sombra a quien pasea, y los muros gruesos de las casas antiguas mantienen el fresco durante el día. Hoy, arquitectos e ingenieros estudian estas ideas para aplicarlas a los edificios nuevos." },
      { p: "Además, en muchos pueblos y ciudades andaluzas ya se están preparando: plantan árboles para dar sombra, crean refugios climáticos con aire fresco y aprovechan mejor el agua." },
      { h: "¿Y qué puedo hacer yo?" },
      { p: "Quizá pienses que un niño no puede cambiar el clima, pero muchas acciones pequeñas, sumadas, sí cuentan. Ir al colegio andando o en bici en lugar de en coche reduce los gases contaminantes. Apagar las luces y los aparatos que no se usan ahorra energía. Cerrar el grifo mientras te lavas los dientes ahorra agua, que en Andalucía será cada vez más valiosa. Y plantar y cuidar árboles en el patio o en el barrio da sombra, refresca el aire y da refugio a pájaros e insectos. Además, puedes contar a tu familia lo que has aprendido: a veces los niños convencen a los mayores." },
      { p: "En definitiva, el clima de Andalucía será más cálido y más seco, pero cuánto dependerá, en buena parte, de lo que hagamos desde hoy. Esta vez, conocer la predicción sirve precisamente para intentar que no se cumpla del todo." },
    ],
    vocabulario: [
      { p: "clima", d: "tiempo atmosférico habitual de un lugar a lo largo de muchos años." },
      { p: "simular", d: "reproducir algo de forma artificial para estudiarlo." },
      { p: "emitir", d: "echar al aire gases, humo, etc." },
      { p: "encalar", d: "pintar las paredes con cal, que las deja blancas." },
      { p: "refugio climático", d: "lugar fresco donde las personas pueden protegerse del calor extremo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "Explica con el ejemplo de la clase y el examen la diferencia entre el tiempo y el clima.", r: "No se puede saber la nota de cada alumno (el tiempo de un día), pero sí la media de la clase (el clima de muchos años).", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué las casas encaladas se calientan menos?", r: "Porque el color blanco refleja la luz del sol.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué el texto dice que un escenario «no es una profecía»?", r: "Porque no afirma lo que pasará seguro, sino lo que pasaría según lo que hagamos, por ejemplo si emitimos más o menos gases.", lineas: 2 },
      { tipo: "texto", q: "Copia los conectores que ordenan las predicciones. ¿Por qué crees que el autor usa «es probable que» en una de ellas?", r: "En primer lugar, en segundo lugar, en tercer lugar, por último. Usa «es probable» porque esa predicción (la lluvia) es menos segura que las demás.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué cambiarías en tu colegio para que fuera más fresco en los días de calor? ¿Por qué?", r: "Respuesta libre. Valorar que use ideas del texto (árboles, toldos, patios con plantas…).", lineas: 2 },
      { tipo: "reflexion", q: "Las personas que más sufrirán el cambio climático son niños como tú. ¿Crees que deberían participar en las decisiones sobre este tema? ¿Cómo?", r: "Respuesta libre. Valorar que argumente.", lineas: 2 },
    ],
  },
  {
    id: "predictivo-10-viajes-espaciales",
    titulo: "Rumbo a la Luna… y después, a Marte",
    subtipo: "Artículo de divulgación",
    curso: "6º",
    fuente: "Texto original",
    datos: ["NASA: misión Artemis II (abril de 2026)", "ESA: misión ExoMars Rosalind Franklin"],
    antes: "¿Te gustaría viajar al espacio? ¿Crees que algún día vivirán personas en la Luna o en Marte?",
    texto: [
      { p: "En abril de 2026, cuatro astronautas despegaron a bordo de la nave Orión para rodear la Luna. Era la misión Artemis II de la NASA, la agencia espacial de Estados Unidos, y la primera vez desde 1972 que seres humanos viajaban hasta nuestro satélite. A bordo iban Reid Wiseman, Victor Glover, Christina Koch y el canadiense Jeremy Hansen. Durante diez días, recorrieron cientos de miles de kilómetros, sobrevolaron la cara oculta de la Luna y batieron el récord de la mayor distancia a la que han viajado personas desde la Tierra. El 10 de abril amerizaron en el océano Pacífico." },
      { p: "Artemis II no se posó en la Luna: era un ensayo. Pero, gracias a lo que aprendieron, ¿qué podemos esperar ahora?" },
      { h: "¿Por qué volver a la Luna?" },
      { p: "Entre 1969 y 1972, doce astronautas caminaron sobre la Luna, y después nadie volvió. Hoy hay nuevas razones para regresar. Los científicos han descubierto que en algunos cráteres del polo sur de la Luna, donde nunca da el sol, hay agua helada. Ese hielo podría servir, en el futuro, para beber, para cultivar plantas e incluso para fabricar combustible. Además, la Luna es un buen lugar para practicar: todo lo que aprendamos allí servirá para viajes mucho más largos." },
      { h: "Lo que está previsto" },
      { p: "En primer lugar, la NASA planea que, en las próximas misiones Artemis, algunos astronautas vuelvan a caminar sobre la Luna. El objetivo, a largo plazo, es construir bases donde se pueda permanecer durante más tiempo. En segundo lugar, la Agencia Espacial Europea (ESA), de la que forma parte España, prepara el lanzamiento del explorador Rosalind Franklin, un robot que viajará a Marte. Si se cumple el calendario, despegará a finales de 2028 y llegará a Marte en 2030. Una vez allí, perforará el suelo hasta unos dos metros de profundidad para buscar señales de vida pasada." },
      { h: "¿Cómo sería una base lunar?" },
      { p: "Vivir en la Luna no será como acampar. No hay aire para respirar, las temperaturas pasan de un calor abrasador cuando da el sol a un frío terrible en la sombra, y la radiación del espacio llega sin nada que la frene. Por eso, los ingenieros imaginan bases pequeñas, muy aisladas y protegidas con una capa gruesa de polvo lunar por encima. Dentro, los astronautas tendrían que reciclar el aire y el agua una y otra vez." },
      { h: "España también participa" },
      { p: "En noviembre de 2022, la ESA eligió a su nueva promoción de astronautas. Entre ellos está el leonés Pablo Álvarez, y la investigadora Sara García, también de León, entró en la reserva de astronautas. Son los herederos de Pedro Duque, que viajó al espacio por primera vez en 1998." },
      { h: "Lo que es más difícil de predecir" },
      { p: "¿Y cuándo pisará Marte el primer ser humano? Aquí las predicciones son mucho menos seguras. El viaje duraría varios meses, los astronautas recibirían mucha radiación y todavía no existe una nave preparada para ir y volver. Además, no se puede salir hacia Marte en cualquier momento: la Tierra y Marte giran alrededor del Sol a distinta velocidad y solo se colocan en buena posición para el viaje más o menos cada dos años. Si una misión pierde esa oportunidad, tiene que esperar a la siguiente." },
      { p: "Por eso, cuando alguien anuncia una fecha exacta, conviene preguntarse en qué se basa. La historia de la exploración espacial está llena de retrasos: las misiones se aplazan cuando hay problemas técnicos, porque la seguridad es lo primero." },
      { p: "En conclusión, es muy probable que en los próximos años veamos de nuevo huellas humanas en la Luna y robots europeos en Marte. Las personas en Marte, en cambio, son por ahora una posibilidad. Quién sabe: quizá alguien de tu clase trabaje algún día en una de esas misiones." },
    ],
    vocabulario: [
      { p: "satélite", d: "cuerpo que gira alrededor de un planeta, como la Luna alrededor de la Tierra." },
      { p: "amerizar", d: "posarse una nave en el agua del mar." },
      { p: "perforar", d: "hacer un agujero atravesando algo." },
      { p: "aplazar", d: "dejar algo para más adelante." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué tuvo de especial la misión Artemis II?", r: "Fue la primera vez desde 1972 que personas viajaron hasta la Luna, y batieron el récord de distancia desde la Tierra.", lineas: 2 },
      { tipo: "comprension", q: "¿Para qué podría servir el agua helada de los cráteres del polo sur de la Luna?", r: "Para beber, para cultivar plantas e incluso para fabricar combustible.", lineas: 1 },
      { tipo: "comprension", q: "¿Por qué crees que un retraso pequeño puede hacer que una misión a Marte se aplace unos dos años?", r: "Porque la Tierra y Marte solo están en buena posición para el viaje más o menos cada dos años; si se pierde esa oportunidad hay que esperar a la siguiente.", lineas: 2 },
      { tipo: "texto", q: "El texto distingue entre «es muy probable» y «una posibilidad». Explica la diferencia y copia una oración en condicional sobre el viaje a Marte.", r: "«Muy probable» indica una predicción con buenas razones; «posibilidad», algo incierto. Condicional: «El viaje duraría varios meses» o «los astronautas recibirían mucha radiación».", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que es importante gastar dinero en explorar el espacio? Da dos razones.", r: "Respuesta libre. Valorar que argumente con razones.", lineas: 2 },
      { tipo: "reflexion", q: "Si alguien en internet asegura que en cinco años habrá una ciudad en Marte, ¿cómo comprobarías si es una predicción fiable?", r: "Respuesta libre. Valorar que aplique las preguntas: quién lo dice, cuándo, si coincide con otras fuentes y si hay pruebas.", lineas: 2 },
    ],
  },
];
