// Lecturas · Texto teatral (10 lecturas para 5º-6º)
window.LECTURAS = window.LECTURAS || {};
window.LECTURAS["teatro"] = [
  // ------------------------------------------------------------------ 01
  {
    id: "teatro-01-borrador-desaparecido",
    titulo: "El misterio del borrador desaparecido",
    subtipo: "Escena teatral de misterio escolar",
    curso: "5º",
    fuente: "Texto original",
    antes: "Si algo desapareciera de tu clase, ¿cómo lo investigarías? ¿Qué pistas buscarías?",
    texto: [
      { acot: "Un aula de quinto, un lunes por la mañana. A la izquierda, una pizarra verde con tizas. Al fondo, una estantería y, en el suelo, el terrario de Tomasa, la tortuga de la clase." },
      { personaje: "MAESTRA ROSA", acot: "buscando por toda la mesa", dice: "¿Alguien ha visto el borrador? El viernes lo dejé aquí, junto a las tizas." },
      { personaje: "LUCAS", dice: "Yo no he sido. El viernes me fui el primero porque tenía dentista." },
      { personaje: "AMINA", dice: "¡Qué raro! Un borrador no tiene patas para irse solo." },
      { personaje: "DANIEL", acot: "con voz de película de miedo", dice: "A lo mejor el colegio tiene un fantasma que odia las matemáticas." },
      { personaje: "IRENE", dice: "Los fantasmas no existen, Daniel. Lo que sí existen son las pistas. Seño, ¿puedo investigar?" },
      { personaje: "MAESTRA ROSA", dice: "Tienes cinco minutos, detective. Después, fracciones." },
      { acot: "IRENE saca una lupa de su estuche y se pone a gatas. Los demás la siguen por el suelo." },
      { personaje: "IRENE", dice: "Mirad. Hay una raya de polvo blanco, como si alguien hubiera arrastrado algo." },
      { personaje: "LUCAS", dice: "Empieza en la pizarra y va hacia la estantería." },
      { personaje: "DANIEL", acot: "mirando el terrario", dice: "Un momento… ¡El terrario está vacío! ¿Dónde está Tomasa?" },
      { personaje: "AMINA", dice: "¡Se ha escapado! ¿Quién le dio de comer el viernes?" },
      { acot: "Silencio. Todos miran a LUCAS, que se pone colorado." },
      { personaje: "LUCAS", dice: "Vale… Fui yo. Le puse lechuga y salí corriendo sin cerrar la tapa. ¡Por el dentista!" },
      { personaje: "IRENE", dice: "Entonces tenemos dos misterios. O quizá solo uno." },
      { acot: "IRENE se agacha junto a la estantería y aparta una caja de lápices. Allí está Tomasa, dormida, con la cabeza apoyada en el borrador." },
      { personaje: "IRENE", dice: "Caso resuelto. Tomasa no es una ladrona: ¡se ha buscado una almohada!" },
      { personaje: "DANIEL", dice: "Yo lo sabía. Esa tortuga tiene cara de saber mucho." },
      { acot: "Todos ríen. LUCAS devuelve a Tomasa al terrario, cierra la tapa y comprueba dos veces que está bien cerrada." },
      { personaje: "MAESTRA ROSA", dice: "Muy bien, detectives. Tomasa se queda con su almohada y yo traeré otro borrador. Y ahora… ¡fracciones!" },
      { personaje: "TODOS", acot: "a la vez", dice: "¡Ooooh!" },
      { acot: "Se apagan las luces. Solo se ve el terrario, donde Tomasa sigue durmiendo tan tranquila." },
    ],
    vocabulario: [
      { p: "terrario", d: "caja de cristal preparada para que vivan animales pequeños como tortugas o reptiles." },
      { p: "a gatas", d: "apoyando las manos y las rodillas en el suelo." },
      { p: "colorado", d: "con la cara roja, por vergüenza o calor." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Dónde y cuándo ocurre la escena? ¿Qué problema aparece al principio?", r: "En un aula de quinto, un lunes por la mañana. La maestra no encuentra el borrador que dejó el viernes.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué había una raya de polvo blanco en el suelo?", r: "Porque la tortuga arrastró el borrador, lleno de tiza, desde la pizarra hasta la estantería.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué se pone colorado Lucas? Elige:", opciones: ["Porque le duele la muela.", "Porque se da cuenta de que Tomasa se escapó por su culpa.", "Porque él escondió el borrador."], r: "Porque se da cuenta de que Tomasa se escapó por su culpa." },
      { tipo: "comprension", q: "Irene dice: «Tenemos dos misterios. O quizá solo uno». ¿Qué quiere decir?", r: "Que la desaparición del borrador y la de la tortuga pueden estar relacionadas: quizá Tomasa se llevó el borrador.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué hace Lucas al final que demuestra que ha aprendido de su error?", r: "Cierra la tapa del terrario y comprueba dos veces que está bien cerrada.", lineas: 1 },
      { tipo: "texto", q: "Copia una acotación que indique un movimiento de un personaje. ¿Por qué los actores no la dicen en voz alta?", r: "Por ejemplo: «IRENE saca una lupa de su estuche y se pone a gatas». Las acotaciones son indicaciones del autor para representar la obra (gestos, movimientos, escenario); no forman parte de lo que dicen los personajes.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece bien cómo reaccionan los compañeros cuando Lucas confiesa? ¿Por qué?", r: "Respuesta libre. Valorar que se reconozca la importancia de admitir los errores y de no burlarse de quien lo hace.", lineas: 3 },
      { tipo: "opinion", q: "Si representarais esta obra en clase, ¿qué personaje te gustaría hacer y cómo lo interpretarías?", r: "Respuesta libre. Valorar que se aluda a la voz, los gestos o el carácter del personaje.", lineas: 3 },
      { tipo: "reflexion", q: "Irene dice que los fantasmas no existen, pero las pistas sí. ¿Por qué es mejor buscar pruebas antes de acusar a alguien?", r: "Respuesta libre. Valorar que se relacione con la justicia y con no hacer daño a otros con acusaciones falsas.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 02
  {
    id: "teatro-02-ensayo-general",
    titulo: "Ensayo general",
    subtipo: "Comedia escolar",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Has actuado alguna vez en una función? ¿Salió todo como estaba previsto?",
    texto: [
      { acot: "El salón de actos del colegio, la tarde antes de la función de fin de curso. En el escenario hay un árbol de cartón y una cesta. El PROFESOR JAVIER está sentado en primera fila con el guion en la mano." },
      { personaje: "PROFESOR JAVIER", dice: "Último ensayo, chicos. Mañana viene todo el colegio. Valeria, cuando quieras." },
      { personaje: "VALERIA", acot: "entra dando saltitos con una capa roja", dice: "Voy a casa de mi abuelita a llevarle… a llevarle… ¿Qué le llevaba yo?" },
      { personaje: "NOA", acot: "susurrando desde un lateral", dice: "¡Pasteles y miel!" },
      { personaje: "VALERIA", dice: "¡Pasteles y miel! Gracias, Noa." },
      { personaje: "PROFESOR JAVIER", dice: "Valeria, al público no se le dan las gracias por el apunte. Sigue." },
      { acot: "Entra OMAR disfrazado de lobo. Lleva una bufanda enorme y un pañuelo en la mano." },
      { personaje: "OMAR", acot: "con voz ronca", dice: "Hola, niña. ¿Adónde vas tan… tan… ¡Aaachís!" },
      { acot: "El estornudo es tan fuerte que el árbol de cartón se tambalea. Desde dentro del árbol se oye una voz." },
      { personaje: "MARCOS", dice: "¡Eh, cuidado! Que yo desde aquí dentro no veo nada." },
      { personaje: "PROFESOR JAVIER", acot: "llevándose las manos a la cabeza", dice: "Un lobo resfriado, una Caperucita sin memoria y un árbol que habla. ¡Esto es un desastre!" },
      { acot: "Silencio. Los actores se miran preocupados. NOA sale al centro del escenario." },
      { personaje: "NOA", dice: "Profe, ¿y si no es un desastre? A lo mejor es otra obra. Una más divertida." },
      { personaje: "OMAR", dice: "¡Claro! Un lobo que no puede asustar a nadie porque está constipado." },
      { personaje: "MARCOS", acot: "asomando la cabeza por un agujero del tronco", dice: "Y un árbol parlanchín que le da consejos a Caperucita." },
      { personaje: "VALERIA", dice: "Y yo puedo olvidarme las cosas a propósito, y el árbol me las recuerda." },
      { personaje: "PROFESOR JAVIER", acot: "piensa un momento y sonríe", dice: "«Caperucita y el lobo con catarro»… Me gusta. Pero hay una condición." },
      { personaje: "TODOS", dice: "¿Cuál?" },
      { personaje: "PROFESOR JAVIER", dice: "Que Omar se tome hoy un buen vaso de leche con miel y se acueste temprano." },
      { personaje: "OMAR", dice: "Hecho. Pero la miel es para la abuelita, ¿eh? Yo solo quiero la leche." },
      { acot: "Todos ríen. El PROFESOR JAVIER rompe una hoja del guion y empieza a escribir deprisa. Mientras tanto, el árbol de cartón se tambalea otra vez." },
      { personaje: "MARCOS", dice: "¡Que alguien me saque de aquí, por favor!" },
      { acot: "Telón." },
    ],
    vocabulario: [
      { p: "ensayo", d: "práctica de una obra antes de representarla ante el público." },
      { p: "apunte", d: "ayuda en voz baja para recordar a un actor lo que tiene que decir." },
      { p: "tambalearse", d: "moverse de un lado a otro, como si fuera a caerse." },
      { p: "telón", d: "gran cortina que se abre y se cierra delante del escenario." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué obra están ensayando y para cuándo?", r: "Caperucita Roja, para la función de fin de curso del día siguiente.", lineas: 1 },
      { tipo: "comprension", q: "Enumera los tres problemas que surgen durante el ensayo.", r: "Valeria olvida su texto, Omar está resfriado y estornuda, y Marcos no ve nada desde dentro del árbol.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué papel tiene Noa en la obra? Elige:", opciones: ["Hace de abuelita.", "Hace de apuntadora: ayuda a los actores a recordar el texto.", "Es la encargada de las luces."], r: "Hace de apuntadora: ayuda a los actores a recordar el texto." },
      { tipo: "comprension", q: "¿Por qué crees que el profesor rompe una hoja del guion y escribe deprisa?", r: "Porque va a cambiar la obra para incluir las ideas de los niños: el lobo resfriado, el árbol que habla y la Caperucita olvidadiza.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo convierte Noa el problema en una solución?", r: "Propone que los fallos formen parte de una obra nueva y más divertida.", lineas: 2 },
      { tipo: "texto", q: "Señala el planteamiento, el nudo y el desenlace de esta escena.", r: "Planteamiento: el último ensayo en el salón de actos. Nudo: los errores (olvidos, estornudos, el árbol que no ve) y el enfado del profesor. Desenlace: deciden hacer una obra nueva con esos fallos.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué harías tú si algo sale mal el día de una función? ¿Por qué?", r: "Respuesta libre. Valorar actitudes como mantener la calma, improvisar o apoyar a los compañeros.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece que la obra nueva será mejor que la original? Explica tu respuesta.", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "A veces los errores dan lugar a buenas ideas. ¿Conoces algún ejemplo en tu vida o en la historia?", r: "Respuesta libre. Valorar ejemplos concretos y la idea de aprender de los errores.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 03
  {
    id: "teatro-03-raton-campo-ciudad",
    titulo: "El ratón de campo y el ratón de ciudad",
    subtipo: "Fábula teatralizada",
    curso: "5º",
    fuente: "Adaptación teatral de la fábula «El ratón de campo y el ratón de ciudad», de Esopo",
    antes: "¿Qué prefieres, vivir en el campo o en la ciudad? ¿Qué ventajas tiene cada lugar?",
    texto: [
      { acot: "Escena primera. Un olivar de Jaén al atardecer. Bajo un olivo hay una madriguera con una mesa hecha con una piedra plana. Sobre ella, unas bellotas y unas migas de pan." },
      { personaje: "NARRADORA", dice: "Había una vez un ratón que vivía feliz entre olivos. Un día recibió la visita de su primo, que vivía en la ciudad." },
      { personaje: "RATÓN DE CAMPO", acot: "abriendo los brazos", dice: "¡Bienvenido, primo! Siéntate, que hoy cenamos bellotas y pan. Y de postre, aire fresco." },
      { personaje: "RATÓN DE CIUDAD", acot: "mirando la mesa con cara de asco", dice: "¿Bellotas? ¿Esto es todo lo que comes? Primo, tú no sabes lo que es vivir bien." },
      { personaje: "RATÓN DE CAMPO", dice: "Yo como poco, pero como tranquilo." },
      { personaje: "RATÓN DE CIUDAD", dice: "Ven conmigo a la ciudad y verás lo que es un banquete de verdad." },
      { acot: "Se apagan las luces. Suena música de ciudad: coches, pitidos, voces." },
      { acot: "Escena segunda. Una cocina enorme. Sobre la mesa hay queso, jamón, pasteles y fruta. Los dos ratones entran de puntillas." },
      { personaje: "RATÓN DE CIUDAD", acot: "orgulloso", dice: "¿Qué te parece? Queso curado, jamón y tarta de chocolate. Sírvete lo que quieras." },
      { personaje: "RATÓN DE CAMPO", acot: "con los ojos muy abiertos", dice: "¡Nunca había visto tanta comida junta!" },
      { acot: "Justo cuando va a morder el queso, se oye un maullido. Entra el GATO BIGOTES, estirándose." },
      { personaje: "GATO BIGOTES", dice: "Mmm… Huele a ratón. Y hoy huele a dos ratones." },
      { personaje: "RATÓN DE CIUDAD", acot: "gritando", dice: "¡Corre, primo, al agujero de la pared!" },
      { acot: "Los ratones huyen. El GATO da un salto y cae sobre la tarta. Se queda con la cara llena de chocolate. Los ratones asoman la cabeza por el agujero, temblando." },
      { personaje: "RATÓN DE CAMPO", dice: "¿Y esto os pasa todos los días?" },
      { personaje: "RATÓN DE CIUDAD", dice: "Casi todos. Pero te acostumbras." },
      { personaje: "RATÓN DE CAMPO", dice: "Pues yo no quiero acostumbrarme. Gracias por la invitación, primo, pero me vuelvo a mi olivo. Prefiero mis bellotas con calma que tus pasteles con miedo." },
      { acot: "El RATÓN DE CAMPO sale por un lateral, con su hatillo al hombro." },
      { personaje: "NARRADORA", dice: "Y así aprendió el ratón de campo que más vale poco y tranquilo que mucho y con sobresaltos." },
      { acot: "Telón." },
    ],
    vocabulario: [
      { p: "madriguera", d: "cueva pequeña donde viven algunos animales." },
      { p: "banquete", d: "comida abundante y especial." },
      { p: "hatillo", d: "pequeño bulto de ropa y cosas atado con un pañuelo." },
      { p: "sobresalto", d: "susto repentino." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿En qué dos lugares transcurre la obra?", r: "En un olivar de Jaén (la madriguera del ratón de campo) y en la cocina de una casa de la ciudad.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué opina el ratón de ciudad de la comida de su primo?", r: "Le parece pobre y poco apetecible: pone cara de asco y dice que su primo no sabe lo que es vivir bien.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el ratón de campo con «Yo como poco, pero como tranquilo»? Elige:", opciones: ["Que está a dieta.", "Que prefiere la tranquilidad a la abundancia.", "Que no le gustan las bellotas."], r: "Que prefiere la tranquilidad a la abundancia." },
      { tipo: "comprension", q: "¿Por qué dice el ratón de ciudad «Pero te acostumbras»? ¿Crees que de verdad está tranquilo?", r: "Porque vive con miedo al gato casi a diario y se ha acostumbrado. No parece tranquilo: también huye y tiembla.", lineas: 2 },
      { tipo: "comprension", q: "Escribe con tus palabras la moraleja de la fábula.", r: "Es mejor vivir con poco y en paz que con muchas cosas pero con miedo o preocupaciones.", lineas: 2 },
      { tipo: "texto", q: "La obra tiene dos escenas. ¿Qué cambia de una a otra? ¿Qué personaje nuevo aparece en la segunda?", r: "Cambia el lugar y el decorado: del olivar a la cocina de la ciudad. En la segunda escena aparece el gato Bigotes.", lineas: 2 },
      { tipo: "opinion", q: "¿Con cuál de los dos ratones estás más de acuerdo? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué papel cumple la narradora? ¿Crees que la obra se entendería sin ella?", r: "Respuesta libre. Valorar que se note que presenta la historia y dice la moraleja.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué cosas sencillas te hacen sentir tranquilo y feliz, aunque no cuesten dinero?", r: "Respuesta libre.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 04
  {
    id: "teatro-04-banco-del-recreo",
    titulo: "El banco del recreo",
    subtipo: "Escena teatral de convivencia",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Recuerdas tu primer día en un sitio nuevo? ¿Cómo te sentiste?",
    texto: [
      { acot: "El patio de un colegio a la hora del recreo. A la derecha, un banco. ÉRIKA, una niña nueva, está sentada sola dibujando en un cuaderno. Al otro lado, CLARA, SAÚL y PAULA hablan con una pelota en la mano." },
      { personaje: "SAÚL", dice: "Oye, ¿habéis visto a la nueva? Lleva tres días sentada en ese banco." },
      { personaje: "PAULA", acot: "encogiéndose de hombros", dice: "Ya. Pero nosotros ya somos tres para jugar. Si viene, hay que cambiar los equipos." },
      { personaje: "CLARA", dice: "Tampoco pasa nada por cambiarlos, Paula." },
      { personaje: "PAULA", dice: "Es que no la conocemos. A lo mejor ni le gusta jugar." },
      { personaje: "SAÚL", dice: "Pues eso tiene fácil solución: preguntárselo." },
      { acot: "SAÚL y CLARA se acercan al banco. PAULA se queda atrás, con los brazos cruzados." },
      { personaje: "CLARA", dice: "Hola. Soy Clara, y este es Saúl. ¿Qué dibujas?" },
      { personaje: "ÉRIKA", acot: "tapando el cuaderno con timidez", dice: "Nada… Un cómic. Me lo invento yo." },
      { personaje: "SAÚL", dice: "¿Un cómic? ¿Nos lo enseñas?" },
      { acot: "ÉRIKA duda un momento y abre el cuaderno. SAÚL y CLARA se sientan a su lado." },
      { personaje: "CLARA", dice: "¡Hala! ¿Esto es una gata astronauta?" },
      { personaje: "ÉRIKA", acot: "sonriendo por primera vez", dice: "Se llama Galaxia. Viaja de planeta en planeta buscando a su familia." },
      { acot: "PAULA se acerca poco a poco, con curiosidad, y mira por encima del hombro de SAÚL." },
      { personaje: "PAULA", dice: "Está muy bien dibujado. ¿Tú sabías dibujar así en tu otro colegio?" },
      { personaje: "ÉRIKA", dice: "Allí teníamos un club de cómic. Aquí todavía no conozco a nadie." },
      { personaje: "PAULA", acot: "algo avergonzada", dice: "Bueno… Ahora nos conoces a nosotros. Perdona por no haberme acercado antes." },
      { personaje: "SAÚL", dice: "¿Y si montamos un club de cómic aquí? Los viernes, en este banco." },
      { personaje: "ÉRIKA", dice: "¿De verdad? ¡Me encantaría! Y otros días puedo jugar a la pelota con vosotros, aunque os aviso de que soy malísima." },
      { personaje: "CLARA", dice: "Da igual. Paula también, y siempre la elegimos." },
      { personaje: "PAULA", acot: "fingiendo que se enfada", dice: "¡Oye!" },
      { acot: "Todos ríen. Suena el timbre. Los cuatro se levantan juntos y salen hablando de Galaxia. El banco queda vacío." },
    ],
    vocabulario: [
      { p: "encogerse de hombros", d: "subir los hombros para mostrar que algo no importa o que no se sabe." },
      { p: "timidez", d: "vergüenza para hablar o relacionarse con los demás." },
      { p: "fingir", d: "hacer como si algo fuera verdad sin serlo." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quién es Érika y qué hace en el recreo al principio de la escena?", r: "Es una niña nueva en el colegio. Está sentada sola en un banco dibujando un cómic.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué no quiere Paula que Érika juegue con ellos?", r: "Porque así tendrían que cambiar los equipos y porque no la conocen.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué propone Saúl para resolver el problema? Elige:", opciones: ["Acusar a Paula ante la maestra.", "Preguntar a Érika si quiere jugar.", "Cambiar de banco."], r: "Preguntar a Érika si quiere jugar." },
      { tipo: "comprension", q: "¿Por qué crees que Paula se acerca «poco a poco» y luego pide perdón?", r: "Porque siente curiosidad por el cómic, le gusta y se da cuenta de que se equivocó al no querer conocer a Érika.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué significa que el banco quede vacío al final?", r: "Que Érika ya no está sola: ahora tiene amigos con los que irse.", lineas: 2 },
      { tipo: "texto", q: "Busca una acotación que indique cómo se siente un personaje. ¿Cómo lo mostraría el actor o la actriz sin palabras?", r: "Por ejemplo: «tapando el cuaderno con timidez» o «sonriendo por primera vez». El actor lo mostraría con gestos, la mirada, la postura o el tono de voz.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué harías tú si vieras a un compañero nuevo solo en el recreo? ¿Por qué?", r: "Respuesta libre. Valorar la empatía y las propuestas concretas.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece bien que Paula pida perdón? ¿Es fácil reconocer que te has equivocado?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué pueden hacer un colegio y una clase para que nadie se sienta solo? Propón dos ideas.", r: "Respuesta libre. Valorar ideas concretas y realistas.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 05
  {
    id: "teatro-05-playa-para-todos",
    titulo: "Una playa para todos",
    subtipo: "Escena teatral sobre medio ambiente",
    curso: "5º",
    fuente: "Texto original",
    antes: "¿Qué tipo de basura has visto alguna vez en una playa, en un río o en el campo?",
    texto: [
      { acot: "Una playa de Huelva, cerca de Doñana, un domingo de junio por la mañana. Hay una sombrilla, dos toallas y un cubo de playa. El ABUELO ANDRÉS lee el periódico. SOFÍA y TEO construyen un castillo de arena." },
      { personaje: "TEO", acot: "sacando algo de la arena", dice: "¡Puaj! Otra tapa de botella. Ya van cinco." },
      { personaje: "SOFÍA", dice: "Y yo he encontrado una pajita y un trozo de bolsa. Este castillo va a tener más plástico que arena." },
      { personaje: "ABUELO ANDRÉS", acot: "doblando el periódico", dice: "Cuando yo tenía vuestra edad, aquí lo que encontrabas eran conchas y cangrejillos." },
      { acot: "Entra LOLA, la socorrista, con su camiseta roja y un silbato al cuello." },
      { personaje: "LOLA", dice: "Buenos días. ¿Qué tenéis ahí, arqueólogos?" },
      { personaje: "TEO", dice: "Basura. La estamos sacando del castillo." },
      { personaje: "LOLA", dice: "Pues hacéis muy bien. El plástico que llega al mar se va rompiendo en trocitos diminutos, tan pequeños que los peces y las aves se los comen sin darse cuenta." },
      { personaje: "SOFÍA", acot: "preocupada", dice: "¿Y eso les hace daño?" },
      { personaje: "LOLA", dice: "Mucho. Por eso cada trocito que recogemos cuenta." },
      { acot: "TEO se levanta de un salto, vacía el cubo de arena y lo levanta como si fuera un trofeo." },
      { personaje: "TEO", dice: "¡Operación Playa Limpia! Abuelo, ¿te apuntas?" },
      { personaje: "ABUELO ANDRÉS", acot: "levantándose despacio", dice: "Con estas rodillas no corro mucho, pero agacharme aún sé." },
      { acot: "Los tres recorren la orilla recogiendo restos. Entra un SEÑOR con sombrero de paja que come pipas y tira las cáscaras a la arena." },
      { personaje: "SOFÍA", acot: "muy educada", dice: "Perdone, señor. ¿Quiere una bolsita para las cáscaras? Estamos haciendo una playa limpia." },
      { personaje: "SEÑOR", acot: "sorprendido, mira el suelo", dice: "Vaya… Pensaba que las cáscaras no eran basura." },
      { personaje: "TEO", dice: "No son plástico, pero tardan en desaparecer, y la arena no es una papelera." },
      { personaje: "SEÑOR", acot: "riendo y cogiendo la bolsa", dice: "Me habéis pillado. Trae, que la próxima vez me traigo mi bolsa de casa." },
      { acot: "Al mediodía, el cubo está lleno. LOLA hace una foto al grupo junto al contenedor." },
      { personaje: "LOLA", dice: "Si cada familia hiciera lo mismo un ratito, esta playa volvería a ser la que conoció tu abuelo." },
      { personaje: "ABUELO ANDRÉS", acot: "guiñando un ojo", dice: "Con conchas, cangrejillos… y sin tapas de botella." },
      { acot: "Telón." },
    ],
    vocabulario: [
      { p: "socorrista", d: "persona que vigila una playa o piscina para ayudar a quien lo necesite." },
      { p: "arqueólogo", d: "persona que estudia restos antiguos que encuentra bajo tierra." },
      { p: "diminuto", d: "muy pequeño." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Dónde y cuándo ocurre la escena? ¿Qué están haciendo Sofía y Teo al principio?", r: "En una playa de Huelva, cerca de Doñana, un domingo de junio por la mañana. Están construyendo un castillo de arena.", lineas: 2 },
      { tipo: "comprension", q: "Según Lola, ¿por qué es peligroso el plástico en el mar?", r: "Porque se rompe en trocitos diminutos que los peces y las aves se comen sin darse cuenta, y eso les hace daño.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Lola llama «arqueólogos» a los niños? Elige:", opciones: ["Porque estudian historia en el colegio.", "Porque están sacando cosas enterradas en la arena.", "Porque llevan sombrero."], r: "Porque están sacando cosas enterradas en la arena." },
      { tipo: "comprension", q: "¿Cómo consigue Sofía que el señor cambie de actitud sin enfadarse?", r: "Le habla con educación y le ofrece una bolsita para las cáscaras, explicándole lo que están haciendo.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir el abuelo con su última frase?", r: "Que ojalá la playa vuelva a estar como en su infancia: con animales y conchas, y sin basura.", lineas: 2 },
      { tipo: "texto", q: "¿Cuántos personajes hay? Si tuvierais que representarla, ¿qué objetos (atrezo) necesitaríais? Busca pistas en las acotaciones.", r: "Cinco personajes: Teo, Sofía, el abuelo Andrés, Lola y el señor. Atrezo: sombrilla, toallas, cubo, periódico, silbato, sombrero de paja, pipas, bolsa, restos de plástico.", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece bien la forma en que Sofía habla al señor? ¿Cómo lo habrías hecho tú?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Participarías en una «Operación Playa Limpia» en tu barrio o pueblo? ¿Dónde la harías y por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "¿Qué podemos hacer en casa y en el colegio para que llegue menos plástico al mar?", r: "Respuesta libre. Valorar propuestas como usar botellas reutilizables, reciclar, evitar pajitas o bolsas de un solo uso.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 06
  {
    id: "teatro-06-biblioteca-medianoche",
    titulo: "La biblioteca a medianoche",
    subtipo: "Escena teatral fantástica",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "Si los libros pudieran hablar, ¿qué crees que nos dirían?",
    texto: [
      { h: "Escena primera" },
      { acot: "La biblioteca del barrio, de noche. Una luz azulada entra por la ventana. MARINA se despierta en un sillón, con un libro abierto sobre las rodillas." },
      { personaje: "MARINA", acot: "frotándose los ojos", dice: "¿Qué hora es? ¡Me he quedado dormida! ¿Y ahora cómo salgo?" },
      { acot: "De una estantería baja sale, muy despacio, un libro gordo y viejo. Es el DICCIONARIO. Lleva gafas redondas y tose polvo." },
      { personaje: "DICCIONARIO", dice: "Cof, cof… Por fin alguien. Hacía años que nadie me abría." },
      { personaje: "MARINA", acot: "dando un bote", dice: "¡Un libro que habla!" },
      { personaje: "DICCIONARIO", dice: "Todos los libros hablan, jovencita. Lo que pasa es que casi nadie escucha." },
      { h: "Escena segunda" },
      { acot: "Entran corriendo el CÓMIC, lleno de colores, y la ENCICLOPEDIA, muy seria, con un puntero." },
      { personaje: "CÓMIC", dice: "¡Eh, Diccionario! ¿Ya estás quejándote otra vez?" },
      { personaje: "ENCICLOPEDIA", dice: "No se queja por gusto. Está perdiendo palabras. Esta semana se le han borrado «zascandil» y «remolonear»." },
      { personaje: "MARINA", dice: "¿Cómo que se le borran?" },
      { personaje: "DICCIONARIO", acot: "abriendo sus páginas con tristeza", dice: "Las palabras que nadie usa se van quedando en blanco, como fotos viejas. Mira: aquí ponía «ojalá» y ya casi no se lee." },
      { personaje: "MARINA", dice: "¡Pero «ojalá» es preciosa! Mi abuela la dice mucho." },
      { acot: "Al oírla, las letras de «ojalá» brillan y vuelven a verse en la página." },
      { personaje: "CÓMIC", dice: "¡Ha funcionado! Cuando alguien dice una palabra en voz alta, recupera la tinta." },
      { personaje: "ENCICLOPEDIA", dice: "Entonces necesitamos a alguien que lea mucho y hable todavía más." },
      { personaje: "MARINA", acot: "sonriendo", dice: "Pues habéis encontrado a la persona perfecta. En clase dicen que no me callo ni debajo del agua." },
      { acot: "MARINA empieza a leer en voz alta. Una a una, las páginas del DICCIONARIO se llenan de letras brillantes." },
      { h: "Escena tercera" },
      { acot: "Por la mañana. Los libros están quietos en sus estanterías. Entra la BIBLIOTECARIA con las llaves en la mano." },
      { personaje: "BIBLIOTECARIA", acot: "sorprendida", dice: "¡Marina! ¿Has pasado aquí la noche? Tus padres te estarán buscando." },
      { personaje: "MARINA", dice: "Lo siento, me quedé dormida. ¿Puedo llevarme este libro, por favor?" },
      { personaje: "BIBLIOTECARIA", dice: "¿El diccionario? Nunca nadie me lo había pedido." },
      { acot: "Cuando MARINA sale abrazada al libro, el DICCIONARIO guiña un ojo al público. Oscuro." },
    ],
    vocabulario: [
      { p: "zascandil", d: "persona inquieta y enredadora que va de un lado a otro sin hacer nada útil." },
      { p: "remolonear", d: "hacerse el perezoso para no hacer algo o no levantarse." },
      { p: "puntero", d: "palo largo y fino que se usa para señalar en una pizarra o un mapa." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Por qué está Marina en la biblioteca de noche?", r: "Porque se quedó dormida leyendo en un sillón y nadie se dio cuenta al cerrar.", lineas: 1 },
      { tipo: "comprension", q: "¿Qué problema tiene el Diccionario?", r: "Está perdiendo las palabras que nadie usa: se le borran de las páginas.", lineas: 2 },
      { tipo: "comprension", q: "¿Cómo se recuperan las palabras? Elige:", opciones: ["Escribiéndolas con tinta nueva.", "Diciéndolas en voz alta.", "Guardando el libro en un lugar seco."], r: "Diciéndolas en voz alta." },
      { tipo: "comprension", q: "¿Por qué Marina es «la persona perfecta» para ayudar a los libros?", r: "Porque le gusta leer y habla mucho: «no se calla ni debajo del agua», así que usará muchas palabras.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué nos quiere decir el autor con la idea de que las palabras que nadie usa se borran?", r: "Que las palabras viven mientras las usamos; si las olvidamos, el idioma se empobrece.", lineas: 2 },
      { tipo: "texto", q: "La obra se divide en tres escenas. ¿Qué ocurre para que empiece la escena segunda? ¿Y la tercera?", r: "La escena segunda empieza cuando entran nuevos personajes, el Cómic y la Enciclopedia. La tercera, cuando cambia el tiempo (por la mañana) y entra la bibliotecaria.", lineas: 3 },
      { tipo: "opinion", q: "¿Qué palabra te gustaría salvar del olvido? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Te gustaría pasar una noche en una biblioteca? ¿Qué libro elegirías para que cobrara vida?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "Piensa en palabras que usan tus abuelos y tú no. ¿Por qué crees que algunas palabras se dejan de usar?", r: "Respuesta libre. Valorar referencias a los cambios en la forma de vida, los objetos o las costumbres.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 07
  {
    id: "teatro-07-desconectados",
    titulo: "Desconectados",
    subtipo: "Comedia familiar",
    curso: "5º-6º",
    fuente: "Texto original",
    antes: "¿Qué harías en casa una tarde entera sin internet ni televisión?",
    texto: [
      { acot: "El salón de una casa, una tarde de tormenta. Cada uno está con su pantalla: LEO, con la consola; VERA, con la tableta; PAPÁ, con el ordenador. La ABUELA CARMEN hace punto en una mecedora. Se oye un trueno y, de repente, se apagan todas las luces." },
      { personaje: "LEO", acot: "gritando", dice: "¡Nooo! ¡Estaba a punto de pasarme el nivel!" },
      { personaje: "VERA", dice: "¡Y yo estaba viendo el final del vídeo!" },
      { personaje: "PAPÁ", dice: "Tranquilos. Será un momento. Voy a mirar los plomos." },
      { acot: "PAPÁ sale con una linterna. Vuelve enseguida." },
      { personaje: "PAPÁ", dice: "Es todo el barrio. Nos hemos quedado sin luz… y sin internet." },
      { personaje: "LEO", acot: "tirándose en el sofá de forma exagerada", dice: "Esto es el fin de la civilización." },
      { personaje: "ABUELA CARMEN", acot: "sin dejar de hacer punto", dice: "Pues yo sigo tejiendo igual. El punto no necesita enchufe." },
      { acot: "La ABUELA enciende unas velas. Se hace el silencio. Solo se oye la lluvia." },
      { personaje: "VERA", dice: "¿Y qué hacíais vosotros cuando se iba la luz, abuela?" },
      { personaje: "ABUELA CARMEN", dice: "Contábamos historias, jugábamos a las adivinanzas o hacíamos sombras chinescas en la pared. Mirad." },
      { acot: "La ABUELA pone las manos delante de una vela. En la pared aparece la sombra de un perro que abre la boca." },
      { personaje: "VERA", acot: "fascinada", dice: "¡Un perro! ¿Cómo lo haces?" },
      { personaje: "PAPÁ", dice: "Yo sabía hacer un conejo. A ver si me acuerdo…" },
      { acot: "PAPÁ lo intenta. En la pared aparece algo raro, con tres orejas." },
      { personaje: "LEO", acot: "riendo a carcajadas", dice: "¡Eso es un conejo extraterrestre!" },
      { personaje: "ABUELA CARMEN", dice: "Os propongo un juego: cada uno inventa un animal con sombras y los demás lo adivinan." },
      { acot: "Durante un buen rato, la familia juega. Se oyen risas, gritos de «¡un pato!» y «¡no, es una jirafa!». De pronto, vuelve la luz. Nadie se da cuenta." },
      { personaje: "VERA", dice: "Me toca. Adivinad: tiene cuello largo, cuernos pequeños…" },
      { personaje: "PAPÁ", dice: "Eh… chicos. Ha vuelto la luz." },
      { acot: "Todos miran las pantallas encendidas. Silencio. LEO se acerca a la lámpara y la apaga." },
      { personaje: "LEO", dice: "Solo una ronda más, ¿vale?" },
      { personaje: "ABUELA CARMEN", acot: "sonriendo mientras enciende otra vela", dice: "Ya decía yo que la civilización no se había acabado." },
      { acot: "Oscuro final." },
    ],
    vocabulario: [
      { p: "plomos", d: "fusibles de la instalación eléctrica de una casa, que cortan la luz si hay un problema." },
      { p: "sombras chinescas", d: "figuras que se forman con las manos delante de una luz y se proyectan en una pared." },
      { p: "civilización", d: "forma de vida de una sociedad, con sus avances y costumbres." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Qué están haciendo los personajes al principio y qué ocurre de repente?", r: "Cada uno está con una pantalla (consola, tableta, ordenador) y la abuela hace punto. Por la tormenta se va la luz en todo el barrio.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la abuela es la única que no se preocupa por el apagón?", r: "Porque su actividad, hacer punto, no necesita electricidad, y sabe entretenerse sin pantallas.", lineas: 2 },
      { tipo: "comprension", q: "Leo dice: «Esto es el fin de la civilización». ¿Cómo lo dice? Elige:", opciones: ["En serio, porque está asustado.", "Exagerando, para hacer gracia.", "Enfadado con su padre."], r: "Exagerando, para hacer gracia." },
      { tipo: "comprension", q: "¿Por qué Leo apaga la lámpara al final?", r: "Porque se lo están pasando tan bien con las sombras que quiere seguir jugando una ronda más.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir la abuela con su última frase?", r: "Que Leo exageraba: la familia ha descubierto que puede divertirse junta sin pantallas.", lineas: 2 },
      { tipo: "texto", q: "Las acotaciones indican sonidos y luces. Copia dos y explica cómo se harían en una representación en clase.", r: "Por ejemplo: «Se oye un trueno» (con un audio o agitando una lámina de metal) y «se apagan todas las luces» (apagando las luces del aula). También «En la pared aparece la sombra de un perro» (con una linterna).", lineas: 3 },
      { tipo: "opinion", q: "¿Crees que pasamos demasiado tiempo con pantallas? Da una razón.", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Qué juego sin pantallas le enseñarías a tu familia? ¿Por qué ese?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Qué pueden aprender los niños de sus abuelos y qué pueden aprender los abuelos de los niños?", r: "Respuesta libre. Valorar la idea de aprendizaje mutuo entre generaciones.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 08
  {
    id: "teatro-08-asamblea-pista",
    titulo: "La asamblea de la pista",
    subtipo: "Obra breve de convivencia en dos escenas",
    curso: "6º",
    fuente: "Texto original",
    antes: "¿Cómo se reparten los espacios del patio en tu colegio? ¿Te parece justo?",
    texto: [
      { h: "Escena primera" },
      { acot: "El patio del colegio. En la pista, HUGO bota un balón de fútbol. ALBA llega con una pelota de baloncesto y YERAY con una comba." },
      { personaje: "ALBA", dice: "Hugo, ¿nos dejáis media pista hoy? Queremos jugar al baloncesto." },
      { personaje: "HUGO", acot: "sin dejar de botar el balón", dice: "Imposible. Estamos a mitad de la liga del recreo." },
      { personaje: "YERAY", dice: "Llevas diciendo lo mismo desde septiembre. Ya estamos en marzo." },
      { personaje: "HUGO", dice: "Haber llegado antes. El que primero llega, primero juega." },
      { personaje: "ALBA", acot: "enfadada", dice: "¡Si salís corriendo antes de que suene el timbre!" },
      { acot: "Suena el timbre. Todos salen discutiendo en voz alta." },
      { h: "Escena segunda" },
      { acot: "El aula de sexto, esa tarde. Las mesas están en círculo. La TUTORA MERCEDES está sentada con los alumnos. CANDELA, la delegada, tiene un cuaderno de actas." },
      { personaje: "CANDELA", dice: "Empieza la asamblea. Tema: el uso de la pista del patio. Recuerdo las normas: se pide la palabra levantando la mano y no se interrumpe. Alba, tienes la palabra." },
      { personaje: "ALBA", dice: "La pista es de todos, pero siempre la usan los mismos. A muchos nos gustan otros juegos y no tenemos sitio." },
      { personaje: "HUGO", acot: "levanta la mano y espera", dice: "Nosotros no lo hacemos con mala intención. Es que el fútbol necesita mucho espacio." },
      { personaje: "YERAY", dice: "La comba también necesita espacio. Y el baloncesto." },
      { personaje: "TUTORA MERCEDES", dice: "Buenos argumentos por las dos partes. ¿Alguien tiene una propuesta?" },
      { personaje: "CANDELA", dice: "Yo propongo un calendario. Lunes y miércoles, fútbol. Martes y jueves, baloncesto y juegos de comba. Y los viernes, juego libre para todos, mezclados." },
      { personaje: "HUGO", acot: "pensativo", dice: "Solo dos días de fútbol… Bueno, los otros días podríamos probar el baloncesto. Yeray dice que es fácil." },
      { personaje: "YERAY", acot: "sonriendo", dice: "Y yo te enseño a saltar a la comba. Eso sí que es difícil." },
      { personaje: "CANDELA", dice: "Votamos. ¿Quién está a favor del calendario?" },
      { acot: "Casi todas las manos se levantan. Poco a poco, también la de HUGO." },
      { personaje: "CANDELA", acot: "escribiendo en el cuaderno", dice: "Aprobado. Lo probaremos un mes y después lo revisaremos en otra asamblea." },
      { personaje: "TUTORA MERCEDES", dice: "Hoy habéis hecho algo muy importante: resolver un conflicto hablando." },
      { personaje: "HUGO", dice: "Y sin que nadie saliera corriendo antes del timbre." },
      { acot: "Risas. Telón." },
    ],
    vocabulario: [
      { p: "asamblea", d: "reunión de un grupo para hablar y tomar decisiones entre todos." },
      { p: "delegada", d: "alumna elegida para representar a su clase." },
      { p: "acta", d: "escrito donde se anota lo que se ha hablado y decidido en una reunión." },
      { p: "argumento", d: "razón que se da para defender una opinión." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Cuál es el conflicto de la obra?", r: "Que la pista del patio siempre la usan los que juegan al fútbol y los demás no pueden jugar a otros juegos.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué quiere decir Yeray con «Llevas diciendo lo mismo desde septiembre. Ya estamos en marzo»?", r: "Que Hugo pone siempre la misma excusa y que el problema dura desde hace meses.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué hace Hugo en la asamblea que demuestra que respeta las normas? Elige:", opciones: ["Grita más que los demás.", "Levanta la mano y espera su turno.", "Se va del aula."], r: "Levanta la mano y espera su turno." },
      { tipo: "comprension", q: "Explica la propuesta de Candela.", r: "Un calendario: lunes y miércoles, fútbol; martes y jueves, baloncesto y comba; viernes, juego libre para todos.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la última frase de Hugo hace reír a todos?", r: "Porque recuerda con humor lo que Alba le reprochó en la primera escena: que salían corriendo antes del timbre. Demuestra que ha cambiado de actitud.", lineas: 2 },
      { tipo: "texto", q: "¿En qué se diferencian las dos escenas (lugar, tiempo y personajes)? ¿Por qué crees que el autor la ha dividido así?", r: "La primera ocurre en el patio, en el recreo, sin la tutora ni Candela; la segunda, en el aula por la tarde, con la tutora y la delegada. Se divide así para separar el conflicto (nudo) de su solución (desenlace).", lineas: 3 },
      { tipo: "opinion", q: "¿Te parece justa la solución del calendario? ¿Cambiarías algo?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Crees que las asambleas de clase son útiles? ¿Por qué?", r: "Respuesta libre.", lineas: 3 },
      { tipo: "reflexion", q: "La tutora dice que han resuelto un conflicto «hablando». ¿Qué otros conflictos de tu entorno podrían resolverse así?", r: "Respuesta libre. Valorar ejemplos concretos y la importancia del diálogo.", lineas: 3 },
    ],
  },

  // ------------------------------------------------------------------ 09
  {
    id: "teatro-09-cadiz-1812",
    titulo: "Una mañana de marzo en Cádiz",
    subtipo: "Escena teatral histórica",
    curso: "6º",
    fuente: "Texto original basado en hechos históricos (Cádiz, 19 de marzo de 1812)",
    datos: ["Biblioteca Virtual Miguel de Cervantes: portal «La Constitución española de 1812»", "Archivos de Castilla y León: «La Constitución de 1812»", "Fundación Legado de las Cortes: «Asedio del ejército napoleónico a Cádiz»", "Turismo de San Fernando: «La Isla de las Cortes»"],
    antes: "¿Sabes qué es una constitución? ¿Por qué crees que es importante para un país?",
    texto: [
      { acot: "Cádiz, 19 de marzo de 1812, día de San José. Una calle estrecha cerca del Oratorio de San Felipe Neri. Se oye a lo lejos el mar y, de vez en cuando, un cañonazo. PEPA y su hermano JOSÉ, de unos once años, llevan una cesta de pescado. DOÑA TERESA, la vecina costurera, cose en la puerta de su casa." },
      { personaje: "DOÑA TERESA", dice: "¡Felicidades, José! Hoy es tu santo." },
      { personaje: "JOSÉ", dice: "Gracias, doña Teresa. Pero hoy nadie se acuerda de mí. Todo el mundo va hacia San Felipe." },
      { acot: "Suena un cañonazo lejano. PEPA ni se inmuta." },
      { personaje: "PEPA", dice: "Otra bomba de los franceses. Llevan dos años rodeando la ciudad, pero muchas bombas caen al agua." },
      { personaje: "DOÑA TERESA", acot: "riendo", dice: "Ya lo dice la copla: con las bombas que tiran los fanfarrones, se hacen las gaditanas tirabuzones." },
      { personaje: "JOSÉ", dice: "Doña Teresa, ¿por qué hay tanta gente en la calle?" },
      { personaje: "DOÑA TERESA", acot: "dejando la aguja", dice: "Porque los diputados de las Cortes han terminado su trabajo. Han venido de muchos lugares de España y de América, y llevan más de un año reuniéndose ahí, en San Felipe Neri." },
      { personaje: "PEPA", dice: "¿Y qué han hecho?" },
      { personaje: "DOÑA TERESA", dice: "Una constitución. Un libro de leyes que está por encima de todos, hasta del rey." },
      { personaje: "JOSÉ", acot: "sorprendido", dice: "¿Por encima del rey?" },
      { personaje: "DOÑA TERESA", dice: "Dice que el poder pertenece a la nación, es decir, a la gente. Que quien hace las leyes no es el mismo que las aplica ni el mismo que juzga. Y que se podrá escribir e imprimir lo que uno piensa." },
      { acot: "Entra un PREGONERO con un papel enrollado. Se detiene en el centro y toca una campanilla." },
      { personaje: "PREGONERO", dice: "¡Oíd, vecinos de Cádiz! ¡Hoy se proclama la Constitución Política de la Monarquía Española! ¡Acudid a la plaza!" },
      { acot: "Se oyen aplausos y gritos de alegría fuera del escenario. PEPA tira de la manga de su hermano." },
      { personaje: "PEPA", dice: "José, como hoy es San José, la gente ya la está llamando «la Pepa»." },
      { personaje: "JOSÉ", acot: "fingiendo que se ofende", dice: "¡Anda ya! ¿Mi santo y le ponen tu nombre?" },
      { personaje: "DOÑA TERESA", dice: "Pues a los dos os toca cuidarla. Una ley en un papel no sirve de nada si la gente no la defiende." },
      { acot: "Los tres salen hacia la plaza. Se oye el último cañonazo, y después, solo aplausos." },
    ],
    vocabulario: [
      { p: "constitución", d: "ley principal de un país, que organiza cómo se gobierna y reconoce los derechos de las personas." },
      { p: "Cortes", d: "reunión de representantes que hacen las leyes." },
      { p: "fanfarrón", d: "persona que presume de lo que no es o no hace." },
      { p: "tirabuzón", d: "rizo de pelo largo en forma de espiral." },
      { p: "pregonero", d: "persona que anunciaba noticias en voz alta por las calles." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Dónde y cuándo ocurre la escena? ¿Qué situación vivía la ciudad?", r: "En Cádiz, el 19 de marzo de 1812. La ciudad estaba rodeada (sitiada) por el ejército francés, que la bombardeaba.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Pepa no se asusta con los cañonazos?", r: "Porque llevan dos años oyéndolos y muchas bombas caen al agua sin hacer daño.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué la Constitución se llamó popularmente «la Pepa»? Elige:", opciones: ["Porque la escribió una mujer llamada Pepa.", "Porque se proclamó el día de San José, y a los José se les llama Pepe.", "Porque era el nombre de la plaza."], r: "Porque se proclamó el día de San José, y a los José se les llama Pepe." },
      { tipo: "comprension", q: "¿Qué ideas nuevas de la Constitución explica doña Teresa?", r: "Que el poder pertenece a la nación (a la gente), que se separan los poderes de hacer leyes, aplicarlas y juzgar, y que hay libertad para escribir e imprimir las propias ideas.", lineas: 3 },
      { tipo: "comprension", q: "¿Qué quiere decir la copla sobre las bombas y los tirabuzones?", r: "Que los gaditanos se reían de los franceses porque sus bombas no conseguían asustarlos: con humor, dicen que solo sirven para rizarse el pelo.", lineas: 2 },
      { tipo: "texto", q: "¿Qué información da la primera acotación? ¿Por qué es tan importante en una obra histórica?", r: "Indica el lugar (una calle de Cádiz cerca de San Felipe Neri), la fecha (19 de marzo de 1812), los sonidos (mar y cañonazos) y los personajes. Es importante porque sitúa al público en la época y el lugar.", lineas: 3 },
      { tipo: "opinion", q: "Doña Teresa dice que una ley no sirve si la gente no la defiende. ¿Estás de acuerdo? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "Hoy tenemos la Constitución de 1978. ¿Qué derecho te parece más importante para los niños y las niñas? Explica por qué.", r: "Respuesta libre. Valorar que se argumente (educación, igualdad, libertad de expresión…).", lineas: 3 },
      { tipo: "opinion", q: "¿Te gustaría vivir en la época de la escena? ¿Qué te llamaría más la atención?", r: "Respuesta libre.", lineas: 2 },
    ],
  },

  // ------------------------------------------------------------------ 10
  {
    id: "teatro-10-retablo-maravillas",
    titulo: "El retablo de las maravillas",
    subtipo: "Entremés",
    curso: "6º",
    fuente: "Adaptación libre del entremés «El retablo de las maravillas», de Miguel de Cervantes (1615). Se ha cambiado la condición original para ver las maravillas por otra adecuada a la edad.",
    antes: "¿Alguna vez has dicho que veías o entendías algo solo para no quedar mal delante de los demás?",
    texto: [
      { acot: "La plaza de un pueblo de Castilla. Hay un pequeño teatrillo cubierto con una tela. CHANFALLA y CHIRINOS, dos pícaros que van de pueblo en pueblo, hablan con el alcalde BENITO REPOLLO, el escribano PEDRO CAPACHO y la vecina JUANA CASTRADA." },
      { personaje: "CHANFALLA", dice: "Señor alcalde, este es el famoso Retablo de las Maravillas. Lo construyó un sabio y dentro aparecen figuras asombrosas." },
      { personaje: "CHIRINOS", acot: "en voz baja, al público", dice: "Tan asombrosas que ni nosotros las hemos visto nunca." },
      { personaje: "CHANFALLA", dice: "Pero tiene un secreto: las maravillas solo las pueden ver las personas listas. Quien no sea listo, no verá nada." },
      { personaje: "BENITO REPOLLO", acot: "hinchando el pecho", dice: "Entonces yo lo veré todo. En este pueblo no hay nadie más listo que su alcalde." },
      { personaje: "PEDRO CAPACHO", dice: "Ni que su escribano." },
      { personaje: "JUANA CASTRADA", dice: "Ni que yo, que sé leer y hacer cuentas." },
      { acot: "CHIRINOS cobra a cada uno una moneda. CHANFALLA quita la tela del teatrillo. Dentro no hay absolutamente nada." },
      { personaje: "CHANFALLA", acot: "con voz solemne", dice: "¡Contemplad! ¡Por ahí sale un toro bravo!" },
      { personaje: "JUANA CASTRADA", acot: "dando un salto hacia atrás", dice: "¡Ay, qué cuernos! ¡Que me pilla!" },
      { personaje: "PEDRO CAPACHO", acot: "mirando fijamente el teatrillo vacío, en voz baja", dice: "Yo no veo nada… Pero si lo digo, pensarán que no soy listo." },
      { personaje: "PEDRO CAPACHO", acot: "en voz alta", dice: "¡Qué toro tan hermoso! ¡Mirad qué patas!" },
      { personaje: "CHANFALLA", dice: "¡Y ahora, una manada de ratones!" },
      { acot: "JUANA se sube a una silla. BENITO REPOLLO se sacude las piernas como si le subieran ratones." },
      { personaje: "BENITO REPOLLO", dice: "¡Fuera, bichos! ¡Que me hacen cosquillas!" },
      { acot: "Entra un FURRIER, un soldado encargado de buscar alojamiento para su tropa." },
      { personaje: "FURRIER", dice: "¿Quién es el alcalde? Esta noche llegan treinta soldados y necesitan dónde dormir." },
      { personaje: "BENITO REPOLLO", acot: "riendo", dice: "¡Otra figura del retablo! ¡Qué bien hecha está! Parece de verdad." },
      { personaje: "FURRIER", acot: "desconcertado", dice: "¿Figura? ¡Soy un soldado de carne y hueso!" },
      { personaje: "JUANA CASTRADA", dice: "Qué bien habla este muñeco. Se nota que somos muy listos, porque lo vemos perfectamente." },
      { personaje: "FURRIER", acot: "mirando dentro del teatrillo", dice: "¿Pero qué miran ustedes? ¡Ahí dentro no hay nada!" },
      { acot: "Silencio. Todos se miran. Nadie se atreve a hablar." },
      { personaje: "CHIRINOS", acot: "guardando las monedas", dice: "Chanfalla, creo que es buen momento para irnos." },
      { acot: "Los dos pícaros salen corriendo con el dinero mientras los vecinos siguen discutiendo. Telón." },
    ],
    vocabulario: [
      { p: "entremés", d: "obra de teatro breve y cómica que se representaba entre los actos de otra obra más larga." },
      { p: "retablo", d: "aquí, pequeño teatro portátil de figuras." },
      { p: "pícaro", d: "persona astuta que engaña a otros para sacar provecho." },
      { p: "escribano", d: "persona encargada de escribir y dar fe de documentos oficiales." },
      { p: "furrier", d: "soldado que se encargaba de buscar alojamiento y comida para la tropa." },
    ],
    preguntas: [
      { tipo: "comprension", q: "¿Quiénes son Chanfalla y Chirinos y qué pretenden?", r: "Son dos pícaros que van de pueblo en pueblo. Quieren cobrar a los vecinos por ver un retablo que, en realidad, está vacío.", lineas: 2 },
      { tipo: "comprension", q: "¿Cuál es el truco que usan para engañar a los vecinos?", r: "Dicen que solo las personas listas pueden ver las maravillas, así que nadie se atreve a reconocer que no ve nada.", lineas: 2 },
      { tipo: "comprension", q: "¿Por qué Pedro Capacho dice que ve un toro si no ve nada? Elige:", opciones: ["Porque tiene mucha imaginación.", "Porque le da miedo que piensen que no es listo.", "Porque Chirinos le ha pagado."], r: "Porque le da miedo que piensen que no es listo." },
      { tipo: "comprension", q: "¿Por qué los vecinos creen que el furrier es una figura del retablo?", r: "Porque están tan metidos en el engaño que todo lo que aparece les parece parte del espectáculo.", lineas: 2 },
      { tipo: "comprension", q: "¿Qué crees que pasará después con los vecinos y con los pícaros?", r: "Respuesta abierta coherente: los vecinos se darán cuenta del engaño y se sentirán avergonzados; los pícaros escaparán con el dinero.", lineas: 2 },
      { tipo: "texto", q: "Algunas acotaciones dicen «al público» o «en voz baja». ¿Para qué sirven? ¿Cómo lo representarías en clase?", r: "Indican que el personaje dice algo que los demás personajes no oyen, solo el público (un aparte). Se representaría girándose hacia el público, bajando la voz o tapándose la boca con la mano.", lineas: 3 },
      { tipo: "opinion", q: "¿Por qué crees que nadie se atreve a decir que no ve nada? ¿Qué habrías hecho tú?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "opinion", q: "¿Te parece que esta obra, escrita hace más de 400 años, sigue siendo divertida hoy? ¿Por qué?", r: "Respuesta libre.", lineas: 2 },
      { tipo: "reflexion", q: "¿Conoces situaciones actuales en las que la gente hace o dice algo solo por miedo a quedar mal? Pon un ejemplo.", r: "Respuesta libre. Valorar ejemplos como modas, redes sociales o presión del grupo, y la importancia de pensar por uno mismo.", lineas: 3 },
    ],
  },
];
