// La Ciudadela · sesiones del bloque 2 (y 3): Lo que me digo · La pausa
window.CIUDADELA_NUEVAS = (window.CIUDADELA_NUEVAS || []).concat([
  // ---------------- Bloque 2 · Lo que me digo ----------------
  {
    bloque: 2,
    virtud: "sabiduria",
    titulo: "La etiqueta que me pego",
    historia: "Hugo sale a la pizarra a resolver una división y se equivoca en la última resta. Vuelve a su sitio con la cara ardiendo y escribe en una esquina del cuaderno: «Soy tonto». En toda la mañana no vuelve a levantar la mano, ni siquiera en Ciencias, que es lo que más le gusta.",
    pregunta: "¿Una resta equivocada dice cómo es Hugo entero? ¿Qué frase más justa podría escribir en esa esquina del cuaderno?",
    juego: {
      consigna: "¿Es un hecho o es lo que Hugo se dice?",
      tipo: "HECHO",
      items: [
        { t: "Se equivocó en la última resta", r: "si" },
        { t: "Soy tonto", r: "no" },
        { t: "El resto de la división estaba bien", r: "si" },
        { t: "Nunca voy a entender las divisiones", r: "no" },
        { t: "Toda la clase piensa que no sé nada", r: "no" },
        { t: "No ha vuelto a levantar la mano", r: "si" },
      ],
    },
    idea: "Un error es algo que haces, no algo que eres. Las etiquetas como «soy tonto» se pegan muy fácil y cuesta mucho despegarlas.",
    frase: { t: "Mira dentro de ti. Dentro está la fuente del bien, y siempre puede brotar si sigues cavando.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 59" },
    reto: "Si hoy te pillas diciendo «soy…» después de un error, cámbialo por «me he equivocado en…».",
  },
  {
    bloque: 2,
    virtud: "sabiduria",
    titulo: "Siempre, nunca, todo, nada",
    historia: "La maestra sortea quién se llevará a casa el hámster de la clase este fin de semana, y sale el nombre de Bruno. Aitana resopla y protesta en voz alta: «Nunca me toca nada. Siempre les toca a los mismos». Bruno se gira y le recuerda que hace dos semanas ella fue la encargada de la biblioteca de aula.",
    pregunta: "¿Qué le pasa a un pensamiento cuando lleva dentro un «siempre» o un «nunca»? ¿Cómo podría decirlo Aitana de forma más exacta?",
    juego: {
      consigna: "¿Es un hecho o es lo que Aitana se dice?",
      tipo: "HECHO",
      items: [
        { t: "Hoy no ha salido su nombre en el sorteo", r: "si" },
        { t: "Nunca me toca nada", r: "no" },
        { t: "Hace dos semanas fue encargada de la biblioteca", r: "si" },
        { t: "Siempre les toca a los mismos", r: "no" },
        { t: "Se ha sentido decepcionada", r: "si", x: "La decepción es real y vale. Lo que no es un hecho es el «nunca»." },
        { t: "La maestra hace trampas en el sorteo", r: "no" },
      ],
    },
    idea: "«Siempre» y «nunca» casi nunca son verdad. Cambiarlos por «esta vez» hace que un mal momento pese solo lo que pesa de verdad.",
    frase: { t: "¡Cuánto más daño nos hacen el enfado y el disgusto que las cosas que los provocan!", autor: "Marco Aurelio", obra: "Meditaciones, XI, 18" },
    reto: "Hoy caza un «siempre» o un «nunca» en lo que dices y cámbialo por «hoy» o «esta vez».",
  },
  {
    bloque: 2,
    virtud: "sabiduria",
    titulo: "Adivinos sin bola de cristal",
    historia: "Youssef está explicando su mural sobre los volcanes. A mitad de la exposición, el maestro frunce el ceño y apunta algo en su libreta. Youssef se pone nervioso, se salta dos partes y piensa: «Lo estoy haciendo fatal. Me va a suspender». Al terminar, el maestro le dice que había apuntado una pregunta para hacerle, porque le había interesado mucho.",
    pregunta: "¿Qué sabía Youssef de verdad y qué estaba adivinando? ¿Os ha pasado alguna vez creer que sabíais lo que pensaba otra persona?",
    juego: {
      consigna: "¿Es real o se lo imagina Youssef?",
      tipo: "REAL",
      items: [
        { t: "El maestro frunció el ceño", r: "si" },
        { t: "El maestro apuntó algo en su libreta", r: "si" },
        { t: "Lo estoy haciendo fatal", r: "no" },
        { t: "Al maestro no le gusta mi mural", r: "no" },
        { t: "Se saltó dos partes por los nervios", r: "si" },
        { t: "Me va a suspender", r: "no" },
      ],
    },
    idea: "Nadie puede leer la mente. Cuando creas saber lo que otro piensa de ti, recuerda que es una suposición y, si puedes, pregunta.",
    frase: { t: "Si no está bien, no lo hagas. Si no es verdad, no lo digas.", autor: "Marco Aurelio", obra: "Meditaciones, XII, 17" },
    reto: "Si hoy crees saber lo que alguien piensa de ti, pregúntaselo con amabilidad en vez de adivinar.",
  },
  {
    bloque: 2,
    virtud: "sabiduria",
    titulo: "La bola de nieve",
    historia: "Al volver de la excursión al parque, Valentina se da cuenta de que ha perdido la sudadera nueva. En el autobús su cabeza no para: «Mi padre se va a enfadar muchísimo, me dejará un mes sin tablet, no me dejarán ir a más excursiones…». Cuando llega a casa, está tan agobiada que casi no puede ni contarlo.",
    pregunta: "¿Cómo ha ido creciendo la preocupación de Valentina, como una bola de nieve? ¿Qué es lo más probable que pase de verdad?",
    juego: {
      consigna: "¿Es real o se lo imagina Valentina?",
      tipo: "REAL",
      items: [
        { t: "Ha perdido la sudadera nueva", r: "si" },
        { t: "Está muy agobiada", r: "si" },
        { t: "Su padre se va a enfadar muchísimo", r: "no" },
        { t: "La dejarán un mes sin tablet", r: "no" },
        { t: "No podrá ir a más excursiones", r: "no" },
        { t: "Mañana puede preguntar en objetos perdidos", r: "si", x: "Es una posibilidad real, y además está en su mano." },
      ],
    },
    idea: "Cuando un pensamiento arrastra a otro peor, para la bola de nieve y pregúntate: ¿qué es lo más probable?, ¿qué puedo hacer ya?",
    frase: { t: "¿Qué hay que hacer, entonces? Sacar el mejor partido de lo que depende de nosotros, y tomar lo demás como venga.", autor: "Epicteto", obra: "Disertaciones, I, 1" },
    reto: "Si hoy te preocupa algo, piensa lo peor, lo mejor y lo más probable. ¿Cuál es más realista?",
  },
  {
    bloque: 2,
    virtud: "sabiduria",
    titulo: "¿Contra quién compito?",
    historia: "En Educación Física cronometran los sesenta metros. Mateo hace once segundos; en septiembre hizo doce. Pero Pau, su mejor amigo, ha hecho nueve, y Mateo se sienta en el banco pensando: «Soy lentísimo. No valgo para correr». Ni siquiera escucha a la maestra cuando le lee su tiempo de septiembre.",
    pregunta: "¿Con quién se está comparando Mateo? ¿Qué vería si se comparara con el Mateo de septiembre?",
    juego: {
      consigna: "¿Es un hecho o es lo que Mateo se dice?",
      tipo: "HECHO",
      items: [
        { t: "Ha corrido los sesenta metros en once segundos", r: "si" },
        { t: "Ha mejorado un segundo desde septiembre", r: "si" },
        { t: "Pau ha corrido más rápido que él", r: "si" },
        { t: "Soy lentísimo", r: "no" },
        { t: "No valgo para correr", r: "no" },
        { t: "Si Pau corre más, yo valgo menos", r: "no" },
      ],
    },
    idea: "Compararte con los demás te dice muy poco. Compárate con quien eras antes: ahí se ve todo lo que has avanzado.",
    frase: { t: "Cada capacidad crece con la práctica: se aprende a caminar caminando y a correr corriendo.", autor: "Epicteto", obra: "Disertaciones, II, 18" },
    reto: "Busca hoy algo que hagas mejor que hace un mes y cuéntaselo a alguien.",
  },
  {
    bloque: 2,
    virtud: "templanza",
    titulo: "Perfecto o nada",
    historia: "Chen tiene que entregar mañana un trabajo sobre los ríos de Andalucía. Ya ha hecho la portada cuatro veces: una letra torcida, un borrón pequeñito, un color que no le convence… Son las diez de la noche, el trabajo sigue sin empezar y Chen tiene ganas de llorar: «Si no me sale perfecto, no lo entrego».",
    pregunta: "¿Qué gana Chen repitiendo la portada? ¿Qué está perdiendo? ¿Dónde estaría el punto justo?",
    juego: {
      consigna: "¿Se pasa, se queda corto o es el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Repetir la portada por un borrón pequeñito", r: "pasa" },
        { t: "Revisar la ortografía una vez antes de entregar", r: "justo" },
        { t: "Entregarlo sin mirarlo, a toda prisa", r: "corto" },
        { t: "Quedarse sin dormir para dejarlo perfecto", r: "pasa" },
        { t: "Tachar con cuidado un error y seguir", r: "justo" },
        { t: "No hacerlo porque «total, no va a quedar perfecto»", r: "corto", x: "No hacer nada es quedarse corto, aunque nazca de exigirse demasiado." },
      ],
    },
    idea: "Hacerlo bien no es lo mismo que hacerlo perfecto. Esforzarse ayuda; exigirte lo imposible te bloquea.",
    frase: { t: "Vivir bien se consigue poco a poco, pero no es poca cosa.", autor: "Zenón de Citio", obra: "según Diógenes Laercio, Vidas, VII, 26" },
    reto: "Hoy haz una tarea «suficientemente bien» y entrégala sin repetirla. Fíjate en cómo te sientes.",
  },
  {
    bloque: 2,
    virtud: "templanza",
    titulo: "La voz que me habla",
    historia: "Irina se da cuenta en clase de que se ha dejado los deberes de Inglés en casa. Por dentro se machaca: «Eres un desastre, siempre igual, no haces nada bien». Justo después, su compañera Olga descubre que tampoco los trae, e Irina le susurra: «Tranquila, le pasa a cualquiera. Mañana los traes».",
    pregunta: "¿Por qué Irina es tan amable con Olga y tan dura consigo misma? ¿Qué cambiaría si se hablara como le habla a su amiga?",
    juego: {
      consigna: "¿Depende de Irina?",
      tipo: "DEPENDE",
      items: [
        { t: "Haberse dejado hoy los deberes en casa", r: "no", x: "Ya ha pasado: eso no se puede cambiar. Lo que viene ahora, sí." },
        { t: "Que la profe le pida traerlos mañana", r: "no" },
        { t: "Sentirse fastidiada", r: "parte", x: "El fastidio llega solo. Cuánto lo alimenta con insultos, depende de ella." },
        { t: "Cómo se habla a sí misma", r: "si" },
        { t: "Preparar la mochila la noche antes", r: "si" },
        { t: "Decirse lo mismo que le dijo a Olga", r: "si" },
      ],
    },
    idea: "Háblate como le hablarías a un buen amigo: con la verdad, pero con cariño. Nadie aprende mejor a base de insultos.",
    frase: { t: "Es propio del ser humano querer incluso a quienes se equivocan.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 22" },
    reto: "Cuando hoy te equivoques, pregúntate: «¿Qué le diría a un amigo?». Y dítelo a ti.",
  },
  {
    bloque: 2,
    virtud: "coraje",
    titulo: "El poder del «todavía»",
    historia: "Gonzalo se apuntó al club de ajedrez del cole en septiembre y aún no ha ganado ninguna partida. Hoy ha vuelto a perder en diez movimientos y ha dicho, recogiendo las piezas: «No sé jugar. El ajedrez no es lo mío». La monitora le ha contestado con una sola palabra: «Todavía». Gonzalo se ha quedado pensando en ella todo el camino a casa.",
    pregunta: "¿Qué cambia en la frase «no sé jugar» si le añades «todavía»? ¿Qué sabéis hacer hoy que antes no sabíais?",
    juego: {
      consigna: "¿Depende de Gonzalo?",
      tipo: "DEPENDE",
      items: [
        { t: "Ganar la próxima partida", r: "parte", x: "Depende de cómo juegue él, pero también de su rival." },
        { t: "Practicar un rato cada semana", r: "si" },
        { t: "Que otros lleven años jugando", r: "no" },
        { t: "Fijarse en qué falló en cada partida", r: "si" },
        { t: "Pedir a la monitora que le enseñe una jugada", r: "si" },
        { t: "Cómo termina la frase «No sé jugar…»", r: "si" },
      ],
    },
    idea: "«No sé» cierra una puerta; «todavía no sé» la deja abierta. Casi todo lo que sabes hoy empezó con un «todavía no».",
    frase: { t: "Nada grande nace de repente, ni siquiera un racimo de uvas o un higo. Primero florece, luego da fruto y después madura.", autor: "Epicteto", obra: "Disertaciones, I, 15" },
    reto: "Escribe algo que aún no sabes hacer, añade «todavía» y apunta un primer paso pequeño.",
  },
  {
    bloque: 2,
    virtud: "justicia",
    titulo: "La cancela abierta",
    historia: "Salma salió corriendo al cole y se dejó abierta la cancela del patio. Al volver, Canela, su perrita, se había escapado; la encontró un vecino dos calles más allá. Salma se encerró en su cuarto repitiendo: «Soy lo peor. Todo es culpa mía». Su madre llamó a la puerta: «No quiero que te castigues. Quiero que pensemos juntas cómo evitarlo».",
    pregunta: "¿Qué diferencia hay entre decirse «soy lo peor» y decirse «me he equivocado, ¿cómo lo arreglo?»? ¿Cuál de las dos ayuda más a que no vuelva a pasar?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Decir «he sido yo» aunque le dé vergüenza", r: "coraje" },
        { t: "Pensar un truco para no olvidar la cancela", r: "sabiduria" },
        { t: "Dar las gracias al vecino que encontró a Canela", r: "justicia" },
        { t: "Calmarse antes de hablar con su madre", r: "templanza" },
        { t: "Pedir perdón a su familia por el susto", r: "justicia" },
        { t: "Pegar en la puerta una nota: «¿Cancela cerrada?»", r: "sabiduria" },
      ],
    },
    idea: "Sentirte culpable no arregla nada. Hacerte responsable, sí: reconocer lo que hiciste, repararlo y pensar cómo evitarlo la próxima vez.",
    frase: { t: "Primero decide qué persona quieres ser. Después, haz lo que tengas que hacer.", autor: "Epicteto", obra: "Disertaciones, III, 23" },
    reto: "Si hoy te equivocas en algo, en vez de castigarte, pregúntate: «¿Qué puedo hacer para arreglarlo?».",
  },
  {
    bloque: 2,
    virtud: "sabiduria",
    titulo: "Lo que dijo y lo que oí",
    historia: "Al acabar el entrenamiento de fútbol sala, el entrenador le dice a Martina: «Hoy has corrido muchísimo. Ahora te falta levantar la cabeza y pasar más». Martina se va a casa rabiando: «Me tiene manía. Piensa que soy una chupona y que juego fatal». A la hora de cenar ya ni se acuerda de la primera parte de la frase.",
    pregunta: "¿Qué dijo exactamente el entrenador y qué añadió Martina? ¿Para qué le puede servir esa crítica?",
    juego: {
      consigna: "¿Es un hecho o es lo que Martina se dice?",
      tipo: "HECHO",
      items: [
        { t: "El entrenador dijo que había corrido muchísimo", r: "si" },
        { t: "Le pidió que pasara más el balón", r: "si" },
        { t: "Me tiene manía", r: "no" },
        { t: "Piensa que juego fatal", r: "no" },
        { t: "Soy una chupona", r: "no" },
        { t: "Martina se ha sentido molesta", r: "si" },
      ],
    },
    idea: "Una crítica habla de algo que hiciste, no de quién eres. Escúchala entera, quédate con lo útil y deja lo que añade tu enfado.",
    frase: { t: "Si alguien me demuestra que me equivoco, cambiaré con gusto de opinión. Busco la verdad, y la verdad nunca ha hecho daño a nadie.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 21" },
    reto: "Si hoy alguien te corrige, repite en tu cabeza lo que dijo exactamente antes de responder.",
  },

  // ---------------- Bloque 3 · La pausa ----------------
  {
    bloque: 3,
    virtud: "templanza",
    titulo: "Un minuto en la fuente",
    historia: "Carla y Julia juegan al pañuelo en el recreo y no se ponen de acuerdo: ¿ha pisado la raya o no? Cada vez hablan más alto, y Carla nota el calor subiéndole a la cara y los puños apretados. Entonces dice: «Necesito un minuto». Se va a la fuente, bebe agua, respira despacio cuatro veces y vuelve.",
    pregunta: "¿Por qué creéis que Carla se ha ido un momento? ¿Es lo mismo alejarse un minuto que irse enfadada para siempre?",
    juego: {
      consigna: "¿Se pasa, se queda corto o es el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Seguir discutiendo a gritos hasta ganar", r: "pasa" },
        { t: "Decir «necesito un minuto» y volver después", r: "justo" },
        { t: "Irse sin decir nada y no volver a jugar", r: "corto", x: "Alejarse sin volver deja el problema sin resolver. La pausa sirve si luego se habla." },
        { t: "Respirar despacio, soltando el aire muy lento", r: "justo" },
        { t: "Empujar a Julia para que se calle", r: "pasa" },
        { t: "Callarse y dejar que Julia decida siempre", r: "corto" },
      ],
    },
    idea: "Alejarte un momento no es huir: es darle tiempo a tu cuerpo para calmarse y volver con la cabeza clara.",
    frase: { t: "En ningún sitio puede uno retirarse con más tranquilidad que en su propia alma.", autor: "Marco Aurelio", obra: "Meditaciones, IV, 3" },
    reto: "Busca hoy tu «fuente»: un sitio al que ir un minuto cuando notes que el enfado sube.",
  },
  {
    bloque: 3,
    virtud: "templanza",
    titulo: "Palabras antes que puños",
    historia: "En la fila del comedor, Gabriel le da a Iván una colleja «de broma». Iván le dice que pare, pero a los dos minutos llega otra, y los de detrás se ríen. Iván aprieta el puño y está a punto de darse la vuelta para pegarle. Entonces se acuerda de que tiene otra herramienta: la voz.",
    pregunta: "¿Qué podría decir Iván, y cómo? ¿Y qué tendría que hacer si Gabriel lo repite todos los días?",
    juego: {
      consigna: "¿Puede resolverlo Iván o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Decir con voz firme: «Para. No me gusta»", r: "yo" },
        { t: "Una broma que se acaba cuando se lo pide", r: "yo" },
        { t: "Las collejas se repiten todos los días", r: "adulto" },
        { t: "Le hacen daño de verdad y no paran", r: "adulto" },
        { t: "Cambiarse de sitio en la fila", r: "yo" },
        { t: "Contárselo a un adulto de confianza", r: "adulto" },
      ],
    },
    nota: "Si alguien te hace daño o lo repite aunque le pidas que pare, cuéntaselo a un adulto de confianza. Eso siempre depende de ti, y no tienes que aguantarlo ni resolverlo solo.",
    idea: "Pegar convierte un problema en dos. Decir «para» con voz firme, y pedir ayuda cuando hace falta, es más valiente.",
    frase: { t: "La mejor manera de defenderte es no parecerte a quien te hace daño.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 6" },
    reto: "Practica en voz alta con un compañero tu frase firme: «Para. No me gusta».",
  },
  {
    bloque: 3,
    virtud: "templanza",
    titulo: "El enfado que se contagia",
    historia: "En la final del torneo de fútbol del recreo, el árbitro, un chico de sexto, pita una falta. Alguien grita «¡Estás comprado!» y en pocos segundos medio equipo lo rodea, chillando. Samuel ni siquiera ha visto la jugada, pero nota que le sube la rabia y está a punto de ponerse a gritar con los demás.",
    pregunta: "¿Por qué siente rabia Samuel si ni siquiera vio la jugada? ¿Qué puede hacer una sola persona para que un grupo se calme?",
    juego: {
      consigna: "¿Depende de Samuel?",
      tipo: "DEPENDE",
      items: [
        { t: "Que sus compañeros griten", r: "no" },
        { t: "Notar la rabia que se contagia", r: "parte", x: "Llega casi sin querer, como un bostezo. Pero puede darse cuenta y frenarla." },
        { t: "Ponerse a gritar él también", r: "si" },
        { t: "Apartarse un paso del grupo", r: "si" },
        { t: "Que el árbitro cambie su decisión", r: "no" },
        { t: "Proponer: «Vamos a preguntar a la maestra»", r: "si" },
      ],
    },
    idea: "El enfado de un grupo se contagia como un bostezo. Darte cuenta te deja elegir si te sumas o no.",
    frase: { t: "Igual que sentimos un escalofrío cuando nos salpica agua fría, hay movimientos del ánimo que llegan sin que los elijamos.", autor: "Séneca", obra: "Sobre la ira, II, 2" },
    reto: "Si hoy ves a un grupo enfadándose, da un paso atrás y respira antes de unirte.",
  },
  {
    bloque: 3,
    virtud: "templanza",
    titulo: "Saber perder",
    historia: "Adam lleva toda la tarde jugando al parchís con su familia y va ganando. En la última jugada, su hermana mayor le come una ficha a dos casillas de la meta y gana ella. Adam da un manotazo al tablero, las fichas salen volando y se va al sofá. Su abuela empieza a recogerlas en silencio.",
    pregunta: "¿Qué sintió Adam y qué hizo con eso? ¿Qué puede hacer ahora que ya ha pasado?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Felicitar a su hermana, aunque le fastidie", r: "justicia" },
        { t: "Respirar antes de tocar el tablero", r: "templanza" },
        { t: "Pensar qué jugada podría hacer mejor", r: "sabiduria" },
        { t: "Volver a la mesa aunque le dé vergüenza", r: "coraje" },
        { t: "Ayudar a su abuela a recoger las fichas", r: "justicia" },
        { t: "Jugar otra vez aunque pueda volver a perder", r: "coraje" },
      ],
    },
    idea: "Perder duele, y está bien que duela. Lo que dice cómo eres es lo que haces justo después.",
    frase: { t: "Lo que se pone en medio del camino se convierte en el camino.", autor: "Marco Aurelio", obra: "Meditaciones, V, 20" },
    reto: "La próxima vez que pierdas en algo, di «buena partida» antes de decir nada más.",
  },
  {
    bloque: 3,
    virtud: "templanza",
    titulo: "Las dos asas",
    historia: "Fátima intenta hacer los deberes y su hermano Omar, de siete años, repite todo lo que ella dice con voz de pito. «Para ya». «Para ya». «¡Mamá!». «¡Mamá!». Fátima siente que va a explotar y piensa: «Lo hace solo para fastidiarme. Es insoportable y me odia».",
    pregunta: "¿Qué otras razones puede tener Omar para hacer eso? ¿Cómo podría Fátima coger esta situación por la otra asa?",
    juego: {
      consigna: "¿Es un hecho o es lo que Fátima se dice?",
      tipo: "HECHO",
      items: [
        { t: "Omar repite todo lo que ella dice", r: "si" },
        { t: "Fátima no consigue concentrarse", r: "si" },
        { t: "Lo hace solo para fastidiarme", r: "no", x: "Puede ser, pero también puede querer jugar con ella o que le haga caso." },
        { t: "Me odia", r: "no" },
        { t: "Omar tiene siete años", r: "si" },
        { t: "Nunca me va a dejar en paz", r: "no" },
      ],
    },
    idea: "Cuando alguien de tu familia te chincha, puedes cogerlo por el asa del enfado o por la de «es mi hermano». La segunda pesa menos.",
    frase: { t: "Cada cosa tiene dos asas: por una se puede llevar y por la otra no. Si tu hermano te trata mal, no la cojas por el asa de «me ha tratado mal», sino por la de «es mi hermano y hemos crecido juntos».", autor: "Epicteto", obra: "Enquiridión, 43" },
    reto: "Si hoy alguien de casa te chincha, di con calma lo que necesitas: «Ahora estoy con los deberes, luego jugamos».",
  },
  {
    bloque: 3,
    virtud: "justicia",
    titulo: "Después de la explosión",
    historia: "En el trabajo en grupo, Leo derrama un vaso de agua sobre el mural que han tardado una semana en pintar. Rubén explota: «¡Eres un inútil! ¡Siempre lo estropeas todo!». Leo se queda callado y en toda la mañana no le mira. Por la tarde, ya tranquilo, a Rubén le pesa lo que dijo, pero no sabe cómo arreglarlo.",
    pregunta: "¿Qué hace que un perdón sea de verdad? ¿Qué diferencia hay entre «perdón, pero es que tú…» y un perdón sin excusas?",
    juego: {
      consigna: "¿Depende de Rubén?",
      tipo: "DEPENDE",
      items: [
        { t: "Que Leo le perdone", r: "no", x: "Rubén puede pedir perdón de verdad; perdonar lo decide Leo, y quizá necesite tiempo." },
        { t: "Pedir perdón sin poner excusas", r: "si" },
        { t: "Borrar lo que ya dijo", r: "no" },
        { t: "Sentir vergüenza por lo que pasó", r: "parte", x: "Llega sola y le avisa de que algo no estuvo bien. Lo que hace con ella es cosa suya." },
        { t: "Ofrecerse a arreglar el mural juntos", r: "si" },
        { t: "Qué hará la próxima vez que se enfade", r: "si" },
      ],
    },
    idea: "Explotar le puede pasar a cualquiera. Un buen perdón dice qué hiciste mal, no pone excusas y busca cómo reparar.",
    frase: { t: "No discutas más sobre cómo tiene que ser una buena persona. Sé una.", autor: "Marco Aurelio", obra: "Meditaciones, X, 16" },
    reto: "Si le debes un perdón a alguien, díselo hoy: «Siento haber… La próxima vez…».",
  },
  {
    bloque: 3,
    virtud: "coraje",
    titulo: "Un «no» tranquilo",
    historia: "Nico le pide a Paula sus rotuladores nuevos por tercera vez esta semana. Las otras dos veces se los devolvió sin tapa y secos. Paula nota que se enfada por dentro, pero también le da apuro decir que no. Duda entre gritarle «¡Eres un aprovechado!» o dejárselos otra vez y tragarse el enfado.",
    pregunta: "¿Hay alguna opción entre gritar y callarse? ¿Cómo se dice un «no» firme sin hacer daño?",
    juego: {
      consigna: "¿Se pasa, se queda corto o es el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Gritarle «¡Eres un aprovechado!»", r: "pasa" },
        { t: "Dejárselos otra vez aunque no quiera", r: "corto" },
        { t: "Decir: «No, esta vez no. Se me secaron»", r: "justo" },
        { t: "Inventarse que los ha perdido", r: "corto", x: "Evita el mal rato, pero no dice la verdad ni resuelve nada." },
        { t: "Ofrecerle un lápiz y explicarle por qué", r: "justo" },
        { t: "No volver a hablarle nunca más", r: "pasa" },
      ],
    },
    idea: "Se puede decir «no» con calma: sin gritos y sin tragarte lo que piensas. Tus cosas y tus límites también importan.",
    frase: { t: "No es que no nos atrevamos porque las cosas sean difíciles. Son difíciles porque no nos atrevemos.", autor: "Séneca", obra: "Cartas a Lucilio, 104" },
    reto: "Practica hoy un «no» tranquilo: mirando a los ojos, con voz firme y una razón corta.",
  },
  {
    bloque: 3,
    virtud: "templanza",
    titulo: "Lo que casi le dije a Joel",
    historia:
      "En la comida del domingo, su primo Joel se ríe de Alejandro delante de todos: «Tu equipo ha vuelto a perder. Sois malísimos». A Alejandro se le calienta la cara y ya tiene en la punta de la lengua un insulto de los gordos. Abre la boca… y, de repente, se calla y cuenta hasta cinco.",
    pregunta: "¿Qué puede pasar si lo dice ahora? ¿Y si espera un poco?",
    juego: {
      consigna: "¿Es real o se lo imagina Alejandro?",
      tipo: "REAL",
      items: [
        { t: "Su equipo perdió ayer", r: "si" },
        { t: "Joel se ha reído de su equipo delante de todos", r: "si" },
        { t: "Joel quiere hacerle daño de verdad", r: "no", x: "Puede ser una broma de primos que le ha salido mal. Sin preguntar, no lo sabe." },
        { t: "Si no contesta ya, quedará como un tonto", r: "no" },
        { t: "Lo que se dice ya no se puede borrar", r: "si" },
        { t: "Ahora mismo está muy enfadado", r: "si" },
      ],
    },
    idea: "Una palabra dicha con rabia no se puede recoger. Esperar antes de contestar hace que respondas tú, y no tu enfado.",
    frase: { t: "Si no está bien, no lo hagas. Si no es verdad, no lo digas.", autor: "Marco Aurelio", obra: "Meditaciones, XII, 17" },
    reto: "Si hoy algo te enfada, cuenta hasta cinco antes de contestar.",
  },
  {
    bloque: 3,
    virtud: "justicia",
    titulo: "Querer bien no es mandar",
    historia: "Noa y Claudia son amigas desde Infantil. Últimamente, Claudia se enfada si Noa juega con otras niñas, le pregunta con quién ha hablado en cada recreo y un día le dijo: «Si vas al cumple de Irene, ya no soy tu amiga». Noa ya no sabe si está haciendo algo mal, y cada día está más nerviosa.",
    pregunta: "¿Una buena amistad puede decidir con quién juegas o adónde vas? ¿Cómo se siente alguien a quien tratan bien?",
    juego: {
      consigna: "¿Puede resolverlo Noa o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Decirle a Claudia: «Yo juego con quien quiero»", r: "yo" },
        { t: "Claudia se enfada un día por perder un juego", r: "yo" },
        { t: "Alguien te amenaza con hacerte daño si no obedeces", r: "adulto" },
        { t: "Cada día tienes miedo de cómo reaccionará", r: "adulto" },
        { t: "Ves que alguien asusta o controla a otra persona", r: "adulto" },
        { t: "Contárselo a un adulto de confianza", r: "adulto" },
      ],
    },
    nota: "Nadie tiene derecho a controlarte ni a asustarte, tampoco un amigo o alguien mayor. Contárselo a un adulto de confianza siempre depende de ti: no es algo que tengas que aguantar ni resolver solo.",
    idea: "Quien te quiere bien te respeta: no decide por ti, no te vigila y no te asusta. Nadie tiene derecho a controlar a otra persona.",
    frase: { t: "Si quieres que te quieran, quiere.", autor: "Séneca", obra: "Cartas a Lucilio, 9" },
    reto: "Dile hoy a alguien que te trata bien qué es lo que te hace sentir a gusto a su lado.",
  },
  {
    bloque: 3,
    virtud: "templanza",
    titulo: "El acantilado",
    historia: "Volviendo de la excursión, el autobús se para en la autovía por una avería. Pasa media hora: unos gritan, otros lloran y alguien dice que van a pasar allí la noche. Elena también está nerviosa, pero se queda en su asiento, respira y le enseña a su compañero Pol un juego de adivinanzas. Poco a poco, los de alrededor se van uniendo.",
    pregunta: "¿Cómo ha ayudado Elena sin decirle a nadie «cálmate»? ¿Conocéis a alguien que sea como un acantilado?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Respirar despacio aunque todos chillen", r: "templanza" },
        { t: "Preguntar al conductor qué ha pasado de verdad", r: "sabiduria" },
        { t: "Consolar al compañero que está llorando", r: "justicia" },
        { t: "Proponer un juego aunque le dé corte", r: "coraje" },
        { t: "No repetir «vamos a pasar aquí la noche»", r: "sabiduria", x: "Es no dar por cierto lo que nadie sabe todavía." },
        { t: "Compartir su agua con quien no tiene", r: "justicia" },
      ],
    },
    idea: "Cuando todo a tu alrededor se agita, puedes ser como un acantilado: firme por dentro. Y tu calma también se contagia.",
    frase: { t: "Sé como el acantilado contra el que rompen las olas: se mantiene firme, y a su alrededor el agua se calma.", autor: "Marco Aurelio", obra: "Meditaciones, IV, 49" },
    reto: "Hoy, cuando alguien a tu lado esté nervioso, habla más despacio y más bajo. Observa qué pasa.",
  },
]);
