// La Ciudadela · sesiones del bloque 4 y 5: Sabiduría, Justicia
window.CIUDADELA_NUEVAS = (window.CIUDADELA_NUEVAS || []).concat([
  // ---------------- Bloque 4 · Sabiduría ----------------
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "Me has convencido",
    historia:
      "En Ciencias, Hugo defiende con fuerza que el murciélago es un pájaro: vuela, ¿no? Aitana abre el libro y le enseña que es un mamífero: tiene pelo y sus crías toman leche. Media clase se gira a mirar a Hugo. Él nota calor en las orejas y piensa si seguir discutiendo o decir que se ha equivocado.",
    pregunta: "¿Por qué cuesta tanto decir «me has convencido»? ¿Pierde algo Hugo si cambia de opinión?",
    juego: {
      consigna: "¿Depende de Hugo?",
      tipo: "DEPENDE",
      items: [
        { t: "Que el murciélago sea un mamífero", r: "no" },
        { t: "Mirar con calma las pruebas del libro", r: "si" },
        { t: "Sentir vergüenza al principio", r: "parte", x: "La vergüenza llega sola. Lo que Hugo hace después sí depende de él." },
        { t: "Lo que piensen los que le miran", r: "no" },
        { t: "Decir «tenías razón, no lo sabía»", r: "si" },
        { t: "Dar las gracias a Aitana por explicárselo", r: "si" },
      ],
    },
    idea: "Cambiar de opinión cuando te dan buenas razones no es perder: es ganar algo que no sabías. Lo importante es acercarse a la verdad.",
    frase: { t: "Si alguien me demuestra que me equivoco, cambiaré con gusto de opinión. Busco la verdad, y la verdad nunca ha hecho daño a nadie.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 21" },
    reto: "Hoy, cuando alguien te dé una buena razón, prueba a decir: «Vale, eso no lo había pensado».",
  },
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "Dos orejas, una boca",
    historia:
      "Salma empieza a contarle a Youssef que su perra se escapó el fin de semana. Antes de que termine, Youssef la interrumpe: «¡A mi primo le pasó igual y la encontró la policía!», y sigue hablando cinco minutos. Cuando por fin se calla, Salma ya no tiene ganas de contar el final. Youssef no entiende por qué se ha quedado tan seria.",
    pregunta: "¿Qué quería Salma cuando empezó a hablar? ¿Cómo se nota que alguien te está escuchando de verdad?",
    juego: {
      consigna: "¿Es real o se lo imagina Youssef?",
      tipo: "REAL",
      items: [
        { t: "Salma estaba contando algo importante para ella", r: "si" },
        { t: "«Ya sé lo que me va a contar»", r: "no", x: "Youssef no sabía el final: no dejó que Salma lo contara." },
        { t: "«Mi historia le interesa más que la suya»", r: "no" },
        { t: "Salma se ha quedado seria", r: "si" },
        { t: "«Está enfadada conmigo sin motivo»", r: "no", x: "Hay un motivo: no la dejó terminar. Preguntárselo sería la forma de saberlo." },
        { t: "Youssef la interrumpió antes del final", r: "si" },
      ],
    },
    idea: "Escuchar bien es dejar que el otro termine, mirarle y preguntar antes de contar lo tuyo. Así la otra persona se siente importante.",
    frase: { t: "Tenemos dos orejas y una sola boca para escuchar más y hablar menos.", autor: "Zenón de Citio", obra: "según Diógenes Laercio, Vidas, VII, 23" },
    reto: "Hoy, cuando alguien te cuente algo, espera a que termine y hazle una pregunta antes de hablar de ti.",
  },
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "El volcán que no explotó",
    historia:
      "Mateo lleva días preparando un volcán para la feria de Ciencias. Delante de toda la clase echa el vinagre y… nada, solo sale una espuma triste. En casa descubre que se saltó un paso de las instrucciones: no puso bicarbonato suficiente. Tira el cuaderno al suelo y dice que las Ciencias no son lo suyo.",
    pregunta: "¿Qué ha pasado de verdad y qué se está diciendo Mateo? ¿Qué puede sacar de este error para la próxima vez?",
    juego: {
      consigna: "¿Es un hecho o es lo que Mateo se dice?",
      tipo: "HECHO",
      items: [
        { t: "El volcán no explotó", r: "si" },
        { t: "No puso bicarbonato suficiente", r: "si" },
        { t: "«Las Ciencias no son lo mío»", r: "no" },
        { t: "«Todos se han reído de mí»", r: "no", x: "Quizá alguno sonrió, pero «todos» es lo que le dice su disgusto." },
        { t: "Se saltó un paso de las instrucciones", r: "si" },
        { t: "«Nunca me va a salir nada bien»", r: "no" },
      ],
    },
    idea: "Un error es información: te dice qué cambiar. Molesta, y es normal que moleste, pero no dice quién eres ni lo que puedes llegar a hacer.",
    frase: { t: "Cada capacidad crece con la práctica: se aprende a caminar caminando y a correr corriendo.", autor: "Epicteto", obra: "Disertaciones, II, 18" },
    reto: "Piensa en un error reciente y escribe una frase: «La próxima vez voy a…».",
  },
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "Dos cumpleaños, un sábado",
    historia:
      "Irina tiene un lío: sus dos mejores amigas celebran el cumpleaños el mismo sábado, a la misma hora y en sitios distintos. Lleva tres días dándole vueltas sola, sin dormir bien. Piensa que pedir consejo es de pequeños y que tiene que saber arreglarlo ella. Mientras tanto, las dos amigas le preguntan cada mañana si va a ir.",
    pregunta: "¿Por qué a veces nos da vergüenza pedir consejo? ¿A quién podría preguntar Irina y qué le diría?",
    juego: {
      consigna: "¿Puedes resolverlo tú o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Elegir a qué cumpleaños ir", r: "yo", x: "Lo decide ella, aunque pedir consejo le puede ayudar mucho." },
        { t: "Explicar a una amiga que no podrá ir", r: "yo" },
        { t: "Te pierdes del grupo en la excursión", r: "adulto" },
        { t: "Llevas días durmiendo mal por una preocupación", r: "adulto", x: "Cuando algo te quita el sueño varios días, mejor compartirlo con un adulto." },
        { t: "Olvidaste qué deberes había para mañana", r: "yo" },
        { t: "Un compañero se ha hecho daño en el patio", r: "adulto" },
      ],
    },
    idea: "Pedir consejo es una decisión sabia, no una debilidad. Quien pregunta ve más cosas que quien piensa solo, y la decisión sigue siendo suya.",
    frase: { t: "No te dé vergüenza que te ayuden. Como el soldado que no puede subir solo la muralla, a veces necesitamos una mano.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 7" },
    reto: "Hoy pide consejo a alguien sobre algo pequeño que te preocupe, y escucha su respuesta hasta el final.",
  },
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "Lo que quiero ahora",
    historia:
      "Mañana es la excursión a Doñana y el autobús sale a las ocho. Chen está en casa de su primo, que le propone ver una película larguísima que termina a las once. Chen se muere de ganas, pero también quiere estar despierto para ver los flamencos. Tiene el mando en la mano. Una voz le dice «¡quédate!» y otra le recuerda el despertador.",
    pregunta: "¿Qué quiere Chen ahora mismo y qué le conviene? ¿Cómo se puede escuchar a las dos voces antes de decidir?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Chen espera un minuto antes de decidir", r: "sabiduria" },
        { t: "Ve solo media película y la termina otro día", r: "templanza" },
        { t: "Le dice a su primo que hoy se va pronto", r: "coraje", x: "Decir que no a un plan que apetece cuesta. También hay sabiduría en la decisión." },
        { t: "Piensa cómo se sentirá mañana a las siete", r: "sabiduria" },
        { t: "Se lo agradece a su primo y propone otro día", r: "justicia" },
      ],
    },
    idea: "Lo que quiero ahora y lo que me conviene no siempre coinciden. Pararse a pensar en tu yo de mañana te ayuda a elegir mejor.",
    frase: { t: "Primero decide qué persona quieres ser. Después, haz lo que tengas que hacer.", autor: "Epicteto", obra: "Disertaciones, III, 23" },
    reto: "Hoy, antes de algo que te apetezca mucho, pregúntate: «¿Y mañana me alegraré de esto?».",
  },
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "El mejor regalo del invierno",
    historia:
      "Vuelven las clases después de las vacaciones de invierno. En la fila, todos comparan lo que les han regalado y Valentina se queda callada: ella ha recibido un libro y unos calcetines. Pero lo que no se le olvida es la tarde que pasó con su abuelo haciendo churros y riendo cuando se les quemó la primera tanda. No sabe si eso cuenta como regalo.",
    pregunta: "¿Qué cosas de las vacaciones recordarás dentro de un año? ¿Qué te hace sentir bien de verdad?",
    juego: {
      consigna: "¿Depende de Valentina?",
      tipo: "DEPENDE",
      items: [
        { t: "Qué regalos le hacen", r: "no" },
        { t: "Lo que tienen sus compañeros", r: "no" },
        { t: "Dar las gracias por lo que ha recibido", r: "si" },
        { t: "Sentirse un poco peor al comparar", r: "parte", x: "Esa punzada puede llegar sola. Seguir comparando o no, sí depende de ella." },
        { t: "Contar en la fila la tarde de los churros", r: "si" },
        { t: "Pasar más ratos así con su familia", r: "parte", x: "Ella puede proponerlo, pero también depende de los demás." },
      ],
    },
    idea: "Las cosas se gastan o se olvidan. Los ratos compartidos con quien quieres se quedan contigo mucho más tiempo.",
    frase: { t: "Ningún bien nos alegra de verdad si no tenemos con quién compartirlo.", autor: "Séneca", obra: "Cartas a Lucilio, 6" },
    reto: "Cuenta a alguien de la clase un buen momento de tus vacaciones que no se pueda comprar.",
  },
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "Un puerto al que llegar",
    historia:
      "El uno de enero, Rubén escribe su lista de propósitos: leer cincuenta libros, sacar dieces en todo, correr cada mañana, no discutir nunca con su hermana y aprender japonés. Pega la lista en la puerta de su cuarto. El día diez ya ha fallado en casi todo y la arranca enfadado: «Total, para qué».",
    pregunta: "¿Qué le ha pasado a la lista de Rubén? ¿Cómo sería un propósito que sí pudiera cumplir?",
    juego: {
      consigna: "Este propósito, ¿se pasa, se queda corto o es el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Leer cincuenta libros en un año", r: "pasa", x: "Para algún gran lector es posible, pero junto a todo lo demás de la lista es demasiado." },
        { t: "Leer diez minutos antes de dormir", r: "justo" },
        { t: "No proponerse nada, por si acaso", r: "corto" },
        { t: "Correr dos tardes por semana con un amigo", r: "justo" },
        { t: "Sacar diez en todos los exámenes", r: "pasa" },
        { t: "Recoger mi cuarto cuando me acuerde", r: "corto", x: "«Cuando me acuerde» es tan vago que casi nunca pasa." },
      ],
    },
    idea: "Un buen propósito es como un puerto: claro, cercano y posible. Mejor uno pequeño que cumples que diez enormes que abandonas.",
    frase: { t: "Si uno no sabe a qué puerto se dirige, ningún viento le es favorable.", autor: "Séneca", obra: "Cartas a Lucilio, 71" },
    reto: "Escribe un solo propósito para este mes: qué harás, cuándo y cómo sabrás que lo has cumplido.",
  },
  {
    bloque: 4,
    virtud: "sabiduria",
    titulo: "La abuela que aprende a nadar",
    historia:
      "La abuela de Daniela tiene setenta y dos años y se ha apuntado a clases de natación. Los martes, Daniela la acompaña a la piscina y la ve agarrada al borde, tragando agua y riéndose. «¿Para qué aprendes ahora, abuela?», le pregunta. «Porque todavía no sé», contesta ella. Daniela piensa en lo mucho que protesta cuando le toca repasar las tablas.",
    pregunta: "¿Por qué crees que la abuela quiere aprender a su edad? ¿Hay algo que te gustaría aprender aunque no te lo pidan en el cole?",
    juego: {
      consigna: "¿Depende de la abuela?",
      tipo: "DEPENDE",
      items: [
        { t: "Tener setenta y dos años", r: "no" },
        { t: "Ir a clase todos los martes", r: "si" },
        { t: "Aprender a nadar tan rápido como una niña", r: "parte", x: "Practicar depende de ella; el ritmo de su cuerpo, no del todo." },
        { t: "Reírse cuando traga agua", r: "si" },
        { t: "Que la piscina esté abierta en agosto", r: "no" },
        { t: "Pedir ayuda al monitor cuando no le sale", r: "si" },
      ],
    },
    idea: "Aprender no se termina al acabar el cole. Mientras haya algo que no sabes, hay una aventura esperándote, tengas la edad que tengas.",
    frase: { t: "Hay que seguir aprendiendo mientras haya algo que no sepamos.", autor: "Séneca", obra: "Cartas a Lucilio, 76" },
    reto: "Pregunta hoy a un adulto de tu familia qué ha aprendido este año, y cuéntale tú algo que hayas aprendido.",
  },

  // ---------------- Bloque 5 · Justicia ----------------
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "Igual no siempre es justo",
    historia:
      "La tutora ha cambiado los sitios de la clase y Samuel se sienta en la primera fila, porque no ve bien la pizarra desde lejos. Martina protesta: «¡No es justo! Todos deberíamos ir cambiando». Algunos le dan la razón. Samuel no dice nada y se pone colorado. La tutora pregunta a la clase qué sería lo justo aquí.",
    pregunta: "¿Es lo mismo tratar a todos igual que tratar a todos de forma justa? ¿Qué necesita cada uno para aprender?",
    juego: {
      consigna: "¿Es un hecho o es lo que Martina se dice?",
      tipo: "HECHO",
      items: [
        { t: "Samuel no ve bien la pizarra de lejos", r: "si" },
        { t: "«Samuel es el favorito de la profe»", r: "no" },
        { t: "La tutora le ha puesto en primera fila", r: "si" },
        { t: "«Si él va delante, yo salgo perdiendo»", r: "no", x: "A Martina no le quitan nada: cada uno necesita cosas distintas." },
        { t: "Samuel se ha puesto colorado", r: "si" },
        { t: "«Lo justo es que todos tengamos lo mismo»", r: "no", x: "Es lo que ella piensa ahora. A veces lo justo es dar a cada uno lo que necesita." },
      ],
    },
    idea: "Ser justo no es dar a todos lo mismo, sino dar a cada uno lo que necesita para tener las mismas oportunidades.",
    frase: { t: "Lo que inquieta a las personas no son las cosas, sino las opiniones que tienen sobre las cosas.", autor: "Epicteto", obra: "Enquiridión, 5" },
    reto: "Fíjate hoy en algo que alguien necesite distinto a ti y piensa cómo podrías ayudarle.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "Te lo prometí",
    historia:
      "Iván le prometió a Carla que el jueves por la tarde la ayudaría a practicar comba para la prueba de Educación Física. El jueves, a la salida, sus primos le invitan a jugar a la consola en su casa. Iván piensa que Carla seguro que lo entiende y que ya practicarán otro día. Carla le está esperando en el parque con la cuerda.",
    pregunta: "¿Qué siente Carla si Iván no aparece? ¿Qué puede hacer Iván si de verdad no puede cumplir una promesa?",
    juego: {
      consigna: "¿Depende de Iván?",
      tipo: "DEPENDE",
      items: [
        { t: "Que sus primos le inviten", r: "no" },
        { t: "Tener ganas de ir a jugar", r: "parte", x: "Las ganas llegan solas. Lo que hace con ellas sí depende de él." },
        { t: "Ir al parque como prometió", r: "si" },
        { t: "Lo que Carla sienta si no va", r: "no" },
        { t: "Avisar a Carla si de verdad no puede ir", r: "si" },
        { t: "Pensar antes de prometer algo", r: "si" },
      ],
    },
    idea: "Una promesa es una pequeña deuda con otra persona. Si la cumples, confían en ti. Si no puedes, se avisa y se busca otra solución.",
    frase: { t: "No discutas más sobre cómo tiene que ser una buena persona. Sé una.", autor: "Marco Aurelio", obra: "Meditaciones, X, 16" },
    reto: "Hoy solo promete lo que sepas que puedes cumplir, y cumple una cosa que hayas dicho que harías.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "El pincel de Gonzalo",
    historia:
      "Gonzalo tiene una caja de acuarelas que le regalaron por su cumpleaños y la cuida muchísimo. Un día sale al baño y Fátima coge su pincel bueno sin preguntar para terminar su mural. Cuando Gonzalo vuelve, el pincel tiene las cerdas dobladas. Fátima dice que solo lo ha usado un momento y que tampoco es para tanto.",
    pregunta: "¿Por qué a Gonzalo le importa tanto, aunque sea solo un pincel? ¿Qué podría hacer ahora Fátima?",
    juego: {
      consigna: "¿Depende de Fátima?",
      tipo: "DEPENDE",
      items: [
        { t: "Preguntar antes de coger algo ajeno", r: "si" },
        { t: "Que Gonzalo se enfade", r: "no" },
        { t: "Pedir perdón sin poner excusas", r: "si" },
        { t: "Que el pincel vuelva a quedar como nuevo", r: "no" },
        { t: "Ofrecer uno de los suyos para compensar", r: "si" },
        { t: "Que Gonzalo vuelva a prestarle cosas", r: "parte", x: "Lo decide Gonzalo, pero cómo actúe ahora Fátima ayuda a recuperar la confianza." },
      ],
    },
    idea: "Las cosas de los demás no se cogen sin permiso, aunque sea un momento. Lo que para ti es poco, para otra persona puede ser mucho.",
    frase: { t: "Primero decide qué persona quieres ser. Después, haz lo que tengas que hacer.", autor: "Epicteto", obra: "Disertaciones, III, 23" },
    reto: "Hoy pide permiso antes de usar cualquier cosa que no sea tuya, aunque sea una goma.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "La idea era de Nerea",
    historia:
      "En el trabajo sobre el reciclaje, a Nerea se le ocurrió hacer un contenedor gigante con cajas. Ella es tímida y prefirió que Adam lo explicara en voz alta. Cuando terminan, la maestra felicita a Adam: «¡Qué idea tan original!». Adam nota que Nerea baja la mirada. Tiene un segundo para decir algo o quedarse con el aplauso.",
    pregunta: "¿Qué pierde y qué gana Adam si dice que la idea fue de Nerea? ¿Cómo te sientes cuando alguien reconoce lo que has hecho tú?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Adam dice: «La idea fue de Nerea»", r: "justicia" },
        { t: "Nerea se atreve a explicar una parte", r: "coraje" },
        { t: "Adam no presume aunque le aplaudan", r: "templanza" },
        { t: "Pensar quién hizo cada parte antes de contestar", r: "sabiduria" },
        { t: "Repartir el aplauso entre todo el equipo", r: "justicia" },
      ],
    },
    idea: "Reconocer el mérito de otra persona no te quita nada. Es darle a cada uno lo que le corresponde, y eso es justicia.",
    frase: { t: "Que calle quien hizo el favor; que lo cuente quien lo recibió.", autor: "Séneca", obra: "Sobre los beneficios, II, 11" },
    reto: "Hoy di en voz alta algo bueno que haya hecho otra persona: «Esto lo ha hecho…».",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "Todos nos equivocamos",
    historia:
      "En Inglés, Alejandro sale a la pizarra y lee «kitchen» como se escribe. Media clase suelta una carcajada y alguien lo repite imitando su voz. Alejandro vuelve a su sitio mirando al suelo. Aitana, que también se había reído, ve su cara y deja de reír de golpe. Ella se equivocó en lo mismo la semana pasada.",
    pregunta: "¿Qué siente quien se equivoca y oye risas? ¿Qué puede hacer quien se ha reído sin pensarlo?",
    juego: {
      consigna: "¿Puedes resolverlo tú o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Te ríes sin querer del error de alguien", r: "yo", x: "Puedes parar y pedirle perdón. Eso está en tus manos." },
        { t: "Animar a quien se ha equivocado", r: "yo" },
        { t: "Se ríen de un compañero todos los días", r: "adulto" },
        { t: "Alguien graba un error de otro para reírse", r: "adulto" },
        { t: "Te equivocas tú y te da vergüenza", r: "yo" },
        { t: "Imitan a alguien y ya no quiere venir", r: "adulto" },
      ],
    },
    nota: "Si las risas se repiten o alguien lo pasa mal de verdad, se cuenta a un adulto de confianza. Hacerlo siempre depende de ti: no hay que aguantarlo.",
    idea: "Equivocarse es parte de aprender, para todos. Reírse del error de otro hace que nadie se atreva a intentarlo.",
    frase: { t: "Es propio del ser humano querer incluso a quienes se equivocan.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 22" },
    reto: "Hoy, si alguien se equivoca delante de ti, dile algo que le ayude a seguir.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "Defender sin pelear",
    historia:
      "En la cola del comedor, dos chicos de sexto le quitan la gorra a Omar y se la pasan por encima de su cabeza. Omar intenta cogerla y ellos se ríen. Irene lo ve todo. Le late el corazón deprisa: no quiere quedarse callada, pero tampoco quiere acabar a empujones con dos chicos mayores.",
    pregunta: "¿Qué puede hacer Irene para ayudar a Omar sin ponerse en peligro? ¿Qué diferencia hay entre defender y atacar?",
    juego: {
      consigna: "Lo que hace Irene, ¿se pasa, se queda corta o es el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Empujar a los de sexto para quitarles la gorra", r: "pasa" },
        { t: "Mirar hacia otro lado", r: "corto" },
        { t: "Decir con voz firme: «Devolvédsela»", r: "justo" },
        { t: "Avisar a la monitora del comedor", r: "justo" },
        { t: "Insultarlos delante de todo el comedor", r: "pasa" },
        { t: "Ponerse al lado de Omar y hablarle", r: "justo" },
      ],
    },
    nota: "Contar a un adulto lo que ha pasado siempre depende de ti y no es chivarse: es proteger. Si se repite, no se aguanta ni se arregla solo.",
    idea: "Defender a alguien es ponerte de su lado con firmeza y respeto, sin convertirte en quien hace daño. Buscar a un adulto también es defender.",
    frase: { t: "Sé como el acantilado contra el que rompen las olas: se mantiene firme, y a su alrededor el agua se calma.", autor: "Marco Aurelio", obra: "Meditaciones, IV, 49" },
    reto: "Piensa y ensaya en voz baja una frase firme y respetuosa para defender a alguien si hace falta.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "El billete junto a la fuente",
    historia:
      "Al salir al recreo, Lucía encuentra un billete de cinco euros junto a la fuente. Nadie la ha visto. Con eso podría comprarse el cuaderno de purpurina que tanto le gusta. Entonces oye a una niña de tercero que busca por el suelo, con los ojos llorosos: «Era para la excursión».",
    pregunta: "¿Qué pesa más en Lucía: las ganas o lo que es justo? ¿Cambiaría algo si nadie estuviera buscando el billete?",
    juego: {
      consigna: "¿Depende de Lucía?",
      tipo: "DEPENDE",
      items: [
        { t: "Encontrarse el billete", r: "no" },
        { t: "Que nadie la haya visto", r: "no" },
        { t: "Tener ganas de quedárselo", r: "parte", x: "Las ganas llegan solas. Lo que hace con el billete sí depende de ella." },
        { t: "Preguntar a la niña qué ha perdido", r: "si" },
        { t: "Llevarlo a conserjería si no aparece su dueña", r: "si" },
        { t: "Que la niña le dé las gracias", r: "no" },
      ],
    },
    idea: "Lo que no es tuyo se devuelve. Ser justo es pensar en quien lo está buscando.",
    frase: { t: "Somos partes de un mismo gran cuerpo. La naturaleza nos hizo familia.", autor: "Séneca", obra: "Cartas a Lucilio, 95" },
    reto: "Hoy, si encuentras algo que no es tuyo, averigua de quién es o llévalo a objetos perdidos.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "¿Para qué sirven las normas?",
    historia:
      "Mario cree que la norma de levantar la mano es una tontería de pequeños. Un día, la tutora propone probar una asamblea sin ella. A los dos minutos hablan seis a la vez, Marta no consigue decir su idea y dos compañeros acaban enfadados por quién lo dijo primero. Cuando la tutora pregunta qué ha pasado, Mario se rasca la cabeza.",
    pregunta: "¿Qué ha descubierto Mario? ¿Qué norma de la clase te parece importante y a quién protege?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Esperar tu turno para hablar", r: "templanza" },
        { t: "Dejar hablar a quien casi nunca participa", r: "justicia" },
        { t: "Proponer en asamblea cambiar una norma injusta", r: "coraje", x: "También es sabiduría: pensar la norma y dar razones." },
        { t: "Preguntar para qué sirve una norma antes de criticarla", r: "sabiduria" },
        { t: "Cumplir la norma aunque la profe no mire", r: "justicia" },
      ],
    },
    idea: "Las buenas normas no están para fastidiar: protegen a todos, sobre todo a quien tiene menos fuerza o menos voz.",
    frase: { t: "Lo que no es bueno para la colmena, tampoco es bueno para la abeja.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 54" },
    reto: "Elige una norma de la clase y explícale a tu pareja a quién ayuda.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "La paz del patio",
    historia:
      "Es 30 de enero, Día Escolar de la No Violencia y la Paz. Pero en el patio, 5.º A y 5.º B vuelven a discutir por la pista de fútbol, como cada semana. Hay gritos y un balón que sale volando lejos. Esa tarde, Paula propone algo en la asamblea: un calendario de turnos para la pista y un rincón para arreglar los problemas hablando.",
    pregunta: "¿La paz es algo que solo firman los países o también se construye en un patio? ¿Qué harías tú para que hubiera más paz en el tuyo?",
    juego: {
      consigna: "¿Depende de nosotros?",
      tipo: "DEPENDE",
      items: [
        { t: "Que la pista sea pequeña para todos", r: "no" },
        { t: "Proponer turnos para usar la pista", r: "si" },
        { t: "Hablar sin gritar cuando hay un problema", r: "si" },
        { t: "Que el otro grupo acepte el acuerdo", r: "parte", x: "No depende solo de nosotros, pero proponerlo bien ayuda mucho." },
        { t: "Pedir ayuda a un adulto si no nos entendemos", r: "si" },
        { t: "Que nunca haya ningún conflicto", r: "no", x: "Los conflictos pasan. La paz es cómo los resolvemos." },
      ],
    },
    nota: "Si una discusión acaba en empujones, amenazas o se repite contra alguien, se avisa a un adulto de confianza. Eso siempre está en tu mano.",
    idea: "La paz no es que nunca haya conflictos, sino resolverlos hablando y de forma justa. Empieza en lo pequeño: un patio, una clase, una mesa.",
    frase: { t: "La amabilidad sincera es invencible.", autor: "Marco Aurelio", obra: "Meditaciones, XI, 18" },
    reto: "Hoy, si surge un roce, propón una solución justa en lugar de ganar la discusión.",
  },
  {
    bloque: 5,
    virtud: "justicia",
    titulo: "Justo también conmigo",
    historia:
      "Valeria ha organizado el mercadillo solidario de la clase: ha hecho los carteles, los turnos y la caja. Cuando la tutora la felicita delante de todos, Valeria se encoge: «Qué va, ha sido suerte». Por la tarde, su hermano le pregunta qué tal ha salido, y ella solo habla de lo que falló.",
    pregunta: "¿Es justo que Valeria no se reconozca lo que hizo? ¿Qué diferencia hay entre presumir y reconocer tu propio esfuerzo?",
    juego: {
      consigna: "¿Es un hecho o es lo que Valeria se dice?",
      tipo: "HECHO",
      items: [
        { t: "Valeria hizo los carteles y los turnos", r: "si" },
        { t: "«Ha sido suerte»", r: "no" },
        { t: "La tutora la ha felicitado", r: "si" },
        { t: "«Si digo que lo hice bien, soy una creída»", r: "no", x: "Reconocer tu esfuerzo no es presumir, mientras no hagas pequeños a los demás." },
        { t: "Se olvidaron de poner precio a los bizcochos", r: "si" },
        { t: "«Como falló algo, todo salió mal»", r: "no" },
      ],
    },
    idea: "La justicia también se practica con uno mismo: darte lo que te corresponde, ni más ni menos. Reconocer tu esfuerzo no es presumir.",
    frase: { t: "Mira dentro de ti. Dentro está la fuente del bien, y siempre puede brotar si sigues cavando.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 59" },
    reto: "Hoy, si alguien te felicita, en vez de «qué va», prueba a decir: «Gracias, me esforcé mucho».",
  },
]);
