// La Ciudadela · sesiones del bloque 6 y 7: Coraje y Templanza
window.CIUDADELA_NUEVAS = (window.CIUDADELA_NUEVAS || []).concat([
  // ---------------- Bloque 6 · Coraje (febrero) ----------------
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "La muralla de las divisiones",
    historia:
      "Hugo lleva tres días sin entender las divisiones con decimales. Cuando la maestra pregunta si hay dudas, él mira la mesa y no levanta la mano. En casa copia los resultados del final del libro para que nadie note nada. El viernes hay control y Hugo siente un nudo en la tripa cada vez que lo piensa.",
    pregunta: "¿Por qué crees que a Hugo le cuesta tanto pedir ayuda? ¿Qué le diríais si fuerais sus compañeros de mesa?",
    juego: {
      consigna: "¿Depende de Hugo?",
      tipo: "DEPENDE",
      items: [
        { t: "Levantar la mano y decir «no lo entiendo»", r: "si" },
        { t: "Que las divisiones con decimales sean difíciles", r: "no" },
        { t: "Pedir a un compañero que se lo explique", r: "si" },
        { t: "Que nadie piense nada al verle preguntar", r: "no", x: "Lo que piensen los demás no depende de él. Y casi siempre piensan: «yo tampoco lo entendía»." },
        { t: "Entenderlo antes del viernes", r: "parte", x: "Depende de que pregunte y practique, pero también de cuánto tiempo y ayuda tenga." },
        { t: "Sentir vergüenza al preguntar", r: "parte", x: "La vergüenza llega sola. Preguntar a pesar de ella sí depende de él." },
      ],
    },
    idea: "Pedir ayuda no es de débiles: es de valientes. Hace falta coraje para decir «no lo sé» delante de los demás.",
    frase: { t: "No te dé vergüenza que te ayuden. Como el soldado que no puede subir solo la muralla, a veces necesitamos una mano.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 7" },
    reto: "Hoy pregunta una duda que tengas, en clase o en casa, aunque te dé un poco de vergüenza.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "El estuche estaba en mi mochila",
    historia:
      "Aitana no encuentra su estuche nuevo y, delante de toda la clase, dice que seguro que lo ha cogido Iker, que se sienta a su lado. Iker se pone rojo y dice que no. Por la tarde, al vaciar la mochila en casa, Aitana encuentra el estuche en el bolsillo pequeño. Al día siguiente, al entrar en clase, ve a Iker colgando su abrigo.",
    pregunta: "¿Qué puede hacer Aitana ahora? ¿Por qué cuesta tanto reconocer un error cuando lo han oído todos?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Decir delante de la clase: «Me equivoqué, perdona, Iker»", r: "coraje" },
        { t: "Comprobar la mochila antes de acusar a nadie", r: "sabiduria" },
        { t: "Querer que Iker quede limpio ante todos", r: "justicia" },
        { t: "No pasarse la mañana dándose la culpa sin parar", r: "templanza", x: "Reconocer el error sí; castigarse todo el día, no. Es el punto justo." },
        { t: "Pedir perdón aunque sienta la cara ardiendo", r: "coraje" },
        { t: "Escuchar a Iker antes de decir nada más", r: "sabiduria", x: "También podría ser justicia: escuchar a quien has tratado mal es darle su lugar." },
      ],
    },
    idea: "Reconocer un error en voz alta da miedo, pero repara el daño. Equivocarse es humano; esconderlo es lo que lo hace más grande.",
    frase: { t: "Si alguien me demuestra que me equivoco, cambiaré con gusto de opinión. Busco la verdad, y la verdad nunca ha hecho daño a nadie.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 21" },
    reto: "Si hoy te equivocas en algo, dilo tú primero: «Me he equivocado». Fíjate en cómo reaccionan los demás.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "Un no que cuesta decir",
    historia:
      "Al salir del cole, Pablo e Izan quieren llamar a todos los timbres de un portal y salir corriendo. Mateo dice que no le apetece. «¡Venga, no seas miedica!», le insisten, y uno le tira de la mochila. Mateo nota cómo le sube el calor a la cara. Si dice que no otra vez, a lo mejor se enfadan con él. Si dice que sí, va a hacer algo que no quiere.",
    pregunta: "¿Quién está siendo más valiente en esta historia? ¿Qué podría decir Mateo para que su «no» suene firme?",
    juego: {
      consigna: "¿Puede resolverlo Mateo o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Le insisten para tocar timbres y salir corriendo", r: "yo", x: "Puede decir «no» y marcharse. Si le persiguen o le amenazan, ya es otra cosa." },
        { t: "Su amigo se enfada un rato porque dijo que no", r: "yo" },
        { t: "Le amenazan con pegarle si no lo hace", r: "adulto" },
        { t: "Un chico mayor le exige que coja algo de una tienda", r: "adulto" },
        { t: "Le llaman «miedica» una vez en el patio", r: "yo", x: "Si pasa todos los días o le hace daño, hay que contarlo." },
        { t: "Le obligan a guardar un secreto que le hace sentir mal", r: "adulto" },
      ],
    },
    nota: "Si alguien te amenaza, te obliga o te pide guardar un secreto que te hace daño, cuéntaselo a un adulto de confianza. Eso siempre depende de ti y no tienes que resolverlo solo.",
    idea: "Decir «no» a lo que no quieres hacer también es coraje, aunque los demás lo llamen miedo. El valiente es quien elige, no quien obedece al grupo.",
    frase: { t: "Si no está bien, no lo hagas. Si no es verdad, no lo digas.", autor: "Marco Aurelio", obra: "Meditaciones, XII, 17" },
    reto: "Piensa y ensaya en voz baja una frase corta para decir «no» con calma: «No me apetece, yo me voy».",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "La primera presa",
    historia:
      "Irina va al cumpleaños de Lola en un rocódromo. Nunca ha escalado y, solo con ver la pared, ya ha decidido que se va a caer. Lola sube la primera con cara de felicidad. El monitor le ajusta el arnés a Irina y todos esperan. Irina pone un pie en la primera presa, lo quita y lo vuelve a poner.",
    pregunta: "¿De qué tiene miedo Irina en realidad? ¿Os ha pasado con una comida, un deporte o una actividad nueva?",
    juego: {
      consigna: "¿Es un hecho o es lo que Irina se dice?",
      tipo: "HECHO",
      items: [
        { t: "Nunca ha escalado", r: "si" },
        { t: "Seguro que me caigo y hago el ridículo", r: "no" },
        { t: "A Lola le encanta escalar", r: "si" },
        { t: "Si no llego arriba, voy a quedar fatal", r: "no" },
        { t: "Puede probar a subir hasta la segunda presa", r: "si" },
        { t: "Las cosas nuevas siempre me salen mal", r: "no" },
      ],
    },
    idea: "Probar algo nuevo, aunque sea un paso pequeño, es una forma de coraje. Y si no te gusta, también has aprendido algo.",
    frase: { t: "Son más las cosas que nos asustan que las que nos hacen daño. Sufrimos más en la imaginación que en la realidad.", autor: "Séneca", obra: "Cartas a Lucilio, 13" },
    reto: "Esta semana prueba una cosa nueva: una comida, un juego del patio o hablar en un grupo distinto.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "Mi idea en el debate",
    historia:
      "En clase hay un debate: ¿debería haber un día a la semana sin balón en el patio? Casi todos gritan que no. Salma piensa que sí, porque así podrían jugar también los que se quedan en las esquinas. Tiene preparado lo que quiere decir, pero ve que nadie más levanta la mano por su lado. Se le seca la boca.",
    pregunta: "¿Qué necesita Salma para decir lo que piensa? ¿Y qué necesitan los demás para escucharla de verdad?",
    juego: {
      consigna: "¿Me paso, me quedo corta o doy en el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Decir su idea con calma aunque la mayoría piense otra cosa", r: "justo" },
        { t: "Callarse aunque tenía buenas razones", r: "corto" },
        { t: "Gritar para que los demás no puedan hablar", r: "pasa" },
        { t: "Cambiar de opinión si le dan una razón mejor", r: "justo", x: "Cambiar de idea por una buena razón no es rendirse: es pensar bien." },
        { t: "Decir «lo que queráis» solo para no discutir", r: "corto" },
        { t: "Burlarse de la idea de los demás", r: "pasa" },
      ],
    },
    idea: "Defender tu idea con respeto es coraje. No hace falta gritar ni ganar: basta con decirla y escuchar las de los demás.",
    frase: { t: "Sé como el acantilado contra el que rompen las olas: se mantiene firme, y a su alrededor el agua se calma.", autor: "Marco Aurelio", obra: "Meditaciones, IV, 49" },
    reto: "Hoy, cuando no estés de acuerdo con algo, dilo con calma y explica tu razón en una frase.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "Cuando Lucas no está",
    historia:
      "En el recreo, Vera cuenta que Lucas, que hoy ha faltado, hace ganchillo con su abuela. «Eso es de niñas», dice alguien, y el corro se ríe. Alejandro ha visto el cojín que hizo Lucas y le pareció chulísimo, pero nota que se le acelera el corazón: si lo dice, igual se ríen de él también.",
    pregunta: "¿Existen cosas «de niños» y cosas «de niñas»? ¿Qué podría decir Alejandro para defender a Lucas aunque no esté?",
    juego: {
      consigna: "¿Se pasa, se queda corto o da en el punto justo de coraje?",
      tipo: "PUNTO",
      items: [
        { t: "Reírse con el corro para no quedar mal", r: "corto" },
        { t: "Decir: «Pues yo he visto su cojín y es chulísimo»", r: "justo" },
        { t: "Llamar idiotas a los que se ríen", r: "pasa" },
        { t: "Cambiar de tema sin decir lo que piensa", r: "corto", x: "Evita el mal rato, pero Lucas sigue siendo el blanco de las risas." },
        { t: "Preguntar: «¿Por qué va a ser de niñas?»", r: "justo" },
        { t: "Contárselo a Lucas para que se enfade con ellos", r: "pasa", x: "Le haría daño a Lucas y encendería más la pelea." },
      ],
    },
    nota: "Si las burlas a alguien se repiten, esté delante o no, contárselo a un adulto de confianza SIEMPRE depende de ti: eso no se aguanta ni se arregla solo.",
    idea: "Defender a quien no está delante también es coraje. Y las aficiones no tienen género: cada uno puede disfrutar de lo que le guste.",
    frase: { t: "Primero decide qué persona quieres ser. Después, haz lo que tengas que hacer.", autor: "Epicteto", obra: "Disertaciones, III, 23" },
    reto: "Si hoy oyes una burla sobre alguien que no está, di con calma algo bueno de esa persona.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "El banco del fondo",
    historia:
      "Todos los recreos, Rubén se sienta en el banco del fondo y mira cómo juegan los demás. Chen se ha dado cuenta hace semanas. Hoy ha pensado en acercarse, pero se ha quedado quieto: ¿y si Rubén no quiere hablar? ¿Y si sus amigos se ríen de él por irse con el niño que está solo? Suena el timbre y el recreo se acaba otra vez.",
    pregunta: "¿Por qué hace falta coraje para acercarse a alguien que está solo? ¿Qué pequeño primer paso podría dar Chen?",
    juego: {
      consigna: "¿Depende de Chen?",
      tipo: "DEPENDE",
      items: [
        { t: "Acercarse y decir «¿Quieres jugar?»", r: "si" },
        { t: "Que Rubén diga que sí", r: "no", x: "Quizá prefiera estar tranquilo. Lo importante es que sepa que puede contar con alguien." },
        { t: "Lo que piensen sus amigos", r: "no" },
        { t: "Invitar a sus amigos a jugar todos juntos", r: "si" },
        { t: "Que Rubén deje de estar solo en los recreos", r: "parte", x: "Chen puede ayudar mucho, pero también ayudan otros compañeros y los maestros." },
        { t: "Contárselo a un adulto si alguien aparta a Rubén a propósito", r: "si" },
      ],
    },
    nota: "Si alguien está solo porque los demás lo apartan o se burlan de él, se cuenta a un adulto de confianza. Contarlo siempre depende de ti: no hay que aguantarlo ni resolverlo solo.",
    idea: "Acercarse a quien está solo cuesta más que quedarse con los de siempre. Por eso es coraje, aunque dure solo un minuto.",
    frase: { t: "La amabilidad sincera es invencible.", autor: "Marco Aurelio", obra: "Meditaciones, XI, 18" },
    reto: "Hoy habla un momento en el recreo o en el comedor con alguien con quien casi nunca hablas.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "Un cuatro no es el final",
    historia:
      "Daniela estudió para el examen de Lengua y ha sacado un cuatro. Se ha equivocado sobre todo en las tildes. Al ver la nota ha guardado el examen en la mochila sin mirarlo y ha pensado: «Ya no pienso estudiar más, para qué». La maestra ha dicho que el viernes habrá otra oportunidad para quien quiera.",
    pregunta: "¿Qué hace falta para volver a intentarlo después de suspender? ¿Qué le diríais a Daniela si fuera vuestra amiga?",
    juego: {
      consigna: "¿Es un hecho o es lo que Daniela se dice?",
      tipo: "HECHO",
      items: [
        { t: "He sacado un cuatro en Lengua", r: "si" },
        { t: "Soy malísima en Lengua", r: "no" },
        { t: "La mayoría de mis fallos son de tildes", r: "si" },
        { t: "Por mucho que estudie, no voy a aprobar", r: "no" },
        { t: "El viernes hay otra oportunidad", r: "si" },
        { t: "Estudiar no sirve para nada", r: "no" },
      ],
    },
    idea: "Suspender duele, y es normal sentirse mal. El coraje está en volver a mirar el examen, ver qué falló y probar otra vez.",
    frase: { t: "Cada capacidad crece con la práctica: se aprende a caminar caminando y a correr corriendo.", autor: "Epicteto", obra: "Disertaciones, II, 18" },
    reto: "Busca un ejercicio o examen que te saliera mal y repite hoy una sola parte de él.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "Cinco minutos más de sábana",
    historia:
      "Es lunes de febrero, todavía es de noche y hace frío. Suena el despertador e Iván se tapa hasta la cabeza. «Cinco minutos más», piensa, y luego otros cinco. Al final se levanta corriendo, desayuna de pie, se deja la flauta en casa y llega a clase de mal humor. Su madre le ha llamado cuatro veces.",
    pregunta: "¿Por qué cuesta tanto salir de la cama algunas mañanas? ¿Qué podría hacer Iván la noche antes y por la mañana?",
    juego: {
      consigna: "¿Depende de Iván?",
      tipo: "DEPENDE",
      items: [
        { t: "Que haga frío por la mañana", r: "no" },
        { t: "Levantarse cuando suena el despertador", r: "si" },
        { t: "Tener sueño los lunes", r: "parte", x: "El sueño llega solo, pero acostarse antes ayuda a tener menos." },
        { t: "Preparar la mochila la noche antes", r: "si" },
        { t: "Que el cole empiece a las nueve", r: "no" },
        { t: "Llegar de buen humor", r: "parte", x: "No siempre se consigue, pero empezar sin prisas ayuda mucho." },
      ],
    },
    idea: "Levantarse cuando cuesta es un coraje pequeño de todos los días. Hasta un emperador tenía que recordárselo cada mañana.",
    frase: { t: "Por la mañana, cuando te cueste levantarte, piensa: «Me levanto para hacer mi trabajo de ser humano».", autor: "Marco Aurelio", obra: "Meditaciones, V, 1" },
    reto: "Esta noche deja preparada la mochila y mañana levántate a la primera. Cuenta en clase cómo te fue.",
  },
  {
    bloque: 6,
    virtud: "coraje",
    titulo: "Una carta como las de Séneca",
    historia:
      "Para el Día de Andalucía, la clase de Martina prepara un mural. Ella descubre que Séneca nació en Córdoba, fue escritor y consejero en Roma y escribió cartas a su amigo Lucilio. La maestra propone escribir una carta a un amigo, como él. Martina quiere escribir a Noa para pedirle perdón por algo del mes pasado, pero no sabe si se atreverá a dársela.",
    pregunta: "¿Por qué a veces es más fácil escribir algo difícil que decirlo? ¿Qué te gustaría decirle a alguien en una carta?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Darle a Noa la carta pidiendo perdón", r: "coraje" },
        { t: "Comprobar en un libro dónde nació Séneca antes de escribirlo", r: "sabiduria" },
        { t: "Repartir los rotuladores para que todos puedan pintar", r: "justicia" },
        { t: "En el desayuno andaluz, coger una tostada y dejar para otros", r: "templanza" },
        { t: "Leer su carta en voz alta aunque le tiemble la voz", r: "coraje" },
        { t: "Explicar la fiesta a un compañero recién llegado", r: "justicia", x: "También es sabiduría: compartir lo que sabes para que nadie se quede fuera." },
      ],
    },
    idea: "Séneca, nacido en Córdoba, daba consejos por carta a su amigo. Escribir lo que cuesta decir también es una forma de coraje.",
    frase: { t: "Ningún bien nos alegra de verdad si no tenemos con quién compartirlo.", autor: "Séneca", obra: "Cartas a Lucilio, 6" },
    reto: "Escribe una carta corta a alguien: un consejo, un gracias o un perdón. Tú decides si se la das.",
  },

  // ---------------- Bloque 7 · Templanza (marzo) ----------------
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "La tercera porción de tarta",
    historia:
      "En el cumpleaños de Leo hay patatas, gominolas, bocadillos y una tarta de chocolate enorme. Valentina ya se ha comido dos porciones y ahora va a por la tercera, aunque empieza a notar la tripa rara. Luego hay juegos en el jardín y no quiere perdérselos. Valentina tiene el plato en la mano y la tarta delante.",
    pregunta: "¿Qué pasa por la cabeza de Valentina? ¿Cómo se puede disfrutar de una fiesta sin terminar con dolor de tripa?",
    juego: {
      consigna: "¿Se pasa, se queda corta o da en el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Tercera porción aunque le duele la tripa", r: "pasa" },
        { t: "Una porción y disfrutarla despacio", r: "justo" },
        { t: "No probar nada para no pasarse", r: "corto", x: "Templanza no es prohibirse todo: es disfrutar sin pasarse." },
        { t: "Llenarse los bolsillos de gominolas para luego", r: "pasa" },
        { t: "Parar cuando nota que ya está a gusto", r: "justo" },
        { t: "Comer un poco de todo y beber agua", r: "justo" },
      ],
    },
    idea: "La templanza no es decir que no a todo: es encontrar el punto justo para disfrutar sin hacerte daño.",
    frase: { t: "Primero decide qué persona quieres ser. Después, haz lo que tengas que hacer.", autor: "Epicteto", obra: "Disertaciones, III, 23" },
    reto: "Hoy, en la comida o la merienda, come despacio y para cuando notes que ya estás a gusto.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "¡Espera, que falta lo mejor!",
    historia:
      "Samuel ha vuelto del puente en la nieve y en el recreo lo cuenta todo: el trineo, la caída, el hotel, el perro de los vecinos. Cada vez que alguien empieza a hablar, Samuel dice «¡Espera, espera, que falta lo mejor!». Poco a poco, sus amigos se van yendo a jugar. Samuel no entiende por qué.",
    pregunta: "¿Qué no está viendo Samuel? ¿Cómo sabes cuándo es tu turno de hablar y cuándo el de escuchar?",
    juego: {
      consigna: "¿Se pasa, se queda corto o da en el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Contar su viaje y luego preguntar «¿Y tú?»", r: "justo" },
        { t: "Interrumpir cada vez que otro empieza a hablar", r: "pasa" },
        { t: "No contar nunca nada suyo para no molestar", r: "corto", x: "Lo tuyo también importa. El punto justo es compartir y escuchar." },
        { t: "Escuchar mirando a la cara a quien habla", r: "justo" },
        { t: "Hablar veinte minutos sin parar", r: "pasa" },
        { t: "Contestar solo «vale» a todo lo que te cuentan", r: "corto" },
      ],
    },
    idea: "Una buena conversación es como un partido de tenis: la pelota va y viene. Escuchar también es una forma de templanza.",
    frase: { t: "Si quieres que te quieran, quiere.", autor: "Séneca", obra: "Cartas a Lucilio, 9" },
    reto: "Hoy, en una conversación, haz al menos dos preguntas a la otra persona y escucha la respuesta hasta el final.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "Las judías que no crecen",
    historia:
      "En Ciencias, cada alumno ha plantado una judía en un vaso con algodón. Carla lo mira cada mañana nada más llegar. Al tercer día, como no ve nada, lo riega el doble, lo cambia de ventana y hasta levanta el algodón para mirar la semilla. Su compañero Iker no toca el suyo, y al sexto día le asoma un brote verde.",
    pregunta: "¿Qué le pasa a Carla con la espera? ¿Qué cosas de tu vida necesitan tiempo y no se pueden acelerar?",
    juego: {
      consigna: "¿Depende de Carla?",
      tipo: "DEPENDE",
      items: [
        { t: "Cuánto tarda la semilla en brotar", r: "no" },
        { t: "Regarla lo justo, como dijo la maestra", r: "si" },
        { t: "Sentir impaciencia cada mañana", r: "parte", x: "La impaciencia llega sola. Lo que hace con ella, sí depende de Carla." },
        { t: "Dejar el algodón tranquilo", r: "si" },
        { t: "Que brote antes que la de Iker", r: "no" },
        { t: "Apuntar en un cuaderno lo que ve cada día", r: "si" },
      ],
    },
    idea: "Hay cosas que necesitan su tiempo y no se pueden acelerar. Templanza también es saber esperar y cuidar sin agobiar.",
    frase: { t: "Nada grande nace de repente, ni siquiera un racimo de uvas o un higo. Primero florece, luego da fruto y después madura.", autor: "Epicteto", obra: "Disertaciones, I, 15" },
    reto: "Hoy, cuando tengas que esperar algo, busca qué hacer mientras tanto en vez de protestar.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "La paga del sábado",
    historia:
      "Adam quiere comprarse un balón de baloncesto que cuesta veinte euros. Cada sábado le dan cinco euros de paga. Este sábado, al pasar por el quiosco, se compra chucherías, un sobre de cromos y un llavero. El lunes ya no le queda nada. Hace la cuenta y se da cuenta de que así el balón nunca llega.",
    pregunta: "¿Qué le pasa a Adam con el dinero? ¿Cómo podría darse algún capricho y aun así llegar al balón?",
    juego: {
      consigna: "¿Se pasa, se queda corto o da en el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Gastarse toda la paga el mismo sábado", r: "pasa" },
        { t: "Guardar cuatro euros y gastar uno en algo que le apetece", r: "justo" },
        { t: "No gastar nunca nada aunque ya tenga el balón", r: "corto", x: "Ahorrar tiene sentido si sabes para qué. Guardar por guardar también es pasarse de largo." },
        { t: "Apuntar en un papel cuánto lleva ahorrado", r: "justo" },
        { t: "Pedir dinero prestado a su hermana para chucherías", r: "pasa" },
        { t: "Esperar una semana antes de comprar algo que ve", r: "justo" },
      ],
    },
    idea: "El dinero, como la comida o el tiempo, necesita un punto justo. Saber qué quieres te ayuda a no gastarlo todo de golpe.",
    frase: { t: "Si uno no sabe a qué puerto se dirige, ningún viento le es favorable.", autor: "Séneca", obra: "Cartas a Lucilio, 71" },
    reto: "Piensa en algo que te gustaría conseguir. Escribe cuánto cuesta y cuántas semanas tendrías que ahorrar.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "El cinco a cero del jueves",
    historia:
      "El equipo de Nerea gana cinco a cero en el partido de la hora del patio. Al marcar el último gol, dos compañeros de su equipo se ponen a bailar delante de la portería contraria y a gritar «¡Paquetes, paquetes!». Los del otro equipo se van cabizbajos. Nerea está feliz por ganar, pero algo no le gusta.",
    pregunta: "¿Qué es lo que no le gusta a Nerea? ¿Cómo se puede celebrar una victoria sin hacer sentir mal a nadie?",
    juego: {
      consigna: "¿Se pasa, se queda corto o da en el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Abrazarse con su equipo y chocar las manos", r: "justo" },
        { t: "Bailar delante de los que han perdido", r: "pasa" },
        { t: "Dar la mano a los del otro equipo", r: "justo" },
        { t: "Recordarles el cinco a cero toda la semana", r: "pasa" },
        { t: "Hacer como si no hubieran ganado para no molestar", r: "corto", x: "Alegrarse de ganar está bien. Lo que sobra es la burla." },
        { t: "Decir «buen partido» al portero contrario", r: "justo" },
      ],
    },
    nota: "Una burla puntual se puede hablar en el momento. Si alguien se burla de otro una y otra vez, se cuenta a un adulto de confianza: eso siempre depende de ti.",
    idea: "Ganar sin burlarse es templanza: la alegría cabe entera sin necesidad de hacer pequeño al otro.",
    frase: { t: "Las ovejas no enseñan a los pastores cuánto han comido: lo digieren y dan lana y leche. Tú tampoco presumas de lo que sabes: demuéstralo con lo que haces.", autor: "Epicteto", obra: "Enquiridión, 46" },
    reto: "La próxima vez que ganes en algo, di una frase amable a quien ha perdido.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "¿Dónde se ha ido mi tarde?",
    historia:
      "Gonzalo llega a casa a las cinco con deberes de Matemáticas y la idea de bajar a la plaza. Primero merienda viendo vídeos en el móvil de su padre. Luego juega un rato con el perro. Luego otro vídeo. A las ocho y media se da cuenta de que no ha hecho los deberes, no ha bajado a la plaza y ya es hora de cenar.",
    pregunta: "¿En qué momento se le escapó la tarde a Gonzalo? ¿Cómo podría repartir mejor su tiempo mañana?",
    juego: {
      consigna: "¿Depende de Gonzalo?",
      tipo: "DEPENDE",
      items: [
        { t: "Tener deberes de Matemáticas", r: "no" },
        { t: "Decidir qué hace primero al llegar", r: "si" },
        { t: "Que la tarde dure solo unas horas", r: "no" },
        { t: "Dejar de ver vídeos cuando se lo propone", r: "parte", x: "Cuesta, porque los vídeos enganchan. Ponerse un límite antes de empezar ayuda." },
        { t: "Hacer una lista de lo que quiere hacer", r: "si" },
        { t: "Que sus amigos sigan en la plaza a las siete", r: "no" },
      ],
    },
    idea: "El tiempo se escapa a trocitos si no lo cuidas. Ordenar la tarde es darle a cada cosa su sitio, también al juego.",
    frase: { t: "No es que tengamos poco tiempo, es que perdemos mucho.", autor: "Séneca", obra: "Sobre la brevedad de la vida, 1" },
    reto: "Esta tarde escribe en un papel tres cosas que quieres hacer y en qué orden. Tacha cada una al terminarla.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "La risa que se escapa",
    historia:
      "Bruno lee en clase un poema que ha escrito sobre el pueblo de su abuela. Le tiembla un poco la voz y todos escuchan en silencio. De pronto, alguien pone una cara rara y a Fátima le entra la risa. Intenta aguantarla, pero se le escapa un bufido. Bruno levanta la vista del papel y se pone rojo.",
    pregunta: "¿Tiene la culpa Fátima de que le entre la risa? ¿Qué puede hacer cuando nota que se le escapa en un momento serio?",
    juego: {
      consigna: "¿Se pasa, se queda corta o da en el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Reírse a carcajadas mientras Bruno lee", r: "pasa" },
        { t: "Respirar hondo y mirar un punto fijo", r: "justo" },
        { t: "Pedir salir un momento si no puede parar", r: "justo" },
        { t: "Estar seria todo el día por miedo a reírse", r: "corto", x: "La risa no es mala. Solo hay que elegir el momento." },
        { t: "Decirle a Bruno después: «Perdona, no me reía de ti»", r: "justo" },
        { t: "Hacer más caras para que se ría más gente", r: "pasa" },
      ],
    },
    idea: "La risa nerviosa llega sola, no la elegimos. Lo que sí podemos es frenarla a tiempo y reparar si hemos hecho daño.",
    frase: { t: "Igual que sentimos un escalofrío cuando nos salpica agua fría, hay movimientos del ánimo que llegan sin que los elijamos.", autor: "Séneca", obra: "Sobre la ira, II, 2" },
    reto: "Hoy, si alguien habla de algo que le importa, escúchale sin reírte y dile algo bonito al final.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "Las zapatillas de Aroa",
    historia:
      "Aroa llega a clase con unas zapatillas nuevas que brillan en la oscuridad. Todo el mundo se acerca a verlas. Paula mira las suyas, que tienen un agujerito en la punta, y siente algo pinchándole por dentro. Cuando Aroa le pregunta si le gustan, Paula contesta: «Bah, son un poco horteras». Luego se siente peor que antes.",
    pregunta: "¿Qué sentía Paula? ¿Por qué creéis que contestó así, y qué otra cosa podría haber dicho?",
    juego: {
      consigna: "¿Es un hecho o es lo que Paula se dice?",
      tipo: "HECHO",
      items: [
        { t: "Aroa tiene zapatillas nuevas", r: "si" },
        { t: "Todo el mundo tiene cosas mejores que yo", r: "no" },
        { t: "Mis zapatillas tienen un agujerito", r: "si" },
        { t: "Si tuviera esas zapatillas, sería feliz siempre", r: "no" },
        { t: "Aroa se cree mejor que nadie", r: "no" },
        { t: "Con mis zapatillas puedo correr y jugar", r: "si" },
      ],
    },
    idea: "Sentir envidia es humano. Lo que nos hace daño es lo que nos decimos después. Mirar lo que ya tienes ayuda a soltarla.",
    frase: { t: "Lo que inquieta a las personas no son las cosas, sino las opiniones que tienen sobre las cosas.", autor: "Epicteto", obra: "Enquiridión, 5" },
    reto: "Si hoy sientes envidia de algo, dilo por dentro: «Siento envidia». Y después piensa en una cosa tuya que te guste.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "Diez cosas a la vez",
    historia:
      "Marcos hace los deberes en la mesa del salón con la tele puesta. A la vez, mira el grupo de mensajes de la familia en la tablet, se come un bocadillo y le contesta a su hermana Sara, que le pregunta cosas. Una hora después, solo ha hecho dos ejercicios y los dos están mal. «¡No me da tiempo a nada!», protesta.",
    pregunta: "¿Por qué no le cunde el tiempo a Marcos? ¿Hacéis vosotros varias cosas a la vez? ¿Qué pasa cuando lo hacéis?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Apagar la tele antes de empezar los deberes", r: "templanza" },
        { t: "Decirle a Sara: «Ahora no, te respondo en diez minutos»", r: "templanza", x: "También es justicia: le da una respuesta amable y cumple lo que dice." },
        { t: "Darse cuenta de que así no aprende nada", r: "sabiduria" },
        { t: "Preguntar a la maestra lo que no entendió", r: "coraje" },
        { t: "Dejar la tablet en otra habitación mientras estudia", r: "templanza" },
        { t: "Ayudar luego a Sara con sus deberes", r: "justicia" },
      ],
    },
    idea: "Hacer una cosa cada vez es templanza: la atención no se puede partir en diez trozos sin que se estropee.",
    frase: { t: "Quien está en todas partes no está en ninguna.", autor: "Séneca", obra: "Cartas a Lucilio, 2" },
    reto: "Hoy haz tus deberes con una sola cosa delante: nada de pantallas ni ruido. Mira cuánto tardas.",
  },
  {
    bloque: 7,
    virtud: "templanza",
    titulo: "Descansar también cuenta",
    historia:
      "Julia tiene natación los lunes, inglés los martes, música los miércoles y fútbol los jueves y los viernes. El sábado hay partido y el domingo quiere adelantar deberes. Esta semana está cansada, se enfada por todo y en natación le duele el hombro. Aun así, dice que no quiere faltar a nada porque «descansar es de vagos».",
    pregunta: "¿Estáis de acuerdo con Julia en que descansar es de vagos? ¿Cómo sabéis cuándo vuestro cuerpo necesita parar?",
    juego: {
      consigna: "¿Se pasa, se queda corta o da en el punto justo?",
      tipo: "PUNTO",
      items: [
        { t: "Nadar con el hombro dolorido para no faltar", r: "pasa" },
        { t: "Dormir nueve o diez horas cada noche", r: "justo" },
        { t: "Dejar una tarde libre a la semana para no hacer nada", r: "justo" },
        { t: "Faltar a todo en cuanto algo cuesta un poco", r: "corto" },
        { t: "Apuntarse a otra actividad más aunque ya está agotada", r: "pasa" },
        { t: "Contar en casa que le duele el hombro", r: "justo" },
      ],
    },
    idea: "Descansar no es de vagos: es parte de hacer las cosas bien. La templanza también es saber parar a tiempo.",
    frase: { t: "Vivir bien se consigue poco a poco, pero no es poca cosa.", autor: "Zenón de Citio", obra: "según Diógenes Laercio, Vidas, VII, 26" },
    reto: "Hoy busca diez minutos para descansar de verdad: sin deberes, sin pantallas, solo tumbarte, mirar o respirar.",
  },
]);
