// La Ciudadela · sesiones del bloque 0 (y 1): Mi ciudadela · Conozco mis emociones
window.CIUDADELA_NUEVAS = (window.CIUDADELA_NUEVAS || []).concat([
  // ---------------- Bloque 0 · Mi ciudadela (septiembre) ----------------
  {
    bloque: 0,
    virtud: "coraje",
    titulo: "Nueva clase, caras nuevas",
    historia: "Este año han mezclado las clases de 5.º y Salma ha caído en un grupo donde no está ninguna de sus amigas. En la fila, todos parecen conocerse ya. A la hora del recreo, Salma se sienta sola en un banco y mira de lejos a sus amigas de siempre, que juegan en la otra punta del patio.",
    pregunta: "¿Qué cosas de esta situación no puede cambiar Salma? ¿Qué pequeño paso sí podría dar mañana?",
    juego: {
      consigna: "¿Depende de Salma?",
      tipo: "DEPENDE",
      items: [
        { t: "En qué clase la han puesto", r: "no" },
        { t: "Sentirse sola los primeros días", r: "parte", x: "La emoción llega sola. Pero puede hacer cosas para que dure menos." },
        { t: "Saludar a alguien nuevo en la fila", r: "si" },
        { t: "Que los demás la inviten a jugar", r: "no", x: "Eso no depende de ella, pero preguntar «¿puedo jugar?» sí." },
        { t: "Ver a sus amigas de siempre en el comedor", r: "parte", x: "Puede buscarlas, aunque los turnos y las mesas no los decide ella." },
        { t: "Aprenderse los nombres de sus compañeros", r: "si" },
      ],
    },
    idea: "No elegimos el grupo que nos toca, pero sí cómo entramos en él. Un saludo es algo pequeño que siempre depende de ti.",
    frase: { t: "Si quieres que te quieran, quiere.", autor: "Séneca", obra: "Cartas a Lucilio, 9" },
    reto: "Hoy aprende el nombre de alguien de clase con quien casi no has hablado y salúdalo por su nombre.",
  },
  {
    bloque: 0,
    virtud: "justicia",
    titulo: "El compañero que me ha tocado",
    historia: "El maestro ha cambiado las mesas y a Mateo le ha tocado sentarse con Bruno. Casi no han hablado nunca, pero Mateo ya ha decidido que es un pesado porque el año pasado le oyó reírse muy alto en el autobús. Durante toda la mañana, Mateo apenas le mira y aparta su estuche hacia el borde de la mesa.",
    pregunta: "¿Qué sabe Mateo de Bruno de verdad? ¿Qué podría pasar si le diera una oportunidad?",
    juego: {
      consigna: "¿Es un hecho o es lo que Mateo se dice?",
      tipo: "HECHO",
      items: [
        { t: "Le han sentado con Bruno", r: "si" },
        { t: "Bruno es un pesado", r: "no" },
        { t: "El año pasado Bruno se rio alto en el autobús", r: "si" },
        { t: "Casi no han hablado nunca", r: "si" },
        { t: "Seguro que este curso va a ser horrible", r: "no" },
        { t: "Con Bruno no me voy a llevar bien", r: "no", x: "Todavía no lo sabe: solo lo sabrá si lo intenta." },
      ],
    },
    idea: "Lo que nos decimos sobre alguien puede pesar más que lo que esa persona hace. Antes de juzgar a alguien, conócelo.",
    frase: { t: "Lo que inquieta a las personas no son las cosas, sino las opiniones que tienen sobre las cosas.", autor: "Epicteto", obra: "Enquiridión, 5" },
    reto: "Hoy pregúntale a quien se sienta a tu lado algo que todavía no sepas de su vida.",
  },
  {
    bloque: 0,
    virtud: "sabiduria",
    titulo: "Excursión pasada por agua",
    historia: "Irina llevaba semanas esperando la excursión a la sierra. Esa mañana amanece nublado y, a mitad de ruta, empieza a caer una lluvia fina que no para. Los monitores cambian el plan: nada de subir al mirador, y la comida será bajo el techado del albergue. Irina resopla: «Ya se ha estropeado todo».",
    pregunta: "¿Se ha estropeado todo de verdad? ¿Qué cosas buenas pueden quedar todavía en ese día?",
    juego: {
      consigna: "¿Depende de Irina?",
      tipo: "DEPENDE",
      items: [
        { t: "Que llueva en la sierra", r: "no" },
        { t: "Que los monitores cambien el plan", r: "no" },
        { t: "Sentir decepción al ver la lluvia", r: "parte", x: "La decepción llega sola; decirse «se ha estropeado todo» ya es algo que ella añade." },
        { t: "Jugar a algo con su grupo en el albergue", r: "si" },
        { t: "Llevar chubasquero en la próxima excursión", r: "si" },
        { t: "Que el día acabe siendo divertido", r: "parte", x: "Depende de muchas cosas, y una de ellas es la actitud de Irina." },
      ],
    },
    idea: "La lluvia no la decides tú. Lo que haces con el día que queda, sí: el disgusto puede estropearlo más que la lluvia.",
    frase: { t: "¡Cuánto más daño nos hacen el enfado y el disgusto que las cosas que los provocan!", autor: "Marco Aurelio", obra: "Meditaciones, XI, 18" },
    reto: "Si hoy algo no sale como esperabas, busca una cosa buena que todavía puedas hacer con lo que queda.",
  },
  {
    bloque: 0,
    virtud: "justicia",
    titulo: "Si ella no recoge, yo tampoco",
    historia: "En casa de Gonzalo cada uno tiene sus tareas: él pone la mesa y ordena su cuarto. Esta tarde su hermana mayor tiene visita y ha dejado el salón patas arriba. Gonzalo piensa: «Si ella no recoge sus cosas, yo tampoco». Cuando su padre llega, encuentra la mesa sin poner y el cuarto de Gonzalo con ropa por el suelo.",
    pregunta: "¿Es justo lo que piensa Gonzalo? ¿Qué parte de la casa depende de él, haga lo que haga su hermana?",
    juego: {
      consigna: "¿Depende de Gonzalo?",
      tipo: "DEPENDE",
      items: [
        { t: "Que su hermana recoja sus cosas", r: "no" },
        { t: "Poner la mesa a su hora", r: "si" },
        { t: "Ordenar su cuarto", r: "si" },
        { t: "Que su padre llegue cansado del trabajo", r: "no" },
        { t: "Decirle a su hermana, sin gritar, que le molesta", r: "si" },
        { t: "Que la casa esté siempre ordenada", r: "parte", x: "Él pone su parte; el resto depende de toda la familia." },
      ],
    },
    idea: "Tu parte del trabajo depende de ti, aunque otros no hagan la suya. Si algo te parece injusto, se habla; no se copia.",
    frase: { t: "Por la mañana, cuando te cueste levantarte, piensa: «Me levanto para hacer mi trabajo de ser humano».", autor: "Marco Aurelio", obra: "Meditaciones, V, 1" },
    reto: "Hoy haz en casa una de tus tareas sin que nadie te lo tenga que recordar.",
  },
  {
    bloque: 0,
    virtud: "sabiduria",
    titulo: "La pulsera perdida",
    historia: "Valentina lleva siempre una pulsera de hilo que le hizo su prima. Al volver del recreo se da cuenta de que ya no la tiene. Se le hace un nudo en el estómago y no consigue concentrarse en la clase de Lengua. No sabe si buscarla ella sola, esperar a que aparezca o decírselo a la maestra.",
    pregunta: "¿Qué puede hacer Valentina por su cuenta? ¿Cuándo tiene sentido pedir ayuda a un adulto?",
    juego: {
      consigna: "¿Puede resolverlo Valentina o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Se le ha perdido un lápiz en clase", r: "yo" },
        { t: "No encuentra su chaqueta en el perchero", r: "yo" },
        { t: "Ha perdido la pulsera en el patio", r: "yo", x: "Puede buscarla y preguntar en objetos perdidos. Pedir ayuda a la maestra tampoco estaría mal." },
        { t: "Ha perdido la llave de casa", r: "adulto" },
        { t: "Un compañero le esconde el estuche todos los días", r: "adulto" },
        { t: "Le devuelven la pulsera si da su merienda", r: "adulto", x: "Eso es un chantaje: ya no es cosa de buscar, hay que contarlo." },
      ],
    },
    nota: "Si alguien te quita o te esconde tus cosas a menudo, o te pide algo a cambio de devolverlas, contárselo a un adulto de confianza siempre depende de ti. Eso no se aguanta ni se arregla solo.",
    idea: "Hay problemas que puedes resolver tú y otros para los que hace falta un adulto. Saber distinguirlos, y pedir ayuda, es de sabios.",
    frase: { t: "No te dé vergüenza que te ayuden. Como el soldado que no puede subir solo la muralla, a veces necesitamos una mano.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 7" },
    reto: "Piensa en qué adulto del cole confiarías si algo te preocupara. Hoy salúdalo por su nombre.",
  },
  {
    bloque: 0,
    virtud: "sabiduria",
    titulo: "Las normas del maestro nuevo",
    historia: "Este curso Chen tiene un maestro nuevo, don Ramiro, con normas distintas: nada de estuches encima de la mesa en los exámenes y la agenda firmada cada viernes. «Con la seño del año pasado no era así», protesta Chen. El primer viernes se le olvida la agenda y se pasa la mañana refunfuñando. Por la tarde, don Ramiro explica por qué le importa tanto esa firma.",
    pregunta: "¿Cambia algo que Chen conozca las razones de la norma? ¿Qué puede hacer si una norma le sigue pareciendo injusta?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Preguntar con educación para qué sirve una norma", r: "sabiduria" },
        { t: "Respirar antes de protestar en voz alta", r: "templanza" },
        { t: "Decir al maestro, con respeto, que algo le parece injusto", r: "coraje", x: "También es justicia: defender lo que te parece justo, con respeto." },
        { t: "Explicar las normas nuevas a un compañero que faltó", r: "justicia" },
        { t: "Admitir «me equivoqué» al ver que la norma tenía sentido", r: "sabiduria", x: "También hace falta un poco de coraje para reconocerlo delante de otros." },
      ],
    },
    idea: "Las normas cambian aunque tú no lo decidas. Entenderlas antes de juzgarlas es sabiduría, y opinar con respeto también depende de ti.",
    frase: { t: "Si alguien me demuestra que me equivoco, cambiaré con gusto de opinión. Busco la verdad, y la verdad nunca ha hecho daño a nadie.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 21" },
    reto: "Si hoy una norma te molesta, averigua para qué sirve antes de protestar.",
  },
  {
    bloque: 0,
    virtud: "templanza",
    titulo: "Mi fortaleza por dentro",
    historia: "Rubén ha tenido una mañana movida: un ruido tremendo en el comedor y un partido en el recreo donde todos gritaban a la vez. Al volver al aula, cierra los ojos un momento, respira despacio y se imagina una fortaleza con muros altos y un patio tranquilo dentro. Cuando los abre, nota el pecho más suelto.",
    pregunta: "¿Cómo sería tu ciudadela por dentro? ¿Cuándo te vendría bien refugiarte en ella un momento?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Respirar un minuto cuando el ruido le agobia", r: "justo" },
        { t: "Encerrarse en su mundo y no hablar en todo el día", r: "pasa", x: "La ciudadela es para recargar fuerzas y volver, no para esconderse siempre." },
        { t: "No parar nunca, aunque esté a punto de estallar", r: "corto" },
        { t: "Pedir a la maestra salir un momento a beber agua", r: "justo" },
        { t: "Hacer como que no oye cuando le hablan", r: "pasa" },
        { t: "Aguantarse todo hasta llegar a casa", r: "corto", x: "Puede buscar un momento de calma antes, y pedir ayuda si lo necesita." },
      ],
    },
    idea: "Dentro de ti hay un lugar tranquilo que nadie te puede quitar. Se entra para recuperar la calma y se sale para seguir viviendo.",
    frase: { t: "Una mente tranquila es una ciudadela: no hay lugar más fuerte donde refugiarse.", autor: "Marco Aurelio", obra: "Meditaciones, VIII, 48" },
    reto: "Hoy busca un momento para cerrar los ojos, respirar tres veces despacio y visitar tu ciudadela.",
  },

  // ---------------- Bloque 1 · Conozco mis emociones (octubre) ----------------
  {
    bloque: 1,
    virtud: "justicia",
    titulo: "Una alegría para compartir",
    historia: "Martina ha ganado el concurso de carteles del cole y su dibujo estará en la entrada todo el año. Se le escapa una sonrisa enorme y le entran ganas de dar saltos. Quiere contárselo a todo el mundo, pero ve que Aroa, que también se presentó y trabajó mucho en su cartel, está callada en su sitio.",
    pregunta: "¿Cómo puede Martina disfrutar de su alegría sin olvidarse de Aroa? ¿Con quién te gusta compartir tus alegrías?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Decirle a Aroa que su cartel también le gustaba", r: "justicia" },
        { t: "Celebrarlo sin restregárselo a nadie", r: "templanza" },
        { t: "Presentarse al concurso aunque le daba miedo perder", r: "coraje" },
        { t: "Pensar qué le salió bien para repetirlo", r: "sabiduria" },
        { t: "Dar las gracias a quien le prestó los rotuladores", r: "justicia", x: "Reconocer lo que otros aportan es darles lo que les corresponde." },
        { t: "Saltar de alegría en el patio, no en mitad de clase", r: "templanza" },
      ],
    },
    idea: "La alegría es para disfrutarla y para compartirla. Compartida crece, y si alguien está triste al lado, se puede celebrar sin hacerle daño.",
    frase: { t: "Ningún bien nos alegra de verdad si no tenemos con quién compartirlo.", autor: "Séneca", obra: "Cartas a Lucilio, 6" },
    reto: "Hoy cuéntale a alguien una cosa buena que te haya pasado y pregúntale por una suya.",
  },
  {
    bloque: 1,
    virtud: "sabiduria",
    titulo: "El sitio vacío del recreo",
    historia: "Pedro, el mejor amigo de Adam, se ha mudado a otra ciudad este verano. En el recreo, Adam no sabe con quién jugar y se queda mirando el banco donde siempre se sentaban juntos. Tiene los ojos brillantes y pocas ganas de hablar. Un compañero le dice: «Venga, no estés triste, que no es para tanto».",
    pregunta: "¿Ayuda que le digan «no estés triste»? ¿Qué le ayudaría de verdad a Adam?",
    juego: {
      consigna: "¿Depende de Adam?",
      tipo: "DEPENDE",
      items: [
        { t: "Que Pedro se haya mudado", r: "no" },
        { t: "Sentirse triste al ver el banco vacío", r: "no", x: "La tristeza llega sola y tiene sentido: echa de menos a su amigo." },
        { t: "Que la tristeza se vaya ya mismo", r: "no" },
        { t: "Contarle a alguien cómo se siente", r: "si" },
        { t: "Hablar con Pedro el fin de semana", r: "parte", x: "Puede pedirlo en casa, pero necesita que un adulto le ayude a llamar." },
        { t: "Acercarse a otro grupo en el recreo", r: "si" },
      ],
    },
    idea: "La tristeza nos dice que algo nos importa. No hay que echarla: hay que escucharla y dejar que alguien nos acompañe.",
    frase: { t: "No te dé vergüenza que te ayuden. Como el soldado que no puede subir solo la muralla, a veces necesitamos una mano.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 7" },
    reto: "Si hoy ves a alguien triste, no le digas «no es para tanto»: pregúntale si quiere compañía.",
  },
  {
    bloque: 1,
    virtud: "coraje",
    titulo: "Arriba del trampolín",
    historia: "En el curso de natación, el monitor propone saltar desde el trampolín. Fátima sube la escalerilla y, al mirar abajo, le tiemblan las piernas y el corazón le late muy deprisa. Desde la cola, alguien grita: «¡Tírate de cabeza, cobarde!». Fátima se queda quieta arriba, sin saber si bajar, saltar de pie o hacer lo que le dicen.",
    pregunta: "¿Para qué sirve el miedo? ¿Cómo se sabe si hay que hacerle caso o si toca atreverse poco a poco?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Tirarse de cabeza sin saber, porque se lo gritan", r: "pasa" },
        { t: "Saltar de pie con el monitor cerca", r: "justo" },
        { t: "Bajar y no volver a intentarlo nunca", r: "corto" },
        { t: "Pedir probar primero desde el borde de la piscina", r: "justo" },
        { t: "Subir al trampolín más alto para demostrar que no teme", r: "pasa" },
        { t: "Bajar hoy y proponerse intentarlo la semana que viene", r: "justo", x: "Retirarse a tiempo también puede ser valiente si hay un plan para volver." },
      ],
    },
    idea: "El miedo avisa de un peligro y a veces tiene razón. Ser valiente es atreverse a lo que toca, paso a paso, no hacer locuras.",
    frase: { t: "No es que no nos atrevamos porque las cosas sean difíciles. Son difíciles porque no nos atrevemos.", autor: "Séneca", obra: "Cartas a Lucilio, 104" },
    reto: "Hoy atrévete a algo pequeño que te dé un poco de miedo, como preguntar una duda en clase.",
  },
  {
    bloque: 1,
    virtud: "justicia",
    titulo: "Un enfado con razón",
    historia: "En Educación Física, el equipo de Iván reparte los puestos y, como siempre, dejan a Lola de portera, aunque ella ha dicho muchas veces que quiere jugar delante. Hoy vuelve a pasar. Iván nota calor en la cara y los puños apretados. A él no le toca, pero siente muy dentro que aquello no es justo.",
    pregunta: "¿Qué le está diciendo el enfado a Iván? ¿Cómo puede defender lo justo sin que el enfado mande?",
    juego: {
      consigna: "¿Depende de Iván?",
      tipo: "DEPENDE",
      items: [
        { t: "Notar calor en la cara y los puños apretados", r: "no", x: "Es el cuerpo avisando. Llega solo." },
        { t: "Que el equipo cambie cómo reparte los puestos", r: "parte", x: "No lo decide él solo, pero puede proponerlo." },
        { t: "Proponer que los puestos vayan por turnos", r: "si" },
        { t: "Gritar y tirar el balón al suelo", r: "si" },
        { t: "Preguntarle a Lola dónde le gustaría jugar", r: "si" },
        { t: "Contárselo al maestro si siempre pasa lo mismo", r: "si" },
      ],
    },
    nota: "Si a alguien lo dejan de lado una y otra vez, contárselo a un adulto de confianza siempre depende de ti. Eso no se aguanta ni se resuelve solo.",
    idea: "A veces el enfado es una alarma que dice «esto no es justo». Escúchala, respira y usa esa energía para arreglarlo, no para hacer daño.",
    frase: { t: "Sé como el acantilado contra el que rompen las olas: se mantiene firme, y a su alrededor el agua se calma.", autor: "Marco Aurelio", obra: "Meditaciones, IV, 49" },
    reto: "Hoy, si algo te parece injusto, dilo con calma y proponiendo una solución.",
  },
  {
    bloque: 1,
    virtud: "justicia",
    titulo: "Qué asco… ¿o no?",
    historia: "Hoy en el comedor hay un plato que Daniela no conoce: crema de calabaza con semillas por encima. Solo con verla arruga la nariz y se le cierra el estómago. Su amiga Vera grita «¡Qué asco!» y aparta el plato. Justo detrás está Rosario, la cocinera, que ha preparado la crema con mucho cariño.",
    pregunta: "¿Se puede sentir asco sin hacer sentir mal a nadie? ¿Qué podría decir o hacer Daniela?",
    juego: {
      consigna: "¿Es un hecho o es lo que Daniela se dice?",
      tipo: "HECHO",
      items: [
        { t: "Nunca ha probado la crema de calabaza", r: "si" },
        { t: "Esto va a estar malísimo", r: "no" },
        { t: "La crema tiene semillas por encima", r: "si" },
        { t: "Todo lo que lleva semillas sabe fatal", r: "no" },
        { t: "Ha arrugado la nariz al verla", r: "si" },
        { t: "Si la pruebo, voy a vomitar", r: "no", x: "Es una idea que la asusta. Probar un poquito le diría la verdad." },
      ],
    },
    idea: "El asco nos protege de lo que podría sentarnos mal. Pero «no me apetece» no es lo mismo que «es asqueroso», y las palabras llegan a otros.",
    frase: { t: "Si no está bien, no lo hagas. Si no es verdad, no lo digas.", autor: "Marco Aurelio", obra: "Meditaciones, XII, 17" },
    reto: "Hoy prueba un bocado pequeño de algo nuevo, o di «no me apetece» en vez de «qué asco».",
  },
  {
    bloque: 1,
    virtud: "sabiduria",
    titulo: "¡No me lo esperaba!",
    historia: "A la entrada, alguien suelta la noticia: «¡Este año no hay viaje de fin de curso!». Alejandro abre mucho los ojos y la boca, y se queda sin palabras. En un minuto, la sorpresa se convierte en disgusto y Alejandro se lo cuenta a todo el que pasa. Ya en clase, la tutora explica que todavía no se ha decidido nada.",
    pregunta: "¿Por qué la sorpresa nos hace creernos las cosas tan rápido? ¿Qué podría haber hecho Alejandro antes de contarlo?",
    juego: {
      consigna: "¿Se sabe o es un rumor?",
      tipo: "RUMOR",
      items: [
        { t: "La tutora ha dicho que aún no está decidido", r: "si" },
        { t: "«Han cancelado el viaje para siempre»", r: "no" },
        { t: "«Dicen que es porque nos portamos fatal»", r: "no" },
        { t: "La agenda dice que el viernes hay reunión de familias", r: "si" },
        { t: "«Mi primo dice que al final vamos a la playa»", r: "no" },
        { t: "El curso pasado, 5.º fue de viaje a Granada", r: "si", x: "Pasó y se puede comprobar, aunque no dice nada de lo que pasará este año." },
      ],
    },
    idea: "La sorpresa es un salto rápido del corazón. Antes de que se convierta en disgusto, o en noticia para otros, comprueba qué se sabe de verdad.",
    frase: { t: "Tenemos dos orejas y una sola boca para escuchar más y hablar menos.", autor: "Zenón de Citio", obra: "según Diógenes Laercio, Vidas, VII, 23" },
    reto: "Hoy, si una noticia te sorprende, pregunta «¿cómo lo sabes?» antes de contarla.",
  },
  {
    bloque: 1,
    virtud: "coraje",
    titulo: "Tierra, trágame",
    historia: "En el comedor, Carla tropieza con la bandeja y los macarrones acaban en el suelo. Se hace un silencio y alguien suelta una risita. A Carla le arde la cara, quiere desaparecer y se imagina que todo el colegio hablará de ello durante semanas. Al día siguiente no quiere volver a entrar en el comedor.",
    pregunta: "¿Cuánto crees que durará lo de los macarrones en la cabeza de los demás? ¿Y en la de Carla?",
    juego: {
      consigna: "¿Es real o lo imagina Carla?",
      tipo: "REAL",
      items: [
        { t: "Se le ha caído la bandeja", r: "si" },
        { t: "Alguien se ha reído un momento", r: "si" },
        { t: "Le arde la cara", r: "si" },
        { t: "Todo el colegio hablará de ello durante semanas", r: "no" },
        { t: "Ahora todos piensan que es una torpe", r: "no" },
        { t: "Nadie querrá sentarse con ella", r: "no", x: "Es lo que teme, pero sus amigos siguen ahí. Puede comprobarlo sentándose con ellos." },
      ],
    },
    idea: "La vergüenza hace que todo parezca más grande. A los demás se les olvida enseguida; lo que más dura es lo que nos imaginamos.",
    frase: { t: "Son más las cosas que nos asustan que las que nos hacen daño. Sufrimos más en la imaginación que en la realidad.", autor: "Séneca", obra: "Cartas a Lucilio, 13" },
    reto: "Si hoy algo te da vergüenza, pregúntate: «¿Se acordará alguien de esto la semana que viene?».",
  },
  {
    bloque: 1,
    virtud: "justicia",
    titulo: "La culpa que ayuda",
    historia: "En el cumpleaños de Unai, Pablo se enfadó al perder en un juego y le soltó: «Tu fiesta es un rollo». Unai se quedó muy serio. Esa noche, Pablo no puede dormir: le da vueltas una y otra vez, piensa que es la peor persona del mundo y que Unai no querrá volver a hablarle nunca.",
    pregunta: "¿Para qué le sirve a Pablo sentirse culpable? ¿Cuándo ayuda la culpa y cuándo se pasa de la raya?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Pedirle perdón a Unai al día siguiente", r: "justo" },
        { t: "Pensar «soy la peor persona del mundo»", r: "pasa" },
        { t: "Decirse «bah, Unai es un exagerado»", r: "corto" },
        { t: "Invitar a Unai a jugar para arreglarlo", r: "justo" },
        { t: "No querer ir al cole para no verle", r: "pasa", x: "La culpa se ha hecho tan grande que le aparta justo de lo que puede arreglarlo." },
        { t: "Hacer como si no hubiera pasado nada", r: "corto" },
      ],
    },
    idea: "La culpa útil te empuja a reparar lo que hiciste. La exagerada solo te hace daño. Equivocarte no te convierte en mala persona.",
    frase: { t: "Es propio del ser humano querer incluso a quienes se equivocan.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 22" },
    reto: "Si hoy te equivocas con alguien, pide perdón y busca cómo arreglarlo. Luego, date permiso para pasar página.",
  },
  {
    bloque: 1,
    virtud: "templanza",
    titulo: "Orgullo del bueno",
    historia: "Noa ha pasado todo el verano practicando a la comba y hoy, por fin, ha llegado a cien saltos seguidos. Nota el pecho hinchado y una sonrisa que no le cabe en la cara. En el recreo empieza a decir que es la mejor saltadora del cole y que los demás saltan «como patos».",
    pregunta: "¿De qué tiene motivos Noa para estar orgullosa? ¿En qué momento el orgullo empieza a hacer daño?",
    juego: {
      consigna: "¿Es un hecho o es lo que Noa se dice?",
      tipo: "HECHO",
      items: [
        { t: "Ha practicado casi todos los días", r: "si" },
        { t: "Ha llegado a cien saltos seguidos", r: "si" },
        { t: "Ha mejorado mucho desde junio", r: "si" },
        { t: "Es la mejor saltadora del cole", r: "no" },
        { t: "Los demás saltan como patos", r: "no" },
        { t: "Ya no necesita practicar más", r: "no", x: "Lo que ha conseguido es real, pero seguir mejorando depende de seguir practicando." },
      ],
    },
    idea: "Estar orgulloso de tu esfuerzo es sano. Se estropea cuando, para sentirte grande, necesitas hacer pequeños a los demás.",
    frase: { t: "Las ovejas no enseñan a los pastores cuánto han comido: lo digieren y dan lana y leche. Tú tampoco presumas de lo que sabes: demuéstralo con lo que haces.", autor: "Epicteto", obra: "Enquiridión, 46" },
    reto: "Hoy piensa en algo que te haya salido bien gracias a tu esfuerzo, y felicita a alguien por el suyo.",
  },
  {
    bloque: 1,
    virtud: "templanza",
    titulo: "Me aburrooo",
    historia: "Es domingo, llueve y la tablet de casa está sin batería. Álvaro se tumba en el sofá y repite cada cinco minutos: «Me aburrooo». Su madre le propone varias cosas y a todas dice que no. Al rato, casi sin darse cuenta, coge unas pinzas de la ropa y una caja de cartón y empieza a construir algo.",
    pregunta: "¿Qué le pasó a Álvaro cuando dejó de esperar que algo le entretuviera? ¿Puede el aburrimiento servir para algo?",
    juego: {
      consigna: "¿Depende de Álvaro?",
      tipo: "DEPENDE",
      items: [
        { t: "Que llueva el domingo", r: "no" },
        { t: "Que la tablet esté sin batería", r: "no" },
        { t: "Sentirse aburrido un rato", r: "parte", x: "Llega solo, pero no tiene por qué durar toda la tarde." },
        { t: "Inventarse un juego con lo que hay en casa", r: "si" },
        { t: "Que su madre le entretenga", r: "no", x: "Puede proponerle hacer algo juntos, pero entretenerse es cosa suya." },
        { t: "Coger un libro o un lápiz", r: "si" },
      ],
    },
    idea: "El aburrimiento no es un enemigo: es un hueco. Si no lo llenas de quejas, puede llenarse de ideas.",
    frase: { t: "Todo lo demás es ajeno: solo el tiempo es nuestro.", autor: "Séneca", obra: "Cartas a Lucilio, 1" },
    reto: "Hoy, si te aburres, espera dos minutos sin pantallas y mira qué se te ocurre.",
  },
  {
    bloque: 1,
    virtud: "sabiduria",
    titulo: "Nervios y ganas a la vez",
    historia: "Mañana Inés se va tres días de convivencia con su clase a una granja escuela. Tiene muchísimas ganas: habrá animales, juegos y noches con sus amigas. Pero a la vez le da miedo echar de menos su casa y no poder dormir. Nota cosquillas en la barriga y, al mismo tiempo, un nudo en la garganta. «¿Estoy contenta o asustada?», se pregunta.",
    pregunta: "¿Se pueden sentir dos emociones a la vez? ¿Dónde notas tú en el cuerpo la alegría, y dónde los nervios?",
    juego: {
      consigna: "¿Depende de Inés?",
      tipo: "DEPENDE",
      items: [
        { t: "Sentir ilusión y miedo a la vez", r: "no", x: "Las dos llegan solas, y las dos tienen sentido." },
        { t: "Notar cosquillas en la barriga", r: "no" },
        { t: "Ponerle nombre a cada emoción", r: "si" },
        { t: "Llevar en la mochila algo que le recuerde a casa", r: "si" },
        { t: "Dormir bien la primera noche", r: "parte", x: "No lo controla del todo, pero puede ayudarse: respirar, leer un rato, hablar con una amiga." },
        { t: "Contar a la monitora que echa de menos su casa", r: "si" },
      ],
    },
    idea: "Las emociones pueden venir de dos en dos, y no se anulan. Ponerles nombre y notar dónde viven en tu cuerpo te ayuda a entenderlas.",
    frase: { t: "De las cosas, unas dependen de nosotros y otras no dependen de nosotros.", autor: "Epicteto", obra: "Enquiridión, 1" },
    reto: "Hoy, al notar una emoción, pon la mano donde la sientes en el cuerpo y dile su nombre en voz baja.",
  },
]);
