// La Ciudadela · sesiones del bloque 8 (y 9): Amistad y conflictos · Ciudadanos del mundo
window.CIUDADELA_NUEVAS = (window.CIUDADELA_NUEVAS || []).concat([
  // ---------------- Bloque 8 · Amistad y conflictos ----------------
  {
    bloque: 8,
    virtud: "coraje",
    titulo: "El primer «¿puedo jugar?»",
    historia:
      "Youssef ha empezado en el club de atletismo del barrio y no conoce a nadie. En el descanso, tres chicos juegan con un frisbi junto a la pista. Youssef se acerca dos veces, pero se da la vuelta antes de llegar. En casa le dice a su madre que el club es aburrido.",
    pregunta: "¿Por qué crees que Youssef dice que el club es aburrido? ¿Qué pequeño paso podría dar el próximo día?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Mirar desde lejos todo el descanso", r: "corto" },
        { t: "Preguntar: «¿Puedo jugar con vosotros?»", r: "justo" },
        { t: "Quitarles el frisbi para que le hagan caso", r: "pasa" },
        { t: "Contarles su vida entera en el primer minuto", r: "pasa", x: "Tener ganas está bien, pero conocerse lleva su tiempo." },
        { t: "Sonreír y preguntarles cómo se llaman", r: "justo" },
        { t: "Esperar a que ellos vengan a buscarle", r: "corto", x: "Puede que pase, pero dar el primer paso sí depende de él." },
      ],
    },
    idea: "Hacer un amigo empieza con un gesto pequeño que da un poco de miedo. El miedo no se va antes de atreverse: se hace pequeño después.",
    frase: { t: "No es que no nos atrevamos porque las cosas sean difíciles. Son difíciles porque no nos atrevemos.", autor: "Séneca", obra: "Cartas a Lucilio, 104" },
    reto: "Hoy pregunta algo a alguien de otra clase o de otro grupo con quien casi nunca hablas.",
  },
  {
    bloque: 8,
    virtud: "sabiduria",
    titulo: "Amigos que te hacen bien",
    historia:
      "Aitana quiere entrar en el grupo de Olivia, que siempre está en el centro del patio. Para caerles bien, les presta sus rotuladores nuevos y se ríe de una broma sobre Pablo que no le hace ninguna gracia. Esa tarde, Marta, su vecina, llama a su puerta para ir en bici al parque. Aitana le dice que está ocupada.",
    pregunta: "¿Qué busca Aitana en ese grupo? ¿Cómo se nota que una amistad te hace bien?",
    juego: {
      consigna: "¿Depende de Aitana?",
      tipo: "DEPENDE",
      items: [
        { t: "Que el grupo de Olivia quiera ser su amigo", r: "no" },
        { t: "Reírse de una broma que no le gusta", r: "si" },
        { t: "Con quién pasa su tiempo libre", r: "si" },
        { t: "Sentirse bien con alguien", r: "parte", x: "Ella elige con quién está; cómo la tratan depende también de los demás." },
        { t: "Pensar despacio antes de llamar a alguien amigo", r: "si" },
        { t: "Que Marta vuelva a invitarla", r: "no", x: "Lo decide Marta, aunque Aitana puede proponerle ella el próximo plan." },
      ],
    },
    idea: "Un buen amigo no te pide que dejes de ser tú. Elegir amigos con calma es de sabios, y cuidarlos cuando los tienes, también.",
    frase: { t: "Piensa despacio si quieres a alguien como amigo. Cuando lo hayas decidido, recíbelo de todo corazón.", autor: "Séneca", obra: "Cartas a Lucilio, 3" },
    reto: "Piensa en un amigo con quien te sientes tú mismo y dile hoy algo que valoras de él.",
  },
  {
    bloque: 8,
    virtud: "templanza",
    titulo: "Mi mejor amigo tiene otro amigo",
    historia:
      "Mateo y Bruno son mejores amigos desde Infantil. Este trimestre, Bruno se sienta con Iker en Plástica y en el recreo juegan juntos al baloncesto. Mateo se queda en el banco pensando: «Ya no le importo nada». Cuando Bruno le llama para que se una, Mateo le contesta: «Vete con tu amigo nuevo».",
    pregunta: "¿Qué siente Mateo? Lo que se dice a sí mismo, ¿es seguro o es una suposición? ¿Qué podría hacer en lugar de apartarse?",
    juego: {
      consigna: "¿Es real o lo imagina Mateo?",
      tipo: "REAL",
      items: [
        { t: "Bruno juega al baloncesto con Iker", r: "si" },
        { t: "Bruno ya no le quiere como amigo", r: "no" },
        { t: "Bruno le ha llamado para jugar", r: "si" },
        { t: "Iker quiere quitarle a su amigo", r: "no" },
        { t: "Mateo se siente dejado de lado", r: "si", x: "El sentimiento es real y vale. Lo que Mateo se cuenta sobre él, quizá no." },
        { t: "Si Bruno tiene otro amigo, él sobra", r: "no" },
      ],
    },
    idea: "Sentir celos es normal. Pero un amigo puede tener más amigos sin quererte menos: la amistad no es una tarta que se acaba.",
    frase: { t: "Lo que inquieta a las personas no son las cosas, sino las opiniones que tienen sobre las cosas.", autor: "Epicteto", obra: "Enquiridión, 5" },
    reto: "Si hoy sientes celos, pregúntate: «¿Qué ha pasado de verdad y qué me estoy imaginando?».",
  },
  {
    bloque: 8,
    virtud: "templanza",
    titulo: "Decir lo que duele sin herir",
    historia:
      "Irina y Salma quedaron el sábado para terminar juntas el mural de los planetas. Salma no apareció ni avisó, e Irina lo acabó sola hasta la hora de cenar. El lunes, en el pasillo, Irina está a punto de gritarle: «¡Eres una egoísta y una mentirosa!». Respira hondo, se para un momento y piensa qué quiere decir de verdad.",
    pregunta: "¿Qué diferencia hay entre decir «eres una egoísta» y «me sentí sola cuando…»? ¿Cuál ayuda más a arreglarlo?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Gritarle «egoísta» delante de todos", r: "pasa" },
        { t: "No decir nada y dejar de hablarle", r: "corto" },
        { t: "«Me sentí sola cuando no viniste ni avisaste»", r: "justo" },
        { t: "Contárselo a media clase para que la critiquen", r: "pasa" },
        { t: "Decir «no pasa nada» cuando sí pasa", r: "corto", x: "Callar lo que duele no lo arregla: suele salir después, y peor." },
        { t: "Pedirle hablar en el recreo, las dos solas", r: "justo" },
      ],
    },
    idea: "Se puede discutir sin herir: hablar de lo que pasó y de cómo me sentí, en vez de poner etiquetas a la otra persona.",
    frase: { t: "Si no está bien, no lo hagas. Si no es verdad, no lo digas.", autor: "Marco Aurelio", obra: "Meditaciones, XII, 17" },
    reto: "Si hoy algo te molesta, prueba la fórmula «Me sentí… cuando…». Sin insultos ni etiquetas.",
  },
  {
    bloque: 8,
    virtud: "sabiduria",
    titulo: "Dos versiones del bocadillo",
    historia:
      "Daniela llega tarde al patio y encuentra a Alba llorando: dice que Gonzalo le ha tirado el bocadillo al suelo a propósito. Daniela, muy enfadada, va directa a por él y le grita delante de todos. Gonzalo, sorprendido, le explica que tropezó con una mochila y que iba a pedir perdón.",
    pregunta: "¿Qué sabía Daniela de verdad cuando fue a por Gonzalo? ¿Por qué cuesta tanto escuchar la otra versión cuando ya estamos enfadados?",
    juego: {
      consigna: "¿Es un hecho o es lo que Daniela se dice?",
      tipo: "HECHO",
      items: [
        { t: "El bocadillo está en el suelo", r: "si" },
        { t: "Alba está llorando", r: "si" },
        { t: "Gonzalo lo hizo a propósito", r: "no" },
        { t: "Gonzalo siempre va molestando", r: "no" },
        { t: "Gonzalo dice que tropezó", r: "si", x: "Que lo dice es un hecho. Si es verdad, hay que averiguarlo con calma." },
        { t: "Si defiendo a mi amiga, no hace falta preguntar", r: "no" },
      ],
    },
    idea: "Toda historia tiene al menos dos versiones. Escuchar antes de juzgar no es ponerse de un lado: es buscar la verdad.",
    frase: { t: "Tenemos dos orejas y una sola boca para escuchar más y hablar menos.", autor: "Zenón de Citio", obra: "según Diógenes Laercio, Vidas, VII, 23" },
    reto: "Hoy, antes de opinar sobre un problema entre otros, pregunta a las dos partes qué ha pasado.",
  },
  {
    bloque: 8,
    virtud: "justicia",
    titulo: "En medio de dos amigos",
    historia:
      "Valentina es amiga de Álex y de Nora, que llevan dos días sin hablarse por una jugada discutida en el pañuelo. Los dos quieren que Valentina se ponga de su parte. Álex le dice: «Si eres mi amiga, no te juntes con ella». Nora le pide que le cuente qué dice Álex de ella. Valentina está hecha un lío.",
    pregunta: "¿Tiene Valentina que elegir un bando? ¿Cómo podría ayudar sin hacer de jueza ni de mensajera?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Tratar igual a los dos, aunque uno insista", r: "justicia" },
        { t: "Decirle a Álex: «No voy a elegir entre vosotros»", r: "coraje" },
        { t: "Esperar a que se calmen antes de juntarlos", r: "templanza", x: "También es sabiduría: hablar en caliente suele salir mal." },
        { t: "Preguntar a cada uno qué necesita para arreglarlo", r: "sabiduria" },
        { t: "No llevarle a Nora lo que Álex dijo enfadado", r: "justicia" },
        { t: "Proponer volver a jugar con reglas claras", r: "sabiduria" },
      ],
    },
    idea: "Mediar no es decidir quién gana. Es ayudar a que los dos se escuchen, tratándolos igual y sin llevar recados.",
    frase: { t: "Sé como el acantilado contra el que rompen las olas: se mantiene firme, y a su alrededor el agua se calma.", autor: "Marco Aurelio", obra: "Meditaciones, IV, 49" },
    reto: "Si hoy ves discutir a dos personas, en vez de tomar partido, pregunta con calma: «¿Qué ha pasado?».",
  },
  {
    bloque: 8,
    virtud: "coraje",
    titulo: "Todos contra uno, no",
    historia:
      "El grupo de Chen ha decidido que Paula ya no juega con ellos porque «es una pesada». Si alguien le habla, los demás le hacen el vacío también. Hoy, en la fila del comedor, Paula se acerca a Chen y le pregunta en voz baja si puede sentarse con ellos. Todo el grupo se queda mirando a Chen.",
    pregunta: "¿Qué siente Chen en ese momento? ¿Qué persona quiere ser, aunque el grupo le presione?",
    juego: {
      consigna: "¿Puede resolverlo Chen o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Decirle que sí a Paula aunque el grupo proteste", r: "yo" },
        { t: "Invitar a Paula a jugar en el recreo", r: "yo" },
        { t: "Dejar de seguir al grupo cuando excluye a alguien", r: "yo" },
        { t: "El grupo lleva semanas dejando sola a Paula", r: "adulto" },
        { t: "Le amenazan con dejarle solo si ayuda a Paula", r: "adulto" },
        { t: "Contárselo a un adulto de confianza", r: "adulto", x: "Siempre puede hacerlo. Es una buena decisión, no un chivatazo." },
      ],
    },
    nota: "Dejar fuera a alguien a propósito y día tras día es acoso, aunque nadie pegue a nadie. Contárselo a un adulto de confianza siempre depende de ti: eso no se aguanta ni se resuelve solo.",
    idea: "La presión del grupo empuja fuerte, pero decidir qué persona quieres ser depende de ti. A veces el coraje es decir: «Ven, siéntate».",
    frase: { t: "Primero decide qué persona quieres ser. Después, haz lo que tengas que hacer.", autor: "Epicteto", obra: "Disertaciones, III, 23" },
    reto: "Hoy busca a alguien que suele quedarse solo y proponle algo: jugar, sentarse juntos o ir contigo en la fila.",
  },
  {
    bloque: 8,
    virtud: "justicia",
    titulo: "Secretos que pesan",
    historia:
      "Lara le cuenta a Adam que le gusta un chico de sexto y le pide que no se lo diga a nadie. Adam cumple su palabra. Una semana después, Lara le cuenta otro secreto: unos chicos mayores le quitan la merienda cada día a la salida, y le han dicho que, si habla, será peor. Otra vez le pide que no diga nada.",
    pregunta: "¿En qué se parecen los dos secretos de Lara? ¿En qué se diferencian? ¿Qué debería hacer Adam con cada uno?",
    juego: {
      consigna: "¿Puede resolverlo Adam o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Guardar el secreto de a quién le gusta Lara", r: "yo" },
        { t: "A Lara le quitan la merienda y la amenazan", r: "adulto" },
        { t: "Un amigo no quiere que cuenten que duerme con peluche", r: "yo" },
        { t: "Un adulto le pide un secreto con sus padres", r: "adulto", x: "Un adulto no debe pedir a un niño secretos con su familia. Eso siempre se cuenta." },
        { t: "Preparar una fiesta sorpresa sin que se entere nadie", r: "yo" },
        { t: "Contárselo a un adulto de confianza", r: "adulto" },
      ],
    },
    nota: "Un secreto que hace daño o que da miedo no se guarda. Contárselo a un adulto de confianza siempre depende de ti y no es traicionar a nadie: eso no se aguanta ni se resuelve solo.",
    idea: "Guardar un secreto es ser leal. Pero si el secreto hace daño a alguien, lo justo es contarlo a un adulto: eso también es ser buen amigo.",
    frase: { t: "No te dé vergüenza que te ayuden. Como el soldado que no puede subir solo la muralla, a veces necesitamos una mano.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 7" },
    reto: "Piensa qué adulto de confianza tienes en el cole y otro en casa. Díselo a tu compañero de pareja.",
  },
  {
    bloque: 8,
    virtud: "justicia",
    titulo: "Querer y dejarse querer",
    historia:
      "Rubén ayuda a todo el mundo: presta sus cosas, explica los deberes y recoge los balones de todos. Pero hoy ha fallado un penalti y se le ha roto la maqueta de Ciencias. Cuando su amiga Elena le pregunta qué le pasa, contesta «nada» y se aleja. Tampoco deja que nadie le ayude a arreglar la maqueta.",
    pregunta: "¿Por qué crees que a Rubén le cuesta tanto dejarse ayudar? ¿Cómo se sentirá Elena cuando él le dice «nada»?",
    juego: {
      consigna: "¿Depende de Rubén?",
      tipo: "DEPENDE",
      items: [
        { t: "Ayudar a los demás", r: "si" },
        { t: "Contarle a Elena cómo se siente", r: "si" },
        { t: "Que Elena quiera ayudarle", r: "no" },
        { t: "Meter o fallar el penalti", r: "parte", x: "Él pone el esfuerzo; el portero y la suerte también cuentan." },
        { t: "Aceptar ayuda con la maqueta", r: "si", x: "Cuesta, pero dejar que le ayuden depende de él." },
        { t: "Que a sus amigos les importe lo que le pasa", r: "no" },
      ],
    },
    idea: "La amistad va en las dos direcciones: cuidar y dejarse cuidar. Quien nunca acepta ayuda también deja un poco fuera a sus amigos.",
    frase: { t: "Si quieres que te quieran, quiere.", autor: "Séneca", obra: "Cartas a Lucilio, 9" },
    reto: "Hoy acepta una ayuda que te ofrezcan, o cuéntale a un amigo algo que te preocupa.",
  },
  {
    bloque: 8,
    virtud: "sabiduria",
    titulo: "Te estaba ayudando",
    historia:
      "Martina ha dejado su puzle de mil piezas a medio hacer en la mesa del salón. Su hermano Pol, de seis años, se ha subido a una silla y ha deshecho una esquina entera. Martina nota que le arde la cara y piensa: «Siempre lo estropea todo». Entonces Pol le enseña una pieza, muy orgulloso: «¡Mira, te estaba ayudando!».",
    pregunta: "¿Qué quería hacer Pol y qué ha conseguido? ¿Cómo puede Martina decirle lo que siente sin apagar sus ganas de ayudar?",
    juego: {
      consigna: "¿Depende de Martina?",
      tipo: "DEPENDE",
      items: [
        { t: "Que Pol haya deshecho una esquina", r: "no" },
        { t: "Sentir rabia al verlo", r: "parte", x: "La rabia llega sola. Lo que hace con ella, sí depende de Martina." },
        { t: "Seguir pensando «siempre lo estropea todo»", r: "parte", x: "El primer pensamiento sale solo; revisarlo y cambiarlo sí depende de ella." },
        { t: "Enseñarle a Pol a buscar los bordes", r: "si" },
        { t: "Guardar el puzle donde Pol no llegue", r: "si" },
        { t: "Que Pol tenga seis años", r: "no" },
      ],
    },
    idea: "A veces quien nos fastidia quería ayudar. Mirar la intención no borra el enfado, pero ayuda a arreglarlo.",
    frase: { t: "¡Cuánto más daño nos hacen el enfado y el disgusto que las cosas que los provocan!", autor: "Marco Aurelio", obra: "Meditaciones, XI, 18" },
    reto: "Hoy, si alguien de tu familia te molesta, pregúntate qué quería hacer antes de enfadarte.",
  },
  {
    bloque: 8,
    virtud: "coraje",
    titulo: "Quién da el primer paso",
    historia:
      "Hugo y Emma discutieron hace una semana por quién había ganado una carrera, y desde entonces no se hablan. Hugo la echa de menos en el recreo, pero piensa: «Que venga ella, que fue la que empezó». Desde la otra punta del patio, Emma parece pensar lo mismo. Pasan los días y ninguno de los dos se acerca.",
    pregunta: "¿Quién debería dar el primer paso? ¿Por qué a veces cuesta más hacer las paces que discutir?",
    juego: {
      consigna: "¿Depende de Hugo?",
      tipo: "DEPENDE",
      items: [
        { t: "Que Emma quiera hacer las paces", r: "no" },
        { t: "Acercarse y decirle «te echo de menos»", r: "si" },
        { t: "Reconocer su parte en la discusión", r: "si" },
        { t: "Que todo vuelva a ser como antes enseguida", r: "parte", x: "Él pone de su parte, pero la confianza se recupera entre los dos y con tiempo." },
        { t: "Seguir esperando a que ella empiece", r: "si" },
        { t: "Saber quién ganó de verdad la carrera", r: "no", x: "Ya no se puede comprobar, y tampoco hace falta para volver a ser amigos." },
      ],
    },
    idea: "Reconciliarse no es decidir quién tenía razón. Dar el primer paso no te hace perder: te hace valiente.",
    frase: { t: "La amabilidad sincera es invencible.", autor: "Marco Aurelio", obra: "Meditaciones, XI, 18" },
    reto: "Si estás enfadado con alguien, da hoy un paso pequeño: un saludo, una sonrisa o un «¿hablamos?».",
  },

  // ---------------- Bloque 9 · Ciudadanos del mundo ----------------
  {
    bloque: 9,
    virtud: "justicia",
    titulo: "Si a uno le duele…",
    historia:
      "En Educación Física, Sofía se tuerce el tobillo y se queda sentada en el suelo, con lágrimas en los ojos. Algunos siguen jugando como si nada. Iván para el partido y va corriendo a buscar a la maestra. Después, en clase, varios compañeros le preguntan a Sofía cómo está y le acercan la mochila a su sitio.",
    pregunta: "¿Por qué crees que Iván paró el partido? ¿Qué querrá decir que somos partes de un mismo cuerpo?",
    juego: {
      consigna: "¿Depende de Iván?",
      tipo: "DEPENDE",
      items: [
        { t: "Que Sofía se haya torcido el tobillo", r: "no" },
        { t: "Parar el partido para ayudarla", r: "si" },
        { t: "Avisar a la maestra", r: "si" },
        { t: "Que el tobillo se cure pronto", r: "no" },
        { t: "Que Sofía se sienta acompañada", r: "parte", x: "Él puede acompañarla; cómo se siente ella no depende solo de él." },
        { t: "Que los demás sigan jugando", r: "no", x: "Puede pedirles que paren, pero lo que hacen depende de ellos." },
      ],
    },
    idea: "Somos como partes de un mismo cuerpo: si a una le duele, las demás se dan cuenta y la cuidan. Esa es la justicia en pequeño.",
    frase: { t: "Somos partes de un mismo gran cuerpo. La naturaleza nos hizo familia.", autor: "Séneca", obra: "Cartas a Lucilio, 95" },
    reto: "Hoy fíjate en si alguien está mal o solo y pregúntale: «¿Estás bien? ¿Te ayudo?».",
  },
  {
    bloque: 9,
    virtud: "justicia",
    titulo: "La colmena y la abeja",
    historia:
      "Después del recreo, el patio queda lleno de envoltorios y cáscaras de mandarina. Fátima ve un papel junto a su pie y piensa: «No es mío, que lo recoja otro». Por la tarde, en el parque de su barrio, se queja a su padre de que los columpios están pintarrajeados y hay latas por todas partes.",
    pregunta: "¿Qué relación hay entre el papel del patio y las latas del parque? ¿De quién es un sitio que es de todos?",
    juego: {
      consigna: "¿Depende de Fátima?",
      tipo: "DEPENDE",
      items: [
        { t: "Tirar su envoltorio a la papelera", r: "si" },
        { t: "Recoger un papel que no es suyo", r: "si", x: "No lo tiró ella, pero cuidar lo de todos también es cosa suya." },
        { t: "Que alguien pintara los columpios", r: "no" },
        { t: "Que el patio esté limpio mañana", r: "parte", x: "Ella pone su parte; el resto depende de todos." },
        { t: "Proponer en clase turnos para cuidar el patio", r: "si" },
        { t: "Que el ayuntamiento arregle el parque", r: "no" },
      ],
    },
    idea: "Lo que es bueno para todos también es bueno para cada uno. Cuidar el patio y el barrio es cuidarte a ti.",
    frase: { t: "Lo que no es bueno para la colmena, tampoco es bueno para la abeja.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 54" },
    reto: "Hoy recoge algo del suelo del patio o de la calle, aunque no sea tuyo.",
  },
  {
    bloque: 9,
    virtud: "templanza",
    titulo: "Mirar sin llevarse",
    historia:
      "En la excursión al río, Carla descubre una charca llena de renacuajos. Marcos quiere llenar una botella para llevárselos a casa, y otros empiezan a tirar piedras para ver cómo saltan. Carla también tiene muchas ganas de coger uno con la mano, aunque el maestro les ha pedido que no los toquen.",
    pregunta: "¿Dónde está la línea entre disfrutar de la naturaleza y pasarse? ¿Qué necesitan los renacuajos para estar bien?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Mirarlos de cerca sin tocarlos", r: "justo" },
        { t: "Llevarse una botella llena a casa", r: "pasa" },
        { t: "Tirar piedras a la charca para divertirse", r: "pasa" },
        { t: "No acercarse porque «la naturaleza es aburrida»", r: "corto" },
        { t: "Dibujarlos en el cuaderno y dejarlos allí", r: "justo" },
        { t: "Ver cómo tiran piedras y no decir nada", r: "corto", x: "Se puede pedir con calma que paren, o avisar al maestro." },
      ],
    },
    idea: "Cuidar la naturaleza es disfrutarla sin quedársela ni romperla: mirar, aprender y dejarla igual o mejor de como estaba.",
    frase: { t: "No discutas más sobre cómo tiene que ser una buena persona. Sé una.", autor: "Marco Aurelio", obra: "Meditaciones, X, 16" },
    reto: "Hoy cuida algo vivo: riega una planta, pon agua a un animal o deja tranquilo a un insecto.",
  },
  {
    bloque: 9,
    virtud: "justicia",
    titulo: "Ayudar sin pasarse",
    historia:
      "Omar va en silla de ruedas desde pequeño y le encanta el baloncesto adaptado. Desde que empezó el curso, Lucía le empuja la silla aunque él no se lo pida, le coge el estuche antes de que lo alcance y contesta por él cuando le preguntan algo. Hoy Omar le ha dicho, un poco harto: «Puedo yo solo».",
    pregunta: "¿Por qué crees que Lucía hace todo eso? ¿Cómo se sabe cuándo una ayuda ayuda de verdad?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Preguntar «¿quieres que te ayude?» antes de hacerlo", r: "justo" },
        { t: "Empujarle la silla sin preguntar", r: "pasa" },
        { t: "Contestar por él cuando le hablan", r: "pasa" },
        { t: "No invitarle a jugar por si no puede", r: "corto", x: "Mejor preguntarle y buscar juntos cómo jugar." },
        { t: "Pensar un juego de patio en el que jueguen todos", r: "justo" },
        { t: "Hacerse la despistada cuando pide que le acerquen algo", r: "corto" },
      ],
    },
    idea: "Incluir es contar con cada persona tal como es: ayudar cuando lo necesita y lo pide, y dejarle hacer lo que puede hacer solo.",
    frase: { t: "Hemos nacido para colaborar, como los pies, las manos o los párpados.", autor: "Marco Aurelio", obra: "Meditaciones, II, 1" },
    reto: "Hoy, antes de ayudar a alguien, pregunta primero: «¿Quieres que te eche una mano?».",
  },
  {
    bloque: 9,
    virtud: "justicia",
    titulo: "Rosa tiene nombre",
    historia:
      "Al terminar Plástica, el aula queda llena de recortes y pegotes de cola. Samuel dice: «Déjalo, para eso está la limpiadora». Por la tarde ve a Rosa, la señora que limpia el colegio, rascando el pegamento del suelo con paciencia. Nadie la saluda. Samuel recuerda que fue Rosa quien le encontró la chaqueta perdida el mes pasado.",
    pregunta: "¿Por qué a veces tratamos distinto a las personas según su trabajo? ¿Qué cambiaría si toda la clase supiera cómo se llama Rosa?",
    juego: {
      consigna: "¿Es un hecho o es lo que Samuel se dice?",
      tipo: "HECHO",
      items: [
        { t: "Rosa limpia el colegio por las tardes", r: "si" },
        { t: "Para eso está la limpiadora", r: "no" },
        { t: "Rosa le encontró la chaqueta perdida", r: "si" },
        { t: "Su trabajo es menos importante que otros", r: "no" },
        { t: "Hoy nadie la ha saludado", r: "si" },
        { t: "Si limpia ella, yo puedo dejarlo todo tirado", r: "no" },
      ],
    },
    idea: "Todas las personas merecen el mismo respeto, hagan el trabajo que hagan. Saludar, dar las gracias y no cargar a otros con lo nuestro es justicia.",
    frase: { t: "La amabilidad sincera es invencible.", autor: "Marco Aurelio", obra: "Meditaciones, XI, 18" },
    reto: "Hoy saluda por su nombre y da las gracias a alguien que trabaja en el cole: conserjería, cocina, limpieza o monitores.",
  },
  {
    bloque: 9,
    virtud: "justicia",
    titulo: "Dar lo que me gustaría recibir",
    historia:
      "La clase organiza una recogida de material escolar para una asociación del barrio. Alejandro tiene tres cajas de lápices de colores, pero duda: «¿Y si luego las necesito?». Al final mete en la caja una goma partida y un cuaderno con varias páginas escritas. Su compañera Aya trae un estuche casi nuevo, lleno de rotuladores.",
    pregunta: "¿Qué es compartir de verdad? ¿Por qué nos cuesta dar lo que nos gusta?",
    juego: {
      consigna: "¿Depende de Alejandro?",
      tipo: "DEPENDE",
      items: [
        { t: "Qué material lleva a la recogida", r: "si" },
        { t: "Que otras familias tengan menos dinero", r: "no" },
        { t: "Sentir miedo a quedarse sin nada", r: "parte", x: "Ese miedo llega solo; lo que decide hacer después, sí depende de él." },
        { t: "Dar algo que a él le gustaría recibir", r: "si" },
        { t: "Que la asociación reparta bien el material", r: "no" },
        { t: "Presumir en clase de lo que ha dado", r: "si" },
      ],
    },
    idea: "Compartir no es dar lo que sobra o está roto: es dar lo que a nosotros nos gustaría recibir. Y compartido, se disfruta más.",
    frase: { t: "Ningún bien nos alegra de verdad si no tenemos con quién compartirlo.", autor: "Séneca", obra: "Cartas a Lucilio, 6" },
    reto: "Hoy comparte algo tuyo con alguien: la merienda, un rotulador, tu tiempo o un juego.",
  },
  {
    bloque: 9,
    virtud: "sabiduria",
    titulo: "Lo distinto no es raro",
    historia:
      "En la semana de las familias, cada alumno trae un plato de su casa. Noa lleva salmorejo y Mei, unos panecillos rellenos. Noa los ve y dice en voz alta: «Qué asco, eso huele raro». Mei se pone roja. Al rato, como sobran, Noa prueba uno: está buenísimo. La madre de Mei explica que en su familia los cocinan para celebrar el año nuevo.",
    pregunta: "¿Por qué dijo Noa eso antes de probarlo? ¿Qué costumbre de tu casa le podría parecer rara a alguien que no la conoce?",
    juego: {
      consigna: "¿Se sabe o es un rumor?",
      tipo: "RUMOR",
      items: [
        { t: "Los panecillos son una receta de la familia de Mei", r: "si" },
        { t: "«En su país todos comen cosas raras»", r: "no" },
        { t: "Noa los probó y le gustaron", r: "si" },
        { t: "Oí que Mei no sabe hablar bien castellano", r: "no", x: "Mei nació aquí y habla castellano y chino. Mejor preguntar que suponer." },
        { t: "«A la gente de fuera no le gusta nuestra comida»", r: "no" },
        { t: "El salmorejo lleva tomate, pan y aceite", r: "si" },
      ],
    },
    idea: "Lo distinto no es raro: solo es nuevo para mí. Preguntar y probar antes de juzgar es de sabios; meter a todo un grupo en el mismo saco, no.",
    frase: { t: "Si alguien me demuestra que me equivoco, cambiaré con gusto de opinión. Busco la verdad, y la verdad nunca ha hecho daño a nadie.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 21" },
    reto: "Pregunta hoy a un compañero por una comida, una fiesta o una palabra de su familia que no conozcas.",
  },
  {
    bloque: 9,
    virtud: "sabiduria",
    titulo: "Un cuaderno solo para mí",
    historia:
      "Es 23 de abril, Día del Libro. El maestro cuenta que el emperador Marco Aurelio escribía en un cuaderno solo para él, con consejos para ser mejor persona, y que hoy lo lee gente de todo el mundo. Inés se acuerda de una novela en la que la protagonista defendía a su hermano aunque le temblaban las piernas. Esa tarde estrena un cuaderno y copia su primera frase.",
    pregunta: "¿Qué libro te ha hecho pensar o cambiar un poco? ¿Qué frase escribirías tú en tu propio cuaderno?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Una protagonista defiende a su hermano aunque tiene miedo", r: "coraje" },
        { t: "Una detective comprueba las pistas antes de acusar", r: "sabiduria" },
        { t: "Unos piratas reparten el tesoro a partes iguales", r: "justicia" },
        { t: "Inés cierra el libro a su hora para dormir", r: "templanza", x: "Leer mucho está genial; saber parar a tiempo también." },
        { t: "Un personaje pide perdón a quien trató mal", r: "justicia", x: "También se ve coraje: cuesta reconocer un error." },
        { t: "Inés relee una página que no había entendido", r: "sabiduria" },
      ],
    },
    idea: "Los buenos libros son como amigos sabios: nos ayudan a ser mejores. Y escribir lo que aprendemos nos ayuda a no olvidarlo.",
    frase: { t: "Hay que seguir aprendiendo mientras haya algo que no sepamos.", autor: "Séneca", obra: "Cartas a Lucilio, 76" },
    reto: "Hoy copia en un papel una frase de un libro que te haga pensar, y guárdala en un sitio especial.",
  },
  {
    bloque: 9,
    virtud: "justicia",
    titulo: "Ayudar sin que se sepa",
    historia:
      "Los sábados, Daniel acompaña a su tía a la protectora de animales para limpiar jaulas y pasear perros. Nadie le paga ni le dan ningún diploma. El lunes, su compañero Joel le dice que eso es de tontos: «Si no te dan nada, ¿para qué vas?». Daniel se queda pensando qué contestar.",
    pregunta: "¿Qué se lleva Daniel, aunque nadie le dé nada? ¿Qué cambiaría si cada vez que ayudamos lo contáramos para que nos aplaudan?",
    juego: {
      consigna: "¿Depende de Daniel?",
      tipo: "DEPENDE",
      items: [
        { t: "Ir los sábados a la protectora", r: "parte", x: "Él decide que quiere ir, pero necesita que un adulto le acompañe." },
        { t: "Que adopten a los perros", r: "no" },
        { t: "Lo que Joel piense del voluntariado", r: "no" },
        { t: "Cuidar bien a los perros mientras está allí", r: "si" },
        { t: "Contarlo para presumir o guardárselo", r: "si" },
        { t: "Explicarle a Joel por qué le gusta ir", r: "si" },
      ],
    },
    idea: "Ayudar sin esperar nada a cambio es de lo más justo que hay. Quien ayuda no necesita contarlo: ya se lleva algo bueno dentro.",
    frase: { t: "Que calle quien hizo el favor; que lo cuente quien lo recibió.", autor: "Séneca", obra: "Sobre los beneficios, II, 11" },
    reto: "Haz hoy un favor a alguien sin contárselo a nadie después.",
  },
  {
    bloque: 9,
    virtud: "coraje",
    titulo: "El mundo que queremos dejar",
    historia:
      "La clase de Leire prepara una cápsula del tiempo que se abrirá cuando terminen el instituto. Cada uno escribe cómo quiere que sea el mundo entonces: más árboles, playas limpias, nadie solo en el recreo. Leire relee su carta y suspira: «Qué bonito, pero yo sola no puedo cambiar nada».",
    pregunta: "¿Tiene razón Leire? ¿Qué podría hacer ella, desde hoy, para acercarse a ese mundo?",
    juego: {
      consigna: "¿Es real o lo imagina Leire?",
      tipo: "REAL",
      items: [
        { t: "Sus deseos están escritos en la carta", r: "si" },
        { t: "Yo sola no puedo cambiar nada", r: "no", x: "Sola no lo cambia todo, pero sí su parte, y eso cuenta." },
        { t: "Si cada uno recoge un papel, el patio mejora", r: "si" },
        { t: "Lo que haga una niña de quinto no importa", r: "no" },
        { t: "Invitar a alguien a jugar cambia su recreo", r: "si" },
        { t: "Para cambiar algo hay que ser mayor", r: "no" },
      ],
    },
    idea: "Saber hacia dónde quieres ir te ayuda a dar el primer paso. El mundo que queremos se construye con gestos pequeños, empezando hoy.",
    frase: { t: "Si uno no sabe a qué puerto se dirige, ningún viento le es favorable.", autor: "Séneca", obra: "Cartas a Lucilio, 71" },
    reto: "Escribe un deseo para el mundo y, debajo, una cosa pequeña que harás esta semana para acercarte a él.",
  },
]);
