// La Ciudadela · sesiones del bloque 10 y 11: Pantallas y yo; Cambios y despedidas
window.CIUDADELA_NUEVAS = (window.CIUDADELA_NUEVAS || []).concat([
  // ---------------- Bloque 10 · Pantallas y yo ----------------
  {
    bloque: 10,
    virtud: "justicia",
    titulo: "Risas en el grupo de clase",
    historia: "En el grupo de mensajes de la clase, alguien sube un dibujo de Iván con orejas de burro. Empiezan a llegar caritas llorando de risa, una detrás de otra. Nerea lo ve desde el móvil de su madre. No le hace gracia, pero piensa que, si no pone nada, a lo mejor la toman por aburrida. Iván no ha escrito nada desde ayer.",
    pregunta: "¿Qué siente Iván al ver esas caritas? ¿Qué puede hacer Nerea, dentro y fuera del grupo?",
    juego: {
      consigna: "¿Puede resolverlo Nerea o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Se ríen de Iván en el grupo casi todos los días", r: "adulto" },
        { t: "Nerea quiere escribir a Iván para animarlo", r: "yo" },
        { t: "Alguien amenaza a Iván por mensaje", r: "adulto" },
        { t: "Nerea puso una carita sin pensar y se arrepiente", r: "yo", x: "Puede borrarla y pedirle perdón a Iván. Eso está en su mano." },
        { t: "Crean otro grupo sin Iván para burlarse de él", r: "adulto" },
        { t: "Quiere escribir en el grupo: «Esto no tiene gracia»", r: "yo", x: "Es justo y valiente. Si aun así no paran, toca avisar a un adulto." },
      ],
    },
    nota: "Burlarse de alguien en un grupo de mensajes es acoso si se repite, y no se aguanta. Contárselo a un adulto de confianza SIEMPRE depende de ti, y hacerlo no es chivarse: es proteger.",
    idea: "Una carita de risa también es una forma de participar. En internet, como en el patio, lo justo es no sumarse a la burla y ayudar a quien la sufre.",
    frase: { t: "Si no está bien, no lo hagas. Si no es verdad, no lo digas.", autor: "Marco Aurelio", obra: "Meditaciones, XII, 17" },
    reto: "Si hoy ves una burla en un grupo, no la reenvíes ni la celebres. Cuéntaselo a un adulto de confianza.",
  },
  {
    bloque: 10,
    virtud: "justicia",
    titulo: "Una foto que no es tuya",
    historia: "En el cumpleaños de Carla, Youssef hace una foto justo cuando a ella se le cae un trozo de tarta encima. Sale con la cara llena de nata y la boca abierta. Es graciosísima. Con la tablet de su padre, Youssef ya tiene el grupo de clase abierto y el dedo encima de «enviar».",
    pregunta: "¿Qué pensaría Carla si viera su foto en el grupo? ¿De quién es una foto: de quien la hace o de quien sale en ella?",
    juego: {
      consigna: "¿Depende de Youssef?",
      tipo: "DEPENDE",
      items: [
        { t: "Que a Carla se le cayera la tarta", r: "no" },
        { t: "Preguntarle a Carla si puede enviarla", r: "si" },
        { t: "Borrar la foto si Carla dice que no", r: "si" },
        { t: "Lo que hagan otros si la foto llega al grupo", r: "no", x: "Una vez enviada, la foto se puede copiar y reenviar. Ya no hay forma de recogerla." },
        { t: "Que Carla se ría o se enfade", r: "parte", x: "Lo que Carla sienta es cosa suya, pero Youssef puede ahorrarle un mal rato." },
        { t: "Contárselo a un adulto si alguien reenvía fotos sin permiso", r: "si" },
      ],
    },
    nota: "Enviar o reenviar fotos de alguien sin su permiso puede hacerle mucho daño. Si circula una foto tuya o de otra persona, contárselo a un adulto de confianza SIEMPRE depende de ti.",
    idea: "La cara de una persona es suya. Antes de enviar una foto de alguien, se pregunta. Lo que se envía ya no se puede recoger.",
    frase: { t: "No discutas más sobre cómo tiene que ser una buena persona. Sé una.", autor: "Marco Aurelio", obra: "Meditaciones, X, 16" },
    reto: "Hoy, antes de hacer o enseñar una foto de alguien, pregúntale: «¿Te importa?».",
  },
  {
    bloque: 10,
    virtud: "coraje",
    titulo: "Alguien en la partida",
    historia: "Aitana juega a un videojuego en línea con la tablet de casa. Un jugador que dice tener once años la ayuda a pasar de nivel y le escribe cosas simpáticas. Hoy le promete muchas monedas del juego si le manda una foto suya. «Es nuestro secreto, ¿vale?», añade. Aitana siente algo raro en la tripa.",
    pregunta: "¿Por qué crees que ese jugador quiere que sea un secreto? ¿Qué le está diciendo a Aitana esa sensación rara en la tripa?",
    juego: {
      consigna: "¿Puede resolverlo Aitana o hay que avisar a un adulto?",
      tipo: "AYUDA",
      items: [
        { t: "Un desconocido le pide una foto a cambio de premios", r: "adulto" },
        { t: "Alguien del juego le pide guardar un secreto", r: "adulto", x: "Los secretos que te hacen sentir raro no se guardan. Contarlo no te mete en ningún lío." },
        { t: "Un jugador desconocido quiere hablar por otra aplicación", r: "adulto" },
        { t: "Pierde una partida y le da mucha rabia", r: "yo" },
        { t: "Un compañero de clase le gana siempre y presume", r: "yo" },
        { t: "Alguien le pregunta su dirección o su colegio", r: "adulto" },
      ],
    },
    nota: "Nadie desconocido en internet debe pedirte fotos, datos ni secretos. Si pasa, contárselo a un adulto de confianza SIEMPRE depende de ti, y no te vas a meter en ningún lío por hacerlo.",
    idea: "Pedir ayuda a tiempo es de valientes. Si alguien en internet te pide fotos, datos o secretos, cierra y cuéntaselo enseguida a un adulto.",
    frase: { t: "No te dé vergüenza que te ayuden. Como el soldado que no puede subir solo la muralla, a veces necesitamos una mano.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 7" },
    reto: "Hoy, cuenta en casa con quién juegas en internet y decidid juntos qué haréis si te escribe un desconocido.",
  },
  {
    bloque: 10,
    virtud: "coraje",
    titulo: "El vídeo que no me deja dormir",
    historia: "Hugo estaba viendo vídeos de fútbol en la tablet de su hermano cuando, sin que él lo eligiera, empezó otro: una criatura con la cara deformada que aparecía de golpe en la oscuridad. Lo quitó enseguida, pero ya era tarde. Esa noche no puede dormir y no se atreve a contarlo: le da vergüenza y cree que le quitarán la tablet.",
    pregunta: "¿Qué parte del miedo de Hugo viene del vídeo y qué parte de lo que imagina? ¿Qué pasaría si se lo contara a alguien?",
    juego: {
      consigna: "¿Es real o lo imagina Hugo?",
      tipo: "REAL",
      items: [
        { t: "Vio un vídeo que le asustó", r: "si" },
        { t: "La criatura está escondida en su habitación", r: "no" },
        { t: "Tiene el corazón acelerado y no se duerme", r: "si" },
        { t: "Si lo cuenta, se reirán de él", r: "no", x: "Es lo que teme, pero no lo sabe. A casi todos los adultos les ha pasado algo parecido." },
        { t: "Le quitarán la tablet para siempre", r: "no", x: "Lo imagina. Lo más probable es que le ayuden a no volver a encontrarse esos vídeos." },
        { t: "Esos vídeos se hacen con maquillaje y efectos", r: "si" },
      ],
    },
    nota: "Si algo que ves en una pantalla te asusta o no te deja dormir, contárselo a un adulto de confianza SIEMPRE depende de ti, y no te vas a meter en ningún lío por hacerlo.",
    idea: "Lo que asusta en una pantalla crece en silencio y se hace pequeño al contarlo. Contárselo a un adulto es de valientes.",
    frase: { t: "Son más las cosas que nos asustan que las que nos hacen daño. Sufrimos más en la imaginación que en la realidad.", autor: "Séneca", obra: "Cartas a Lucilio, 13" },
    reto: "Si algo que has visto en una pantalla te da vueltas en la cabeza, cuéntaselo hoy a un adulto de confianza.",
  },
  {
    bloque: 10,
    virtud: "sabiduria",
    titulo: "Reenvía esto a diez personas",
    historia: "A Salma le llega un mensaje por el grupo del equipo de fútbol: «Mañana cortan el agua en todo el barrio y no habrá cole. ¡Reenvíalo a diez personas o tendrás mala suerte!». Lleva muchos signos de exclamación y lo han reenviado muchas veces. Salma ya ha empezado a elegir contactos cuando se para un momento.",
    pregunta: "¿Qué pistas tiene el mensaje de que puede ser un bulo? ¿Cómo podría Salma comprobarlo antes de reenviarlo?",
    juego: {
      consigna: "¿Se sabe o es un rumor?",
      tipo: "RUMOR",
      items: [
        { t: "«Mañana no hay cole», según un mensaje reenviado muchas veces", r: "no" },
        { t: "La circular del cole anuncia la excursión del viernes", r: "si" },
        { t: "Si no lo reenvías, tendrás mala suerte", r: "no", x: "Nadie puede saber eso. Las cadenas usan el miedo para que las reenvíes." },
        { t: "La tutora lo ha dicho hoy en clase", r: "si" },
        { t: "Lo ha reenviado tanta gente que será verdad", r: "no", x: "Que mucha gente lo reenvíe no lo hace verdad; solo hace que corra más." },
        { t: "La web del ayuntamiento avisa del corte de agua", r: "si" },
      ],
    },
    idea: "Antes de reenviar, para y comprueba. Un bulo viaja rápido porque cada uno le da un empujón; tú puedes ser quien lo frena.",
    frase: { t: "Si alguien me demuestra que me equivoco, cambiaré con gusto de opinión. Busco la verdad, y la verdad nunca ha hecho daño a nadie.", autor: "Marco Aurelio", obra: "Meditaciones, VI, 21" },
    reto: "Hoy, si te llega una cadena o una noticia rara, no la reenvíes: pregunta antes a un adulto si es verdad.",
  },
  {
    bloque: 10,
    virtud: "sabiduria",
    titulo: "Vidas de vídeo",
    historia: "Mateo ve cada tarde los vídeos de un chico de su edad que tiene una habitación enorme, viaja a sitios increíbles y siempre está sonriendo. Después, Mateo mira su cuarto, que comparte con su hermano, y todo le parece aburrido. «Mi vida es un rollo», piensa, y se le quitan las ganas de bajar a jugar.",
    pregunta: "¿Qué no se ve en esos vídeos? ¿Es justo comparar tu día entero con los mejores minutos de otra persona?",
    juego: {
      consigna: "¿Es un hecho o es lo que Mateo se dice?",
      tipo: "HECHO",
      items: [
        { t: "El chico del vídeo siempre está contento", r: "no", x: "Mateo solo ve lo que ese chico decide enseñar, grabado y recortado." },
        { t: "Mateo comparte cuarto con su hermano", r: "si" },
        { t: "Mi vida es un rollo", r: "no" },
        { t: "Esta mañana ha metido un gol en el recreo", r: "si" },
        { t: "Todo el mundo tiene más cosas que yo", r: "no" },
        { t: "Mateo solo ve unos minutos de la vida de ese chico", r: "si" },
      ],
    },
    idea: "En los vídeos se ve lo mejor, elegido y recortado. Compararte con eso es como comparar tu día entero con un anuncio.",
    frase: { t: "Lo que inquieta a las personas no son las cosas, sino las opiniones que tienen sobre las cosas.", autor: "Epicteto", obra: "Enquiridión, 5" },
    reto: "Esta noche, apunta tres cosas buenas de tu día que nunca saldrían en un vídeo.",
  },
  {
    bloque: 10,
    virtud: "templanza",
    titulo: "¿Cuántos me gusta?",
    historia: "Irina envía al grupo de clase, desde el móvil de su madre, una foto del cómic que ha dibujado durante toda la semana. A los cinco minutos solo tiene dos reacciones. Irina mira el móvil otra vez, y otra, y otra. Ya no se acuerda de lo bien que se lo pasó dibujando.",
    pregunta: "¿De quién depende que el cómic de Irina sea bueno? ¿Qué le está quitando mirar tanto el móvil?",
    juego: {
      consigna: "¿Depende de Irina?",
      tipo: "DEPENDE",
      items: [
        { t: "Cuántas reacciones recibe su cómic", r: "no" },
        { t: "Cuántas veces mira el móvil", r: "si" },
        { t: "Disfrutar dibujando", r: "si" },
        { t: "Sentirse un poco decepcionada", r: "parte", x: "La decepción llega sola y es normal. Lo que se dice después sí depende de ella." },
        { t: "Que sus compañeros estén ocupados y no lo vean", r: "no" },
        { t: "Seguir dibujando aunque tenga pocas reacciones", r: "si" },
      ],
    },
    idea: "Tu valor no se mide en «me gusta». Lo que haces con cariño vale lo mismo si lo ve una persona o si lo ven cien.",
    frase: { t: "Mira dentro de ti. Dentro está la fuente del bien, y siempre puede brotar si sigues cavando.", autor: "Marco Aurelio", obra: "Meditaciones, VII, 59" },
    reto: "Hoy, haz algo que te guste solo por el gusto de hacerlo, sin enseñárselo a nadie.",
  },
  {
    bloque: 10,
    virtud: "templanza",
    titulo: "El pacto de las pantallas",
    historia: "En casa de Chen van a hacer un pacto de pantallas para toda la familia, adultos incluidos. Su madre le pide que proponga él algunas normas. Chen piensa primero en «sin límite», pero se acuerda de las tardes en que acabó con dolor de cabeza y sin hacer nada de lo que quería. Coge un papel y se sienta a pensar.",
    pregunta: "¿Cómo sabes que una pantalla ya te está quitando más de lo que te da? ¿Qué norma propondrías tú para los adultos de tu casa?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Ver una película en familia el sábado", r: "justo" },
        { t: "Jugar hasta medianoche un día de cole", r: "pasa" },
        { t: "Llevarse la tablet a la cama", r: "pasa" },
        { t: "Jugar un rato después de hacer los deberes", r: "justo" },
        { t: "No jugar nunca, aunque haya tiempo y me apetezca", r: "corto", x: "La templanza no es prohibirse todo: es encontrar la medida." },
        { t: "Mirar el móvil en cada comida", r: "pasa" },
      ],
    },
    idea: "La pantalla no es buena ni mala: depende de la medida. El punto justo es el que te deja tiempo para todo lo demás.",
    frase: { t: "No es que tengamos poco tiempo, es que perdemos mucho.", autor: "Séneca", obra: "Sobre la brevedad de la vida, 1" },
    reto: "Hoy, antes de encender una pantalla, decide cuánto rato vas a usarla. Cuando acabe el tiempo, apágala tú.",
  },
  {
    bloque: 10,
    virtud: "templanza",
    titulo: "Escrito, pero sin enviar",
    historia: "Valentina descubre en el grupo que Martina y otras amigas han quedado el sábado en el parque sin decirle nada. Con el móvil de su padre escribe un mensaje larguísimo, en mayúsculas, con palabras que nunca le diría a la cara. Tiene el dedo sobre el botón de enviar. Le tiemblan un poco las manos.",
    pregunta: "¿Qué puede pasar si Valentina lo envía ahora? ¿Y si espera hasta mañana?",
    juego: {
      consigna: "¿Depende de Valentina?",
      tipo: "DEPENDE",
      items: [
        { t: "Que sus amigas quedaran sin ella", r: "no" },
        { t: "Sentirse dolida y enfadada", r: "parte", x: "Esa emoción llega sola y tiene sentido. Qué hace con ella sí depende de Valentina." },
        { t: "Enviar el mensaje ahora o esperar", r: "si" },
        { t: "Borrar el mensaje cuando ya lo han leído", r: "no", x: "Aunque lo borre, ya lo han visto o pueden haberlo guardado." },
        { t: "Hablar con Martina en persona mañana", r: "si" },
        { t: "Lo que Martina le responda", r: "no" },
      ],
    },
    idea: "Un mensaje escrito en caliente se lee en frío. Si estás enfadado, escribe si lo necesitas, pero espera antes de enviar.",
    frase: { t: "El mejor remedio contra la ira es esperar.", autor: "Séneca", obra: "Sobre la ira, II, 29" },
    reto: "Si hoy te enfadas con alguien, no escribas nada en una pantalla durante una hora. Luego decide qué decir.",
  },
  {
    bloque: 10,
    virtud: "coraje",
    titulo: "Un reto que no es valiente",
    historia: "En el parque, unos chicos mayores enseñan en el móvil un reto viral: hacer algo peligroso y grabarlo para subirlo. Uno de ellos mira a Rubén: «Venga, que tú eres el más atrevido. ¿O te da miedo?». Los demás se ríen y sacan el móvil para grabarlo. Rubén nota que le arde la cara.",
    pregunta: "¿Qué es ser valiente en esta situación? ¿Qué le da más miedo a Rubén: hacerse daño o que se rían de él?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto de valor?",
      tipo: "PUNTO",
      items: [
        { t: "Hacer el reto para que no le llamen miedica", r: "pasa" },
        { t: "Decir «yo paso» aunque se rían", r: "justo" },
        { t: "Ver a otro hacerlo y quedarse callado", r: "corto", x: "Callar cuando alguien puede hacerse daño es quedarse corto de valor." },
        { t: "Avisar a un adulto si alguien va a hacerlo", r: "justo" },
        { t: "Grabar a otro mientras hace el reto", r: "pasa", x: "Grabar también empuja a otro a ponerse en peligro." },
        { t: "Proponer un reto divertido y sin peligro", r: "justo" },
      ],
    },
    nota: "Si alguien te presiona para hacer algo peligroso, o ves que otro va a hacerlo, contárselo a un adulto de confianza SIEMPRE depende de ti. No es chivarse: es cuidar.",
    idea: "Coraje no es hacer cualquier cosa para que te aplaudan. A veces lo más valiente es decir «no» delante de todos.",
    frase: { t: "Sé como el acantilado contra el que rompen las olas: se mantiene firme, y a su alrededor el agua se calma.", autor: "Marco Aurelio", obra: "Meditaciones, IV, 49" },
    reto: "Piensa hoy una frase corta para decir que no a un reto peligroso. Ensáyala en voz alta.",
  },
  {
    bloque: 10,
    virtud: "sabiduria",
    titulo: "Mi contraseña es mía",
    historia: "Daniela tiene una cuenta en un juego de la tablet familiar, con una contraseña que eligió con su padre. Fátima, su mejor amiga, le dice: «Dámela y te paso el nivel esta noche. Si somos amigas de verdad, no hay secretos». Daniela no quiere que Fátima se enfade, pero algo le dice que no es buena idea.",
    pregunta: "¿Guardar una contraseña es tener secretos con una amiga? ¿Cómo podría Daniela decir que no sin herir a Fátima?",
    juego: {
      consigna: "¿Depende de Daniela?",
      tipo: "DEPENDE",
      items: [
        { t: "Guardar su contraseña solo para ella y su familia", r: "si" },
        { t: "Que Fátima se moleste un rato", r: "parte", x: "Cómo se lo diga puede ayudar, pero lo que sienta Fátima es cosa de Fátima." },
        { t: "Elegir con su familia una contraseña difícil de adivinar", r: "si" },
        { t: "Que alguien intente entrar en su cuenta", r: "no" },
        { t: "Avisar a un adulto si alguien entra en su cuenta", r: "si" },
        { t: "Explicarle a Fátima que no es por desconfianza", r: "si" },
      ],
    },
    idea: "Una contraseña es como la llave de casa: no se presta ni al mejor amigo. Guardarla no es desconfiar, es cuidar lo tuyo.",
    frase: { t: "Primero decide qué persona quieres ser. Después, haz lo que tengas que hacer.", autor: "Epicteto", obra: "Disertaciones, III, 23" },
    reto: "Hoy, repasa con tu familia qué contraseñas usas y quién las conoce. Solo tu familia debería saberlas.",
  },
  {
    bloque: 10,
    virtud: "justicia",
    titulo: "Aquí, con los de verdad",
    historia: "Los abuelos de Gonzalo han venido de su pueblo a pasar el domingo. Durante la comida, el abuelo cuenta cómo una vez se escapó una cabra por toda la plaza, y todos se ríen. Gonzalo se ha perdido la historia: estaba mirando vídeos debajo de la mesa. Cuando levanta la vista, el abuelo ya está recogiendo los platos.",
    pregunta: "¿Qué se ha perdido Gonzalo? ¿Cómo crees que se ha sentido su abuelo?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Dejar el móvil en otra habitación durante la comida", r: "templanza" },
        { t: "Escuchar al abuelo mirándole a los ojos", r: "justicia" },
        { t: "Pensar qué importa más ahora: el vídeo o la familia", r: "sabiduria" },
        { t: "Proponer comer sin pantallas aunque otros protesten", r: "coraje" },
        { t: "Pedirle al abuelo que repita la historia de la cabra", r: "justicia", x: "Es darle la atención que se merece quien ha venido a verte." },
        { t: "Decir que no a otro vídeo para jugar a las cartas", r: "templanza" },
      ],
    },
    idea: "Quien está a la vez en una pantalla y en una mesa no está del todo en ninguna. Estar presente es un regalo para quien te quiere.",
    frase: { t: "Quien está en todas partes no está en ninguna.", autor: "Séneca", obra: "Cartas a Lucilio, 2" },
    reto: "En la cena de hoy, deja las pantallas lejos y pregúntale a alguien de tu familia algo de su día.",
  },

  // ---------------- Bloque 11 · Cambios y despedidas ----------------
  {
    bloque: 11,
    virtud: "sabiduria",
    titulo: "Lo que me llevo a la casa nueva",
    historia: "La familia de Alejandro se muda en julio a un piso en otro barrio. Seguirá en el mismo cole, pero ya no podrá bajar a jugar con los vecinos de siempre. Por la noche, mira su habitación medio llena de cajas y piensa que allí todo será peor. Luego se acuerda de que, al principio, este barrio tampoco le gustaba.",
    pregunta: "¿Qué cambia de verdad para Alejandro y qué se lleva con él a donde vaya? ¿Qué cosa buena podría traerle el cambio?",
    juego: {
      consigna: "¿Es real o lo imagina Alejandro?",
      tipo: "REAL",
      items: [
        { t: "Se mudan a otro barrio en julio", r: "si" },
        { t: "En el barrio nuevo nadie querrá jugar con él", r: "no" },
        { t: "Seguirá en el mismo cole con sus amigos", r: "si" },
        { t: "Le da pena dejar a sus vecinos", r: "si" },
        { t: "Allí todo será peor", r: "no", x: "Es una predicción, no un hecho: todavía no conoce el barrio nuevo." },
        { t: "Va a perder a todos sus amigos", r: "no" },
      ],
    },
    idea: "Los cambios dan miedo porque todavía no los conocemos, pero también traen cosas nuevas. Tu forma de ser viaja contigo: tu ciudadela se muda contigo.",
    frase: { t: "Lo que tienes que cambiar es tu forma de ser, no el lugar donde estás.", autor: "Séneca", obra: "Cartas a Lucilio, 28" },
    reto: "Piensa en un cambio que te dio miedo y salió mejor de lo que creías. Cuéntaselo hoy a alguien.",
  },
  {
    bloque: 11,
    virtud: "sabiduria",
    titulo: "El balance de las cuatro virtudes",
    historia: "Es el último mes del curso y la tutora de Samuel reparte un folio con cuatro columnas: sabiduría, justicia, coraje y templanza. «Escribid algo que hayáis hecho este año en cada una», dice. Samuel se queda mirando el papel en blanco. Al principio cree que no ha hecho nada especial. Luego empieza a recordar.",
    pregunta: "¿Qué pondrías tú en cada columna? ¿En qué virtud crees que has crecido más este curso?",
    juego: {
      consigna: "¿Qué virtud se ve aquí?",
      tipo: "VIRTUD",
      items: [
        { t: "Confesar que rompí algo aunque me castigaran", r: "coraje" },
        { t: "Contar hasta diez antes de contestar mal", r: "templanza" },
        { t: "Comprobar un rumor antes de creérmelo", r: "sabiduria" },
        { t: "Invitar a jugar a alguien que estaba solo", r: "justicia", x: "También es coraje: acercarse a quien está solo cuesta." },
        { t: "Apagar la consola cuando tocaba", r: "templanza" },
        { t: "Preguntar en clase aunque me diera vergüenza", r: "coraje" },
      ],
    },
    idea: "Crecer por dentro no se nota en un día, pero sí en un curso. Mirar atrás ayuda a ver todo lo que has construido.",
    frase: { t: "Vivir bien se consigue poco a poco, pero no es poca cosa.", autor: "Zenón de Citio", obra: "según Diógenes Laercio, Vidas, VII, 26" },
    reto: "Escribe hoy una cosa que hayas hecho este curso en cada virtud. Guárdala para leerla en septiembre.",
  },
  {
    bloque: 11,
    virtud: "justicia",
    titulo: "Gracias que no se dijeron",
    historia: "Lola hace una lista de personas que la han ayudado este curso: la monitora del comedor que la consoló un día malo, el conserje que encontró su chaqueta, un compañero que le explicó las divisiones con paciencia. Se da cuenta de que a casi ninguno le dio las gracias de verdad. Quedan solo dos semanas de curso.",
    pregunta: "¿Por qué es justo dar las gracias, y no solo sentirlas? ¿A quién te gustaría agradecer algo de este curso?",
    juego: {
      consigna: "¿Depende de Lola?",
      tipo: "DEPENDE",
      items: [
        { t: "Dar las gracias antes de que acabe el curso", r: "si" },
        { t: "Recordar quién la ha ayudado", r: "si" },
        { t: "Que la monitora se emocione al leer su nota", r: "no" },
        { t: "Sentir vergüenza al decirlo en persona", r: "parte", x: "La vergüenza llega sola. Si le cuesta hablar, puede elegir escribir una nota." },
        { t: "Que el conserje se acuerde de la chaqueta", r: "no" },
        { t: "Decir exactamente qué le ayudó", r: "si" },
      ],
    },
    idea: "Agradecer es devolver un poco de lo que recibimos. Unas gracias concretas, diciendo qué te ayudó, valen mucho más que unas gracias rápidas.",
    frase: { t: "Que calle quien hizo el favor; que lo cuente quien lo recibió.", autor: "Séneca", obra: "Sobre los beneficios, II, 11" },
    reto: "Hoy, da las gracias a alguien del cole diciéndole exactamente qué hizo por ti este curso.",
  },
  {
    bloque: 11,
    virtud: "coraje",
    titulo: "Los últimos días con Omar",
    historia: "Omar, el mejor amigo de Noa, se muda a otra ciudad en verano porque su madre ha encontrado trabajo allí. Desde que lo sabe, Noa lo evita en el recreo y juega con otros. Si no está con él, piensa, dolerá menos cuando se vaya. Omar no entiende qué pasa y cada día está más callado.",
    pregunta: "¿Por qué crees que Noa evita a Omar? ¿Qué podrían hacer con los días que les quedan juntos?",
    juego: {
      consigna: "¿Es un hecho o es lo que Noa se dice?",
      tipo: "HECHO",
      items: [
        { t: "Omar se muda a otra ciudad en verano", r: "si" },
        { t: "Si no estoy con él, dolerá menos", r: "no", x: "Es lo que Noa se dice para protegerse. Pero ahora lo están pasando mal los dos." },
        { t: "Noa está triste por la mudanza", r: "si" },
        { t: "Ya no seremos amigos nunca más", r: "no" },
        { t: "Pueden escribirse o llamarse con ayuda de sus familias", r: "si" },
        { t: "Omar no me va a echar de menos", r: "no" },
      ],
    },
    idea: "Despedirse duele porque la amistad vale mucho. Aprovechar el tiempo que queda y decir lo que sientes es más valiente que esconderse.",
    frase: { t: "Todo lo demás es ajeno: solo el tiempo es nuestro.", autor: "Séneca", obra: "Cartas a Lucilio, 1" },
    reto: "Dile hoy a un amigo o una amiga algo que valoras de vuestra amistad.",
  },
  {
    bloque: 11,
    virtud: "coraje",
    titulo: "Dicen que en sexto…",
    historia: "El curso que viene, la clase de Jimena tendrá tutor nuevo y se mudará a la planta de arriba, la de los mayores. En el patio corren rumores: que el nuevo tutor es durísimo, que hay deberes todos los días, que los de la otra clase son unos creídos. Jimena lleva días con un nudo en el estómago.",
    pregunta: "¿Cuánto de lo que asusta a Jimena lo sabe de verdad? ¿Qué podría hacer el primer día para ponérselo más fácil?",
    juego: {
      consigna: "¿Se sabe o es un rumor?",
      tipo: "RUMOR",
      items: [
        { t: "El curso que viene tendrán tutor nuevo", r: "si" },
        { t: "El nuevo tutor es durísimo", r: "no" },
        { t: "Los de la otra clase son unos creídos", r: "no", x: "Es una etiqueta para un grupo entero, y Jimena todavía no los conoce." },
        { t: "La tutora ha dicho quién será el nuevo tutor", r: "si" },
        { t: "En sexto hay deberes todos los días", r: "no" },
        { t: "Jimena ha visto al nuevo tutor en el comedor", r: "si" },
      ],
    },
    idea: "Lo nuevo asusta porque lo imaginamos antes de conocerlo. El coraje es ir a descubrirlo por ti mismo.",
    frase: { t: "No es que no nos atrevamos porque las cosas sean difíciles. Son difíciles porque no nos atrevemos.", autor: "Séneca", obra: "Cartas a Lucilio, 104" },
    reto: "Hoy, habla con alguien de la otra clase con quien casi nunca hablas. Pregúntale qué le gusta hacer.",
  },
  {
    bloque: 11,
    virtud: "templanza",
    titulo: "Un verano en mis manos",
    historia: "Adam está deseando que llegue el verano. Se imagina dos meses enteros de consola, dormir hasta tarde y cero libros. Su madre le recuerda que por las mañanas tendrá que ayudar con su hermana pequeña y que habrá días de calor sin piscina. Adam protesta: «¡Pues vaya verano!». Todavía no ha empezado y ya está enfadado con él.",
    pregunta: "¿Qué parte del verano de Adam depende de él? ¿Cómo sería un verano con el punto justo de todo?",
    juego: {
      consigna: "¿Depende de Adam?",
      tipo: "DEPENDE",
      items: [
        { t: "El calor que haga en agosto", r: "no" },
        { t: "Cuántas horas pasa con la consola", r: "parte", x: "Hay normas en casa, pero dentro de ellas Adam elige cuánto rato." },
        { t: "Leer algo que le guste de verdad", r: "si" },
        { t: "Que la piscina esté abierta", r: "no" },
        { t: "Cómo trata a su hermana pequeña", r: "si" },
        { t: "Qué hace en una tarde de calor en casa", r: "si" },
      ],
    },
    idea: "El verano no se elige entero, pero cada día se elige un poco. La templanza ayuda a que haya sitio para todo.",
    frase: { t: "¿Qué hay que hacer, entonces? Sacar el mejor partido de lo que depende de nosotros, y tomar lo demás como venga.", autor: "Epicteto", obra: "Disertaciones, I, 1" },
    reto: "Haz hoy una lista de cinco cosas que quieres hacer este verano y que dependen de ti. Que no todas sean pantallas.",
  },
  {
    bloque: 11,
    virtud: "sabiduria",
    titulo: "Carta a mi yo de septiembre",
    historia: "La tutora de Elena propone a la clase escribir una carta a su yo del curso que viene. La guardará en un sobre cerrado y la devolverá en septiembre. Elena no sabe qué poner. ¿Que saque buenas notas? ¿Que sea la más popular? Mordisquea el lápiz hasta que se le ocurre preguntarse qué tipo de persona quiere ser.",
    pregunta: "¿Qué diferencia hay entre desear algo y proponerse algo? ¿Qué le escribirías tú a tu yo de septiembre?",
    juego: {
      consigna: "¿Depende de Elena?",
      tipo: "DEPENDE",
      items: [
        { t: "Sacar un diez en todos los exámenes", r: "parte", x: "Puede estudiar y esforzarse, pero la nota exacta no depende solo de ella." },
        { t: "Ser la más popular de la clase", r: "no" },
        { t: "Ayudar a quien llegue nuevo a la clase", r: "si" },
        { t: "Que le toque el maestro que quiere", r: "no" },
        { t: "Contar hasta diez cuando se enfade", r: "si" },
        { t: "Leer la carta en septiembre y revisarla", r: "si" },
      ],
    },
    idea: "Si sabes qué persona quieres ser, sabes hacia dónde remar. Un propósito que depende de ti vale más que un deseo que no.",
    frase: { t: "Si uno no sabe a qué puerto se dirige, ningún viento le es favorable.", autor: "Séneca", obra: "Cartas a Lucilio, 71" },
    reto: "Escribe hoy tres frases a tu yo de septiembre con cosas que dependan de ti. Guárdalas en un sitio seguro.",
  },
  {
    bloque: 11,
    virtud: "templanza",
    titulo: "La ciudadela no se va de vacaciones",
    historia: "Marcos ha aprendido este curso a respirar hondo cuando se enfada y a repasar su día antes de dormir. Le ha costado meses. Ahora piensa: «En verano no hay cole, así que me tomo vacaciones de todo eso». Su hermana mayor se ríe: «¿Y también te vas a tomar vacaciones de montar en bici?».",
    pregunta: "¿Qué quiere decir la hermana de Marcos? ¿Qué cosas de este curso quieres seguir practicando en verano?",
    juego: {
      consigna: "¿Me paso, punto justo o me quedo corto?",
      tipo: "PUNTO",
      items: [
        { t: "Olvidarme de todo lo aprendido hasta septiembre", r: "corto" },
        { t: "Hacer fichas tres horas al día en agosto", r: "pasa", x: "Descansar también hace falta. Pasarse tampoco es templanza." },
        { t: "Respirar hondo cuando me enfade con mis primos", r: "justo" },
        { t: "Jugar a la consola todo el día porque es verano", r: "pasa" },
        { t: "Leer un rato casi todos los días", r: "justo" },
        { t: "No leer ni una página en dos meses", r: "corto" },
      ],
    },
    idea: "Lo que has construido por dentro no se derrumba en vacaciones, pero se cuida practicando un poco. Descansar y seguir practicando caben en el mismo verano.",
    frase: { t: "Una mente tranquila es una ciudadela: no hay lugar más fuerte donde refugiarse.", autor: "Marco Aurelio", obra: "Meditaciones, VIII, 48" },
    reto: "Elige hoy una cosa de este curso que quieras seguir practicando en verano. Escríbela y ponla en tu habitación.",
  },
  {
    bloque: 11,
    virtud: "justicia",
    titulo: "Una fiesta con sitio para todos",
    historia: "Para la fiesta de fin de curso, la clase prepara un baile por grupos. Sofía y sus amigas ya han formado el suyo y están ensayando en el patio. Julia, que llegó en enero, las mira desde el banco con el bocadillo sin abrir. Una de las amigas susurra: «Si entra ella, no nos va a salir igual».",
    pregunta: "¿Cómo se siente Julia en ese banco? ¿Qué es más importante en una fiesta: que el baile salga perfecto o que todos se sientan parte?",
    juego: {
      consigna: "¿Depende de Sofía?",
      tipo: "DEPENDE",
      items: [
        { t: "Proponer al grupo que Julia baile con ellas", r: "si" },
        { t: "Que a Julia le apetezca bailar", r: "no" },
        { t: "Lo que digan sus amigas al principio", r: "no" },
        { t: "Que el baile salga perfecto", r: "parte", x: "Pueden ensayar mucho, pero nunca sale todo perfecto. Y tampoco hace falta." },
        { t: "Sentarse un rato con Julia en el banco", r: "si" },
        { t: "Contárselo a un adulto si a Julia la dejan siempre fuera", r: "si" },
      ],
    },
    nota: "Dejar a alguien fuera una vez duele; si pasa siempre, es exclusión y no se aguanta. Contárselo a un adulto de confianza SIEMPRE depende de ti.",
    idea: "Una fiesta es buena cuando nadie se queda mirando desde el banco. Hacer sitio a alguien es justicia, y también alegría compartida.",
    frase: { t: "Ningún bien nos alegra de verdad si no tenemos con quién compartirlo.", autor: "Séneca", obra: "Cartas a Lucilio, 6" },
    reto: "Hoy, en el recreo, busca a alguien que esté solo y proponle jugar o hablar un rato.",
  },
]);
