// ============================================================
// Novela Colectiva — léxico base (ARCHIVO GENERADO, no editar a
// mano salvo para añadir palabras al final de una lista).
//
// Parte de las listas ya curadas para 5.º y 6.º en Cifras y Letras
// y añade el vocabulario propio de la narración (aventura, fantasía,
// misterio), que es el que de verdad usan escribiendo una novela.
//
// A partir de estas listas, diccionario.js genera solo los plurales,
// los femeninos, los adverbios en -mente y las formas verbales, así
// que el diccionario efectivo es muchísimo mayor.
//
// Ninguna lista puede ser completa: por eso una palabra desconocida
// nunca se marca como falta, solo como duda ("¿seguro que se escribe
// así?"), y el docente puede darla por buena en el proyecto.
// ============================================================

// Sustantivos (se generan los plurales).
export const SUSTANTIVOS = [
  "golpe", "empujón", "tirón", "salto", "carrera", "paso", "gesto", "mirada",
  "sonrisa", "mueca", "gruñido", "rugido", "aullido", "graznido", "zumbido",
  "crujido", "chasquido", "estruendo", "estallido", "silbido", "murmullo",
  "resplandor", "destello", "reflejo", "brillo", "penumbra", "tiniebla",
  "acantilado", "risco", "peñasco", "cumbre", "ladera", "hondonada", "llanura",
  "tubo", "valla", "baya", "vello", "cima", "sima", "ola", "onda", "honda",
  "savia", "hierba", "hierro", "hueso", "huevo", "hielo", "hilo", "hoyo",
  "rayo", "cuerda", "soga", "farol", "candil", "brasa", "ceniza", "chispa",
  "humo", "vapor", "barro", "lodo", "roca", "guijarro", "musgo", "helecho",
  "ortiga", "zarza", "espina", "raíz", "tronco", "rama", "brote", "semilla",
  "corteza", "sendero", "vereda", "claro", "linde", "orilla", "ribera",
  "cauce", "remanso", "cascada", "torrente", "manantial", "aljibe", "pozo",
  "molino", "granero", "establo", "pesebre", "cobertizo", "desván", "sótano",
  "buhardilla", "chimenea", "hogar", "umbral", "portón", "aldaba", "cerrojo",
  "candado", "bisagra", "pestillo", "picaporte", "tejado", "alero", "veleta",
  "abanico", "abeja", "abogado", "abrazo", "abrigo", "abril", "abuela",
  "abuelo", "acantilado", "aceite", "acera", "acero", "acierto", "actor",
  "actriz", "afición", "agosto", "agricultor", "agua", "águila", "aguja",
  "agujero", "ahorro", "aire", "ajedrez", "ajo", "alambre", "albañil",
  "aldea", "alegría", "algodón", "aliado", "alienígena", "almohada",
  "almuerzo", "altura", "alumna", "alumno", "amanecer", "amapola", "amiga",
  "amigo", "amistad", "amor", "anchura", "anciano", "ancla", "andamio",
  "andén", "androide", "ángulo", "anillo", "animal", "ánimo", "anochecer",
  "anorak", "antorcha", "año", "apellido", "araña", "árbitro", "árbol",
  "arco", "arcoíris", "ardilla", "arena", "armadura", "armario", "aroma",
  "arquitecto", "arroyo", "arroz", "ascensor", "asiento", "asombro",
  "astronauta", "atajo", "atardecer", "atún", "augurio", "aula", "aumento",
  "autobús", "autopista", "avenida", "aventura", "avestruz", "avión",
  "avispa", "ayuda", "azar", "azúcar", "bailarín", "baile", "bajada",
  "balcón", "ballena", "balón", "banco", "bandada", "bandera", "baño",
  "baraja", "barco", "barrio", "barro", "bata", "batalla", "batería",
  "baúl", "bebé", "beso", "bestia", "biblioteca", "bicicleta", "billete",
  "bizcocho", "boca", "bocadillo", "bolsa", "bolsillo", "bombero",
  "bombilla", "borde", "borrador", "bosque", "bota", "botella", "botón",
  "brazo", "brisa", "bruja", "brujo", "brújula", "bufanda", "búho",
  "burro", "caballero", "caballo", "cabeza", "cable", "cabra", "cadena",
  "caja", "cajón", "calabaza", "calamar", "calcetín", "caldo",
  "calendario", "calle", "calor", "cama", "cámara", "camarero", "cambio",
  "camello", "camino", "camión", "camisa", "camiseta", "campeón", "campo",
  "canario", "canasta", "cancha", "canción", "cangrejo", "canguro",
  "canica", "cantante", "capa", "capital", "capitán", "capitana",
  "capítulo", "cara", "caracol", "carácter", "caramelo", "carcajada",
  "cariño", "carne", "carnicería", "carnicero", "carpintero", "carrera",
  "carretera", "carta", "cartero", "cartón", "casa", "caso", "castillo",
  "casualidad", "catarro", "causa", "caverna", "cebolla", "cebra", "ceja",
  "cemento", "cena", "ceniza", "centinela", "centro", "cepillo", "cerdo",
  "cerebro", "cereza", "cerilla", "cerradura", "césped", "cesta",
  "chancla", "chaqueta", "charco", "chica", "chico", "chillido",
  "chimenea", "chocolate", "chopo", "chorizo", "cielo", "ciencia",
  "científica", "científico", "ciervo", "cifra", "cigüeña", "cilindro",
  "cine", "cintura", "cinturón", "círculo", "ciruela", "ciudad", "clase",
  "clavel", "clavo", "cliente", "clima", "cobre", "coche", "cocina",
  "cocinero", "cocodrilo", "codo", "cofre", "cohete", "cola", "colección",
  "colegio", "colina", "collar", "columna", "columpio", "comarca", "comba",
  "cometa", "comida", "compañero", "compra", "concierto", "conductor",
  "conejo", "conjunto", "conjuro", "cono", "consejo", "contraseña", "copa",
  "copia", "corazón", "cordero", "cordón", "coro", "corona", "correo",
  "corsario", "corteza", "costa", "costumbre", "cráter", "cremallera",
  "criatura", "cristal", "cuaderno", "cuadra", "cuadrado", "cuarto",
  "cubo", "cuchara", "cuchillo", "cuello", "cuenta", "cuento", "cuerda",
  "cuero", "cuerpo", "cueva", "culpa", "cumpleaños", "curva", "dado",
  "deber", "deberes", "dedo", "defecto", "delfín", "dentista", "deporte",
  "derecho", "desafío", "desayuno", "descanso", "descenso", "desenlace",
  "deseo", "desierto", "destino", "detalle", "detective", "día", "diálogo",
  "diario", "dibujo", "dibujos", "diciembre", "diente", "diferencia",
  "dimensión", "dinero", "director", "distancia", "doble", "docena",
  "domingo", "dragón", "ducha", "duda", "duende", "eco", "edad",
  "edificio", "efecto", "ejemplo", "electricista", "elefante", "elfo",
  "enano", "enchufe", "encina", "enemigo", "enero", "enfado", "enfermera",
  "enigma", "enjambre", "ensalada", "ensueño", "entrada", "entrenador",
  "equipaje", "equipo", "erizo", "error", "escalera", "escarabajo",
  "escarcha", "escena", "escenario", "escoba", "escondite", "escritor",
  "escudo", "escuela", "esfera", "esfuerzo", "espacio", "espada",
  "espalda", "espejo", "esperanza", "espía", "esquina", "estación",
  "estadio", "estante", "estómago", "estrella", "estuche", "examen",
  "éxito", "expedición", "experimento", "extraterrestre", "extremo",
  "fábrica", "falda", "fallo", "familia", "fantasma", "farmacia", "faro",
  "favor", "febrero", "fecha", "ficha", "fiebre", "fiesta", "fila",
  "final", "flauta", "flecha", "flor", "foca", "folio", "fontanero",
  "forma", "foto", "fracaso", "frase", "freno", "frente", "fresa", "frío",
  "frontera", "fruta", "frutero", "fruto", "fuego", "fuente", "función",
  "furgoneta", "futuro", "gafas", "galaxia", "galeón", "galleta",
  "gallina", "gallo", "gamba", "ganadero", "ganso", "garaje", "garbanzo",
  "gasolina", "gato", "gaviota", "genio", "gente", "gigante", "gimnasia",
  "girasol", "globo", "gol", "golondrina", "goma", "gorila", "gorra",
  "gorrión", "gorro", "gota", "grada", "grado", "gramo", "granizo",
  "granja", "granjero", "grifo", "grillo", "gripe", "grito", "grupo",
  "guante", "guardián", "guardiana", "guerra", "guitarra", "gusano",
  "gusto", "habitante", "hada", "hambre", "harina", "hechizo", "hecho",
  "helado", "helicóptero", "herida", "hermana", "hermano", "héroe",
  "heroína", "herramienta", "hielo", "hierba", "hierro", "hija", "hijo",
  "hilo", "himno", "hipopótamo", "historia", "hogar", "hoja", "hombre",
  "hombro", "hora", "horizonte", "hormiga", "horno", "hospital", "hucha",
  "huella", "hueso", "huevo", "humo", "idea", "idioma", "iglesia",
  "ilusión", "imagen", "imperio", "infancia", "ingeniero", "instante",
  "instrumento", "intento", "invierno", "invitado", "isla", "jabalí",
  "jabón", "jamón", "jarabe", "jardín", "jardinero", "jarra", "jaula",
  "jefe", "jersey", "jinete", "jirafa", "joven", "judía", "juego",
  "jueves", "juez", "jugador", "juguete", "julio", "junio", "juventud",
  "kilo", "kiwi", "laberinto", "labio", "laboratorio", "lado", "ladrillo",
  "ladrón", "ladrona", "lagarto", "lago", "lágrima", "laguna", "lámpara",
  "lana", "lancha", "lanza", "lápiz", "leche", "lechuga", "lechuza",
  "lengua", "lenteja", "león", "leopardo", "letra", "ley", "leyenda",
  "librería", "libreta", "libro", "liga", "limón", "línea", "linterna",
  "lista", "litro", "llama", "llanto", "llave", "llegada", "lluvia",
  "lobo", "lombriz", "longitud", "loro", "lugar", "luna", "lunes", "luz",
  "madera", "madre", "madrugada", "maestra", "maestro", "mago", "maíz",
  "maldición", "maleta", "manada", "manga", "manguera", "mano", "manta",
  "mantequilla", "manuscrito", "manzana", "mañana", "mapa", "mar",
  "marcador", "margarita", "marinero", "mariposa", "martes", "martillo",
  "marzo", "mayo", "mazmorra", "mecánico", "mechero", "medalla", "media",
  "medianoche", "médico", "medida", "mediodía", "mejillón", "melocotón",
  "melodía", "melón", "memoria", "mensaje", "mensajero", "mentira",
  "mercado", "merienda", "merluza", "mes", "mesa", "meta", "metal",
  "meteorito", "metro", "miedo", "miel", "miércoles", "milagro", "minuto",
  "misión", "misterio", "mitad", "mito", "mochila", "moda", "modelo",
  "momento", "moneda", "mono", "monstruo", "montaña", "monte", "montón",
  "mosca", "mosquito", "motivo", "moto", "motor", "móvil", "muela",
  "muerte", "mujer", "mundo", "muñeca", "muralla", "murciélago", "músculo",
  "museo", "musgo", "música", "músico", "naranja", "nariz", "narrador",
  "narradora", "naturaleza", "nave", "nevera", "nido", "niebla", "nieto",
  "nieve", "niña", "niño", "noche", "nombre", "norma", "nota", "noticia",
  "noviembre", "nube", "número", "oasis", "oca", "océano", "octubre",
  "oficina", "oficio", "ogro", "oído", "ojo", "ola", "olfato", "olivo",
  "olla", "olor", "orden", "ordenador", "oreja", "original", "orilla",
  "oro", "orquesta", "oscuridad", "oso", "otoño", "oveja", "ovni",
  "paciencia", "padre", "página", "país", "paisaje", "pájaro", "pala",
  "palabra", "palacio", "palmera", "paloma", "pan", "panadería",
  "panadero", "pánico", "pantalla", "pantalón", "pantano", "papel",
  "paquete", "par", "parada", "paraguas", "parchís", "parecido", "pared",
  "pareja", "parque", "parte", "partido", "pasadizo", "pasado", "paso",
  "pasta", "pastilla", "patata", "patinete", "patio", "pato", "pavo",
  "paz", "pecho", "pedazo", "pegamento", "peine", "película", "peligro",
  "pelo", "pelota", "peluche", "peluquero", "pena", "pendiente",
  "pensamiento", "penumbra", "pepino", "pera", "perdón", "perfume",
  "pergamino", "periódico", "periodista", "perro", "persona", "personaje",
  "pesadilla", "pescadero", "pescado", "pescador", "peso", "pétalo", "pez",
  "piano", "pie", "piedra", "piel", "pierna", "pijama", "pila", "piloto",
  "pimiento", "pingüino", "pino", "pintor", "pintura", "piña", "pirata",
  "piscina", "piso", "pista", "pizarra", "planeta", "plástica", "plástico",
  "plata", "plátano", "plato", "playa", "plaza", "pócima", "poción",
  "poema", "poeta", "policía", "pollo", "polvo", "popa", "portal",
  "portero", "postre", "precio", "pregunta", "premio", "presagio",
  "presente", "prima", "primavera", "primo", "princesa", "príncipe",
  "principio", "proa", "problema", "prodigio", "profecía", "profesor",
  "programa", "promesa", "protagonista", "provincia", "prueba", "pueblo",
  "puente", "puerta", "puerto", "pulmón", "pulpo", "pulsera", "punto",
  "pupitre", "puzle", "queso", "rabia", "racimo", "radio", "raíz", "rama",
  "ramo", "rana", "raqueta", "rastrillo", "rastro", "rata", "rato",
  "ratón", "rayo", "razón", "rebaja", "rebaño", "receta", "recreo",
  "recta", "rectángulo", "recuerdo", "red", "refresco", "regalo", "región",
  "regla", "regreso", "reina", "reino", "relámpago", "reloj", "remolino",
  "rescate", "respeto", "respuesta", "resta", "resto", "resultado", "reto",
  "revista", "rey", "riesgo", "rinoceronte", "río", "risa", "ritmo",
  "robot", "roca", "rodilla", "rombo", "ropa", "rosa", "rotonda", "rueda",
  "ruido", "sábado", "sábana", "sabor", "sal", "salida", "salón", "salto",
  "salud", "saludo", "sandalia", "sandía", "sangre", "sapo", "sardina",
  "sartén", "satélite", "secreto", "sed", "segundo", "sello", "selva",
  "semáforo", "semana", "semilla", "sendero", "sentido", "señal", "señor",
  "señora", "septiembre", "serpiente", "seta", "sierra", "siglo",
  "silencio", "silla", "sillón", "sirena", "sitio", "sobre", "sobrino",
  "sociedad", "sofá", "sol", "soldado", "solución", "sombra", "sombrero",
  "sonido", "sonrisa", "sopa", "sorpresa", "sorteo", "sospechoso",
  "subida", "suceso", "sudadera", "sueldo", "suelo", "sueño", "suerte",
  "suma", "susto", "susurro", "tableta", "tacto", "taladro", "talento",
  "talla", "taller", "talón", "tamaño", "tambor", "tapa", "tarde", "tarea",
  "tarro", "tarta", "taxi", "taza", "teatro", "techo", "teclado", "tejado",
  "tela", "teléfono", "televisión", "tenedor", "tercio", "ternero",
  "terraza", "terremoto", "terror", "tesoro", "texto", "tiburón", "tiempo",
  "tienda", "tierra", "tigre", "tijera", "tijeras", "timbre", "timón",
  "tirita", "tiza", "toalla", "tobillo", "tobogán", "tomate", "tonelada",
  "torbellino", "tormenta", "torneo", "tornillo", "toro", "torre",
  "tortilla", "tortuga", "tos", "trabajo", "trampa", "tranvía", "travesía",
  "tregua", "tren", "triángulo", "triple", "tripulación", "tristeza",
  "trofeo", "trompeta", "tronco", "trono", "trozo", "trueno", "túnel",
  "turno", "unicornio", "unión", "universo", "uña", "uva", "vaca",
  "vacuna", "valle", "valor", "vampiro", "vaquero", "varita", "vaso",
  "vecindario", "vecino", "vela", "velero", "venda", "vendedor", "venta",
  "ventana", "ventisca", "verano", "verdad", "verdura", "vestido",
  "veterinario", "viaje", "vida", "vídeo", "viento", "viernes", "vigía",
  "villano", "vinagre", "violín", "virtud", "visión", "visita", "vista",
  "volante", "volcán", "voz", "vuelta", "yegua", "yogur", "zanahoria",
  "zapatilla", "zapato", "zona", "zorro", "zumo",
];

// Adjetivos (se generan femenino, plurales y adverbios en -mente).
export const ADJETIVOS = [
  "abierto", "abrasador", "ácido", "alegre", "alto", "amable", "amargo",
  "amarillo", "ancestral", "ancho", "antiguo", "antipático", "ardiente",
  "asombroso", "áspero", "astral", "astuto", "atento", "aterrador",
  "atrevido", "azul", "azulado", "bajo", "barato", "blanco", "blando",
  "bondadoso", "bonito", "bravo", "brillante", "bueno", "caliente",
  "caluroso", "canoso", "cansado", "cariñoso", "caro", "castaño",
  "celeste", "cercano", "cerrado", "cierto", "claro", "cobarde",
  "colorido", "completo", "complicado", "conocido", "contento",
  "contrario", "corriente", "corto", "cuadrado", "curioso", "débil",
  "delgado", "desconocido", "deslumbrante", "despierto", "difícil",
  "diminuto", "distinto", "diurno", "doble", "doméstico", "dorado",
  "dormido", "dulce", "duro", "educado", "egoísta", "empinado",
  "encantado", "enfadado", "enfermo", "enorme", "entero", "escarpado",
  "espantoso", "especial", "estival", "estrecho", "estudioso", "eterno",
  "extraño", "fácil", "falso", "famoso", "feo", "fino", "flojo", "fresco",
  "frío", "fuerte", "gélido", "generoso", "gigantesco", "gordo", "grande",
  "gratuito", "gris", "grisáceo", "grueso", "hábil", "helado", "hermoso",
  "hondo", "húmedo", "humilde", "igual", "imponente", "importante",
  "imposible", "increíble", "inesperado", "infinito", "injusto", "inútil",
  "invernal", "invisible", "joven", "justo", "largo", "legendario",
  "lejano", "lento", "ligero", "limpio", "liso", "listo", "lleno",
  "lluvioso", "lúgubre", "lujoso", "luminoso", "lunar", "mágico",
  "majestuoso", "maldito", "malo", "malvado", "manchado", "manso",
  "marrón", "mayor", "medio", "mejor", "menor", "mentiroso", "minúsculo",
  "misterioso", "mítico", "moderno", "mojado", "morado", "moreno",
  "muerto", "naranja", "necesario", "negro", "nervioso", "nocturno",
  "normal", "nublado", "nuevo", "obediente", "ordenado", "oscuro",
  "otoñal", "oxidado", "pálido", "parecido", "pegajoso", "pelado",
  "peludo", "peor", "pequeño", "pesado", "picante", "plano", "plateado",
  "pobre", "polvoriento", "posible", "precioso", "primaveral", "primero",
  "profundo", "prohibido", "próximo", "puntiagudo", "rápido", "raro",
  "rayado", "recto", "redondo", "reluciente", "repentino", "resbaladizo",
  "revuelto", "rico", "rojizo", "rojo", "rosa", "roto", "rubio", "rugoso",
  "ruidoso", "sabio", "sabroso", "sagrado", "salado", "salvaje", "sano",
  "seco", "segundo", "sencillo", "sigiloso", "silencioso", "simpático",
  "sincero", "siniestro", "solar", "soleado", "sombrío", "sonoro", "soso",
  "suave", "sucio", "tardío", "temible", "templado", "temprano",
  "tenebroso", "tercero", "terrorífico", "tímido", "tonto", "torcido",
  "torpe", "trabajador", "tranquilo", "travieso", "triste", "último",
  "único", "urgente", "útil", "vacío", "vago", "valiente", "vecino",
  "veloz", "ventoso", "veraniego", "verdadero", "verde", "verdoso",
  "viejo", "violeta", "vivo",
];

// Infinitivos (se generan las formas conjugadas).
export const VERBOS = [
  "aburrir", "agradecer", "alcanzar", "amanecer", "anochecer", "apoyar",
  "arreglar", "atender", "avanzar", "callar", "cambiar", "cargar", "colocar",
  "comparar", "completar", "comprobar", "comunicar", "conducir", "confiar",
  "considerar", "contestar", "continuar", "controlar", "convencer", "cruzar",
  "cuidar", "curar", "dejar", "depender", "desarrollar", "desear", "dirigir",
  "disfrutar", "durar", "echar", "enfadar", "engañar", "entrar", "entregar",
  "enviar", "esperar", "evitar", "existir", "expresar", "faltar", "felicitar",
  "fijar", "formar", "funcionar", "guardar", "gustar", "importar", "indicar",
  "iniciar", "insistir", "intentar", "interesar", "invitar", "lavar",
  "limpiar", "llamar", "llegar", "llenar", "llevar", "llorar", "lograr",
  "mandar", "marchar", "mejorar", "meter", "molestar", "necesitar", "notar",
  "ocupar", "ocurrir", "odiar", "ofrecer", "organizar", "pagar", "parar",
  "parecer", "pasar", "pelear", "permitir", "pertenecer", "plantar",
  "practicar", "preocupar", "preparar", "presentar", "prestar", "producir",
  "prohibir", "quedar", "quejar", "quitar", "realizar", "recibir", "recoger",
  "reconocer", "recorrer", "regalar", "regresar", "rellenar", "representar",
  "resultar", "retirar", "reunir", "revisar", "robar", "sacar", "sonreír",
  "suceder", "sufrir", "sujetar", "superar", "tapar", "tardar", "terminar",
  "tomar", "trabajar", "traducir", "tratar", "usar", "utilizar", "vender",
  "viajar", "vigilar", "visitar", "votar", "acabar", "acompañar", "acordar",
  "actuar", "admirar", "adornar", "afirmar", "agarrar", "agitar", "agotar",
  "alegrar", "aliviar", "alzar", "amenazar", "animar", "anunciar", "apartar",
  "apoderar", "aprovechar", "apuntar", "arrancar", "arrojar", "asegurar",
  "asomar", "atar", "atrapar", "aumentar", "avisar", "bastar", "besar",
  "borrar", "brincar", "burlar", "calmar", "cavar", "ceder", "clavar",
  "cobrar", "coincidir", "colaborar", "comentar", "cometer", "comprar",
  "conceder", "conservar", "consultar", "contemplar", "contener", "conversar",
  "corresponder", "crecer", "criticar", "cubrir", "culpar", "chocar",
  "debatir", "decorar", "dedicar", "defender", "definir", "demostrar",
  "derribar", "desatar", "desviar", "detener", "devolver", "difundir",
  "disculpar", "discutir", "disimular", "disparar", "distinguir", "dividir",
  "dudar", "elevar", "eliminar", "emocionar", "encargar", "enfrentar",
  "enredar", "ensayar", "entretener", "envidiar", "escapar", "esconder",
  "esforzar", "espantar", "estirar", "estropear", "examinar", "exigir",
  "explotar", "extender", "fabricar", "fallar", "fingir", "flotar", "frenar",
  "girar", "gobernar", "golpear", "gozar", "hallar", "heredar", "herir",
  "hundir", "ignorar", "impedir", "impresionar", "incluir", "informar",
  "insultar", "interrumpir", "juntar", "jurar", "justificar", "librar",
  "limitar", "mantener", "marcar", "masticar", "merecer", "mezclar", "morder",
  "mover", "nombrar", "notar", "obedecer", "observar", "obtener", "ofender",
  "opinar", "ordenar", "pertenecer", "pescar", "picar", "pisar", "poblar",
  "poseer", "predecir", "premiar", "prender", "presumir", "prever", "probar",
  "proclamar", "prometer", "proteger", "protestar", "provocar", "publicar",
  "quemar", "rascar", "rechazar", "recomendar", "recorrer", "recuperar",
  "reflejar", "reforzar", "regar", "reinar", "relacionar", "remar", "rendir",
  "renunciar", "reparar", "repartir", "reprochar", "rescatar", "reservar",
  "resistir", "respetar", "responder", "retrasar", "reunir", "rodear",
  "rogar", "saludar", "salvar", "sembrar", "sentar", "separar", "señalar",
  "silbar", "situar", "sobrar", "soltar", "solucionar", "sonar", "soplar",
  "sorprender", "sospechar", "sostener", "subrayar", "sugerir", "sumergir",
  "suplicar", "surgir", "suspender", "sustituir", "temer", "tender", "tirar",
  "titubear", "tolerar", "torcer", "trasladar", "trepar", "tropezar",
  "unir", "usar", "vaciar", "valorar", "variar", "vencer", "vestir", "vigilar",
  "volcar", "zarpar",
  "abandonar", "abrir", "acabar", "acampar", "acechar", "acelerar",
  "aceptar", "acercar", "acertar", "acompañar", "actuar", "adelantar",
  "adentrar", "adornar", "advertir", "afinar", "aflojar", "agarrar",
  "aguantar", "ahorrar", "alegrar", "alejar", "alisar", "almorzar",
  "alumbrar", "amanecer", "amar", "andar", "anidar", "animar", "anochecer",
  "añadir", "apagar", "aparecer", "aplaudir", "aprender", "apretar",
  "aprovechar", "apuntar", "arder", "arrastrar", "arreglar", "arriesgar",
  "arrugar", "asar", "asomar", "asustar", "atacar", "atar", "atardecer",
  "atornillar", "atrapar", "atrasar", "atravesar", "atrever", "aullar",
  "avisar", "ayudar", "bailar", "bajar", "balar", "balbucear", "barrer",
  "batir", "beber", "borrar", "bostezar", "brillar", "brotar", "bucear",
  "buscar", "cacarear", "caer", "calcular", "calentar", "callar", "calmar",
  "cambiar", "caminar", "cantar", "cargar", "cavar", "cazar", "celebrar",
  "cenar", "cerrar", "charlar", "chirriar", "clavar", "cobrar", "cocinar",
  "coger", "colaborar", "colocar", "colorear", "comenzar", "comer",
  "comparar", "compartir", "competir", "comprar", "comprender", "conducir",
  "confesar", "congelar", "conjurar", "conocer", "conseguir", "consolar",
  "construir", "contar", "contestar", "continuar", "conversar",
  "convertir", "copiar", "correr", "cortar", "cosechar", "coser", "costar",
  "crear", "crecer", "crujir", "cruzar", "cuidar", "cultivar", "cumplir",
  "curar", "decidir", "declamar", "decorar", "defender", "deletrear",
  "derretir", "derrotar", "derrumbar", "desaparecer", "desatar",
  "desayunar", "descansar", "describir", "descubrir", "deslizar",
  "desmontar", "desobedecer", "despedir", "despejar", "despertar",
  "desplomar", "devolver", "dibujar", "discutir", "disfrazar",
  "distinguir", "dividir", "doblar", "doler", "dormir", "dormitar",
  "dudar", "durar", "elegir", "empaquetar", "empatar", "empezar",
  "emprender", "empujar", "encantar", "encargar", "encender", "enchufar",
  "encoger", "encontrar", "enfadar", "enfriar", "engañar", "enredar",
  "ensayar", "enseñar", "ensuciar", "entender", "entrar", "entregar",
  "entrenar", "envejecer", "enviar", "envolver", "escalar", "escampar",
  "escapar", "escoger", "esconder", "escribir", "escuchar", "esperar",
  "espiar", "estallar", "estirar", "estornudar", "estremecer", "estropear",
  "estudiar", "exclamar", "explicar", "explorar", "fallar", "faltar",
  "festejar", "filmar", "flotar", "fotografiar", "fracasar", "fregar",
  "freír", "frenar", "funcionar", "galopar", "ganar", "gastar", "girar",
  "golpear", "grabar", "granizar", "gritar", "guardar", "gustar", "hablar",
  "hallar", "hechizar", "hervir", "huir", "hundir", "iluminar", "imaginar",
  "imprimir", "intentar", "intercambiar", "introducir", "inventar",
  "investigar", "invitar", "invocar", "jugar", "juntar", "jurar", "ladrar",
  "lanzar", "lavar", "leer", "levantar", "limpiar", "llamar", "llegar",
  "llenar", "llevar", "llorar", "llover", "lograr", "luchar", "madrugar",
  "maldecir", "mandar", "manejar", "marear", "masticar", "maullar",
  "medir", "mentir", "merendar", "meter", "mezclar", "mirar", "mojar",
  "molestar", "montar", "morder", "morir", "mugir", "multiplicar",
  "murmurar", "nacer", "nadar", "narrar", "naufragar", "navegar",
  "necesitar", "nevar", "obedecer", "observar", "ocultar", "odiar", "oír",
  "oler", "olvidar", "operar", "opinar", "ordenar", "ordeñar", "pagar",
  "parar", "participar", "partir", "pasar", "pasear", "pegar", "pelar",
  "pelear", "pensar", "perder", "perdonar", "perseguir", "pesar", "pescar",
  "piar", "picar", "pintar", "planchar", "planear", "plantar", "podar",
  "practicar", "preferir", "preguntar", "prestar", "probar", "programar",
  "prometer", "pronunciar", "proteger", "publicar", "quemar", "querer",
  "quitar", "rechazar", "recibir", "recitar", "recoger", "recolectar",
  "reconocer", "recordar", "recortar", "reflejar", "regalar", "regar",
  "regatear", "regresar", "reír", "relampaguear", "relatar", "relinchar",
  "relucir", "remar", "renacer", "rendir", "reparar", "repartir",
  "repasar", "representar", "reptar", "resbalar", "rescatar", "resistir",
  "resolver", "resonar", "respirar", "resplandecer", "responder", "restar",
  "resumir", "retumbar", "reunir", "revelar", "rimar", "rodar", "rodear",
  "rogar", "romper", "rugir", "saber", "saborear", "sacar", "salir",
  "saltar", "saludar", "salvar", "sanar", "secar", "seguir", "sembrar",
  "señalar", "separar", "servir", "silbar", "sobrar", "sobrevivir",
  "sollozar", "soltar", "sombrear", "sonar", "sonreír", "soñar", "soplar",
  "soportar", "sorprender", "sospechar", "subir", "subrayar", "sumar",
  "suplicar", "surgir", "suspirar", "susurrar", "tambalear", "tardar",
  "tartamudear", "teclear", "temblar", "temer", "terminar", "tirar",
  "tiritar", "tocar", "torcer", "toser", "trabajar", "traducir", "traer",
  "tragar", "traicionar", "tramar", "tranquilizar", "transformar",
  "trepar", "tronar", "tropezar", "trotar", "urdir", "usar", "utilizar",
  "vaciar", "vacilar", "vacunar", "vencer", "vendar", "vender", "ventear",
  "ver", "viajar", "vigilar", "visitar", "vivir", "volar", "zumbar",
];

// Palabras que no cambian: determinantes, pronombres, adverbios, nexos, números.
export const INVARIABLES = [
  "a", "abajo", "acá", "acaso", "además", "adentro", "adiós", "adónde",
  "afortunadamente", "afuera", "ah", "ahí", "ahora", "al", "algo",
  "alguien", "algún", "alguna", "algunas", "alguno", "algunos", "allá",
  "allí", "alrededor", "ambas", "ambos", "ante", "anteayer", "antes",
  "apenas", "aquel", "aquella", "aquellas", "aquello", "aquellos", "aquí",
  "arriba", "asimismo", "aun", "aún", "aunque", "ay", "ayer", "bah",
  "bajo", "bastante", "bastantes", "bien", "cada", "cambio", "casi",
  "catorce", "cerca", "cien", "ciento", "cinco", "cincuenta", "claro",
  "como", "cómo", "con", "conmigo", "consigo", "contigo", "contra", "cual",
  "cuál", "cuales", "cuáles", "cualquier", "cualquiera", "cuando",
  "cuándo", "cuánta", "cuántas", "cuanto", "cuánto", "cuántos", "cuarenta",
  "cuarta", "cuarto", "cuatro", "cuya", "cuyas", "cuyo", "cuyos", "de",
  "debajo", "décima", "décimo", "definitivamente", "del", "delante",
  "demasiada", "demasiadas", "demasiado", "demasiados", "dentro", "desde",
  "desgraciadamente", "después", "detrás", "diecinueve", "dieciocho",
  "dieciséis", "diecisiete", "diez", "doce", "donde", "dónde", "dos",
  "doscientos", "durante", "e", "eh", "el", "él", "ella", "ellas", "ellos",
  "embargo", "en", "encima", "enfrente", "enseguida", "entonces", "entre",
  "entretanto", "esa", "esas", "ese", "eso", "esos", "esta", "estas",
  "este", "esto", "estos", "finalmente", "fuera", "gracias", "hacia",
  "hasta", "hola", "hoy", "incluso", "inmediatamente", "jamás", "junto",
  "la", "lado", "las", "le", "lejos", "lentamente", "les", "lo", "los",
  "luego", "mal", "mañana", "mas", "más", "me", "mejor", "menos", "mi",
  "mí", "mía", "mías", "mientras", "mil", "millón", "millones", "mío",
  "míos", "mis", "misma", "mismas", "mismo", "mismos", "mucha", "muchas",
  "mucho", "muchos", "muy", "nada", "nadie", "ni", "ningún", "ninguna",
  "ninguno", "ningunos", "no", "nos", "nosotras", "nosotros", "novena",
  "noveno", "noventa", "nuestra", "nuestras", "nuestro", "nuestros",
  "nueve", "nunca", "o", "ochenta", "ocho", "octava", "octavo", "oh",
  "ojalá", "once", "os", "otra", "otras", "otro", "otros", "para", "peor",
  "perdón", "pero", "poca", "pocas", "poco", "pocos", "por", "porque",
  "primera", "primero", "pronto", "propia", "propio", "pues", "que", "qué",
  "quien", "quién", "quienes", "quiénes", "quince", "quinientos", "quinta",
  "quinto", "quizá", "quizás", "rápidamente", "realidad", "repentinamente",
  "se", "seguida", "según", "segunda", "segundo", "seis", "séptima",
  "séptimo", "sesenta", "setenta", "sexta", "sexto", "si", "sí", "siempre",
  "siete", "sin", "sino", "sobre", "solamente", "solo", "sólo", "su",
  "súbitamente", "sus", "suya", "suyas", "suyo", "suyos", "tal", "tales",
  "también", "tampoco", "tanta", "tantas", "tanto", "tantos", "tarde",
  "te", "temprano", "tercera", "tercero", "ti", "toda", "todas", "todo",
  "todos", "tras", "través", "trece", "treinta", "tres", "trescientos",
  "tu", "tú", "tus", "tuya", "tuyas", "tuyo", "tuyos", "u", "uf", "un",
  "una", "unas", "uno", "unos", "usted", "ustedes", "vale", "varias",
  "varios", "veces", "veinte", "veintidós", "veintitrés", "veintiuno",
  "vez", "vosotras", "vosotros", "vuestra", "vuestras", "vuestro",
  "vuestros", "y", "ya", "yo",
];

// Nombres propios reales: no se piden fichas por ellos.
export const PROPIOS = [
  "abril", "África", "agosto", "Alemania", "Almería", "Alpes", "Amazonas",
  "América", "Andalucía", "Antártida", "Aragón", "Argentina", "Ártico",
  "Asia", "Asturias", "Atlántico", "Australia", "Baleares", "Barcelona",
  "Bilbao", "Bolivia", "Brasil", "Cádiz", "Canadá", "Canarias",
  "Cantabria", "Cantábrico", "Carnaval", "Cataluña", "Chile", "China",
  "Colombia", "Córdoba", "Cuba", "diciembre", "domingo", "Duero", "Ebro",
  "Ecuador", "Egipto", "enero", "España", "Estados", "Europa", "Everest",
  "Extremadura", "febrero", "Francia", "Galicia", "Google", "Granada",
  "Grecia", "Guadalquivir", "Halloween", "Huelva", "India", "Índico",
  "Inglaterra", "Internet", "Irlanda", "Italia", "Jaén", "Japón", "jueves",
  "julio", "junio", "Júpiter", "Luna", "lunes", "Madrid", "Málaga",
  "Marruecos", "Marte", "martes", "marzo", "mayo", "Mediterráneo",
  "Mercurio", "México", "miércoles", "Murcia", "Navarra", "Navidad",
  "Neptuno", "Nilo", "noviembre", "Oceanía", "octubre", "Oviedo",
  "Pacífico", "Paraguay", "Perú", "Pirineos", "Plutón", "Portugal",
  "Reyes", "Rusia", "sábado", "Sáhara", "Salamanca", "Santa", "Santander",
  "Saturno", "Semana", "septiembre", "setiembre", "Sevilla", "Sol", "Tajo",
  "Tierra", "Toledo", "Unidos", "Urano", "Uruguay", "Valencia",
  "Valladolid", "Venezuela", "Venus", "viernes", "WhatsApp", "YouTube",
  "Zaragoza",
];
